/* Masala Dabba — norske regionsammendrag. Den engelske utgaven ligger i COURSE inne i appen.
   Nøkler som mangler her, faller tilbake på engelsk, så en halvferdig fil ødelegger ingenting.
   dishes[] er [navn, vegetarisk], og retter, krydderblandinger og stedsnavn beholder sin egen form. */
window.COURSE_NO = {
 'IN-HIM':{name:'Kashmir og Himalaya', capital:'Srinagar', intro:"Safrankrokusen blomstrer på karewa-terrassene ved Pampore, mens kortkornet ris bærer sausene i Kashmir-dalen. Muslimske kokker og pandit-kokker bruker de samme rettnavnene, men følger ulike regler for løk og hvitløk. En bryllupswazwan serveres rett for rett på et kobberfat og ender med gushtaba. Utenfor dalen stiger terrenget gjennom Himachal og Uttarakhand mot Ladakh. Hirse, bygg og saltet te kinnet med smør forteller da om andre vekster, klima og gamle forbindelser over fjellene.",
   landmark:{name:'Dal-sjøen og Mughal-hagene', desc:'Shikara-båter på en innsjø som mughalene dro nordover til for å slippe unna varmen, med terrassehagene Jahangir anla ved Shalimar i 1619 i skråningen over.'},
   spices:[['Safran (kong)'],['Kashmiri-chili'],['Ver masala'],['Fennikel (saunf)'],['Tørket ingefær (sonth)'],['Praan (sjalottløk)']],
   plate:'Ris, en skål rogan josh, haak-grønnsaker ved siden av, og kahwa etterpå med en høvlet mandel flytende i koppen.',
   dishes:[['Rogan josh',0],['Yakhni',0],['Dum aloo',1],['Haak',1],['Modur pulav',1],['Tabak maaz',0],['Kahwa',1],['Nadru yakhni',1]],
   lessons:['Safran, ver og chilien som farger','Ris, wazwan og den syvende retten','Rogan josh, yakhni og dalens to kjøkken','Mughaler i fjellet: hvorfor dalen spiser som den gjør']},
 'IN-PUN':{name:'Punjab og Delhi', capital:'Amritsar', intro:"En nystekt roti kommer på bordet før den forrige er spist opp. På slettene i Punjab preger hvete og meieriprodukter hverdagsmaten, mens tandooren gir brødet blemmer i overflaten og kjøttet røyksmak. Regionen samler Punjab, Haryana, Chandigarh og Delhi. Her hører vinterens sennepsblader og langtidskokt dal hjemme, sammen med restaurantene flyktninger åpnet etter delingen i 1947. I Amritsar byr langaren ved Det gylne tempel på en annen form for felles måltid: Folk sitter sammen og får den samme maten.",
   landmark:{name:'Det gylne tempel, Amritsar', desc:'Tempelet har stått i sitt eget basseng siden 1604, og Ranjit Singh lot det kle i gull to hundre år senere. Langar-kjøkkenet der metter omkring hundre tusen mennesker om dagen, gratis, og det er det største kjøkkenet i verden som går uten stans.'},
   spices:[['Garam masala'],['Spisskummen (jeera)'],['Korianderfrø'],['Ajwain'],['Kasuri methi (tørket bukkehornkløver)'],['Amchur (tørket mango)']],
   plate:'Sarson da saag med en makki-roti, en klump hvitt smør som smelter ned i den, og et glass saltet lassi.',
   dishes:[['Sarson da saag',1],['Makki di roti',1],['Butter chicken',0],['Tandoorikylling',0],['Dal makhani',1],['Rajma-chawal',1],['Chole bhature',1],['Amritsari-fisk',0],['Lassi',1]],
   lessons:['Garam masala og tandooren','Hvete, meieri og den punjabiske tallerkenen','Saag, dal makhani og tandooribordet','1947: flyktningkjøkken og butter chicken']},
 'IN-RAJ':{name:'Rajasthan', capital:'Jaipur', intro:"I Rajasthan formet vannhøsting, husdyrhold og jordbruk i tørre områder et forråd av perlehirse, belgfrukter, ghee, yoghurt og råvarer tørket for senere bruk. Mathania-chili farger laal maas, mens ker-bær og sangri-belger gjør ørkenplanter til en verdsatt rett. Rajputenes hofftradisjoner, marwariske handelsnettverk og jainistiske matregler la ulike historier til det samme regionale bordet. Indira Gandhi-kanalen endret senere jordbruket i deler av nordvest, men eldre retter beholdt sin plass i minne og gjestfrihet.",
   landmark:{name:'Mehrangarh, Jodhpur', desc:'En festning på en klippe 120 meter over den blå byen, påbegynt i 1459 og aldri inntatt. Kjøkkenene der metter en garnison som ikke kunne regne med regn.'},
   spices:[['Mathania-chili'],['Koriander (dhania)'],['Asafoetida (hing)'],['Kachri'],['Nellik'],['Panchkuta']],
   plate:'Dal, en bati brutt opp og druknet i ghee, churma ved siden av, og laal maas hvis huset spiser kjøtt.',
   dishes:[['Laal maas',0],['Ker sangri',1],['Gatte ki sabzi',1],['Dal bati churma',1],['Pyaaz kachori',1],['Bajre ki roti',1],['Ghevar',1],['Mawa kachori',1]],
   lessons:['Å lage mat uten vann: chili, ghee og yoghurt','Bajra, bati og det ørkenen gir','Laal maas, ker sangri og gatte','Rajputer og marwarier: to kjøkken, én ørken']},
 'IN-AWA':{name:'Awadh', capital:'Lucknow', intro:"Hoffmaten fra Lucknow bruker rose, kewra, safran og hele krydder med stor varsomhet. Under dum bremser en deigforseglet gryte tapet av væske og duft mens ris, kjøtt eller grønnsaker blir ferdige over svak varme. Galouti og kakori søker ulik konsistens, mens nihari får fylde av timer i gryta. Nawabenes støtte utviklet teknikkene, og spredningen etter britenes anneksjon av Awadh i 1856 førte maten videre til gateboder, hjem, bryllup og eksilhoffet i Metiabruz.",
   landmark:{name:'Bara Imambara, Lucknow', desc:'Bygd i 1784 som nødsarbeid. Nawaben betalte byen for å bygge om dagen og, sier historien, for å rive om natten. Hovedsalen har tak uten en eneste søyle.'},
   spices:[['Kewra (skruepalme)'],['Rosevann'],['Muskatblomme (javitri)'],['Grønn kardemomme'],['Safran'],['Potli masala']],
   plate:'Galouti-kebab på en varm sheermal, en skvett lime, og biryani som først kommer ut når forseglingen brytes ved bordet.',
   dishes:[['Galouti kebab',0],['Awadhi-biryani',0],['Nihari',0],['Kakori kebab',0],['Sheermal',1],['Shahi tukda',1],['Banarasi chaat',1],['Malai makhan',1]],
   lessons:['Attar og duft: et parfymert kjøkken','Dum: ris, brød og den forseglede gryta','Kebab, biryani og nihari','Nawabene, 1856, og hvor kokkene tok veien']},
 'IN-GUJ':{name:'Gujarat', capital:'Ahmedabad', intro:"Gujarat balanserer søtt, surt og sterkt i thalier, brød, farsan og retter av sesongens grønnsaker. Havner, jainistisk og vaishnavisk praksis, tørre landskap og variasjon mellom hjem har alle formet maten.",
   landmark:{name:'Rani ki Vav, Patan', desc:'En trappebrønn fra 1000-tallet fordelt på sju nivåer, der vannhåndtering møter formen og skulpturene i et omvendt tempel.'},
   spices:[['Dhana-jeera'],['Sennepsfrø'],['Asafoetida (hing)'],['Sesam (til)'],['Jaggery (gud)'],['Kokum']],
   plate:'En thali: to grønnsaker, dal, kadhi, rotli, ris, pickles og noe fritert som kommer sist og varmt.',
   dishes:[['Dhokla',1],['Undhiyu',1],['Khandvi',1],['Thepla',1],['Handvo',1],['Gujarati kadhi',1],['Shrikhand',1],['Fafda-jalebi',1]],
   lessons:['Søtt, surt og sterkt, med dhana-jeera i bunnen','Thalien som system','Dhokla, undhiyu og det dampede kjøkkenet','Havner, jainer og parsernes landgang ved Sanjan']},
  'IN-MAH':{name:'Maharashtra', capital:'Mumbai', intro:"Vest-Ghatene, Konkan-kysten og Dekkan-platået gir ulike balansepunkt mellom ris, hirse, kokos, peanøtt og syre. I Mumbai møter koli- og østindisk-katolske tradisjoner maten til parsere, iranere og mange senere migranter.",
   landmark:{name:'Gateway of India, Mumbai', desc:'En basaltbue som stod ferdig i 1924 for å ta imot visekonger, og som i 1948 så de siste britiske troppene marsjere ut gjennom seg.'},
   spices:[['Goda masala'],['Dagad phool (steinblomst)'],['Kala masala'],['Peanøtt'],['Karriblad'],['Kokum']],
   plate:'Misal med pav til å tørke opp med, rå løk og lime ved siden av, og den tynne røde rassaen helt over til slutt.',
   dishes:[['Misal pav',1],['Vada pav',1],['Puran poli',1],['Pav bhaji',1],['Geitekjøtt fra Kolhapur',0],['Bombil fry',0],['Modak',1],['Kanda poha',1],['Sali boti',0]],
   lessons:['Goda masala og steinblomsten','Bhakri på platået, ris ved kysten','Misal, vada pav og den røde rassaen fra Kolhapur','Bombay: spinneriene, iranerne og maten til nykommerne']},
 'IN-KON':{name:'Goa og Konkan', capital:'Panaji', intro:"Kjøkkenene i Goa samler råvarer fra Konkan, ulike hinduistiske og katolske tradisjoner og de langvarige følgene av portugisisk styre og sjøhandel. Kokos, ris, fisk, kokum og lokal eddik møter vekster fraktet over havet, blant annet cashew og amerikansk chili.",
   landmark:{name:'Bom Jesus-basilikaen, Gamle Goa', desc:'Kirken er bygd i laterittstein og kalk og ble innviet i 1605, og den rommer Frans Xaviers legeme. Byen rundt ble en gang kalt Østens Roma og er nå stort sett skog.'},
   spices:[['Recheado masala'],['Xacuti masala'],['Kashmiri-chili'],['Palmeeddik'],['Ristet kokos'],['Tamarind']],
   plate:'Et mulig kystmåltid setter fiskekarri sammen med forkokt ris, stekt fisk eller grønnsaker og et avkjølende glass solkadhi.',
   dishes:[['Vindaloo',0],['Xacuti',0],['Sorpotel',0],['Cafreal',0],['Balchão med reker',0],['Fiskekarri med ris',0],['Sannas',1],['Bebinca',1]],
   lessons:['Eddik, chili og recheado-masalaen','Ukda-ris og den daglige fiskekarrien','Vindaloo, xacuti og sorpotel','1510: hva Portugal brakte, og hva det tok']},
 'IN-CEN':{name:'Det midtre Dekkan', capital:'Bhopal', intro:"Det sentrale India samler hveten og pohaen i Malwa, rismaten i Chhattisgarh, hofftradisjonene i Bhopal og de varierte adivasi-matveiene i Bastar. Åker, by, ukemarked og sesongens skogsprodukter former alle det regionale bordet.",
   landmark:{name:'Den store stupaen i Sanchi', desc:'En teglkjerne fra Ashokas tid som senere ble utvidet og kledd i stein, med rikt utskårne portaler fra senere dynastier. UNESCO kaller Sanchi et av de eldste bevarte buddhistiske helligstedene.'},
   spices:[['Valmuefrø (khus khus)'],['Bhopali garam masala'],['Chironji'],['Mahua'],['Svart kardemomme'],['Tamarind']],
   plate:'En kjent frokost i Indore setter myk poha sammen med sev, lime og jiravan, noen ganger med jalebi og te ved siden av.',
   dishes:[['Indori poha',1],['Bhutte ka kees',1],['Dal bafla',1],['Bhopali korma',0],['Bhopali rogan josh',0],['Chironji ki barfi',1],['Chila',1],['Mahua laddu',1]],
   lessons:['Valmuefrø, chironji og råvarene i skogen','Hvete i Malwa, ris i Chhattisgarh','Poha, bafla og den bhopaliske kormaen','Ashoka, begumene og kjøkkenene i Bastar']},
 'IN-BEN':{name:'Bengal og øst', capital:'Kolkata', intro:"Bengal, Bihar, Jharkhand og Odisha samler ris fra elveland, hvete og sattu, sennep, fisk, tempelmat og varierte dyrkede og sankede råvarer. Tempering med hele krydder, våte pastaer og formelle måltidsrekkefølger er viktige tråder, ikke regler for hvert bord.",
   landmark:{name:'Howrah-brua, Kolkata', desc:'En utkragerbru av stål, tatt i bruk i 1943 og satt sammen med nagler, som knytter Kolkata og Howrah sammen over Hooghly.'},
   spices:[['Panch phoron'],['Sennepsolje'],['Svartkarve (kalonji)'],['Valmuefrø (posto)'],['Radhuni'],['Kasundi (sennepssaus)']],
   plate:'Et formelt måltid kan gå fra bitre grønnsaker via ris og dal til fisk eller kjøtt, chutney og søtt, med rekkefølge etter husholdning og anledning.',
   dishes:[['Shorshe ilish',0],['Macher jhol',0],['Kosha mangsho',0],['Shukto',1],['Luchi-alur dom',1],['Litti chokha',1],['Chhena poda',1],['Mishti doi',1],['Rasgulla',1]],
   lessons:['Panch phoron, sennep og regelen om hele krydder','Ris og rekkefølgen i et bengalsk måltid','Ilish, kosha mangsho og søtsakene','Chhana, portugiserne og en nawab i eksil']},
 'IN-NEA':{name:'Nordøst-India', capital:'Guwahati', intro:"Åtte delstater og mange ulike kjøkken møtes rundt ris, urter, chili, bambusskudd og gjæret mat. Sennepsolje og khar fra Assam, røykt kjøtt fra Nagaland, fiskegjæring fra Manipur og Himalaya-maten i Sikkim viser bredden.",
   landmark:{name:'De levende rotbruene i Meghalaya', desc:'Røtter av gummifiken som khasi-samfunn leder og vedlikeholder som forbindelser mellom landsbyer, gårder og markeder i Meghalaya.'},
   spices:[['Bhut jolokia'],['Bambusskudd'],['Axone (gjæret soya)'],['Khar (lut)'],['Svart sesam'],['Kharoli (sennepspasta)']],
   plate:'Ris, en skål sur tenga, en pitika av most potet med sennepsolje, og en chili på kanten av tallerkenen.',
   dishes:[['Masor tenga',0],['Khar',1],['Røkt svin med bambusskudd',0],['Axone med svinekjøtt',0],['Eromba',0],['Jadoh',0],['Aloo pitika',1],['Thukpa',0]],
   lessons:['Gjæring, lut, røyk og krydder','Ris, klebrig ris og den dampede gryta','Tenga, khar og det røykte svinekjøttet','Ahomene, teen og forbindelser i endring']},
 'IN-KAR':{name:'Karnataka', capital:'Bengaluru', intro:"Karnataka samler fingerhirse og sorghum i mange innlandsdistrikter, ris og kokos langs kysten, matkulturene i Kodagu og tempel- og restauranttradisjonene i Udupi. Byadgichili, kaffe og skiftende vannsystemer knytter gårder, markeder og kjøkken sammen.",
   landmark:{name:'Mysore-palasset', desc:'Henry Irwins indo-sarasenske palass stod ferdig i 1912 etter at det forrige brant, og lyses opp på utvalgte kvelder og under dasara.'},
   spices:[['Byadgi-chili'],['Bisi bele bath-pulver'],['Kokos'],['Karriblad'],['Kachampuli'],['Svart kardemomme']],
   plate:'Ragi mudde spist i små biter med en tynn saaru av grønne blad, med krydret kjernemelk som ett mulig tilbehør.',
   dishes:[['Bisi bele bath',1],['Mysore masala dosa',1],['Ragi mudde',1],['Neer dosa',1],['Pandi curry',0],['Kundapur koli saaru',0],['Mysore pak',1],['Dharwad peda',1]],
   lessons:['Byadgi: chilien som dyrkes for fargen','Ragi, ris og røren ved kysten','Bisi bele bath, dosa og pandi curry','Vijayanagara, wodeyarene og sju kaffebønner']},
 'IN-AND':{name:'Andhra og Telangana', capital:'Hyderabad', intro:"Guntur-chili, tamarind og gongura former mange av de sterke og sure smakene i telugutalende kjøkken. Hyderabad tilfører biryani, haleem og nøttejevnet saus fra en flerspråklig hoff- og handelsby på Dekkan.",
   landmark:{name:'Charminar, Hyderabad', desc:'Fire minareter over fire buer, bestilt i 1591 mens den qutbshahiske hovedstaden Hyderabad tok form rundt monumentet.'},
   spices:[['Guntur-chili'],['Gongura'],['Tamarind (chintapandu)'],['Sennepsfrø'],['Bukkehornkløver (menthulu)'],['Bagara masala']],
   plate:'Ris, en skje ghee, pappu, gongura-pachadi og en liten porsjon kjøleskapslagret avakaya.',
   dishes:[['Hyderabadi-biryani',0],['Gongura mamsam',0],['Avakaya',1],['Pesarattu',1],['Pulihora',1],['Haleem',0],['Bagara baingan',1],['Qubani ka meetha',1]],
   lessons:['Guntur-styrke og gongura-syre','Ris, pappu og mangopickles','Biryani, haleem og gongura-lammet','Qutbshahier, nizamer og en hovedstad på Dekkan']},
 'IN-TAM':{name:'Tamil Nadu', capital:'Chennai', intro:"Pepper, ris, belgfrukter, tamarind og sesam knytter tamilsk mat til en lang historie med jordbruk og handel. Chettinad bidrar med én særpreget tradisjon for ristet krydder blant delstatens mange kjøkken.",
   landmark:{name:'Brihadisvara-tempelet, Thanjavur', desc:'Et levende cholatempel innviet av Rajaraja I i 1009–1010, med et granitttårn som stiger nesten 60 meter.'},
   spices:[['Svart pepper'],['Kalpasi (steinblomst)'],['Stjerneanis'],['Marathi mokku'],['Sambar podi'],['Tamarind']],
   plate:'Et bananblad med ris, grønnsaker, sambar, rasam, syrnet melk og små tilbehør ordnet etter verten og anledningen.',
   dishes:[['Idli',1],['Dosa',1],['Sambar',1],['Rasam',1],['Chettinad-kylling',0],['Meen kuzhambu',0],['Kothu parotta',0],['Filterkaffe',1],['Payasam',1]],
   lessons:['Pepper, kalpasi og Chettinad-ristingen','Gjæret røre og rekkefølgen på bananbladet','Idli, sambar og Chettinad-kjøkkenet','Cholaer, romere og chettiarene som dro østover']},
 'IN-KER':{name:'Kerala', capital:'Kochi', intro:"Monsunskråningene i Kerala gir gode forhold for pepper og kardemomme, mens kysten lenge har vært del av handelen over Indiahavet. Ris, kokos, fisk, brød og kjøttretter gjenspeiler ulike regionale og sosiale historier.",
   landmark:{name:'De kinesiske fiskenettene i Fort Kochi', desc:'Landfaste vippenett som senkes og heves av fire mann og en rad med stein, og som etter sigende kom med handelsmenn fra Kublai Khans hoff.'},
   spices:[['Svart pepper'],['Kardemomme'],['Kanel'],['Karriblad'],['Kokosolje'],['Kudampuli']],
   plate:'Rød mattaris med en av Keralas mange fiskekarrier, en grønnsaksthoran, pickles og et annet tilbehør valgt etter husholdning og anledning.',
   dishes:[['Meen curry',0],['Appam med stuing',0],['Puttu-kadala',1],['Keralaparotta',1],['Stekt oksekjøtt (beef fry)',0],['Avial',1],['Karimeen pollichathu',0],['Thalassery-biryani',0],['Sadya',1]],
   lessons:['Pepper, kardemomme og krydderkysten','Ris i fire former, kokos i fire til','Meen curry, appam og sadya','Fra Muziris til Vasco da Gama: handelen som formet kjøkkenet']}
};
