/* Masala Dabba — norske regionsammendrag. Den engelske utgaven ligger i COURSE inne i appen.
   Nøkler som mangler her, faller tilbake på engelsk, så en halvferdig fil ødelegger ingenting.
   dishes[] er [navn, vegetarisk], og retter, krydderblandinger og stedsnavn beholder sin egen form. */
window.COURSE_NO = {
 'IN-HIM':{name:'Kashmir og Himalaya', capital:'Srinagar', intro:"Safran vokser på Pampore-platået, risen er kort og klebrig, og de to store kjøkkenene i dalen er uenige om løk. Over dem klatrer Himalaya opp mot Ladakh, der smørte og bygg tar over for ris og chili.",
   landmark:{name:'Dal-sjøen og Mughal-hagene', desc:'Shikara-båter på en innsjø mughalene dro nordover for å slippe unna varmen, terrassert av hagene Jahangir anla ved Shalimar i 1619.'},
   plate:'Ris, en skål rogan josh, haak-grønnsaker ved siden av, og kahwa etterpå med en høvlet mandel flytende i koppen.',
   dishes:[['Rogan josh',0],['Yakhni',0],['Dum aloo',1],['Haak',1],['Modur pulav',1],['Tabak maaz',0],['Kahwa',1],['Nadru yakhni',1]],
   lessons:['Safran, ver og chilien som farger','Ris, wazwan og den syvende retten','Rogan josh, yakhni og dalens to kjøkken','Mughaler i fjellet: hvorfor dalen spiser som den gjør']},
 'IN-PUN':{name:'Punjab og Delhi', capital:'Amritsar', intro:"Fem elver, hvete i stedet for ris, og en leirovn som forandret hvordan verden tror indisk mat smaker. Delhi ligger i den østre enden av den samme sletta og lager maten delingen i 1947 førte dit.",
   landmark:{name:'Det gylne tempel, Amritsar', desc:'Forgylt og stående i sitt eget bassend siden 1604. Langar-kjøkkenet der metter omkring hundre tusen mennesker om dagen, gratis, og er det største kjøkkenet i verden som går kontinuerlig.'},
   plate:'Sarson da saag med en makki-roti, en klump hvitt smør som smelter ned i den, og et glass saltet lassi.',
   dishes:[['Sarson da saag',1],['Makki di roti',1],['Butter chicken',0],['Tandoori chicken',0],['Dal makhani',1],['Rajma-chawal',1],['Chole bhature',1],['Amritsari fish',0],['Lassi',1]],
   lessons:['Garam masala og tandooren','Hvete, meieri og den punjabiske tallerkenen','Saag, dal makhani og tandooribordet','1947: flyktningkjøkkenene som fant opp butter chicken']},
 'IN-RAJ':{name:'Rajasthan', capital:'Jaipur', intro:"Et kjøkken bygd der vannet var mangelvare og ghee ikke var det. Kjøtt kokes i yoghurt og chili, grønnsakene er tørkede bønner og bær sanket fra ørkenkratt, og brødet er hirse.",
   landmark:{name:'Mehrangarh, Jodhpur', desc:'En festning på en klippe 120 meter over den blå byen, påbegynt i 1459 og aldri inntatt. Kjøkkenene der metter en garnison som ikke kunne regne med regn.'},
   plate:'Dal, en bati brutt opp og druknet i ghee, churma ved siden av, og laal maas hvis huset spiser kjøtt.',
   dishes:[['Laal maas',0],['Ker sangri',1],['Gatte ki sabzi',1],['Dal bati churma',1],['Pyaaz kachori',1],['Bajre ki roti',1],['Ghevar',1],['Mawa kachori',1]],
   lessons:['Å lage mat uten vann: chili, ghee og yoghurt','Bajra, bati og ørkenskapet','Laal maas, ker sangri og gatte','Rajputer og marwarier: to kjøkken, én ørken']},
 'IN-AWA':{name:'Awadh', capital:'Lucknow', intro:"Den mest parfymerte matlagingen i India, og den stilleste. Kokkene i Awadh arbeider med rose, skruepalme og safran heller enn chili, forsegler gryta med deig og lar ilden gjøre nesten ingenting på tre timer.",
   landmark:{name:'Bara Imambara, Lucknow', desc:'Bygd i 1784 som nødhjelp: nawaben betalte byen for å bygge om dagen og, sier historien, for å rive om natten. Hovedsalen har tak uten en eneste søyle.'},
   plate:'Galouti-kebab på en varm sheermal, en skvett lime, og biryani som først kommer ut når forseglingen brytes ved bordet.',
   dishes:[['Galouti kebab',0],['Awadhi biryani',0],['Nihari',0],['Kakori kebab',0],['Sheermal',1],['Shahi tukda',1],['Banarasi chaat',1],['Malai makhan',1]],
   lessons:['Attar og duft: det parfymerte skapet','Dum: ris, brød og den forseglede gryta','Kebab, biryani og nihari','Nawabene, 1856, og hvor kokkene tok veien']},
 'IN-GUJ':{name:'Gujarat', capital:'Ahmedabad', intro:"Søtt, surt og sterkt i samme munnfull, stort sett uten kjøtt, og servert alt på én gang på en stålthali. Gujarat har handlet over Arabiahavet i fire tusen år, og kjøkkenet viser appetitten til kjøpmenn.",
   landmark:{name:'Rani ki Vav, Patan', desc:'En trappebrønn hogd sju etasjer ned på 1060-tallet, med tusen skulpturer langs veggene. Så mye var vann verdt.'},
   plate:'En thali: to grønnsaker, dal, kadhi, rotli, ris, en pickles, og noe fritert som kommer sist og varmt.',
   dishes:[['Dhokla',1],['Undhiyu',1],['Khandvi',1],['Thepla',1],['Handvo',1],['Gujarati kadhi',1],['Shrikhand',1],['Fafda-jalebi',1]],
   lessons:['Søtt, surt og sterkt: skapet rundt dhana-jeera','Thalien som system','Dhokla, undhiyu og det dampede kjøkkenet','Havner, jainer og parsernes landgang ved Sanjan']},
 'IN-MAH':{name:'Maharashtra', capital:'Mumbai', intro:"Tre kjøkken under ett navn: kokos og ris langs Konkan-kysten, peanøtt og jaggery på Dekkan-platået, og i Mumbai maten til alle som noen gang kom dit med båt eller tog.",
   landmark:{name:'Gateway of India, Mumbai', desc:'En basaltbue ferdigstilt i 1924 for å ta imot visekonger, og brukt i 1948 til å se de siste britiske troppene dra gjennom den.'},
   plate:'Misal med pav til å tørke opp med, rå løk og lime ved siden av, og den tynne røde rassaen helt over til slutt.',
   dishes:[['Misal pav',1],['Vada pav',1],['Puran poli',1],['Pav bhaji',1],['Kolhapuri mutton',0],['Bombil fry',0],['Modak',1],['Kanda poha',1],['Sali boti',0]],
   lessons:['Goda masala og steinblomsten','Bhakri på platået, ris ved kysten','Misal, vada pav og den kolhapuriske rødfargen','Bombay: spinneriene, iranerne og ankomstenes mat']},
 'IN-KON':{name:'Goa og Konkan', capital:'Panaji', intro:"Fire hundre og femti år med Portugal etterlot eddik, svinekjøtt og et ord for karri, og tok svært lite med seg. Chilien selv kom i land her, fra Brasil, og gikk videre og forandret hvert eneste kjøkken i dette kurset.",
   landmark:{name:'Bom Jesus-basilikaen, Gamle Goa', desc:'Laterittstein og kalk, innviet i 1605, og den rommer Frans Xaviers legeme. Byen rundt ble en gang kalt Østens Roma og er nå stort sett skog.'},
   plate:'Fiskekarri og forkokt ris, hver dag, med en stekt makrell ved siden av og solkadhi til slutt.',
   dishes:[['Vindaloo',0],['Xacuti',0],['Sorpotel',0],['Cafreal',0],['Prawn balchão',0],['Fish curry rice',0],['Sannas',1],['Bebinca',1]],
   lessons:['Eddik, chili og recheado-masalaen','Ukda-ris og den daglige fiskekarrien','Vindaloo, xacuti og sorpotel','1510: hva Portugal brakte, og hva det tok']},
 'IN-CEN':{name:'Det midtre Dekkan', capital:'Bhopal', intro:"Landets midte lager mat i stillhet og blir sjelden skrevet om. Malwa maler valmuefrø inn i sausene sine, Bhopal arvet et mughalsk kjøkken som ble drevet av fire kvinner i hundre år, og skogene i Bastar spiser ting som ikke vokser noe annet sted.",
   landmark:{name:'Den store stupaen i Sanchi', desc:'En kuppel av tegl reist av Ashoka på 200-tallet før vår tidsregning, kledd i stein og omgitt av fire utskårne portaler. Det eldste steinbygget som fortsatt står i India.'},
   plate:'Poha med sev og en lime-båt klokka åtte om morgenen, jalebi som fortsatt drypper, og te etterpå.',
   dishes:[['Indori poha',1],['Bhutte ka kees',1],['Dal bafla',1],['Bhopali korma',0],['Rogan josh Bhopali',0],['Chironji ki barfi',1],['Chila',1],['Mahua laddu',1]],
   lessons:['Valmuefrø, chironji og skogsskapet','Hvete i Malwa, ris i Chhattisgarh','Poha, bafla og den bhopaliske kormaen','Ashoka, begumene og kjøkkenene i Bastar']},
 'IN-BEN':{name:'Bengal og øst', capital:'Kolkata', intro:"Fem krydder som aldri males, sennepsolje varm nok til å ta bakerst i halsen, og et måltid som serveres i en rekkefølge som går fra bittert til søtt. Øst for Bihar gjør ris og fisk den jobben hvete og meieriprodukter gjør i Punjab.",
   landmark:{name:'Howrah-brua, Kolkata', desc:'Et utkragerspenn som åpnet i 1943 uten bolter og muttere, naglet hele veien, og som bærer omkring hundre tusen mennesker til fots hver dag.'},
   plate:'Ris, så shukto, så dal, så en fisk i lett saus, så chutney, så noe søtt. I den rekkefølgen, og ikke i noen annen.',
   dishes:[['Shorshe ilish',0],['Macher jhol',0],['Kosha mangsho',0],['Shukto',1],['Luchi-alur dom',1],['Litti chokha',1],['Chhena poda',1],['Mishti doi',1],['Rasgulla',1]],
   lessons:['Panch phoron, sennep og regelen om hele krydder','Ris og rekkefølgen i et bengalsk måltid','Ilish, kosha mangsho og søtsakene','Chhana, portugiserne og en nawab i eksil']},
 'IN-NEA':{name:'Nordøst-India', capital:'Guwahati', intro:"Åtte delstater der nesten ingenting av det indiske krydderskapet kom fram. Styrken kommer fra en chili som holdt verdensrekorden, dybden fra gjæret fisk, soya og bambus, og maten dampes, røykes og kokes i stedet for å stekes.",
   landmark:{name:'De levende rotbruene i Meghalaya', desc:'Røtter av gummifiken trent over en elv gjennom femten eller tjue år, og sterkere for hvert tiår i stedet for svakere. Noen skal være fem hundre år gamle.'},
   plate:'Ris, en skål sur tenga, en pitika av most potet med sennepsolje, og en chili på kanten av tallerkenen.',
   dishes:[['Masor tenga',0],['Khar',1],['Smoked pork with bamboo',0],['Axone pork',0],['Eromba',1],['Jadoh',0],['Aloo pitika',1],['Thukpa',0]],
   lessons:['Gjæring i stedet for krydder','Ris, klebrig ris og den dampede gryta','Tenga, khar og det røykte svinekjøttet','Ahomene, åsene og skapet som aldri kom over']},
 'IN-KAR':{name:'Karnataka', capital:'Bengaluru', intro:"Fingerhirse i det tørre innlandet, ris og kokos ved kysten, en chili som dyrkes for fargen heller enn styrken, og i Udupi et tempelkjøkken som dro hjemmefra og åpnet restauranter i hver eneste indiske by.",
   landmark:{name:'Mysore-palasset', desc:'Gjenoppbygd i 1912 etter en brann, i en stil arkitekten kalte indo-sarasensk og alle andre kaller Mysore-palasset. Nittisju tusen lyspærer tenner det på søndagskvelder.'},
   plate:'En ball ragi mudde som svelges, ikke tygges, med en tynn saaru av grønt, og kjernemelk etterpå.',
   dishes:[['Bisi bele bath',1],['Mysore masala dosa',1],['Ragi mudde',1],['Neer dosa',1],['Pandi curry',0],['Kundapur koli saaru',0],['Mysore pak',1],['Dharwad peda',1]],
   lessons:['Byadgi: chilien som dyrkes for fargen','Ragi, ris og røren ved kysten','Bisi bele bath, dosa og pandi curry','Vijayanagara, wodeyarene og sju kaffebønner']},
 'IN-AND':{name:'Andhra og Telangana', capital:'Hyderabad', intro:"Den sterkeste hverdagsmaten i India, bygd på Guntur-chilien og en syrlighet fra tamarind og gongura-blad. I Hyderabad vokser et annet kjøkken fram i det samme landskapet, persisk i duftene sine, og det kjøler ned alt sammen.",
   landmark:{name:'Charminar, Hyderabad', desc:'Fire minareter over fire buer, reist i 1591 da det qutbshahiske hoffet flyttet ut av Golconda. Det gamle markedet går fortsatt rundt føttene på den.'},
   plate:'Ris, en skje ghee, pappu, en sur gongura-pachadi, og avakaya fra glasset som ble fylt i mai.',
   dishes:[['Hyderabadi biryani',0],['Gongura mamsam',0],['Avakaya',1],['Pesarattu',1],['Pulihora',1],['Haleem',0],['Bagara baingan',1],['Qubani ka meetha',1]],
   lessons:['Guntur-styrke og gongura-syre','Ris, pappu og pickles som holder et år','Biryani, haleem og gongura-lammet','Qutbshahier og nizamer: Persia på Dekkan']},
 'IN-TAM':{name:'Tamil Nadu', capital:'Chennai', intro:"Før chilien fantes pepperen, og havnene i Tamil Nadu solgte den til Roma. Hverdagsmaten er nedtonet og bygd på ris; Chettinad-kjøkkenet i innlandet er alt annet enn det, og rister krydderet svart.",
   landmark:{name:'Brihadisvara-tempelet, Thanjavur', desc:'Ferdig i 1010 under Rajaraja Chola, med et tårn på 66 meter granitt i et distrikt uten granitt på seksti kilometers omkrets.'},
   plate:'Et bananblad: ris i midten, sambar helles først, så rasam, så kulturmelk, med pickles øverst i venstre hjørne der den alltid har ligget.',
   dishes:[['Idli',1],['Dosa',1],['Sambar',1],['Rasam',1],['Chettinad chicken',0],['Meen kuzhambu',0],['Kothu parotta',0],['Filter coffee',1],['Payasam',1]],
   lessons:['Pepper, kalpasi og Chettinad-ristingen','Gjæret røre og rekkefølgen på bananbladet','Idli, sambar og Chettinad-kjøkkenet','Cholaer, romere og chettiarene som dro østover']},
 'IN-KER':{name:'Kerala', capital:'Kochi', intro:"Her begynner historien. Svart pepper og kardemomme vokser i disse åsene, og hver eneste handelsmann som ville ha dem - romer, araber, kineser, jøde, portugiser, nederlender - la igjen noe i kjøkkenet på veien.",
   landmark:{name:'De kinesiske fiskenettene i Fort Kochi', desc:'Landfaste vippenett som senkes og heves av fire mann og en rad med stein, og som etter sigende kom med handelsmenn fra Kublai Khans hoff.'},
   plate:'Rød mattaris, en fiskekarri skarp av kudampuli, thoran ved siden av, og en skje kokosolje helt over til slutt.',
   dishes:[['Meen curry',0],['Appam with stew',0],['Puttu-kadala',1],['Kerala parotta',1],['Beef fry',0],['Avial',1],['Karimeen pollichathu',0],['Thalassery biryani',0],['Sadya',1]],
   lessons:['Pepper, kardemomme og krydderkysten','Ris i fire former, kokos i fire til','Meen curry, appam og sadya','Fra Muziris til Vasco da Gama: handelen som formet kjøkkenet']}
};
