/* Masala Dabba — repetisjonsspørsmål for Andhra og Telangana (IN-AND), norsk bokmål.
   Kontrakt: docs/quiz-format.md, sjekkes av tools/quizcheck.py. Samme rekkefølge og samme
   fasitindeks som i den engelske filen. Spørsmålene leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-AND'] = [
 [
  {q:'Hva er uvanlig med gongura som syrningsmiddel?',
   a:['Det er det tørkede skallet av en frukt og ikke et blad',
      'Syren sitter i selve bladet og tilsettes ikke gryta',
      'Bladet blir først surt etter å ha stått natten over',
      'Bladet må gjære før det smaker av noe'],
   c:1, why:'Gongura er blad av hibiskusarten roselle, og det kommer surt av seg selv, så det syrner og smaksetter retten i samme grep.'},
  {q:'Hvordan er Guntur Sannam sammenlignet med kashmirchili og byadgichili?',
   a:['Den er mildere, og den dyrkes mest for fargens skyld',
      'Den er omtrent like sterk, men mørkere rød',
      'Den er mange ganger sterkere, mens de to dyrkes mest for fargen',
      'Den er ingen chili, men en slags pepper'],
   c:2, why:'Publiserte Scoville-tall for Guntur Sannam ligger i titusenvis, godt over chiliene andre regioner dyrker for fargen.'},
  {q:'Hva er en podi?',
   a:['Et tørt krydderpulver som serveres til maten eller brukes under kokingen',
      'En våt pasta som males som bunn i en karri',
      'En tempering som helles over en ferdig dal',
      'En pickles som modnes under et lag olje'],
   c:0, why:'Podi betyr pulver. Kandi podi og karam podi kan serveres til ris eller pannekaker, mens andre podier brukes under kokingen.'}
 ],
 [
  {q:'Hva forteller det første ordet i tomato pappu eller gongura pappu deg?',
   a:['Hvor lenge dalen har kokt',
      'Hvilken grønnsak som er kokt inn i dalen',
      'Hvilken belgfrukt retten er laget av',
      'Hvilket distrikt oppskriften kommer fra'],
   c:1, why:'Pappu får navn etter grønnsaken som kokes inn i den, og metoden endrer seg knapt fra den ene utgaven til den neste.'},
  {q:'Hva skiller pesarattu fra en dosa?',
   a:['Den dampes i stedet for å stekes på takke',
      'Den lages av hvetemel',
      'Den brettes alltid rundt et fyll av potet',
      'Røren bruker hele grønne mungbønner og stekes vanligvis fersk'],
   c:3, why:'Pesarattu bruker hele grønne mungbønner og stekes vanligvis samme dag i stedet for å gjæres med vilje over natten.'},
  {q:'Hvordan oppbevarer kurset sin variant av avakaya?',
   a:['I romtemperatur under olje i et år',
      'I en åpen bolle ved komfyren',
      'Straks i kjøleskapet i et rent glass med lokk',
      'Fryst før krydderet går i'],
   c:2, why:'Olje alene dokumenterer ikke trygg lagring i romtemperatur. Kurset lager en liten porsjon, setter den straks kaldt og bruker rent redskap.'}
 ],
 [
  {q:'Hva gjør kacchi-metoden vanskeligere enn pakki-metoden?',
   a:['Risen må vaskes og bløtlegges natten over',
      'Rått kjøtt og halvkokt ris må bli ferdige i samme øyeblikk',
      'Gryta må åpnes og røres i hvert tiende minutt',
      'Kjøttet kokes to ganger, både før og etter lagdelingen'],
   c:1, why:'I en pakki-biryani er kjøttet ferdig kokt på forhånd. I en kacchi satser kokken på at geitekjøttet og risen blir ferdige samtidig.'},
  {q:'Hvorfor går gongura sent i kursoppskriften på gongura mamsam?',
   a:['For å holde bladsmaken tydelig og justere sluttsyren',
      'Fordi bladene er giftige før geitekjøttet er mørt',
      'For å gjøre sausen tykk nok til å skjære',
      'Fordi bladene bare plukkes helt på slutten av sesongen'],
   c:0, why:'Sen tilsetting holder gonguraen tydelig og lar kokken balansere syren etter at kjøttet er mørt; det er et oppskriftsvalg og ingen universell regel.'},
  {q:'Hva skal de mange timene med banking gi haleem?',
   a:['En mørkere farge',
      'En kraftigere smak av hele krydder',
      'Én glatt masse der hvete og kjøtt ikke lenger skiller seg',
      'Et lavere fettinnhold'],
   c:2, why:'Lang koking gjør råvarene myke, og bankingen fordeler kjøttfibrene gjennom den jevnede blandingen av korn og linser.'}
 ],
 [
  {q:'Hva knytter sikkert Charminar til grunnleggelsen av Hyderabad?',
   a:['Monumentet ble bestilt i 1591 mens den nye byen tok form',
      'Det ble reist etter at Aurangzeb tok Golconda i 1687',
      'Det begynte som britisk diamantbørs',
      'Det markerte opprettelsen av Telangana i 2014'],
   c:0, why:'Muhammad Quli Qutb Shah bestilte Charminar i 1591. Kildene gir flere forklaringer på monumentet, så kurset gjør ikke én legende til sikker historie.'},
  {q:'Hvor kommer ord som biryani, salan, baghar og khubani inn i regionen fra?',
   a:['Telugu, språket i begge delstatene',
      'Marathi, fra Dekkan i vest',
      'Dakhni, den sørlige formen av språket som ble til urdu',
      'Portugisisk, via Konkan-kysten'],
   c:2, why:'Dakhni utviklet seg i kontakt mellom indoarisk talemål, persisk og arabisk skriftkultur og flere regionale språk på Dekkan.'},
  {q:'Hva viser at det hyderabadiske kjøkkenet ble forsynt utenfra Dekkan?',
   a:['Basmatirisen i biryanien',
      'Chilien i mirchi ka salan',
      'Geitekjøttet i biryanien',
      'De tørkede aprikosene i qubani ka meetha'],
   c:3, why:'Tørkede aprikoser kom til Dekkan gjennom langdistansehandel fra kjøligere dyrkingsområder i nord og nordvest.'}
 ]
];
