/* Masala Dabba — repetisjonsspørsmål for Andhra og Telangana (IN-AND), norsk bokmål.
   Kontrakt: docs/quiz-format.md, sjekkes av tools/quizcheck.py. Samme rekkefølge og samme
   fasitindeks som i den engelske filen. Spørsmålene leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-AND'] = [
 [
  {q:'Hva er uvanlig med gongura som syrningsmiddel?',
   a:['Det er det tørkede skallet av en frukt og ikke et blad',
      'Syren sitter i selve bladet og tilsettes ikke gryta',
      'Bladet blir først surt etter å ha stått natten over',
      'Bladet må gjære før det smaker av noe'],
   c:1, why:'Gongura er blad av hibiskusarten roselle, og det kommer surt av seg selv, så det syrner og smaksetter retten i samme grep.'},
  {q:'Hvordan er Guntur Sannam sammenlignet med kashmirchili og byadgichili?',
   a:['Den er mildere, og den dyrkes mest for fargens skyld',
      'Den er omtrent like sterk, men mørkere rød',
      'Den er mange ganger sterkere, mens de to dyrkes mest for fargen',
      'Den er ingen chili, men en slags pepper'],
   c:2, why:'Publiserte Scoville-tall for Guntur Sannam ligger i titusenvis, godt over chiliene andre regioner dyrker for fargen.'},
  {q:'Hva er en podi?',
   a:['Et tørt pulver som spises som det er, på ris eller ved siden av en dosa',
      'En våt pasta som males som bunn i en karri',
      'En tempering som helles over en ferdig dal',
      'En pickles som modnes under et lag olje'],
   c:0, why:'Kandi podi og karam podi spises tørre, blandet i varm ris med en skje ghee. En podi kokes aldri inn i en rett.'}
 ],
 [
  {q:'Hva forteller det første ordet i tomato pappu eller gongura pappu deg?',
   a:['Hvor lenge dalen har kokt',
      'Hvilken grønnsak som er kokt inn i dalen',
      'Hvilken belgfrukt retten er laget av',
      'Hvilket distrikt oppskriften kommer fra'],
   c:1, why:'Pappu får navn etter grønnsaken som kokes inn i den, og metoden endrer seg knapt fra den ene utgaven til den neste.'},
  {q:'Hva skiller pesarattu fra en dosa?',
   a:['Den dampes i stedet for å stekes på takke',
      'Den lages av hvetemel',
      'Den brettes alltid rundt et fyll av potet',
      'Røren er hele grønne mungbønner og gjærer aldri'],
   c:3, why:'Pesarattu males av hele grønne mungbønner og brukes samme dag. Det finnes ingen heving over natten og ingen urad dal i den.'},
  {q:'Hvorfor får hver mangobit i avakaya beholde en flis av det harde indre skallet?',
   a:['Flisen holder biten sammen gjennom et år i salt',
      'Flisen gir picklesen en bitterhet den trenger',
      'Flisen hindrer at sennepspulveret legger seg i bunnen',
      'Flisen gjør bitene lettere å løfte opp av glasset'],
   c:0, why:'Skallet hindrer at mangoen blir til mos i løpet av et år, og derfor hakkes mangoen med tung kniv i stedet for å skrelles.'}
 ],
 [
  {q:'Hva gjør kacchi-metoden vanskeligere enn pakki-metoden?',
   a:['Risen må vaskes og bløtlegges natten over',
      'Rått kjøtt og halvkokt ris må bli ferdige i samme øyeblikk',
      'Gryta må åpnes og røres i hvert tiende minutt',
      'Kjøttet kokes to ganger, både før og etter lagdelingen'],
   c:1, why:'I en pakki-biryani er kjøttet ferdig kokt på forhånd. I en kacchi satser kokken på at geitekjøttet og risen blir ferdige samtidig.'},
  {q:'Hvorfor går gongura sent i gongura mamsam og ikke tidlig?',
   a:['Syren ville gjort kjøttet seinere mørt og latt det være seigt',
      'Bladene mister fargen hvis de koker lenge',
      'Sausen ville blitt for tykk til å helle',
      'Bladene plukkes bare helt på slutten av sesongen'],
   c:0, why:'Syre gjør kjøtt seinere mørt, så blader som går i fra starten, lar kokken vente en time til. Går de i sent, skjærer de i stedet gjennom fettet i geitekjøttet.'},
  {q:'Hva skal de mange timene med banking gi haleem?',
   a:['En mørkere farge',
      'En kraftigere smak av hele krydder',
      'Én glatt masse der hvete og kjøtt ikke lenger skiller seg',
      'Et lavere fettinnhold'],
   c:2, why:'Konsistensen er selve oppskriften. Ingenting i den ferdige skålen er til å kjenne igjen, og det er derfor en som bryter fasten, kan spise mye av den raskt.'}
 ],
 [
  {q:'Hvorfor forlot det qutbshahiske hoffet Golconda i 1591?',
   a:['Aurangzeb hadde tatt festningen etter en beleiring',
      'Åsen hadde vannmangel og ingen plass å vokse på',
      'Diamantgruvene i nærheten var tømt',
      'Elva Musi hadde oversvømt festningen'],
   c:1, why:'Muhammad Quli Qutb Shah la ut en planlagt by på sletten nedenfor, med Charminar i midten, og hoffet flyttet elleve kilometer ned til den.'},
  {q:'Hvor kommer ord som biryani, salan, baghar og khubani inn i regionen fra?',
   a:['Telugu, språket i begge delstatene',
      'Marathi, fra Dekkan i vest',
      'Dakhni, den sørlige formen av språket som ble til urdu',
      'Portugisisk, via Konkan-kysten'],
   c:2, why:'Dakhni vokste fram på Dekkan fra 1300-tallet og tok persiske og arabiske ord ovenfra, mens maten til hverdags fortsatt har navn på telugu.'},
  {q:'Hva viser at det hyderabadiske kjøkkenet ble forsynt utenfra Dekkan?',
   a:['Basmatirisen i biryanien',
      'Chilien i mirchi ka salan',
      'Geitekjøttet i biryanien',
      'De tørkede aprikosene i qubani ka meetha'],
   c:3, why:'Aprikoser vokser ikke på Dekkan. De tørkes langt nord og i Sentral-Asia, og de kom til Hyderabad som handelsvare.'}
 ]
];
