/* Masala Dabba — recap questions for Andhra & Telangana (IN-AND), English.
   Contract: docs/quiz-format.md, checked by tools/quizcheck.py. Four readings, three questions each.
   Questions are NEVER narrated: narrate.py only ever sees a reading's html. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-AND'] = [
 [
  {q:'What is unusual about gongura as a souring agent?',
   a:['It is the dried rind of a fruit rather than a leaf',
      'The acidity sits in the leaf itself rather than being added to the pot',
      'It only turns sour after standing overnight',
      'It has to be fermented before it tastes of anything'],
   c:1, why:'Gongura is roselle leaf, and it arrives sour on its own, so it sours and flavours a dish in the same move.'},
  {q:'How does the Guntur Sannam chilli compare with the Kashmiri and Byadgi chillies?',
   a:['It is milder, and it is grown mainly for its colour',
      'It is about the same heat but a deeper red',
      'It is many times hotter, while those two are grown mainly for colour',
      'It is not a chilli at all but a kind of pepper'],
   c:2, why:'Published Scoville figures for Guntur Sannam sit in the tens of thousands, well above the chillies other regions grow for colour.'},
  {q:'What is a podi?',
   a:['A dry powder eaten as it is, on rice or beside a dosa',
      'A wet paste ground as the base of a curry',
      'A tempering poured over a finished dal',
      'A pickle matured under a layer of oil'],
   c:0, why:'Kandi podi and karam podi are eaten dry, mixed into hot rice with a spoonful of ghee. A podi is never cooked into a dish.'}
 ],
 [
  {q:'What does the first word of tomato pappu or gongura pappu tell you?',
   a:['How long the dal has been cooked',
      'Which vegetable has been cooked into the dal',
      'Which lentil the dish is made from',
      'Which district the recipe comes from'],
   c:1, why:'Pappu is named for the vegetable cooked into it, and the method hardly changes between one version and the next.'},
  {q:'What makes pesarattu different from a dosa?',
   a:['It is steamed rather than cooked on a griddle',
      'It is made from wheat flour',
      'It is always folded round a potato filling',
      'The batter is whole green gram and is never fermented'],
   c:3, why:'Pesarattu is ground from whole green gram and used the same day. There is no overnight rise and no urad dal in it.'},
  {q:'Why is a fragment of the hard inner shell left on each piece of mango in avakaya?',
   a:['It holds the piece together through a year in salt',
      'It gives the pickle a bitterness it needs',
      'It stops the mustard powder from settling',
      'It makes the pieces easier to lift out of the jar'],
   c:0, why:'The shell is what stops the mango turning to mush over a year, which is why the pieces are cut with a heavy blade rather than peeled.'}
 ],
 [
  {q:'What makes the kacchi method harder than the pakki method?',
   a:['The rice has to be washed and soaked overnight',
      'Raw meat and part-boiled rice have to finish at the same moment',
      'The pot must be opened and stirred every ten minutes',
      'The meat is cooked twice, once before and once after layering'],
   c:1, why:'In a pakki biryani the meat is already cooked. In a kacchi one the cook is betting that the goat and the rice will be done together.'},
  {q:'Why does the gongura go into gongura mamsam late rather than early?',
   a:['Its acidity would slow the meat down and keep it tough',
      'The leaves lose their colour if they cook for long',
      'It would make the gravy too thick to pour',
      'The leaves are only picked at the end of the season'],
   c:0, why:'Acid slows meat down, so leaves added at the start leave the cook waiting an hour longer. Added late they cut the fat of the goat instead.'},
  {q:'What is haleem pounded for hours to achieve?',
   a:['A deeper colour',
      'A stronger flavour of whole spice',
      'A single smooth mass in which wheat and meat no longer separate',
      'A lower fat content'],
   c:2, why:'The texture is the recipe. Nothing in the finished bowl is identifiable, and that is what lets someone breaking a fast eat a lot of it quickly.'}
 ],
 [
  {q:'Why did the Qutb Shahi court leave Golconda in 1591?',
   a:['Aurangzeb had taken the fort after a siege',
      'The hill had a water problem and no room to grow',
      'The diamond mines nearby had been worked out',
      'The Musi river had flooded the fortress'],
   c:1, why:'Muhammad Quli Qutb Shah laid out a planned city on the plain below, with Charminar at its centre, and the court moved eleven kilometres down to it.'},
  {q:'Where do words like biryani, salan, baghar and khubani come into the region from?',
   a:['Telugu, the language of both states',
      'Marathi, from the Deccan to the west',
      'Dakhni, the southern form of the language that became Urdu',
      'Portuguese, by way of the Konkan coast'],
   c:2, why:'Dakhni grew in the Deccan from the fourteenth century and took Persian and Arabic vocabulary from above, while the everyday plate is still named in Telugu.'},
  {q:'Which of these shows that the Hyderabadi kitchen was supplied from outside the Deccan?',
   a:['The basmati rice in the biryani',
      'The chilli in mirchi ka salan',
      'The goat in the biryani',
      'The dried apricots in qubani ka meetha'],
   c:3, why:'Apricots do not grow on the Deccan. They are dried far to the north and in Central Asia, and they reached Hyderabad as trade goods.'}
 ]
];
