/* Masala Dabba — recap questions for Andhra & Telangana (IN-AND), English.
   Contract: docs/quiz-format.md, checked by tools/quizcheck.py. Four readings, three questions each.
   Questions are NEVER narrated: narrate.py only ever sees a reading's html. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-AND'] = [
 [
  {q:'What is unusual about gongura as a souring agent?',
   a:['It is the dried rind of a fruit rather than a leaf',
      'The acidity sits in the leaf itself rather than being added to the pot',
      'It only turns sour after standing overnight',
      'It has to be fermented before it tastes of anything'],
   c:1, why:'Gongura is roselle leaf, and it arrives sour on its own, so it sours and flavours a dish in the same move.'},
  {q:'How does the Guntur Sannam chilli compare with the Kashmiri and Byadgi chillies?',
   a:['It is milder, and it is grown mainly for its colour',
      'It is about the same heat but a deeper red',
      'It is many times hotter, while those two are grown mainly for colour',
      'It is not a chilli at all but a kind of pepper'],
   c:2, why:'Published Scoville figures for Guntur Sannam sit in the tens of thousands, well above the chillies other regions grow for colour.'},
  {q:'What is a podi?',
   a:['A dry seasoning powder, served as a condiment or used in cooking',
      'A wet paste ground as the base of a curry',
      'A tempering poured over a finished dal',
      'A pickle matured under a layer of oil'],
   c:0, why:'Podi means a powder. Kandi podi and karam podi may be served with rice or crepes, while other podis are used in cooking.'}
 ],
 [
  {q:'What does the first word of tomato pappu or gongura pappu tell you?',
   a:['How long the dal has been cooked',
      'Which vegetable has been cooked into the dal',
      'Which lentil the dish is made from',
      'Which district the recipe comes from'],
   c:1, why:'Pappu is named for the vegetable cooked into it, and the method hardly changes between one version and the next.'},
  {q:'What makes pesarattu different from a dosa?',
   a:['It is steamed rather than cooked on a griddle',
      'It is made from wheat flour',
      'It is always folded round a potato filling',
      'Its batter uses whole green gram and is usually cooked fresh'],
   c:3, why:'Pesarattu uses whole green gram and is usually cooked the same day rather than deliberately fermented overnight.'},
  {q:'How does the course store its avakaya adaptation?',
   a:['At room temperature under oil for a year',
      'In an open bowl beside the stove',
      'Refrigerated immediately in a clean lidded jar',
      'Frozen before the spices are added'],
   c:2, why:'Oil alone does not validate shelf-stable storage. The course makes a small batch, refrigerates it immediately and uses a clean utensil.'}
 ],
 [
  {q:'What makes the kacchi method harder than the pakki method?',
   a:['The rice has to be washed and soaked overnight',
      'Raw meat and part-boiled rice have to finish at the same moment',
      'The pot must be opened and stirred every ten minutes',
      'The meat is cooked twice, once before and once after layering'],
   c:1, why:'In a pakki biryani the meat is already cooked. In a kacchi one the cook is betting that the goat and the rice will be done together.'},
  {q:'Why does the course recipe add gongura late to gongura mamsam?',
   a:['To keep the leaf flavour vivid and adjust the final acidity',
      'Because the leaves are poisonous until the goat is tender',
      'To make the gravy thick enough to slice',
      'Because the leaves are picked only at the end of the season'],
   c:0, why:'Late addition keeps the gongura distinct and lets the cook balance its acidity after the meat is tender; it is a recipe choice, not a universal meat rule.'},
  {q:'What is haleem pounded for hours to achieve?',
   a:['A deeper colour',
      'A stronger flavour of whole spice',
      'A single smooth mass in which wheat and meat no longer separate',
      'A lower fat content'],
   c:2, why:'Long cooking softens the ingredients, and beating distributes the meat fibres through the thickened grain and pulse mixture.'}
 ],
 [
  {q:'What securely links Charminar with Hyderabad\'s foundation?',
   a:['It was commissioned in 1591 as the new city took shape',
      'It was built after Aurangzeb captured Golconda in 1687',
      'It began as a British diamond exchange',
      'It marked the creation of Telangana in 2014'],
   c:0, why:'Muhammad Quli Qutb Shah commissioned Charminar in 1591. Sources give several explanations for the monument, so the course does not present one legend as certain.'},
  {q:'Where do words like biryani, salan, baghar and khubani come into the region from?',
   a:['Telugu, the language of both states',
      'Marathi, from the Deccan to the west',
      'Dakhni, the southern form of the language that became Urdu',
      'Portuguese, by way of the Konkan coast'],
   c:2, why:'Dakhni developed through contact among Indo-Aryan speech, Persian and Arabic literary cultures, and several regional languages of the Deccan.'},
  {q:'Which of these shows that the Hyderabadi kitchen was supplied from outside the Deccan?',
   a:['The basmati rice in the biryani',
      'The chilli in mirchi ka salan',
      'The goat in the biryani',
      'The dried apricots in qubani ka meetha'],
   c:3, why:'Dried apricots reached the Deccan through long-distance trade from cooler growing regions to the north and northwest.'}
 ]
];
