/* Masala Dabba — repetisjonsspørsmål for Awadh (IN-AWA), norsk bokmål. Kontrakt: docs/quiz-format.md,
   sjekkes av tools/quizcheck.py. Samme rekkefølge og samme riktige svar som i den engelske filen. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-AWA'] = [
 [
  {q:'Hvorfor går attar i helt til slutt, eller ned i en forseglet gryte?',
   a:['Den er for dyr til å bruke i noen mengde',
      'Varmen driver duften rett av',
      'Den får melken til å skille seg hvis den går i tidlig',
      'Den må løse seg i fett før den virker'],
   c:1, why:'En attar er duft båret av olje og ikke et uttrekk i alkohol, og den tåler ikke koking, så den går i med kjelen av platen eller der en forsegling holder på den.'},
  {q:'Hva er en potli, og hva gjør den som en malt masala ikke kan?',
   a:['Et leirlokk som forsegler gryta',
      'Kobberkjelen som brukes i Kannauj',
      'Hele krydder knyttet i musselin og løftet opp før servering',
      'En kraft kokt på bein og hele krydder'],
   c:2, why:'En potli gir bare fra seg det som løser seg ut, og så forlater den gryta, så sausen holder seg lys og ren og kokken bestemmer når det er nok.'},
  {q:'Hvorfor kan ikke rosevann og roseessens byttes om?',
   a:['Essensen er mange ganger sterkere, så samme mengde ødelegger retten',
      'Essensen destilleres av en annen rosenart',
      'Rosevann blir dårlig i løpet av en uke, og essensen gjør ikke det',
      'Essensen selges bare til parfyme og kan ikke spises'],
   c:0, why:'Rosevann er tynt, og en spiseskje passer i en gryte ris, mens essensen kommer på en mye mindre flaske og er mange ganger sterkere.'}
 ],
 [
  {q:'Hvilken virkning av forseglingen med deig betyr mest for nettopp dette kjøkkenet?',
   a:['Den hever trykket nok til at kjøttet koker raskere',
      'Den hindrer risen i å brenne seg fast i bunnen',
      'Den hindrer alt flyktig i å slippe ut',
      'Den lar kokken røre uten å miste varme'],
   c:2, why:'Kewra, rosevann, safran og muskatblomme ville havnet i taket på kjøkkenet i løpet av et minutt hvis gryta stod åpen, og under en forsegling går det tilbake i maten.'},
  {q:'Hvordan skiller en biryani fra Awadh seg fra kacchi-varianten i Hyderabad?',
   a:['Den bruker kortkornet ris i stedet for basmati',
      'Kjøttet kokes først, og risen halvkokes i kraften fra det',
      'Den gjøres ferdig i en tandoor i stedet for over glør',
      'Den kokes helt uten forsegling'],
   c:1, why:'Hyderabad forsegler rått marinert kjøtt under halvkokt ris. Awadh koker kjøttet først, halvkoker risen i den samme kraften og legger så de to lagvis.'},
  {q:'Hvorfor passer lang koking under forsegling til skank, nakke og bog?',
   a:['De stykkene er magre, og en åpen gryte ville tørket dem ut',
      'Kollagenet blir til gelatin, så kjøttet mykner og kraften tykner',
      'De må brunes først, og en forseglet gryte bruner dem',
      'De er de eneste stykkene som får plass i en leirgryte'],
   c:1, why:'Holdes de like under kokepunktet i timevis, uten røring og uten at vann forsvinner, blir kollagenet til gelatin, og da trengs knapt mel og ingen innkoking.'}
 ],
 [
  {q:'Hva gjør at en galouti-kebab faller fra hverandre på tunga?',
   a:['Den dampes i stedet for å stekes',
      'Rå papaya, som inneholder papain, et enzym som bryter ned proteinene',
      'Den inneholder ikke kjøtt i det hele tatt, bare malte linser',
      'Farsen bindes med egg og fløte'],
   c:1, why:'Papainet arbeider videre så lenge farsen står, og nettopp derfor gir en for lang hvile en masse som ikke henger sammen.'},
  {q:'Hva skiller en kakori fra en galouti?',
   a:['En kakori er en seekh-kebab som stekes på spidd over glør',
      'En kakori lages av kylling og en galouti av geit',
      'En kakori kokes først og stekes etterpå',
      'En kakori har ikke papaya i seg i det hele tatt'],
   c:0, why:'En kakori må bli sittende på det flate spiddet over ilden, så den bygges myk og likevel fast, mens en galouti stekes på flat plate.'},
  {q:'Hvor har nihari navnet sitt fra, og hvor kommer tykkelsen fra?',
   a:['Fra en småby ved Lucknow, og fra malte mandler',
      'Fra nahar, morgen, og fra kollagenet i beina',
      'Fra det persiske ordet for damp, og fra malt ris',
      'Fra navnet på en nawab, og fra fløte rørt inn til slutt'],
   c:1, why:'Nahar er det arabiske ordet for morgen, og kraften tykner av seg selv fordi kollagenet i skank og margbein blir til gelatin i løpet av natta.'}
 ],
 [
  {q:'Hvorfor ble Bara Imambara bygd?',
   a:['For å romme graven til Saadat Khan',
      'Som nødsarbeid etter at regnet sviktet i 1784',
      'For å markere at hoffet flyttet fra Faizabad til Lucknow',
      'Som festning mot Det britiske ostindiske kompani'],
   c:1, why:'Regnet sviktet i 1784, og Asaf-ud-Daula svarte med et byggeprosjekt som med vilje gikk langsomt, slik at arbeidet og lønningene varte.'},
  {q:'Hva skjedde med Awadh i februar 1856?',
   a:['Kompaniet annekterte landet og avsatte Wajid Ali Shah',
      'Hoffet flyttet fra Faizabad til Lucknow',
      'Begum Hazrat Mahal ble utropt til regent for sønnen sin',
      'Residency ble beleiret i fem måneder'],
   c:0, why:'Anneksjonen 7. februar 1856 fjernet en traktatpartner som aldri hadde kjempet mot kompaniet, og harmen over den bidro til opprøret året etter.'},
  {q:'Hvordan henger denne modulen sammen med biryanien man spiser i Kolkata?',
   a:['Bengalske kokker ble hentet til Lucknow for å arbeide ved hoffet',
      'Poteten kom til Lucknow fra Bengal langs elva',
      'Den avsatte nawaben tok kjøkkenet sitt med til Metiabruz',
      'Begge byene kokte biryanien sin på den samme kortkornede risen'],
   c:2, why:'Wajid Ali Shah slo seg ned i Metiabruz ved Calcutta de siste tretti årene av livet, og kokkene som fulgte ham, er grunnen til at Kolkata-biryani har en potet i seg.'}
 ]
];
