/* Masala Dabba — recap questions for Awadh (IN-AWA), English. Contract: docs/quiz-format.md,
   checked by tools/quizcheck.py. Four readings, three questions each. Questions are NEVER narrated. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-AWA'] = [
 [
  {q:'Why does attar go in at the very end of cooking, or into a sealed pot?',
   a:['It is too expensive to use in any quantity',
      'Heat drives the fragrance straight off',
      'It curdles milk if it goes in early',
      'It has to dissolve into fat before it works'],
   c:1, why:'An attar is fragrance carried in oil rather than an extract in alcohol, and it does not survive cooking, so it is added off the heat or where a seal traps it.'},
  {q:'What is a potli, and what does it do that a ground masala cannot?',
   a:['A clay lid that seals the pot',
      'The copper still used in Kannauj',
      'Whole spices tied in muslin and lifted out before serving',
      'A stock made from bones and whole spice'],
   c:2, why:'A potli gives up only what dissolves out of it and then leaves the pot, so the gravy stays pale and clean and the cook decides when to stop.'},
  {q:'Why are rose water and rose essence not interchangeable?',
   a:['Essence is many times stronger, so the same measure ruins the dish',
      'Essence is distilled from a different species of rose',
      'Rose water spoils within a week and essence does not',
      'Essence is sold only for perfume and is not edible'],
   c:0, why:'Rose water is dilute and a tablespoon suits a pot of rice, while essence comes in a much smaller bottle and is many times stronger.'}
 ],
 [
  {q:'Which effect of the dough seal matters most to this particular kitchen?',
   a:['It raises the pressure enough to cook the meat faster',
      'It stops the rice from sticking to the base of the pot',
      'It stops anything volatile from escaping',
      'It lets the cook stir without losing heat'],
   c:2, why:'Kewra, rose water, saffron and mace would be on the kitchen ceiling within a minute of an open pot, and under a seal they go back into the food.'},
  {q:'How does an Awadhi biryani differ from Hyderabad\'s kacchi version?',
   a:['It uses short-grain rice rather than basmati',
      'The meat is cooked first and the rice part-boiled in its stock',
      'It is finished in a tandoor rather than over coals',
      'It is cooked without any seal at all'],
   c:1, why:'Hyderabad seals raw marinated meat under part-boiled rice. Awadh cooks the meat first, part-boils the rice in the same stock and then layers the two.'},
  {q:'Why does long cooking under a seal suit shank, neck and shoulder?',
   a:['Those cuts are lean, and an open pot would dry them out',
      'Their collagen turns to gelatine, so the meat softens and the broth thickens',
      'They have to be browned first, and a sealed pot browns them',
      'They are the only cuts that will fit into a clay pot'],
   c:1, why:'Held just under boiling for hours, without stirring and without losing water, collagen becomes gelatine, so little flour and no reduction are needed.'}
 ],
 [
  {q:'What makes a galouti kebab collapse on the tongue?',
   a:['It is steamed rather than fried',
      'Raw papaya, whose papain cuts the proteins apart',
      'It contains no meat at all, only ground lentils',
      'The mince is bound with egg and cream'],
   c:1, why:'Papain keeps working for as long as the mixture stands, which is also why too long a rest leaves a paste that will not hold together.'},
  {q:'What separates a kakori from a galouti?',
   a:['A kakori is a seekh kebab cooked on a skewer over coals',
      'A kakori is made with chicken and a galouti with goat',
      'A kakori is boiled first and then fried',
      'A kakori has no papaya in it at all'],
   c:0, why:'A kakori has to stay on its flat skewer over the fire, so it is built to be soft and still firm, while a galouti is fried on a flat pan.'},
  {q:'Where does nihari get its name, and where does its thickness come from?',
   a:['From a town near Lucknow, and from ground almond',
      'From nahar, morning, and from the collagen in the bones',
      'From the Persian word for steam, and from ground rice',
      'From the name of a Nawab, and from cream stirred in at the end'],
   c:1, why:'Nahar is the Arabic word for morning, and the broth thickens on its own because the collagen in shank and marrow bones turns to gelatine overnight.'}
 ],
 [
  {q:'Why was the Bara Imambara built?',
   a:['To house the tomb of Saadat Khan',
      'As famine relief after the rains failed in 1784',
      'To mark the move of the court from Faizabad to Lucknow',
      'As a fort against the East India Company'],
   c:1, why:'The rains failed in 1784 and Asaf-ud-Daula answered with a building project that was deliberately slow, so that the work and the wages lasted.'},
  {q:'What happened to Awadh in February 1856?',
   a:['The Company annexed it and deposed Wajid Ali Shah',
      'The court moved from Faizabad to Lucknow',
      'Begum Hazrat Mahal was proclaimed regent for her son',
      'The Residency was besieged for five months'],
   c:0, why:'The annexation of 7 February 1856 removed a treaty ally who had never fought the Company, and the grievance fed the revolt the following year.'},
  {q:'How is this module connected to the biryani eaten in Kolkata?',
   a:['Bengali cooks were brought to Lucknow to work at the court',
      'The potato reached Lucknow from Bengal by river',
      'The deposed Nawab took his kitchen with him to Metiabruz',
      'Both cities cooked their biryani with the same short-grain rice'],
   c:2, why:'Wajid Ali Shah settled at Metiabruz near Calcutta for the last thirty years of his life, and the cooks who went with him are why Kolkata biryani has a potato in it.'}
 ]
];
