/* Masala Dabba — oppsummeringsspørsmål, norsk. Kontrakt: docs/quiz-format.md, sjekkes av tools/quizcheck.py.
   Samme antall lesetekster, samme antall spørsmål og samme riktige svarindeks som den engelske filen.
   Spørsmålene leses aldri opp, så en endring her gjør ingen lydfil utdatert. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-BEN'] = [
 [
  {q:'Hvorfor holdes panch phoron-blandingen i kurset hel?',
   a:['Maling er forbudt i alle bengalske oppskrifter',
      'Hele frø slipper duft i ulik takt og forblir tydelige i retten',
      'Blandingen er for oljete til å males på stein',
      'Den males i Bengal, men ikke i Odisha'],
   c:1, why:'Hele frø beholder ulike konsistenser og dufter under temperingen. Blandingene og tidspunktet de tilsettes på, kan variere.'},
  {q:'Hvorfor varmer mange kokker sennepsoljen før steking?',
   a:['For å sterilisere den, siden den er kaldpresset',
      'For at den skal bli varm nok til å forsegle fisken',
      'For å drive av den rå skarpheten og la en nøtteaktig varme bli igjen',
      'For å skille den, så faststoffet kan tas ut'],
   c:2, why:'Oppvarming mildner den rå skarpheten i kaldpresset sennepsolje. Andre retter beholder litt rå olje som smakstilsetning til slutt.'},
  {q:'Hvilke forhold kan endre styrken og bitterheten i sennepspasta?',
   a:['Frøfarge, bløtlegging, maling og koking',
      'At den saltes',
      'At det brukes kaldt vann i stedet for varmt',
      'At den blir stående en time'],
   c:0, why:'Sennepsforhold og behandling påvirker resultatet. Kurset maler kort og koker forsiktig, men hjemlige metoder varierer.'}
 ],
 [
  {q:'Hvorfor er ris så viktig i lavlandet i Bengal?',
   a:['Britene erstattet hveten med ris på 1800-tallet',
      'Jorda er for mager til hvete',
      'Området ligger på deltaet til Ganges og Brahmaputra, som er flatt, slamrikt og svært vått',
      'Risen kom med handelsmenn fra Java og tok over'],
   c:2, why:'Elvenes lavland, monsunregn og vanning støtter flere rissesonger. Høylandet andre steder i kursregionen har andre råvaremønstre.'},
  {q:'Hva er kursets tryggere metode for panta bhat eller pakhala?',
   a:['Ris kokt i melk og palmesukker',
      'Bruk utprøvd fermentering, eller kjøl risen raskt og tilsett kaldt vann senere',
      'Den første risen fra aman-avlingen',
      'Rismel dampet i en bambussylinder'],
   c:1, why:'Kokt ris i romtemperatur kan gi vekstvilkår for Bacillus cereus. Tradisjonelle retter har flere metoder, men kurset anbefaler ikke ukontrollert nattelagring.'},
  {q:'Hva beskriver best rekkefølgen i et formelt bengalsk måltid?',
   a:['Bitre grønnsaker blir fortest dårlige, så de spises først',
      'Det er en portugisisk vane som ble sittende',
      'Det kan åpne med bittert og gå via dal og karriretter til chutney og søtt',
      'Den bitre retten renser ganen mellom fiskerettene'],
   c:2, why:'Dette er en kjent formell progresjon, ikke en fast regel for alle husholdninger eller en etablert ernæringslov.'}
 ],
 [
  {q:'Hva betyr mest for framtidige ville ilishvandringer?',
   a:['Om kokken vasker den oppskårne fisken',
      'Friske vandringsveier og vern av yngel og gytefisk',
      'Det løsner beina, så de havner i sausen',
      'Skjellene ville fulgt med vannet'],
   c:1, why:'Fiskepress og barrierer i elvene påvirker denne vandrende arten. Vernetiltak beskytter sårbare livsstadier og elveforbindelser.'},
  {q:'Hva beskriver ordet kosha?',
   a:['En gryte kjøttet forsegles i',
      'En blanding av hele garam masala-krydder',
      'Å steke noe langsomt ned med svært lite væske',
      'Et stykke geitekjøtt fra bogen'],
   c:2, why:'Kosha mangsho har navn etter teknikken. Kokken steker kjøttet ned, har i en skvett vann hver gang det truer med å svi seg, og steker det ned igjen, i nesten en time.'},
  {q:'Hvordan endte striden om hvem som fant opp rasgullaen?',
   a:['Vest-Bengal vant, og Odisha trakk kravet sitt',
      'Odisha vant på grunnlag av kildene fra Jagannath-tempelet',
      'Ingen av kravene ble registrert, så begge er fortsatt uformelle',
      'Begge delstatene har geografisk opprinnelsesbetegnelse, for to ulike produkter med hvert sitt navn'],
   c:3, why:'Banglar Rasogolla og Odisha Rasagola er to registrerte produkter. En geografisk betegnelse avgjør ikke det historiske spørsmålet om oppfinnelse.'}
 ],
 [
  {q:'Hvorfor trekkes påstanden om at portugiserne lærte Bengal å skille melk, i tvil?',
   a:['Ingen portugisere slo seg noen gang ned i Bengal',
      'Manasollasa fra 1100-tallet beskriver allerede noe som ligner sterkt på chhana',
      'Chhana brukes ikke i bengalske søtsaker i det hele tatt',
      'Nederlenderne kom til Hooghly først'],
   c:1, why:'Metoden var kjent i India lenge før noe portugisisk skip rundet Afrika, og de bengalske sukkerbakerne var en egen yrkesgruppe som ikke var bundet av tabuet historien hviler på.'},
  {q:'Hva er den sikreste historiske koblingen bak biryanien fra Kolkata?',
   a:['Risen drøyes fordi potet er billigere enn safran',
      'Poteten hører hjemme i Bengal og ble brukt lenge før risen',
      'Husholdningen til Wajid Ali Shah tok awadhisk mattradisjon til Metiabruz',
      'Britiske offiserer ba om den på 1890-tallet'],
   c:2, why:'Wajid Ali Shah slo seg ned i Metiabruz etter avsettelsen i 1856. Historiene om trang økonomi og poteten som nyhet er fortsatt udokumenterte.'},
  {q:'Hvilket av disse er et varig portugisisk spor i Bengal?',
   a:['Panch phoron',
      'Lånord som almari og girja, og tradisjonen med bandelost',
      'Skikken med å spise med høyre hånd',
      'Forkokingen av risen'],
   c:1, why:'Portugisisk kontakt satte spor i språk og mat ved Hooghly, men historien til enkeltord og direkte arvelinjer krever varsomhet.'}
 ]
];
