/* Masala Dabba — oppsummeringsspørsmål, norsk. Kontrakt: docs/quiz-format.md, sjekkes av tools/quizcheck.py.
   Samme antall lesetekster, samme antall spørsmål og samme riktige svarindeks som den engelske filen.
   Spørsmålene leses aldri opp, så en endring her gjør ingen lydfil utdatert. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-BEN'] = [
 [
  {q:'Hvorfor males panch phoron aldri?',
   a:['Skikken forbyr det, av andre grunner enn matlagingen',
      'De fem frøene koker i ulik takt, og hele holder de seg fra hverandre i retten',
      'Blandingen er for oljete til å males på stein',
      'Den males i Bengal, men ikke i Odisha'],
   c:1, why:'Bukkehornkløver svir seg på sekunder, mens fennikel trenger lengre tid. Males de sammen, koker de i samme takt og smaker ingenting bestemt.'},
  {q:'Hvorfor varmes sennepsoljen hardt før noe annet går i pannen?',
   a:['For å sterilisere den, siden den er kaldpresset',
      'For at den skal bli varm nok til å forsegle fisken',
      'For å drive av den rå skarpheten og la en nøtteaktig varme bli igjen',
      'For å skille den, så faststoffet kan tas ut'],
   c:2, why:'Kaldpresset sennepsolje er skarp av allylisotiocyanat. Varmes den til den så vidt ryker, brenner den rå kanten av; sløyfer du steget, smaker retten av flasken.'},
  {q:'Hva gjør en rå sennepspasta bitter?',
   a:['At den males for lenge, eller kokes for hardt',
      'At det har i salt',
      'At det brukes kaldt vann i stedet for varmt',
      'At den blir stående en time'],
   c:0, why:'Varme sammen med vann setter i gang enzymet som lager bitterstoffene. Derfor males pastaen raskt, med salt og gurkemeie, og går i retten mot slutten.'}
 ],
 [
  {q:'Hvorfor spiser det østlige India så mye ris?',
   a:['Britene erstattet hveten med ris på 1800-tallet',
      'Jorda er for mager til hvete',
      'Området ligger på deltaet til Ganges og Brahmaputra, som er flatt, slamrikt og svært vått',
      'Risen kom med handelsmenn fra Java og tok over'],
   c:2, why:'De to elvene har bygd verdens største delta. Flatt land, slam som fornyes hvert år og godt over halvannen meter monsunregn er nettopp det risen vil ha.'},
  {q:'Hva er panta bhat, eller pakhala?',
   a:['Ris kokt i melk og palmesukker',
      'Kokt ris som står i vann over natten og spises kald og svakt syrlig',
      'Den første risen fra aman-avlingen',
      'Rismel dampet i en bambussylinder'],
   c:1, why:'Retten begynte som en måte å holde kokt ris spiselig gjennom en varm natt uten kjøleskap, og ble til noe folk vil ha for sin egen del. Odisha holder en egen dag for den hver mars.'},
  {q:'Hvorfor åpner et bengalsk måltid med noe bittert?',
   a:['Bitre grønnsaker blir fortest dårlige, så de spises først',
      'Det er en portugisisk vane som ble sittende',
      'Bitterhet åpner matlysten, og syre til slutt lukker den',
      'Den bitre retten renser ganen mellom fiskerettene'],
   c:2, why:'Prinsippet kommer fra ayurveda, men det fungerer på egne premisser: en enkel bitter rett først gjør at alt etterpå smaker sterkere.'}
 ],
 [
  {q:'Hvorfor vaskes ilish aldri etter at den er skåret opp?',
   a:['Elvevannet ville ødelagt den',
      'Vaskingen fjerner oljen som gjør fisken verdt å spise',
      'Det løsner beina, så de havner i sausen',
      'Skjellene ville fulgt med vannet'],
   c:1, why:'Ilish er ettertraktet for fettet, og oljen skyller rett av oppskåret fisk. Det fettet er også grunnen til at Bengal godtar en fisk full av fine kløyvde bein.'},
  {q:'Hva beskriver ordet kosha?',
   a:['En gryte kjøttet forsegles i',
      'En blanding av hele garam masala-krydder',
      'Å steke noe langsomt ned med svært lite væske',
      'Et stykke geitekjøtt skåret fra bogen'],
   c:2, why:'Kosha mangsho har navn etter teknikken. Kokken steker kjøttet ned, har i en skvett vann hver gang det svir seg, og steker det ned igjen, i nesten en time.'},
  {q:'Hvordan endte striden om hvem som fant opp rasgullaen?',
   a:['Vest-Bengal vant, og Odisha trakk kravet sitt',
      'Odisha vant på grunnlag av kildene fra Jagannath-tempelet',
      'Ingen av kravene ble registrert, så begge er fortsatt uformelle',
      'Begge delstatene har geografisk opprinnelsesbetegnelse, for to ulike produkter med hvert sitt navn'],
   c:3, why:'Banglar Rasogolla ble registrert i 2017 og Odisha Rasagola i 2019. De er anerkjent som to forskjellige produkter, og det er den ærlige utgangen.'}
 ],
 [
  {q:'Hvorfor trekkes påstanden om at portugiserne lærte Bengal å skille melk, i tvil?',
   a:['Ingen portugisere slo seg noen gang ned i Bengal',
      'Manasollasa fra 1100-tallet beskriver allerede noe som ligner sterkt på chhana',
      'Chhana brukes ikke i bengalske søtsaker i det hele tatt',
      'Nederlenderne kom til Hooghly først'],
   c:1, why:'Metoden var kjent i India lenge før noe portugisisk skip rundet Afrika, og de bengalske sukkerbakerne var en egen yrkesgruppe som ikke var bundet av tabuet historien hviler på.'},
  {q:'Hvorfor ligger det en hel potet i biryanien fra Kolkata?',
   a:['Risen drøyes fordi potet er billigere enn safran',
      'Poteten hører hjemme i Bengal og ble brukt lenge før risen',
      'Den kom fra kjøkkenet til den avsatte nawaben av Awadh i Metiabruz',
      'Britiske offiserer ba om den på 1890-tallet'],
   c:2, why:'Wajid Ali Shah ble avsatt i 1856 og slo seg ned sør for Calcutta med kokkene sine. Om poteten drøyde en slunken kasse eller var en dyr nyhet, er omstridt.'},
  {q:'Hvilket av disse er et varig portugisisk spor i Bengal?',
   a:['Panch phoron',
      'Ordet pauruti for loff, og bandelosten',
      'Skikken med å spise med høyre hånd',
      'Forkokingen av risen'],
   c:1, why:'Bengali tok pauruti, almari, balti, janla og girja fra portugisisk, og en røkt ost fra bosetningen ved Hooghly lages og selges fortsatt i Kolkata.'}
 ]
];
