/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-BEN'] = [
 [
  {q:'Why is panch phoron never ground?',
   a:['Grinding is forbidden by custom rather than by cooking',
      'The five seeds cook at different rates, and whole they stay separate in the dish',
      'The mix is too oily to grind on a stone',
      'It is ground in Bengal, but not in Odisha'],
   c:1, why:'Fenugreek burns in seconds while fennel needs longer. Ground together they would all cook at the same rate and taste of nothing in particular.'},
  {q:'Why is mustard oil heated hard before anything else goes into the pan?',
   a:['To sterilise it, because it is cold-pressed',
      'To make it hot enough to seal the fish',
      'To drive off its raw pungency and leave a nutty warmth',
      'To separate it, so the solids can be removed'],
   c:2, why:'Cold-pressed mustard oil is sharp with allyl isothiocyanate. Heating it until it just smokes burns that raw edge off, and skipping the step leaves the dish tasting of the bottle.'},
  {q:'What turns a raw mustard paste bitter?',
   a:['Grinding it too long, or cooking it hard',
      'Adding salt to it',
      'Using cold water instead of warm',
      'Leaving it to stand for an hour'],
   c:0, why:'Heat with water present sets off the enzyme that makes the bitter compounds. So the paste is ground quickly with salt and turmeric, and goes in near the end.'}
 ],
 [
  {q:'Why does the east of India eat so much rice?',
   a:['The British replaced wheat with rice in the nineteenth century',
      'The soil is too poor for wheat',
      'It sits on the Ganges–Brahmaputra delta, which is flat, silted and very wet',
      'Rice was brought by traders from Java and took over'],
   c:2, why:'The two rivers have built the largest delta on earth. Flat land, silt renewed every year and well over a metre and a half of monsoon rain are exactly what rice wants.'},
  {q:'What is panta bhat, or pakhala?',
   a:['Rice cooked in milk and jaggery',
      'Cooked rice left in water overnight, eaten cool and faintly sour',
      'The first rice of the aman harvest',
      'Rice flour steamed in a bamboo cylinder'],
   c:1, why:'It began as a way of keeping cooked rice edible through a hot night without a fridge, and became something people want for its own sake. Odisha holds a day for it every March.'},
  {q:'Why does a Bengali meal open with something bitter?',
   a:['Bitter vegetables spoil fastest, so they are eaten first',
      'It is a Portuguese habit that stuck',
      'Bitterness opens the appetite, and sourness at the end closes it',
      'The bitter dish is a palate cleanser between fish courses'],
   c:2, why:'The principle comes from Ayurveda, but it works on its own terms: a plain bitter dish first makes everything after it taste stronger.'}
 ],
 [
  {q:'Why is ilish never washed once it has been cut?',
   a:['River water would spoil it',
      'Washing removes the oil that makes the fish worth eating',
      'It loosens the bones and they come out in the gravy',
      'The scales would come away with the water'],
   c:1, why:'Hilsa is prized for its fat, and the oil rinses straight off cut flesh. That fat is also why Bengal tolerates a fish full of fine forked bones.'},
  {q:'What does the word kosha describe?',
   a:['A pot the meat is sealed into',
      'A blend of whole garam masala',
      'Frying something down slowly with very little liquid',
      'A cut of goat taken from the shoulder'],
   c:2, why:'Kosha mangsho is named for its technique. The cook fries the meat down, adds a splash of water whenever it catches, and fries it down again for the best part of an hour.'},
  {q:'How did the dispute over who invented the rasgulla end?',
   a:['West Bengal won, and Odisha withdrew its claim',
      'Odisha won on the strength of the Jagannath temple records',
      'Neither claim was registered, so both remain informal',
      'Both states hold geographical indications, for two differently named products'],
   c:3, why:'Banglar Rasogolla was registered in 2017 and Odisha Rasagola in 2019. They are recognised as different products, which is the honest outcome.'}
 ],
 [
  {q:'Why is the Portuguese claim to have taught Bengal to split milk doubted?',
   a:['No Portuguese ever settled in Bengal',
      'The twelfth-century Manasollasa already describes making something very like chhana',
      'Chhana is not used in Bengali sweets at all',
      'The Dutch reached the Hooghly first'],
   c:1, why:'The technique was known in India well before any Portuguese ship rounded Africa, and Bengal\'s professional sweet-makers were not bound by the domestic taboo the story depends on.'},
  {q:'Why does Kolkata biryani contain a whole potato?',
   a:['The rice is stretched because potato is cheaper than saffron',
      'Potato is native to Bengal and was used long before rice',
      'It came from the exiled Nawab of Awadh\'s kitchen at Metiabruz',
      'British officers asked for it in the 1890s'],
   c:2, why:'Wajid Ali Shah was deposed in 1856 and settled south of Calcutta with his cooks. Whether the potato stretched thin funds or was an expensive novelty is disputed.'},
  {q:'Which of these is a lasting Portuguese trace in Bengal?',
   a:['Panch phoron',
      'The word pauruti for a loaf of bread, and Bandel cheese',
      'The custom of eating with the right hand',
      'The parboiling of rice'],
   c:1, why:'Bengali took pauruti, almari, balti, janla and girja from Portuguese, and a smoked cheese from the Hooghly settlement is still made and sold in Kolkata.'}
 ]
];
