/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-BEN'] = [
 [
  {q:'Why is the course panch phoron kept whole?',
   a:['Grinding is forbidden in every Bengali recipe',
      'Whole seeds release aroma at different rates and remain distinct in the dish',
      'The mix is too oily to grind on a stone',
      'It is ground in Bengal, but not in Odisha'],
   c:1, why:'Whole seeds retain distinct textures and aromas during tempering. Panch phoron formulas and the moment they are added can vary.'},
  {q:'Why do many cooks heat mustard oil before frying?',
   a:['To sterilise it, because it is cold-pressed',
      'To make it hot enough to seal the fish',
      'To drive off its raw pungency and leave a nutty warmth',
      'To separate it, so the solids can be removed'],
   c:2, why:'Heating softens the raw pungency of cold-pressed mustard oil. Other preparations deliberately retain some raw oil as a finishing flavour.'},
  {q:'Which factors can change a mustard paste\'s heat and bitterness?',
   a:['Seed colour, soaking, grinding and cooking',
      'Adding salt to it',
      'Using cold water instead of warm',
      'Leaving it to stand for an hour'],
   c:0, why:'Mustard ratios and handling affect the result. This course grinds briefly and cooks gently, but household methods differ.'}
 ],
 [
  {q:'Why is rice so important in Bengal\'s lowlands?',
   a:['The British replaced wheat with rice in the nineteenth century',
      'The soil is too poor for wheat',
      'It sits on the Ganges–Brahmaputra delta, which is flat, silted and very wet',
      'Rice was brought by traders from Java and took over'],
   c:2, why:'River lowlands, monsoon rain and irrigation support several rice seasons. Uplands elsewhere in the course region have different crop patterns.'},
  {q:'Which is the course\'s safer approach to panta bhat or pakhala?',
   a:['Rice cooked in milk and jaggery',
      'Use tested fermentation, or chill cooked rice promptly and add cold water later',
      'The first rice of the aman harvest',
      'Rice flour steamed in a bamboo cylinder'],
   c:1, why:'Cooked rice at room temperature can support Bacillus cereus. Traditional dishes have several methods, but the course does not advise an uncontrolled overnight rest.'},
  {q:'What best describes the order of a formal Bengali meal?',
   a:['Bitter vegetables spoil fastest, so they are eaten first',
      'It is a Portuguese habit that stuck',
      'It may open with bitter food and move through dal and curries to chutney and sweets',
      'The bitter dish is a palate cleanser between fish courses'],
   c:2, why:'This is a recognised formal progression, not a fixed rule for every household or an established nutritional law.'}
 ],
 [
  {q:'What most affects the future of wild hilsa runs?',
   a:['Whether cooks wash the cut fish',
      'Healthy migration routes and protection of juveniles and spawning fish',
      'It loosens the bones and they come out in the gravy',
      'The scales would come away with the water'],
   c:1, why:'Fishing pressure and river barriers affect this migratory species. Conservation protects vulnerable life stages and river connections.'},
  {q:'What does the word kosha describe?',
   a:['A pot the meat is sealed into',
      'A blend of whole garam masala',
      'Frying something down slowly with very little liquid',
      'A cut of goat taken from the shoulder'],
   c:2, why:'Kosha mangsho is named for its technique. The cook fries the meat down, adds a splash of water whenever it catches, and fries it down again for the best part of an hour.'},
  {q:'How did the dispute over who invented the rasgulla end?',
   a:['West Bengal won, and Odisha withdrew its claim',
      'Odisha won on the strength of the Jagannath temple records',
      'Neither claim was registered, so both remain informal',
      'Both states hold geographical indications, for two differently named products'],
   c:3, why:'Banglar Rasogolla and Odisha Rasagola are separate registered products. A geographical indication does not settle the historical question of invention.'}
 ],
 [
  {q:'Why is the Portuguese claim to have taught Bengal to split milk doubted?',
   a:['No Portuguese ever settled in Bengal',
      'The twelfth-century Manasollasa already describes making something very like chhana',
      'Chhana is not used in Bengali sweets at all',
      'The Dutch reached the Hooghly first'],
   c:1, why:'The technique was known in India well before any Portuguese ship rounded Africa, and Bengal\'s professional sweet-makers were not bound by the domestic taboo the story depends on.'},
  {q:'What is the firmest historical link behind Kolkata biryani?',
   a:['The rice is stretched because potato is cheaper than saffron',
      'Potato is native to Bengal and was used long before rice',
      'Wajid Ali Shah\'s household carried Awadhi food traditions to Metiabruz',
      'British officers asked for it in the 1890s'],
   c:2, why:'Wajid Ali Shah settled at Metiabruz after his 1856 deposition. The budget and novelty stories about the potato remain undocumented.'},
  {q:'Which of these is a lasting Portuguese trace in Bengal?',
   a:['Panch phoron',
      'Loanwords such as almari and girja, and the Bandel cheese tradition',
      'The custom of eating with the right hand',
      'The parboiling of rice'],
   c:1, why:'Portuguese contact left linguistic and food traces in the Hooghly region, though individual word histories and direct lines of descent need care.'}
 ]
];
