/* Masala Dabba — oppsummeringsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme fasitindeks som den engelske fila. Spørsmålene leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-CEN'] = [
 [
  {q:'Hvorfor er hvite valmuefrø billige og lette å få tak i i Malwa?',
   a:['De dyrkes på åkrene for oljens skyld',
      'De er det lovlige biproduktet av lisensiert opiumsvalmue',
      'De importeres fra Tyrkia gjennom havnene i vest',
      'Delstaten subsidierer dem for å hjelpe dem som lager søtsaker'],
   c:1, why:'Malwa var et av Indias store opiumsdistrikter, og lisensiert dyrking fortsetter i delstaten. Opiumen kommer fra frøkapselen, og frøene blir til overs.'},
  {q:'Hva er mahua?',
   a:['Frøet inni en liten steinfrukt fra skogen',
      'En kapsel som tørkes over vedfyr og brukes i kjøttretter',
      'Blomsten til et skogstre, som faller om natten om våren',
      'Et surt fruktkjøtt som presses til mørke blokker'],
   c:2, why:'Madhuca longifolia slipper blomsterkronene om natten i mars og april, og de sopes sammen i grålysningen og tørkes i sola.'},
  {q:'Hvorfor er det ingen chili i garam masalaen fra Bhopal?',
   a:['Chili dyrkes ikke i Madhya Pradesh',
      'Hoffkjøkkenet den kommer fra, var vegetarisk',
      'Med chili i ville den malte blandingen bli dårlig i hylla',
      'Da kan den gå i sent og i rikelig mengde, mens styrken bestemmes for seg'],
   c:3, why:'Når chilien holdes utenfor, kan kokken bruke duften fritt og så bestemme styrken med den chilien retten faktisk trenger.'}
 ],
 [
  {q:'Hvorfor sås hveten i Malwa i oktober?',
   a:['Den svarte jorda holder på vannet fra monsunen, så avlingen vokser på fuktighet som alt ligger i bakken',
      'Vinterregnet på platået er for kraftig for hvete',
      'Platået er fritt for frost bare fra oktober',
      'Vanningskanalene åpnes i oktober'],
   c:0, why:'Den svarte basaltjorda i Malwa lagrer vann som en svamp, så hveten og kikertene sås etter monsunen i stedet for å vente på regn.'},
  {q:'Hva er basi?',
   a:['Rismel som klappes flatt og bakes mellom blader',
      'Kokt ris som står i vann over natten og spises kald om morgenen',
      'En bolle av kikertmel som dampes i stedet for å friteres',
      'En tynn, sur gryte av grønnsaker og bambusskudd'],
   c:1, why:'Det begynte som en måte å holde kokt ris spiselig gjennom en varm natt uten kjøleskap, og nå markerer Chhattisgarh sin egen utgave offentlig den første mai.'},
  {q:'Hva er uvanlig med frokosten i Malwa, der folk ellers spiser hvete?',
   a:['Den er alltid søt',
      'Den inneholder ikke korn i det hele tatt',
      'Den er laget av ris, for poha er flattrykt ris',
      'Den spises bare på markedsdager'],
   c:2, why:'Poha er forvellet ris som er valset flat og tørket. Indore spiser store porsjoner av den fra halv åtte, og ingen tenker på den som en risrett.'}
 ],
 [
  {q:'Hva skiller en bafla fra en bati fra Rajasthan?',
   a:['Baflaen er laget av kikertmel og ikke av hvete',
      'Baflaen kokes før den bakes',
      'Baflaen legges aldri i ghee',
      'Baflaen dampes mellom blader'],
   c:1, why:'Kokingen forklistrer stivelsen før tørrvarmen kommer til, så en bafla holder seg myk og litt fuktig inni, mens en bati er tett og tørr.'},
  {q:'Hvorfor er sukkermais feil mais til bhutte ka kees?',
   a:['Den får melka til å skille seg',
      'Den lar seg ikke rive rå',
      'Den trenger mye lengre koketid',
      'Sødmen gjør en rett som ikke skal være søt, til noe som ligner en dessert'],
   c:3, why:'Retten virker fordi maisstivelsen tykner melka, og mais som ikke er foredlet for sødme, gir den tykningen uten sukkeret i sukkermaisen.'},
  {q:'Hva gir kormaen fra Bhopal fylden?',
   a:['Fløte som røres inn til slutt',
      'Tomat som er kokt ned til en masse',
      'Brunet løk, yoghurt og malte valmuefrø',
      'Kikertmel som er ristet i ghee'],
   c:2, why:'Det er verken fløte eller tomat i den. Løken brunes og males, yoghurten røres langsomt inn, og valmuefrøene tykner sausen.'}
 ],
 [
  {q:'Hva forteller Ashokas første store bergedikt om kjøkkenet hans?',
   a:['At det hadde tusen kokker',
      'At slaktingen var nede i to påfugler og en hjort',
      'At kjøtt var forbudt i hele riket',
      'At palasset bare spiste ris og melk'],
   c:1, why:'Ediktet sier at hundretusener av dyr tidligere ble slaktet hver dag til bordet, at tallet nå var tre, og at heller ikke disse tre skulle slaktes i framtida.'},
  {q:'Hvilke år styrte de fire begumene Bhopal etter hverandre?',
   a:['Fra 1819 til 1926',
      'Fra 1750 til 1818',
      'Fra 1857 til 1900',
      'Fra 1901 til 1947'],
   c:0, why:'Qudsia, Sikandar, Shah Jahan og Sultan Jahan styrte etter hverandre i hundre og sju år, til Sultan Jahan abdiserte til fordel for sønnen.'},
  {q:'Hva er chapda?',
   a:['En pickle laget av unge bambusskudd',
      'En sopp som kommer etter det første kraftige regnet',
      'En chutney av røde maur og eggene deres',
      'Et flatbrød som bakes mellom blader av sal'],
   c:2, why:'Maurene inneholder maursyre, så chutneyen er skarpt sur, og den spises i små mengder til ris, slik man spiser en pickle.'}
 ]
];
