/* Masala Dabba — oppsummeringsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme fasitindeks som den engelske fila. Spørsmålene leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-CEN'] = [
 [
  {q:'Hvordan henger valmuefrø til mat sammen med regulert opiumsdyrking?',
   a:['De lages ved å male de tørkede blomsterbladene',
      'Det modne frøet kommer fra samme plante som gir opium fra den umodne kapselen',
      'De importeres fra Tyrkia gjennom havnene i vest',
      'Delstaten subsidierer dem for å hjelpe dem som lager søtsaker'],
   c:1, why:'Malwa var historisk viktig i opiumshandelen, og lisensiert dyrking fortsetter i utvalgte områder. Frø til mat kommer fra modne frø av samme plante.'},
  {q:'Hva er mahua?',
   a:['Frøet inni en liten steinfrukt fra skogen',
      'En kapsel som tørkes over vedfyr og brukes i kjøttretter',
      'Blomsten til et skogstre, som faller om natten om våren',
      'Et surt fruktkjøtt som presses til mørke blokker'],
   c:2, why:'Mahua-trær slipper søte blomster i en kort vårsesong. De sankede blomstene kan tørkes til mat, salg eller gjæring.'},
  {q:'Hvorfor er det ingen chili i blandingen i Bhopal-stil som brukes her?',
   a:['Chili dyrkes ikke i Madhya Pradesh',
      'Hoffkjøkkenet den kommer fra, var vegetarisk',
      'Med chili i ville den malte blandingen bli dårlig i hylla',
      'Da kan den gå i sent og i rikelig mengde, mens styrken bestemmes for seg'],
   c:3, why:'I kursblandingen lar skillet mellom chili og aromatiske krydder kokken justere duft og styrke hver for seg. Andre blandinger kan være annerledes.'}
 ],
 [
  {q:'Hvorfor sås hveten i Malwa i oktober?',
   a:['Den svarte jorda holder på vannet fra monsunen, så avlingen vokser på fuktighet som alt ligger i bakken',
      'Vinterregnet på platået er for kraftig for hvete',
      'Platået er fritt for frost bare fra oktober',
      'Vanningskanalene åpnes i oktober'],
   c:0, why:'Den svarte jorda i Malwa holder på monsunfuktighet og støtter vinterhvete og kikerter sammen med nedbør og vanning.'},
  {q:'Hva er basi?',
   a:['Rismel som klappes flatt og bakes mellom blader',
      'Kokt ris som står i vann over natten og spises kald om morgenen',
      'En bolle av kikertmel som dampes i stedet for å friteres',
      'En tynn, sur gryte av grønnsaker og bambusskudd'],
   c:1, why:'Basi tilhører en familie av bløtlagte eller gjærede risretter. Kokt ris kan gi vekstvilkår for skadelige bakterier, så moderne tilberedning krever rask kjøling og en kontrollert, mattrygg metode.'},
  {q:'Hva er uvanlig med frokosten i Malwa, der folk ellers spiser hvete?',
   a:['Den er alltid søt',
      'Den inneholder ikke korn i det hele tatt',
      'Den er laget av ris, for poha er flattrykt ris',
      'Den spises bare på markedsdager'],
   c:2, why:'Poha er forvellet, flattrykt og tørket ris. Betydningen i Indore viser at en hvetedyrkende region også kan feire en risfrokost.'}
 ],
 [
  {q:'Hva skiller en bafla fra en bati fra Rajasthan?',
   a:['Baflaen er laget av kikertmel og ikke av hvete',
      'Baflaen kokes før den bakes',
      'Baflaen legges aldri i ghee',
      'Baflaen dampes mellom blader'],
   c:1, why:'Småkoking av deigbollene før tørrvarmen er det avgjørende trinnet i bafla og bidrar til en mykere kjerne.'},
  {q:'Hvorfor kan en kokk velge mindre søt mais til bhutte ka kees?',
   a:['Den får melka til å skille seg',
      'Den lar seg ikke rive rå',
      'Den trenger mye lengre koketid',
      'Sødmen gjør en rett som ikke skal være søt, til noe som ligner en dessert'],
   c:3, why:'Mindre søt, moden mais gir et saltere resultat. Sukkermais fungerer også, men gir en søtere variant.'},
  {q:'Hva gir kursoppskriften på korma fra Bhopal fylde?',
   a:['Fløte som røres inn til slutt',
      'Tomat som er kokt ned til en masse',
      'Brunet løk, yoghurt og malte valmuefrø',
      'Kikertmel som er ristet i ghee'],
   c:2, why:'Denne utgaven bruker brunet løk, yoghurt og malte valmuefrø i stedet for fløte eller tomat. Andre kormaer fra Bhopal kan være annerledes.'}
 ],
 [
  {q:'Hva forteller Ashokas første store bergedikt om kjøkkenet hans?',
   a:['At det hadde tusen kokker',
      'At slaktingen var nede i to påfugler og en hjort',
      'At kjøtt var forbudt i hele riket',
      'At palasset bare spiste ris og melk'],
   c:1, why:'Ediktet sier at hundretusener av dyr tidligere ble slaktet hver dag til bordet, at tallet nå var tre, og at heller ikke disse tre skulle slaktes i framtida.'},
  {q:'Hvilket tidsspenn forbindes med epoken til de fire begumene i Bhopal?',
   a:['Fra 1819 til 1926',
      'Fra 1750 til 1818',
      'Fra 1857 til 1900',
      'Fra 1901 til 1947'],
   c:0, why:'Qudsia, Sikandar, Shah Jahan og Sultan Jahan preget dynastiet mellom 1819 og 1926, en periode som også rommet regentskap og avbrudd.'},
  {q:'Hva er chapda?',
   a:['En pickle laget av unge bambusskudd',
      'En sopp som kommer etter det første kraftige regnet',
      'En chutney av røde maur og eggene deres',
      'Et flatbrød som bakes mellom blader av sal'],
   c:2, why:'Maurene inneholder maursyre, så chutneyen er skarpt sur, og den spises i små mengder til ris, slik man spiser en pickle.'}
 ]
];
