/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-CEN'] = [
 [
  {q:'Why is white poppy seed cheap and plentiful in Malwa?',
   a:['It is grown as a field crop for its oil',
      'It is the legal by-product of a licensed opium poppy crop',
      'It is imported from Turkey through the western ports',
      'The state subsidises it for the sweet trade'],
   c:1, why:'Malwa was one of India\'s great opium districts, licensed cultivation continues in the state, and opium comes from the pod while the seed is the leftover.'},
  {q:'What is mahua?',
   a:['The seed inside a small forest stone fruit',
      'A pod dried over a wood fire and used in meat dishes',
      'The flower of a forest tree, which falls overnight in spring',
      'A sour pulp pressed into dark blocks'],
   c:2, why:'Madhuca longifolia sheds its corollas in the night through March and April, and they are swept up at first light and dried in the sun.'},
  {q:'Why does Bhopal\'s garam masala contain no chilli?',
   a:['Chilli is not grown in Madhya Pradesh',
      'The court kitchen it comes from was vegetarian',
      'Chilli would make the ground blend spoil on the shelf',
      'So it can go in late and generously while the heat is set separately'],
   c:3, why:'Keeping the chilli out means the cook can add aroma freely and then decide the heat with whatever chilli the dish actually needs.'}
 ],
 [
  {q:'Why is Malwa\'s wheat sown in October?',
   a:['The black soil holds the monsoon, so the crop grows on moisture already in the ground',
      'Winter rain on the plateau is too heavy for wheat',
      'The plateau is free of frost only from October',
      'The irrigation canals are opened in October'],
   c:0, why:'Malwa\'s black basalt soil stores water like a sponge, so wheat and gram go in after the monsoon rather than waiting for rain.'},
  {q:'What is basi?',
   a:['Rice flour patted flat and baked between leaves',
      'Cooked rice left in water overnight and eaten cool in the morning',
      'A gram-flour dumpling that is steamed rather than fried',
      'A thin sour stew of vegetables and bamboo shoot'],
   c:1, why:'It began as a way of keeping cooked rice edible through a hot night without a fridge, and Chhattisgarh now marks its own version publicly on the first of May.'},
  {q:'What is unusual about breakfast in wheat-eating Malwa?',
   a:['It is always sweet',
      'It contains no grain at all',
      'It is made of rice, because poha is flattened rice',
      'It is eaten only on market days'],
   c:2, why:'Poha is parboiled rice rolled flat and dried, and Indore eats plates of it from half past seven without thinking of it as a rice dish.'}
 ],
 [
  {q:'What separates a bafla from a Rajasthani bati?',
   a:['The bafla is made from gram flour rather than wheat',
      'The bafla is boiled before it is baked',
      'The bafla is never soaked in ghee',
      'The bafla is steamed between leaves'],
   c:1, why:'Boiling gelatinises the starch before the dry heat reaches it, so a bafla stays soft and slightly moist inside where a bati is dense and dry.'},
  {q:'Why is sweetcorn the wrong corn for bhutte ka kees?',
   a:['It curdles the milk',
      'It cannot be grated while raw',
      'It takes far longer to cook through',
      'Its sugar turns a savoury dish into something closer to a pudding'],
   c:3, why:'The dish works because corn starch thickens milk, and field corn gives that thickening without the sweetness sweetcorn was bred for.'},
  {q:'What gives a Bhopali korma its body?',
   a:['Cream stirred in at the end',
      'Tomato cooked down to a paste',
      'Browned onion, yoghurt and poppy-seed paste',
      'Gram flour toasted in ghee'],
   c:2, why:'There is no cream and no tomato in it. The onion is browned and ground, the yoghurt is cooked in slowly, and the poppy seed thickens the gravy.'}
 ],
 [
  {q:'What does Ashoka\'s first Major Rock Edict record about his kitchen?',
   a:['That it employed a thousand cooks',
      'That the killing was down to two peacocks and a deer',
      'That meat was forbidden throughout the empire',
      'That the palace ate only rice and milk'],
   c:1, why:'The edict says hundreds of thousands of animals had been killed daily for the table, that the number was now three, and that even these three would not be killed in future.'},
  {q:'Over what years did the four Begums rule Bhopal in succession?',
   a:['From 1819 to 1926',
      'From 1750 to 1818',
      'From 1857 to 1900',
      'From 1901 to 1947'],
   c:0, why:'Qudsia, Sikandar, Shah Jahan and Sultan Jahan ruled one after another for a hundred and seven years, until Sultan Jahan abdicated in favour of her son.'},
  {q:'What is chapda?',
   a:['A pickle made from young bamboo shoots',
      'A mushroom that appears after the first heavy rain',
      'A chutney ground from red weaver ants and their eggs',
      'A flatbread baked between sal leaves'],
   c:2, why:'The ants carry formic acid, so the chutney is sharply sour, and it is eaten in small quantities with rice in the way a pickle is.'}
 ]
];
