/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-CEN'] = [
 [
  {q:'How is culinary poppy seed connected with regulated opium cultivation?',
   a:['It is made by grinding the dried flower petals',
      'The mature seed comes from the same plant whose unripe pod yields opium',
      'It is imported from Turkey through the western ports',
      'The state subsidises it for the sweet trade'],
   c:1, why:'Malwa was historically important in the opium trade, and licensed cultivation continues in selected areas. Culinary seed comes from the mature seed of the same plant.'},
  {q:'What is mahua?',
   a:['The seed inside a small forest stone fruit',
      'A pod dried over a wood fire and used in meat dishes',
      'The flower of a forest tree, which falls overnight in spring',
      'A sour pulp pressed into dark blocks'],
   c:2, why:'Mahua trees drop sweet flowers during a short spring season. The collected flowers can be dried for food, sale or fermentation.'},
  {q:'Why does the Bhopali-style garam masala used here contain no chilli?',
   a:['Chilli is not grown in Madhya Pradesh',
      'The court kitchen it comes from was vegetarian',
      'Chilli would make the ground blend spoil on the shelf',
      'So it can go in late and generously while the heat is set separately'],
   c:3, why:'In this course blend, keeping chilli separate lets the cook adjust aroma and pungency independently. Other blends may differ.'}
 ],
 [
  {q:'Why is Malwa\'s wheat sown in October?',
   a:['The black soil holds the monsoon, so the crop grows on moisture already in the ground',
      'Winter rain on the plateau is too heavy for wheat',
      'The plateau is free of frost only from October',
      'The irrigation canals are opened in October'],
   c:0, why:'Malwa\'s black soils retain monsoon moisture, which helps support winter wheat and gram alongside rainfall and irrigation.'},
  {q:'What is basi?',
   a:['Rice flour patted flat and baked between leaves',
      'Cooked rice left in water overnight and eaten cool in the morning',
      'A gram-flour dumpling that is steamed rather than fried',
      'A thin sour stew of vegetables and bamboo shoot'],
   c:1, why:'Basi belongs to a family of soaked or fermented rice dishes. Because cooked rice can support harmful bacteria, modern preparation needs prompt cooling and a controlled, food-safe method.'},
  {q:'What is unusual about breakfast in wheat-eating Malwa?',
   a:['It is always sweet',
      'It contains no grain at all',
      'It is made of rice, because poha is flattened rice',
      'It is eaten only on market days'],
   c:2, why:'Poha is parboiled, flattened and dried rice. Its importance in Indore shows that a wheat-growing region can also celebrate a rice breakfast.'}
 ],
 [
  {q:'What separates a bafla from a Rajasthani bati?',
   a:['The bafla is made from gram flour rather than wheat',
      'The bafla is boiled before it is baked',
      'The bafla is never soaked in ghee',
      'The bafla is steamed between leaves'],
   c:1, why:'Simmering the dough balls before dry heat is the defining step in bafla and helps produce a softer centre.'},
  {q:'Why might a cook choose less-sweet corn for bhutte ka kees?',
   a:['It curdles the milk',
      'It cannot be grated while raw',
      'It takes far longer to cook through',
      'Its sugar turns a savoury dish into something closer to a pudding'],
   c:3, why:'Less-sweet mature corn produces a more savoury dish. Sweetcorn still works, but makes a sweeter variation.'},
  {q:'What gives the course\'s Bhopali korma its body?',
   a:['Cream stirred in at the end',
      'Tomato cooked down to a paste',
      'Browned onion, yoghurt and poppy-seed paste',
      'Gram flour toasted in ghee'],
   c:2, why:'This version uses browned onion, yoghurt and poppy-seed paste rather than cream or tomato; other Bhopali kormas may differ.'}
 ],
 [
  {q:'What does Ashoka\'s first Major Rock Edict record about his kitchen?',
   a:['That it employed a thousand cooks',
      'That the killing was down to two peacocks and a deer',
      'That meat was forbidden throughout the empire',
      'That the palace ate only rice and milk'],
   c:1, why:'The edict says hundreds of thousands of animals had been killed daily for the table, that the number was now three, and that even these three would not be killed in future.'},
  {q:'Which span is associated with the era of Bhopal\'s four Begums?',
   a:['From 1819 to 1926',
      'From 1750 to 1818',
      'From 1857 to 1900',
      'From 1901 to 1947'],
   c:0, why:'Qudsia, Sikandar, Shah Jahan and Sultan Jahan shaped the dynasty between 1819 and 1926, a span that also included regencies and interruptions.'},
  {q:'What is chapda?',
   a:['A pickle made from young bamboo shoots',
      'A mushroom that appears after the first heavy rain',
      'A chutney ground from red weaver ants and their eggs',
      'A flatbread baked between sal leaves'],
   c:2, why:'The ants carry formic acid, so the chutney is sharply sour, and it is eaten in small quantities with rice in the way a pickle is.'}
 ]
];
