/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-KON'] = [
 [
  {q:'Where did the chilli in Indian cooking come from?',
   a:['It was domesticated in the Western Ghats',
      'Arab merchants brought it overland from Persia',
      'Portuguese ships carried it east from Brazil',
      'It arrived with the Mughals from Central Asia'],
   c:2, why:'Capsicum is American. It came east on Portuguese ships and landed on this coast in the sixteenth century, and every chilli in the other thirteen regions of this course descends from that arrival.'},
  {q:'What carried the heat in an Indian kitchen before the chilli arrived?',
   a:['Mustard oil and asafoetida',
      'Black pepper and long pepper',
      'Kokum and tamarind',
      'Ginger and green mango'],
   c:1, why:'Both warm rather than burn, and both were expensive enough to be shipped to Rome. The chilli grew in any backyard and pushed long pepper almost out of the cooking pot.'},
  {q:'Why does a jar of recheado paste keep for months?',
   a:['It is boiled before it is jarred',
      'It is sealed under a layer of ghee',
      'The chillies are smoked before grinding',
      'It is ground in vinegar and never sees water'],
   c:3, why:'Vinegar is the only liquid that goes into it at any stage. The same paste loosened with water would spoil within a week.'}
 ],
 [
  {q:'What does ukda mean?',
   a:['Par-boiled',
      'Red-grained',
      'Freshly milled',
      'Grown on tidal land'],
   c:0, why:'The paddy is soaked, steamed while still in the husk and dried before milling, exactly as Kerala treats its matta rice.'},
  {q:'What is a khazan?',
   a:['A stone used for grinding the coconut masala',
      'Tidal land farmed behind bunds and wooden sluice gates',
      'A steamed rice cake raised with palm toddy',
      'The morning fish market of a coastal village'],
   c:1, why:'The gates open on the ebb to drain the field and shut on the flood to keep the salt out, and the salt-tolerant korgut rice is bred for that ground.'},
  {q:'What gives solkadhi its pink colour?',
   a:['Beetroot cooked into the coconut milk',
      'Kashmiri chilli, added for colour rather than heat',
      'Kokum rind steeped in warm water',
      'The unglazed clay it is served in'],
   c:2, why:'The colour is entirely the fruit, and nothing is added to make it pink. Thin coconut milk, garlic and salt go in afterwards.'}
 ],
 [
  {q:'Where does the second half of the word vindaloo come from?',
   a:['The Hindi and Marathi word for potato',
      'A Konkani word meaning soured',
      'The name of a village in Salcete',
      'Portuguese alho, meaning garlic'],
   c:3, why:'The dish is carne de vinha d\'alhos, meat in wine and garlic. The resemblance to aloo is a coincidence, and the Goan original contains no potato.'},
  {q:'Why is sorpotel made three or four days before it is eaten?',
   a:['Reheating it daily drives off water and pushes the vinegar into the meat',
      'The blood has to settle out before the dish is served',
      'The pork needs that long to cure in salt',
      'It has to cool completely before the liver can be added'],
   c:0, why:'Each reheating concentrates the dish, and the fourth-day version is a different and better one from the first-day version.'},
  {q:'What kind of dish is balchao?',
   a:['A dry masala of roasted coconut and whole spice',
      'A thin soured gravy poured over rice',
      'A preserve kept in a jar and eaten a spoonful at a time',
      'A steamed cake eaten with pork at Christmas'],
   c:2, why:'The prawns are cooked down in chilli, garlic and vinegar until almost no liquid is left, then jarred under oil. A tablespoon is a serving.'}
 ],
 [
  {q:'How long did Portugal hold Goa?',
   a:['From 1498, when Vasco da Gama reached the coast, until 1947',
      'Four hundred and fifty-one years, from 1510 to 1961',
      'About two hundred years, ending when the capital moved to Panaji',
      'Three hundred years, ending with the Inquisition in 1812'],
   c:1, why:'Albuquerque took the city on 25 November 1510 and the Indian army entered in December 1961, which is longer than any European power held any territory in Asia.'},
  {q:'Why do the Mangeshi and Shanta Durga temples stand at Ponda?',
   a:['Ponda had the only fresh water on that stretch of coast',
      'The Portuguese built them there for converts who would not give up the old rites',
      'Their deities were carried there when the temples nearer the coast were demolished',
      'They were moved when cholera emptied Old Goa in the nineteenth century'],
   c:2, why:'Temples in the Old Conquests were pulled down from the 1540s, and villagers took their deities across the river into territory Portugal did not control.'},
  {q:'Which part of the cashew is feni distilled from?',
   a:['The fleshy fruit that the nut hangs from',
      'The nut itself, after it has been roasted',
      'The bark, boiled and then fermented',
      'The flowers, collected before dawn'],
   c:0, why:'The nut was the export crop. The cashew apple rots within a day and could not be sold, so Goa crushed it, fermented it and distilled it.'}
 ]
];
