/* Masala Dabba — oppsummeringsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme riktige svarindeks som den engelske filen. Spørsmål leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-KON'] = [
 [
  {q:'Hvor kom chilien i indisk matlaging fra?',
   a:['Den ble domestisert i Vestghatene',
      'Arabiske kjøpmenn brakte den over land fra Persia',
      'Portugisiske skip fraktet den østover fra Brasil',
      'Den kom med mogulene fra Sentral-Asia'],
   c:2, why:'Capsicum er amerikansk. Portugisisk sjøhandel førte chilien til India på 1500-tallet. En bok trykt i Goa i 1563 viser at den da var etablert der, men det første ilandstigningsstedet er usikkert.'},
  {q:'Hva ga styrken i et indisk kjøkken før chilien kom?',
   a:['Sennepsolje og asafoetida',
      'Svart pepper og langpepper',
      'Kokum og tamarind',
      'Ingefær og grønn mango'],
   c:1, why:'Svart pepper og langpepper ga styrke før de amerikanske chiliene kom. Chili ble senere utbredt, mens begge de eldre peppersortene fortsatt er i bruk.'},
  {q:'Hvordan bør hjemmelaget recheado-pasta oppbevares?',
   a:['Den kokes opp før den settes på glass',
      'Den forsegles under et lag ghee',
      'Chiliene røykes før de males',
      'Sett den raskt kaldt, bruk den i løpet av få dager eller frys porsjoner'],
   c:3, why:'Eddik samler smaken, men gjør ikke hjemmelaget pasta holdbar i romtemperatur. Hold den kald og frys det du ikke skal bruke snart.'}
 ],
 [
  {q:'Hva betyr ukda?',
   a:['Forkokt',
      'Rødkornet',
      'Nymalt',
      'Dyrket på tidevannsland'],
   c:0, why:'Den uskallede risen bløtlegges, dampes med skallet på og tørkes før den males, nøyaktig slik Kerala behandler mattarisen sin.'},
  {q:'Hva er en khazan?',
   a:['Steinen kokosmasalaen males på',
      'Tidevannsland som dyrkes bak diker og sluseporter av tre',
      'En dampet riskake som heves med palmetoddy',
      'Fiskemarkedet i en kystlandsby om morgenen'],
   c:1, why:'Diker og sluseporter styrer tidevann og saltinnhold. Korgut er én av de lokale rissortene som forbindes med disse krevende forholdene.'},
  {q:'Hva gir solkadhi den rosa fargen?',
   a:['Rødbete kokt inn i kokosmelken',
      'Kashmiri-chili, som brukes for fargen og ikke for styrken',
      'Kokumskall som trekker i lunkent vann',
      'Den uglaserte leiren den serveres i'],
   c:2, why:'Kokum gir ofte solkadhi en blekrosa farge. Nyansen og smaksettingen varierer med frukten, kokosmelken og husholdningens metode.'}
 ],
 [
  {q:'Hvor kommer den siste halvdelen av ordet vindaloo fra?',
   a:['Ordet for potet på hindi og marathi',
      'Et konkani-ord som betyr syrnet',
      'Navnet på en landsby i Salcete',
      'Portugisisk alho, som betyr hvitløk'],
   c:3, why:'Navnet går tilbake til portugisisk vinha d\'alhos, vin og hvitløk. Likheten med aloo er tilfeldig; potet finnes i noen husholdningsvarianter og nyere utgaver.'},
  {q:'Hvorfor lager mange sorpotel på forhånd?',
   a:['En kald hvile lar smakene samle seg før retten varmes grundig opp',
      'Blodet må få skille seg ut før retten serveres',
      'Svinekjøttet trenger så lang tid på å spekes i salt',
      'Den må kjøles helt ned før leveren kan has i'],
   c:0, why:'En hvile i kjøleskap lar smakene samle seg. Kjøl retten raskt ned, oppbevar den kaldt og varm den grundig før servering.'},
  {q:'Hva slags rett er balchão?',
   a:['En tørr masala av ristet kokos og hele krydder',
      'En tynn syrnet saus som helles over ris',
      'En konserves på glass som spises en skje om gangen',
      'En dampet kake som spises til svinekjøtt i julen'],
   c:2, why:'Rekene kokes inn med chili, hvitløk og eddik til en konsentrert, sylteaktig relish. Oppbevar en hjemmelaget porsjon i en ren beholder i kjøleskapet.'}
 ],
 [
  {q:'Hvor lenge satt Portugal med Goa?',
   a:['Fra 1498, da Vasco da Gama nådde kysten, til 1947',
      'Fire hundre og femtien år, fra 1510 til 1961',
      'Omkring to hundre år, fram til hovedstaden flyttet til Panaji',
      'Tre hundre år, fram til inkvisisjonen ble avviklet i 1812'],
   c:1, why:'Albuquerque tok byen 25. november 1510, og indiske styrker rykket inn i desember 1961. Dette var et av de lengste europeiske kolonistyrene i Asia.'},
  {q:'Hvorfor står Mangeshi- og Shanta Durga-templene i Ponda?',
   a:['Ponda hadde det eneste ferskvannet på den kyststrekningen',
      'Portugiserne bygde dem der for omvendte som ikke ville gi slipp på de gamle ritene',
      'Gudebildene ble båret dit da templene nærmere kysten ble revet',
      'De ble flyttet da koleraen tømte Gamle Goa på 1800-tallet'],
   c:2, why:'Templene i de gamle erobringene ble revet fra 1540-årene, og landsbyboerne bar gudebildene sine over elva til et område Portugal ikke rådde over.'},
  {q:'Hvilken del av cashewtreet destilleres feni av?',
   a:['Den kjøttfulle frukten som nøtten henger under',
      'Selve nøtten, etter at den er ristet',
      'Barken, som kokes og deretter gjæres',
      'Blomstene, som samles inn før daggry'],
   c:0, why:'Cashew-feni destilleres av gjæret saft fra cashewfrukten, mens kokos-feni destilleres av gjæret palmesaft.'}
 ]
];
