/* Masala Dabba — oppsummeringsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme riktige svarindeks som den engelske filen. Spørsmål leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-KON'] = [
 [
  {q:'Hvor kom chilien i indisk matlaging fra?',
   a:['Den ble domestisert i Vestghatene',
      'Arabiske kjøpmenn brakte den over land fra Persia',
      'Portugisiske skip fraktet den østover fra Brasil',
      'Den kom med mogulene fra Sentral-Asia'],
   c:2, why:'Capsicum er amerikansk. Den kom østover med portugisiske skip og gikk i land på denne kysten på 1500-tallet, og all chili i de tretten andre regionene i kurset stammer derfra.'},
  {q:'Hva ga styrken i et indisk kjøkken før chilien kom?',
   a:['Sennepsolje og asafoetida',
      'Svart pepper og langpepper',
      'Kokum og tamarind',
      'Ingefær og grønn mango'],
   c:1, why:'Begge varmer heller enn å svi, og begge var dyre nok til å bli fraktet til Roma. Chilien vokste i enhver bakgård og skjøv langpepperen nesten ut av gryta.'},
  {q:'Hvorfor holder et glass recheado-pasta seg i månedsvis?',
   a:['Den kokes opp før den settes på glass',
      'Den forsegles under et lag ghee',
      'Chiliene røykes før de males',
      'Den males i eddik og møter aldri vann'],
   c:3, why:'Eddik er den eneste væsken som går i den på noe tidspunkt. Den samme pastaen ville blitt dårlig i løpet av en uke hvis den var spedd med vann.'}
 ],
 [
  {q:'Hva betyr ukda?',
   a:['Forkokt',
      'Rødkornet',
      'Nymalt',
      'Dyrket på tidevannsland'],
   c:0, why:'Den uskallede risen bløtlegges, dampes med skallet på og tørkes før den males, nøyaktig slik Kerala behandler mattarisen sin.'},
  {q:'Hva er en khazan?',
   a:['Steinen kokosmasalaen males på',
      'Tidevannsland som dyrkes bak diker og sluseporter av tre',
      'En dampet riskake som heves med palmetoddy',
      'Fiskemarkedet i en kystlandsby om morgenen'],
   c:1, why:'Lukene åpnes når vannet trekker seg tilbake, og stenges når det stiger, så saltet holdes ute. Den salttålende korgut-risen er avlet fram for denne jorda.'},
  {q:'Hva gir solkadhi den rosa fargen?',
   a:['Rødbete kokt inn i kokosmelken',
      'Kashmiri-chili, som brukes for fargen og ikke for styrken',
      'Kokumskall som trekker i lunkent vann',
      'Den uglaserte leiren den serveres i'],
   c:2, why:'Fargen kommer helt og holdent fra frukten, og ingenting tilsettes for å gjøre den rosa. Tynn kokosmelk, hvitløk og salt går i etterpå.'}
 ],
 [
  {q:'Hvor kommer den siste halvdelen av ordet vindaloo fra?',
   a:['Ordet for potet på hindi og marathi',
      'Et konkani-ord som betyr syrnet',
      'Navnet på en landsby i Salcete',
      'Portugisisk alho, som betyr hvitløk'],
   c:3, why:'Retten er carne de vinha d\'alhos, kjøtt i vin og hvitløk. Likheten med aloo er tilfeldig, og originalen fra Goa inneholder ikke potet.'},
  {q:'Hvorfor lages sorpotel tre eller fire dager før den skal spises?',
   a:['Daglig oppvarming driver ut vann og presser eddiken inn i kjøttet',
      'Blodet må få skille seg ut før retten serveres',
      'Svinekjøttet trenger så lang tid på å spekes i salt',
      'Den må kjøles helt ned før leveren kan has i'],
   c:0, why:'Hver oppvarming konsentrerer retten, og utgaven på fjerde dag er en annen og bedre rett enn den på første.'},
  {q:'Hva slags rett er balchão?',
   a:['En tørr masala av ristet kokos og hele krydder',
      'En tynn syrnet saus som helles over ris',
      'En konserves på glass som spises en skje om gangen',
      'En dampet kake som spises til svinekjøtt i julen'],
   c:2, why:'Rekene kokes inn i chili, hvitløk og eddik til det nesten ikke er væske igjen, og settes så på glass under olje. En spiseskje er en porsjon.'}
 ],
 [
  {q:'Hvor lenge satt Portugal med Goa?',
   a:['Fra 1498, da Vasco da Gama nådde kysten, til 1947',
      'Fire hundre og femtien år, fra 1510 til 1961',
      'Omkring to hundre år, fram til hovedstaden flyttet til Panaji',
      'Tre hundre år, fram til inkvisisjonen ble avviklet i 1812'],
   c:1, why:'Albuquerque tok byen 25. november 1510, og den indiske hæren rykket inn i desember 1961. Det er lenger enn noen europeisk makt satt med noe område i Asia.'},
  {q:'Hvorfor står Mangeshi- og Shanta Durga-templene i Ponda?',
   a:['Ponda hadde det eneste ferskvannet på den kyststrekningen',
      'Portugiserne bygde dem der for omvendte som ikke ville gi slipp på de gamle ritene',
      'Gudebildene ble båret dit da templene nærmere kysten ble revet',
      'De ble flyttet da koleraen tømte Gamle Goa på 1800-tallet'],
   c:2, why:'Templene i de gamle erobringene ble revet fra 1540-årene, og landsbyboerne bar gudebildene sine over elva til et område Portugal ikke rådde over.'},
  {q:'Hvilken del av cashewtreet destilleres feni av?',
   a:['Den kjøttfulle frukten som nøtten henger under',
      'Selve nøtten, etter at den er ristet',
      'Barken, som kokes og deretter gjæres',
      'Blomstene, som samles inn før daggry'],
   c:0, why:'Nøtten var eksportvaren. Cashewfrukten råtner i løpet av et døgn og lot seg ikke selge, så Goa knuste den, gjæret den og destillerte den.'}
 ]
];
