/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-KON'] = [
 [
  {q:'Where did the chilli in Indian cooking come from?',
   a:['It was domesticated in the Western Ghats',
      'Arab merchants brought it overland from Persia',
      'Portuguese ships carried it east from Brazil',
      'It arrived with the Mughals from Central Asia'],
   c:2, why:'Capsicum is American. Portuguese maritime trade carried it to India in the sixteenth century; a book printed in Goa in 1563 shows that it was established there, although the exact first landing is uncertain.'},
  {q:'What carried the heat in an Indian kitchen before the chilli arrived?',
   a:['Mustard oil and asafoetida',
      'Black pepper and long pepper',
      'Kokum and tamarind',
      'Ginger and green mango'],
   c:1, why:'Black pepper and long pepper supplied pungency before American chillies arrived. Chillies later became widespread, while both older peppers remained in use.'},
  {q:'How should homemade recheado paste be stored?',
   a:['It is boiled before it is jarred',
      'It is sealed under a layer of ghee',
      'The chillies are smoked before grinding',
      'Refrigerate promptly, use within a few days or freeze portions'],
   c:3, why:'Vinegar concentrates the flavour but does not make homemade paste shelf-stable. Keep it cold and freeze any portion you will not use soon.'}
 ],
 [
  {q:'What does ukda mean?',
   a:['Par-boiled',
      'Red-grained',
      'Freshly milled',
      'Grown on tidal land'],
   c:0, why:'The paddy is soaked, steamed while still in the husk and dried before milling, exactly as Kerala treats its matta rice.'},
  {q:'What is a khazan?',
   a:['A stone used for grinding the coconut masala',
      'Tidal land farmed behind bunds and wooden sluice gates',
      'A steamed rice cake raised with palm toddy',
      'The morning fish market of a coastal village'],
   c:1, why:'Bunds and sluice gates manage tidal water and salinity. Korgut is one of the local rice varieties associated with these challenging conditions.'},
  {q:'What gives solkadhi its pink colour?',
   a:['Beetroot cooked into the coconut milk',
      'Kashmiri chilli, added for colour rather than heat',
      'Kokum rind steeped in warm water',
      'The unglazed clay it is served in'],
   c:2, why:'Kokum commonly gives solkadhi a pale pink colour. The shade and seasonings vary with the fruit, coconut milk and household method.'}
 ],
 [
  {q:'Where does the second half of the word vindaloo come from?',
   a:['The Hindi and Marathi word for potato',
      'A Konkani word meaning soured',
      'The name of a village in Salcete',
      'Portuguese alho, meaning garlic'],
   c:3, why:'The name traces to Portuguese vinha d\'alhos, wine and garlic. Its resemblance to aloo is unrelated; potatoes appear in some household and later versions.'},
  {q:'Why do many cooks prepare sorpotel ahead?',
   a:['A refrigerated rest lets the flavours settle before thorough reheating',
      'The blood has to settle out before the dish is served',
      'The pork needs that long to cure in salt',
      'It has to cool completely before the liver can be added'],
   c:0, why:'A cold rest lets the flavours settle. Cool the dish promptly, refrigerate it, and reheat it thoroughly before serving.'},
  {q:'What kind of dish is balchao?',
   a:['A dry masala of roasted coconut and whole spice',
      'A thin soured gravy poured over rice',
      'A preserve kept in a jar and eaten a spoonful at a time',
      'A steamed cake eaten with pork at Christmas'],
   c:2, why:'The prawns are cooked down with chilli, garlic and vinegar into a concentrated, pickle-like relish. Store a homemade batch in a clean container in the refrigerator.'}
 ],
 [
  {q:'How long did Portugal hold Goa?',
   a:['From 1498, when Vasco da Gama reached the coast, until 1947',
      'Four hundred and fifty-one years, from 1510 to 1961',
      'About two hundred years, ending when the capital moved to Panaji',
      'Three hundred years, ending with the Inquisition in 1812'],
   c:1, why:'Albuquerque took the city on 25 November 1510 and Indian forces entered in December 1961. This was one of the longest European colonial tenures in Asia.'},
  {q:'Why do the Mangeshi and Shanta Durga temples stand at Ponda?',
   a:['Ponda had the only fresh water on that stretch of coast',
      'The Portuguese built them there for converts who would not give up the old rites',
      'Their deities were carried there when the temples nearer the coast were demolished',
      'They were moved when cholera emptied Old Goa in the nineteenth century'],
   c:2, why:'Temples in the Old Conquests were pulled down from the 1540s, and villagers took their deities across the river into territory Portugal did not control.'},
  {q:'Which part of the cashew is feni distilled from?',
   a:['The fleshy fruit that the nut hangs from',
      'The nut itself, after it has been roasted',
      'The bark, boiled and then fermented',
      'The flowers, collected before dawn'],
   c:0, why:'Cashew feni is distilled from fermented cashew-apple juice; coconut feni is distilled from fermented palm sap.'}
 ]
];
