/* Masala Dabba — oppsummeringsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme fasitindeks som den engelske filen. Spørsmål leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-GUJ'] = [
 [
  {q:'Hvorfor har en gujaratisk kokk jaggery i en gryte med dal?',
   a:['For at dalen skal smake søtt',
      'Fordi jaggery er billigere enn salt',
      'For å balansere syren fra kokumen og styrken fra chilien',
      'For at linsene skal bli møre raskere'],
   c:2, why:'De tre smakene holder hverandre på plass. Tar du bort sødmen, står du ubeskyttet mot syren og chilien.'},
  {q:'Hva er dhana-jeera, og i hvilket forhold blandes den?',
   a:['Like deler spisskummen og fennikel',
      'Chili og gurkemeie malt sammen',
      'Koriander, spisskummen, kanel og nellik i like deler',
      'Ristet koriander og spisskummen, omtrent to deler mot én'],
   c:3, why:'Dhana er koriander og jeera er spisskummen. Noen hus går helt til tre mot én, og ingen måler.'},
  {q:'Hvorfor betyr asafoetida så mye på et gujaratisk kjøkken?',
   a:['Den er det eneste krydderet som dyrkes i delstaten',
      'Den gir løksmaken i hjem som verken bruker løk eller hvitløk',
      'Den er det som gjør maten søt',
      'Den erstatter salt i en egn der det er lite av det'],
   c:1, why:'I varmt fett blir harpiksen smaksrik og ligner stekt løk, og det er nettopp det et kjøkken hos jainer eller vaishnavaer mangler.'}
 ],
 [
  {q:'Hvordan kombineres risen ofte på en gujaratisk thali?',
   a:['Den blandes med dal eller kadhi',
      'Den dekkes med kald chaas før servering',
      'Den spises bare sammen med det søte',
      'Den holdes unna alle flytende retter'],
   c:0, why:'Ris spises gjerne med dal eller kadhi, enten den kommer senere eller ligger på brettet fra starten.'},
  {q:'Hva stemmer om serveringen av en gujaratisk thali?',
   a:['Noen restauranter tilbyr fri påfylling, mens faste thalier og hjemmemåltider varierer',
      'Hver tom skål bestiller automatisk en ny porsjon',
      'Ris må alltid serveres som siste rett',
      'Hver thali inneholder nøyaktig sju skåler'],
   c:0, why:'Det finnes ingen serveringsregel for hele delstaten. Den som spiser, kan si fra når det er nok.'},
  {q:'Hva skiller gujaratisk kadhi fra den punjabske?',
   a:['Den inneholder ikke yoghurt i det hele tatt',
      'Den jevnes med rismel i stedet for kikertmel',
      'Den er tynn og søtet med jaggery, og den helles over ris',
      'Den serveres kald i stedet for lun'],
   c:2, why:'Punjabsk kadhi er tykk og bærer friterte boller. Den gujaratiske er væske til risen og nullstiller munnen mellom rettene.'}
 ],
 [
  {q:'Hvilket nyttig skille kan trekkes mellom tradisjonell dhokla og rask khaman?',
   a:['Dhokla friteres og khaman dampes',
      'Dhokla er en gjæret røre av ris og chana dal; khaman er kikertmel hevet med eno',
      'Khaman lages av ris og dhokla av hvete',
      'Det er to navn på nøyaktig den samme retten'],
   c:1, why:'Tradisjonell dhokla kan gjære en røre av korn og belgfrukt, mens mange raske khamanoppskrifter bruker kikertmel og fruktsalt.'},
  {q:'Hvordan vet en kokk at khandvi-massen har kokt lenge nok?',
   a:['Et strøk på en kald tallerken løsner rent etter et minutt',
      'Den slipper kantene i pannen',
      'Den slutter å dampe',
      'Den blir tydelig mørkere gul'],
   c:0, why:'En masse som ikke har kokt lenge nok, stivner aldri og sklir av brettet, mens en som har kokt for lenge, revner i flak.'},
  {q:'Hvor kommer navnet undhiyu fra?',
   a:['Landsbyen ved Surat der retten først ble laget',
      'Den flate grønne bønnen retten bygger på',
      'Det gujaratiske ordet undhu, opp ned, etter den nedgravde gryta',
      'Pottemakeren som først laget den forseglede gryta'],
   c:2, why:'Navnet knyttes til undhu, opp ned; den beslektede landsbyretten umbhadiyu bevarer metoden med snudd leirgryte.'}
 ],
 [
  {q:'Hva er fortsatt omstridt ved funnstedet Lothal?',
   a:['Om byen i det hele tatt hører til Induskulturen',
      'Om teglbassenget var en dokk eller et vannmagasin',
      'Om perler laget der nådde Mesopotamia',
      'Om bosetningen var lagt ut etter en plan'],
   c:1, why:'Utgraveren leste bassenget som en tidevannsdokk; andre har siden 1960-tallet hevdet at det lagret vann i en tørr egn.'},
  {q:'Hvorfor sløyfer et strengt kjøkken hos jainene potet, løk og gulrot?',
   a:['De kom med portugiserne og regnes som fremmede',
      'De blir fort dårlige i varmen i Gujarat',
      'River du opp en rot, dreper du hele planten og livene i jorda rundt',
      'De regnes for å gjøre kroppen treg'],
   c:2, why:'Regelen følger av å unngå skade på alt levende, og den er grunnen til at disse kjøkkenene hviler på asafoetida i stedet.'},
  {q:'Hva er forholdet mellom fortellingen om melk og sukker og Qissa-i Sanjan?',
   a:['Den er nedtegnet i en persisk krønike fra samtiden',
      'Den er bekreftet av en innskrift i Udvada',
      'Den ble skrevet ned av herskeren som tok imot flyktningene',
      'Den er en senere muntlig legende og står ikke i den bevarte Qissa'],
   c:3, why:'Qissa er en sen fortellende kilde til bosettingen, men den kjente episoden med melk og sukker hører til senere muntlig tradisjon.'}
 ]
];
