/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-GUJ'] = [
 [
  {q:'Why does a Gujarati cook put jaggery into a savoury pot of dal?',
   a:['To make the dal taste sweet',
      'Because jaggery is cheaper than salt',
      'To balance the sourness of the kokum and the heat of the chilli',
      'To help the lentils soften as they cook'],
   c:2, why:'The three tastes hold each other in place. Take the sweetness out and the sour and the chilli arrive unguarded.'},
  {q:'What is dhana-jeera, and in what proportion is it mixed?',
   a:['Equal parts cumin and fennel seed',
      'Chilli and turmeric ground together',
      'Coriander, cumin, cinnamon and clove in equal parts',
      'Roasted coriander and cumin, roughly two parts to one'],
   c:3, why:'Dhana is coriander and jeera is cumin. Some houses go as far as three to one, and nobody measures.'},
  {q:'Why does asafoetida matter so much in a Gujarati kitchen?',
   a:['It is the only spice grown in the state',
      'It supplies the savoury onion note in houses that eat no onion or garlic',
      'It is what makes the food taste sweet',
      'It replaces salt in a region short of it'],
   c:1, why:'In hot fat the resin turns savoury and close to frying onion, which is exactly what a Jain or Vaishnav kitchen is missing.'}
 ],
 [
  {q:'Why should you not fill up on bread in the first ten minutes of a thali?',
   a:['Rice with dal or kadhi comes last and is what the meal builds towards',
      'The bread is the only item charged for separately',
      'Asking twice for bread is thought impolite',
      'The vegetables only arrive once the bread is finished'],
   c:0, why:'The last act of the meal is rice with dal or kadhi poured over it, and anyone already full has skipped it.'},
  {q:'What does a Gujarati server read an empty katori as?',
   a:['A request for more of that dish',
      'A signal that the meal is over',
      'A complaint about the seasoning',
      'A sign that the diner wants the bill'],
   c:0, why:'A thali is refilled rather than portioned, so you leave a little in a bowl or cover it with a hand to stop the serving.'},
  {q:'What makes Gujarati kadhi different from the Punjabi version?',
   a:['It contains no yoghurt at all',
      'It is thickened with rice flour rather than gram flour',
      'It is thin and sweetened with jaggery, and it is poured over rice',
      'It is served cold rather than warm'],
   c:2, why:'Punjabi kadhi is thick and carries fried dumplings. The Gujarati one is a liquid for the rice and a way of resetting the mouth.'}
 ],
 [
  {q:'What separates proper dhokla from the khaman sold everywhere under the same name?',
   a:['Dhokla is fried and khaman is steamed',
      'Dhokla is a fermented rice and chana dal batter; khaman is gram flour raised with eno',
      'Khaman uses rice and dhokla uses wheat',
      'They are two names for exactly the same dish'],
   c:1, why:'One ferments overnight and tastes of it. The other rises chemically in twenty minutes, which is why it has largely taken over.'},
  {q:'How does a cook know the khandvi paste has cooked long enough?',
   a:['A smear on a cold plate peels off cleanly after a minute',
      'It pulls away from the sides of the pan',
      'It stops steaming altogether',
      'It turns a noticeably deeper yellow'],
   c:0, why:'Undercooked paste never sets and slides off the tray; overcooked paste tears into flakes instead of peeling away in a sheet.'},
  {q:'Where does the name undhiyu come from?',
   a:['The village near Surat where it was first cooked',
      'The flat green bean the dish is built around',
      'The Gujarati word undhu, upside down, from the buried pot',
      'The potter who first made the sealed vessel'],
   c:2, why:'The pot was packed, sealed, turned mouth-down into a pit and cooked under a fire of dried leaves.'}
 ],
 [
  {q:'What is still disputed about the site at Lothal?',
   a:['Whether the town belongs to the Indus civilisation at all',
      'Whether the brick basin was a dock or a water reservoir',
      'Whether beads made there reached Mesopotamia',
      'Whether the settlement was laid out to a plan'],
   c:1, why:'The excavator read the basin as a tidal dock; others have argued since the 1960s that it stored water in a dry region.'},
  {q:'Why does a strict Jain kitchen leave out potato, onion and carrot?',
   a:['They were brought by the Portuguese and count as foreign',
      'They spoil too quickly in the heat of Gujarat',
      'Uprooting a root kills the whole plant and the lives in the soil with it',
      'They are thought to make the body sluggish'],
   c:2, why:'The rule follows from avoiding harm to living things, and it is why those kitchens lean on asafoetida instead.'},
  {q:'How solid is the story of the milk and the sugar at Sanjan?',
   a:['It is recorded in a Persian chronicle written at the time',
      'It is confirmed by an inscription at Udvada',
      'It was set down by the ruler who received the refugees',
      'It comes from one text written in 1599, long after the events'],
   c:3, why:'The Qissa-i Sanjan records what had been passed on orally for centuries, and even the century of the landing is argued over.'}
 ]
];
