/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-HIM'] = [
 [
  {q:'Why does saffron cost what it does?',
   a:['The crocus only flowers once every three years',
      'Every flower is picked and stripped by hand',
      'The plant will only grow above 3,000 metres',
      'Export from the valley is tightly restricted'],
   c:1, why:'A kilogram of dried saffron takes roughly a hundred and fifty thousand flowers, and harvesting and separating the stigmas remain painstaking manual work.'},
  {q:'What makes rogan josh red?',
   a:['Colour-rich chilli, sometimes helped by ratan jot or mawal',
      'Tomato cooked down for the better part of an hour',
      'Saffron threads steeped in a spoonful of warm milk',
      'A long browning of the onion and garlic base'],
   c:0, why:'Kashmiri chilli is valued for colour and comparatively mild heat; ratan jot or mawal can deepen the red without determining how hot the dish tastes.'},
  {q:'Why is ver stored as a dried cake rather than as a powder?',
   a:['A solid cake is easier to weigh out accurately',
      'The dried chilli in it would fade in a clear jar',
      'The dried form makes a seasonal batch practical to store',
      'It is a religious custom rather than a practical one'],
   c:2, why:'Drying the paste into a hard ring makes a large batch practical to store for months in dry, airtight conditions and easy to break off as needed.'}
 ],
 [
  {q:'What is a trami?',
   a:['The wooden mallet the meat is pounded with',
      'The copper platter that four people share at a wazwan',
      'The head cook of a wazwan team of cooks',
      'The jug and basin passed round for washing hands'],
   c:1, why:'Rice is heaped on it and divided into four by the meat laid across the top, and nobody at the meal is given a plate of their own.'},
  {q:'How should the figure of thirty-six courses in a wazwan be treated?',
   a:['As an exact count fixed by long custom',
      'As the minimum a host is expected to serve',
      'As the number served at royal weddings only',
      'As a figure of speech that varies in practice'],
   c:3, why:'What is actually served depends on the household and on the money, and a modern wazwan is often shorter. The sequence is fixed; the total is not.'},
  {q:'Why does Ladakh eat barley rather than rice?',
   a:['Rice is reserved there for religious occasions',
      'Barley was brought by Tibetan traders and took over',
      'Barley tolerates the high, cold and dry conditions better',
      'The soil of the high valleys is too salty for rice'],
   c:2, why:'At about 3,500 metres, barley is better suited than rice to Ladakh\'s cold, dry conditions and short growing season.'}
 ],
 [
  {q:'What can be said safely about the name rogan josh?',
   a:['Its exact etymology is disputed, and red does not necessarily mean very hot',
      'It certainly means red and hot in Kashmiri',
      'It means lamb cooked slowly in a sealed clay pot',
      'It names the hereditary wazwan cooks of Srinagar'],
   c:0, why:'A Persian explanation links the words to fat and boiling, while alternatives connect red with meat or juice. The exact origin remains disputed.'},
  {q:'What separates the Kashmiri Pandit kitchen from the Kashmiri Muslim one?',
   a:['One of them eats meat and the other does not',
      'One of them uses saffron and the other does not',
      'One cooks in ghee and the other in mustard oil',
      'One uses onion and garlic and the other refuses them'],
   c:3, why:'Both eat meat freely. The Pandit kitchen uses no alliums at all and reaches for fennel, dry ginger and asafoetida instead.'},
  {q:'Why is yakhni stirred in one direction until it comes back to a simmer?',
   a:['So that the pieces of meat do not break up',
      'Because yoghurt splits when it is heated',
      'To stop the ground fennel sinking to the bottom',
      'Because the sealed pot cannot be opened again'],
   c:1, why:'Once the yoghurt has boiled with the meat it is stable and the pot can be left alone. Stop stirring before that and the gravy turns to grains for good.'}
 ],
 [
  {q:'Which of these did the Mughals not bring to Kashmir?',
   a:['Saffron growing on the karewa terraces',
      'The Persian garden plan of Shalimar Bagh',
      'The chinar trees planted along the walks',
      'The habit of simmering meat in yoghurt'],
   c:0, why:'Saffron and the trade in it are attested centuries before the Mughals came north, so the valley grew its most famous spice long before they arrived.'},
  {q:'Where does the word kahwa come from?',
   a:['The Kashmiri word for the saffron crocus',
      'A Ladakhi word for the churn tea is made in',
      'The Arabic word for coffee',
      'A Mughal courtier said to have invented it'],
   c:2, why:'The vocabulary of this kitchen maps the routes its food came in on. Rogan, josh, yakhni, korma and pulav are Persian, and kahwa is Arabic.'},
  {q:'What are the floating gardens of Dal Lake?',
   a:['Terraces cut into the hillside above the lake',
      'Anchored beds of weed and mud, planted and towable',
      'Ornamental beds laid out by Jahangir in 1619',
      'Rafts on which lotus root is dried before sale'],
   c:1, why:'The beds are built up on rafts of lake vegetation and staked in the shallows, and the dawn market on the water sells what was lifted off them that morning.'}
 ]
];
