/* Masala Dabba — repetisjonsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme riktige svarindeks som den engelske filen. Spørsmålene leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-HIM'] = [
 [
  {q:'Hvorfor koster safran det den gjør?',
   a:['Krokusen blomstrer bare hvert tredje år',
      'Hver blomst plukkes og renses for hånd',
      'Planten vokser bare over 3000 meter',
      'Utførsel fra dalen er strengt regulert'],
   c:1, why:'Ett kilo tørket safran krever i størrelsesorden hundre og femti tusen blomster, og verken plukkingen eller rensingen er mekanisert.'},
  {q:'Hva gjør rogan josh rød?',
   a:['En mild chili dyrket for farge, hjulpet av ratan jot',
      'Tomat som er kokt inn i nesten en time',
      'Safrantråder som har trukket i en skje lunken melk',
      'En lang bruning av bunnen med løk og hvitløk'],
   c:0, why:'Kashmiri-chili er foredlet for farge og ikke for styrke, og ratan jot, en alkannarot, gir fra seg en fettløselig rødfarge som legger seg på overflaten.'},
  {q:'Hvorfor oppbevares ver som en tørket kake i stedet for som pulver?',
   a:['En fast kake er lettere å veie nøyaktig opp',
      'Den tørkede chilien ville bleknet i et klart glass',
      'En malt blanding blir flat i løpet av noen uker',
      'Det er en religiøs skikk og ikke en praktisk ordning'],
   c:2, why:'Når blandingen er presset til en ring med salt og olje, ligger de aromatiske oljene forseglet til noen brekker av et stykke, så én maledag i året gir ferskt krydder hele året.'}
 ],
 [
  {q:'Hva er en trami?',
   a:['Trekølla kjøttet bankes med',
      'Kobberfatet fire personer deler i en wazwan',
      'Sjefen for laget av kokker i en wazwan',
      'Mugga og fatet som sendes rundt til håndvask'],
   c:1, why:'Risen ligger i en haug på fatet og deles i fire av kjøttet som legges over, og ingen i måltidet får en egen tallerken.'},
  {q:'Hvordan bør tallet trettiseks retter i en wazwan forstås?',
   a:['Som en nøyaktig opptelling fastsatt av lang skikk',
      'Som det minste en vert forventes å servere',
      'Som antallet som bare serveres i kongelige bryllup',
      'Som en talemåte som varierer i praksis'],
   c:3, why:'Hva som faktisk serveres, avhenger av husholdningen og av pengene, og en moderne wazwan er ofte kortere. Rekkefølgen ligger fast, summen gjør det ikke.'},
  {q:'Hvorfor spiser Ladakh bygg i stedet for ris?',
   a:['Ris er forbeholdt religiøse anledninger der',
      'Bygg kom med tibetanske handelsmenn og tok over',
      'På 3500 meter rekker bare bygg å bli ferdig',
      'Jorda i de høye dalene er for salt for ris'],
   c:2, why:'Høyden avgjør basismaten i hele regionen: ris på dalbunnen i 1600 meters høyde, grovere korn i åsene imellom, og bygg i 3500.'}
 ],
 [
  {q:'Hva betyr navnet rogan josh egentlig?',
   a:['Fett og kraft, og begge ordene er persiske',
      'Rød og sterk, og begge ordene er kashmirske',
      'Lam kokt langsomt i en forseglet leirgryte',
      'Retten til wazwan-kokkene i Srinagar'],
   c:0, why:'Rogan er persisk for fett eller olje, og josh er persisk for kraft, varmen i et rullende oppkok. Ingen av ordene har noe med chili å gjøre.'},
  {q:'Hva skiller det kashmirske pandit-kjøkkenet fra det muslimske?',
   a:['Det ene spiser kjøtt og det andre gjør det ikke',
      'Det ene bruker safran og det andre gjør det ikke',
      'Det ene steker i ghee og det andre i sennepsolje',
      'Det ene bruker løk og hvitløk og det andre nekter'],
   c:3, why:'Begge spiser kjøtt uten videre. Pandit-kjøkkenet bruker ingen løkvekster i det hele tatt og griper i stedet etter fennikel, tørket ingefær og asafoetida.'},
  {q:'Hvorfor røres yakhni én vei helt til gryta koker opp igjen?',
   a:['For at kjøttbitene ikke skal gå i stykker',
      'Fordi yoghurt skiller seg når den varmes',
      'For å hindre at malt fennikel synker til bunns',
      'Fordi den forseglede gryta ikke kan åpnes igjen'],
   c:1, why:'Har yoghurten først kokt sammen med kjøttet, er den stabil og gryta kan stå. Slutter du å røre før det, klumper sausen seg, og den lar seg ikke samle igjen.'}
 ],
 [
  {q:'Hva av dette hadde mughalene ikke med seg til Kashmir?',
   a:['Safrandyrking på karewa-terrassene',
      'Den persiske hageplanen i Shalimar Bagh',
      'Chinartrærne som ble plantet langs gangene',
      'Vanen med å småkoke kjøtt i yoghurt'],
   c:0, why:'Både safranen og handelen med den er belagt århundrer før mughalene kom nordover, så dalen dyrket sitt mest berømte krydder lenge før dem.'},
  {q:'Hvor kommer ordet kahwa fra?',
   a:['Det kashmirske ordet for safrankrokus',
      'Et ladakhisk ord for kinna te lages i',
      'Det arabiske ordet for kaffe',
      'En mughalsk hoffmann som skal ha funnet den opp'],
   c:2, why:'Ordene i dette kjøkkenet tegner veiene maten kom langs. Rogan, josh, yakhni, korma og pulav er persiske, og kahwa er arabisk.'},
  {q:'Hva er de flytende hagene på Dal-sjøen?',
   a:['Terrasser skåret inn i åssiden over sjøen',
      'Forankrede bed av vannplanter og mudder som kan slepes',
      'Prydbed anlagt av Jahangir i 1619',
      'Flåter der lotusrot tørkes før den selges'],
   c:1, why:'Bedene bygges opp på flåter av vannplanter og stakes fast på grunna, og markedet på vannet ved daggry selger det som er tatt opp av dem samme morgen.'}
 ]
];
