/* Masala Dabba — repetisjonsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme riktige svar som den engelske filen. Spørsmål blir aldri lest inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-KAR'] = [
 [
  {q:'Hva betaler kjøperne for når de kjøper byadgichili?',
   a:['Den er den sterkeste chilien som dyrkes i Sør-India',
      'Den modner to ganger i samme sesong',
      'Den inneholder langt mer rødt fargestoff enn de fleste indiske chilier',
      'Den er den eneste chilien som kan tørkes hel'],
   c:2, why:'Byadgi omsettes etter fargeverdi. Styrken ligger på omkring fem til femten tusen Scoville-enheter, godt under en Guntur-chili.'},
  {q:'Hva er uvanlig med bisi bele bath-pulver?',
   a:['Det inneholder ingen chili i det hele tatt',
      'Ristede linser males inn i det, så det tykner like mye som det krydrer',
      'Det må males ferskt til hver eneste gryte',
      'Det er den eneste indiske blandingen med kanel i'],
   c:1, why:'Chana dal og urad dal ristes med i blandingen, og derfor trenger retten den er laget til, ingen annen jevning.'},
  {q:'Hvordan lager man i Kodagu kachampuli av den samme frukten som Kerala tørker?',
   a:['Saften samles opp og kokes inn til en tykk, mørk sirup',
      'Skallet saltes og gjæres i et år',
      'Frukten presses med palmeeddik og siles',
      'Frøene ristes og males'],
   c:0, why:'Moden frukt legges i hauger til saften drypper ut, og saften småkokes over vedild til den tykner. Ingenting gjæres.'}
 ],
 [
  {q:'Hvorfor svelges ragi mudde i stedet for å tygges?',
   a:['Tygging regnes som uhøflig ved et arbeidsmåltid',
      'Ballen er for varm til å holde i munnen',
      'Tygd ragideig blir en klebrig masse som smaker svært lite',
      'Klumpene er for store til å bite gjennom'],
   c:2, why:'En klump som er dekket av saaru, glir ned og tar smaken med seg. Tygges den, setter deigen seg i ganen.'},
  {q:'Hva er bassaru?',
   a:['En ball av hirsedeig formet for hånd',
      'Vannet som bladgrønnsaker og belgfrukter er kokt i, servert som den tynne kraften',
      'En blanding av ristede linser og tørket chili',
      'Kjernemelk krydret med karriblad og ingefær'],
   c:1, why:'Kokevannet blir saaru, og det som blir igjen i silen, blir en tørr siderett, så én gryte gir to retter.'},
  {q:'Hva skiller røren til neer dosa fra en vanlig røre til idli eller dosa?',
   a:['Den males med urad dal, men får aldri hvile',
      'Den gjærer i tre døgn i stedet for én natt',
      'Den lages uten linser og uten gjæring, og den males og brukes samme dag',
      'Den dampes i en form i stedet for å stekes i panne'],
   c:2, why:'Rå ris males med litt kokos og spes med vann. Luften i dosaen kommer fra damp, og derfor lar røren seg ikke lagre.'}
 ],
 [
  {q:'Hva gjør en Mysore masala dosa til nettopp Mysores?',
   a:['En rå rød chutney av chili og hvitløk som smøres inni den på takken',
      'En røre som gjærer i to netter i stedet for én',
      'Et potetfyll som kokes med kokos i stedet for løk',
      'En tynnere røre som helles i stedet for å bres ut'],
   c:0, why:'Chutneyen smøres på dosaen før poteten, så styrken er forseglet inne i bretten der du ikke får skrapt den av.'},
  {q:'Hvorfor er bisi bele bath ikke bare sambar med ris?',
   a:['Den serveres romtemperert',
      'Risen og dalen kokes inn i hverandre til de er blitt én rett',
      'Den lages helt uten tamarind',
      'Kikerter brukes i stedet for dal'],
   c:1, why:'Sambar med ris er to retter som møtes på tallerkenen. Her kokes de sammen til riskornene mister kantene.'},
  {q:'Hvordan kom matlagingen fra Udupi til restauranter over hele India?',
   a:['Wodeyarene sendte palasskokker til andre fyrstehoff',
      'Britiske plantere ansatte kokker fra kysten og flyttet dem nordover',
      'Kokker som var lært opp i tempeltradisjonen, dro til byene og åpnet spisesteder der',
      'Handelsmenn fra Vijayanagara tok oppskriftene med langs karavaneveiene'],
   c:2, why:'Fra tidlig på 1900-tallet, og særlig gjennom 1930- og 1940-årene, åpnet kokkene Udupi-restauranter i Mumbai og videre utover.'}
 ],
 [
  {q:'Hva skjedde med Vijayanagara i 1565?',
   a:['Hovedstaden ble flyttet nordover til Bijapur',
      'Hæren ble slått ved Talikota, og hovedstaden ble plyndret',
      'Byen ble satt under vann da Tungabhadra skiftet løp',
      'Riket gikk fredelig inn i kongedømmet Mysore'],
   c:1, why:'En allianse av sultanatene på Dekkan vant slaget, og Hampi ble plyndret i måneder og aldri bebodd igjen.'},
  {q:'Hvorfor betyr Vijayanagara noe for maten på platået?',
   a:['Riket innførte chili og tomat i Sør-India',
      'Riket bygde de første sukkerraffineriene i regionen',
      'Demningene, kanalene og dammene gjorde at tørt land kunne gi sikre avlinger',
      'Riket hentet kaffen ned fra åsene til sletten'],
   c:2, why:'Noen av dammene vanner fortsatt jorder, og de er grunnen til at hirse, belgfrukter og sukkerrør kunne fø en by på tørt land.'},
  {q:'Hvordan bør historien om Baba Budan og de sju bønnene behandles?',
   a:['Som en hendelse som er dokumentert i kilder fra samtiden',
      'Som bevis for at kaffen nådde India før den nådde Jemen',
      'Som en britisk oppfinnelse fra 1800-tallet',
      'Som en historie som fortelles, siden detaljene ikke er dokumentert'],
   c:3, why:'Åsene, helligdommen og kaffenæringen finnes virkelig. De sju bønnene og skjegget er en tradisjon og ikke en kilde.'}
 ]
];
