/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-KAR'] = [
 [
  {q:'Why do buyers pay for Byadgi chilli?',
   a:['It is the hottest chilli grown in southern India',
      'It ripens twice in a single season',
      'It carries far more red pigment than most Indian chillies',
      'It is the only chilli that can be dried whole'],
   c:2, why:'Byadgi is traded on its colour value. Its heat is roughly five to fifteen thousand Scoville units, well under a Guntur chilli.'},
  {q:'What is unusual about bisi bele bath powder?',
   a:['It contains no chilli at all',
      'Roasted lentils are ground into it, so it thickens as well as seasons',
      'It has to be ground fresh for every pot',
      'It is the only Indian blend that uses cinnamon'],
   c:1, why:'Chana dal and urad dal are roasted into the blend, which is why the dish it is made for needs no other thickening.'},
  {q:'How does Kodagu turn the same fruit Kerala dries into kachampuli?',
   a:['The juice is collected and boiled down to a thick dark syrup',
      'The rind is salted and fermented for a year',
      'The fruit is pressed with palm vinegar and strained',
      'The seeds are roasted and then ground'],
   c:0, why:'Liquid collected from ripe Garcinia fruit is reduced to a dark sour concentrate. Accounts differ on the resting and fermentation stage.'}
 ],
 [
  {q:'How should a learner eat ragi mudde safely?',
   a:['Take a whole ball at once',
      'Let it remain hot enough to melt',
      'Take a small piece, coat it in saaru and chew as needed',
      'Dry it until it becomes crisp'],
   c:2, why:'Small pieces coated in thin saaru are easier to handle. Experienced diners may chew little, but learners should choose a comfortable size and chew as needed.'},
  {q:'What is bassaru?',
   a:['A ball of millet dough shaped by hand',
      'The water that greens and pulses were boiled in, served as the thin stew',
      'A blend of roasted lentils and dried chilli',
      'Buttermilk seasoned with curry leaf and ginger'],
   c:1, why:'The cooking water becomes the saaru and the drained solids become a dry side dish, so one pot feeds the plate twice.'},
  {q:'How does neer dosa differ from an idli or dosa batter?',
   a:['It is ground with urad dal but never left to rest',
      'It ferments for three days rather than one night',
      'It uses no lentil and no fermentation, and is ground and used the same day',
      'It is steamed in a mould instead of cooked on a pan'],
   c:2, why:'Raw rice is ground with a little coconut and thinned with water. Steam makes the holes; refrigerate the unfermented batter promptly and use it fresh.'}
 ],
 [
  {q:'What makes a Mysore masala dosa a Mysore one?',
   a:['A raw red chutney of chilli and garlic spread inside it on the griddle',
      'A batter fermented for two nights instead of one',
      'A potato filling cooked with coconut rather than onion',
      'A thinner batter that is poured rather than spread'],
   c:0, why:'The chutney goes on the dosa before the potato, so the heat is sealed inside the fold where it cannot be scraped off.'},
  {q:'Why is bisi bele bath not simply sambar with rice?',
   a:['It is served at room temperature',
      'The rice and the dal are cooked into each other until they are one dish',
      'It is made without any tamarind',
      'Chickpeas are used in place of the dal'],
   c:1, why:'Sambar with rice is two dishes meeting on a plate. Here they cook together until the grain loses its edges.'},
  {q:'How did the Udupi restaurant name spread across India?',
   a:['The Wodeyars sent palace cooks to other princely courts',
      'British planters hired coastal cooks and moved them north',
      'Migrants from the Udupi area opened eating houses in cities such as Mumbai',
      'Vijayanagara traders carried the recipes along the caravan routes'],
   c:2, why:'During the twentieth century, migrants from the Udupi area opened vegetarian southern restaurants in Mumbai and other cities; later operators had varied connections to the temple tradition.'}
 ],
 [
  {q:'What happened to Vijayanagara in 1565?',
   a:['It moved its capital north to Bijapur',
      'Its army was defeated at Talikota and the capital was sacked',
      'It was flooded when the Tungabhadra changed course',
      'It was absorbed peacefully into the kingdom of Mysore'],
   c:1, why:'A coalition of Deccan sultanates won the battle, after which the capital suffered major destruction; the wider empire continued from other centres.'},
  {q:'Why does Vijayanagara matter to what the plateau eats?',
   a:['It introduced chilli and tomato to southern India',
      'It built the first sugar refineries in the region',
      'Its dams, canals and tanks expanded water storage and irrigation',
      'It brought coffee down from the hills to the plain'],
   c:2, why:'Vijayanagara developed tanks and canals that supported settlement and farming in a seasonally dry landscape; some waterworks remain legible or in use.'},
  {q:'How should the story of Baba Budan and the seven beans be treated?',
   a:['As an event documented in the records of the time',
      'As proof that coffee reached India before it reached Yemen',
      'As a British invention from the nineteenth century',
      'As a story that is told, because the details are not documented'],
   c:3, why:'The hills, the shrine and the coffee industry are all real. The seven beans and the beard are a tradition rather than a record.'}
 ]
];
