/* Masala Dabba — repetisjonsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme riktige svar som den engelske filen. Spørsmål blir aldri lest inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-KAR'] = [
 [
  {q:'Hva betaler kjøperne for når de kjøper byadgichili?',
   a:['Den er den sterkeste chilien som dyrkes i Sør-India',
      'Den modner to ganger i samme sesong',
      'Den inneholder langt mer rødt fargestoff enn de fleste indiske chilier',
      'Den er den eneste chilien som kan tørkes hel'],
   c:2, why:'Byadgi omsettes etter fargeverdi. Styrken ligger på omkring fem til femten tusen Scoville-enheter, godt under en Guntur-chili.'},
  {q:'Hva er uvanlig med bisi bele bath-pulver?',
   a:['Det inneholder ingen chili i det hele tatt',
      'Ristede linser males inn i det, så det tykner like mye som det krydrer',
      'Det må males ferskt til hver eneste gryte',
      'Det er den eneste indiske blandingen med kanel i'],
   c:1, why:'Chana dal og urad dal ristes med i blandingen, og derfor trenger retten den er laget til, ingen annen jevning.'},
  {q:'Hvordan lager man i Kodagu kachampuli av den samme frukten som Kerala tørker?',
   a:['Saften samles opp og kokes inn til en tykk, mørk sirup',
      'Skallet saltes og gjæres i et år',
      'Frukten presses med palmeeddik og siles',
      'Frøene ristes og males'],
   c:0, why:'Væske fra moden Garcinia-frukt kokes inn til et mørkt, surt konsentrat. Kildene beskriver hvile- og gjæringsstadiet ulikt.'}
 ],
 [
  {q:'Hvordan bør en nybegynner spise ragi mudde trygt?',
   a:['Ta hele ballen på én gang',
      'La den være varm nok til å smelte',
      'Ta en liten bit, dekk den med saaru og tygg etter behov',
      'Tørk den til den blir sprø'],
   c:2, why:'Små biter dekket med tynn saaru er lettere å håndtere. Erfarne spisere tygger kanskje lite, men nybegynnere bør velge en behagelig størrelse og tygge etter behov.'},
  {q:'Hva er bassaru?',
   a:['En ball av hirsedeig formet for hånd',
      'Vannet som bladgrønnsaker og belgfrukter er kokt i, servert som den tynne kraften',
      'En blanding av ristede linser og tørket chili',
      'Kjernemelk krydret med karriblad og ingefær'],
   c:1, why:'Kokevannet blir saaru, og det som blir igjen i silen, blir en tørr siderett, så én gryte gir to retter.'},
  {q:'Hva skiller røren til neer dosa fra en vanlig røre til idli eller dosa?',
   a:['Den males med urad dal, men får aldri hvile',
      'Den gjærer i tre døgn i stedet for én natt',
      'Den lages uten linser og uten gjæring, og den males og brukes samme dag',
      'Den dampes i en form i stedet for å stekes i panne'],
   c:2, why:'Rå ris males med litt kokos og spes med vann. Damp lager hullene; sett den ugjærede røren raskt kaldt og bruk den fersk.'}
 ],
 [
  {q:'Hva gjør en Mysore masala dosa til nettopp Mysores?',
   a:['En rå rød chutney av chili og hvitløk som smøres inni den på takken',
      'En røre som gjærer i to netter i stedet for én',
      'Et potetfyll som kokes med kokos i stedet for løk',
      'En tynnere røre som helles i stedet for å bres ut'],
   c:0, why:'Chutneyen smøres på dosaen før poteten, så styrken er forseglet inne i bretten der du ikke får skrapt den av.'},
  {q:'Hvorfor er bisi bele bath ikke bare sambar med ris?',
   a:['Den serveres romtemperert',
      'Risen og dalen kokes inn i hverandre til de er blitt én rett',
      'Den lages helt uten tamarind',
      'Kikerter brukes i stedet for dal'],
   c:1, why:'Sambar med ris er to retter som møtes på tallerkenen. Her kokes de sammen til riskornene mister kantene.'},
  {q:'Hvordan spredte navnet Udupi-restaurant seg over India?',
   a:['Wodeyarene sendte palasskokker til andre fyrstehoff',
      'Britiske plantere ansatte kokker fra kysten og flyttet dem nordover',
      'Migranter fra Udupi-området åpnet spisesteder i byer som Mumbai',
      'Handelsmenn fra Vijayanagara tok oppskriftene med langs karavaneveiene'],
   c:2, why:'På 1900-tallet åpnet migranter fra Udupi-området vegetariske sørindiske restauranter i Mumbai og andre byer; senere drivere hadde ulike forbindelser til tempeltradisjonen.'}
 ],
 [
  {q:'Hva skjedde med Vijayanagara i 1565?',
   a:['Hovedstaden ble flyttet nordover til Bijapur',
      'Hæren ble slått ved Talikota, og hovedstaden ble plyndret',
      'Byen ble satt under vann da Tungabhadra skiftet løp',
      'Riket gikk fredelig inn i kongedømmet Mysore'],
   c:1, why:'En allianse av sultanater på Dekkan vant slaget, og hovedstaden ble hardt ødelagt; det større riket fortsatte fra andre sentre.'},
  {q:'Hvorfor betyr Vijayanagara noe for maten på platået?',
   a:['Riket innførte chili og tomat i Sør-India',
      'Riket bygde de første sukkerraffineriene i regionen',
      'Demningene, kanalene og dammene utvidet vannlagring og vanning',
      'Riket hentet kaffen ned fra åsene til sletten'],
   c:2, why:'Vijayanagara utviklet dammer og kanaler som støttet bosetning og jordbruk i et sesongtørt landskap; enkelte vannverk kan fortsatt leses eller brukes.'},
  {q:'Hvordan bør historien om Baba Budan og de sju bønnene behandles?',
   a:['Som en hendelse som er dokumentert i kilder fra samtiden',
      'Som bevis for at kaffen nådde India før den nådde Jemen',
      'Som en britisk oppfinnelse fra 1800-tallet',
      'Som en historie som fortelles, siden detaljene ikke er dokumentert'],
   c:3, why:'Åsene, helligdommen og kaffenæringen finnes virkelig. De sju bønnene og skjegget er en tradisjon og ikke en kilde.'}
 ]
];
