/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-KAR'] = [
 [
  {q:'Why do buyers pay for Byadgi chilli?',
   a:['It is the hottest chilli grown in southern India',
      'It ripens twice in a single season',
      'It carries far more red pigment than most Indian chillies',
      'It is the only chilli that can be dried whole'],
   c:2, why:'Byadgi is traded on its colour value. Its heat is roughly five to fifteen thousand Scoville units, well under a Guntur chilli.'},
  {q:'What is unusual about bisi bele bath powder?',
   a:['It contains no chilli at all',
      'Roasted lentils are ground into it, so it thickens as well as seasons',
      'It has to be ground fresh for every pot',
      'It is the only Indian blend that uses cinnamon'],
   c:1, why:'Chana dal and urad dal are roasted into the blend, which is why the dish it is made for needs no other thickening.'},
  {q:'How does Kodagu turn the same fruit Kerala dries into kachampuli?',
   a:['The juice is collected and boiled down to a thick dark syrup',
      'The rind is salted and fermented for a year',
      'The fruit is pressed with palm vinegar and strained',
      'The seeds are roasted and then ground'],
   c:0, why:'Ripe fruit is heaped until the juice drips out, and that juice is simmered over a wood fire until it thickens. Nothing is fermented.'}
 ],
 [
  {q:'Why is ragi mudde swallowed rather than chewed?',
   a:['Chewing is thought impolite at a working meal',
      'The ball is too hot to keep in the mouth',
      'Chewed ragi dough turns into a sticky paste that tastes of very little',
      'The lumps are too large to bite through'],
   c:2, why:'A coated lump goes down carrying the flavour of the saaru with it. Chewed, the dough clings to the roof of the mouth.'},
  {q:'What is bassaru?',
   a:['A ball of millet dough shaped by hand',
      'The water that greens and pulses were boiled in, served as the thin stew',
      'A blend of roasted lentils and dried chilli',
      'Buttermilk seasoned with curry leaf and ginger'],
   c:1, why:'The cooking water becomes the saaru and the drained solids become a dry side dish, so one pot feeds the plate twice.'},
  {q:'How does neer dosa differ from an idli or dosa batter?',
   a:['It is ground with urad dal but never left to rest',
      'It ferments for three days rather than one night',
      'It uses no lentil and no fermentation, and is ground and used the same day',
      'It is steamed in a mould instead of cooked on a pan'],
   c:2, why:'Raw rice is ground with a little coconut and let down with water. The lift comes from steam, so the batter cannot be kept.'}
 ],
 [
  {q:'What makes a Mysore masala dosa a Mysore one?',
   a:['A raw red chutney of chilli and garlic spread inside it on the griddle',
      'A batter fermented for two nights instead of one',
      'A potato filling cooked with coconut rather than onion',
      'A thinner batter that is poured rather than spread'],
   c:0, why:'The chutney goes on the dosa before the potato, so the heat is sealed inside the fold where it cannot be scraped off.'},
  {q:'Why is bisi bele bath not simply sambar with rice?',
   a:['It is served at room temperature',
      'The rice and the dal are cooked into each other until they are one dish',
      'It is made without any tamarind',
      'Chickpeas are used in place of the dal'],
   c:1, why:'Sambar with rice is two dishes meeting on a plate. Here they cook together until the grain loses its edges.'},
  {q:'How did Udupi cooking reach restaurants across India?',
   a:['The Wodeyars sent palace cooks to other princely courts',
      'British planters hired coastal cooks and moved them north',
      'Cooks trained in the temple tradition left for the cities and opened eating houses there',
      'Vijayanagara traders carried the recipes along the caravan routes'],
   c:2, why:'From the early twentieth century, and above all through the nineteen-thirties and forties, those cooks opened Udupi hotels in Mumbai and beyond.'}
 ],
 [
  {q:'What happened to Vijayanagara in 1565?',
   a:['It moved its capital north to Bijapur',
      'Its army was defeated at Talikota and the capital was sacked',
      'It was flooded when the Tungabhadra changed course',
      'It was absorbed peacefully into the kingdom of Mysore'],
   c:1, why:'A coalition of the Deccan sultanates won the battle, and Hampi was sacked over months and never lived in again.'},
  {q:'Why does Vijayanagara matter to what the plateau eats?',
   a:['It introduced chilli and tomato to southern India',
      'It built the first sugar refineries in the region',
      'Its dams, canals and tanks let dry country grow food reliably',
      'It brought coffee down from the hills to the plain'],
   c:2, why:'Some of those tanks still irrigate fields, and they are why millet, pulses and sugarcane could feed a city on dry land.'},
  {q:'How should the story of Baba Budan and the seven beans be treated?',
   a:['As an event documented in the records of the time',
      'As proof that coffee reached India before it reached Yemen',
      'As a British invention from the nineteenth century',
      'As a story that is told, because the details are not documented'],
   c:3, why:'The hills, the shrine and the coffee industry are all real. The seven beans and the beard are a tradition rather than a record.'}
 ]
];
