/* Masala Dabba — oppsummeringsspørsmål for Maharashtra (IN-MAH), norsk. Kontrakt: docs/quiz-format.md.
   Samme antall lesetekster, samme antall spørsmål og samme riktige svarindeks som den engelske filen.
   Spørsmålene leses aldri opp, så en endring her gjør ingen lydfil utdatert. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-MAH'] = [
 [
  {q:'Hva antyder navnet goda masala?',
   a:['Den ristede kokosen i den smaker søtt av seg selv',
      'Navnet er en sammenligning med den langt sterkere kala masalaen',
      'Blandingen ble laget til søtsaker først og tatt i bruk i annen mat siden',
      'Goda er et stedsnavn og ikke et ord for søt'],
   c:1, why:'Goda betyr søt, men viser her til en mild og rund profil, ikke en sukkerholdig blanding. Oppskriftene og grensen mot kala masala varierer.'},
  {q:'Hva er dagad phool?',
   a:['En tørket blomst som samles på Dekkan-platået',
      'En bark som flås av et tre i åsene og ristes',
      'En lav som skrapes av berg og bark',
      'En frøkapsel som bare åpner seg etter risting'],
   c:2, why:'Dagad phool betyr steinblomst, men er tørket, spiselig lav som ofte identifiseres blant Parmotrema-arter. Et beslektet produkt er kjent som kalpasi i tamilsk mat.'},
  {q:'Hvordan brukes dagad phool ofte i Maharashtra?',
   a:['Den ristes med andre hele krydder til blandinger som goda masala',
      'Den står for det meste av styrken i blandingen',
      'Den hindrer den malte blandingen i å harskne',
      'Den gir den mørke fargen'],
   c:0, why:'Dagad phool ristes ofte med andre hele krydder før blandingen males. Det nøyaktige smaksbidraget er diskret og avhenger av oppskriften.'}
 ],
 [
  {q:'Hvorfor klappes eller presses jowar- og bajra-bhakri ofte ut?',
   a:['Deigen er for varm til å kjevles rett etter blandingen',
      'Kjevling ville gjort den for tynn for flammen',
      'Sorghum og perlehirse har ikke gluten som holder deigen sammen',
      'Takken er for liten til en kjevlet skive'],
   c:2, why:'Disse glutenfrie deigene er skjøre, så klapping eller pressing er en vanlig måte å forme dem på. Erfarne kokker kan også kjevle enkelte utgaver.'},
  {q:'Hva kan litt jaggery gjøre i enkelte dal-oppskrifter fra Maharashtra?',
   a:['For å gjøre den til en søt avslutning på måltidet',
      'For at linsene skal bli møre fortere',
      'For at den skal holde seg til dagen etter',
      'For å runde av chilien og syren så ingen av dem står alene'],
   c:3, why:'I oppskrifter som bruker den, kan litt jaggery balansere chili og syrlige ingredienser. Andre amti-oppskrifter utelater den.'},
  {q:'Hva lages katachi amti av?',
   a:['Vannet chana dalen til puran poli ble kokt i',
      'Det som sitter igjen i pannen etter at vade er stekt',
      'Kokum trukket sammen med tynn kokosmelk',
      'Kjernemelk spedd med vannet risen er skylt i'],
   c:0, why:'Festretten legger igjen et biprodukt, og det kastes ikke. Kokevannet smakes til med goda masala, tamarind og jaggery og serveres ved siden av det søte brødet.'}
 ],
 [
  {q:'Hvorfor settes en tallerken misal sammen i aller siste liten?',
   a:['Spirene koker videre i den varme usalen',
      'Det stekte topplaget må holde seg sprøtt til det møter det våte',
      'Limen gjør den rå løken bitter hvis den blir stående',
      'Rassaen skiller seg hvis den helles på for tidlig'],
   c:1, why:'Farsan er det sprø lokket på en våt gryte. Settes retten sammen for tidlig, er sprøheten borte før skålen når bordet.'},
  {q:'Hvordan bør man forholde seg til at Ashok Vaidya får æren for vada pav?',
   a:['Som avgjort, siden boden fortsatt drives under navnet hans',
      'Som feil, fordi retten er mye eldre enn spinneriene',
      'Som en utbredt fortelling, ikke som et dokumentert faktum',
      'Som en rettslig avgjørelse, fordi en domstol tok stilling til det'],
   c:2, why:'De fleste beretninger nevner ham og daterer retten til Bombay på 1960- eller 1970-tallet, men andre boder har gjort krav på den, og ingenting av det er dokumentert.'},
  {q:'Hva er pandhra rassa og tambda rassa?',
   a:['To chilier, den ene brukt til farge og den andre til styrke',
      'Den tørre og den våte utgaven av den samme kolhapuriske retten',
      'En lys kokossaus og en chilirød saus til et kolhapurisk kjøttmåltid',
      'Navnene på første og andre pressing av kokosmelk'],
   c:2, why:'Pandhra rassa er lys av kokos og ofte frø eller nøtter; tambda rassa er rød av chili og masala. Oppskriftene og om de deler én kraft, varierer.'}
 ],
 [
  {q:'Hva bidro til å utvide markedet for bærbar gatemat i Bombay?',
   a:['Spinneristrøkene og travle jernbanestasjoner',
      'Portugisiske kjøkken som ble igjen etter at øyene skiftet eier',
      'Mangel på brensel til matlaging i byen gjennom 1900-tallet',
      'Regler som forbød å selge tilberedt mat innendørs'],
   c:0, why:'Skiftarbeid, tettbygde strøk og pendlertrafikk skapte etterspørsel etter rimelig mat som var rask å servere og enkel å bære.'},
  {q:'Hvilke samfunn ble forbundet med Irani-kaféene?',
   a:['Parsier som hadde kommet til Gujarat omkring tusen år tidligere',
      'Senere innvandrere fra Iran, både zoroastriere og andre religiøse samfunn',
      'Armenske handelsmenn som slo seg ned i Fort etter 1850',
      'Goanske katolikker som flyttet nordover med jernbanen'],
   c:1, why:'Eierne kom gjennom senere migrasjon fra Iran og omfattet både zoroastriere og mennesker fra andre iranske religiøse samfunn. De var ulike det eldre parsiske samfunnet.'},
  {q:'Hvorfor ventes det med potetstrimlene på sali boti til i siste liten?',
   a:['De suger til seg eddiken og gjør sausen tynn',
      'De saltes for seg og ville gjort retten for salt',
      'Retten serveres kald, og strimlene må være varme',
      'Hele poenget med retten er et sprøtt og tørt topplag på en klebrig gryte'],
   c:3, why:'Sali er selve strimlene, og retten har navn etter dem. Røres de inn, blir de myke, og da forsvinner den kontrasten retten finnes for.'}
 ]
];
