/* Masala Dabba — oppsummeringsspørsmål for Maharashtra (IN-MAH), norsk. Kontrakt: docs/quiz-format.md.
   Samme antall lesetekster, samme antall spørsmål og samme riktige svarindeks som den engelske filen.
   Spørsmålene leses aldri opp, så en endring her gjør ingen lydfil utdatert. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-MAH'] = [
 [
  {q:'Hvorfor kalles goda masala søt når det ikke går sukker i den?',
   a:['Den ristede kokosen i den smaker søtt av seg selv',
      'Navnet er en sammenligning med den langt sterkere kala masalaen',
      'Blandingen ble laget til søtsaker først og tatt i bruk i annen mat siden',
      'Goda er et stedsnavn og ikke et ord for søt'],
   c:1, why:'Goda betyr riktignok søt på marathi, men navnet forteller om en sammenligning. Ved siden av den chilitunge kala masalaen på samme hylle er goda masala åpenbart den mildeste.'},
  {q:'Hva er dagad phool?',
   a:['En tørket blomst som samles på Dekkan-platået',
      'En bark som flås av et tre i åsene og ristes',
      'En lav som skrapes av berg og bark',
      'En frøkapsel som bare åpner seg etter risting'],
   c:2, why:'Dagad phool betyr steinblomst og er ingen av delene. Det er en lav i slekten Parmotrema, og Tamil Nadu selger den samme organismen som kalpasi.'},
  {q:'Hva gjør laven egentlig i goda masala?',
   a:['Den legger en bunn av jord og gammelt treverk under den ristede kokosen',
      'Den står for det meste av styrken i blandingen',
      'Den hindrer den malte blandingen i å harskne',
      'Den gir den mørke fargen'],
   c:0, why:'Ristet kokos er søt og rund og kan bli for myk. Laven legger noe smaksrikt under den, og en blanding uten er rett og slett tynnere.'}
 ],
 [
  {q:'Hvorfor må bhakri klappes ut for hånd i stedet for å kjevles?',
   a:['Deigen er for varm til å kjevles rett etter blandingen',
      'Kjevling ville gjort den for tynn for flammen',
      'Sorghum og perlehirse har ikke gluten som holder deigen sammen',
      'Takken er for liten til en kjevlet skive'],
   c:2, why:'Uten gluten er det ingenting som binder deigen under en kjevle. En våt håndflate og en fjøl er den eneste måten å få den flat i ett stykke på.'},
  {q:'Hvorfor går det jaggery i en helt vanlig dal i Maharashtra?',
   a:['For å gjøre den til en søt avslutning på måltidet',
      'For at linsene skal bli møre fortere',
      'For at den skal holde seg til dagen etter',
      'For å runde av chilien og syren så ingen av dem står alene'],
   c:3, why:'Den går i omtrent slik salt gjør, i en liten mengde. En amti uten jaggery smaker uferdig, ikke mindre søt.'},
  {q:'Hva lages katachi amti av?',
   a:['Vannet chana dalen til puran poli ble kokt i',
      'Det som sitter igjen i pannen etter at vade er stekt',
      'Kokum trukket sammen med tynn kokosmelk',
      'Kjernemelk spedd med vannet risen er skylt i'],
   c:0, why:'Festretten legger igjen et biprodukt, og det kastes ikke. Kokevannet smakes til med goda masala, tamarind og jaggery og serveres ved siden av det søte brødet.'}
 ],
 [
  {q:'Hvorfor settes en tallerken misal sammen i aller siste liten?',
   a:['Spirene koker videre i den varme usalen',
      'Det stekte topplaget må holde seg sprøtt til det møter det våte',
      'Limen gjør den rå løken bitter hvis den blir stående',
      'Rassaen skiller seg hvis den helles på for tidlig'],
   c:1, why:'Farsan er det sprø lokket på en våt gryte. Settes retten sammen for tidlig, er sprøheten borte før skålen når bordet.'},
  {q:'Hvordan bør man forholde seg til at Ashok Vaidya får æren for vada pav?',
   a:['Som avgjort, siden boden fortsatt drives under navnet hans',
      'Som feil, fordi retten er mye eldre enn spinneriene',
      'Som en utbredt fortelling, ikke som et dokumentert faktum',
      'Som en rettslig avgjørelse, fordi en domstol tok stilling til det'],
   c:2, why:'De fleste beretninger nevner ham og daterer retten til Bombay på 1960- eller 1970-tallet, men andre boder har gjort krav på den, og ingenting av det er dokumentert.'},
  {q:'Hva er pandhra rassa og tambda rassa?',
   a:['To chilier, den ene brukt til farge og den andre til styrke',
      'Den tørre og den våte utgaven av den samme kolhapuriske retten',
      'En hvit og en rød saus, begge laget av den samme kraften fra kjøttet',
      'Navnene på første og andre pressing av kokosmelk'],
   c:2, why:'Én kraft blir til to motsatte ting: hvit med kokos og pepper og uten chili, rød med kala masala og chiliene Bedgi og Lavangi. Begge kommer på bordet samtidig.'}
 ],
 [
  {q:'Hva formet gatematen i Bombay?',
   a:['Skiftene i spinneriene og livet på perrongen, der det verken var tallerken, bestikk eller sitteplass',
      'Portugisiske kjøkken som ble igjen etter at øyene skiftet eier',
      'Mangel på brensel til matlaging i byen gjennom 1900-tallet',
      'Regler som forbød å selge tilberedt mat innendørs'],
   c:0, why:'Rommene i chawlene hadde ikke kjøkken verdt navnet, og skiftene gav ingen tid. Hver rett som kjennetegner byen, svarer på den samme bestillingen: én hånd, ingen tallerken, ferdig før fløyta går.'},
  {q:'Hvem åpnet Irani-kaféene?',
   a:['Parsier som hadde kommet til Gujarat omkring tusen år tidligere',
      'Zoroastriere som kom fra Iran sent på 1800-tallet',
      'Armenske handelsmenn som slo seg ned i Fort etter 1850',
      'Goanske katolikker som flyttet nordover med jernbanen'],
   c:1, why:'De kom fra Yazd og Kerman, drevet ut av forfølgelse og tørke. De deler religion med det eldre parsiske samfunnet, men de er en annen ankomst.'},
  {q:'Hvorfor ventes det med potetstrimlene på sali boti til i siste liten?',
   a:['De suger til seg eddiken og gjør sausen tynn',
      'De saltes for seg og ville gjort retten for salt',
      'Retten serveres kald, og strimlene må være varme',
      'Hele poenget med retten er et sprøtt og tørt topplag på en klebrig gryte'],
   c:3, why:'Sali er selve strimlene, og retten har navn etter dem. Røres de inn, blir de myke, og da forsvinner den kontrasten retten finnes for.'}
 ]
];
