/* Masala Dabba — recap questions for Maharashtra (IN-MAH), English. Contract: docs/quiz-format.md,
   checked by tools/quizcheck.py. Four readings, three questions each. Questions are NEVER narrated. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-MAH'] = [
 [
  {q:'What does the name goda masala suggest?',
   a:['The roasted coconut in it tastes sweet on its own',
      'It is named by comparison with the much hotter kala masala',
      'It was originally a blend for sweets and later moved to savoury food',
      'Goda is a place name rather than a word for sweet'],
   c:1, why:'Goda means sweet, but here it points to a gentle, rounded profile rather than a sugary blend. Recipes and the boundary with kala masala vary.'},
  {q:'What is dagad phool?',
   a:['A dried flower gathered on the Deccan plateau',
      'A bark stripped from a hill tree and roasted',
      'A lichen scraped off rock and bark',
      'A seed pod that opens only after roasting'],
   c:2, why:'Dagad phool means stone flower but is dried edible lichen, commonly identified among Parmotrema species. A related product is known as kalpasi in Tamil cooking.'},
  {q:'How is dagad phool commonly used in Maharashtra?',
   a:['It is roasted with other whole spices for blends such as goda masala',
      'It adds most of the heat in the blend',
      'It keeps the ground blend from going rancid',
      'It supplies the dark colour'],
   c:0, why:'Dagad phool is commonly roasted with other whole spices before the blend is ground. Its exact sensory contribution is subtle and depends on the recipe.'}
 ],
 [
  {q:'Why are jowar and bajra bhakri often patted or pressed?',
   a:['The dough is too hot to roll straight after mixing',
      'Rolling would make it too thin for the flame',
      'Sorghum and pearl millet have no gluten to hold the dough together',
      'The griddle is too small for a rolled disc'],
   c:2, why:'These gluten-free doughs are fragile, so patting or pressing is a common way to shape them. Skilled cooks may also roll some versions.'},
  {q:'What can a little jaggery do in some Maharashtrian dal recipes?',
   a:['To make it a sweet course at the end of the meal',
      'To help the lentils soften faster',
      'To preserve it for a second day',
      'To round off the chilli and the sourness so neither stands alone'],
   c:3, why:'In recipes that use it, a little jaggery can balance chilli and souring ingredients. Other amti recipes omit it.'},
  {q:'What is katachi amti made from?',
   a:['The water the chana dal for puran poli was boiled in',
      'The scrapings left in the pan after frying vade',
      'Kokum steeped with thin coconut milk',
      'Buttermilk thinned with the rice-washing water'],
   c:0, why:'The festival sweet leaves a by-product, and it is not thrown away. The cooking water is seasoned with goda masala, tamarind and jaggery and served alongside the sweet bread.'}
 ],
 [
  {q:'Why is a plate of misal assembled at the last possible second?',
   a:['The sprouts continue to cook in the hot usal',
      'The fried topping has to stay crisp until it meets the wet layer',
      'The lime turns the raw onion bitter if it sits',
      'The rassa separates if it is poured early'],
   c:1, why:'Farsan is the crunchy lid on a wet curry. Build it early and the crunch is gone before the bowl reaches the table.'},
  {q:'How should the attribution of vada pav to Ashok Vaidya be treated?',
   a:['As settled, since the stall is still trading under his name',
      'As false, because the dish is much older than the mills',
      'As a credited story rather than a documented fact',
      'As a legal finding, because a court ruled on it'],
   c:2, why:'Most accounts name him and date the dish to Bombay in the 1960s or 70s, but other stalls have claimed it and none of it is documented.'},
  {q:'What are pandhra rassa and tambda rassa?',
   a:['Two chillies, one used for colour and one for heat',
      'The dry and the wet version of the same Kolhapuri dish',
      'A pale coconut gravy and a chilli-red gravy served with a Kolhapuri meat meal',
      'The names for the first and second pressing of coconut milk'],
   c:2, why:'Pandhra rassa is pale from coconut and often seeds or nuts; tambda rassa is red from chilli and masala. Recipes and whether they share one stock vary.'}
 ],
 [
  {q:'What helped expand the market for portable Bombay street food?',
   a:['Mill districts and busy railway stations',
      'Portuguese kitchens that stayed on after the islands changed hands',
      'A shortage of cooking fuel in the city through the 1900s',
      'Rules that banned cooked food from being sold indoors'],
   c:0, why:'Shift work, dense neighbourhoods and commuter traffic helped create demand for inexpensive food that was quick to serve and easy to carry.'},
  {q:'Which communities were associated with Irani cafés?',
   a:['Parsis who had arrived in Gujarat around a thousand years earlier',
      'Later migrants from Iran, including Zoroastrians and other religious communities',
      'Armenian traders who settled in Fort after 1850',
      'Goan Catholics who moved north with the railway'],
   c:1, why:'Irani café owners came through later migrations from Iran and included Zoroastrians as well as people from other Iranian religious communities. They were distinct from the older Parsi community.'},
  {q:'Why are the potato straws on sali boti added only at the last moment?',
   a:['They soak up the vinegar and turn the gravy thin',
      'They are salted separately and would make the dish too salty',
      'The dish is served cold and the straws must be warm',
      'The whole point of the dish is a crisp dry topping on a sticky stew'],
   c:3, why:'Sali means the straws, and the dish is named after them. Stir them in and they go soft, which removes the contrast the dish exists for.'}
 ]
];
