/* Masala Dabba — recap questions for Maharashtra (IN-MAH), English. Contract: docs/quiz-format.md,
   checked by tools/quizcheck.py. Four readings, three questions each. Questions are NEVER narrated. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-MAH'] = [
 [
  {q:'Why is goda masala called sweet when no sugar goes into it?',
   a:['The roasted coconut in it tastes sweet on its own',
      'It is named by comparison with the much hotter kala masala',
      'It was originally a blend for sweets and later moved to savoury food',
      'Goda is a place name rather than a word for sweet'],
   c:1, why:'Goda does mean sweet in Marathi, but the name is a comparison. Next to the chilli-heavy kala masala on the same shelf, goda masala is obviously the gentler of the two.'},
  {q:'What is dagad phool?',
   a:['A dried flower gathered on the Deccan plateau',
      'A bark stripped from a hill tree and roasted',
      'A lichen scraped off rock and bark',
      'A seed pod that opens only after roasting'],
   c:2, why:'Dagad phool means stone flower and is neither. It is a lichen of the genus Parmotrema, and Tamil Nadu sells the same organism as kalpasi.'},
  {q:'What does the lichen actually do in goda masala?',
   a:['It gives a floor of earth and old wood under the roasted coconut',
      'It adds most of the heat in the blend',
      'It keeps the ground blend from going rancid',
      'It supplies the dark colour'],
   c:0, why:'Roasted coconut is sweet and rounded and can turn soft. The lichen puts something savoury underneath it, and a blend without it is simply thinner.'}
 ],
 [
  {q:'Why must bhakri be patted out by hand rather than rolled?',
   a:['The dough is too hot to roll straight after mixing',
      'Rolling would make it too thin for the flame',
      'Sorghum and pearl millet have no gluten to hold the dough together',
      'The griddle is too small for a rolled disc'],
   c:2, why:'No gluten means nothing binds the dough under a rolling pin. A wet palm and a board are the only way to get it flat in one piece.'},
  {q:'Why does jaggery go into an everyday Maharashtrian dal?',
   a:['To make it a sweet course at the end of the meal',
      'To help the lentils soften faster',
      'To preserve it for a second day',
      'To round off the chilli and the sourness so neither stands alone'],
   c:3, why:'It goes in roughly the way salt does, in a small amount. An amti made without it tastes unfinished rather than less sweet.'},
  {q:'What is katachi amti made from?',
   a:['The water the chana dal for puran poli was boiled in',
      'The scrapings left in the pan after frying vade',
      'Kokum steeped with thin coconut milk',
      'Buttermilk thinned with the rice-washing water'],
   c:0, why:'The festival sweet leaves a by-product, and it is not thrown away. The cooking water is seasoned with goda masala, tamarind and jaggery and served alongside the sweet bread.'}
 ],
 [
  {q:'Why is a plate of misal assembled at the last possible second?',
   a:['The sprouts continue to cook in the hot usal',
      'The fried topping has to stay crisp until it meets the wet layer',
      'The lime turns the raw onion bitter if it sits',
      'The rassa separates if it is poured early'],
   c:1, why:'Farsan is the crunchy lid on a wet curry. Build it early and the crunch is gone before the bowl reaches the table.'},
  {q:'How should the attribution of vada pav to Ashok Vaidya be treated?',
   a:['As settled, since the stall is still trading under his name',
      'As false, because the dish is much older than the mills',
      'As a credited story rather than a documented fact',
      'As a legal finding, because a court ruled on it'],
   c:2, why:'Most accounts name him and date the dish to Bombay in the 1960s or 70s, but other stalls have claimed it and none of it is documented.'},
  {q:'What are pandhra rassa and tambda rassa?',
   a:['Two chillies, one used for colour and one for heat',
      'The dry and the wet version of the same Kolhapuri dish',
      'A white gravy and a red one, both made from the same mutton stock',
      'The names for the first and second pressing of coconut milk'],
   c:2, why:'One stock becomes two opposite things: white with coconut and pepper and no chilli at all, red with kala masala and Bedgi and Lavangi. Both reach the table at once.'}
 ],
 [
  {q:'What shaped the design of Bombay street food?',
   a:['Mill shifts and train platforms, which left no plate, cutlery or seat',
      'Portuguese kitchens that stayed on after the islands changed hands',
      'A shortage of cooking fuel in the city through the 1900s',
      'Rules that banned cooked food from being sold indoors'],
   c:0, why:'Chawls had no real kitchens and shifts left no time. Every characteristic dish of the city answers the same brief: one hand, no plate, ready before the siren.'},
  {q:'Who opened the Irani cafés?',
   a:['Parsis who had arrived in Gujarat around a thousand years earlier',
      'Zoroastrians who came from Iran in the late nineteenth century',
      'Armenian traders who settled in Fort after 1850',
      'Goan Catholics who moved north with the railway'],
   c:1, why:'They came from Yazd and Kerman, driven out by persecution and drought. They share a religion with the older Parsi community but are a separate arrival.'},
  {q:'Why are the potato straws on sali boti added only at the last moment?',
   a:['They soak up the vinegar and turn the gravy thin',
      'They are salted separately and would make the dish too salty',
      'The dish is served cold and the straws must be warm',
      'The whole point of the dish is a crisp dry topping on a sticky stew'],
   c:3, why:'Sali means the straws, and the dish is named after them. Stir them in and they go soft, which removes the contrast the dish exists for.'}
 ]
];
