/* Masala Dabba — repetisjonsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme riktige svarindeks som den engelske filen. Spørsmål leses aldri
   inn som lyd, så en endring her kan ikke gjøre en lydfil utdatert. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-NEA'] = [
 [
  {q:'Hva lages khar av?',
   a:['Malte sennepsfrø rørt sammen med salt',
      'Aske fra bananskall, filtrert med vann',
      'En sur frukt som er tørket og røykt over bål',
      'Kokte soyabønner støtt til en pasta'],
   c:1, why:'Bananskall eller tørket bananstamme brennes til lys aske, vann helles langsomt gjennom, og den basiske væsken som drypper ut, heter kolakhar.'},
  {q:'Hvorfor ber kurset deg bruke hansker til bhut jolokia?',
   a:['Frukten gir varige flekker på huden',
      'All fersk chili er farlig å ta på',
      'Mengden capsaicin kan være ekstrem og varierer mellom fruktene',
      'Hansker hindrer at chilien mister røykaromaen'],
   c:2, why:'Bhut jolokia kan spises fersk, røykes, støtes til chutney eller kokes. Målt mengde og hansker gjør den skiftende, ekstreme styrken tryggere å håndtere.'},
  {q:'Hva har axone, kinema, tungrymbai og ngari felles?',
   a:['De er alle gjærede råvarer, og den sterke lukten viser at råvaren arbeider',
      'De lages alle av unge bambusskudd',
      'De er malte krydderblandinger som står i en boks',
      'De er sure frukter som brukes til å syrne en kraft'],
   c:0, why:'Tre er gjærede soyaprodukter og ngari er gjæret fisk. En forventet kraftig lukt kan være normal, men trygg produksjon og riktig lagring er fortsatt viktig.'}
 ],
 [
  {q:'Hva er det uvanlige ved komal saul, den myke risen fra Assam?',
   a:['Den dyrkes på terrasser over to tusen meter',
      'Den må males til mel før den kan spises',
      'Den kokes bare til høsttakkefesten i januar',
      'Behandlingen gjør at bløtlegging mykner den uten en ny kokerunde'],
   c:3, why:'Komal eller kumol saul behandles særskilt før salg. Bløtleggingstid og vanntemperatur varierer, så et pakket produkt bør tilberedes etter anvisningen.'},
  {q:'Hva er en pitika?',
   a:['En kokt eller svidd grønnsak most sammen med rå sennepsolje, løk og chili',
      'En riskake dampet i et grønt bambusrør',
      'En tynn sur kraft som serveres sist i måltidet',
      'En pakke klebrig ris viklet inn i et blad'],
   c:0, why:'Den er tørr, rå i smaken og skarp mot en ellers våt tallerken, og det er den jobben en pickles gjør lenger vest.'},
  {q:'Hvilken rekkefølge kan finnes i et formelt assamesisk måltid?',
   a:['Alt settes fram samtidig på ett blad',
      'Den basiske retten først og den sure sist',
      'Den sure retten først og den basiske sist',
      'Noe søtt først, så fisken, så risen'],
   c:1, why:'Et formelt måltid kan åpne med basisk khar og slutte med sur tenga. Det er en kjent mattradisjon, ikke en fast lov for alle husholdninger.'}
 ],
 [
  {q:'Hva syrner en masor tenga?',
   a:['Tamarind, i alle utgaver av retten',
      'Outenga, tørket thekera, tomat eller sitron, alt etter hva man har',
      'Yoghurt vispet inn med kjelen av platen',
      'Gjæret soyabønne malt til en pasta'],
   c:1, why:'Assam har flere syrningsmidler og bruker det sesongen gir. Det faste er den tynne kraften og den korte koketiden, ikke frukten.'},
  {q:'Hvilke råvarer krydrer ofte naga-retter med svinekjøtt?',
   a:['En masala av ti malte krydder, bygd opp langsomt',
      'Kokosmelk, karriblad og sennepsfrø',
      'Yoghurt, fløte og hel kardemomme',
      'Gjærede bambusskudd eller axone, i kombinasjoner som varierer'],
   c:3, why:'Gjærede bambusskudd, axone eller anishi kan brukes med svin, mens urter, ingefær og chili varierer med samfunn og kokk.'},
  {q:'Hva er eromba?',
   a:['Kokte grønnsaker most sammen med ristet ngari og tørket chili',
      'Rød ris kokt med svinekjøtt til den tar fargen av kjøttet',
      'En kraft med nudler, grønnsaker og kjøtt fra Sikkim',
      'Svinekjøtt hengt over ildstedet og røykt i flere uker'],
   c:0, why:'Det er en meitei-rett av kokte grønnsaker, chili og ofte gjæret fisk. Server raskt, eller sett retten kaldt etter avkjøling.'}
 ],
 [
  {q:'Hvem var ahomene?',
   a:['Portugisiske kjøpmenn som slo seg ned ved nedre Brahmaputra',
      'Et tai-folk som kom over fra øvre Burma i 1228',
      'Et mogulsk dynasti som ble satt til å styre Assam',
      'En khasi-klan som hersket over åsene i Meghalaya'],
   c:1, why:'Sukaphaa krysset Patkai i 1228. Ahomstaten utviklet seg så gjennom århundrer med allianser, konflikt og innlemmelse i Brahmaputradalen.'},
  {q:'Hva formet råvaremønstrene i Nordøst-India?',
   a:['Et britisk forbud mot krydderhandel etter 1830',
      'Et klima der alt tørket krydder ble ødelagt',
      'Økologi, lokale valg og handel i flere retninger',
      'En felles religiøs regel mot malt krydder'],
   c:2, why:'Ruter knyttet Bengal og Brahmaputradalen til pass mot Myanmar, Bhutan og Tibet. Økologi, preferanser og gjentatt utveksling skapte ulike lokale spiskamre.'},
  {q:'Hvordan kom teen til Assam?',
   a:['Ahom-kongene plantet den på 1400-tallet',
      'Buddhistiske munker bar den over Patkai-åsene',
      'Portugisiske skip fraktet planten fra Kina',
      'Lokale samfunn brukte den før plantasjene vokste fra 1830-årene'],
   c:3, why:'Singphoer og andre samfunn kjente lokal te før britisk kommersiell dyrking. Koloniale selskaper utvidet plantasjene med kapital og tvangspreget rekruttering av migrantarbeidere.'}
 ]
];
