/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-NEA'] = [
 [
  {q:'What is khar made from?',
   a:['Ground mustard seed worked with salt',
      'The ash of banana peel, filtered with water',
      'A sour fruit dried and smoked over a fire',
      'Boiled soybeans pounded into a paste'],
   c:1, why:'Banana peel or dried banana trunk is burnt to a pale ash, water is poured slowly through it, and the alkaline liquid that drips out is kolakhar.'},
  {q:'Why is bhut jolokia usually eaten raw beside the food rather than cooked into it?',
   a:['Cooking destroys its heat almost completely',
      'It is reserved for offerings and cannot go in a pot',
      'Nothing on the plate would soften the heat once it had spread through a dish',
      'The skin turns bitter the moment it is heated'],
   c:2, why:'There is no coconut milk, no cream and no yoghurt anywhere in the region to catch the heat, so the eater controls it instead of the cook.'},
  {q:'What do axone, kinema, tungrymbai and ngari have in common?',
   a:['They are ferments, and their strong smell is the ingredient working',
      'They are all made from young bamboo shoots',
      'They are ground spice blends kept in a tin',
      'They are sour fruits used to acidify a broth'],
   c:0, why:'Three are fermented soybeans and one is fermented fish. The ammoniacal smell belongs to the ferment in the way a cellar smell belongs to a ripe cheese.'}
 ],
 [
  {q:'What is unusual about komal saul, Assam’s soft rice?',
   a:['It is grown on terraces above two thousand metres',
      'It has to be ground to flour before it is eaten',
      'It is only cooked at the January harvest festival',
      'It needs no cooking, only twenty minutes in warm water'],
   c:3, why:'The grain is soaked and parboiled in a particular way at the mill. After that a bowl of it in warm water is a meal, which is why it needs no fuel.'},
  {q:'What is a pitika?',
   a:['A boiled or roasted vegetable mashed with raw mustard oil, onion and chilli',
      'A rice cake steamed in a length of green bamboo',
      'A thin sour broth served at the end of the meal',
      'A parcel of sticky rice wrapped in a leaf'],
   c:0, why:'It is dry, raw-tasting and sharp against an otherwise wet plate, which is the job a pickle does further west.'},
  {q:'In what order does a traditional Assamese meal run?',
   a:['Everything arrives together on one leaf',
      'The alkaline dish first and the sour one last',
      'The sour dish first and the alkaline one last',
      'Sweet first, then the fish, then the rice'],
   c:1, why:'The meal opens with khar and closes with tenga. The two are chemical opposites, which is also why they never share a bowl.'}
 ],
 [
  {q:'What sours a masor tenga?',
   a:['Tamarind, in every version of the dish',
      'Elephant apple, dried thekera, tomato or lemon, whichever is to hand',
      'Yoghurt whisked in with the heat turned off',
      'Fermented soybean ground to a paste'],
   c:1, why:'Assam keeps several souring agents and uses whichever the season offers. What is fixed is the thin broth and the fast cooking, not the fruit.'},
  {q:'What goes into a Naga pot alongside smoked pork?',
   a:['A masala of ten ground spices, built up slowly',
      'Coconut milk, curry leaf and mustard seed',
      'Yoghurt, cream and whole cardamom',
      'One strong ferment, either bamboo shoot or axone'],
   c:3, why:'Beyond the ferment there is salt, chilli, ginger and water. The flavours are large, direct and few, and the style does not try to be subtle.'},
  {q:'What is eromba?',
   a:['Boiled vegetables mashed with roasted ngari and dried chilli',
      'Red rice cooked with pork until it takes the colour of the meat',
      'A broth of noodles, vegetables and meat from Sikkim',
      'Pork hung above the hearth and smoked for several weeks'],
   c:0, why:'It is a Meitei dish from the Manipur valley, served at room temperature, and the ngari is roasted over a flame before it is crumbled in.'}
 ],
 [
  {q:'Who were the Ahoms?',
   a:['Portuguese traders who settled on the lower Brahmaputra',
      'A Tai people who crossed from upper Burma in 1228',
      'A Mughal dynasty appointed to govern Assam',
      'A Khasi clan that ruled the Meghalaya hills'],
   c:1, why:'Sukaphaa led a few thousand followers over the Patkai hills, and the kingdom they founded held the valley for about six hundred years.'},
  {q:'Why did the Indian spice pantry never reach these eight states?',
   a:['The British banned the spice trade here in the 1830s',
      'The wet climate destroyed dried spice within weeks',
      'Trade ran east into Burma, and the local kitchen had no gap to fill',
      'Religious rules in the hills forbade the use of ground spice'],
   c:2, why:'A kitchen that already had a sour fruit, an alkali, a fermented fish, a fermented bean and a very hot chilli had nothing a spice merchant could sell it.'},
  {q:'How did tea come to Assam?',
   a:['Ahom kings planted it in the fifteenth century',
      'Buddhist monks carried it over the Patkai hills',
      'Portuguese ships brought the plant from China',
      'It grew wild there, and the British planted estates from the 1830s'],
   c:3, why:'Robert Bruce was told of the wild plant among the Singpho in 1823, the Assam Company was formed in 1839, and labour was recruited a thousand kilometres away.'}
 ]
];
