/* Masala Dabba — repetisjonsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme riktige svarindeks som den engelske filen. Spørsmål leses aldri
   inn som lyd, så en endring her kan ikke gjøre en lydfil utdatert. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-NEA'] = [
 [
  {q:'Hva lages khar av?',
   a:['Malte sennepsfrø rørt sammen med salt',
      'Aske fra bananskall, filtrert med vann',
      'En sur frukt som er tørket og røykt over bål',
      'Kokte soyabønner støtt til en pasta'],
   c:1, why:'Bananskall eller tørket bananstamme brennes til lys aske, vann helles langsomt gjennom, og den basiske væsken som drypper ut, heter kolakhar.'},
  {q:'Hvorfor spises bhut jolokia som regel rå ved siden av maten i stedet for kokt i den?',
   a:['Koking ødelegger nesten hele styrken',
      'Den er forbeholdt offergaver og kan ikke gå i en gryte',
      'Ingenting på tallerkenen kunne dempet styrken når den først var spredt i retten',
      'Skallet blir bittert i det øyeblikket det varmes opp'],
   c:2, why:'I hele regionen finnes det verken kokosmelk, fløte eller yoghurt som kan fange opp styrken, så den som spiser, styrer den i stedet for kokken.'},
  {q:'Hva har axone, kinema, tungrymbai og ngari felles?',
   a:['De er alle gjærede råvarer, og den sterke lukten viser at råvaren arbeider',
      'De lages alle av unge bambusskudd',
      'De er malte krydderblandinger som står i en boks',
      'De er sure frukter som brukes til å syrne en kraft'],
   c:0, why:'Tre av dem er gjærede soyabønner og én er gjæret fisk. Ammoniakklukten hører til gjæringen slik kjellerlukten hører til en moden ost.'}
 ],
 [
  {q:'Hva er det uvanlige ved komal saul, den myke risen fra Assam?',
   a:['Den dyrkes på terrasser over to tusen meter',
      'Den må males til mel før den kan spises',
      'Den kokes bare til høsttakkefesten i januar',
      'Den trenger ingen koking, bare tjue minutter i lunkent vann'],
   c:3, why:'Kornet bløtlegges og forkokes på en bestemt måte på mølla. Etterpå er en skål i lunkent vann et måltid, og derfor krever risen ikke brensel.'},
  {q:'Hva er en pitika?',
   a:['En kokt eller svidd grønnsak most sammen med rå sennepsolje, løk og chili',
      'En riskake dampet i et grønt bambusrør',
      'En tynn sur kraft som serveres sist i måltidet',
      'En pakke klebrig ris viklet inn i et blad'],
   c:0, why:'Den er tørr, rå i smaken og skarp mot en ellers våt tallerken, og det er den jobben en pickles gjør lenger vest.'},
  {q:'I hvilken rekkefølge går et tradisjonelt måltid i Assam?',
   a:['Alt settes fram samtidig på ett blad',
      'Den basiske retten først og den sure sist',
      'Den sure retten først og den basiske sist',
      'Noe søtt først, så fisken, så risen'],
   c:1, why:'Måltidet åpner med khar og lukkes med tenga. De to er kjemiske motsetninger, og det er også grunnen til at de aldri møtes i samme skål.'}
 ],
 [
  {q:'Hva syrner en masor tenga?',
   a:['Tamarind, i alle utgaver av retten',
      'Outenga, tørket thekera, tomat eller sitron, alt etter hva man har',
      'Yoghurt vispet inn med kjelen av platen',
      'Gjæret soyabønne malt til en pasta'],
   c:1, why:'Assam har flere syrningsmidler og bruker det sesongen gir. Det faste er den tynne kraften og den korte koketiden, ikke frukten.'},
  {q:'Hva går i gryta sammen med det røykte svinekjøttet i Nagaland?',
   a:['En masala av ti malte krydder, bygd opp langsomt',
      'Kokosmelk, karriblad og sennepsfrø',
      'Yoghurt, fløte og hel kardemomme',
      'Én kraftig gjæret ingrediens, enten bambusskudd eller axone'],
   c:3, why:'Utover gjæringen er det salt, chili, ingefær og vann. Smakene er store, direkte og få, og stilen prøver ikke å være finstemt.'},
  {q:'Hva er eromba?',
   a:['Kokte grønnsaker most sammen med ristet ngari og tørket chili',
      'Rød ris kokt med svinekjøtt til den tar fargen av kjøttet',
      'En kraft med nudler, grønnsaker og kjøtt fra Sikkim',
      'Svinekjøtt hengt over ildstedet og røykt i flere uker'],
   c:0, why:'Retten kommer fra meiteiene i dalen i Manipur, den serveres ved romtemperatur, og ngarien ristes over flammen før den smuldres oppi.'}
 ],
 [
  {q:'Hvem var ahomene?',
   a:['Portugisiske kjøpmenn som slo seg ned ved nedre Brahmaputra',
      'Et tai-folk som kom over fra øvre Burma i 1228',
      'Et mogulsk dynasti som ble satt til å styre Assam',
      'En khasi-klan som hersket over åsene i Meghalaya'],
   c:1, why:'Sukaphaa førte noen tusen følgesvenner over Patkai-åsene, og riket de grunnla, holdt dalen i omkring seks hundre år.'},
  {q:'Hvorfor nådde den indiske krydderhylla aldri disse åtte delstatene?',
   a:['Britene forbød krydderhandelen her på 1830-tallet',
      'Det våte klimaet ødela tørket krydder på få uker',
      'Handelen gikk østover mot Burma, og det lokale kjøkkenet hadde ingen åpning å fylle',
      'Religiøse regler i åsene forbød bruk av malt krydder'],
   c:2, why:'Et kjøkken som allerede hadde en sur frukt, en lut, en gjæret fisk, en gjæret bønne og en svært sterk chili, hadde ingenting en krydderhandler kunne selge det.'},
  {q:'Hvordan kom teen til Assam?',
   a:['Ahom-kongene plantet den på 1400-tallet',
      'Buddhistiske munker bar den over Patkai-åsene',
      'Portugisiske skip fraktet planten fra Kina',
      'Den vokste vilt der, og britene anla plantasjer fra 1830-årene'],
   c:3, why:'Robert Bruce fikk høre om den ville planten hos singphoene i 1823, Assam Company ble stiftet i 1839, og arbeidskraften ble hentet hundre mil unna.'}
 ]
];
