/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-NEA'] = [
 [
  {q:'What is khar made from?',
   a:['Ground mustard seed worked with salt',
      'The ash of banana peel, filtered with water',
      'A sour fruit dried and smoked over a fire',
      'Boiled soybeans pounded into a paste'],
   c:1, why:'Banana peel or dried banana trunk is burnt to a pale ash, water is poured slowly through it, and the alkaline liquid that drips out is kolakhar.'},
  {q:'Why does the course call for gloves when handling bhut jolokia?',
   a:['The fruit stains skin permanently',
      'It is unsafe to touch any fresh chilli',
      'Its capsaicin level can be extreme and varies between fruits',
      'Gloves keep the chilli from losing its smoke aroma'],
   c:2, why:'Bhut jolokia may be eaten fresh, smoked, made into chutney or cooked. A measured quantity and gloves make that variable, extreme heat safer to handle.'},
  {q:'What do axone, kinema, tungrymbai and ngari have in common?',
   a:['They are ferments, and their strong smell is the ingredient working',
      'They are all made from young bamboo shoots',
      'They are ground spice blends kept in a tin',
      'They are sour fruits used to acidify a broth'],
   c:0, why:'Three are fermented soybean foods and ngari is fermented fish. A strong expected aroma may be normal, but established production and proper storage still matter.'}
 ],
 [
  {q:'What is unusual about komal saul, Assam’s soft rice?',
   a:['It is grown on terraces above two thousand metres',
      'It has to be ground to flour before it is eaten',
      'It is only cooked at the January harvest festival',
      'Processing lets it soften by soaking without another cooking stage'],
   c:3, why:'Komal or kumol saul is specially processed before sale. Soaking time and water temperature vary, so a packaged product should be prepared according to its instructions.'},
  {q:'What is a pitika?',
   a:['A boiled or roasted vegetable mashed with raw mustard oil, onion and chilli',
      'A rice cake steamed in a length of green bamboo',
      'A thin sour broth served at the end of the meal',
      'A parcel of sticky rice wrapped in a leaf'],
   c:0, why:'It is dry, raw-tasting and sharp against an otherwise wet plate, which is the job a pickle does further west.'},
  {q:'What progression may appear in a formal Assamese meal?',
   a:['Everything arrives together on one leaf',
      'The alkaline dish first and the sour one last',
      'The sour dish first and the alkaline one last',
      'Sweet first, then the fish, then the rice'],
   c:1, why:'A formal meal may open with alkaline khar and close with sour tenga. It is a recognised culinary progression rather than a fixed law for every household.'}
 ],
 [
  {q:'What sours a masor tenga?',
   a:['Tamarind, in every version of the dish',
      'Elephant apple, dried thekera, tomato or lemon, whichever is to hand',
      'Yoghurt whisked in with the heat turned off',
      'Fermented soybean ground to a paste'],
   c:1, why:'Assam keeps several souring agents and uses whichever the season offers. What is fixed is the thin broth and the fast cooking, not the fruit.'},
  {q:'Which ingredients commonly flavour Naga pork dishes?',
   a:['A masala of ten ground spices, built up slowly',
      'Coconut milk, curry leaf and mustard seed',
      'Yoghurt, cream and whole cardamom',
      'Fermented bamboo shoot or axone, with combinations varying by community'],
   c:3, why:'Fermented bamboo shoot, axone or anishi may appear with pork, while herbs, ginger and chilli vary by community and cook.'},
  {q:'What is eromba?',
   a:['Boiled vegetables mashed with roasted ngari and dried chilli',
      'Red rice cooked with pork until it takes the colour of the meat',
      'A broth of noodles, vegetables and meat from Sikkim',
      'Pork hung above the hearth and smoked for several weeks'],
   c:0, why:'It is a Meitei dish of cooked vegetables, chilli and often fermented fish. Serve it promptly, or refrigerate it after cooling.'}
 ],
 [
  {q:'Who were the Ahoms?',
   a:['Portuguese traders who settled on the lower Brahmaputra',
      'A Tai people who crossed from upper Burma in 1228',
      'A Mughal dynasty appointed to govern Assam',
      'A Khasi clan that ruled the Meghalaya hills'],
   c:1, why:'Sukaphaa crossed the Patkai in 1228. The Ahom state then developed through centuries of alliance, conflict and incorporation in the Brahmaputra valley.'},
  {q:'What shaped ingredient patterns across the Northeast?',
   a:['A British ban on spice trading after 1830',
      'A climate in which every dried spice spoiled',
      'Ecology, community preference and trade in several directions',
      'A shared religious rule against ground spice'],
   c:2, why:'Routes linked Bengal, the Brahmaputra valley and passes toward Myanmar, Bhutan and Tibet. Ecology, preference and repeated exchange produced different local pantries.'},
  {q:'How did tea come to Assam?',
   a:['Ahom kings planted it in the fifteenth century',
      'Buddhist monks carried it over the Patkai hills',
      'Portuguese ships brought the plant from China',
      'Local communities used it before colonial estates expanded from the 1830s'],
   c:3, why:'Singpho and other communities knew local tea before British commercial planting. Colonial companies expanded estates using capital and coercively recruited migrant labour.'}
 ]
];
