/* Masala Dabba — repetisjonsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme riktige svar som den engelske filen. Spørsmålene leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-PUN'] = [
 [
  {q:'Hvorfor går garam masala som regel i retten til slutt og ikke i starten?',
   a:['Den ville gjort sausen for tykk hvis den gikk i tidlig',
      'Den må løses opp i meieriprodukter, som kommer sist',
      'Duften sitter i flyktige oljer som lang koking driver bort',
      'Den svir seg ved lavere temperatur enn malt chili'],
   c:2, why:'Litt garam masala mot slutten bevarer en frisk duft fra de flyktige oljene. Oppskrifter kan også bruke blandingen tidligere for å få en annen virkning.'},
  {q:'Hvorfor lukter ajwain så sterkt av timian?',
   a:['Det er en timiansort som dyrkes på slettene i Punjab',
      'Frøet inneholder tymol, det samme stoffet som preger timian',
      'Det selges som regel blandet med tørket timian',
      'Det tørkes på timianbusker i sola'],
   c:1, why:'De to plantene er ikke i slekt. De deler tymol, og derfor kjenner en europeisk nese ajwain igjen med en gang.'},
  {q:'Hva gjør amchur som en skvett sitron ikke klarer?',
   a:['Den syrner retten uten å tilføre væske',
      'Den syrner retten og søter den samtidig',
      'Den beholder syren gjennom timevis med koking',
      'Den tykner sausen i tillegg til å syrne den'],
   c:0, why:'Amchur er tørt, og derfor passer det i fylte parathaer, i tørre potetretter og i kikerter, der mer væske bare ville vært til bry.'}
 ],
 [
  {q:'Hvorfor er brød og ikke ris basismaten i denne regionen?',
   a:['Ris var for dyrt for de fleste punjabiske husholdninger',
      'Hvete er en tørrsesongavling og passer til en kald, tørr punjabisk vinter',
      'Britene motarbeidet risdyrking i Punjab',
      'Jorda er for grunn til en rismark'],
   c:1, why:'Hveten sås etter monsunen og vokser gjennom den kjølige, tørre vinteren. Vannet ris er også viktig, men brød står fortsatt sentralt i mange måltider.'},
  {q:'Hva forandret hvetesortene med korte strå fra 1960-tallet?',
   a:['De modnet en måned tidligere og ga plass til to avlinger i året',
      'De trengte ikke vanning i det hele tatt',
      'De motstod skadedyrene som hadde ødelagt tidligere avlinger',
      'De la seg ikke selv om de ble tungt gjødslet, så de tålte både gjødsel og vann'],
   c:3, why:'En høy hvete som får rikelig med gjødsel, kan få tunge aks og legge seg. Sortene med korte strå ble stående og bidro til at produksjonen steg raskt.'},
  {q:'Hva får du når du kjerner en gryte syrnet melk med vann i et punjabisk kjøkken?',
   a:['Ghee og khoya', 'Paneer og myse', 'Lassi og hvitt smør', 'Dahi og fløte'],
   c:2, why:'Smøret stiger opp og blir makhan. Væsken under er en tradisjonell tynn lassi, som ofte saltes.'}
 ],
 [
  {q:'Hvorfor går en neve maismel i sarson da saag?',
   a:['Det tykner bladene og gir en sødme som står mot sennepen',
      'Det hindrer at bladene mister fargen i gryta',
      'Det erstatter smøret i en husholdning som ikke har noe',
      'Det korter koketiden ned fra to timer til tjue minutter'],
   c:0, why:'Maisen både tykner og søter, og det er det samme melet som makki-rotien ved siden av lages av.'},
  {q:'Hvor kommer den tykke, kremete konsistensen i dal makhani egentlig fra?',
   a:['Tomaten som kokes ned i starten',
      'Smøret som røres inn til slutt',
      'Godt kokte belgfrukter som går i stykker og tykner væsken',
      'Kidneybønner som moses og røres tilbake'],
   c:2, why:'Koking i gryte eller trykkoker gjør belgfruktene møre. Småkoking, omrøring og lett mosing tykner deretter sausen, mens smør og fløte gir fylde.'},
  {q:'Hvorfor bygges en tandoorimarinade på yoghurt og ikke på en tynn væske?',
   a:['Yoghurt holder kjøttet kaldt lenger i et varmt kjøkken',
      'Syren bidrar til å mørne overflaten, og tykk yoghurt holder krydderet inntil kjøttet',
      'Yoghurten gir retten den røde fargen',
      'Det var den eneste syren en region uten kyst hadde'],
   c:1, why:'Tykk yoghurt dekker kyllingen og holder krydderet på plass. Syren bidrar til å mørne overflaten under marineringen.'}
 ],
 [
  {q:'Når ble Radcliffe-grensen gjennom Punjab offentliggjort?',
   a:['Et halvt år før selvstendigheten, så folk kunne rekke å flytte',
      'På selve selvstendighetsdagen',
      'I 1948, etter det verste av volden',
      '17. august 1947, etter selvstendighetsseremoniene'],
   c:3, why:'Streken var tegnet på omtrent fem uker og ble offentliggjort etter selvstendighetsseremoniene. Da var folk allerede på vandring uten å vite hvor den ville gå.'},
  {q:'Hva sier leseteksten om hvem som fant opp butter chicken?',
   a:['Den ble utvilsomt laget på Moti Mahal i Daryaganj',
      'Den kom ut av de punjabiske flyktningkjøkkenene i Delhi, men den nøyaktige påstanden er omstridt',
      'Den ble funnet opp i Peshawar før delingen',
      'Den ble funnet opp på en britisk restaurant på 1960-tallet'],
   c:1, why:'Konkurrerende restaurantbedrifter tok markedsføringspåstandene til Delhi High Court i 2024. Saken dokumenterer striden, men fastslår ikke en oppfinner.'},
  {q:'Hvorfor er maten som serveres i en langar, alltid vegetarisk?',
   a:['Sikhismen forbyr å spise kjøtt',
      'Grønnsaker var billigere for et kjøkken som metter tusener',
      'Slik at mennesker med ulik tro og ulike kostregler kan dele måltidet',
      'Fordi kjøkkenet ikke har noen måte å holde kjøtt kaldt på'],
   c:2, why:'Det felles vegetariske måltidet uttrykker inkludering og lar mennesker med ulik tro og ulike kostregler spise sammen.'}
 ]
];
