/* Masala Dabba — repetisjonsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme fasitindeks som den engelske filen. Spørsmålene leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-RAJ'] = [
 [
  {q:'Hvorfor lager et kjøkken i Rajasthan mat i fett og syrnet melk i stedet for i vann?',
   a:['Vannet måtte bæres og ble talt, så det ble ikke brukt til matlaging',
      'Fettet holdt fluene unna mat som ble stående i varmen',
      'Mogulhoffene innførte steking, og det ble værende',
      'Man trodde koking ødela krydderet'],
   c:0, why:'Rajasthan har 10,4 prosent av Indias areal, men rundt 1,15 prosent av overflatevannet. Mangelen fremmet metoder som bruker lite vann.'},
  {q:'Hva skal Mathania-chilien først og fremst gjøre i laal maas?',
   a:['Svi, og så sterkt som mulig',
      'Gi farge og en duft av tørket frukt',
      'Jevne sausen mens den koker inn',
      'Konservere kjøttet til dagen etter'],
   c:1, why:'Mathania-chili verdsettes for dyp farge og duft i tillegg til styrke. Styrken varierer, så kokken justerer antallet belger.'},
  {q:'Hvorfor piskes yoghurten sammen med en skje kikertmel før den møter pannen?',
   a:['For å gjøre den søt nok til å balansere chilien',
      'For at den skal syrne raskere over natten',
      'For at den ikke skal skille seg',
      'For å gi sausen den røde fargen'],
   c:2, why:'Glattpisket yoghurt, litt besan og rolig oppvarming bidrar til å stabilisere sausen. Retningen man rører i, spiller ingen rolle.'}
 ],
 [
  {q:'Hvorfor er bajra brødkornet i de vestlige distriktene?',
   a:['Den smaker bedre enn hvete når den stekes på glør',
      'Den modner på omtrent tre måneder og på svært lite regn',
      'Den holder seg lenger enn hvete etter at den er malt',
      'Den kom med handelsmenn og fortrengte den lokale hveten'],
   c:1, why:'Tidlige sorter av perlehirse modnes på rundt 65 til 90 dager og tåler varme og tørke bedre enn hvete.'},
  {q:'Hva er en bati, og hvorfor druknes den i ghee ved bordet?',
   a:['Et stekt brød, og gheen er bare for smakens skyld',
      'En dampet bolle, og gheen hindrer at den tørker ut',
      'En hirsepannekake, og gheen hindrer at den setter seg fast i pannen',
      'En hard, usyret kule bakt i glør, og gheen gjør den spiselig'],
   c:3, why:'Ingenting er tilsatt deigen for å heve den, så batien bakes tett, sprukken og tørr og holder seg i dagevis. Den smeltede gheen er det som retter opp tørrheten.'},
  {q:'Hva gjør mangodi, papad og badi på en hylle i Rajasthan?',
   a:['De er grønnsakretten, tørket måneder i forveien',
      'De er snacks som spises mellom måltidene',
      'De er jevning som røres i dalen til slutt',
      'De lages bare til bryllup og høytider'],
   c:0, why:'Tørking av belgfruktmasse, papad, bær og belger gjør sesongråvarer til hverdagsmat for senere måneder.'}
 ],
 [
  {q:'Hvordan vet kokken at laal maas er ferdig?',
   a:['Kjøttet faller av beinet',
      'Et lag rød ghee skiller seg ut og legger seg på overflaten',
      'Sausen går fra rød til brun',
      'Chilien slutter å dufte av frukt'],
   c:1, why:'Utskilt fett viser at yoghurtblandingen er kokt inn. Kjøttet må fortsatt prøves for å se om det er mørt.'},
  {q:'Hvorfor bløtlegges tørket ker og sangri før de kokes?',
   a:['For å skylle av saltet de ble lagret i',
      'For at de skal svelle og dermed rekke lenger',
      'For å mykne dem og trekke ut bitterheten',
      'For at de ikke skal farge sausen'],
   c:2, why:'Bløtlegging gir de tørkede råvarene vann igjen og bidrar til å dempe bitterheten. Tid og væske varierer mellom oppskrifter.'},
  {q:'Hva kan bli en del av sausen i gatte ki sabzi?',
   a:['Pisket yoghurt og ikke noe annet',
      'En pasta av stekt løk og hvitløk',
      'Tomat kokt inn med fløte',
      'Vannet som gatte ble kokt i'],
   c:3, why:'Noen kokker bruker litt av det stivelsesrike kokevannet sammen med yoghurt og besan. Andre begynner med friskt vann.'}
 ],
 [
  {q:'Hvorfor bør ikke rajputenes og marwariernes mat behandles som to ensartede kjøkken?',
   a:['Religion, kaste, sted og husholdningens valg skaper variasjon innenfor begge merkelapper',
      'Ingen av gruppene har bodd lenge i Rajasthan',
      'Begge merkelappene beskriver bare restaurantmat',
      'Oppskriftene deres ble helt forandret av kanalvanning'],
   c:0, why:'Rajputenes hoffmat rommer kjøttretter, mens marwari-identitet favner flere religioner og kosthold. Felles teknikker fjerner ikke variasjonen.'},
  {q:'Hvorfor betyr asafoetida mye i husholdninger som unngår løk og hvitløk?',
   a:['Den konserverer kokt mat gjennom de varme månedene',
      'Den er det eneste krydderet som vokser i ørkenen',
      'Den jevner en yoghurtsaus uten at den skiller seg',
      'Den gjør jobben til løk og hvitløk, som de ikke spiser'],
   c:3, why:'Streng jainistisk praksis utelater rotgrønnsaker, men graden av etterlevelse varierer. En klype hing i varmt fett gir maten en fyldig duft.'},
  {q:'Hva endret Indira Gandhi-kanalen i det nordvestlige Rajasthan?',
   a:['Den fjernet vannmangelen i hele delstaten',
      'Den muliggjorde vannede vekster i deler av ørkenen mens eldre retter beholdt sin verdi',
      'Den erstattet hver hirseåker med ris',
      'Den gjorde kjøtt vanlig i marwariske husholdninger'],
   c:1, why:'Kanalen muliggjorde hvete, sennep og andre vekster i deler av nordvest. Vann og mat endret seg ujevnt, mens eldre retter forble viktige.'}
 ]
];
