/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-RAJ'] = [
 [
  {q:'Why does a Rajasthani kitchen cook in fat and soured milk rather than in water?',
   a:['Water had to be carried and counted, so it was not spent on cooking',
      'Fat kept the flies off food left standing in the heat',
      'The Mughal courts introduced frying and it stayed',
      'Boiling was believed to destroy the spices'],
   c:0, why:'Rajasthan has 10.4 per cent of India’s area but about 1.15 per cent of its surface-water resources. Scarcity helped favour methods that use little water.'},
  {q:'What is the Mathania chilli mainly in laal maas to do?',
   a:['Burn, and as fiercely as possible',
      'Give colour and a dried-fruit smell',
      'Thicken the gravy as it cooks down',
      'Preserve the meat for the next day'],
   c:1, why:'Mathania chilli is prized for deep colour and aroma as well as pungency. Its heat varies, so the cook adjusts the number of pods.'},
  {q:'Why is yoghurt beaten with a spoonful of gram flour before it meets the pan?',
   a:['To sweeten it enough to balance the chilli',
      'To make it sour faster overnight',
      'To stop it splitting into curds and whey',
      'To give the gravy its red colour'],
   c:2, why:'Beating the yoghurt smooth, adding a little besan and heating it gently all help stabilise the gravy. The direction of stirring does not matter.'}
 ],
 [
  {q:'Why is bajra the bread grain of the western districts?',
   a:['It tastes better than wheat when cooked on embers',
      'It ripens in about three months on very little rain',
      'It keeps longer than wheat once it has been milled',
      'It was brought by traders and replaced the local wheat'],
   c:1, why:'Early pearl-millet cultivars mature in roughly 65 to 90 days and tolerate heat and drought better than wheat.'},
  {q:'What is a bati, and why is it drowned in ghee at the table?',
   a:['A fried bread, and the ghee is only for flavour',
      'A steamed dumpling, and the ghee stops it drying out',
      'A millet pancake, and the ghee keeps it off the pan',
      'A hard unleavened ball baked in embers, and the ghee makes it edible'],
   c:3, why:'Nothing goes into the dough to make it rise, so a bati bakes dense, cracked and dry and keeps for days. The melted ghee is what repairs the dryness.'},
  {q:'What are mangodi, papad and badi doing on a Rajasthani shelf?',
   a:['They are the vegetable course, dried months in advance',
      'They are snacks eaten between meals',
      'They are thickeners stirred into dal at the end',
      'They are made only for weddings and festivals'],
   c:0, why:'Drying pulse paste, papad, berries and pods during suitable weather turns seasonal ingredients into everyday food for later months.'}
 ],
 [
  {q:'How does a cook know that laal maas is finished?',
   a:['The meat falls away from the bone',
      'A slick of red ghee separates out and rises to the surface',
      'The gravy darkens from red to brown',
      'The chilli stops smelling of fruit'],
   c:1, why:'Separated fat shows that the yoghurt masala has reduced and cooked. The meat must still be checked for tenderness.'},
  {q:'Why are dried ker and sangri soaked before they are cooked?',
   a:['To wash off the salt they were stored in',
      'To make them swell so that they go further',
      'To soften them and draw the bitterness out',
      'To stop them colouring the gravy'],
   c:2, why:'Soaking rehydrates the dried ingredients and helps reduce bitterness. Recipes vary in soaking time and liquid.'},
  {q:'What may become part of the gravy in gatte ki sabzi?',
   a:['Beaten yoghurt and nothing else',
      'A paste of fried onion and garlic',
      'Tomato cooked down with cream',
      'The water the gatte were boiled in'],
   c:3, why:'Some cooks reuse part of the starchy cooking water, then add beaten yoghurt and besan; other versions begin with fresh water.'}
 ],
 [
  {q:'Why should Rajput and Marwari food not be treated as two uniform kitchens?',
   a:['Religion, caste, place and household choice create variation within both labels',
      'Neither group has lived in Rajasthan for very long',
      'Both labels describe only restaurant cooking',
      'Their recipes changed completely after canal irrigation'],
   c:0, why:'Rajput court food includes meat traditions, while Marwari identity spans religions and diets. Shared techniques do not erase variation within either group.'},
  {q:'Why does asafoetida matter in households that avoid onion and garlic?',
   a:['It preserves cooked food through the hot months',
      'It is the only spice that grows in the desert',
      'It thickens a yoghurt gravy without splitting it',
      'It does the work of onion and garlic, which they do not eat'],
   c:3, why:'Strict Jain practice excludes root vegetables, though observance varies. A pinch of hing bloomed in hot fat gives food a savoury aroma.'},
  {q:'What did the Indira Gandhi Canal change in north-west Rajasthan?',
   a:['It ended water scarcity everywhere in the state',
      'It enabled irrigated crops in parts of the desert while older dishes retained value',
      'It replaced every millet field with rice',
      'It made meat usual in Marwari households'],
   c:1, why:'The canal enabled wheat, mustard and other crops in parts of the north-west. Water access and cooking both changed unevenly, while older dishes remained culturally important.'}
 ]
];
