/* Masala Dabba — recap questions, English. Contract: docs/quiz-format.md, checked by tools/quizcheck.py.
   One array of four readings per region, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing a question cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-RAJ'] = [
 [
  {q:'Why does a Rajasthani kitchen cook in fat and soured milk rather than in water?',
   a:['Water had to be carried and counted, so it was not spent on cooking',
      'Fat kept the flies off food left standing in the heat',
      'The Mughal courts introduced frying and it stayed',
      'Boiling was believed to destroy the spices'],
   c:0, why:'Official figures give Rajasthan about a tenth of India’s land and close to one per cent of its surface water, so ghee, yoghurt and buttermilk took the place of a pot of water.'},
  {q:'What is the Mathania chilli mainly in laal maas to do?',
   a:['Burn, and as fiercely as possible',
      'Give colour and a dried-fruit smell',
      'Thicken the gravy as it cooks down',
      'Preserve the meat for the next day'],
   c:1, why:'The pods are deep red, thin-skinned and moderate in heat, and they go in a dozen at a time. The yoghurt and the ghee hold down whatever heat they carry.'},
  {q:'Why is yoghurt beaten with a spoonful of gram flour before it meets the pan?',
   a:['To sweeten it enough to balance the chilli',
      'To make it sour faster overnight',
      'To stop it splitting into curds and whey',
      'To give the gravy its red colour'],
   c:2, why:'Cold curd tipped into hot fat curdles at once. Beaten smooth, thickened with a little besan and stirred one way as it warms, it comes to a simmer glossy.'}
 ],
 [
  {q:'Why is bajra the bread grain of the western districts?',
   a:['It tastes better than wheat when cooked on embers',
      'It ripens in about three months on very little rain',
      'It keeps longer than wheat once it has been milled',
      'It was brought by traders and replaced the local wheat'],
   c:1, why:'Pearl millet germinates days after the first rain and sets seed in soil hot enough to kill a wheat seedling. No other cereal of consequence manages that.'},
  {q:'What is a bati, and why is it drowned in ghee at the table?',
   a:['A fried bread, and the ghee is only for flavour',
      'A steamed dumpling, and the ghee stops it drying out',
      'A millet pancake, and the ghee keeps it off the pan',
      'A hard unleavened ball baked in embers, and the ghee makes it edible'],
   c:3, why:'Nothing goes into the dough to make it rise, so a bati bakes dense, cracked and dry and keeps for days. The melted ghee is what repairs the dryness.'},
  {q:'What are mangodi, papad and badi doing on a Rajasthani shelf?',
   a:['They are the vegetable course, dried months in advance',
      'They are snacks eaten between meals',
      'They are thickeners stirred into dal at the end',
      'They are made only for weddings and festivals'],
   c:0, why:'Nothing green keeps in that climate, so vegetables are manufactured in the dry weeks before the monsoon. Papad ki sabzi is a main dish, not a garnish.'}
 ],
 [
  {q:'How does a cook know that laal maas is finished?',
   a:['The meat falls away from the bone',
      'A slick of red ghee separates out and rises to the surface',
      'The gravy darkens from red to brown',
      'The chilli stops smelling of fruit'],
   c:1, why:'There is enough ghee in the pot that the fat separates as the yoghurt reduces, and the red slick on top is a more reliable test than a clock.'},
  {q:'Why must ker and sangri be soaked overnight before they are cooked?',
   a:['To wash off the salt they were stored in',
      'To make them swell so that they go further',
      'To soften them and draw the bitterness out',
      'To stop them colouring the gravy'],
   c:2, why:'Ker is sharply bitter raw, and the bitterness leaves with the soaking water. A cook who skips the soaking gets a dish nobody will finish.'},
  {q:'What becomes the base of the gravy in gatte ki sabzi?',
   a:['Beaten yoghurt and nothing else',
      'A paste of fried onion and garlic',
      'Tomato cooked down with cream',
      'The water the gatte were boiled in'],
   c:3, why:'The boiling water carries flour and spice out of the dough, so it is kept and built up with beaten yoghurt and another spoon of besan.'}
 ],
 [
  {q:'What do the Rajput and the Marwari kitchens have in common?',
   a:['Both fry rather than boil, sour with curd and keep a shelf of dried pods',
      'Both avoid chilli and rely on whole spices instead',
      'Both build their gravies on fried onion',
      'Both eat goat, but only on festival days'],
   c:0, why:'The desert set the technique and the two communities disagree about the ingredients. One applies the method to goat, the other to gram flour.'},
  {q:'Why does asafoetida matter so much in Marwari and Jain households?',
   a:['It preserves cooked food through the hot months',
      'It is the only spice that grows in the desert',
      'It thickens a yoghurt gravy without splitting it',
      'It does the work of onion and garlic, which they do not eat'],
   c:3, why:'Strict practice avoids root vegetables, so onion and garlic are off the table. A pinch of hing bloomed in hot fat turns savoury and almost oniony.'},
  {q:'What happened to Rajasthani cooking once canal water reached the north-west?',
   a:['It largely disappeared within a generation',
      'It carried on almost unchanged',
      'It turned into a wheat-based cuisine',
      'Meat became usual in Marwari houses'],
   c:1, why:'Wheat and mustard now grow where bajra grew or nothing did, but households with a tap still fry their vegetables, still sour with curd and still keep sangri in a sack.'}
 ]
];
