/* Masala Dabba — repetisjonsspørsmål, norsk bokmål. Kontrakt: docs/quiz-format.md.
   Samme rekkefølge og samme fasitindeks som den engelske filen. Spørsmålene leses aldri inn. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-RAJ'] = [
 [
  {q:'Hvorfor lager et kjøkken i Rajasthan mat i fett og syrnet melk i stedet for i vann?',
   a:['Vannet måtte bæres og ble talt, så det ble ikke brukt til matlaging',
      'Fettet holdt fluene unna mat som ble stående i varmen',
      'Mogulhoffene innførte steking, og det ble værende',
      'Man trodde koking ødela krydderet'],
   c:0, why:'Offisielle tall gir Rajasthan omkring en tidel av Indias landareal og nær én prosent av overflatevannet, så ghee, yoghurt og kjernemelk overtok for gryta med vann.'},
  {q:'Hva skal Mathania-chilien først og fremst gjøre i laal maas?',
   a:['Svi, og så sterkt som mulig',
      'Gi farge og en duft av tørket frukt',
      'Jevne sausen mens den koker inn',
      'Konservere kjøttet til dagen etter'],
   c:1, why:'Belgene er dypt røde, tynnskallede og moderate i styrke, og de går i et dusin om gangen. Yoghurten og gheen demper det lille de bærer.'},
  {q:'Hvorfor piskes yoghurten sammen med en skje kikertmel før den møter pannen?',
   a:['For å gjøre den søt nok til å balansere chilien',
      'For at den skal syrne raskere over natten',
      'For at den ikke skal skille seg',
      'For å gi sausen den røde fargen'],
   c:2, why:'Kald yoghurt sluppet i varmt fett skiller seg med en gang. Pisket glatt, jevnet med litt besan og rørt én vei mens den varmes, kommer den blank opp til kokepunktet.'}
 ],
 [
  {q:'Hvorfor er bajra brødkornet i de vestlige distriktene?',
   a:['Den smaker bedre enn hvete når den stekes på glør',
      'Den modner på omtrent tre måneder og på svært lite regn',
      'Den holder seg lenger enn hvete etter at den er malt',
      'Den kom med handelsmenn og fortrengte den lokale hveten'],
   c:1, why:'Perlehirsen spirer noen dager etter det første regnet og setter frø i jord som er varm nok til å ta livet av en hveteplante. Ingen annen kornsort av betydning klarer det.'},
  {q:'Hva er en bati, og hvorfor druknes den i ghee ved bordet?',
   a:['Et stekt brød, og gheen er bare for smakens skyld',
      'En dampet bolle, og gheen hindrer at den tørker ut',
      'En hirsepannekake, og gheen hindrer at den setter seg fast i pannen',
      'En hard, usyret kule bakt i glør, og gheen gjør den spiselig'],
   c:3, why:'Ingenting er tilsatt deigen for å heve den, så batien bakes tett, sprukken og tørr og holder seg i dagevis. Den smeltede gheen er det som retter opp tørrheten.'},
  {q:'Hva gjør mangodi, papad og badi på en hylle i Rajasthan?',
   a:['De er grønnsakretten, tørket måneder i forveien',
      'De er snacks som spises mellom måltidene',
      'De er jevning som røres i dalen til slutt',
      'De lages bare til bryllup og høytider'],
   c:0, why:'Ingenting grønt holder seg i det klimaet, så grønnsakene lages i de tørre ukene før monsunen. Papad ki sabzi er en hovedrett og ingen pynt.'}
 ],
 [
  {q:'Hvordan vet kokken at laal maas er ferdig?',
   a:['Kjøttet faller av beinet',
      'Et lag rød ghee skiller seg ut og legger seg på overflaten',
      'Sausen går fra rød til brun',
      'Chilien slutter å dufte av frukt'],
   c:1, why:'Det er så mye ghee i gryta at fettet skiller seg ut når yoghurten koker inn, og det røde laget på toppen er en sikrere prøve enn en klokke.'},
  {q:'Hvorfor må ker og sangri bløtlegges over natten før de kokes?',
   a:['For å skylle av saltet de ble lagret i',
      'For at de skal svelle og dermed rekke lenger',
      'For å mykne dem og trekke ut bitterheten',
      'For at de ikke skal farge sausen'],
   c:2, why:'Ker er skarpt bittert rått, og bitterheten går ut med bløtevannet. Den som hopper over bløtleggingen, får en rett ingen spiser opp.'},
  {q:'Hva blir grunnlaget for sausen i gatte ki sabzi?',
   a:['Pisket yoghurt og ikke noe annet',
      'En pasta av stekt løk og hvitløk',
      'Tomat kokt inn med fløte',
      'Vannet som gatte ble kokt i'],
   c:3, why:'Kokevannet bærer med seg mel og krydder ut av deigen, så det tas vare på og bygges opp med pisket yoghurt og enda en skje besan.'}
 ],
 [
  {q:'Hva har rajputenes og marwariernes kjøkken felles?',
   a:['Begge steker i stedet for å koke, syrner med yoghurt og har en hylle med tørkede belger',
      'Begge unngår chili og bruker hele krydder i stedet',
      'Begge bygger sausene sine på stekt løk',
      'Begge spiser geit, men bare på høytidsdager'],
   c:0, why:'Ørkenen bestemte teknikken, og de to samfunnene er uenige om ingrediensene. Det ene bruker metoden på geitekjøtt, det andre på kikertmel.'},
  {q:'Hvorfor betyr asafoetida så mye i marwariske og jainske husholdninger?',
   a:['Den konserverer kokt mat gjennom de varme månedene',
      'Den er det eneste krydderet som vokser i ørkenen',
      'Den jevner en yoghurtsaus uten at den skiller seg',
      'Den gjør jobben til løk og hvitløk, som de ikke spiser'],
   c:3, why:'Streng praksis unngår rotgrønnsaker, så løk og hvitløk er ute. En klype hing varmet i fett blir smaksrik og nesten løkaktig.'},
  {q:'Hva skjedde med matlagingen i Rajasthan da kanalvannet nådde nordvest?',
   a:['Den forsvant stort sett i løpet av en generasjon',
      'Den fortsatte nesten uendret',
      'Den ble et hvetebasert kjøkken',
      'Kjøtt ble vanlig i marwariske hjem'],
   c:1, why:'Det vokser nå hvete og sennep på jord som bar bajra eller ingenting, men husholdninger med vann i springen steker fortsatt grønnsakene, syrner med yoghurt og har sangri i en sekk.'}
 ]
];
