/* Masala Dabba — recap questions for Tamil Nadu (IN-TAM), English. Contract: docs/quiz-format.md,
   checked by tools/quizcheck.py. Four readings, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing one cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-TAM'] = [
 [
  {q:'Why is the Tamil word for chilli built out of the word for pepper?',
   a:['Chilli was first grown up the same vines as pepper',
      'Chilli arrived long after pepper and was named against it',
      'The two are ground together in the everyday blend',
      'The Portuguese used their own word for both'],
   c:1, why:'Pepper is milagu and chilli is milagai. The new fruit reached the coast in the sixteenth century, and the obvious way to name it was as a kind of pepper.'},
  {q:'What is kalpasi?',
   a:['The dried flower bud of a forest tree',
      'A bark, related to cassia',
      'A lichen that grows on bark and rock in the southern hills',
      'A powder of roasted lentils and chilli'],
   c:2, why:'It is Parmotrema perlatum, sold dried as black stone flower, and it belongs to the same family as the oakmoss used in perfumery.'},
  {q:'What marks sambar podi out from a north Indian garam masala?',
   a:['Roasted lentils are ground into it, and it carries no warm sweet spices',
      'It is ground much finer and used in larger quantity',
      'It is made with fresh green chilli rather than dried red',
      'It contains no coriander seed at all'],
   c:0, why:'Toor dal and chana dal are roasted and ground in with the spices, so the powder thickens as well as seasons, and cinnamon, clove and cardamom are absent.'}
 ],
 [
  {q:'What does the urad dal bring to the breakfast batter that the rice does not?',
   a:['The starch that sets into a crumb when the batter is steamed',
      'Both the wild bacteria and a protein that traps gas',
      'The sourness, which comes from a spoon of yoghurt',
      'The salt, which is carried on the skin of the lentil'],
   c:1, why:'Urad carries Leuconostoc and Lactobacillus on its skin, and it also carries a protein and a sticky polysaccharide that hold gas the way egg white does.'},
  {q:'Why is the rice for idli parboiled?',
   a:['So that it can be ground without being soaked first',
      'Because it kills the wild bacteria, so baker’s yeast can be used instead',
      'Steaming rearranges the starch, so the grain takes up water without turning gluey',
      'Because the red colour is what an idli is supposed to have'],
   c:2, why:'A parboiled batter steams into a crumb that is soft and open, where raw rice gives something denser and slightly rubbery.'},
  {q:'Why does the same pot of batter become dosa on the second morning?',
   a:['A second grinding thins it down',
      'Fenugreek is stirred in on the second day',
      'A pinch of yeast is added to lift it again',
      'It has soured and slackened, so it spreads thinner and browns faster'],
   c:3, why:'Nothing is done to the batter at all. The acid builds as it stands, and a slacker, more acid batter is exactly what a griddle wants.'}
 ],
 [
  {q:'How do sambar and rasam differ?',
   a:['Rasam is sambar that has been cooked down further',
      'Sambar is soured with tamarind and rasam is not',
      'Sambar is a thick dal stew and rasam a thin peppery broth',
      'Sambar is eaten in the morning and rasam in the evening'],
   c:2, why:'Both are soured with tamarind, but sambar is built on toor dal and vegetables while rasam is mostly water, pepper and cumin, and half of it is drunk.'},
  {q:'What goes into milagu rasam?',
   a:['Chilli, tomato and a great deal of coriander',
      'Pepper, cumin, garlic and tamarind, and no chilli at all',
      'Pepper and thin coconut milk, with no souring agent',
      'Fennel, star anise and kalpasi, as in the Chettinad blend'],
   c:1, why:'It is the plainest and oldest version of rasam, made for someone with a cold, and it is the clearest example of pepper doing a job chilli never took over.'},
  {q:'Why is rasam taken off the heat as soon as it froths at the edges?',
   a:['Boiling it hard dulls the pepper and drives off the fresh coriander',
      'The dal would break up and cloud the broth',
      'It would reduce below the volume a full leaf needs',
      'The tamarind turns bitter above a simmer'],
   c:0, why:'Rasam is judged on how fresh the pepper and the coriander smell, and both are lost within a minute of a hard boil.'}
 ],
 [
  {q:'What do the deliberate chisel cuts on Roman coins found in the far south suggest?',
   a:['That local rulers were cancelling foreign currency',
      'That the gold was being handled by weight rather than spent as money',
      'That the coins were being prepared for use as jewellery',
      'That they were defaced for religious reasons'],
   c:1, why:'Hoards in Pudukottai, Karur and around Coimbatore are dense and often cut, which points to bullion changing hands rather than a currency circulating.'},
  {q:'How did the Nattukottai Chettiars make the money that built the Chettinad mansions?',
   a:['Pepper plantations on the slopes of the Western Ghats',
      'Endowments and land granted by the Chola temples',
      'Banking and credit in Burma, Ceylon, Malaya and Indochina',
      'Weaving and the export of cloth from Madras'],
   c:2, why:'Their own district grows very little, so from the early nineteenth century the business was credit, run through a network of small counting houses abroad.'},
  {q:'Why is star anise in a Chettinad masala historically interesting?',
   a:['It is the only anise native to southern India',
      'The Portuguese brought it along with the chilli',
      'It was grown in the Kaveri delta until the nineteenth century',
      'The tree is not grown in India at all, so it can only have arrived by trade'],
   c:3, why:'Illicium verum grows in southern China and northern Vietnam, and Chettinad is effectively the only Indian regional kitchen that uses it as a matter of routine.'}
 ]
];
