/* Masala Dabba — oppsummeringsspørsmål for Tamil Nadu (IN-TAM), norsk bokmål.
   Kontrakt: docs/quiz-format.md. Samme rekkefølge og samme fasitindeks som den engelske filen.
   Spørsmålene leses aldri inn, så en endring her kan ikke gjøre en lydfil utdatert. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-TAM'] = [
 [
  {q:'Hvorfor er det tamilske ordet for chili bygd av ordet for pepper?',
   a:['Chilien ble først dyrket opp langs de samme rankene som pepperen',
      'Chilien kom lenge etter pepperen og ble navngitt mot den',
      'De to males sammen i hverdagsblandingen',
      'Portugiserne brukte sitt eget ord om begge deler'],
   c:1, why:'Pepper heter milagu og chili milagai. Den nye frukten nådde kysten på 1500-tallet, og det mest nærliggende var å navngi den som en slags pepper.'},
  {q:'Hva er kalpasi?',
   a:['Den tørkede blomsterknoppen til et skogstre',
      'En bark i slekt med kassia',
      'En lav som vokser på bark og stein i åsene i sør',
      'Et pulver av ristede linser og chili'],
   c:2, why:'Kalpasi er Parmotrema perlatum, som selges tørket som steinblomst, og den hører til samme familie som eikemosen parfymørene bruker.'},
  {q:'Hva skiller sambar podi fra en nordindisk garam masala?',
   a:['Ristede linser males inn i den, og den har ingen varme søte krydder',
      'Den males mye finere og brukes i større mengder',
      'Den lages med fersk grønn chili i stedet for tørket rød',
      'Den inneholder ikke korianderfrø i det hele tatt'],
   c:0, why:'Toor dal og chana dal ristes og males inn sammen med krydderet, så pulveret både jevner og smaker, og kanel, nellik og kardemomme mangler helt.'}
 ],
 [
  {q:'Hva bidrar urad dal med i frokostrøren som risen ikke gir?',
   a:['Stivelsen som setter seg til en smule når røren dampes',
      'Både de ville bakteriene og et protein som fanger gass',
      'Syrligheten, som kommer fra en skje yoghurt',
      'Saltet, som sitter på skallet av linsen'],
   c:1, why:'Urad har Leuconostoc og Lactobacillus på skallet, og den har i tillegg et protein og et seigt polysakkarid som holder på gass slik eggehvite gjør.'},
  {q:'Hvorfor er risen til idli forkokt?',
   a:['Slik at den kan males uten å bløtlegges først',
      'Fordi forkokingen dreper de ville bakteriene, så gjær kan brukes i stedet',
      'Dampingen ordner stivelsen på nytt, så kornet tar opp vann uten å bli klissete',
      'Fordi den røde fargen er den en idli skal ha'],
   c:2, why:'En forkokt røre damper seg til en myk og åpen smule, mens rå ris gir en idli som er tettere og litt gummiaktig.'},
  {q:'Hvorfor blir den samme gryta med røre til dosa den andre morgenen?',
   a:['En ny maling tynner den ut',
      'Bukkehornkløver røres inn dag to',
      'En klype gjær tilsettes for å heve den igjen',
      'Den har surnet og blitt slappere, så den brer seg tynnere og bruner raskere'],
   c:3, why:'Ingen gjør noe med røren. Syren bygger seg opp mens den står, og en slappere og surere røre er nettopp det takka vil ha.'}
 ],
 [
  {q:'Hva skiller sambar fra rasam?',
   a:['Rasam er sambar som har kokt lenger inn',
      'Sambar syrnes med tamarind og rasam gjør det ikke',
      'Sambar er en tykk dal-gryte og rasam en tynn, pepret kraft',
      'Sambar spises om morgenen og rasam om kvelden'],
   c:2, why:'Begge syrnes med tamarind, men sambaren bygger på toor dal og grønnsaker, mens rasamen stort sett er vann, pepper og spisskummen, og halvparten drikkes.'},
  {q:'Hva går i en milagu rasam?',
   a:['Chili, tomat og svært mye koriander',
      'Pepper, spisskummen, hvitløk og tamarind, og ingen chili',
      'Pepper og tynn kokosmelk, uten noe syrningsmiddel',
      'Fennikel, stjerneanis og kalpasi, som i Chettinad-blandingen'],
   c:1, why:'Dette er den enkleste og eldste utgaven av rasam, laget til noen som er forkjølet, og den viser tydeligst at pepperen har en oppgave chilien aldri overtok.'},
  {q:'Hvorfor tas rasamen av platen så snart den skummer langs kanten?',
   a:['Hard koking sløver pepperen og driver bort den friske korianderen',
      'Dalen ville gått i oppløsning og gjort kraften uklar',
      'Den ville kokt inn under den mengden et fullt blad trenger',
      'Tamarinden blir bitter av alt mer enn småkoking'],
   c:0, why:'En rasam bedømmes på hvor friskt pepperen og korianderen lukter, og begge deler er borte innen et minutt med hard koking.'}
 ],
 [
  {q:'Hva tyder de bevisste kuttene i romerske mynter lengst sør på?',
   a:['At lokale herskere satte fremmed mynt ut av kraft',
      'At gullet ble håndtert etter vekt og ikke brukt som penger',
      'At myntene ble klargjort for bruk som smykker',
      'At de ble vansiret av religiøse grunner'],
   c:1, why:'Funnene i Pudukottai, Karur og rundt Coimbatore er tette og ofte kuttet, og det peker mot gull som skiftet hender etter vekt heller enn en mynt i omløp.'},
  {q:'Hvordan tjente nattukottai-chettiarene pengene som bygde herskapshusene i Chettinad?',
   a:['Pepperplantasjer på skråningene av Vestghatene',
      'Gaver og jord fra cholatemplene',
      'Bankvirksomhet og kreditt i Burma, Ceylon, Malaya og Indokina',
      'Veving og eksport av tøy fra Madras'],
   c:2, why:'Deres eget distrikt gir svært lite, så fra tidlig på 1800-tallet var forretningen kreditt, drevet gjennom et nett av små kontorer i utlandet.'},
  {q:'Hvorfor er stjerneanisen i en Chettinad-masala historisk interessant?',
   a:['Den er den eneste anisen som hører hjemme i Sør-India',
      'Portugiserne brakte den hit sammen med chilien',
      'Den ble dyrket i Kaveri-deltaet fram til 1800-tallet',
      'Treet dyrkes ikke i India i det hele tatt, så den kan bare ha kommet med handel'],
   c:3, why:'Illicium verum vokser i Sør-Kina og Nord-Vietnam, og Chettinad er i praksis det eneste indiske regionkjøkkenet som bruker den rutinemessig.'}
 ]
];
