/* Masala Dabba — recap questions for Tamil Nadu (IN-TAM), English. Contract: docs/quiz-format.md,
   checked by tools/quizcheck.py. Four readings, three questions each. Questions are NEVER narrated:
   narrate.py only ever sees a reading's html, so editing one cannot make audio stale. */
window.QUIZ = window.QUIZ || {};
window.QUIZ['IN-TAM'] = [
 [
  {q:'Why is the Tamil word for chilli built out of the word for pepper?',
   a:['Chilli was first grown up the same vines as pepper',
      'Chilli arrived long after pepper and was named against it',
      'The two are ground together in the everyday blend',
      'The Portuguese used their own word for both'],
   c:1, why:'Pepper is milagu and chilli is milagai. The new fruit reached the coast in the sixteenth century, and the obvious way to name it was as a kind of pepper.'},
  {q:'What is kalpasi?',
   a:['The dried flower bud of a forest tree',
      'A bark, related to cassia',
      'A lichen that grows on bark and rock in the southern hills',
      'A powder of roasted lentils and chilli'],
   c:2, why:'It is Parmotrema perlatum, sold dried as black stone flower, and it belongs to the same family as the oakmoss used in perfumery.'},
  {q:'Which addition appears in some sambar podi formulas and can help thicken the stew?',
   a:['Roasted lentils ground into the blend',
      'It is ground much finer and used in larger quantity',
      'It is made with fresh green chilli rather than dried red',
      'It contains no coriander seed at all'],
   c:0, why:'Sambar podi formulas vary. Some include roasted toor dal or chana dal, which adds body as well as flavour; the blend is made for sambar rather than used like garam masala.'}
 ],
 [
  {q:'What structural role does urad dal play in the breakfast batter?',
   a:['The starch that sets into a crumb when the batter is steamed',
      'Proteins and polysaccharides that help the batter trap gas',
      'The sourness, which comes from a spoon of yoghurt',
      'The salt, which is carried on the skin of the lentil'],
   c:1, why:'The fermentation involves bacteria and yeasts from several sources. Ground urad contributes the light, gas-holding structure that makes the steamed cakes airy.'},
  {q:'Why is the rice for idli parboiled?',
   a:['So that it can be ground without being soaked first',
      'Because it kills the wild bacteria, so baker’s yeast can be used instead',
      'Steaming rearranges the starch, so the grain takes up water without turning gluey',
      'Because the red colour is what an idli is supposed to have'],
   c:2, why:'Parboiling changes the rice starch and water absorption. It is a common idli choice, although recipes also use other rice and grain preparations.'},
  {q:'Why can refrigerated leftover idli batter work well for dosa?',
   a:['A second grinding thins it down',
      'Fenugreek is stirred in on the second day',
      'A pinch of yeast is added to lift it again',
      'It has soured and slackened, so it spreads thinner and browns faster'],
   c:3, why:'During refrigerated storage the batter can become more acidic and its texture changes. Thin it as needed and judge it by its clean smell and consistency, not a fixed day number.'}
 ],
 [
  {q:'How do sambar and rasam differ?',
   a:['Rasam is sambar that has been cooked down further',
      'Sambar is soured with tamarind and rasam is not',
      'Sambar is a thick dal stew and rasam a thin peppery broth',
      'Sambar is eaten in the morning and rasam in the evening'],
   c:2, why:'Both are soured with tamarind, but sambar is built on toor dal and vegetables while rasam is mostly water, pepper and cumin, and half of it is drunk.'},
  {q:'What goes into milagu rasam?',
   a:['Chilli, tomato and a great deal of coriander',
      'Pepper, cumin, garlic and tamarind, and no chilli at all',
      'Pepper and thin coconut milk, with no souring agent',
      'Fennel, star anise and kalpasi, as in the Chettinad blend'],
   c:1, why:'Milagu rasam is a pepper-and-cumin variation often served as comfort food during a cold. It is food rather than a medical treatment.'},
  {q:'Why is rasam taken off the heat as soon as it froths at the edges?',
   a:['Boiling it hard dulls the pepper and drives off the fresh coriander',
      'The dal would break up and cloud the broth',
      'It would reduce below the volume a full leaf needs',
      'The tamarind turns bitter above a simmer'],
   c:0, why:'Rasam is judged on how fresh the pepper and the coriander smell, and both are lost within a minute of a hard boil.'}
 ],
 [
  {q:'What can historians safely conclude from cuts and marks on some Roman coins found in the far south?',
   a:['That local rulers were cancelling foreign currency',
      'That the coins were altered locally, while the precise reason remains debated',
      'That the coins were being prepared for use as jewellery',
      'That they were defaced for religious reasons'],
   c:1, why:'The altered coins document local handling, but weighing as metal, testing, reuse and other practices have all been proposed. The cuts alone do not settle the question.'},
  {q:'How did the Nattukottai Chettiars make the money that built the Chettinad mansions?',
   a:['Pepper plantations on the slopes of the Western Ghats',
      'Endowments and land granted by the Chola temples',
      'Banking and credit in Burma, Ceylon, Malaya and Indochina',
      'Weaving and the export of cloth from Madras'],
   c:2, why:'Their own district grows very little, so from the early nineteenth century the business was credit, run through a network of small counting houses abroad.'},
  {q:'Why is star anise in a Chettinad masala historically interesting?',
   a:['It is the only anise native to southern India',
      'The Portuguese brought it along with the chilli',
      'It was grown in the Kaveri delta until the nineteenth century',
      'The spice is native farther east and reached India through trade, though its exact Chettinad route is undocumented'],
   c:3, why:'Star anise is native to southern China and northern Vietnam and is used in several Indian cuisines. Chettiar trade offers context, but does not prove one precise route into the masala.'}
 ]
];
