/* Masala Dabba — oppsummeringsspørsmål for Tamil Nadu (IN-TAM), norsk bokmål.
   Kontrakt: docs/quiz-format.md. Samme rekkefølge og samme fasitindeks som den engelske filen.
   Spørsmålene leses aldri inn, så en endring her kan ikke gjøre en lydfil utdatert. */
window.QUIZ_NO = window.QUIZ_NO || {};
window.QUIZ_NO['IN-TAM'] = [
 [
  {q:'Hvorfor er det tamilske ordet for chili bygd av ordet for pepper?',
   a:['Chilien ble først dyrket opp langs de samme rankene som pepperen',
      'Chilien kom lenge etter pepperen og ble navngitt mot den',
      'De to males sammen i hverdagsblandingen',
      'Portugiserne brukte sitt eget ord om begge deler'],
   c:1, why:'Pepper heter milagu og chili milagai. Den nye frukten nådde kysten på 1500-tallet, og det mest nærliggende var å navngi den som en slags pepper.'},
  {q:'Hva er kalpasi?',
   a:['Den tørkede blomsterknoppen til et skogstre',
      'En bark i slekt med kassia',
      'En lav som vokser på bark og stein i åsene i sør',
      'Et pulver av ristede linser og chili'],
   c:2, why:'Kalpasi er Parmotrema perlatum, som selges tørket som steinblomst, og den hører til samme familie som eikemosen parfymørene bruker.'},
  {q:'Hvilket tillegg finnes i noen sambar podi-oppskrifter og kan bidra til å jevne gryta?',
   a:['Ristede linser malt inn i blandingen',
      'Den males mye finere og brukes i større mengder',
      'Den lages med fersk grønn chili i stedet for tørket rød',
      'Den inneholder ikke korianderfrø i det hele tatt'],
   c:0, why:'Sambar podi-oppskrifter varierer. Noen har ristet toor dal eller chana dal, som gir både fylde og smak; blandingen er laget for sambar og brukes ikke som garam masala.'}
 ],
 [
  {q:'Hvilken strukturell rolle har urad dal i frokostrøren?',
   a:['Stivelsen som setter seg til en smule når røren dampes',
      'Proteiner og polysakkarider som hjelper røren å holde på gass',
      'Syrligheten, som kommer fra en skje yoghurt',
      'Saltet, som sitter på skallet av linsen'],
   c:1, why:'Gjæringen involverer bakterier og gjær fra flere kilder. Malt urad gir den luftige, gassholdende strukturen som gjør de dampede kakene lette.'},
  {q:'Hvorfor er risen til idli forkokt?',
   a:['Slik at den kan males uten å bløtlegges først',
      'Fordi forkokingen dreper de ville bakteriene, så gjær kan brukes i stedet',
      'Dampingen ordner stivelsen på nytt, så kornet tar opp vann uten å bli klissete',
      'Fordi den røde fargen er den en idli skal ha'],
   c:2, why:'Forkokingen endrer risstivelsen og vannopptaket. Forkokt ris er et vanlig idli-valg, men oppskrifter bruker også andre ris- og kornbehandlinger.'},
  {q:'Hvorfor kan kjølt rest av idlirøre passe godt til dosa?',
   a:['En ny maling tynner den ut',
      'Bukkehornkløver røres inn dag to',
      'En klype gjær tilsettes for å heve den igjen',
      'Den har surnet og blitt slappere, så den brer seg tynnere og bruner raskere'],
   c:3, why:'Under kjølt lagring kan røren bli syrligere og endre konsistens. Spe den etter behov, og vurder ren lukt og konsistens i stedet for et fast dagnummer.'}
 ],
 [
  {q:'Hva skiller sambar fra rasam?',
   a:['Rasam er sambar som har kokt lenger inn',
      'Sambar syrnes med tamarind og rasam gjør det ikke',
      'Sambar er en tykk dal-gryte og rasam en tynn, pepret kraft',
      'Sambar spises om morgenen og rasam om kvelden'],
   c:2, why:'Begge syrnes med tamarind, men sambaren bygger på toor dal og grønnsaker, mens rasamen stort sett er vann, pepper og spisskummen, og halvparten drikkes.'},
  {q:'Hva går i en milagu rasam?',
   a:['Chili, tomat og svært mye koriander',
      'Pepper, spisskummen, hvitløk og tamarind, og ingen chili',
      'Pepper og tynn kokosmelk, uten noe syrningsmiddel',
      'Fennikel, stjerneanis og kalpasi, som i Chettinad-blandingen'],
   c:1, why:'Milagu rasam er en variant med pepper og spisskummen som ofte serveres som trøstemat ved forkjølelse. Den er mat og ikke medisinsk behandling.'},
  {q:'Hvorfor tas rasamen av platen så snart den skummer langs kanten?',
   a:['Hard koking sløver pepperen og driver bort den friske korianderen',
      'Dalen ville gått i oppløsning og gjort kraften uklar',
      'Den ville kokt inn under den mengden et fullt blad trenger',
      'Tamarinden blir bitter av alt mer enn småkoking'],
   c:0, why:'En rasam bedømmes på hvor friskt pepperen og korianderen lukter, og begge deler er borte innen et minutt med hard koking.'}
 ],
 [
  {q:'Hva kan historikere trygt slutte av kutt og merker på enkelte romerske mynter lengst sør?',
   a:['At lokale herskere satte fremmed mynt ut av kraft',
      'At myntene ble endret lokalt, mens den nøyaktige grunnen er omdiskutert',
      'At myntene ble klargjort for bruk som smykker',
      'At de ble vansiret av religiøse grunner'],
   c:1, why:'De endrede myntene dokumenterer lokal håndtering, men veiing som metall, testing, gjenbruk og andre praksiser er foreslått. Kuttene alene avgjør ikke spørsmålet.'},
  {q:'Hvordan tjente nattukottai-chettiarene pengene som bygde herskapshusene i Chettinad?',
   a:['Pepperplantasjer på skråningene av Vestghatene',
      'Gaver og jord fra cholatemplene',
      'Bankvirksomhet og kreditt i Burma, Ceylon, Malaya og Indokina',
      'Veving og eksport av tøy fra Madras'],
   c:2, why:'Deres eget distrikt gir svært lite, så fra tidlig på 1800-tallet var forretningen kreditt, drevet gjennom et nett av små kontorer i utlandet.'},
  {q:'Hvorfor er stjerneanisen i en Chettinad-masala historisk interessant?',
   a:['Den er den eneste anisen som hører hjemme i Sør-India',
      'Portugiserne brakte den hit sammen med chilien',
      'Den ble dyrket i Kaveri-deltaet fram til 1800-tallet',
      'Krydderet har opphav lenger øst og nådde India gjennom handel, men den nøyaktige veien til Chettinad er ukjent'],
   c:3, why:'Stjerneanis har opphav i Sør-Kina og Nord-Vietnam og brukes i flere indiske kjøkken. Chettiarhandelen gir bakgrunn, men beviser ikke én bestemt vei inn i masalaen.'}
 ]
];
