// SNAPSHOT, NOT SOURCE. This is the COURSE object as it was injected by tools/_port.py.
// masala-dabba.html is the source of truth and has diverged since. Kept only as the record
// of the port; editing this file changes nothing.
// ============================================================ COURSE SUMMARIES (one entry per region)
// Fourteen culinary regions, each a union of whole states (course.json says which). The four
// lesson titles per region follow one rhythm, which the kickers and every content format encode:
//   1 the spice logic   2 the staple and the table   3 the dishes   4 the place and its history
// spices[] is [name, kind]: whole | ground | blend | fresh | souring. dishes[] is [name, veg].
const COURSE = {
 'IN-HIM':{name:'Kashmir & the Himalaya', capital:'Srinagar', area:'North', color:'#8fa7b8', intro:"Saffron grows on the Pampore plateau, the rice is short and sticky, and the two great kitchens of the valley disagree about onions. Above them the Himalaya climbs into Ladakh, where butter tea and barley take over from rice and chilli.",
   landmark:{name:'Dal Lake and the Mughal gardens', desc:'Shikara boats on a lake the Mughals came north to escape the heat, terraced by the gardens Jahangir laid out at Shalimar in 1619.', props:[['dal',34.12,74.86]]},
   spices:[['Saffron (kong)','whole'],['Kashmiri chilli','ground'],['Ver masala','blend'],['Fennel (saunf)','whole'],['Dry ginger (sonth)','ground'],['Praan (shallot)','fresh']],
   plate:'Rice, a bowl of rogan josh, haak greens beside it, and kahwa afterwards with a shaved almond floating in the cup.',
   dishes:[['Rogan josh',0],['Yakhni',0],['Dum aloo',1],['Haak',1],['Modur pulav',1],['Tabak maaz',0],['Kahwa',1],['Nadru yakhni',1]],
   lessons:['Saffron, ver and the chilli that colours','Rice, the wazwan and the seventh course','Rogan josh, yakhni and the two valley kitchens','Mughals in the mountains: why the valley eats as it does']},
 'IN-PUN':{name:'Punjab & Delhi', capital:'Amritsar', area:'North', color:'#c9a94e', intro:"Five rivers, wheat instead of rice, and a clay oven that changed how the world thinks Indian food tastes. Delhi sits at the eastern end of the same plain and cooks what Partition brought it.",
   landmark:{name:'The Golden Temple, Amritsar', desc:'Gilded and standing in its own tank since 1604. Its langar feeds about a hundred thousand people a day, free, in the largest continuously running kitchen on earth.',props:[['harmandir',31.62,74.88]]},
   spices:[['Garam masala','blend'],['Cumin (jeera)','whole'],['Coriander seed','whole'],['Ajwain','whole'],['Kasuri methi','fresh'],['Amchur','souring']],
   plate:'Sarson da saag with a makki roti, a lump of white butter melting into it, and a glass of salted lassi.',
   dishes:[['Sarson da saag',1],['Makki di roti',1],['Butter chicken',0],['Tandoori chicken',0],['Dal makhani',1],['Rajma-chawal',1],['Chole bhature',1],['Amritsari fish',0],['Lassi',1]],
   lessons:['Garam masala and the tandoor','Wheat, dairy and the Punjabi plate','Saag, dal makhani and the tandoori table','1947: the refugee kitchens that invented butter chicken']},
 'IN-RAJ':{name:'Rajasthan', capital:'Jaipur', area:'North', color:'#d4a06a', intro:"A kitchen built where water was the scarce thing and ghee was not. Meat is cooked in yoghurt and chilli, vegetables are dried beans and berries gathered off desert scrub, and the bread is millet.",
   landmark:{name:'Mehrangarh, Jodhpur', desc:'A fort on a 120 m cliff above the blue city, begun in 1459 and never taken. Its kitchens fed a garrison that could not count on rain.',props:[['mehrangarh',26.30,73.02]]},
   spices:[['Mathania chilli','ground'],['Coriander (dhania)','ground'],['Asafoetida (hing)','ground'],['Kachri','souring'],['Clove','whole'],['Panchkuta','blend']],
   plate:'Dal, bati broken open and drowned in ghee, churma on the side, and laal maas if the house eats meat.',
   dishes:[['Laal maas',0],['Ker sangri',1],['Gatte ki sabzi',1],['Dal bati churma',1],['Pyaaz kachori',1],['Bajre ki roti',1],['Ghevar',1],['Mawa kachori',1]],
   lessons:['Cooking without water: chilli, ghee and yoghurt','Bajra, bati and the desert pantry','Laal maas, ker sangri and gatte','Rajputs and Marwaris: two kitchens, one desert']},
 'IN-AWA':{name:'Awadh', capital:'Lucknow', area:'North', color:'#bfae67', intro:"The most perfumed cooking in India, and the quietest. Awadhi cooks work with rose, screwpine and saffron rather than chilli, seal the pot with dough, and let the fire do almost nothing for three hours.",
   landmark:{name:'Bara Imambara, Lucknow', desc:'Built in 1784 as famine relief: the Nawab paid the city to build by day and, so the story goes, to unbuild by night. Its central hall is roofed without a single pillar.',props:[['imambara',26.87,80.91]]},
   spices:[['Kewra (screwpine)','fresh'],['Rose water','fresh'],['Mace (javitri)','whole'],['Green cardamom','whole'],['Saffron','whole'],['Potli masala','blend']],
   plate:'Galouti kebabs on a warm sheermal, a squeeze of lime, and biryani brought out only when the seal is broken at the table.',
   dishes:[['Galouti kebab',0],['Awadhi biryani',0],['Nihari',0],['Kakori kebab',0],['Sheermal',1],['Shahi tukda',1],['Banarasi chaat',1],['Malai makhan',1]],
   lessons:['Attar and aroma: the perfumed pantry','Dum: rice, bread and the sealed pot','Kebabs, biryani and nihari','The Nawabs, 1856, and where the cooks went']},
 'IN-GUJ':{name:'Gujarat', capital:'Ahmedabad', area:'West', color:'#cbbe6e', intro:"Sweet, sour and hot in the same mouthful, mostly without meat, and served all at once on a steel thali. Gujarat has traded across the Arabian Sea for four thousand years, and its kitchen shows the appetite of merchants.",
   landmark:{name:'Rani ki Vav, Patan', desc:'A stepwell cut seven storeys down in the 1060s, walled with a thousand sculptures. Water was worth this much.',props:[['stepwell',23.86,72.10]]},
   spices:[['Dhana-jeera','blend'],['Mustard seed','whole'],['Asafoetida (hing)','ground'],['Sesame (til)','whole'],['Jaggery (gud)','fresh'],['Kokum','souring']],
   plate:'A thali: two vegetables, dal, kadhi, rotli, rice, a pickle, and something fried that arrives last and hot.',
   dishes:[['Dhokla',1],['Undhiyu',1],['Khandvi',1],['Thepla',1],['Handvo',1],['Gujarati kadhi',1],['Shrikhand',1],['Fafda-jalebi',1]],
   lessons:['Sweet, sour and hot: the dhana-jeera pantry','The thali as a system','Dhokla, undhiyu and the steamed kitchen','Ports, Jains and the Parsi landing at Sanjan']},
 'IN-MAH':{name:'Maharashtra', capital:'Mumbai', area:'West', color:'#c98f5e', intro:"Three kitchens under one name: coconut and rice on the Konkan coast, peanut and jaggery on the Deccan plateau, and in Mumbai the food of everybody who ever arrived by boat or by train.",
   landmark:{name:'Gateway of India, Mumbai', desc:'A basalt arch finished in 1924 to greet arriving Viceroys, and used in 1948 to watch the last British troops leave through it.',props:[['gateway',18.92,72.83]]},
   spices:[['Goda masala','blend'],['Dagad phool','whole'],['Kala masala','blend'],['Peanut','whole'],['Curry leaf','fresh'],['Kokum','souring']],
   plate:'Misal with pav to mop it, raw onion and lime alongside, and the thin red rassa poured over at the end.',
   dishes:[['Misal pav',1],['Vada pav',1],['Puran poli',1],['Pav bhaji',1],['Kolhapuri mutton',0],['Bombil fry',0],['Modak',1],['Kanda poha',1],['Sali boti',0]],
   lessons:['Goda masala and the stone flower','Bhakri on the plateau, rice on the coast','Misal, vada pav and the Kolhapuri red','Bombay: mills, Iranis and the food of arrival']},
 'IN-KON':{name:'Goa & the Konkan', capital:'Panaji', area:'West', color:'#d97f5c', intro:"Four hundred and fifty years of Portugal left vinegar, pork and a word for curry, and took very little away. The chilli itself came ashore here, from Brazil, and went on to change every kitchen in this course.",
   landmark:{name:'Basilica of Bom Jesus, Old Goa', desc:'Laterite and lime, consecrated 1605, holding the body of Francis Xavier. The city around it was once called the Rome of the East and is now mostly trees.',props:[['bomjesus',15.50,73.91]]},
   spices:[['Recheado masala','blend'],['Xacuti masala','blend'],['Kashmiri chilli','ground'],['Palm vinegar','souring'],['Toasted coconut','fresh'],['Tamarind','souring']],
   plate:'Fish curry and par-boiled rice, every day, with a fried mackerel on the side and solkadhi to finish.',
   dishes:[['Vindaloo',0],['Xacuti',0],['Sorpotel',0],['Cafreal',0],['Prawn balchão',0],['Fish curry rice',0],['Sannas',1],['Bebinca',1]],
   lessons:['Vinegar, chilli and the recheado masala','Ukda rice and the daily fish curry','Vindaloo, xacuti and sorpotel','1510: what Portugal brought, and what it took']},
 'IN-CEN':{name:'The Deccan centre', capital:'Bhopal', area:'Centre', color:'#b5a074', intro:"The middle of the country cooks quietly and is rarely written about. Malwa grinds poppy seed into its gravies, Bhopal inherited a Mughal kitchen run for a century by four women, and the forests of Bastar eat things that grow nowhere else.",
   landmark:{name:'The Great Stupa, Sanchi', desc:'A brick dome raised by Ashoka in the third century BC, cased in stone and ringed by four carved gateways. The oldest stone structure still standing in India.',props:[['sanchi',23.48,77.74]]},
   spices:[['Poppy seed (khus khus)','whole'],['Bhopali garam masala','blend'],['Chironji','whole'],['Mahua','fresh'],['Black cardamom','whole'],['Tamarind','souring']],
   plate:'Poha with sev and a wedge of lime at eight in the morning, jalebi still dripping, and tea after.',
   dishes:[['Indori poha',1],['Bhutte ka kees',1],['Dal bafla',1],['Bhopali korma',0],['Rogan josh Bhopali',0],['Chironji ki barfi',1],['Chila',1],['Mahua laddu',1]],
   lessons:['Poppy seed, chironji and the forest pantry','Wheat in Malwa, rice in Chhattisgarh','Poha, bafla and the Bhopali korma','Ashoka, the Begums and the Bastar kitchens']},
 'IN-BEN':{name:'Bengal & the east', capital:'Kolkata', area:'East', color:'#9fb06a', intro:"Five spices that are never ground, mustard oil hot enough to catch the back of the throat, and a meal served in an order that runs bitter to sweet. East of Bihar, rice and fish do the work wheat and dairy do in Punjab.",
   landmark:{name:'Howrah Bridge, Kolkata', desc:'A cantilever span opened in 1943 with no bolts and no nuts, riveted throughout, carrying something like a hundred thousand people on foot every day.',props:[['howrah',22.58,88.35]]},
   spices:[['Panch phoron','blend'],['Mustard oil','fresh'],['Nigella (kalonji)','whole'],['Poppy seed (posto)','whole'],['Radhuni','whole'],['Kasundi','souring']],
   plate:'Rice, then shukto, then dal, then a fish in light gravy, then chutney, then a sweet. In that order, and not in any other.',
   dishes:[['Shorshe ilish',0],['Macher jhol',0],['Kosha mangsho',0],['Shukto',1],['Luchi-alur dom',1],['Litti chokha',1],['Chhena poda',1],['Mishti doi',1],['Rasgulla',1]],
   lessons:['Panch phoron, mustard and the whole-spice rule','Rice and the order of a Bengali meal','Ilish, kosha mangsho and the sweets','Chhana, the Portuguese and a Nawab in exile']},
 'IN-NEA':{name:'The North-East', capital:'Guwahati', area:'East', color:'#77a07e', intro:"Eight states where almost none of the Indian spice pantry arrived. The heat comes from a chilli that held the world record, the depth from fermented fish, soya and bamboo, and the cooking is steaming, smoking and boiling rather than frying.",
   landmark:{name:'The living root bridges of Meghalaya', desc:'Rubber fig roots trained across a river over fifteen or twenty years, and stronger every decade instead of weaker. Some are said to be five hundred years old.',props:[['rootbridge',25.25,91.68]]},
   spices:[['Bhut jolokia','fresh'],['Bamboo shoot','souring'],['Axone (fermented soya)','fresh'],['Khar (alkali)','ground'],['Black sesame','whole'],['Kharoli','souring']],
   plate:'Rice, a bowl of sour tenga, a pitika of mashed potato with mustard oil, and a chilli on the side of the plate.',
   dishes:[['Masor tenga',0],['Khar',1],['Smoked pork with bamboo',0],['Axone pork',0],['Eromba',1],['Jadoh',0],['Aloo pitika',1],['Thukpa',0]],
   lessons:['Fermentation instead of spice','Rice, sticky rice and the steamed pot','Tenga, khar and the smoked pork','The Ahoms, the hills and the pantry that never crossed']},
 'IN-KAR':{name:'Karnataka', capital:'Bengaluru', area:'South', color:'#a8b060', intro:"Finger millet in the dry interior, rice and coconut on the coast, a chilli grown for its colour rather than its heat, and in Udupi a temple kitchen whose cooking left home and opened restaurants in every Indian city.",
   landmark:{name:'Mysore Palace', desc:'Rebuilt in 1912 after a fire, in a style its architect called Indo-Saracenic and everyone else calls the Mysore Palace. Ninety-seven thousand bulbs light it on Sunday nights.',props:[['mysore',12.30,76.65]]},
   spices:[['Byadgi chilli','ground'],['Bisi bele bath powder','blend'],['Coconut','fresh'],['Curry leaf','fresh'],['Kachampuli','souring'],['Black cardamom','whole']],
   plate:'A ball of ragi mudde swallowed, not chewed, with a thin greens saaru, and buttermilk after.',
   dishes:[['Bisi bele bath',1],['Mysore masala dosa',1],['Ragi mudde',1],['Neer dosa',1],['Pandi curry',0],['Kundapur koli saaru',0],['Mysore pak',1],['Dharwad peda',1]],
   lessons:['Byadgi: the chilli grown for colour','Ragi, rice and the coastal batter','Bisi bele bath, dosa and pandi curry','Vijayanagara, the Wodeyars and seven coffee beans']},
 'IN-AND':{name:'Andhra & Telangana', capital:'Hyderabad', area:'South', color:'#c47b56', intro:"The hottest everyday cooking in India, built on the Guntur chilli and a sourness from tamarind and gongura leaf. In Hyderabad the same country grows a second kitchen, Persian in its aromatics, that cools all of it down.",
   landmark:{name:'Charminar, Hyderabad', desc:'Four minarets over four arches, put up in 1591 when the Qutb Shahi court moved out of Golconda. The old market still runs around its feet.',props:[['charminar',17.36,78.47]]},
   spices:[['Guntur chilli','ground'],['Gongura','fresh'],['Tamarind (chintapandu)','souring'],['Mustard seed','whole'],['Fenugreek (menthulu)','whole'],['Bagara masala','blend']],
   plate:'Rice, a spoonful of ghee, pappu, a sour gongura pachadi, and avakaya from the jar that was filled in May.',
   dishes:[['Hyderabadi biryani',0],['Gongura mamsam',0],['Avakaya',1],['Pesarattu',1],['Pulihora',1],['Haleem',0],['Bagara baingan',1],['Qubani ka meetha',1]],
   lessons:['Guntur heat and gongura sour','Rice, pappu and the pickle that lasts a year','Biryani, haleem and the gongura mutton','Qutb Shahis and Nizams: Persia in the Deccan']},
 'IN-TAM':{name:'Tamil Nadu', capital:'Chennai', area:'South', color:'#d0a352', intro:"Before chilli there was pepper, and Tamil ports were selling it to Rome. The everyday cooking is restrained and rice-based; the Chettinad kitchen inland is anything but, and roasts its spices black.",
   landmark:{name:'Brihadisvara Temple, Thanjavur', desc:'Finished in 1010 under Rajaraja Chola, its tower 66 m of granite in a district with no granite for sixty kilometres.',props:[['thanjavur',10.78,79.13]]},
   spices:[['Black pepper','whole'],['Kalpasi (stone flower)','whole'],['Star anise','whole'],['Marathi mokku','whole'],['Sambar podi','blend'],['Tamarind','souring']],
   plate:'A banana leaf: rice at the centre, sambar poured first, then rasam, then curd, with the pickle at the top left corner where it has always been.',
   dishes:[['Idli',1],['Dosa',1],['Sambar',1],['Rasam',1],['Chettinad chicken',0],['Meen kuzhambu',0],['Kothu parotta',0],['Filter coffee',1],['Payasam',1]],
   lessons:['Pepper, kalpasi and the Chettinad roast','Fermented batter and the banana-leaf order','Idli, sambar and the Chettinad kitchen','Cholas, Romans and the Chettiars who went east']},
 'IN-KER':{name:'Kerala', capital:'Kochi', area:'South', color:'#7fa96a', intro:"This is where the story starts. Black pepper and cardamom grow on these hills, and every trader who wanted them - Roman, Arab, Chinese, Jewish, Portuguese, Dutch - left something in the kitchen on the way through.",
   landmark:{name:'The Chinese fishing nets, Fort Kochi', desc:'Cantilevered shore-operated nets, lowered and raised by four men and a row of stones, said to have come with traders from the court of Kublai Khan.',props:[['cheenavala',9.97,76.24]]},
   spices:[['Black pepper','whole'],['Cardamom','whole'],['Cinnamon','whole'],['Curry leaf','fresh'],['Coconut oil','fresh'],['Kudampuli','souring']],
   plate:'Red matta rice, a fish curry sharp with kudampuli, thoran on the side, and a spoon of coconut oil poured over at the end.',
   dishes:[['Meen curry',0],['Appam with stew',0],['Puttu-kadala',1],['Kerala parotta',1],['Beef fry',0],['Avial',1],['Karimeen pollichathu',0],['Thalassery biryani',0],['Sadya',1]],
   lessons:['Pepper, cardamom and the spice coast','Rice in four shapes, coconut in four more','Meen curry, appam and the sadya','Muziris to Vasco da Gama: the trade that made the kitchen']},
};
