/* Masala Dabba — recipes for Andhra & Telangana (IN-AND). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-AND'] = [

{
  id:'pulihora', dish:'Pulihora', course:'rice', lesson:2, serves:4, veg:true,
  time:{prep:25, cook:35}, hero:'pulihora', tags:['rice','tamarind','temple'],
  title:{en:'Pulihora', no:'Pulihora'},
  blurb:{en:'Tamarind cooked down with sesame oil and tempering, then folded through rice and served promptly or chilled.',
         no:'Tamarind kokt inn med sesamolje og tempering, vendt i ris og servert straks eller kjølt ned.'},
  heroCaption:{en:'Peanuts, split chickpeas and curry leaves stay visible through the rice. The colour is turmeric and cooked-down tamarind, not chilli.',
               no:'Jordnøtter, delte kikerter og karriblad ligger synlig i risen. Fargen kommer fra gurkemeie og innkokt tamarind, ikke fra chili.'},
  goesWith:[{en:'Plain yoghurt, cold', no:'Naturell yoghurt, kald'},
            {en:'A fried pappadam', no:'En stekt pappadam'}],
  headnote:{
    en:`<p>Pulihora benefits from a short rest while the tamarind seasoning coats the rice, but cooked rice still needs ordinary temperature control. Serve it after mixing, or refrigerate it within two hours and keep it cold until needed.</p>
<p>Two things separate a good one from a merely sour one. The tamarind is not stirred in raw: it is cooked down in sesame oil with the tempering until it darkens and thickens into a paste that holds a line when you draw a spoon through it. And a small amount of sesame and fenugreek is roasted and ground in at the very end, which gives the dish the nutty bottom note that a plain tamarind rice lacks.</p>
<p>Let the freshly cooked rice release its steam in a clean wide tray. It need not become refrigerator-cold before mixing; the aim is separate grains and prompt serving or chilling.</p>`,
    no:`<p>Pulihora har godt av en kort hvile mens tamarindkrydderet legger seg rundt risen, men kokt ris trenger fortsatt vanlig temperaturkontroll. Server etter blanding, eller sett den i kjøleskap innen to timer og hold den kald til den skal spises.</p>
<p>To ting skiller en god pulihora fra en som bare er sur. Tamarinden røres ikke inn rå. Den kokes ned i sesamolje sammen med temperingen til den mørkner og tykner så mye at sporet etter skjeen blir stående. Og en liten mengde sesam og bukkehornkløver ristes og males inn helt til slutt, og det gir retten den nøtteaktige bunnen en vanlig tamarindris mangler.</p>
<p>La nykokt ris dampe av i et rent, vidt fat. Den trenger ikke bli kjøleskapskald før blanding; målet er separate korn og rask servering eller nedkjøling.</p>`},
  ingredients:[
   {group:{en:'The rice', no:'Risen'}, items:[
    {q:300, u:'g', n:{en:'short-grain or medium-grain rice', no:'kort- eller mellomkornet ris'}, note:{en:'rinsed until the water runs clear', no:'skylt til vannet er klart'}},
    {q:600, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15, u:'ml', n:{en:'sesame oil', no:'sesamolje'}, note:{en:'for forking through the hot rice', no:'til å vende inn i den varme risen'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The tamarind paste', no:'Tamarindpastaen'}, items:[
    {q:60, u:'g', n:{en:'tamarind block', no:'tamarind i blokk'}},
    {q:250, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub', note:{en:'for soaking the tamarind', no:'til å bløtlegge tamarinden i'}},
    {q:60, u:'ml', n:{en:'sesame oil', no:'sesamolje'}},
    {q:5, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:25, u:'g', n:{en:'raw peanuts', no:'usaltede jordnøtter'}},
    {q:15, u:'g', n:{en:'split chickpeas (chana dal)', no:'delte kikerter (chana dal)'}},
    {q:10, u:'g', n:{en:'split black gram (urad dal)', no:'delt urad dal'}},
    {q:4, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half', note:{en:'broken in half', no:'brukket i to'}},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'flekket på langs'}},
    {q:20, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:1, u:'g', n:{en:'asafoetida', no:'asafoetida'}, scale:'none'},
   ]},
   {group:{en:'The roasted powder', no:'Det ristede pulveret'}, items:[
    {q:10, u:'g', n:{en:'sesame seeds', no:'sesamfrø'}},
    {q:2, u:'g', n:{en:'fenugreek seeds', no:'bukkehornkløverfrø'}},
    {q:2, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
   ]}],
  steps:[
    {en:'Cook the rinsed rice in the water with a little salt until the grains are just done and still separate, then tip it out into a wide tray.',
     no:'Kok den skylte risen i vannet med litt salt til kornene akkurat er ferdige og fortsatt ligger hver for seg, og hell den så ut i et vidt fat.'},
    {en:'Fork the sesame oil through the hot rice and spread it out in a thin layer to cool completely. Do not cover it while it cools.',
     no:'Vend sesamoljen inn i den varme risen med en gaffel og bre den utover i et tynt lag så den kjøler seg helt. Ikke dekk den til mens den kjøler seg.'},
    {en:'Soak the tamarind in the hot water for twenty minutes, squeeze it out with your fingers and strain the extract. Throw away the fibres and the seeds.',
     no:'Bløtlegg tamarinden i det varme vannet i tjue minutter, klem den ut med fingrene og sil ekstraktet. Kast trevlene og kjernene.'},
    {en:'Dry-roast the sesame, the fenugreek and the chillies for the powder in a small pan until the sesame starts to jump, then grind them coarse and set the powder aside.',
     no:'Tørrist sesamen, bukkehornkløveren og chilien til pulveret i en liten panne til sesamen begynner å hoppe. Mal dem grovt og sett pulveret til side.'},
    {en:'Heat the sesame oil in a heavy pan, add the mustard seed and wait for it to pop properly before anything else goes in.',
     no:'Varm sesamoljen i en tung panne, ha i sennepsfrøene og vent til de har sprettet ferdig før noe annet går i.'},
    {en:'Add the peanuts, the split chickpeas and the urad dal, and fry over a medium flame until the lentils turn golden and the peanuts colour.',
     no:'Ha i jordnøttene, de delte kikertene og urad dalen, og stek på middels varme til linsene blir gylne og jordnøttene får farge.'},
    {en:'Add the dried chillies, the green chillies and the curry leaves. Stand back while they crackle, then pull the pan off the heat and stir in the turmeric and the asafoetida.',
     no:'Ha i de tørkede chiliene, de grønne chiliene og karribladene. Hold deg unna mens det knitrer, trekk så pannen av platen og rør inn gurkemeien og asafoetidaen.'},
    {en:'Return the pan to a medium flame, pour in the tamarind extract and salt it. Simmer until it darkens and thickens enough to hold a line when a spoon is drawn through it, fifteen to twenty minutes.',
     no:'Sett pannen tilbake på middels varme, hell i tamarindekstraktet og salt. La det småkoke til det mørkner og tykner så mye at sporet etter skjeen blir stående, femten til tjue minutter.'},
    {en:'Take the paste off the heat, stir in the roasted powder and let the strongest heat subside while the rice releases its steam.',
     no:'Ta pastaen av platen, rør inn det ristede pulveret og la den sterkeste varmen slippe mens risen damper av.'},
    {en:'Fold the paste through the rice a little at a time, tasting as you go. Serve promptly, or divide into shallow containers and refrigerate within two hours.',
     no:'Vend pastaen inn i risen litt om gangen og smak underveis. Server straks, eller fordel i grunne bokser og sett i kjøleskap innen to timer.'}],
  notes:[
    {title:{en:'Why the rice is spread out', no:'Hvorfor risen bres utover'},
     body:{en:'Spreading lets steam escape and makes the grains firmer and easier to coat without crushing them. It also helps rice cool quickly if it will not be served at once; move it to the refrigerator within two hours.',
           no:'Når risen bres utover, slipper dampen ut og kornene blir fastere og lettere å dekke uten å knuses. Det hjelper også risen å kjølne raskt hvis den ikke skal serveres straks; sett den i kjøleskap innen to timer.'}},
    {title:{en:'Why the tamarind is cooked down', no:'Hvorfor tamarinden kokes ned'},
     body:{en:'Raw tamarind extract is mostly water, and stirred into rice it makes the grains wet and tastes flat. Cooking it down concentrates the acidity and lets the oil carry the tempering. Refrigerate any unused paste promptly and use it within a few days.',
           no:'Rått tamarindekstrakt er for det meste vann, og rørt inn i ris gjør det kornene våte og smaker flatt. Innkoking konsentrerer syren, og oljen bærer temperingen. Sett ubrukt pasta raskt i kjøleskap og bruk den i løpet av noen dager.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy tamarind as a pressed block with the seeds still in it and soak it yourself, because that is what these quantities are written for.',
           no:'Kjøp tamarind som presset blokk med kjernene i og bløtlegg den selv, for det er det disse mengdene er skrevet for. Konsentratet på glass er allerede kokt inn og er mye sterkere, så bruk under en femdel så mye og spe med vann. «Tamarind paste» i dagligvaren er ofte spedd ut med vann og salt og gir en tynn og salt rett. Karriblad får du ferske eller frosne i indiske butikker på Grønland i Oslo; de tørkede gir nesten ingenting. Bruk kortkornet ris, ikke basmati, for basmatikornet er for tynt og tørt til å bære pastaen. Asafoetida selges som hing og lukter kraftig; en knivsodd er nok.'}}],
  variations:[
    {title:{en:'Nimmakaya pulihora, with lemon', no:'Nimmakaya pulihora, med sitron'},
     body:{en:'Make the same tempering, leave the tamarind out entirely and stir lemon juice into the rice off the heat, with plenty of turmeric. The dish turns yellow and much fresher, and it is what many households make when the tamarind has run out.',
           no:'Lag den samme temperingen, sløyf tamarinden helt og rør sitronsaft inn i risen med kjelen av platen, sammen med rikelig gurkemeie. Retten blir gul og mye friskere, og det er den mange husholdninger lager når tamarinden er slutt.'}},
    {title:{en:'Mamidikaya pulihora, with raw mango', no:'Mamidikaya pulihora, med umoden mango'},
     body:{en:'In spring, grated hard green mango replaces the tamarind. It goes into the tempering and cooks for only a few minutes, because it is meant to stay sharp rather than break down.',
           no:'Om våren erstatter revet hard grønn mango tamarinden. Den går i temperingen og koker bare noen få minutter, for den skal holde seg skarp og ikke falle fra hverandre.'}},
    {title:{en:'With more lentils', no:'Med mer linser'},
     body:{en:'Temple kitchens are generous with the peanuts and the split chickpeas, so that there is something to bite in every mouthful. Doubling them changes the dish more than doubling the tamarind would.',
           no:'Tempelkjøkken er rause med jordnøttene og de delte kikertene, så du får noe å bite i hver munnfull. Dobler du dem, endrer det retten mer enn en dobling av tamarinden ville gjort.'}}]
},

{
  id:'pesarattu', dish:'Pesarattu', course:'breakfast', lesson:2, serves:4, veg:true,
  time:{prep:20, cook:25}, hero:'pesarattu', tags:['breakfast','green gram','unfermented'],
  title:{en:'Pesarattu', no:'Pesarattu'},
  blurb:{en:'A green crepe of whole green gram, ground and cooked the same day, with onion pressed into the surface.',
         no:'En grønn pannekake av hele grønne mungbønner, malt og stekt samme dag, med løk presset ned i overflaten.'},
  heroCaption:{en:'The colour comes from the skins of the whole green gram. A batter made with the split yellow lentil would be pale.',
               no:'Fargen kommer fra skallet på de hele grønne mungbønnene. En røre av den delte gule linsen ville blitt blek.'},
  goesWith:[{en:'Ginger and tamarind chutney', no:'Chutney av ingefær og tamarind'},
            {en:'Strong coffee or tea', no:'Sterk kaffe eller te'}],
  headnote:{
    en:`<p>Pesarattu resembles a dosa but uses a different batter. Whole green gram is soaked, ground with ginger and chilli, and usually cooked the same day without a deliberate overnight fermentation.</p>
<p>Microorganisms occur on many grains and pulses, including green gram, so leaving the batter warm can still start fermentation. This recipe aims for a fresh pulse flavour: refrigerate soaked beans and batter if cooking is delayed.</p>
<p>The crepe is green, a little chewy and distinctly pulse-flavoured. Ginger-and-tamarind chutney is a common partner.</p>`,
    no:`<p>Pesarattu ligner en dosa, men bruker en annen røre. Hele grønne mungbønner bløtlegges, males med ingefær og chili og stekes vanligvis samme dag uten planlagt gjæring over natten.</p>
<p>Mikroorganismer finnes på mange korn og belgfrukter, også mungbønner, så en røre som står varmt, kan begynne å gjære. Denne oppskriften skal smake av ferske belgfrukter: sett bløtlagte bønner og røre i kjøleskap hvis stekingen blir utsatt.</p>
<p>Pannekaken blir grønn, litt seig og smaker tydelig av belgfrukten. Chutney av ingefær og tamarind er et vanlig følge.</p>`},
  ingredients:[
   {group:{en:'The batter', no:'Røren'}, items:[
    {q:300, u:'g', n:{en:'whole green gram (green moong)', no:'hele grønne mungbønner'}, note:{en:'soaked 6 hours or overnight', no:'bløtlagt i 6 timer eller over natten'}},
    {q:50, u:'g', n:{en:'raw rice', no:'ukokt ris'}, note:{en:'soaked with the green gram', no:'bløtlagt sammen med mungbønnene'}},
    {q:30, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'peeled, roughly chopped', no:'skrelt og grovhakket'}},
    {q:4, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:4, u:'g', n:{en:'cumin seed', no:'spisskummen'}},
    {q:180, u:'ml', n:{en:'cold water', no:'kaldt vann'}, scale:'sub', note:{en:'added a little at a time while grinding', no:'has i litt om gangen mens du maler'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'On the griddle', no:'På takken'}, items:[
    {q:2, u:'', n:{en:'onions', no:'løk'}, round:'half', note:{en:'chopped very fine', no:'finhakket'}},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
    {q:3, u:'g', n:{en:'cumin seed', no:'spisskummen'}},
    {u:'', n:{en:'sesame oil for the griddle', no:'sesamolje til takken'}, scale:'none'},
   ]}],
  steps:[
    {en:'Soak the green gram and the rice together in plenty of cold water for six hours or overnight, then drain them well.',
     no:'Bløtlegg mungbønnene og risen sammen i rikelig kaldt vann i seks timer eller over natten, og hell så godt av vannet.'},
    {en:'Grind them with the ginger, the green chillies, the cumin, salt and the cold water to a batter slightly thicker than double cream. It should pour off the ladle in a ribbon rather than run.',
     no:'Kjør dem sammen med ingefæren, de grønne chiliene, spisskummenen, salt og det kalde vannet til en røre som er litt tykkere enn kremfløte. Den skal renne av sleiva som et bånd og ikke som vann.'},
    {en:'Let the batter stand for twenty minutes while you chop the onion and coriander. If cooking is delayed, cover and refrigerate it.',
     no:'La røren stå i tjue minutter mens du hakker løken og korianderen. Hvis stekingen blir utsatt, dekker du røren og setter den i kjøleskapet.'},
    {en:'Heat a flat iron griddle or a heavy frying pan over a medium flame until a drop of water skitters across it and disappears.',
     no:'Varm en flat takke av støpejern eller en tung stekepanne på middels varme til en vanndråpe danser over den og forsvinner.'},
    {en:'Pour a ladle of batter into the middle and spread it outwards in a spiral with the back of the ladle, as thin as you can without tearing it.',
     no:'Hell en sleiv røre midt på og dra den utover i en spiral med baksiden av sleiva, så tynt du klarer uten at den revner.'},
    {en:'Drizzle a little oil round the rim, scatter chopped onion, coriander and cumin over the surface, and press them in lightly with a flat spoon.',
     no:'Drypp litt olje langs kanten, strø hakket løk, koriander og spisskummen over overflaten og trykk dem lett ned med en flat skje.'},
    {en:'Cook for two to three minutes, until the underside is brown in patches and the edges lift away from the griddle on their own.',
     no:'Stek i to til tre minutter, til undersiden er brun i flekker og kantene løsner fra takken av seg selv.'},
    {en:'Fold it in half or roll it up, and take it to the table at once. A pesarattu goes soft within a few minutes of leaving the pan.',
     no:'Brett den i to eller rull den sammen, og sett den på bordet med en gang. En pesarattu blir myk få minutter etter at den forlater pannen.'},
    {en:'Wipe the griddle with a folded cloth before the next one. The surface has to be hot and dry each time, or the batter sticks and tears.',
     no:'Tørk av takken med en sammenbrettet klut før neste. Overflaten må være varm og tørr hver gang, ellers setter røren seg fast og revner.'}],
  notes:[
    {title:{en:'Why this batter is used fresh', no:'Hvorfor denne røren brukes fersk'},
     body:{en:'This recipe is designed around the flavour and texture of freshly ground green gram, not a controlled fermentation. Grind only what you need; refrigerate extra soaked beans or batter promptly and cook them the next day.',
           no:'Oppskriften bygger på smaken og konsistensen i nymalte mungbønner, ikke på kontrollert gjæring. Mal bare det du trenger; sett ekstra bløtlagte bønner eller røre raskt i kjøleskap og stek dem neste dag.'}},
    {title:{en:'Why the onion goes on top and not in', no:'Hvorfor løken legges oppå og ikke i'},
     body:{en:'Onion stirred into the batter releases water as it heats, and the crepe steams instead of crisping. Pressed into the upper surface it browns in the open air while the underside cooks, and it stays where it was put when the crepe is folded.',
           no:'Løk som røres inn i røren, slipper vann når den varmes opp, og da damper pannekaken i stedet for å bli sprø. Trykker du den ned i den øvre flaten, bruner den seg i åpen luft mens undersiden steker, og den blir liggende der du la den når pannekaken brettes.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'The pulse has to be the whole green one with its skin on, not the split yellow moong dal sold beside it.',
           no:'Belgfrukten må være den hele grønne med skallet på, ikke den delte gule moong dalen som ofte står ved siden av. Hele grønne mungbønner selges i indiske butikker, i asiatiske butikker og i helsekost, og de er billige. Ferdig spirede mungbønner fra dagligvaren fungerer ikke, for spirene har brukt opp stivelsen røren trenger. En vanlig stavmikser klarer jobben, men en kraftig blender gir jevnere røre. En støpejernspanne som er godt innarbeidet, er det nærmeste du kommer en indisk takke.'}}],
  variations:[
    {title:{en:'MLA pesarattu, with upma inside', no:'MLA pesarattu, med upma inni'},
     body:{en:'Spread a layer of upma, coarse semolina cooked with onion and mustard seed, over one half of the crepe before folding it. The story says it was named for the legislators eating it near the assembly in Hyderabad, which is a good story rather than a documented one.',
           no:'Legg et lag upma, grov semule kokt med løk og sennepsfrø, over den ene halvdelen før du bretter. Historien vil ha det til at retten er oppkalt etter folkevalgte som spiste den nær delstatsforsamlingen i Hyderabad, og det er en god historie heller enn et dokumentert navn.'}},
    {title:{en:'Allam pachadi, the chutney it belongs with', no:'Allam pachadi, chutneyen som hører til'},
      body:{en:'Fry ginger and dried chilli in sesame oil, grind them with tamarind, jaggery and salt, and finish with mustard seed and curry leaf. Refrigerate promptly and use within three days, or freeze small portions.',
            no:'Stek ingefær og tørket chili i sesamolje, mal dem med tamarind, jaggery og salt, og avslutt med sennepsfrø og karriblad. Sett raskt i kjøleskap og bruk innen tre dager, eller frys små porsjoner.'}},
    {title:{en:'Thicker, as uttapam', no:'Tykkere, som uttapam'},
     body:{en:'Loosen the batter less, pour it out without spreading it and give it five minutes over a lower flame. You get a thick soft pancake instead of a thin crisp one, which suits the onion topping even better.',
           no:'Spe røren mindre, hell den ut uten å dra den utover og gi den fem minutter på lavere varme. Da får du en tykk og myk pannekake i stedet for en tynn og sprø, og det passer løken på toppen enda bedre.'}}]
},

{
  id:'bagara-baingan', dish:'Bagara baingan', course:'main', lesson:3, serves:4, veg:true,
  time:{prep:30, cook:50}, hero:'bagara-baingan', tags:['aubergine','peanut','Hyderabad'],
  title:{en:'Bagara baingan', no:'Bagara baingan'},
  blurb:{en:'Small aubergines fried whole and finished in a gravy thickened with roasted peanut, sesame and dry coconut.',
         no:'Små auberginer stekt hele og ferdigkokt i en saus jevnet med ristede jordnøtter, sesam og tørket kokos.'},
  heroCaption:{en:'The aubergines are slit into quarters but left joined at the stalk, so they hold their shape in the pot.',
               no:'Auberginene snittes i fire, men henger sammen ved stilken, så de holder fasongen i gryta.'},
  goesWith:[{en:'Plain rice, or a mildly spiced bagara khana', no:'Vanlig ris, eller en mildt krydret bagara khana'},
            {en:'Thinned yoghurt with onion', no:'Tynnet yoghurt med løk'}],
  headnote:{
    en:`<p>This is the dish that explains the Hyderabadi gravy. Nothing in it thickens with cream, yoghurt, flour or tomato. The body comes entirely from roasted peanut, sesame and dry coconut ground to a paste, and that paste is also most of the flavour. Mirchi ka salan, the thin chilli dish served beside a biryani, uses very nearly the same gravy, which tells you the paste is the recipe and the vegetable is a passenger.</p>
<p>The word bagara comes from baghar, the tempering, and it turns up all over this kitchen. In this dish it means the mustard seed and curry leaf that go into the oil before the onion, and everything after that builds on them.</p>
<p>The method has one real trap. Small aubergines collapse if you simmer them in gravy for half an hour, so they are fried apart until the skins blister and only returned to the pot at the very end. The gravy is made without them and is finished before they go back in.</p>`,
    no:`<p>Dette er retten som forklarer den hyderabadiske sausen. Ingenting i den jevnes med fløte, yoghurt, mel eller tomat. Fylden kommer utelukkende fra ristede jordnøtter, sesam og tørket kokos malt til pasta, og den pastaen er også mesteparten av smaken. Mirchi ka salan, den tynne chiliretten som serveres ved siden av en biryani, bruker nesten nøyaktig den samme sausen, og det forteller deg at pastaen er oppskriften og at grønnsaken er en passasjer.</p>
<p>Ordet bagara kommer av baghar, som betyr tempering, og det dukker opp over hele dette kjøkkenet. I denne retten betyr det sennepsfrøene og karribladene som går i oljen før løken, og alt som kommer etterpå, bygger på dem.</p>
<p>Metoden har én virkelig felle. Små auberginer faller sammen hvis de småkoker i saus i en halv time, så de stekes for seg til skallet blærer seg, og legges først tilbake i gryta helt til slutt. Sausen lages uten dem og er ferdig før de går i.</p>`},
  ingredients:[
   {group:{en:'The ground paste', no:'Den malte pastaen'}, items:[
    {q:60, u:'g', n:{en:'raw peanuts', no:'usaltede jordnøtter'}},
    {q:30, u:'g', n:{en:'sesame seeds', no:'sesamfrø'}},
    {q:30, u:'g', n:{en:'dry unsweetened coconut', no:'tørket usøtet kokos'}},
    {q:10, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:4, u:'g', n:{en:'cumin seed', no:'spisskummen'}},
   ]},
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:500, u:'g', n:{en:'small round aubergines', no:'små runde auberginer'}, note:{en:'about eight, with the stalks on', no:'omtrent åtte, med stilken på'}},
    {q:80, u:'ml', n:{en:'sesame or groundnut oil', no:'sesamolje eller jordnøttolje'}},
    {q:5, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
    {q:200, u:'g', n:{en:'onions', no:'løk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:15, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:15, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:8, u:'g', n:{en:'hot chilli powder', no:'sterkt chilipulver'}},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:30, u:'g', n:{en:'tamarind block', no:'tamarind i blokk'}},
    {q:200, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub', note:{en:'for soaking the tamarind', no:'til å bløtlegge tamarinden i'}},
    {q:400, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:8, u:'g', n:{en:'jaggery or palm sugar', no:'jaggery eller palmesukker'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Dry-roast the peanuts in a heavy pan over a medium flame until they colour and the skins loosen, then tip them onto a plate.',
     no:'Tørrist jordnøttene i en tung panne på middels varme til de får farge og skallet løsner, og hell dem så over på en tallerken.'},
    {en:'Roast the sesame, the coconut, the coriander and the cumin one after another in the same pan, each only until it smells, and add them to the peanuts.',
     no:'Rist sesamen, kokosen, korianderen og spisskummenen etter hverandre i den samme pannen, hver av dem bare til det dufter, og ha dem sammen med jordnøttene.'},
    {en:'Grind the roasted mixture with enough cold water to make a thick paste. Leave it slightly gritty rather than working it smooth.',
     no:'Mal den ristede blandingen med akkurat nok kaldt vann til en tykk pasta. La den være litt kornete i stedet for å kjøre den glatt.'},
    {en:'Soak the tamarind in the hot water for twenty minutes, squeeze it out and strain the extract.',
     no:'Bløtlegg tamarinden i det varme vannet i tjue minutter, klem den ut og sil ekstraktet.'},
    {en:'Cut each aubergine from the base into quarters, leaving the stalk end joined so the pieces stay together.',
     no:'Snitt hver aubergine i fire fra bunnen, men la enden med stilken henge sammen så bitene holder seg hele.'},
    {en:'Heat the oil in a wide pan and fry the aubergines over a medium flame, turning them, until the skins blister and darken all over. Lift them out and keep them.',
     no:'Varm oljen i en vid panne og stek auberginene på middels varme mens du snur dem, til skallet blærer seg og mørkner overalt. Løft dem ut og ta vare på dem.'},
    {en:'In the same oil, pop the mustard seed, add the curry leaves, then the onion, and fry the onion until it is properly brown, fifteen minutes or so.',
     no:'Sprett sennepsfrøene i den samme oljen, ha så i karribladene og deretter løken. Stek løken til den er skikkelig brun, omtrent femten minutter.'},
    {en:'Add the ginger and garlic and cook for a minute, then pull the pan off the heat and stir in the turmeric and the chilli powder so they colour the oil instead of burning.',
     no:'Ha i ingefæren og hvitløken og la det surre et minutt. Trekk så pannen av platen og rør inn gurkemeien og chilipulveret, så de farger oljen i stedet for å svi seg.'},
    {en:'Return the pan, stir in the ground paste and fry it for five minutes, scraping the base. Add the tamarind extract, the water, the jaggery and salt.',
     no:'Sett pannen tilbake, rør inn den malte pastaen og stek den i fem minutter mens du skraper bunnen. Ha i tamarindekstraktet, vannet, jaggeryen og salt.'},
    {en:'Simmer uncovered for fifteen minutes, until the gravy thickens and a rim of oil rises around the edge of the pan.',
     no:'La det småkoke uten lokk i femten minutter, til sausen tykner og det legger seg en rand av olje langs kanten av pannen.'},
    {en:'Slide the aubergines back in, spoon the gravy over them, cover and cook on the lowest heat for ten minutes. Let it stand for fifteen minutes before serving.',
     no:'Legg auberginene tilbake, øs sausen over dem, legg på lokk og la det stå på lavest mulig varme i ti minutter. La retten hvile i femten minutter før servering.'}],
  notes:[
    {title:{en:'Why the aubergines are fried apart', no:'Hvorfor auberginene stekes for seg'},
     body:{en:'A small aubergine is mostly air and water, and half an hour in liquid turns it to pulp that falls out of its own skin. Frying it first sets the skin and drives some of the water off, so it can take ten minutes in the gravy and still arrive whole on the plate.',
           no:'En liten aubergine er for det meste luft og vann, og en halvtime i væske gjør den til mos som faller ut av sitt eget skinn. Steker du den først, stivner skinnet og noe av vannet damper av, så den tåler ti minutter i sausen og likevel kommer hel på tallerkenen.'}},
    {title:{en:'Why the paste stays gritty', no:'Hvorfor pastaen skal være kornete'},
     body:{en:'The texture is the dish. Ground fine in a powerful blender, the peanut releases its oil and the gravy turns into something closer to a sauce that slides off the vegetable. Left a little coarse, it clings, and every spoonful carries the roasted flavour rather than dissolving it.',
           no:'Konsistensen er hele retten. Males pastaen fin i en kraftig blender, slipper jordnøtten oljen sin, og sausen blir glatt og glir av grønnsaken. Er den litt grov, henger den fast, og hver skjefull bærer den ristede smaken i stedet for å løse den opp.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Use unsalted raw peanuts and roast them yourself, because salted roasted nuts make the gravy far too salty.',
           no:'Bruk usaltede rå jordnøtter og rist dem selv, for ferdig saltede og ristede nøtter gjør sausen altfor salt. Små runde auberginer selges i indiske og asiatiske butikker på Grønland i Oslo; de store avlange fra dagligvaren fungerer i biter på fire centimeter, men de faller lettere fra hverandre. Tørket kokos må være den usøtede typen fra en indisk butikk, ikke kokosmasse til baking, som er tilsatt sukker. Jaggery finnes i indiske butikker, og mørk muscovado er den nærmeste erstatningen.'}}],
  variations:[
    {title:{en:'Mirchi ka salan', no:'Mirchi ka salan'},
     body:{en:'Make exactly the same gravy and put long mild green chillies in it instead of the aubergines, slit and fried the same way. Thin it a little more. This is what goes beside a Hyderabadi biryani, and it is sour and hot where the biryani is rich and dry.',
           no:'Lag nøyaktig den samme sausen og ha lange milde grønne chili i den i stedet for auberginene, flekket og stekt på samme måte. Spe sausen litt mer. Dette er det som står ved siden av en hyderabadisk biryani, og den er sur og sterk der biryanien er fyldig og tørr.'}},
    {title:{en:'With poppy seed', no:'Med valmuefrø'},
     body:{en:'Many households add white poppy seed to the roasted mixture. It makes the gravy paler, smoother and a little sweeter, and it is worth trying once you know what the plain version tastes like.',
           no:'Mange husholdninger har hvite valmuefrø i den ristede blandingen. Det gjør sausen lysere, glattere og litt søtere, og det er verdt å prøve når du vet hvordan den enkle utgaven smaker.'}}]
},

{
  id:'gongura-mamsam', dish:'Gongura mamsam', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:30, cook:100}, hero:'gongura-leaves', tags:['goat','gongura','sour'],
  title:{en:'Gongura mamsam, and what to do about the leaf', no:'Gongura mamsam, og hva du gjør med bladet'},
  heroCaption:{en:'Gongura brought in for sale. This is the ingredient the dish is named for, and it is the one thing in it that cannot be bought fresh in Norway.',
               no:'Gongura kjørt inn for salg. Det er denne råvaren retten er oppkalt etter, og det er den eneste tingen i den som ikke kan kjøpes fersk i Norge.'},
  blurb:{en:'Goat cooked down slowly and finished with wilted, ground roselle leaf, which is sour enough to need no tamarind at all.',
         no:'Geitekjøtt kokt langsomt ned og avsluttet med surrede og malte gongurablader, som er sure nok til at retten ikke trenger tamarind.'},
  goesWith:[{en:'Plain rice and nothing else', no:'Vanlig ris og ingenting annet'},
            {en:'A raw onion and a green chilli on the side', no:'Rå løk og en grønn chili ved siden av'}],
  headnote:{
    en:`<p>Start with the honest part. Fresh gongura is not sold in Norway, and nothing growing here is the same leaf. Indian shops sometimes carry it frozen or in a jar, already cooked and salted, and that is the realistic route: it gives you the right acidity and most of the flavour, and this recipe is written so you can use either. If you cannot find any of it, cook something else. Sorrel gives you the sourness without the taste, and spinach with lemon gives you neither, so a substitute here produces a different dish that should be called something else.</p>
<p>The course method cooks the goat nearly tender with onion and chilli before adding ground gongura for the last ten minutes. This keeps the leaf flavour vivid and lets you adjust the final acidity after the meat is tender.</p>
<p>There is no yoghurt in this, no cream, no coconut and no tomato. The gravy is onion, the fat of the goat and the leaves, and it should taste sharp rather than rich. A tempering poured over at the end is the last thing that happens, and it is what lifts the smell of the finished pot.</p>`,
    no:`<p>La oss ta det ærlige først. Fersk gongura selges ikke i Norge, og ingenting som vokser her, er det samme bladet. Indiske butikker fører det av og til frossent eller på glass, ferdig kokt og saltet, og det er den realistiske veien: du får riktig syre og mesteparten av smaken, og oppskriften er skrevet så du kan bruke begge deler. Finner du ingenting av det, lag noe annet. Engsyre gir deg syren uten smaken, og spinat med sitron gir deg ingen av delene, så en erstatning her gir en annen rett som bør hete noe annet.</p>
<p>I kursmetoden kokes geitekjøttet nesten mørt med løk og chili før malt gongura går i de siste ti minuttene. Slik holder bladsmaken seg tydelig, og du kan justere sluttsyren etter at kjøttet er mørt.</p>
<p>Det går ingen yoghurt i denne retten, ingen fløte, ingen kokos og ingen tomat. Sausen består av løk, fettet fra geitekjøttet og bladene, og den skal smake skarp heller enn fyldig. En tempering som helles over til slutt, er det siste som skjer, og den løfter duften av den ferdige gryta.</p>`},
  ingredients:[
   {group:{en:'The meat', no:'Kjøttet'}, items:[
    {q:800, u:'g', n:{en:'goat on the bone', no:'geitekjøtt med bein'}, note:{en:'shoulder and leg, in large pieces', no:'bog og lår, i store biter'}},
    {q:60, u:'ml', n:{en:'sesame oil', no:'sesamolje'}},
    {q:250, u:'g', n:{en:'onions', no:'løk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:20, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:20, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:8, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:10, u:'g', n:{en:'hot chilli powder', no:'sterkt chilipulver'}},
    {q:8, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:350, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The leaves', no:'Bladene'}, items:[
    {q:300, u:'g', n:{en:'gongura leaves', no:'gongurablader'}, note:{en:'picked off the stems; see the sourcing note', no:'plukket av stilkene; se avsnittet om hvor du får tak i det'}},
    {q:4, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
   ]},
   {group:{en:'The tempering', no:'Temperingen'}, items:[
    {q:20, u:'ml', n:{en:'sesame oil', no:'sesamolje'}},
    {q:5, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:4, u:'g', n:{en:'cumin seed', no:'spisskummen'}},
    {q:15, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'sliced thin', no:'i tynne skiver'}},
    {q:5, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
   ]}],
  steps:[
    {en:'Heat the sesame oil in a heavy pan and fry the onion over a medium flame until it is properly dark brown, which takes a good fifteen minutes and cannot be hurried.',
     no:'Varm sesamoljen i en tung gryte og stek løken på middels varme til den er skikkelig mørkebrun. Det tar gode femten minutter og lar seg ikke forsere.'},
    {en:'Add the ginger and garlic pastes and fry until they stop smelling raw, about a minute.',
     no:'Ha i ingefær- og hvitløkspastaen og stek til de slutter å lukte rått, omtrent et minutt.'},
    {en:'Pull the pan off the heat, stir in the turmeric, the chilli powder and the coriander, then set it back on a medium flame.',
     no:'Trekk gryta av platen, rør inn gurkemeien, chilipulveret og korianderen, og sett den så tilbake på middels varme.'},
    {en:'Add the goat and salt it, and fry it hard for ten minutes, until the pieces have taken colour and the oil begins to separate out.',
     no:'Ha i geitekjøttet og salt det, og stek det hardt i ti minutter, til bitene har fått farge og oljen begynner å skille seg ut.'},
    {en:'Pour in the hot water, cover, and cook on the lowest heat until the meat gives easily under a spoon. Allow an hour to an hour and a half.',
     no:'Hell i det varme vannet, legg på lokk og la det stå på lavest mulig varme til kjøttet gir lett etter for en skje. Regn med en time til halvannen.'},
    {en:'While it cooks, pick the gongura leaves off their stems, wash them and shake them dry.',
     no:'Mens det koker, plukker du gongurabladene av stilkene, vasker dem og rister vannet av.'},
    {en:'Wilt the leaves in a dry pan over a medium flame until they collapse into a dark khaki mass, which takes five minutes at most. Do not add water or oil.',
     no:'Surr bladene i en tørr panne på middels varme til de faller sammen til en mørk, olivengrønn masse. Det tar høyst fem minutter. Ikke ha i vann eller olje.'},
    {en:'Grind the wilted leaves coarsely with two of the green chillies. Leave some texture in it rather than making a purée.',
     no:'Mal de surrede bladene grovt sammen med to av de grønne chiliene. La det være litt tyggemotstand igjen i stedet for å lage puré.'},
    {en:'Stir the ground gongura and the remaining slit chillies into the meat and cook uncovered for ten minutes. Taste it now, and remember that it goes on sharpening as it stands.',
     no:'Rør den malte gonguraen og resten av de flekkede chiliene inn i kjøttet og la det koke uten lokk i ti minutter. Smak nå, og husk at retten fortsetter å bli skarpere mens den står.'},
    {en:'In a small pan, heat the oil for the tempering, pop the mustard seed, then add the cumin, the sliced garlic, the dried chillies and the curry leaves and let them darken.',
     no:'Varm oljen til temperingen i en liten panne, sprett sennepsfrøene, og ha så i spisskummenen, hvitløksskivene, de tørkede chiliene og karribladene og la dem mørkne.'},
    {en:'Pour the tempering over the pot, cover it at once, and leave it for ten minutes before serving with rice.',
     no:'Hell temperingen over gryta, legg straks på lokket, og la den stå i ti minutter før du serverer med ris.'}],
  notes:[
    {title:{en:'Why the leaves go in last', no:'Hvorfor bladene går i sist'},
     body:{en:'Adding the leaves near the end keeps their flavour distinct and lets you adjust the final acidity after the goat is tender. It is the sequence used in this course recipe, not a universal rule for every acidic braise.',
           no:'Når bladene går i mot slutten, holder smaken seg tydelig, og du kan justere syren etter at geitekjøttet er mørt. Det er rekkefølgen i kursoppskriften, ikke en universell regel for alle sure gryteretter.'}},
    {title:{en:'Why there is nothing creamy in it', no:'Hvorfor det ikke er noe kremet i den'},
     body:{en:'Gongura is a fat-cutting ingredient, and goat is a fatty meat cooked on the bone. Yoghurt or coconut would soften exactly the edge the dish exists for. If the finished pot tastes too fierce, the answer is more onion or a longer rest, not dairy.',
           no:'Gongura er en råvare som skjærer gjennom fett, og geitekjøtt er fett kjøtt kokt på beinet. Yoghurt eller kokos ville dempet nettopp den kanten retten finnes for. Smaker den ferdige gryta for hissig, er svaret mer løk eller lengre hviletid, ikke meieriprodukter.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Goat on the bone is the right meat, and the bone matters because the gravy has nothing else to give it body.',
           no:'Geitekjøtt med bein er riktig kjøtt, og beinet betyr noe, for sausen har ikke noe annet å hente fylde fra. Geit og kje selges hos halalslaktere på Grønland i Oslo og i de fleste større byer; be om bog og lår i store biter. Norsk fårekjøtt tåler koketiden og smaker kraftig nok, mens lammekjøtt blir ferdig etter tre kvarter og smaker mildere. Gongura får du ikke fersk her. Indiske butikker fører den iblant frossen eller på glass under navnet gongura eller sorrel leaves; glassvarianten er allerede kokt og saltet, så bruk omtrent to tredeler av vekten, hopp over surringen og salt gryta forsiktig.'}}],
  variations:[
    {title:{en:'Gongura pachadi, from the same leaves', no:'Gongura pachadi, av de samme bladene'},
      body:{en:'Wilt the leaves the same way, grind them with fried dried chillies, garlic and salt, and finish with the same tempering. Refrigerate promptly and use within three days, or freeze small portions.',
            no:'Surr bladene på samme måte, mal dem med stekt tørket chili, hvitløk og salt, og avslutt med den samme temperingen. Sett raskt i kjøleskap og bruk innen tre dager, eller frys små porsjoner.'}},
    {title:{en:'Gongura pappu, without meat', no:'Gongura pappu, uten kjøtt'},
     body:{en:'Cook toor dal until it collapses, stir the wilted ground leaves through it and pour the same tempering over. This is what a Telugu household eats far more often than the mutton, and the leaf does the souring in place of tamarind.',
           no:'Kok toor dal til den faller fra hverandre, rør de surrede, malte bladene inn i den og hell den samme temperingen over. Dette er det en husholdning i Andhra spiser langt oftere enn kjøttretten, og bladet syrner i stedet for tamarinden.'}},
    {title:{en:'With chicken instead', no:'Med kylling i stedet'},
     body:{en:'Use thighs on the bone and cut the covered cooking to twenty-five minutes before the leaves go in. The dish works, but chicken has less fat for the acid to cut through, so it tastes sharper and thinner.',
           no:'Bruk lår med bein og kort koketiden under lokk ned til tjuefem minutter før bladene går i. Retten fungerer, men kylling har mindre fett for syren å skjære gjennom, så den smaker skarpere og tynnere.'}}]
},

{
  id:'avakaya', dish:'Avakaya', course:'side', lesson:2, serves:12, veg:true,
  time:{prep:30, cook:5}, hero:'avakaya', tags:['pickle','mango','mustard','refrigerated'],
  title:{en:'Avakaya', no:'Avakaya'},
  blurb:{en:'A small refrigerated adaptation of Andhra mango pickle with mustard, chilli, salt and sesame oil.',
         no:'En liten kjøleskapstilpasset variant av mangopickles fra Andhra med sennep, chili, salt og sesamolje.'},
  heroCaption:{en:'Firm green mango takes up the heat of chilli and the pungency of freshly ground mustard.',
               no:'Fast grønn mango tar opp styrken fra chili og skarpheten fra nymalt sennep.'},
  goesWith:[{en:'Hot rice with a spoonful of ghee', no:'Varm ris med en skje ghee'},
            {en:'Curd rice, at the end of a meal', no:'Ris med syrnet melk, sist i måltidet'}],
  headnote:{
    en:`<p>Avakaya is a seasonal Andhra pickle of unripe mango, mustard, chilli, salt and oil. Traditional long-keeping versions depend on established proportions and handling that this course has not laboratory-validated.</p>
<p>This recipe therefore makes a small refrigerator batch. Oil carries flavour and reduces contact with air, but it does not by itself make an untested pickle safe at room temperature. Refrigerate the jar as soon as it is mixed and every time after serving.</p>
<p>Use a clean utensil and discard the batch if you see mould, fizzing, a bulging lid or slime, or notice an abnormal smell. Make only what you expect to eat within two weeks.</p>`,
    no:`<p>Avakaya er en sesongpickles fra Andhra av umoden mango, sennep, chili, salt og olje. Tradisjonelle varianter med lang holdbarhet bygger på innarbeidede mengder og rutiner som dette kurset ikke har laboratorietestet.</p>
<p>Denne oppskriften lager derfor en liten kjøleskapsporsjon. Oljen bærer smak og reduserer kontakt med luft, men gjør ikke alene en uprøvd pickles trygg i romtemperatur. Sett glasset i kjøleskapet straks det er blandet og etter hver servering.</p>
<p>Bruk et rent redskap, og kast innholdet ved mugg, brusing, utbulende lokk, slim eller unormal lukt. Lag bare det du regner med å spise innen to uker.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:500, u:'g', n:{en:'hard unripe mango', no:'hard umoden mango'}, note:{en:'weighed after cutting the flesh safely from the stone', no:'veid etter at fruktkjøttet er skåret trygt fra steinen'}},
    {q:50, u:'g', n:{en:'black or brown mustard seed', no:'svarte eller brune sennepsfrø'}},
    {q:40, u:'g', n:{en:'hot chilli powder', no:'sterkt chilipulver'}},
    {q:35, u:'g', n:{en:'salt', no:'salt'}},
    {q:3, u:'g', n:{en:'fenugreek seeds', no:'bukkehornkløverfrø'}},
    {q:120, u:'ml', n:{en:'sesame or groundnut oil', no:'sesamolje eller jordnøttolje'}},
   ]}],
  steps:[
    {en:'Wash the mangoes under running water and dry them. With a stable board and a sharp knife, cut the flesh away from the hard stone; do not chop through the stone.',
     no:'Vask mangoene under rennende vann og tørk dem. Bruk et stabilt brett og en skarp kniv til å skjære fruktkjøttet fra den harde steinen; ikke hakk gjennom steinen.'},
    {en:'Cut the mango flesh into bite-sized pieces and place them in a clean bowl.',
     no:'Skjær mangokjøttet i passe store biter og legg dem i en ren bolle.'},
    {en:'Toast the mustard and fenugreek briefly in a dry pan until fragrant. Cool, then grind them to a coarse powder.',
     no:'Rist sennepsfrø og bukkehornkløver kort i en tørr panne til de dufter. Avkjøl og mal dem grovt.'},
    {en:'Mix the ground spices, chilli powder and salt, then coat the mango evenly with the mixture.',
     no:'Bland de malte krydderne med chilipulver og salt, og vend mangoen jevnt i blandingen.'},
    {en:'Warm the oil just until fluid and fragrant, then let it cool until no longer hot. Mix it thoroughly through the mango.',
     no:'Varm oljen bare til den er flytende og dufter, og la den så kjølne til den ikke lenger er varm. Bland den grundig inn i mangoen.'},
    {en:'Transfer to a clean lidded jar and refrigerate immediately. Stir with a clean spoon after one day; begin tasting after two days and keep refrigerated.',
     no:'Ha blandingen i et rent glass med lokk og sett det straks i kjøleskapet. Rør med en ren skje etter ett døgn; begynn å smake etter to døgn og oppbevar videre i kjøleskapet.'}],
  notes:[
    {title:{en:'Why this version stays cold', no:'Hvorfor denne varianten holdes kald'},
     body:{en:'Salt, acidity and oil all affect spoilage, but the safety of a shelf-stable pickle depends on measured formulation and process. This course recipe has not been validated for room-temperature storage, so refrigeration is part of the method.',
           no:'Salt, syre og olje påvirker holdbarheten, men en lagringsstabil pickles krever målte mengder og en prøvd prosess. Kursoppskriften er ikke validert for romtemperatur, og derfor er kjøleskapet en del av metoden.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Choose firm sour green mango sold for pickling. Indian and other South Asian grocers may label it raw mango or kachi keri. Use pure hot chilli powder rather than a blended seasoning, and use food-grade sesame or groundnut oil.',
           no:'Velg fast, sur grønn mango som selges til pickles. Indiske og andre sørasiatiske butikker kan merke den raw mango eller kachi keri. Bruk rent, sterkt chilipulver i stedet for en krydderblanding, og bruk sesam- eller jordnøttolje beregnet på mat.'}}],
  variations:[
    {title:{en:'Without the garlic', no:'Uten hvitløken'},
      body:{en:'Traditional recipes differ over garlic. This refrigerator adaptation leaves it out so the mango, mustard and chilli remain the focus.',
            no:'Tradisjonelle oppskrifter er ulike når det gjelder hvitløk. Denne kjøleskapsvarianten sløyfer den slik at mango, sennep og chili står i sentrum.'}},
    {title:{en:'Bellam avakaya, with jaggery', no:'Bellam avakaya, med jaggery'},
      body:{en:'Mix a little grated jaggery into the spice blend for a sweeter variation. Keep it refrigerated under the same storage rules.',
            no:'Bland litt revet jaggery i krydderblandingen for en søtere variant. Oppbevar den i kjøleskapet etter de samme reglene.'}},
    {title:{en:'A smaller jar', no:'Et mindre glass'},
      body:{en:'Use the serving control to halve the batch. A small jar is easier to cool, handle cleanly and finish within two weeks.',
            no:'Bruk porsjonsvelgeren til å halvere mengden. Et lite glass er enklere å kjøle, håndtere rent og spise opp innen to uker.'}}]
},

];
