/* Masala Dabba — recipes for Andhra & Telangana (IN-AND). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-AND'] = [

{
  id:'pulihora', dish:'Pulihora', course:'rice', lesson:2, serves:4, veg:true,
  time:{prep:25, cook:35}, hero:'pulihora', tags:['rice','tamarind','temple'],
  title:{en:'Pulihora', no:'Pulihora'},
  blurb:{en:'Tamarind cooked down in sesame oil until it thickens, then folded through cold rice and left to stand.',
         no:'Tamarind kokt inn i sesamolje til den tykner, vendt inn i kald ris og satt til side en stund.'},
  heroCaption:{en:'Peanuts, split chickpeas and curry leaves stay visible through the rice. The colour is turmeric and cooked-down tamarind, not chilli.',
               no:'Jordnøtter, delte kikerter og karriblad ligger synlig i risen. Fargen kommer fra gurkemeie og innkokt tamarind, ikke fra chili.'},
  goesWith:[{en:'Plain yoghurt, cold', no:'Naturell yoghurt, kald'},
            {en:'A fried pappadam', no:'En stekt pappadam'}],
  headnote:{
    en:`<p>Pulihora is one of the few Indian rice dishes that is better an hour after you finish it, and that is not a courtesy. The paste has to work its way into every grain, and the moment it goes in nothing has happened yet. Cooks in Andhra make it in the morning for the afternoon, and temples make it in quantity because it keeps a day without a fridge.</p>
<p>Two things separate a good one from a merely sour one. The tamarind is not stirred in raw: it is cooked down in sesame oil with the tempering until it darkens and thickens into a paste that holds a line when you draw a spoon through it. And a small amount of sesame and fenugreek is roasted and ground in at the very end, which gives the dish the nutty bottom note that a plain tamarind rice lacks.</p>
<p>The third rule is about temperature. The rice must be completely cold. Fold anything through warm rice and the grains break down into paste, and no amount of care later puts them back.</p>`,
    no:`<p>Pulihora er en av de få indiske risrettene som er bedre en time etter at du er ferdig, og det er ikke høflighet. Pastaen må arbeide seg inn i hvert korn, og i det øyeblikket den går i, har ingenting skjedd ennå. Kokker i Andhra lager den om morgenen til ettermiddagen, og templene lager den i store mengder fordi den holder seg et døgn uten kjøleskap.</p>
<p>To ting skiller en god pulihora fra en som bare er sur. Tamarinden røres ikke inn rå. Den kokes ned i sesamolje sammen med temperingen til den mørkner og tykner så mye at sporet etter skjeen blir stående. Og en liten mengde sesam og bukkehornkløver ristes og males inn helt til slutt, og det gir retten den nøtteaktige bunnen en vanlig tamarindris mangler.</p>
<p>Den tredje regelen handler om temperatur. Risen må være helt kald. Vender du noe inn i varm ris, går kornene i oppløsning, og ingen forsiktighet senere henter dem tilbake.</p>`},
  ingredients:[
   {group:{en:'The rice', no:'Risen'}, items:[
    {q:300, u:'g', n:{en:'short-grain or medium-grain rice', no:'kort- eller mellomkornet ris'}, note:{en:'rinsed until the water runs clear', no:'skylt til vannet er klart'}},
    {q:600, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15, u:'ml', n:{en:'sesame oil', no:'sesamolje'}, note:{en:'for forking through the hot rice', no:'til å vende inn i den varme risen'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The tamarind paste', no:'Tamarindpastaen'}, items:[
    {q:60, u:'g', n:{en:'tamarind block', no:'tamarind i blokk'}},
    {q:250, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub', note:{en:'for soaking the tamarind', no:'til å bløtlegge tamarinden i'}},
    {q:60, u:'ml', n:{en:'sesame oil', no:'sesamolje'}},
    {q:5, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:25, u:'g', n:{en:'raw peanuts', no:'usaltede jordnøtter'}},
    {q:15, u:'g', n:{en:'split chickpeas (chana dal)', no:'delte kikerter (chana dal)'}},
    {q:10, u:'g', n:{en:'split black gram (urad dal)', no:'delt urad dal'}},
    {q:4, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half', note:{en:'broken in half', no:'brukket i to'}},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'flekket på langs'}},
    {q:20, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:1, u:'g', n:{en:'asafoetida', no:'asafoetida'}, scale:'none'},
   ]},
   {group:{en:'The roasted powder', no:'Det ristede pulveret'}, items:[
    {q:10, u:'g', n:{en:'sesame seeds', no:'sesamfrø'}},
    {q:2, u:'g', n:{en:'fenugreek seeds', no:'bukkehornkløverfrø'}},
    {q:2, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
   ]}],
  steps:[
    {en:'Cook the rinsed rice in the water with a little salt until the grains are just done and still separate, then tip it out into a wide tray.',
     no:'Kok den skylte risen i vannet med litt salt til kornene akkurat er ferdige og fortsatt ligger hver for seg, og hell den så ut i et vidt fat.'},
    {en:'Fork the sesame oil through the hot rice and spread it out in a thin layer to cool completely. Do not cover it while it cools.',
     no:'Vend sesamoljen inn i den varme risen med en gaffel og bre den utover i et tynt lag så den kjøler seg helt. Ikke dekk den til mens den kjøler seg.'},
    {en:'Soak the tamarind in the hot water for twenty minutes, squeeze it out with your fingers and strain the extract. Throw away the fibres and the seeds.',
     no:'Bløtlegg tamarinden i det varme vannet i tjue minutter, klem den ut med fingrene og sil ekstraktet. Kast trevlene og kjernene.'},
    {en:'Dry-roast the sesame, the fenugreek and the chillies for the powder in a small pan until the sesame starts to jump, then grind them coarse and set the powder aside.',
     no:'Tørrist sesamen, bukkehornkløveren og chilien til pulveret i en liten panne til sesamen begynner å hoppe. Mal dem grovt og sett pulveret til side.'},
    {en:'Heat the sesame oil in a heavy pan, add the mustard seed and wait for it to pop properly before anything else goes in.',
     no:'Varm sesamoljen i en tung panne, ha i sennepsfrøene og vent til de har sprettet ferdig før noe annet går i.'},
    {en:'Add the peanuts, the split chickpeas and the urad dal, and fry over a medium flame until the lentils turn golden and the peanuts colour.',
     no:'Ha i jordnøttene, de delte kikertene og urad dalen, og stek på middels varme til linsene blir gylne og jordnøttene får farge.'},
    {en:'Add the dried chillies, the green chillies and the curry leaves. Stand back while they crackle, then pull the pan off the heat and stir in the turmeric and the asafoetida.',
     no:'Ha i de tørkede chiliene, de grønne chiliene og karribladene. Hold deg unna mens det knitrer, trekk så pannen av platen og rør inn gurkemeien og asafoetidaen.'},
    {en:'Return the pan to a medium flame, pour in the tamarind extract and salt it. Simmer until it darkens and thickens enough to hold a line when a spoon is drawn through it, fifteen to twenty minutes.',
     no:'Sett pannen tilbake på middels varme, hell i tamarindekstraktet og salt. La det småkoke til det mørkner og tykner så mye at sporet etter skjeen blir stående, femten til tjue minutter.'},
    {en:'Take the paste off the heat, stir in the roasted powder and leave it to cool to room temperature.',
     no:'Ta pastaen av platen, rør inn det ristede pulveret og la den kjøle seg til romtemperatur.'},
    {en:'Fold the paste through the cold rice a little at a time, tasting as you go, until every grain is coloured. Cover it and leave it to stand for an hour before eating.',
     no:'Vend pastaen inn i den kalde risen litt om gangen og smak underveis, til hvert korn har fått farge. Dekk til og la den stå i en time før du spiser.'}],
  notes:[
    {title:{en:'Why the rice has to be cold', no:'Hvorfor risen må være kald'},
     body:{en:'Hot rice is still soft and full of free starch on the surface of every grain, and stirring anything through it breaks the grains and glues them together. Cold rice has firmed up, so the paste coats each grain instead of dissolving into it. This is the same reason a fried rice starts with yesterday\'s.',
           no:'Varm ris er fortsatt myk og har fri stivelse på overflaten av hvert korn, så rører du noe inn i den, går kornene i stykker og klistrer seg sammen. Kald ris har stivnet, så pastaen legger seg rundt hvert korn i stedet for å løse seg opp i det. Det er den samme grunnen til at stekt ris lages av gårsdagens ris.'}},
    {title:{en:'Why the tamarind is cooked down', no:'Hvorfor tamarinden kokes ned'},
     body:{en:'Raw tamarind extract is mostly water, and stirred into rice it makes the grains wet and tastes flat. Cooking it in oil drives the water off, concentrates the acid and lets the fat carry the tempering into the paste. It also makes it keep: a properly reduced paste lasts a fortnight in the fridge and can be made ahead.',
           no:'Rått tamarindekstrakt er for det meste vann, og rørt inn i ris gjør det bare kornene våte og smaker flatt. Kokes det i olje, damper vannet av, syren konsentreres, og fettet bærer temperingen inn i pastaen. Den holder seg også: en skikkelig innkokt pasta varer fjorten dager i kjøleskapet og kan lages på forhånd.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy tamarind as a pressed block with the seeds still in it and soak it yourself, because that is what these quantities are written for.',
           no:'Kjøp tamarind som presset blokk med kjernene i og bløtlegg den selv, for det er det disse mengdene er skrevet for. Konsentratet på glass er allerede kokt inn og er mye sterkere, så bruk under en femdel så mye og spe med vann. «Tamarind paste» i dagligvaren er ofte spedd ut med vann og salt og gir en tynn og salt rett. Karriblad får du ferske eller frosne i indiske butikker på Grønland i Oslo; de tørkede gir nesten ingenting. Bruk kortkornet ris, ikke basmati, for basmatikornet er for tynt og tørt til å bære pastaen. Asafoetida selges som hing og lukter kraftig; en knivsodd er nok.'}}],
  variations:[
    {title:{en:'Nimmakaya pulihora, with lemon', no:'Nimmakaya pulihora, med sitron'},
     body:{en:'Make the same tempering, leave the tamarind out entirely and stir lemon juice into the rice off the heat, with plenty of turmeric. The dish turns yellow and much fresher, and it is what many households make when the tamarind has run out.',
           no:'Lag den samme temperingen, sløyf tamarinden helt og rør sitronsaft inn i risen med kjelen av platen, sammen med rikelig gurkemeie. Retten blir gul og mye friskere, og det er den mange husholdninger lager når tamarinden er slutt.'}},
    {title:{en:'Mamidikaya pulihora, with raw mango', no:'Mamidikaya pulihora, med umoden mango'},
     body:{en:'In spring, grated hard green mango replaces the tamarind. It goes into the tempering and cooks for only a few minutes, because it is meant to stay sharp rather than break down.',
           no:'Om våren erstatter revet hard grønn mango tamarinden. Den går i temperingen og koker bare noen få minutter, for den skal holde seg skarp og ikke falle fra hverandre.'}},
    {title:{en:'With more lentils', no:'Med mer linser'},
     body:{en:'Temple kitchens are generous with the peanuts and the split chickpeas, so that there is something to bite in every mouthful. Doubling them changes the dish more than doubling the tamarind would.',
           no:'Tempelkjøkken er rause med jordnøttene og de delte kikertene, så du får noe å bite i hver munnfull. Dobler du dem, endrer det retten mer enn en dobling av tamarinden ville gjort.'}}]
},

{
  id:'pesarattu', dish:'Pesarattu', course:'breakfast', lesson:2, serves:4, veg:true,
  time:{prep:20, cook:25}, hero:'pesarattu', tags:['breakfast','green gram','unfermented'],
  title:{en:'Pesarattu', no:'Pesarattu'},
  blurb:{en:'A green crepe of whole green gram, ground and cooked the same day, with onion pressed into the surface.',
         no:'En grønn pannekake av hele grønne mungbønner, malt og stekt samme dag, med løk presset ned i overflaten.'},
  heroCaption:{en:'The colour comes from the skins of the whole green gram. A batter made with the split yellow lentil would be pale.',
               no:'Fargen kommer fra skallet på de hele grønne mungbønnene. En røre av den delte gule linsen ville blitt blek.'},
  goesWith:[{en:'Ginger and tamarind chutney', no:'Chutney av ingefær og tamarind'},
            {en:'Strong coffee or tea', no:'Sterk kaffe eller te'}],
  headnote:{
    en:`<p>Everything about pesarattu looks like a dosa and almost nothing about it works like one. A dosa batter is rice and urad dal, ground apart and left overnight, and wild bacteria on the lentil raise it and sour it. Pesarattu is whole green gram, ground with ginger and chilli, and used within the hour. Nothing ferments, and nothing is supposed to.</p>
<p>That difference is worth understanding before you cook it, because it changes what waiting does. Leaving a dosa batter out improves it. Leaving this one out makes it sour without making it lighter, because green gram carries neither the bacteria nor the protein that traps gas in urad dal. If the batter has stood overnight, you have a worse breakfast, not a better one.</p>
<p>The crepe that comes off the griddle is green, a little chewy, and tastes clearly of the pulse rather than of fermentation. It is savoury enough to eat on its own, and in Andhra it almost never is: a sharp ginger chutney comes with it, and the two together are the standard breakfast of the coastal towns.</p>`,
    no:`<p>Alt ved pesarattu ser ut som en dosa, og nesten ingenting ved den fungerer som en. En dosarøre er ris og urad dal, malt hver for seg og satt til side natten over, og villbakterier på linsen hever og syrner den. Pesarattu er hele grønne mungbønner, malt med ingefær og chili, og brukt i løpet av timen. Ingenting gjærer, og ingenting skal gjære.</p>
<p>Den forskjellen er verdt å forstå før du lager retten, for den endrer hva ventingen gjør. En dosarøre blir bedre av å stå. Denne røren blir bare sur uten å bli lettere, for mungbønner har verken bakteriene eller proteinet som fanger gass i urad dal. Har røren stått natten over, har du en dårligere frokost og ikke en bedre.</p>
<p>Pannekaken som kommer av takken, er grønn og litt seig, og den smaker tydelig av belgfrukten og ikke av gjæring. Den er smaksrik nok til å spises alene, og i Andhra spises den nesten aldri slik: en skarp ingefærchutney følger med, og sammen er de standardfrokosten i byene langs kysten.</p>`},
  ingredients:[
   {group:{en:'The batter', no:'Røren'}, items:[
    {q:300, u:'g', n:{en:'whole green gram (green moong)', no:'hele grønne mungbønner'}, note:{en:'soaked 6 hours or overnight', no:'bløtlagt i 6 timer eller over natten'}},
    {q:50, u:'g', n:{en:'raw rice', no:'ukokt ris'}, note:{en:'soaked with the green gram', no:'bløtlagt sammen med mungbønnene'}},
    {q:30, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'peeled, roughly chopped', no:'skrelt og grovhakket'}},
    {q:4, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:4, u:'g', n:{en:'cumin seed', no:'spisskummen'}},
    {q:180, u:'ml', n:{en:'cold water', no:'kaldt vann'}, scale:'sub', note:{en:'added a little at a time while grinding', no:'has i litt om gangen mens du maler'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'On the griddle', no:'På takken'}, items:[
    {q:2, u:'', n:{en:'onions', no:'løk'}, round:'half', note:{en:'chopped very fine', no:'finhakket'}},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
    {q:3, u:'g', n:{en:'cumin seed', no:'spisskummen'}},
    {u:'', n:{en:'sesame oil for the griddle', no:'sesamolje til takken'}, scale:'none'},
   ]}],
  steps:[
    {en:'Soak the green gram and the rice together in plenty of cold water for six hours or overnight, then drain them well.',
     no:'Bløtlegg mungbønnene og risen sammen i rikelig kaldt vann i seks timer eller over natten, og hell så godt av vannet.'},
    {en:'Grind them with the ginger, the green chillies, the cumin, salt and the cold water to a batter slightly thicker than double cream. It should pour off the ladle in a ribbon rather than run.',
     no:'Kjør dem sammen med ingefæren, de grønne chiliene, spisskummenen, salt og det kalde vannet til en røre som er litt tykkere enn kremfløte. Den skal renne av sleiva som et bånd og ikke som vann.'},
    {en:'Let the batter stand for twenty minutes while you chop the onion and the coriander. Do not leave it any longer, and never overnight.',
     no:'La røren stå i tjue minutter mens du hakker løken og korianderen. Ikke la den stå lenger, og aldri over natten.'},
    {en:'Heat a flat iron griddle or a heavy frying pan over a medium flame until a drop of water skitters across it and disappears.',
     no:'Varm en flat takke av støpejern eller en tung stekepanne på middels varme til en vanndråpe danser over den og forsvinner.'},
    {en:'Pour a ladle of batter into the middle and spread it outwards in a spiral with the back of the ladle, as thin as you can without tearing it.',
     no:'Hell en sleiv røre midt på og dra den utover i en spiral med baksiden av sleiva, så tynt du klarer uten at den revner.'},
    {en:'Drizzle a little oil round the rim, scatter chopped onion, coriander and cumin over the surface, and press them in lightly with a flat spoon.',
     no:'Drypp litt olje langs kanten, strø hakket løk, koriander og spisskummen over overflaten og trykk dem lett ned med en flat skje.'},
    {en:'Cook for two to three minutes, until the underside is brown in patches and the edges lift away from the griddle on their own.',
     no:'Stek i to til tre minutter, til undersiden er brun i flekker og kantene løsner fra takken av seg selv.'},
    {en:'Fold it in half or roll it up, and take it to the table at once. A pesarattu goes soft within a few minutes of leaving the pan.',
     no:'Brett den i to eller rull den sammen, og sett den på bordet med en gang. En pesarattu blir myk få minutter etter at den forlater pannen.'},
    {en:'Wipe the griddle with a folded cloth before the next one. The surface has to be hot and dry each time, or the batter sticks and tears.',
     no:'Tørk av takken med en sammenbrettet klut før neste. Overflaten må være varm og tørr hver gang, ellers setter røren seg fast og revner.'}],
  notes:[
    {title:{en:'Why waiting does not help this batter', no:'Hvorfor venting ikke hjelper på denne røren'},
     body:{en:'Urad dal carries the wild bacteria that raise a dosa batter and a protein that traps the gas they make. Green gram carries neither, so a pesarattu batter left out ferments a little, goes sour and stays just as dense. Grind it and cook it, and if you have soaked too much, cook the rest as thick pancakes and eat them the same day.',
           no:'Urad dal bærer villbakteriene som hever en dosarøre, og et protein som fanger gassen de lager. Mungbønner har ingen av delene, så en pesarattu-røre som blir stående, gjærer litt, blir sur og er like tung som før. Mal den og stek den, og har du bløtlagt for mye, stek resten som tykke pannekaker og spis dem samme dag.'}},
    {title:{en:'Why the onion goes on top and not in', no:'Hvorfor løken legges oppå og ikke i'},
     body:{en:'Onion stirred into the batter releases water as it heats, and the crepe steams instead of crisping. Pressed into the upper surface it browns in the open air while the underside cooks, and it stays where it was put when the crepe is folded.',
           no:'Løk som røres inn i røren, slipper vann når den varmes opp, og da damper pannekaken i stedet for å bli sprø. Trykker du den ned i den øvre flaten, bruner den seg i åpen luft mens undersiden steker, og den blir liggende der du la den når pannekaken brettes.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'The pulse has to be the whole green one with its skin on, not the split yellow moong dal sold beside it.',
           no:'Belgfrukten må være den hele grønne med skallet på, ikke den delte gule moong dalen som ofte står ved siden av. Hele grønne mungbønner selges i indiske butikker, i asiatiske butikker og i helsekost, og de er billige. Ferdig spirede mungbønner fra dagligvaren fungerer ikke, for spirene har brukt opp stivelsen røren trenger. En vanlig stavmikser klarer jobben, men en kraftig blender gir jevnere røre. En støpejernspanne som er godt innarbeidet, er det nærmeste du kommer en indisk takke.'}}],
  variations:[
    {title:{en:'MLA pesarattu, with upma inside', no:'MLA pesarattu, med upma inni'},
     body:{en:'Spread a layer of upma, coarse semolina cooked with onion and mustard seed, over one half of the crepe before folding it. The story says it was named for the legislators eating it near the assembly in Hyderabad, which is a good story rather than a documented one.',
           no:'Legg et lag upma, grov semule kokt med løk og sennepsfrø, over den ene halvdelen før du bretter. Historien vil ha det til at retten er oppkalt etter folkevalgte som spiste den nær delstatsforsamlingen i Hyderabad, og det er en god historie heller enn et dokumentert navn.'}},
    {title:{en:'Allam pachadi, the chutney it belongs with', no:'Allam pachadi, chutneyen som hører til'},
     body:{en:'Fry a large piece of ginger and a few dried chillies in sesame oil, grind them with tamarind, jaggery and salt, and temper the result with mustard seed and curry leaf. It is dark, sharp and sweet at once, and it keeps for a fortnight.',
           no:'Stek en stor bit ingefær og noen tørkede chili i sesamolje, mal dem med tamarind, jaggery og salt, og hell en tempering av sennepsfrø og karriblad over til slutt. Den blir mørk, skarp og søt på én gang, og den holder seg i fjorten dager.'}},
    {title:{en:'Thicker, as uttapam', no:'Tykkere, som uttapam'},
     body:{en:'Loosen the batter less, pour it out without spreading it and give it five minutes over a lower flame. You get a thick soft pancake instead of a thin crisp one, which suits the onion topping even better.',
           no:'Spe røren mindre, hell den ut uten å dra den utover og gi den fem minutter på lavere varme. Da får du en tykk og myk pannekake i stedet for en tynn og sprø, og det passer løken på toppen enda bedre.'}}]
},

{
  id:'bagara-baingan', dish:'Bagara baingan', course:'main', lesson:3, serves:4, veg:true,
  time:{prep:30, cook:50}, hero:'bagara-baingan', tags:['aubergine','peanut','Hyderabad'],
  title:{en:'Bagara baingan', no:'Bagara baingan'},
  blurb:{en:'Small aubergines fried whole and finished in a gravy thickened with roasted peanut, sesame and dry coconut.',
         no:'Små auberginer stekt hele og ferdigkokt i en saus jevnet med ristede jordnøtter, sesam og tørket kokos.'},
  heroCaption:{en:'The aubergines are slit into quarters but left joined at the stalk, so they hold their shape in the pot.',
               no:'Auberginene snittes i fire, men henger sammen ved stilken, så de holder fasongen i gryta.'},
  goesWith:[{en:'Plain rice, or a mildly spiced bagara khana', no:'Vanlig ris, eller en mildt krydret bagara khana'},
            {en:'Thinned yoghurt with onion', no:'Tynnet yoghurt med løk'}],
  headnote:{
    en:`<p>This is the dish that explains the Hyderabadi gravy. Nothing in it thickens with cream, yoghurt, flour or tomato. The body comes entirely from roasted peanut, sesame and dry coconut ground to a paste, and that paste is also most of the flavour. Mirchi ka salan, the thin chilli dish served beside a biryani, uses very nearly the same gravy, which tells you the paste is the recipe and the vegetable is a passenger.</p>
<p>The word bagara comes from baghar, the tempering, and it turns up all over this kitchen. In this dish it means the mustard seed and curry leaf that go into the oil before the onion, and everything after that builds on them.</p>
<p>The method has one real trap. Small aubergines collapse if you simmer them in gravy for half an hour, so they are fried apart until the skins blister and only returned to the pot at the very end. The gravy is made without them and is finished before they go back in.</p>`,
    no:`<p>Dette er retten som forklarer den hyderabadiske sausen. Ingenting i den jevnes med fløte, yoghurt, mel eller tomat. Fylden kommer utelukkende fra ristede jordnøtter, sesam og tørket kokos malt til pasta, og den pastaen er også mesteparten av smaken. Mirchi ka salan, den tynne chiliretten som serveres ved siden av en biryani, bruker nesten nøyaktig den samme sausen, og det forteller deg at pastaen er oppskriften og at grønnsaken er en passasjer.</p>
<p>Ordet bagara kommer av baghar, som betyr tempering, og det dukker opp over hele dette kjøkkenet. I denne retten betyr det sennepsfrøene og karribladene som går i oljen før løken, og alt som kommer etterpå, bygger på dem.</p>
<p>Metoden har én virkelig felle. Små auberginer faller sammen hvis de småkoker i saus i en halv time, så de stekes for seg til skallet blærer seg, og legges først tilbake i gryta helt til slutt. Sausen lages uten dem og er ferdig før de går i.</p>`},
  ingredients:[
   {group:{en:'The ground paste', no:'Den malte pastaen'}, items:[
    {q:60, u:'g', n:{en:'raw peanuts', no:'usaltede jordnøtter'}},
    {q:30, u:'g', n:{en:'sesame seeds', no:'sesamfrø'}},
    {q:30, u:'g', n:{en:'dry unsweetened coconut', no:'tørket usøtet kokos'}},
    {q:10, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:4, u:'g', n:{en:'cumin seed', no:'spisskummen'}},
   ]},
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:500, u:'g', n:{en:'small round aubergines', no:'små runde auberginer'}, note:{en:'about eight, with the stalks on', no:'omtrent åtte, med stilken på'}},
    {q:80, u:'ml', n:{en:'sesame or groundnut oil', no:'sesamolje eller jordnøttolje'}},
    {q:5, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
    {q:200, u:'g', n:{en:'onions', no:'løk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:15, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:15, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:8, u:'g', n:{en:'hot chilli powder', no:'sterkt chilipulver'}},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:30, u:'g', n:{en:'tamarind block', no:'tamarind i blokk'}},
    {q:200, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub', note:{en:'for soaking the tamarind', no:'til å bløtlegge tamarinden i'}},
    {q:400, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:8, u:'g', n:{en:'jaggery or palm sugar', no:'jaggery eller palmesukker'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Dry-roast the peanuts in a heavy pan over a medium flame until they colour and the skins loosen, then tip them onto a plate.',
     no:'Tørrist jordnøttene i en tung panne på middels varme til de får farge og skallet løsner, og hell dem så over på en tallerken.'},
    {en:'Roast the sesame, the coconut, the coriander and the cumin one after another in the same pan, each only until it smells, and add them to the peanuts.',
     no:'Rist sesamen, kokosen, korianderen og spisskummenen etter hverandre i den samme pannen, hver av dem bare til det dufter, og ha dem sammen med jordnøttene.'},
    {en:'Grind the roasted mixture with enough cold water to make a thick paste. Leave it slightly gritty rather than working it smooth.',
     no:'Mal den ristede blandingen med akkurat nok kaldt vann til en tykk pasta. La den være litt kornete i stedet for å kjøre den glatt.'},
    {en:'Soak the tamarind in the hot water for twenty minutes, squeeze it out and strain the extract.',
     no:'Bløtlegg tamarinden i det varme vannet i tjue minutter, klem den ut og sil ekstraktet.'},
    {en:'Cut each aubergine from the base into quarters, leaving the stalk end joined so the pieces stay together.',
     no:'Snitt hver aubergine i fire fra bunnen, men la enden med stilken henge sammen så bitene holder seg hele.'},
    {en:'Heat the oil in a wide pan and fry the aubergines over a medium flame, turning them, until the skins blister and darken all over. Lift them out and keep them.',
     no:'Varm oljen i en vid panne og stek auberginene på middels varme mens du snur dem, til skallet blærer seg og mørkner overalt. Løft dem ut og ta vare på dem.'},
    {en:'In the same oil, pop the mustard seed, add the curry leaves, then the onion, and fry the onion until it is properly brown, fifteen minutes or so.',
     no:'Sprett sennepsfrøene i den samme oljen, ha så i karribladene og deretter løken. Stek løken til den er skikkelig brun, omtrent femten minutter.'},
    {en:'Add the ginger and garlic and cook for a minute, then pull the pan off the heat and stir in the turmeric and the chilli powder so they colour the oil instead of burning.',
     no:'Ha i ingefæren og hvitløken og la det surre et minutt. Trekk så pannen av platen og rør inn gurkemeien og chilipulveret, så de farger oljen i stedet for å svi seg.'},
    {en:'Return the pan, stir in the ground paste and fry it for five minutes, scraping the base. Add the tamarind extract, the water, the jaggery and salt.',
     no:'Sett pannen tilbake, rør inn den malte pastaen og stek den i fem minutter mens du skraper bunnen. Ha i tamarindekstraktet, vannet, jaggeryen og salt.'},
    {en:'Simmer uncovered for fifteen minutes, until the gravy thickens and a rim of oil rises around the edge of the pan.',
     no:'La det småkoke uten lokk i femten minutter, til sausen tykner og det legger seg en rand av olje langs kanten av pannen.'},
    {en:'Slide the aubergines back in, spoon the gravy over them, cover and cook on the lowest heat for ten minutes. Let it stand for fifteen minutes before serving.',
     no:'Legg auberginene tilbake, øs sausen over dem, legg på lokk og la det stå på lavest mulig varme i ti minutter. La retten hvile i femten minutter før servering.'}],
  notes:[
    {title:{en:'Why the aubergines are fried apart', no:'Hvorfor auberginene stekes for seg'},
     body:{en:'A small aubergine is mostly air and water, and half an hour in liquid turns it to pulp that falls out of its own skin. Frying it first sets the skin and drives some of the water off, so it can take ten minutes in the gravy and still arrive whole on the plate.',
           no:'En liten aubergine er for det meste luft og vann, og en halvtime i væske gjør den til mos som faller ut av sitt eget skinn. Steker du den først, stivner skinnet og noe av vannet damper av, så den tåler ti minutter i sausen og likevel kommer hel på tallerkenen.'}},
    {title:{en:'Why the paste stays gritty', no:'Hvorfor pastaen skal være kornete'},
     body:{en:'The texture is the dish. Ground fine in a powerful blender, the peanut releases its oil and the gravy turns into something closer to a sauce that slides off the vegetable. Left a little coarse, it clings, and every spoonful carries the roasted flavour rather than dissolving it.',
           no:'Konsistensen er hele retten. Males pastaen fin i en kraftig blender, slipper jordnøtten oljen sin, og sausen blir glatt og glir av grønnsaken. Er den litt grov, henger den fast, og hver skjefull bærer den ristede smaken i stedet for å løse den opp.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Use unsalted raw peanuts and roast them yourself, because salted roasted nuts make the gravy far too salty.',
           no:'Bruk usaltede rå jordnøtter og rist dem selv, for ferdig saltede og ristede nøtter gjør sausen altfor salt. Små runde auberginer selges i indiske og asiatiske butikker på Grønland i Oslo; de store avlange fra dagligvaren fungerer i biter på fire centimeter, men de faller lettere fra hverandre. Tørket kokos må være den usøtede typen fra en indisk butikk, ikke kokosmasse til baking, som er tilsatt sukker. Jaggery finnes i indiske butikker, og mørk muscovado er den nærmeste erstatningen.'}}],
  variations:[
    {title:{en:'Mirchi ka salan', no:'Mirchi ka salan'},
     body:{en:'Make exactly the same gravy and put long mild green chillies in it instead of the aubergines, slit and fried the same way. Thin it a little more. This is what goes beside a Hyderabadi biryani, and it is sour and hot where the biryani is rich and dry.',
           no:'Lag nøyaktig den samme sausen og ha lange milde grønne chili i den i stedet for auberginene, flekket og stekt på samme måte. Spe sausen litt mer. Dette er det som står ved siden av en hyderabadisk biryani, og den er sur og sterk der biryanien er fyldig og tørr.'}},
    {title:{en:'With poppy seed', no:'Med valmuefrø'},
     body:{en:'Many households add white poppy seed to the roasted mixture. It makes the gravy paler, smoother and a little sweeter, and it is worth trying once you know what the plain version tastes like.',
           no:'Mange husholdninger har hvite valmuefrø i den ristede blandingen. Det gjør sausen lysere, glattere og litt søtere, og det er verdt å prøve når du vet hvordan den enkle utgaven smaker.'}}]
},

{
  id:'gongura-mamsam', dish:'Gongura mamsam', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:30, cook:100}, hero:'gongura-leaves', tags:['goat','gongura','sour'],
  title:{en:'Gongura mamsam, and what to do about the leaf', no:'Gongura mamsam, og hva du gjør med bladet'},
  heroCaption:{en:'Gongura brought in for sale. This is the ingredient the dish is named for, and it is the one thing in it that cannot be bought fresh in Norway.',
               no:'Gongura kjørt inn for salg. Det er denne råvaren retten er oppkalt etter, og det er den eneste tingen i den som ikke kan kjøpes fersk i Norge.'},
  blurb:{en:'Goat cooked down slowly and finished with wilted, ground roselle leaf, which is sour enough to need no tamarind at all.',
         no:'Geitekjøtt kokt langsomt ned og avsluttet med surrede og malte gongurablader, som er sure nok til at retten ikke trenger tamarind.'},
  goesWith:[{en:'Plain rice and nothing else', no:'Vanlig ris og ingenting annet'},
            {en:'A raw onion and a green chilli on the side', no:'Rå løk og en grønn chili ved siden av'}],
  headnote:{
    en:`<p>Start with the honest part. Fresh gongura is not sold in Norway, and nothing growing here is the same leaf. Indian shops sometimes carry it frozen or in a jar, already cooked and salted, and that is the realistic route: it gives you the right acidity and most of the flavour, and this recipe is written so you can use either. If you cannot find any of it, cook something else. Sorrel gives you the sourness without the taste, and spinach with lemon gives you neither, so a substitute here produces a different dish that should be called something else.</p>
<p>What does travel is the method, and it is worth having. The goat is cooked down almost to tenderness with onion, chilli and nothing sour at all. Only then does the ground gongura go in, for the last ten minutes. That order is not a detail. Acid slows meat down, so leaves added at the start leave you standing at the stove an hour longer with tough goat.</p>
<p>There is no yoghurt in this, no cream, no coconut and no tomato. The gravy is onion, the fat of the goat and the leaves, and it should taste sharp rather than rich. A tempering poured over at the end is the last thing that happens, and it is what lifts the smell of the finished pot.</p>`,
    no:`<p>La oss ta det ærlige først. Fersk gongura selges ikke i Norge, og ingenting som vokser her, er det samme bladet. Indiske butikker fører det av og til frossent eller på glass, ferdig kokt og saltet, og det er den realistiske veien: du får riktig syre og mesteparten av smaken, og oppskriften er skrevet så du kan bruke begge deler. Finner du ingenting av det, lag noe annet. Engsyre gir deg syren uten smaken, og spinat med sitron gir deg ingen av delene, så en erstatning her gir en annen rett som bør hete noe annet.</p>
<p>Metoden lar seg derimot flytte, og den er verdt å ha. Geitekjøttet kokes nesten mørt sammen med løk og chili og ingenting surt i det hele tatt. Først da går den malte gonguraen i, de siste ti minuttene. Rekkefølgen er ingen detalj. Syre gjør kjøtt seinere mørt, så blader som går i fra starten, lar deg stå en time lenger ved komfyren med seigt kjøtt.</p>
<p>Det går ingen yoghurt i denne retten, ingen fløte, ingen kokos og ingen tomat. Sausen består av løk, fettet fra geitekjøttet og bladene, og den skal smake skarp heller enn fyldig. En tempering som helles over til slutt, er det siste som skjer, og den løfter duften av den ferdige gryta.</p>`},
  ingredients:[
   {group:{en:'The meat', no:'Kjøttet'}, items:[
    {q:800, u:'g', n:{en:'goat on the bone', no:'geitekjøtt med bein'}, note:{en:'shoulder and leg, in large pieces', no:'bog og lår, i store biter'}},
    {q:60, u:'ml', n:{en:'sesame oil', no:'sesamolje'}},
    {q:250, u:'g', n:{en:'onions', no:'løk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:20, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:20, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:8, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:10, u:'g', n:{en:'hot chilli powder', no:'sterkt chilipulver'}},
    {q:8, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:350, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The leaves', no:'Bladene'}, items:[
    {q:300, u:'g', n:{en:'gongura leaves', no:'gongurablader'}, note:{en:'picked off the stems; see the sourcing note', no:'plukket av stilkene; se avsnittet om hvor du får tak i det'}},
    {q:4, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
   ]},
   {group:{en:'The tempering', no:'Temperingen'}, items:[
    {q:20, u:'ml', n:{en:'sesame oil', no:'sesamolje'}},
    {q:5, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:4, u:'g', n:{en:'cumin seed', no:'spisskummen'}},
    {q:15, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'sliced thin', no:'i tynne skiver'}},
    {q:5, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
   ]}],
  steps:[
    {en:'Heat the sesame oil in a heavy pan and fry the onion over a medium flame until it is properly dark brown, which takes a good fifteen minutes and cannot be hurried.',
     no:'Varm sesamoljen i en tung gryte og stek løken på middels varme til den er skikkelig mørkebrun. Det tar gode femten minutter og lar seg ikke forsere.'},
    {en:'Add the ginger and garlic pastes and fry until they stop smelling raw, about a minute.',
     no:'Ha i ingefær- og hvitløkspastaen og stek til de slutter å lukte rått, omtrent et minutt.'},
    {en:'Pull the pan off the heat, stir in the turmeric, the chilli powder and the coriander, then set it back on a medium flame.',
     no:'Trekk gryta av platen, rør inn gurkemeien, chilipulveret og korianderen, og sett den så tilbake på middels varme.'},
    {en:'Add the goat and salt it, and fry it hard for ten minutes, until the pieces have taken colour and the oil begins to separate out.',
     no:'Ha i geitekjøttet og salt det, og stek det hardt i ti minutter, til bitene har fått farge og oljen begynner å skille seg ut.'},
    {en:'Pour in the hot water, cover, and cook on the lowest heat until the meat gives easily under a spoon. Allow an hour to an hour and a half.',
     no:'Hell i det varme vannet, legg på lokk og la det stå på lavest mulig varme til kjøttet gir lett etter for en skje. Regn med en time til halvannen.'},
    {en:'While it cooks, pick the gongura leaves off their stems, wash them and shake them dry.',
     no:'Mens det koker, plukker du gongurabladene av stilkene, vasker dem og rister vannet av.'},
    {en:'Wilt the leaves in a dry pan over a medium flame until they collapse into a dark khaki mass, which takes five minutes at most. Do not add water or oil.',
     no:'Surr bladene i en tørr panne på middels varme til de faller sammen til en mørk, olivengrønn masse. Det tar høyst fem minutter. Ikke ha i vann eller olje.'},
    {en:'Grind the wilted leaves coarsely with two of the green chillies. Leave some texture in it rather than making a purée.',
     no:'Mal de surrede bladene grovt sammen med to av de grønne chiliene. La det være litt tyggemotstand igjen i stedet for å lage puré.'},
    {en:'Stir the ground gongura and the remaining slit chillies into the meat and cook uncovered for ten minutes. Taste it now, and remember that it goes on sharpening as it stands.',
     no:'Rør den malte gonguraen og resten av de flekkede chiliene inn i kjøttet og la det koke uten lokk i ti minutter. Smak nå, og husk at retten fortsetter å bli skarpere mens den står.'},
    {en:'In a small pan, heat the oil for the tempering, pop the mustard seed, then add the cumin, the sliced garlic, the dried chillies and the curry leaves and let them darken.',
     no:'Varm oljen til temperingen i en liten panne, sprett sennepsfrøene, og ha så i spisskummenen, hvitløksskivene, de tørkede chiliene og karribladene og la dem mørkne.'},
    {en:'Pour the tempering over the pot, cover it at once, and leave it for ten minutes before serving with rice.',
     no:'Hell temperingen over gryta, legg straks på lokket, og la den stå i ti minutter før du serverer med ris.'}],
  notes:[
    {title:{en:'Why the leaves go in last', no:'Hvorfor bladene går i sist'},
     body:{en:'Acid firms the connective tissue in meat and slows the collagen down, so a pot soured at the start can simmer for hours and still be tough. Cooking the goat in plain water first and souring it afterwards gets you tender meat and a sharp gravy in the same pot, and the same rule holds for tomato and tamarind in any braise.',
           no:'Syre strammer bindevevet i kjøtt og gjør at kollagenet løser seg langsommere, så en gryte som syrnes fra starten, kan koke i timevis og likevel være seig. Koker du geitekjøttet i rent vann først og syrner det etterpå, får du mørt kjøtt og en skarp saus i samme gryte, og den samme regelen gjelder tomat og tamarind i enhver langtidskokt rett.'}},
    {title:{en:'Why there is nothing creamy in it', no:'Hvorfor det ikke er noe kremet i den'},
     body:{en:'Gongura is a fat-cutting ingredient, and goat is a fatty meat cooked on the bone. Yoghurt or coconut would soften exactly the edge the dish exists for. If the finished pot tastes too fierce, the answer is more onion or a longer rest, not dairy.',
           no:'Gongura er en råvare som skjærer gjennom fett, og geitekjøtt er fett kjøtt kokt på beinet. Yoghurt eller kokos ville dempet nettopp den kanten retten finnes for. Smaker den ferdige gryta for hissig, er svaret mer løk eller lengre hviletid, ikke meieriprodukter.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Goat on the bone is the right meat, and the bone matters because the gravy has nothing else to give it body.',
           no:'Geitekjøtt med bein er riktig kjøtt, og beinet betyr noe, for sausen har ikke noe annet å hente fylde fra. Geit og kje selges hos halalslaktere på Grønland i Oslo og i de fleste større byer; be om bog og lår i store biter. Norsk fårekjøtt tåler koketiden og smaker kraftig nok, mens lammekjøtt blir ferdig etter tre kvarter og smaker mildere. Gongura får du ikke fersk her. Indiske butikker fører den iblant frossen eller på glass under navnet gongura eller sorrel leaves; glassvarianten er allerede kokt og saltet, så bruk omtrent to tredeler av vekten, hopp over surringen og salt gryta forsiktig.'}}],
  variations:[
    {title:{en:'Gongura pachadi, from the same leaves', no:'Gongura pachadi, av de samme bladene'},
     body:{en:'Wilt the leaves the same way, then grind them with fried dried chillies, garlic and salt and finish with the same tempering. You get the relish rather than the meat dish, it keeps a week in the fridge, and a teaspoon of it flavours a whole plate of rice.',
           no:'Surr bladene på samme måte, mal dem så med stekt tørket chili, hvitløk og salt, og avslutt med den samme temperingen. Da får du relishen i stedet for kjøttretten. Den holder seg en uke i kjøleskapet, og en teskje av den smaksetter en hel tallerken ris.'}},
    {title:{en:'Gongura pappu, without meat', no:'Gongura pappu, uten kjøtt'},
     body:{en:'Cook toor dal until it collapses, stir the wilted ground leaves through it and pour the same tempering over. This is what a Telugu household eats far more often than the mutton, and the leaf does the souring in place of tamarind.',
           no:'Kok toor dal til den faller fra hverandre, rør de surrede, malte bladene inn i den og hell den samme temperingen over. Dette er det en husholdning i Andhra spiser langt oftere enn kjøttretten, og bladet syrner i stedet for tamarinden.'}},
    {title:{en:'With chicken instead', no:'Med kylling i stedet'},
     body:{en:'Use thighs on the bone and cut the covered cooking to twenty-five minutes before the leaves go in. The dish works, but chicken has less fat for the acid to cut through, so it tastes sharper and thinner.',
           no:'Bruk lår med bein og kort koketiden under lokk ned til tjuefem minutter før bladene går i. Retten fungerer, men kylling har mindre fett for syren å skjære gjennom, så den smaker skarpere og tynnere.'}}]
},

{
  id:'avakaya', dish:'Avakaya', course:'side', lesson:2, serves:12, veg:true,
  time:{prep:75, cook:0}, hero:'avakaya', tags:['pickle','mango','mustard'],
  title:{en:'Avakaya', no:'Avakaya'},
  blurb:{en:'The Andhra mango pickle: hard green mango, ground mustard, chilli, salt and enough oil to stand over the top all year.',
         no:'Mangopicklesen fra Andhra: hard grønn mango, malt sennep, chili, salt og nok olje til at den står over picklesen hele året.'},
  heroCaption:{en:'Every piece keeps a fragment of the hard inner shell, and the whole jar sits under a layer of oil that is never allowed to break.',
               no:'Hver bit beholder en flis av det harde indre skallet, og hele glasset står under et lag olje som aldri får brytes.'},
  goesWith:[{en:'Hot rice with a spoonful of ghee', no:'Varm ris med en skje ghee'},
            {en:'Curd rice, at the end of a meal', no:'Ris med syrnet melk, sist i måltidet'}],
  headnote:{
    en:`<p>Avakaya is made once a year and eaten for a year, and everything about it follows from that. Ava is mustard and kaya is an unripe fruit, and the pickle is exactly those two things plus chilli, salt and a great deal of oil. It is not preserved by vinegar, by sugar or by heat. It is preserved by salt drawing water out of the mango and by a standing layer of oil that keeps the air off.</p>
<p>This is the most useful practical passage in the whole module, because it is also the easiest to get wrong. Three things ruin a jar, and all three are avoidable. A mango that is not hard enough turns to mush by August. A drop of water anywhere in the process starts mould. And a jar whose oil level drops below the pickle spoils from the top down.</p>
<p>Make it in May, when the hard sour mangoes are in the shops, and give it three weeks before you open it properly. It is fiercely hot and fiercely salty on purpose: a teaspoon is a serving, eaten with hot rice and ghee, and the ghee is not optional.</p>`,
    no:`<p>Avakaya lages én gang i året og spises i et år, og alt ved den følger av det. Ava betyr sennep og kaya en umoden frukt, og picklesen er nøyaktig de to tingene, i tillegg til chili, salt og svært mye olje. Den konserveres ikke av eddik, sukker eller varme. Den konserveres av at saltet trekker vann ut av mangoen, og av et lag olje som står over og holder lufta unna.</p>
<p>Dette er den mest nyttige praktiske delen i hele modulen, nettopp fordi den også er den letteste å gjøre feil. Tre ting ødelegger et glass, og alle tre lar seg unngå. En mango som ikke er hard nok, er mos i august. En vanndråpe hvor som helst i prosessen starter mugg. Og et glass der oljen synker under picklesen, ødelegges ovenfra og ned.</p>
<p>Lag den i mai, når de harde sure mangoene er i butikkene, og gi den tre uker før du åpner den for alvor. Den er svært sterk og svært salt med vilje: en teskje er en porsjon, spist med varm ris og ghee, og gheen er ikke valgfri.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:1000, u:'g', n:{en:'hard unripe mango', no:'hard umoden mango'}, note:{en:'two large ones, rock hard and sour', no:'to store, steinharde og sure'}},
    {q:150, u:'g', n:{en:'black or brown mustard seed', no:'svarte eller brune sennepsfrø'}},
    {q:150, u:'g', n:{en:'hot chilli powder', no:'sterkt chilipulver'}},
    {q:150, u:'g', n:{en:'coarse salt', no:'grovt salt'}},
    {q:5, u:'g', n:{en:'fenugreek seeds', no:'bukkehornkløverfrø'}},
    {q:400, u:'ml', n:{en:'sesame or groundnut oil', no:'sesamolje eller jordnøttolje'}},
    {q:30, u:'g', n:{en:'garlic cloves', no:'hvitløksfedd'}, note:{en:'peeled and left whole; optional', no:'skrelt og hele; valgfritt'}},
   ]}],
  steps:[
    {en:'Choose mangoes that are rock hard and sour, with a firm stone inside. One that gives under your thumb will not survive the year, however good it tastes now.',
     no:'Velg mangoer som er steinharde og sure, med fast stein inni. En som gir etter for tommelen, overlever ikke året, uansett hvor god den smaker nå.'},
    {en:'Wash them, wipe them completely dry with a cloth and leave them in the air for an hour. From here on, every surface, bowl, knife and hand has to be dry.',
     no:'Vask dem, tørk dem helt tørre med en klut og la dem ligge i lufta en time. Fra nå av må hver eneste flate, bolle, kniv og hånd være tørr.'},
    {en:'Cut each mango through the stone with a heavy knife into large pieces, so that every piece keeps a fragment of the hard inner shell attached to it.',
     no:'Hakk hver mango tvers gjennom steinen med en tung kniv, i store biter, slik at hver bit beholder en flis av det harde indre skallet.'},
    {en:'Scrape the soft white kernel out of the middle of each shell fragment and throw it away. It holds water and it is the first thing to spoil.',
     no:'Skrap den myke hvite kjernen ut av midten av hver flis av skallet og kast den. Den holder på vann og er det første som blir dårlig.'},
    {en:'Wipe the cut pieces dry with a cloth and spread them out for half an hour. Any juice on the surface has to go.',
     no:'Tørk de oppskårne bitene med en klut og bre dem utover i en halvtime. All saft på overflaten må bort.'},
    {en:'Dry the mustard seed and the fenugreek in the sun or in the oven at its lowest setting, then grind each of them to a coarse powder. Neither should be ground fine.',
     no:'Tørk sennepsfrøene og bukkehornkløveren i sola eller i stekeovnen på laveste innstilling, og mal dem så hver for seg til et grovt pulver. Ingen av dem skal males fint.'},
    {en:'Mix the mustard powder, the chilli powder, the ground fenugreek and the salt in a wide dry bowl until the colour is completely even.',
     no:'Bland sennepspulveret, chilipulveret, den malte bukkehornkløveren og saltet i en vid, tørr bolle til fargen er helt jevn.'},
    {en:'Turn the mango pieces through the powder with a dry hand until every surface is coated, then fold in the garlic if you are using it.',
     no:'Vend mangobitene i pulveret med en tørr hånd til hver flate er dekket, og bland så inn hvitløken hvis du bruker den.'},
    {en:'Pour in most of the oil and mix again. The mixture should look wet and heavy rather than dusty, and it should hold together when you press it.',
     no:'Hell i mesteparten av oljen og bland igjen. Blandingen skal se våt og tung ut i stedet for støvete, og den skal henge sammen når du klemmer på den.'},
    {en:'Pack it into a dry glass or glazed ceramic jar, press it down firmly, and pour the rest of the oil over so that a clear layer stands above the pickle. Cover it with a cloth and a lid.',
     no:'Pakk den i et tørt glass eller en glassert leirkrukke, trykk den godt ned, og hell resten av oljen over så det står et klart lag over picklesen. Dekk til med en klut og et lokk.'},
    {en:'Leave it somewhere cool and turn it once a day with a dry ladle for three days, then leave it alone for three weeks. Top the oil up whenever the level drops to the surface of the pickle.',
     no:'Sett den kjølig og vend den én gang om dagen med en tørr sleiv i tre dager, og la den så stå i fred i tre uker. Fyll på olje hver gang nivået synker til overflaten av picklesen.'}],
  notes:[
    {title:{en:'Why the inner shell is left on', no:'Hvorfor det indre skallet blir sittende'},
     body:{en:'The hard shell around the stone is the piece of the mango that does not soften, and leaving a fragment of it on each cut piece gives the flesh something to hold on to through a year in salt. Peeled cubes of mango pickled the same way collapse into a paste by autumn. It is also why the mango is chopped through the stone with a heavy blade rather than carved off it.',
           no:'Det harde skallet rundt steinen er den delen av mangoen som ikke mykner, og lar du en flis av det sitte på hver bit, får fruktkjøttet noe å henge fast i gjennom et år i salt. Skrelte mangoterninger som legges ned på samme måte, faller sammen til en masse allerede om høsten. Det er også derfor mangoen hakkes tvers gjennom steinen med tung kniv i stedet for å skjæres av den.'}},
    {title:{en:'Why the oil layer is the preservation', no:'Hvorfor oljelaget er konserveringen'},
     body:{en:'Salt pulls water out of the mango and makes what is left too concentrated for most organisms, and the oil on top seals the whole thing off from the air. Nothing else is doing the work, so anything that breaks the oil layer breaks the pickle. Water is the specific enemy, because it is what the salt and oil are there to exclude: one wet spoon can cost a household the whole jar, which is why in many houses one person owns it and nobody else opens it.',
           no:'Saltet trekker vann ut av mangoen og gjør det som er igjen, for konsentrert for de fleste organismer, og oljen på toppen stenger det hele av fra lufta. Ingenting annet gjør jobben, så alt som bryter oljelaget, bryter picklesen. Vann er den bestemte fienden, for vann er nettopp det salt og olje skal holde ute. Én våt skje kan koste husholdningen hele glasset, og derfor er det i mange hus én person som eier det og ingen andre som åpner det.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'The mango is the one ingredient you cannot compromise on, and the season is short.',
           no:'Mangoen er den ene råvaren du ikke kan slakke på, og sesongen er kort. Hard umoden mango selges i de indiske og pakistanske butikkene på Grønland i Oslo i mai og juni, ofte i kasser, og de riktige sortene er merket som raw mango eller kachi keri. En umoden mango fra dagligvaren er som regel en moden sort som ikke har rukket å modne, og den blir søt og bløt i glasset. Bruk grovt salt uten jod og uten antiklumpemiddel. Sterkt chilipulver av typen Guntur eller Teja får du i indisk butikk; vanlig norsk chilipulver er både for svakt og som regel blandet med spisskummen og hvitløk. Kaldpresset sesamolje, ofte merket gingelly, er det tradisjonelle valget, og nøytral jordnøttolje fungerer også. Sennepsolje skal ikke brukes her, for den hører til et annet kjøkken.'}}],
  variations:[
    {title:{en:'Without the garlic', no:'Uten hvitløken'},
     body:{en:'Many households leave the garlic out entirely, and a plain avakaya keeps slightly better for it because the cloves hold a little water. Try one jar each way if you have enough mango.',
           no:'Mange husholdninger sløyfer hvitløken helt, og en enkel avakaya holder seg litt bedre uten den, for feddene bærer med seg noe vann. Lag ett glass av hver hvis du har nok mango.'}},
    {title:{en:'Bellam avakaya, with jaggery', no:'Bellam avakaya, med jaggery'},
     body:{en:'Grated jaggery is mixed in with the powders, roughly a fifth of the weight of the chilli powder. The pickle turns darker and softer and is far easier for a new palate, and it is what many families make for children.',
           no:'Revet jaggery blandes inn sammen med pulverne, omtrent en femdel av vekten på chilipulveret. Picklesen blir mørkere og mildere og er mye lettere for en ny gane, og det er den mange familier lager til barna.'}},
    {title:{en:'A small jar, to learn on', no:'Et lite glass, til å øve på'},
     body:{en:'Set the servings to the smallest the stepper allows and make a single jar the first year. You will learn more from watching one jar through a summer than from reading about it, and a mistake costs one mango rather than a crate.',
           no:'Sett porsjonene til det laveste telleren tillater og lag ett glass det første året. Du lærer mer av å følge ett glass gjennom en sommer enn av å lese om det, og en feil koster én mango i stedet for en kasse.'}}]
},

];
