/* Masala Dabba — recipes for Awadh (IN-AWA). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-AWA'] = [

{
  id:'galouti-kebab', dish:'Galouti kebab', course:'snack', lesson:3, serves:4, veg:false,
  time:{prep:40, cook:20}, hero:'galouti', tags:['kebab','lamb','papaya','ghee'],
  title:{en:'Galouti kebab', no:'Galouti-kebab'},
  blurb:{en:'Lamb pounded to a paste, tenderised with raw papaya and fried in ghee until it barely holds together.',
         no:'Lammekjøtt banket til en jevn masse, mørnet med rå papaya og stekt i ghee til den så vidt henger sammen.'},
  heroCaption:{en:'They are turned with a thin spatula and never with tongs, because a galouti will not survive being gripped.',
               no:'De vendes med en tynn stekespade og aldri med en tang, for en galouti tåler ikke å bli holdt fast.'},
  goesWith:[{en:'Warm sheermal, torn rather than cut', no:'Varm sheermal, revet og ikke skåret'},
            {en:'Sliced raw onion and a wedge of lime', no:'Rå løk i skiver og en limebåt'}],
  headnote:{
    en:`<p>A galouti is not a burger and it is not a kofta. It is meat worked until it has no structure left, held together by nothing but fat and a little starch, and fried gently enough that it survives the pan. Eaten hot off a piece of bread it dissolves, which is the whole point and the reason it is famous.</p>
<p>Two things do the work. Raw green papaya contains papain, an enzyme that cuts proteins apart, and browned onion crushed into the mixture supplies both sweetness and body. Everything else is aroma. The shops claim a hundred spices, and a home kitchen gets most of the way there with a dozen.</p>
<p>The failure to expect is the opposite of the one you expect. A galouti does not come out tough. It comes out as a paste that will not leave the spatula, and that happens when the papaya has been left in too long or used too generously. Weigh it, rest the mixture only as long as the recipe says, and chill it before you shape it.</p>`,
    no:`<p>En galouti er verken en burger eller en kofta. Det er kjøtt som er bearbeidet til det ikke har noen struktur igjen, som bare holdes sammen av fett og litt stivelse, og som stekes så skånsomt at det overlever pannen. Spiser du den varm fra et stykke brød, løser den seg opp, og det er hele poenget og grunnen til at den er berømt.</p>
<p>To ting gjør jobben. Rå grønn papaya inneholder papain, et enzym som bryter ned proteiner, og brunet løk som knuses inn i massen, gir både sødme og fylde. Alt det andre er duft. Butikkene skryter av hundre krydder, og et hjemmekjøkken kommer langt med et dusin.</p>
<p>Feilen som truer, er den motsatte av den du tror. En galouti blir ikke seig. Den blir en masse som ikke slipper stekespaden, og det skjer når papayaen har fått stå for lenge eller er brukt for rundhåndet. Vei den opp, la farsen hvile bare så lenge oppskriften sier, og sett den kaldt før du former den.</p>`},
  ingredients:[
   {group:{en:'The meat', no:'Kjøttet'}, items:[
    {q:600, u:'g', n:{en:'lamb or goat, twice-minced', no:'lammekjøtt eller geitekjøtt, kvernet to ganger'}, note:{en:'shoulder, with its fat left on', no:'bog, med fettet på'}},
    {q:25, u:'g', n:{en:'raw green papaya', no:'rå grønn papaya'}, note:{en:'peeled and grated, flesh only', no:'skrelt og revet, bare fruktkjøttet'}},
    {q:150, u:'g', n:{en:'onion', no:'løk'}, note:{en:'finely sliced', no:'i tynne skiver'}},
    {q:60, u:'g', n:{en:'ghee', no:'ghee'}, note:{en:'for the onion and the mixture', no:'til løken og til farsen'}},
    {q:20, u:'g', n:{en:'gram flour', no:'kikertmel'}},
    {q:15, u:'g', n:{en:'ginger and garlic, ground to a paste', no:'ingefær og hvitløk, most til en jevn masse'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The spices', no:'Krydderet'}, items:[
    {q:4, u:'g', n:{en:'green cardamom', no:'grønn kardemomme'}, note:{en:'seeds only, ground', no:'bare frøene, malt'}},
    {q:2, u:'g', n:{en:'mace', no:'muskatblomme'}, note:{en:'ground', no:'malt'}},
    {q:3, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:2, u:'g', n:{en:'black pepper', no:'svart pepper'}},
    {q:2, u:'g', n:{en:'ground cinnamon', no:'malt kanel'}},
    {q:1, u:'g', n:{en:'ground cloves', no:'malt nellik'}},
    {q:2, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri-chilipulver'}, note:{en:'for colour rather than heat', no:'for fargen og ikke styrken'}},
   ]},
   {group:{en:'To finish', no:'Til slutt'}, items:[
    {q:5, u:'ml', n:{en:'kewra water', no:'kewra-vann'}, scale:'none'},
    {q:80, u:'g', n:{en:'ghee, for frying', no:'ghee, til steking'}, scale:'none'},
   ]}],
  steps:[
    {en:'Fry the sliced onion in ghee over a medium flame until it is evenly brown, then lift it out onto paper and let it cool and go crisp.',
     no:'Stek løkskivene i ghee på middels varme til de er jevnt brune, løft dem så over på papir og la dem kjølne og bli sprø.'},
    {en:'Crush the cooled onion to a coarse powder between your fingers. It should break rather than smear.',
     no:'Knus den avkjølte løken til et grovt pulver mellom fingrene. Den skal brekke og ikke smøre seg.'},
    {en:'Roast the gram flour in a dry pan over a low flame, stirring, until it smells of toasted nuts and darkens by a shade. Let it cool.',
     no:'Rist kikertmelet i en tørr panne på lav varme under omrøring til det lukter ristede nøtter og blir et hakk mørkere. La det kjølne.'},
    {en:'Put the mince in a bowl with the grated papaya, the ginger and garlic, all the ground spices, the crushed onion, the roasted flour and salt. Work it with your hand for five minutes, until it is smooth and slightly sticky.',
     no:'Ha kjøttdeigen i en bolle sammen med den revne papayaen, ingefæren og hvitløken, alle de malte krydderne, den knuste løken, det ristede melet og salt. Arbeid det sammen med hånda i fem minutter, til massen er glatt og litt klebrig.'},
    {en:'Melt the ghee for the mixture, let it cool until it is only just warm, and work it in. Cover the bowl and rest it in the fridge for two hours.',
     no:'Smelt gheen til farsen, la den bli så vidt lunken, og arbeid den inn. Dekk til bollen og la den hvile i kjøleskapet i to timer.'},
    {en:'Sprinkle the kewra water over and fold it through. Fry a pinch of the mixture in a dry pan, taste it, and correct the salt.',
     no:'Dryss kewra-vannet over og vend det inn. Stek en klype av massen i en tørr panne, smak, og juster saltet.'},
    {en:'Wet your palms and pat the mixture into small flat discs about a centimetre thick. Lay them on a cold plate and put them back in the fridge for twenty minutes.',
     no:'Fukt håndflatene og klapp massen ut i små flate kaker på omtrent en centimeter. Legg dem på en kald tallerken og sett dem tilbake i kjøleskapet i tjue minutter.'},
    {en:'Heat a heavy flat pan and add ghee for frying. Hold it at a steady medium: a fierce pan tears the kebabs and a cool one lets them fall apart.',
     no:'Varm en tung, flat panne og ha i ghee til steking. Hold jevn middels varme, for en glovarm panne river kebabene i stykker og en lunken panne lar dem falle fra hverandre.'},
    {en:'Fry them for three to four minutes a side, turning once with a thin spatula. They should be dark brown outside and still soft in the middle.',
     no:'Stek dem i tre til fire minutter på hver side, og snu dem én gang med en tynn stekespade. De skal være mørkebrune utenpå og fortsatt myke inni.'},
    {en:'Serve them straight out of the pan on warm bread, with raw onion and lime. They do not reheat well.',
     no:'Server dem rett fra pannen på varmt brød, med rå løk og lime. De blir ikke gode oppvarmet.'}],
  notes:[
    {title:{en:'Why the papaya is weighed', no:'Hvorfor papayaen veies'},
     body:{en:'Papain does not stop when the bowl goes into the fridge, it only slows down. Too much papaya, or too long a rest, takes the meat past tender and into a paste that will not leave the spatula, and there is no way back from that. The enzyme is strongest in hard green fruit, so it is exactly the properly green papaya that has to be measured.',
           no:'Papainet slutter ikke å arbeide når bollen settes i kjøleskapet, det går bare saktere. For mye papaya, eller for lang hvile, tar kjøttet forbi mørt og over i en masse som ikke slipper stekespaden, og derfra er det ingen vei tilbake. Enzymet er sterkest i hard, grønn frukt, så det er nettopp den grønne papayaen som må måles opp.'}},
    {title:{en:'Why the onion is browned and then crushed', no:'Hvorfor løken brunes og knuses etterpå'},
     body:{en:'Browned onion is doing two jobs at once. It sweetens the mixture, because the sugars have caramelised, and once it is crisp and crushed it works as a dry binder that soaks up the meat juices. Onion added raw or soft would give off water instead, and the kebabs would slump in the pan.',
           no:'Den brunede løken har to oppgaver på én gang. Den søter farsen, for sukkeret har karamellisert, og når den er sprø og knust, virker den som et tørt bindemiddel som suger opp kjøttsaften. Rå eller myk løk ville gitt fra seg vann i stedet, og da siger kebabene ut i pannen.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Ask a halal butcher to mince shoulder twice and leave the fat on, because the lamb mince in an ordinary supermarket is leaner than this recipe wants. Green papaya turns up in the Asian shops in Oslo and Bergen, and an unripe one keeps a fortnight in the fridge.',
           no:'Be en halalslakter kverne bog to ganger og la fettet sitte på, for kjøttdeig av lam i vanlige butikker er magrere enn denne oppskriften vil ha. Grønn papaya finnes i asiatiske butikker i Oslo og Bergen, og en umoden frukt holder seg i fjorten dager i kjøleskapet. Muskatblomme selges som javitri i indiske butikker til en brøkdel av prisen i dagligvarebutikken, og kewra-vann koster nesten ingenting der. Ghee får du samme sted, og klaret usaltet smør gjør samme nytten.'}}],
  variations:[
    {title:{en:'Kakori, on a skewer', no:'Kakori, på spidd'},
     body:{en:'Leave out the gram flour, halve the papaya, add ground white poppy seed and a little khoya, and press the mixture along flat metal skewers instead. Cook it over charcoal, turning it as it sets. It has to hold on to the skewer, so it is built firmer on purpose.',
           no:'Sløyf kikertmelet, halver papayaen, ha i malte hvite valmuefrø og litt khoya, og stryk massen ut langs flate metallspidd i stedet. Stek den over trekull og snu den etter hvert som den stivner. Den må bli sittende på spiddet, så den bygges fastere med vilje.'}},
    {title:{en:'Without papaya', no:'Uten papaya'},
     body:{en:'A kitchen with no green papaya can use grated raw kiwi at about the same weight, because it carries a similar enzyme. It is not traditional and it works. Rest the mixture for an hour rather than two, since the kiwi acts faster.',
           no:'Et kjøkken uten grønn papaya kan bruke revet rå kiwi i omtrent samme vekt, for den har et liknende enzym. Det er ikke tradisjonelt, og det virker. La farsen hvile en time i stedet for to, for kiwien arbeider raskere.'}},
    {title:{en:'A vegetarian version', no:'En vegetarisk utgave'},
     body:{en:'Lucknow makes the same kebab from boiled raw banana or from soaked split peas, mashed and bound with roasted gram flour. No enzyme is needed and none would help, and the spicing and the ghee stay exactly as they are.',
           no:'Lucknow lager den samme kebaben av kokte grønne bananer eller av bløtlagte gule erter, most og bundet med ristet kikertmel. Da trengs ikke noe enzym, og det ville ikke hjulpet heller, mens krydringen og gheen er akkurat som før.'}}]
},

{
  id:'awadhi-biryani', dish:'Awadhi biryani', course:'rice', lesson:2, serves:6, veg:false,
  time:{prep:40, cook:90}, hero:'biryani', tags:['rice','goat','dum','saffron'],
  title:{en:'Awadhi biryani', no:'Awadhi-biryani'},
  blurb:{en:'The meat cooked first in an aromatic stock, the rice part-boiled in the same stock, layered and finished under a dough seal.',
         no:'Kjøttet kokes først i en aromatisk kraft, risen halvkokes i den samme kraften, og alt legges lagvis og gjøres ferdig under en forsegling av deig.'},
  heroCaption:{en:'The pot goes to the table closed. Everything the perfume does happens in the half-minute after the seal is broken.',
               no:'Gryta går lukket til bordet. Alt duften har å gjøre, skjer i det halve minuttet etter at forseglingen er brutt.'},
  goesWith:[{en:'Thinned yoghurt with onion and mint', no:'Tynnet yoghurt med løk og mynte'},
            {en:'A warm sheermal to mop the pot with', no:'En varm sheermal til å tørke opp gryta med'}],
  headnote:{
    en:`<p>This is the pakki method, which means the meat is cooked before it ever meets the rice. Hyderabad does the opposite and seals raw meat under part-boiled grains, and reading two explains why the two dishes taste so unlike each other. Here the meat goes into a spiced stock and comes out tender, and the rice is boiled in that same liquid, so every grain is already carrying flavour before anything is layered.</p>
<p>The seal is what turns two cooked things into one dish. Half an hour under a lid luted with dough, over the lowest heat you can manage, lets steam move up through the rice and saffron milk move down through it, and lets the kewra reach everything. Cook the same layers uncovered and you have rice with meat in it.</p>
<p>Two judgements matter more than the rest. The rice comes off the boil at about seventy per cent done, with a hard core you can still feel between finger and thumb. And the pot finishes on the lowest possible flame with something between it and the ring. Everything else is patience.</p>`,
    no:`<p>Dette er pakki-metoden, og den går ut på at kjøttet er ferdig kokt før det møter risen. Hyderabad gjør det motsatte og forsegler rått kjøtt under halvkokt ris, og lesetekst to forklarer hvorfor de to rettene smaker så ulikt. Her kokes kjøttet i en krydret kraft til det er mørt, og risen kokes i den samme væsken, så hvert eneste korn bærer smak allerede før noe legges lagvis.</p>
<p>Forseglingen gjør to ferdige ting om til én rett. En halvtime under et lokk festet med deig, over den laveste varmen du får til, lar dampen gå opp gjennom risen og safranmelken gå ned gjennom den, og lar kewraen nå alt. Koker du de samme lagene uten lokk, sitter du igjen med ris som det ligger kjøtt i.</p>
<p>To vurderinger betyr mer enn resten. Risen tas av kokevannet når den er omtrent sytti prosent ferdig, med en hard kjerne du fortsatt kjenner mellom fingrene. Og gryta gjøres ferdig på lavest mulig varme med noe imellom seg og platen. Alt annet er tålmodighet.</p>`},
  ingredients:[
   {group:{en:'The meat and its stock', no:'Kjøttet og kraften'}, items:[
    {q:1, u:'kg', n:{en:'goat or lamb on the bone, in large pieces', no:'geite- eller lammekjøtt med bein, i store biter'}, note:{en:'shoulder and leg', no:'bog og lår'}},
    {q:300, u:'g', n:{en:'onion', no:'løk'}, note:{en:'half sliced, half chopped', no:'halvparten i skiver, halvparten hakket'}},
    {q:200, u:'g', n:{en:'plain yoghurt', no:'naturell yoghurt'}, note:{en:'whisked smooth', no:'pisket glatt'}},
    {q:30, u:'g', n:{en:'ginger and garlic, ground to a paste', no:'ingefær og hvitløk, most til en jevn masse'}},
    {q:100, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:1, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The potli', no:'Potlien'}, items:[
    {q:5, u:'g', n:{en:'green cardamom pods', no:'hele grønne kardemommekapsler'}},
    {q:3, u:'g', n:{en:'mace blades', no:'hel muskatblomme'}},
    {q:2, u:'', n:{en:'black cardamom pods', no:'svarte kardemommekapsler'}, round:'half'},
    {q:1, u:'', n:{en:'cinnamon stick', no:'kanelstang'}, round:'half'},
    {q:3, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
    {q:5, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:3, u:'g', n:{en:'black peppercorns', no:'hele svarte pepperkorn'}},
   ]},
   {group:{en:'The rice and the layers', no:'Risen og lagene'}, items:[
    {q:600, u:'g', n:{en:'basmati rice', no:'basmatiris'}, note:{en:'soaked 30 minutes, then drained', no:'bløtlagt i 30 minutter og silt av'}},
    {q:1, u:'g', n:{en:'saffron threads', no:'safrantråder'}, scale:'none'},
    {q:60, u:'ml', n:{en:'warm milk', no:'lunken melk'}, scale:'none'},
    {q:5, u:'ml', n:{en:'kewra water', no:'kewra-vann'}, scale:'none'},
    {q:1, u:'', n:{en:'small bunch of mint', no:'liten bunt mynte'}, round:'half', scale:'none'},
    {q:150, u:'g', n:{en:'plain flour, for the seal', no:'hvetemel, til forseglingen'}, scale:'none', note:{en:'mixed with water into a stiff dough', no:'rørt ut med vann til en fast deig'}},
   ]}],
  steps:[
    {en:'Fry the sliced onion in ghee until it is deep brown and crisp, and lift half of it out onto paper. That half is the birista, and it goes between the layers.',
     no:'Stek løkskivene i ghee til de er dypt brune og sprø, og løft halvparten over på papir. Den halvparten er birista, og den går mellom lagene.'},
    {en:'Tie the whole spices for the potli into a square of muslin and knot it loosely, so the liquid can move through it.',
     no:'Knyt de hele krydderne til potlien inn i en firkant av musselin, og la knuten sitte løst så væsken kan gå gjennom.'},
    {en:'Add the chopped onion to the ghee left in the pan and cook it soft, then stir in the ginger and garlic and give it two more minutes.',
     no:'Ha den hakkede løken i gheen som er igjen i pannen, og la den bli myk, rør så inn ingefæren og hvitløken og la det gå to minutter til.'},
    {en:'Add the meat and brown it lightly. Take the pan off the heat, then stir the whisked yoghurt in a little at a time before returning it to a low flame, so it cannot split.',
     no:'Ha i kjøttet og brun det lett. Ta pannen av platen og rør inn den piskede yoghurten litt om gangen før du setter den tilbake på lav varme, så yoghurten ikke skiller seg.'},
    {en:'Pour in the water, drop in the potli, salt it, cover, and simmer until the meat is tender and the liquid has reduced to a thick gravy. Squeeze the potli against the side of the pan and lift it out.',
     no:'Hell i vannet, slipp ned potlien, salt, legg på lokk, og la det småkoke til kjøttet er mørt og væsken er kokt inn til en tykk saus. Klem potlien mot grytekanten og løft den opp.'},
    {en:'Steep the saffron in the warm milk for a quarter of an hour.',
     no:'La safranen trekke i den lunkne melken i et kvarter.'},
    {en:'Bring a large pan of well-salted water to a hard boil, tip in the drained rice and cook it for four to five minutes only. Bite a grain: the outside should be soft and the centre still hard. Drain it at once.',
     no:'Kok opp en stor kjele med godt saltet vann, hell i den avsilte risen og kok den i bare fire til fem minutter. Bit i et korn: utsiden skal være myk og kjernen fortsatt hard. Sil av med en gang.'},
    {en:'Layer it in a heavy pot: half the rice, then all the meat with its gravy, then the fried onion and torn mint, then the rest of the rice. Drizzle the saffron milk and the kewra water over the top.',
     no:'Legg det lagvis i en tung gryte: halve risen, så alt kjøttet med sausen, så den stekte løken og revet mynte, og til slutt resten av risen. Drypp safranmelken og kewra-vannet over toppen.'},
    {en:'Work the flour and a little water into a stiff rope of dough, press it round the rim of the pot and clamp the lid down onto it.',
     no:'Arbeid melet og litt vann til en fast pølse av deig, press den rundt kanten på gryta og klem lokket ned på den.'},
    {en:'Cook it on the lowest heat for half an hour, with a griddle or a heat diffuser between the pot and the ring. Do not lift the lid to look.',
     no:'La den stå på lavest mulig varme i en halvtime, med en takke eller en varmefordeler mellom gryta og kokeplaten. Ikke løft på lokket for å kikke.'},
    {en:'Rest it off the heat for ten minutes, carry it to the table closed, and break the seal there. Serve with a spoon that reaches the bottom, so every plate gets both layers.',
     no:'La den hvile med gryta av platen i ti minutter, bær den lukket til bordet og bryt forseglingen der. Øs opp med en skje som når bunnen, så hver tallerken får begge lagene.'}],
  notes:[
    {title:{en:'Why the rice comes off the boil hard', no:'Hvorfor risen tas opp hard'},
     body:{en:'The grains go on cooking under the seal in the steam rising off the meat, and that last third is where they take up the flavour. Rice boiled soft beforehand has nothing left to absorb and collapses into the gravy, which is the commonest way a home biryani goes wrong.',
           no:'Kornene koker videre under forseglingen i dampen som stiger fra kjøttet, og i den siste tredjedelen tar de opp smaken. Ris som er kokt myk på forhånd, har ingenting igjen å suge til seg og går i oppløsning ned i sausen, og det er den vanligste feilen i en biryani laget hjemme.'}},
    {title:{en:'Why the yoghurt goes in off the heat', no:'Hvorfor yoghurten går i med kjelen av platen'},
     body:{en:'Yoghurt protein curdles the moment it meets a hot pan, and a gravy that has split looks grainy however long it cooks afterwards. Whisked smooth and stirred into a pan that has come off the fire, it emulsifies instead and thickens the stock.',
           no:'Yoghurt skiller seg i det øyeblikket den møter en varm panne, og en saus som har skilt seg, ser kornet ut uansett hvor lenge den koker etterpå. Er yoghurten pisket glatt og rørt inn i en panne som er tatt av platen, binder den seg i stedet og tykner kraften.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Goat on the bone is sold by halal butchers in Oslo and by several Asian supermarkets, usually frozen and already cut for exactly this kind of dish. Norwegian lamb works and cooks faster, so start testing it twenty minutes earlier than you would goat.',
           no:'Geitekjøtt med bein selges hos halalslaktere i Oslo og i flere asiatiske butikker, som regel frossent og ferdig skåret til nettopp slike retter. Norsk lammekjøtt fungerer og blir fortere mørt, så begynn å kjenne på det tjue minutter tidligere enn du ville gjort med geit. Kjøp gjerne basmati som er lagret i et år, og det står som regel på sekken, for ny ris brekker lettere. Kewra-vann og hel muskatblomme får du i indiske butikker, og musselin kan erstattes av et osteklede.'}}],
  variations:[
    {title:{en:'Without a dough seal', no:'Uten forsegling av deig'},
     body:{en:'A tight lid weighted down with a heavy pan, over a diffuser, gets most of the way there. A sheet of baking paper laid over the rice and under the lid helps more than it sounds as though it should, because it stops the steam running back down the sides.',
           no:'Et tettsittende lokk med en tung panne oppå, over en varmefordeler, kommer langt på vei. Et ark bakepapir lagt over risen og under lokket hjelper mer enn det høres ut som, for det hindrer dampen i å renne ned langs sidene.'}},
    {title:{en:'A vegetable version', no:'En utgave med grønnsaker'},
     body:{en:'Replace the meat with waxy potato, carrot, peas and paneer, cooked in the same stock for about a quarter of the time. Everything else stands, the potli and the seal included.',
           no:'Bytt ut kjøttet med fastkokende potet, gulrot, erter og paneer, kokt i den samme kraften på omtrent en fjerdedel av tiden. Alt det andre blir som før, både potlien og forseglingen.'}},
    {title:{en:'Kacchi, if you want to try it', no:'Kacchi, om du vil prøve'},
     body:{en:'Marinate the raw meat overnight in the yoghurt with grated green papaya, put it in the bottom of the pot, lay the part-boiled rice straight on top and seal it. It needs about an hour and a half, and it is Hyderabad’s method rather than this one.',
           no:'Marinér det rå kjøttet natta over i yoghurten sammen med revet grønn papaya, legg det i bunnen av gryta, legg den halvkokte risen rett oppå og forsegl. Den trenger omtrent halvannen time, og det er Hyderabads metode og ikke denne.'}}]
},

{
  id:'sheermal', dish:'Sheermal', course:'bread', lesson:2, serves:6, veg:true,
  time:{prep:30, cook:15}, hero:'sheermal', tags:['bread','saffron','milk','tandoor'],
  title:{en:'Sheermal', no:'Sheermal'},
  blurb:{en:'A soft, faintly sweet milk bread, baked fast and brushed with saffron milk the moment it comes out.',
         no:'Et mykt, svakt søtt melkebrød som bakes raskt og pensles med safranmelk i det øyeblikket det kommer ut.'},
  heroCaption:{en:'The orange is saffron milk painted on hot bread, not saffron baked into the dough.',
               no:'Det oransje er safranmelk penslet på varmt brød, og ikke safran bakt inn i deigen.'},
  goesWith:[{en:'Galouti kebabs, folded inside it', no:'Galouti-kebab, brettet inn i den'},
            {en:'A bowl of nihari, with the sugar left out', no:'En skål nihari, med sukkeret sløyfet i deigen'}],
  headnote:{
    en:`<p>Sheermal is the bread the kebabs are wrapped in, and that job explains everything about it. It has to be supple enough to fold without tearing, rich enough not to dry out on a stall, and sweet enough to stand beside a spiced kebab without disappearing. Shir is Persian for milk, and milk in place of water is the whole difference.</p>
<p>Lucknow bakes it in a tandoor, and a domestic oven at its hottest gets close enough. What matters is that the dough meets a surface that is already fiercely hot, so the outside sets before the inside dries. A baking stone, or a heavy tray left upside down in the oven for half an hour, does that.</p>
<p>The saffron milk goes on at the end and never into the dough. Baked saffron loses most of what you paid for, while saffron painted onto hot bread perfumes the crust and stains it the orange that makes a sheermal recognisable across a street.</p>`,
    no:`<p>Sheermal er brødet kebabene brettes inn i, og den oppgaven forklarer alt ved det. Det må være mykt nok til å brettes uten å revne, fett nok til ikke å tørke ut på en bod, og søtt nok til å stå ved siden av en krydret kebab uten å forsvinne. Shir er persisk for melk, og melk i stedet for vann er hele forskjellen.</p>
<p>Lucknow baker det i en tandoor, og en vanlig stekeovn på full varme kommer nær nok. Det avgjørende er at deigen møter en flate som alt er glovarm, så utsiden stivner før innsiden tørker. En bakestein, eller et tungt stekebrett som har stått opp-ned i ovnen i en halvtime, gjør den jobben.</p>
<p>Safranmelken pensles på til slutt og går aldri i deigen. Bakt safran mister det meste av det du har betalt for, mens safran penslet på varmt brød gir duft til skorpen og farger den oransje, og det er den fargen som gjør en sheermal til å kjenne igjen tvers over gata.</p>`},
  ingredients:[
   {group:{en:'The dough', no:'Deigen'}, items:[
    {q:500, u:'g', n:{en:'plain flour', no:'hvetemel'}, note:{en:'and a little more for the board', no:'og litt mer til bakebordet'}},
    {q:250, u:'ml', n:{en:'whole milk', no:'helmelk'}, note:{en:'warmed to blood heat', no:'varmet til kroppstemperatur'}},
    {q:80, u:'g', n:{en:'ghee', no:'ghee'}, note:{en:'melted and cooled', no:'smeltet og avkjølt'}},
    {q:40, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:7, u:'g', n:{en:'dried yeast', no:'tørrgjær'}},
    {q:6, u:'g', n:{en:'salt', no:'salt'}},
    {q:2, u:'g', n:{en:'green cardamom', no:'grønn kardemomme'}, note:{en:'seeds only, ground', no:'bare frøene, malt'}},
   ]},
   {group:{en:'To finish', no:'Til slutt'}, items:[
    {q:1, u:'g', n:{en:'saffron threads', no:'safrantråder'}, scale:'none'},
    {q:60, u:'ml', n:{en:'warm milk, for the glaze', no:'lunken melk, til penslingen'}, scale:'none'},
    {q:30, u:'g', n:{en:'ghee, for brushing', no:'ghee, til pensling'}, scale:'none'},
    {q:20, u:'g', n:{en:'flaked almonds or slivered pistachio', no:'mandelflak eller pistasj i strimler'}, note:{en:'optional', no:'valgfritt'}},
   ]}],
  steps:[
    {en:'Stir the sugar and the yeast into the warm milk and leave it for ten minutes, until it froths.',
     no:'Rør sukkeret og gjæren ut i den lunkne melken og la den stå i ti minutter, til den skummer.'},
    {en:'Mix the flour, salt and ground cardamom in a bowl, pour in the yeasted milk and bring it together into a rough dough.',
     no:'Bland mel, salt og malt kardemomme i en bolle, hell i melken med gjær og samle det til en grov deig.'},
    {en:'Work the melted ghee in a little at a time, then knead for ten minutes, until the dough is smooth and no longer clings to your hands.',
     no:'Arbeid inn den smeltede gheen litt om gangen, og elt så i ti minutter, til deigen er glatt og ikke lenger henger fast i hendene.'},
    {en:'Cover the bowl and leave it somewhere warm for an hour and a half, until it has roughly doubled.',
     no:'Dekk til bollen og sett den lunt i halvannen time, til deigen har omtrent doblet seg.'},
    {en:'Put a baking stone or a heavy upturned tray in the oven and heat it to 250 °C for at least half an hour.',
     no:'Sett en bakestein eller et tungt stekebrett opp-ned i ovnen og varm opp ovnen til 250 °C i minst en halvtime.'},
    {en:'Steep the saffron in the warm milk for the glaze while the oven heats.',
     no:'La safranen trekke i den lunkne melken til penslingen mens ovnen varmes.'},
    {en:'Knock the dough back and divide it into equal pieces, one for each person. Roll each into a disc about half a centimetre thick and prick it all over with a fork.',
     no:'Slå ned deigen og del den i like store emner, ett til hver. Kjevle hvert emne ut til en leiv på omtrent en halv centimeter og prikk den godt med en gaffel.'},
    {en:'Bake them on the hot stone, two at a time, for five to six minutes, until they have puffed and are patched with brown.',
     no:'Stek dem på den varme steinen, to om gangen, i fem til seks minutter, til de har hevet seg og fått brune flekker.'},
    {en:'Brush each bread with the saffron milk the instant it leaves the oven, then with a little melted ghee, and scatter the nuts over.',
     no:'Pensle hvert brød med safranmelken i det øyeblikket det kommer ut av ovnen, så med litt smeltet ghee, og strø nøttene over.'},
    {en:'Stack them under a cloth as they come out and serve them warm.',
     no:'Stable dem under et klede etter hvert som de kommer ut, og server dem varme.'}],
  notes:[
    {title:{en:'Why the ghee goes in after the flour is wet', no:'Hvorfor gheen går i etter at melet er fuktet'},
     body:{en:'Fat coats flour and stops gluten forming, so a dough made with the ghee in from the start never builds the strength to hold gas. Wet the flour first, let the gluten begin, and only then work the fat in, and the bread comes out both soft and stretchy.',
           no:'Fett legger seg rundt melet og hindrer at det dannes gluten, så en deig med gheen i fra starten får aldri styrke nok til å holde på gassen. Fukt melet først, la glutenet komme i gang, og arbeid så fettet inn, og da blir brødet både mykt og elastisk.'}},
    {title:{en:'Why the saffron is brushed on rather than baked in', no:'Hvorfor safranen pensles på og ikke bakes inn'},
     body:{en:'Saffron gives up its colour and scent into warm liquid, and much of the scent is lost again at oven temperature. Steeping it and then painting it onto bread that is already cooked puts everything you paid for on the surface, where you smell it before you taste it.',
           no:'Safran gir fra seg farge og duft til lunken væske, og mye av duften går tapt igjen i ovnsvarme. Lar du den trekke og så pensler den på et brød som alt er ferdig, havner alt du har betalt for, på overflaten, der du kjenner duften før du smaker den.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Ordinary Norwegian plain flour is strong enough for this and needs nothing added to it. Ghee is sold in Indian shops and keeps for months out of the fridge, and clarified unsalted butter is the same thing.',
           no:'Vanlig norsk hvetemel er sterkt nok til dette og trenger ingen tilsetning. Ghee selges i indiske butikker og holder seg i månedsvis utenfor kjøleskap, og klaret usaltet smør er det samme. Safran i de små posene i dagligvarebutikken er dyrt i forhold til kvaliteten, mens iranske og indiske butikker selger hele gram for langt mindre. Har du ikke bakestein, gjør et tykt brett eller en panne i støpejern samme nytten.'}}],
  variations:[
    {title:{en:'Taftan', no:'Taftan'},
     body:{en:'Add an egg to the dough and a little more sugar, and shape the breads thicker and rounder. Taftan belongs to the same family, is richer, sits closer to a bun, and is often studded with almonds.',
           no:'Ha et egg i deigen og litt mer sukker, og form brødene tykkere og rundere. Taftan hører til samme familie, er fetere, ligger nærmere en bolle og er ofte pyntet med mandler.'}},
    {title:{en:'In a pan instead of an oven', no:'I panne i stedet for i ovn'},
     body:{en:'A heavy frying pan over a high flame cooks a sheermal in about two minutes a side. It comes out flatter and chewier and it is still good, and it is how most Norwegian kitchens will end up making it.',
           no:'En tung stekepanne på sterk varme steker en sheermal på omtrent to minutter på hver side. Den blir flatere og seigere, men fortsatt god, og det er slik de fleste norske kjøkken kommer til å lage den.'}},
    {title:{en:'Savoury, for nihari', no:'Uten sødme, til nihari'},
     body:{en:'Leave out the sugar and most of the cardamom and the same dough becomes a plain enriched flatbread, which suits a bowl of nihari far better than the sweet version does.',
           no:'Sløyf sukkeret og det meste av kardemommen, så blir den samme deigen et enkelt, fett flatbrød, og det passer til en skål nihari langt bedre enn den søte utgaven gjør.'}}]
},

{
  id:'shahi-tukda', dish:'Shahi tukda', course:'sweet', lesson:3, serves:4, veg:true,
  time:{prep:20, cook:75}, hero:'shahi-tukda', tags:['sweet','bread','rabri','saffron'],
  title:{en:'Shahi tukda', no:'Shahi tukda'},
  blurb:{en:'Bread fried hard in ghee, dipped in syrup and buried under milk boiled down to rabri.',
         no:'Brød stekt hardt i ghee, dyppet i sukkerlake og begravd under melk kokt inn til rabri.'},
  heroCaption:{en:'Fried hard, dipped for seconds, and left under the rabri for hours. The bread should still have a bite.',
               no:'Stekt hardt, dyppet i noen sekunder og satt under rabrien i timevis. Brødet skal fortsatt ha bitt.'},
  goesWith:[{en:'Strong tea, without milk', no:'Sterk te, uten melk'},
            {en:'Made in the morning and eaten in the evening', no:'Laget om morgenen og spist om kvelden'}],
  headnote:{
    en:`<p>Every cuisine with a bread habit has a dish for the loaf that has gone stale, and this is the richest of them. Slices are fried in ghee until they are genuinely hard, dipped in syrup for a moment and then covered in rabri, which is milk reduced over a low flame until it is thick and slightly grainy. It is a dessert of three things, and all three have to be done properly.</p>
<p>The rabri is the long part and it cannot be hurried. Milk goes into a wide pan, the heat stays low, and the skin that forms is pushed against the side and scraped back in again and again, which is exactly what gives the finished cream its texture. An hour is normal.</p>
<p>The one mistake to avoid is soft bread. A slice that has merely been toasted turns to pulp under the rabri and the dish becomes a bowl of sweet mush. Fry it until it is dark and rigid and knocks against the pan, and it will still have a bite after an hour under the cream.</p>`,
    no:`<p>Alle kjøkken med brød på bordet har en rett for brødet som er blitt gammelt, og dette er den feteste av dem. Skivene stekes i ghee til de er virkelig harde, dyppes et øyeblikk i sukkerlake og dekkes så med rabri, altså melk kokt inn på lav varme til den er tykk og litt kornete. Desserten består av tre ting, og alle tre må gjøres ordentlig.</p>
<p>Rabrien er den delen som tar tid, og den kan ikke forseres. Melken går i en vid panne, varmen holdes lav, og skinnet som legger seg, skyves mot kanten og skrapes ned igjen gang på gang, og det er nettopp det som gir den ferdige kremen konsistensen sin. En time er vanlig.</p>
<p>Den ene feilen du bør unngå, er mykt brød. En skive som bare er ristet, blir til grøt under rabrien, og retten ender som en skål søt masse. Stek den til den er mørk og stiv og klaprer mot pannen, så har den fortsatt bitt etter en time under kremen.</p>`},
  ingredients:[
   {group:{en:'The rabri', no:'Rabrien'}, items:[
    {q:1, u:'l', n:{en:'whole milk', no:'helmelk'}},
    {q:60, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:1, u:'g', n:{en:'saffron threads', no:'safrantråder'}, scale:'none'},
    {q:2, u:'g', n:{en:'green cardamom', no:'grønn kardemomme'}, note:{en:'seeds only, ground', no:'bare frøene, malt'}},
   ]},
   {group:{en:'The bread and the syrup', no:'Brødet og laken'}, items:[
    {q:6, u:'', n:{en:'thick slices of white bread', no:'tykke skiver loff'}, round:'half', note:{en:'a day or two old, crusts cut off', no:'ett eller to døgn gamle, uten skorpe'}},
    {q:120, u:'g', n:{en:'ghee', no:'ghee'}, note:{en:'for frying', no:'til steking'}},
    {q:150, u:'g', n:{en:'sugar, for the syrup', no:'sukker, til laken'}},
    {q:150, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:5, u:'ml', n:{en:'rose water', no:'rosevann'}, scale:'none'},
   ]},
   {group:{en:'On top', no:'På toppen'}, items:[
    {q:20, u:'g', n:{en:'pistachio and almond', no:'pistasj og mandler'}, note:{en:'slivered', no:'i tynne strimler'}},
    {q:2, u:'', n:{en:'sheets of edible silver leaf', no:'ark spiselig bladsølv'}, round:'half', note:{en:'optional', no:'valgfritt'}},
   ]}],
  steps:[
    {en:'Pour the milk into a wide heavy pan and bring it to a bare simmer over a low flame.',
     no:'Hell melken i en vid, tung panne og la den så vidt begynne å småkoke på lav varme.'},
    {en:'Cook it down for about an hour, stirring every few minutes, pushing the skin that forms against the side of the pan and then scraping it back in. Stop when it has reduced to roughly a third.',
     no:'Kok den inn i omtrent en time, rør hvert par minutter, skyv skinnet som legger seg, opp mot kanten av pannen, og skrap det ned igjen. Stopp når den er kokt inn til omtrent en tredjedel.'},
    {en:'Stir in the sugar, the ground cardamom and most of the saffron, then take the pan off the heat. The rabri thickens further as it cools.',
     no:'Rør inn sukkeret, den malte kardemommen og det meste av safranen, og ta så pannen av platen. Rabrien tykner videre mens den kjøler seg.'},
    {en:'Boil the syrup sugar with the water until it is faintly sticky between two fingers, about five minutes, then take it off the heat and stir in the rose water.',
     no:'Kok sukkeret til laken sammen med vannet til den er svakt klebrig mellom to fingre, omtrent fem minutter, ta den så av platen og rør inn rosevannet.'},
    {en:'Cut the bread into triangles.',
     no:'Skjær brødet i trekanter.'},
    {en:'Heat the ghee in a frying pan and fry the triangles over a medium flame, a few at a time, until they are deep brown and hard on both sides. Drain them on paper.',
     no:'Varm gheen i en stekepanne og stek trekantene på middels varme, noen få om gangen, til de er dypt brune og harde på begge sider. La dem renne av på papir.'},
    {en:'Dip each fried piece into the warm syrup for about five seconds and lift it straight out. Any longer and it softens all the way through.',
     no:'Dypp hver stekt bit i den varme laken i omtrent fem sekunder og løft den rett opp. Blir den liggende lenger, mykner den tvers igjennom.'},
    {en:'Lay the pieces in a single layer on a wide dish and spoon the rabri over them, so that they are covered but not swimming.',
     no:'Legg bitene i ett lag på et vidt fat og øs rabrien over dem, slik at de er dekket uten å svømme.'},
    {en:'Scatter the nuts and the last of the saffron over, and lay the silver leaf on using the paper it comes on, touching it as little as you can.',
     no:'Strø nøttene og resten av safranen over, og legg bladsølvet på ved hjelp av papiret det ligger på, og ta så lite som mulig i det.'},
    {en:'Chill it for at least two hours before serving. It is better made in the morning for the evening.',
     no:'Sett det kaldt i minst to timer før servering. Det blir best når det lages om morgenen til kvelden.'}],
  notes:[
    {title:{en:'Why the bread is fried and not toasted', no:'Hvorfor brødet stekes og ikke ristes'},
     body:{en:'Frying drives the water out of the crumb and replaces it with fat, so the structure sets and is waterproofed at the same time. Toast has neither, so it drinks the syrup and the rabri straight through and collapses. That is also why the dip is counted in seconds.',
           no:'Steking driver vannet ut av brødsmulen og erstatter det med fett, så strukturen både stivner og blir vanntett på én gang. Ristet brød har ingen av delene, det suger til seg både lake og rabri tvers igjennom, og så faller det sammen. Det er også derfor dyppingen telles i sekunder.'}},
    {title:{en:'What the stirring does to the rabri', no:'Hva røringen gjør med rabrien'},
     body:{en:'The skin that forms on simmering milk is protein and fat, and scraping it back in is what makes rabri grainy rather than smooth. A version blitzed in a blender, or boiled hard, tastes of milk and of nothing else. The texture is the dish.',
           no:'Skinnet som legger seg på småkokende melk, er protein og fett, og når det skrapes ned igjen, blir rabrien kornete i stedet for glatt. En utgave som er kjørt i blender, eller fosskokt, smaker melk og ingenting annet. Konsistensen er hele retten.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'A plain white loaf from any bakery is the right bread, because brioche and other sweet breads make the dish cloying. Edible silver leaf is sold in Indian shops and in cake-decorating shops, and the dish is perfectly good without it.',
           no:'En vanlig loff fra bakeriet er riktig brød, for brioche og andre søte brød gjør retten kvalmende søt. Spiselig bladsølv selges i indiske butikker og i butikker for kakepynt, og retten er god uten. Rosevann fra en tyrkisk eller indisk butikk er laget for mat, mens de små flaskene med essens på bakehylla er langt sterkere og går i dråpevis. Bruk helmelk og ikke lettmelk, for det er fettet som gir rabrien fylden.'}}],
  variations:[
    {title:{en:'Double ka meetha', no:'Double ka meetha'},
     body:{en:'Hyderabad makes the same dish but dries the fried bread in the oven first, soaks it in the syrup properly and pours thinner sweetened milk over it. The result is looser, sweeter and eaten warm.',
           no:'Hyderabad lager den samme retten, men tørker det stekte brødet i ovnen først, legger det ordentlig i laken og heller tynnere, søtet melk over. Resultatet blir løsere, søtere og spises varmt.'}},
    {title:{en:'With khoya instead of rabri', no:'Med khoya i stedet for rabri'},
     body:{en:'Khoya, which is milk already dried to a solid, loosened with a little hot milk, stands in for the hour of reduction. It comes out thicker and less delicate, and most sweet shops work this way because nobody can wait an hour.',
           no:'Khoya er melk som alt er kokt inn til en fast masse, og spedd med litt varm melk kan den erstatte timen med innkoking. Resultatet blir tykkere og mindre fint, og de fleste butikker som selger indiske søtsaker, gjør det slik, for ingen har en time å vente.'}},
    {title:{en:'Fried in oil', no:'Stekt i olje'},
     body:{en:'Ghee is the traditional fat, and a neutral oil fries the bread just as well. Add a little ghee to the pan for the last batch, because most of what ghee contributes here is smell rather than texture.',
           no:'Ghee er det tradisjonelle fettet, og en nøytral olje steker brødet like godt. Ha litt ghee i pannen til den siste omgangen, for her bidrar gheen mest med duft og ikke med konsistens.'}}]
},

{
  id:'nihari', dish:'Nihari', course:'main', lesson:3, serves:6, veg:false,
  time:{prep:30, cook:300}, hero:'nihari', tags:['stew','overnight','marrow','potli'],
  title:{en:'Nihari', no:'Nihari'},
  blurb:{en:'Shank and marrow bones under a sealed lid for hours, thickened by their own collagen and perfumed with a potli.',
         no:'Skank og margbein under forseglet lokk i timevis, tyknet av sitt eget kollagen og parfymert med en potli.'},
  heroCaption:{en:'The ginger, the green chilli and the lime are not garnish. They are what cuts through five hours of fat.',
               no:'Ingefæren, den grønne chilien og limen er ikke pynt. De skjærer gjennom fem timer med fett.'},
  goesWith:[{en:'Khameeri roti, or a sheermal with the sugar left out', no:'Khameeri roti, eller en sheermal uten sukker'},
            {en:'Nothing else at all before midday', no:'Ikke noe mer før midt på dagen'}],
  headnote:{
    en:`<p>Nihari is a breakfast, and the name says so, because nahar is the Arabic word for morning. The pot goes on in the evening, the fire is left to die under it, and what is opened at dawn is meat falling off the bone in a gravy the bones have already thickened. That gravy is the argument for the whole method, because most of what holds it together came out of the bones, and the flour at the end only finishes the job.</p>
<p>Two things do the heavy work. Gelatinous cuts, and shank above all, give up collagen slowly and turn a thin stock into something that coats a spoon. And the spice arrives in a muslin bag that is lifted out before serving, so the broth stays clear instead of going muddy the way a powdered masala would leave it.</p>
<p>Written for a domestic kitchen this is a five-hour dish rather than an eight-hour one, and it can be split across two sittings. Cook it the evening before, cool it and reheat it in the morning. It is better for the night in the fridge, and the fat that sets on top is easy either to lift off or to stir back in.</p>`,
    no:`<p>Nihari er frokost, og navnet sier det, for nahar er det arabiske ordet for morgen. Gryta settes over om kvelden, ilden får dø ut under den, og ved daggry åpnes gryta over kjøtt som faller av beinet i en saus beina alt har tyknet. Nettopp den sausen er argumentet for hele metoden, for det meste av det som holder den sammen, er kommet ut av beina, og melet til slutt gjør bare jobben ferdig.</p>
<p>To ting gjør det tunge arbeidet. Stykker med mye bindevev, og særlig skank, gir langsomt fra seg kollagen og gjør en tynn kraft om til noe som legger seg på skjeen. Og krydderet kommer i en pose av musselin som løftes opp før servering, så kraften holder seg klar i stedet for å bli grumsete slik en malt masala ville gjort den.</p>
<p>I et hjemmekjøkken tar denne retten fem timer og ikke åtte, og den kan deles over to økter. Kok den kvelden før, kjøl den ned og varm den opp om morgenen. Den blir bedre av natta i kjøleskapet, og fettet som stivner på toppen, er lett enten å løfte av eller å røre inn igjen.</p>`},
  ingredients:[
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:1.2, u:'kg', n:{en:'lamb or goat shank, cut across the bone', no:'skank av lam eller geit, skåret på tvers av beinet'}},
    {q:400, u:'g', n:{en:'marrow bones', no:'margbein'}},
    {q:300, u:'g', n:{en:'onion', no:'løk'}, note:{en:'finely sliced', no:'i tynne skiver'}},
    {q:120, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:30, u:'g', n:{en:'ginger and garlic, ground to a paste', no:'ingefær og hvitløk, most til en jevn masse'}},
    {q:8, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri-chilipulver'}},
    {q:5, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:2, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:100, u:'g', n:{en:'plain flour, for the seal', no:'hvetemel, til forseglingen'}, scale:'none', note:{en:'worked with water into a stiff dough; foil under a tight lid also works', no:'arbeidet ut med vann til en fast deig; folie under et tett lokk gjør også nytten'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The potli', no:'Potlien'}, items:[
    {q:4, u:'g', n:{en:'fennel seed', no:'fennikelfrø'}},
    {q:3, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:3, u:'g', n:{en:'mace blades', no:'hel muskatblomme'}},
    {q:4, u:'g', n:{en:'green cardamom pods', no:'hele grønne kardemommekapsler'}},
    {q:2, u:'', n:{en:'black cardamom pods', no:'svarte kardemommekapsler'}, round:'half'},
    {q:1, u:'', n:{en:'cinnamon stick', no:'kanelstang'}, round:'half'},
    {q:3, u:'g', n:{en:'black peppercorns', no:'hele svarte pepperkorn'}},
    {q:2, u:'g', n:{en:'cloves', no:'nellik'}},
    {q:2, u:'g', n:{en:'long pepper, or more peppercorns', no:'langpepper, eller flere pepperkorn'}},
   ]},
   {group:{en:'To finish and to serve', no:'Til slutt og til bordet'}, items:[
    {q:50, u:'g', n:{en:'plain flour, for thickening', no:'hvetemel, til jevning'}, note:{en:'whisked into cold water', no:'vispet ut i kaldt vann'}},
    {q:40, u:'g', n:{en:'ghee, for the final tempering', no:'ghee, til tadkaen på toppen'}, scale:'none'},
    {q:4, u:'g', n:{en:'Kashmiri chilli powder, for the tempering', no:'Kashmiri-chilipulver, til tadkaen'}, scale:'none'},
    {q:40, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'in fine matchsticks', no:'i tynne strimler'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chilier'}, round:'half', note:{en:'sliced', no:'i skiver'}},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
    {q:1, u:'', n:{en:'lime', no:'lime'}, round:'half'},
   ]}],
  steps:[
    {en:'Tie the potli spices into a square of muslin and knot it loosely, so the liquid can move through the bag.',
     no:'Knyt krydderet til potlien inn i en firkant av musselin, og la knuten sitte løst så væsken kan gå gjennom posen.'},
    {en:'Fry the sliced onion in ghee over a medium flame until it is deep brown. Lift half of it out onto paper and keep it back for the table.',
     no:'Stek løkskivene i ghee på middels varme til de er dypt brune. Løft halvparten over på papir og hold den igjen til bordet.'},
    {en:'Stir the ginger and garlic into the pan and cook it for two minutes, then add the chilli powder and the turmeric and stir for thirty seconds, no longer.',
     no:'Rør ingefæren og hvitløken inn i pannen og la det gå i to minutter, ha så i chilipulveret og gurkemeien og rør i tretti sekunder, ikke lenger.'},
    {en:'Add the shank and the marrow bones and turn them in the spiced fat until they are coated all over.',
     no:'Ha i skanken og margbeina og vend dem i det krydrede fettet til de er dekket overalt.'},
    {en:'Pour in the water, drop in the potli, salt it, and bring it to a bare simmer.',
     no:'Hell i vannet, slipp ned potlien, salt, og la det så vidt begynne å småkoke.'},
    {en:'Seal the lid on with a rope of stiff dough, or clamp it down over a sheet of foil, and cook on the lowest heat for four to five hours. Do not stir it at any point.',
     no:'Fest lokket med en pølse av fast deig, eller klem det ned over et ark folie, og la gryta stå på lavest mulig varme i fire til fem timer. Ikke rør i den underveis.'},
    {en:'Take the potli out and squeeze it against the side of the pot with a spoon. Lift the meat and the bones out onto a plate.',
     no:'Ta opp potlien og klem den mot grytekanten med en skje. Løft kjøttet og beina over på et fat.'},
    {en:'Whisk the thickening flour into cold water until there is no lump left, pour it into the simmering broth in a thin stream while stirring, and cook for ten minutes, until the gravy coats a spoon.',
     no:'Visp jevningsmelet ut i kaldt vann til det ikke er en klump igjen, hell det i den småkokende kraften i en tynn stråle mens du rører, og la det koke i ti minutter, til sausen legger seg på en skje.'},
    {en:'Slide the meat and the bones back in and let them warm through.',
     no:'La kjøttet og beina gli ned i gryta igjen og varmes gjennom.'},
    {en:'Heat the ghee for the tempering, take it off the heat, stir the chilli powder into it and pour it over the surface of the pot.',
     no:'Varm gheen til tadkaen, ta den av platen, rør chilipulveret ut i den og hell den over overflaten i gryta.'},
    {en:'Serve it in deep bowls, a marrow bone in each, under the reserved fried onion, the ginger matchsticks, the green chilli, the coriander and a wedge of lime.',
     no:'Server i dype skåler, med et margbein i hver, under den stekte løken du holdt igjen, ingefærstrimlene, den grønne chilien, korianderen og en limebåt.'}],
  notes:[
    {title:{en:'Why nothing is stirred for five hours', no:'Hvorfor ingenting røres på fem timer'},
     body:{en:'Stirring breaks shank into shreds long before the collagen has finished converting, and shreds make a stew look tired. Left alone, the meat holds together right up to the moment it is served and then gives way under a spoon. It is also why the pot is sealed rather than watched.',
           no:'Røring river skanken i trevler lenge før kollagenet er ferdig omdannet, og trevler får en gryte til å se sliten ut. Får kjøttet ligge i fred, henger det sammen helt til det serveres og gir seg først under skjeen. Det er også derfor gryta forsegles i stedet for å passes på.'}},
    {title:{en:'What the potli spares you', no:'Hva potlien sparer deg for'},
     body:{en:'Ground spice added at the start would spend five hours in the pot, darken the broth and settle as grit in the bottom of every bowl. Whole spice in muslin gives its oils up to the liquid and then walks out with the bag, which is why a good nihari manages to be red and clear at once.',
           no:'Malt krydder som går i fra starten, ville ligget fem timer i gryta, gjort kraften mørk og lagt seg som grums i bunnen av hver skål. Hele krydder i musselin gir fra seg oljene sine til væsken og forlater så gryta sammen med posen, og derfor klarer en god nihari å være rød og klar på én gang.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Ask for lamb shank cut across the bone in rounds, so that the marrow shows in every slice; a halal butcher cuts it that way without being asked. Marrow bones are cheap at any butcher and often free if you ask for them.',
           no:'Be om skank av lam skåret i skiver på tvers av beinet, så margen synes i hver skive, og en halalslakter skjærer den slik uten at du spør. Margbein er billige hos enhver slakter og ofte gratis om du ber om det. Langpepper selges som pippali i indiske butikker og kan sløyfes, og muskatblomme heter javitri der. Får du tak i geitekjøtt, bruk heller det enn lam, for geita tåler de fem timene bedre.'}}],
  variations:[
    {title:{en:'Nalli nihari', no:'Nalli nihari'},
     body:{en:'Make the marrow bones the main event rather than a garnish, one large one for each person, and use less shank. The marrow is scooped out with a thin spoon and stirred into the gravy at the table.',
           no:'Gjør margbeina til hovedsaken i stedet for pynt, ett stort til hver, og bruk mindre skank. Margen skrapes ut med en tynn skje og røres inn i sausen ved bordet.'}},
    {title:{en:'Chicken, in one evening', no:'Kylling, på én kveld'},
     body:{en:'Chicken thighs and wings on the bone make a nihari in ninety minutes. It has less body, so keep the flour in and add a lamb trotter or a spoonful of set stock if you have one.',
           no:'Kyllinglår og vinger med bein gir en nihari på halvannen time. Den har mindre fylde, så behold melet, og ha gjerne i en lammelabb eller en skje stiv kraft hvis du har det.'}},
    {title:{en:'The taar', no:'Taar'},
     body:{en:'Keep a ladleful back, cool it and freeze it, and pour it into the next pot you make. A shop does this daily and says its pot has run unbroken for decades. A home kitchen manages it perhaps monthly, and even then the second pot is noticeably deeper than the first.',
           no:'Hold igjen en øse, kjøl den ned og frys den, og hell den i den neste gryta du lager. En butikk gjør det hver dag og sier at gryta har gått ubrutt i tiår. Et hjemmekjøkken får det kanskje til en gang i måneden, og selv da er den andre gryta merkbart dypere i smaken enn den første.'}}]
}

];
