/* Masala Dabba — recipes for Bengal & the east (IN-BEN). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-BEN'] = [

{
  id:'shorshe-ilish', dish:'Shorshe ilish', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:25, cook:20}, hero:'shorshe-ilish', tags:['fish','mustard','monsoon'],
  title:{en:'Shorshe ilish, and what to do without ilish', no:'Shorshe ilish, og hva du gjør uten ilish'},
  blurb:{en:'Fatty fish steaks in a raw mustard paste, barely cooked, with green chillies and raw mustard oil.',
         no:'Koteletter av fet fisk i en rå sennepspasta, så vidt kokt, med grønn chili og rå sennepsolje.'},
  heroCaption:{en:'This version keeps the gravy pale and cooks the fish gently so its rich flesh stays moist.',
               no:'Denne utgaven holder sausen lys og koker fisken forsiktig så det fete kjøttet holder seg saftig.'},
  goesWith:[{en:'Plain boiled rice', no:'Vanlig kokt ris'},
            {en:'A green chilli eaten raw on the side', no:'En rå grønn chili ved siden av'}],
  headnote:{
    en:`<p>Hilsa may be difficult to source in Norway, and another fish will make an adaptation rather than the same dish. This recipe uses mackerel because its rich flesh stands up well to mustard and remains moist during gentle cooking.</p>
<p>Fish choice is still more than fat content: hilsa and mackerel have different flavour, bones and texture. The title keeps the reference to shorshe ilish while the ingredient list and notes state the substitution plainly.</p>
<p>This course method grinds yellow and black mustard briefly, sieves the paste and cooks it gently. Seed ratios and handling affect pungency and bitterness. Use only mustard oil labelled for food, including the optional finishing oil.</p>`,
    no:`<p>Ilish kan være vanskelig å finne i Norge, og en annen fisk gir en tilpasning framfor den samme retten. Oppskriften bruker makrell fordi det fete kjøttet tåler sennep godt og holder seg saftig ved forsiktig koking.</p>
<p>Fiskevalget handler likevel om mer enn fett: ilish og makrell har ulik smak, beinstruktur og konsistens. Tittelen beholder henvisningen til shorshe ilish, mens råvarelista og merknadene sier tydelig fra om byttet.</p>
<p>Kursmetoden maler gule og svarte sennepsfrø kort, siler pastaen og koker den forsiktig. Blandingsforhold og behandling påvirker styrke og bitterhet. Bruk bare sennepsolje som er merket for mat, også til slutt.</p>`},
  ingredients:[
   {group:{en:'The mustard paste', no:'Sennepspastaen'}, items:[
    {q:45, u:'g', n:{en:'yellow mustard seed', no:'gule sennepsfrø'}, note:{en:'soaked 20 minutes in warm water', no:'bløtlagt i 20 minutter i lunkent vann'}},
    {q:15, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The fish', no:'Fisken'}, items:[
    {q:800, u:'g', n:{en:'mackerel, in thick steaks', no:'makrell, i tykke koteletter'}, note:{en:'or hilsa if you can get it; skin on, bone in', no:'eller ilish om du får tak i den; med skinn og bein'}},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}, note:{en:'for rubbing the fish', no:'til å gni inn fisken med'}},
    {q:60, u:'ml', n:{en:'mustard oil', no:'sennepsolje'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'flekket på langs'}},
    {q:200, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15, u:'ml', n:{en:'raw mustard oil, to finish', no:'rå sennepsolje, til slutt'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Soak both kinds of mustard seed in warm water for twenty minutes, then drain them.',
     no:'Bløtlegg begge slags sennepsfrø i lunkent vann i tjue minutter, og hell så av vannet.'},
    {en:'Grind the drained seed with the chillies, the turmeric, a good pinch of salt and just enough cold water to move the blades. Stop as soon as it is smooth.',
     no:'Kjør frøene sammen med chiliene, gurkemeien, en god klype salt og akkurat nok kaldt vann til at knivene går rundt. Stopp så snart pastaen er glatt.'},
    {en:'Push the paste through a sieve and throw away the husks. Taste it: it should be sharp and salty, not bitter. If it is bitter, you ground it too long and it is worth starting again.',
     no:'Press pastaen gjennom en sil og kast skallrestene. Smak på den: den skal være skarp og salt, ikke bitter. Er den bitter, har du malt for lenge, og det lønner seg å begynne på nytt.'},
    {en:'Rub the fish steaks with turmeric and salt and leave them for ten minutes.',
     no:'Gni fiskekotelettene inn med gurkemeie og salt, og la dem ligge i ti minutter.'},
    {en:'Heat the mustard oil in a wide pan over medium-high heat until it shimmers and its raw aroma softens; follow the label and do not leave smoking oil unattended.',
     no:'Varm sennepsoljen i en vid panne på middels høy varme til den skinner og den rå duften mildnes. Følg merkingen og ikke la rykende olje stå uten tilsyn.'},
    {en:'Return the pan to a medium flame and lay the fish in a single layer. Give it a minute a side, only until the surface sets. Do not brown it.',
     no:'Sett pannen tilbake på middels varme og legg fisken i ett lag. Gi den et minutt på hver side, bare til overflaten stivner. Ikke brun den.'},
    {en:'Stir the mustard paste into the water, pour it around the fish and add the slit chillies. Salt it lightly.',
     no:'Rør sennepspastaen ut i vannet, hell blandingen rundt fisken og ha i de flekkede chiliene. Salt lett.'},
    {en:'Cover and cook over a low flame for eight to ten minutes. Swirl the pan instead of stirring, or the steaks break up.',
     no:'Legg på lokk og la det stå på lav varme i åtte til ti minutter. Sving på pannen i stedet for å røre, ellers går kotelettene i stykker.'},
    {en:'The gravy should be pale yellow and just thick enough to coat a spoon. If it is watery, lift the fish out and reduce it for a minute, then put the fish back.',
     no:'Sausen skal være lysegul og akkurat tykk nok til å legge seg på en skje. Er den vassen, løft ut fisken, kok sausen inn i et minutt og legg fisken tilbake.'},
    {en:'Take the pan off the heat, pour the raw mustard oil over and cover it again. Let it stand for ten minutes before serving with rice.',
     no:'Ta pannen av platen, hell den rå sennepsoljen over og legg på lokket igjen. La det stå i ti minutter før du serverer med ris.'}],
  notes:[
    {title:{en:'Why the paste must not be overworked', no:'Hvorfor pastaen ikke må males for lenge'},
     body:{en:'Water activates mustard enzymes and helps create its pungency. Seed colour, soaking, temperature and grind all affect the result. Grind only until smooth for this recipe, then taste before cooking and adjust with more yellow mustard if needed.',
           no:'Vann aktiverer enzymer i sennepen og bidrar til skarpheten. Frøfarge, bløtlegging, temperatur og maling påvirker resultatet. Mal bare til glatt i denne oppskriften, smak før koking og juster med mer gul sennep ved behov.'}},
    {title:{en:'Why fat matters more than species', no:'Hvorfor fettet betyr mer enn arten'},
     body:{en:'Fat softens mustard\'s sharpness and gives the thin gravy body. Lean fish can also be used, but it cooks faster and produces a lighter result; reduce the cooking time and add a little more edible mustard oil if desired.',
           no:'Fett runder av sennepens skarphet og gir den tynne sausen fylde. Mager fisk kan også brukes, men blir raskere ferdig og gir et lettere resultat. Kort ned koketiden og tilsett eventuelt litt mer spiselig sennepsolje.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy mackerel whole and ask the counter to cut it across into steaks rather than filleting it, because the bone holds the flesh together in the gravy.',
           no:'Kjøp hel makrell og be om koteletter skåret på tvers av beinet; beinet holder fisken samlet i sausen. Kjøp bare sennepsolje som er tydelig merket for matbruk. «Kachi ghani» beskriver pressing, men er ikke i seg selv en spiselighetsmerking. Tin frossen fisk i kjøleskapet.'}}],
  variations:[
    {title:{en:'Bhapa: steamed instead', no:'Bhapa: dampet i stedet'},
     body:{en:'Mix the fish, the paste, the chillies and the oil in a tin with a tight lid, and steam the closed tin over boiling water for fifteen minutes. Nothing is fried at all, and the result is cleaner and even sharper.',
           no:'Bland fisken, pastaen, chiliene og oljen i en boks med tett lokk, og damp den lukkede boksen over kokende vann i femten minutter. Ingenting stekes, og resultatet blir renere og enda skarpere.'}},
    {title:{en:'With poppy seed', no:'Med valmuefrø'},
     body:{en:'Grind white poppy seed with the mustard in equal weight. The paste turns milder and thicker, which suits a leaner fish and is how many households cook it midweek.',
           no:'Mal hvite valmuefrø sammen med sennepen, like mye av hver. Pastaen blir mildere og tykkere, og det passer en magrere fisk. Mange husholdninger lager den slik midt i uka.'}},
    {title:{en:'Prawns in mustard', no:'Reker i sennep'},
     body:{en:'Raw shell-on prawns work in exactly the same sauce and need four minutes rather than ten. Bengal calls that chingri, and treats it as a different dish rather than a substitute.',
           no:'Rå reker med skall fungerer i akkurat samme saus og trenger fire minutter i stedet for ti. Bengal kaller det chingri og regner det som en egen rett, ikke som en erstatning.'}}]
},

{
  id:'macher-jhol', dish:'Macher jhol', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:20, cook:30}, hero:'macher-jhol', tags:['fish','everyday','nigella'],
  title:{en:'Macher jhol', no:'Macher jhol'},
  blurb:{en:'A light Bengali fish curry with nigella, green chilli and potato.',
         no:'En lett bengalsk fiskekarri med svartkarve, grønn chili og potet.'},
  heroCaption:{en:'This jhol has a thin yellow gravy with visible nigella seed; other jhol styles vary.',
               no:'Denne jholen har en tynn gul saus med synlige svartkarvefrø; andre varianter er annerledes.'},
  goesWith:[{en:'A mound of plain rice', no:'En haug med vanlig ris'},
            {en:'A fried slice of aubergine on the side', no:'En stekt skive aubergine ved siden av'}],
  headnote:{
    en:`<p>Macher jhol is a broad family of fish dishes rather than one fixed recipe. This course version has a light gravy designed to mix with rice, with nigella, ginger, green chilli and potato.</p>
<p>The fish is fried briefly and lifted out before the gravy is built in the same oil. This firms the surface and reduces breakage when the fish returns. Other households use different fish, vegetables and temperings.</p>
<p>Potato absorbs the seasoned gravy and makes this version more substantial. It is a choice, not padding or a test of completeness; aubergine, pointed gourd, cauliflower or no vegetable may suit another jhol.</p>`,
    no:`<p>Macher jhol er en bred familie av fiskeretter, ikke én fast oppskrift. Kursutgaven har en lett saus som blandes med ris, med svartkarve, ingefær, grønn chili og potet.</p>
<p>Fisken stekes kort og løftes ut før sausen bygges i den samme oljen. Det strammer overflaten og reduserer faren for at fisken går i stykker når den legges tilbake. Andre husholdninger bruker andre fisker, grønnsaker og temperinger.</p>
<p>Poteten trekker til seg den krydrede sausen og gjør denne utgaven mer mettende. Den er et valg, ikke fyllstoff eller en fullstendighetsprøve; aubergine, spisskalebass, blomkål eller ingen grønnsak kan passe i en annen jhol.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:700, u:'g', n:{en:'firm white fish, in steaks', no:'fast hvit fisk, i koteletter'}, note:{en:'carp is traditional; sei, cod or hake all work', no:'karpe er det tradisjonelle; sei, torsk eller lysing fungerer'}},
    {q:400, u:'g', n:{en:'waxy potatoes', no:'fastkokende poteter'}, note:{en:'in thick wedges', no:'i tykke båter'}},
    {q:60, u:'ml', n:{en:'mustard oil', no:'sennepsolje'}},
    {q:5, u:'g', n:{en:'nigella seed', no:'svartkarve'}},
    {q:4, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'flekket på langs'}},
    {q:25, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:8, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:6, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri chilipulver'}, note:{en:'for colour, not heat', no:'for fargen, ikke styrken'}},
    {q:6, u:'g', n:{en:'ground cumin', no:'malt spisskummen'}},
    {q:700, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Rub the fish steaks with half the turmeric and a good pinch of salt, and leave them for ten minutes.',
     no:'Gni fiskekotelettene inn med halvparten av gurkemeien og en god klype salt, og la dem ligge i ti minutter.'},
    {en:'Heat edible mustard oil in a wide pan over medium-high heat until it shimmers. Fry the fish for about two minutes a side, until the surface is set and pale gold, then lift it out.',
     no:'Varm spiselig sennepsolje i en vid panne på middels høy varme til den skinner. Stek fisken i omtrent to minutter på hver side, til overflaten er stivnet og lysegyllen, og løft den ut.'},
    {en:'Fry the potato wedges in the same oil until their edges brown a little. Lift them out too.',
     no:'Stek potetbåtene i den samme oljen til kantene bruner seg litt. Løft dem ut de også.'},
    {en:'Drop the nigella seed and two of the slit chillies into the oil. They will crackle within seconds.',
     no:'Slipp svartkarven og to av de flekkede chiliene i oljen. De knitrer i løpet av sekunder.'},
    {en:'Stir in the ginger paste and cook it for a minute, until it stops smelling raw.',
     no:'Rør inn ingefærpastaen og la den surre et minutt, til den slutter å lukte rått.'},
    {en:'Pull the pan off the heat and stir in the rest of the turmeric, the chilli powder and the cumin, so the ground spices colour the oil instead of burning in it.',
     no:'Trekk pannen av platen og rør inn resten av gurkemeien, chilipulveret og spisskummen, så det malte krydderet farger oljen i stedet for å svi seg i den.'},
    {en:'Return the pan, add the water and the potatoes, salt it, and simmer uncovered until the potatoes are nearly tender, about twelve minutes.',
     no:'Sett pannen tilbake, ha i vannet og potetene, salt, og la det småkoke uten lokk til potetene nesten er møre, omtrent tolv minutter.'},
    {en:'Slide the fish back in with the remaining chillies. Simmer very gently for six minutes, swirling the pan rather than stirring.',
     no:'Legg fisken tilbake sammen med resten av chiliene. La det småkoke svært forsiktig i seks minutter, og sving på pannen i stedet for å røre.'},
    {en:'Taste for salt. The gravy should still be thin enough to pour and clear enough to see the nigella seeds in.',
     no:'Smak til med salt. Sausen skal fortsatt være tynn nok til å helles og klar nok til at du ser svartkarven i den.'},
    {en:'Scatter the coriander over, take the pan off the heat and let it stand for five minutes before serving.',
     no:'Strø korianderen over, ta pannen av platen og la den stå i fem minutter før servering.'}],
  notes:[
    {title:{en:'Why the fish comes out and goes back', no:'Hvorfor fisken tas ut og legges tilbake'},
     body:{en:'A quick fry sets the proteins at the surface, and a set surface holds a steak together through twenty minutes in liquid. Cooking the fish all the way through in the gravy instead leaves you with shreds and a cloudy jhol.',
           no:'En rask steking får proteinene på overflaten til å stivne, og en stivnet overflate holder en kotelett sammen gjennom tjue minutter i væske. Koker du fisken gjennom i sausen i stedet, sitter du igjen med tråder og en uklar jhol.'}},
    {title:{en:'Why the ground spice goes in off the heat', no:'Hvorfor det malte krydderet går i med kjelen av platen'},
     body:{en:'Ground turmeric and chilli burn at a far lower temperature than whole seeds, and burnt chilli powder is bitter in a way nothing later can fix. Taking the pan off for fifteen seconds removes the risk entirely.',
           no:'Malt gurkemeie og chili svir seg ved langt lavere temperatur enn hele frø, og svidd chilipulver er bittert på en måte ingenting senere retter opp. Trekker du pannen av i femten sekunder, er risikoen helt borte.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Ask the fish counter for steaks cut across the bone rather than fillets, whatever the species. A bone-in steak survives the gravy and a fillet does not.',
           no:'Be fiskedisken om koteletter skåret på tvers av beinet i stedet for filet, uansett art. En kotelett med bein tåler sausen; det gjør ikke en filet. Sei er en billig og god fisk til denne retten, og fastere enn torsk. Svartkarve heter kalonji i indiske butikker og er ikke det samme som svart sesam, uansett hva det står på hylla. Kashmiri chilipulver gir farge uten styrke; vanlig norsk chilipulver er sterkere og gir feil farge.'}}],
  variations:[
    {title:{en:'With cauliflower and peas', no:'Med blomkål og erter'},
     body:{en:'In winter many households add cauliflower florets and fresh peas with the potato. The dish stays a jhol, but it stops being mainly about the fish.',
           no:'Om vinteren har mange husholdninger i blomkålbuketter og ferske erter sammen med poteten. Retten er fortsatt en jhol, men den handler ikke lenger mest om fisken.'}},
    {title:{en:'Niramish, without onion or garlic', no:'Niramish, uten løk og hvitløk'},
     body:{en:'This version already has neither, which is not an accident. Many Bengali fish dishes are cooked in the widow\'s style, with ginger instead of onion and garlic, and they are the cleaner-tasting for it.',
           no:'Denne utgaven har verken det ene eller det andre fra før, og det er ikke tilfeldig. Mange bengalske fiskeretter lages niramish, altså uten løk og hvitløk, med ingefær i stedet, og de smaker renere av det.'}}]
},

{
  id:'kosha-mangsho', dish:'Kosha mangsho', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:30, cook:120}, hero:'kosha-mangsho', tags:['goat','Sunday','slow'],
  title:{en:'Kosha mangsho', no:'Kosha mangsho'},
  blurb:{en:'Goat fried down over an hour until the gravy stops being gravy and clings to the meat.',
         no:'Geitekjøtt stekt ned i en time til sausen slutter å være saus og legger seg rundt kjøttet.'},
  heroCaption:{en:'Almost no free liquid is left. What remains is dark, thick and stuck to the meat.',
               no:'Nesten ingen fri væske er igjen. Det som er tilbake, er mørkt, tykt og klistret til kjøttet.'},
  goesWith:[{en:'Luchi, the small puffed wheat breads', no:'Luchi, de små oppblåste hvetebrødene'},
            {en:'Plain rice, if you want it plainer', no:'Vanlig ris, hvis du vil ha det enklere'}],
  headnote:{
    en:`<p>Kosha describes slow browning and reduction with limited liquid. In this kosha mangsho, goat and aromatics are repeatedly cooked down and loosened with small additions of water until the gravy is dark and clings to the meat.</p>
<p>The cycle dissolves browned material from the base and gives the cook control over colour and moisture. Frequency and timing are guides rather than a fixed count; keep the pan from scorching and add enough liquid to tenderise the cut.</p>
<p>The dish is associated with leisurely and celebratory meals in Kolkata. Refrigerated marination can begin the day before, but the meat should remain chilled until shortly before cooking.</p>`,
    no:`<p>Kosha beskriver langsom bruning og innkoking med lite væske. I denne kosha mangsho kokes geit og aromater gjentatte ganger inn og løsnes med små mengder vann til sausen er mørk og legger seg rundt kjøttet.</p>
<p>Rundene løser det brunede laget fra bunnen og gir kokken kontroll over farge og væske. Antall og tid er veiledende; unngå at gryta svir seg, og tilsett nok væske til å mørne kjøttstykket.</p>
<p>Retten forbindes med rolige og festlige måltider i Kolkata. Marineringen kan begynne i kjøleskapet dagen før, men kjøttet skal holdes kaldt til kort tid før koking.</p>`},
  ingredients:[
   {group:{en:'The marinade', no:'Marinaden'}, items:[
    {q:900, u:'g', n:{en:'goat on the bone', no:'geitekjøtt med bein'}, note:{en:'shoulder and leg, in large pieces', no:'bog og lår, i store biter'}},
    {q:200, u:'g', n:{en:'natural yoghurt', no:'naturell yoghurt'}, note:{en:'whisked smooth', no:'pisket glatt'}},
    {q:30, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:25, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:8, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:450, u:'g', n:{en:'onions', no:'løk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:60, u:'ml', n:{en:'mustard oil', no:'sennepsolje'}},
    {q:30, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:15, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:6, u:'', n:{en:'green cardamom pods', no:'grønne kardemommekapsler'}, round:'half', note:{en:'bruised', no:'lett knust'}},
    {q:6, u:'', n:{en:'cloves', no:'hele nellik'}, round:'half'},
    {q:1, u:'', n:{en:'piece of cinnamon bark', no:'bit kanelbark'}, round:'half'},
    {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
    {q:10, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri chilipulver'}},
    {q:10, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:5, u:'g', n:{en:'ground cumin', no:'malt spisskummen'}},
    {q:4, u:'g', n:{en:'garam masala', no:'garam masala'}, note:{en:'to finish', no:'til slutt'}},
    {q:400, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub', note:{en:'added a splash at a time', no:'has i en skvett om gangen'}},
   ]}],
  steps:[
    {en:'Mix the goat with the yoghurt, ginger, garlic, turmeric and salt. Leave it in the fridge for at least four hours, or overnight, and take it out an hour before you cook.',
     no:'Bland geitekjøttet med yoghurten, ingefæren, hvitløken, gurkemeien og saltet. La det stå i kjøleskapet i minst fire timer, gjerne over natten, og ta det ut en time før du skal lage mat.'},
    {en:'Heat edible mustard oil in a heavy pan over medium-high heat until it shimmers. Add the sugar and let it darken to the colour of strong tea, watching closely so it does not burn.',
     no:'Varm spiselig sennepsolje i en tung gryte på middels høy varme til den skinner. Ha i sukkeret og la det mørkne til fargen av sterk te; følg nøye med så det ikke brenner.'},
    {en:'Add the cardamom, clove, cinnamon and bay, wait until they smell, then add the onion. Fry it over a medium flame until it is properly brown, fifteen to twenty minutes.',
     no:'Ha i kardemomme, nellik, kanel og laurbær, vent til det dufter, og ha så i løken. Stek den på middels varme til den er skikkelig brun, femten til tjue minutter.'},
    {en:'Tip in the marinated meat with all its yoghurt and turn the heat up. Stir until the yoghurt has boiled off and the meat begins to sizzle rather than simmer.',
     no:'Ha i det marinerte kjøttet med all yoghurten og skru opp varmen. Rør til yoghurten har kokt inn og kjøttet begynner å frese i stedet for å småkoke.'},
    {en:'Pull the pan off the heat, stir in the chilli powder, coriander and cumin, then put it back on a medium flame.',
     no:'Trekk gryta av platen, rør inn chilipulveret, korianderen og spisskummen, og sett den tilbake på middels varme.'},
    {en:'Now start the kosha. Fry, stirring, until the pan dries and the mixture begins to stick, then add a splash of the hot water and scrape the base clean. Repeat.',
     no:'Nå begynner koshaen. Stek under omrøring til gryta tørker og blandingen begynner å sette seg fast, ha så i en skvett av det varme vannet og skrap bunnen ren. Gjenta.'},
    {en:'Keep that cycle going for forty-five minutes to an hour. The mixture should get darker every time, and the smell should change from raw spice to something roasted.',
     no:'Hold den runden gående i tre kvarter til en time. Blandingen skal bli mørkere for hver gang, og lukten skal gå fra rått krydder til noe ristet.'},
    {en:'When the meat gives under a spoon, add the last of the water, cover, and cook on the lowest heat for twenty minutes.',
     no:'Når kjøttet gir etter for en skje, ha i resten av vannet, legg på lokk og la det stå på lavest mulig varme i tjue minutter.'},
    {en:'Take the lid off and raise the heat for the last few minutes, until the fat separates out and there is almost no free liquid left in the pan.',
     no:'Ta av lokket og skru opp varmen de siste minuttene, til fettet skiller seg ut og det nesten ikke er fri væske igjen i gryta.'},
    {en:'Stir in the ghee and the garam masala, cover, and let it stand for fifteen minutes before serving.',
     no:'Rør inn gheen og garam masalaen, legg på lokk, og la retten stå i femten minutter før servering.'}],
  notes:[
    {title:{en:'Why the splash of water is the whole method', no:'Hvorfor skvetten med vann er hele metoden'},
     body:{en:'Every time the pan dries out, a browned layer forms on the base, and the water dissolves it back into the dish. Adding all the liquid at once would give you a stew: the meat would be tender and the flavour would be flat.',
           no:'Hver gang gryta tørker ut, danner det seg et brunet lag i bunnen, og vannet løser det tilbake i retten. Har du i all væsken på én gang, får du en gryterett: kjøttet blir mørt og smaken flat.'}},
    {title:{en:'Why the sugar goes into the oil first', no:'Hvorfor sukkeret går i oljen først'},
     body:{en:'Caramelised sugar gives the colour that a Bengali cook expects from this dish, and it does it without the chilli powder having to carry the load. It is not there to sweeten anything, and a few seconds too long makes it bitter.',
           no:'Karamellisert sukker gir den fargen en bengalsk kokk venter av denne retten, og det uten at chilipulveret må gjøre jobben. Det er ikke der for å søte noe, og noen sekunder for lenge gjør det bittert.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Goat shoulder or leg on the bone gives a firm texture suited to a long kosha. Lamb shoulder works too but usually finishes sooner. Ask a well-stocked butcher for the cut, and adjust the simmer to the meat rather than the clock.',
           no:'Geitebog eller lår med bein gir en fast konsistens som passer til lang kosha. Lammebog fungerer også, men blir vanligvis ferdig tidligere. Spør en velassortert slakter om stykket, og tilpass koketiden til kjøttet framfor klokka.'}}],
  variations:[
    {title:{en:'With potato', no:'Med potet'},
     body:{en:'Many Kolkata households fry whole small potatoes in the oil at the start and return them for the last twenty minutes. It is the same instinct that puts a potato in the fish curry and in the biryani.',
           no:'Mange husholdninger i Kolkata steker hele småpoteter i oljen i starten og legger dem tilbake de siste tjue minuttene. Det er den samme tanken som legger potet i fiskekarrien og i biryanien.'}},
    {title:{en:'Chicken instead', no:'Med kylling i stedet'},
     body:{en:'Use thighs on the bone and cut the kosha down to twenty-five minutes. The cycle is the same, but chicken cannot take an hour of it and will fall off the bone into the gravy.',
           no:'Bruk lår med bein og kort koshaen ned til tjuefem minutter. Runden er den samme, men kylling tåler ikke en time av den og vil falle av beinet og ut i sausen.'}}]
},

{
  id:'shukto', dish:'Shukto', course:'side', lesson:2, serves:4, veg:true,
  time:{prep:25, cook:30}, hero:'shukto', tags:['bitter','vegetarian','first course'],
  title:{en:'Shukto', no:'Shukto'},
  blurb:{en:'One shukto style: mixed vegetables balanced with bitterness, poppy seed, mustard and milk.',
         no:'Én shukto-stil: blandede grønnsaker balansert med bitterhet, valmuefrø, sennep og melk.'},
  heroCaption:{en:'Everything is cut into batons of the same length, so the vegetables cook evenly and can be picked up.',
               no:'Alt skjæres i staver av samme lengde, så grønnsakene blir ferdige samtidig og lar seg plukke opp.'},
  goesWith:[{en:'Plain rice, often as an early course', no:'Vanlig ris, ofte tidlig i måltidet'},
            {en:'A dal to follow it', no:'En dal som følger etter'}],
  headnote:{
    en:`<p>Shukto is a family of mixed-vegetable dishes with a deliberate bitter element. It often appears early in a formal meal with rice, but ingredients, seasoning and serving order vary across households and communities.</p>
<p>In this version bitter gourd is balanced by sweet or starchy vegetables including sweet potato, green banana, aubergine and radish. Milk and ghee soften the result, producing a pale gravy with a restrained bitterness.</p>
<p>This recipe uses radhuni with a little fennel. Other shukto recipes use different temperings, pastes or no dairy. Celery seed is a workable substitute for radhuni here, used sparingly.</p>`,
    no:`<p>Shukto er en familie av blandede grønnsakretter med et bevisst bittert innslag. Den kommer ofte tidlig i et formelt måltid med ris, men råvarer, krydder og serveringsrekkefølge varierer mellom husholdninger og samfunn.</p>
<p>I denne utgaven balanseres bittermelon med søte eller stivelsesrike grønnsaker som søtpotet, grønn banan, aubergine og reddik. Melk og ghee mildner resultatet og gir en lys saus med behersket bitterhet.</p>
<p>Oppskriften bruker radhuni med litt fennikel. Andre shukto-oppskrifter har andre temperinger, pastaer eller ingen meieriprodukter. Sellerifrø kan erstatte radhuni her, i liten mengde.</p>`},
  ingredients:[
   {group:{en:'The vegetables', no:'Grønnsakene'}, items:[
    {q:150, u:'g', n:{en:'bitter gourd', no:'bittermelon'}, note:{en:'in thin rounds, seeds removed', no:'i tynne skiver, uten frø'}},
    {q:250, u:'g', n:{en:'waxy potatoes', no:'fastkokende poteter'}, note:{en:'in batons 5 cm long', no:'i staver på 5 cm'}},
    {q:200, u:'g', n:{en:'sweet potato', no:'søtpotet'}, note:{en:'in batons the same size', no:'i staver av samme størrelse'}},
    {q:200, u:'g', n:{en:'green banana or plantain', no:'grønn banan eller kokebanan'}, note:{en:'peeled, in batons', no:'skrelt, i staver'}},
    {q:200, u:'g', n:{en:'aubergine', no:'aubergine'}, note:{en:'in batons', no:'i staver'}},
    {q:150, u:'g', n:{en:'white radish', no:'hvit reddik'}, note:{en:'in batons', no:'i staver'}},
    {q:150, u:'g', n:{en:'green beans', no:'grønne bønner'}, note:{en:'topped and tailed', no:'renset i begge ender'}},
   ]},
   {group:{en:'The paste and the seasoning', no:'Pastaen og krydderet'}, items:[
    {q:25, u:'g', n:{en:'white poppy seed', no:'hvite valmuefrø'}, note:{en:'soaked 30 minutes', no:'bløtlagt i 30 minutter'}},
    {q:15, u:'g', n:{en:'yellow mustard seed', no:'gule sennepsfrø'}, note:{en:'soaked with the poppy seed', no:'bløtlagt sammen med valmuefrøene'}},
    {q:25, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:4, u:'g', n:{en:'radhuni', no:'radhuni'}, note:{en:'or celery seed', no:'eller sellerifrø'}},
    {q:2, u:'g', n:{en:'fennel seed', no:'fennikelfrø'}},
    {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
    {q:250, u:'ml', n:{en:'whole milk', no:'helmelk'}},
    {q:400, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:50, u:'ml', n:{en:'mustard oil', no:'sennepsolje'}},
    {q:25, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:8, u:'g', n:{en:'sugar', no:'sukker'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Cut every vegetable except the bitter gourd into batons of the same length, so they cook evenly and can be lifted with the fingers.',
     no:'Skjær alle grønnsakene unntatt bittermelonen i staver av samme lengde, så de blir ferdige samtidig og lar seg løfte med fingrene.'},
    {en:'Grind the soaked poppy and mustard seed together with a little cold water to a smooth pale paste. Push it through a sieve and set it aside.',
     no:'Kjør de bløtlagte valmuefrøene og sennepsfrøene sammen med litt kaldt vann til en glatt, lys pasta. Press den gjennom en sil og sett den til side.'},
    {en:'Heat half the mustard oil in a wide pan and fry the bitter gourd rounds until their edges brown. Lift them out and keep them.',
     no:'Varm halvparten av sennepsoljen i en vid panne og stek skivene av bittermelon til kantene bruner seg. Løft dem ut og ta vare på dem.'},
    {en:'Fry the aubergine and the green banana in the same oil until they take a little colour, then lift those out too.',
     no:'Stek auberginen og den grønne bananen i samme olje til de får litt farge, og løft dem ut de også.'},
    {en:'Add the rest of the oil, then the radhuni, the fennel and the bay. Wait a few seconds until they crackle and smell.',
     no:'Ha i resten av oljen, og så radhuni, fennikel og laurbær. Vent noen sekunder til det knitrer og dufter.'},
    {en:'Stir in the ginger paste, cook it for a minute, then add the potato, sweet potato, radish and beans with the water and a little salt.',
     no:'Rør inn ingefærpastaen, la den surre et minutt, og ha så i potet, søtpotet, reddik og bønner sammen med vannet og litt salt.'},
    {en:'Cover and simmer for twelve minutes, until the harder vegetables are nearly tender.',
     no:'Legg på lokk og la det småkoke i tolv minutter, til de faste grønnsakene nesten er møre.'},
    {en:'Return the aubergine and green banana, and stir in the poppy and mustard paste. Simmer uncovered for five minutes, until the gravy thickens and turns opaque.',
     no:'Legg tilbake auberginen og den grønne bananen, og rør inn pastaen av valmuefrø og sennep. La det småkoke uten lokk i fem minutter, til sausen tykner og blir ugjennomsiktig.'},
    {en:'Pour in the milk, add the sugar, and warm it through without letting it boil. Scatter the fried bitter gourd over the top.',
     no:'Hell i melken, ha i sukkeret og varm det gjennom uten å la det koke. Strø den stekte bittermelonen over.'},
    {en:'Take the pan off the heat, stir in the ghee, cover it and leave it for ten minutes. Serve warm rather than hot, at the start of the meal.',
     no:'Ta pannen av platen, rør inn gheen, legg på lokk og la den stå i ti minutter. Server lunken, ikke rykende varm, i starten av måltidet.'}],
  notes:[
    {title:{en:'Why the bitter gourd is fried separately', no:'Hvorfor bittermelonen stekes for seg'},
     body:{en:'Cooking it in the gravy pushes its bitterness through the whole dish and leaves nothing to contrast with. Frying it apart and scattering it over at the end keeps the bitterness in discrete mouthfuls, which is what the dish is designed to do.',
           no:'Koker du den i sausen, presses bitterheten ut i hele retten, og da er det ingenting igjen å sette den opp mot. Stek den for seg og strø den over til slutt, så holder bitterheten seg i enkelte munnfuller, og det er nettopp det retten er laget for.'}},
    {title:{en:'Why the milk must not boil', no:'Hvorfor melken ikke må koke'},
     body:{en:'The gravy is already acidic from the mustard paste, and milk boiled in an acidic pan splits into curds and whey. Adding it late and keeping it below a simmer leaves the dish pale and smooth.',
           no:'Sausen er allerede sur av sennepspastaen, og melk som kokes i en sur gryte, skiller seg i ostemasse og myse. Ha den i sent og hold den under kokepunktet, så holder retten seg lys og glatt.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Bitter gourd is sold fresh in most Asian and Indian shops and freezes badly, so buy it the day you cook.',
           no:'Bittermelon selges ofte som karela i asiatiske og indiske matbutikker. Radhuni kan være vanskelig å finne; bruk en liten mengde sellerifrø. Be om hvite valmuefrø til denne lyse pastaen. Kokebanan kan erstattes med litt mer potet eller søtpotet.'}}],
  variations:[
    {title:{en:'With bori', no:'Med bori'},
     body:{en:'Bengali households add bori, small sun-dried lentil dumplings, fried crisp and dropped in at the end. They soften in the gravy and give the dish a third texture. Indian shops sell them dried.',
           no:'Bengalske husholdninger har i bori, små soltørkede baller av malte linser, som stekes sprø og slippes i til slutt. De mykner i sausen og gir retten en tredje konsistens. Indiske butikker selger dem tørkede.'}},
    {title:{en:'Without the bitterness', no:'Uten bitterheten'},
     body:{en:'Leave the bitter gourd out entirely and you have a dish called labra, which is a perfectly good vegetable stew and no longer shukto. Say which one you made.',
           no:'Sløyfer du bittermelonen helt, sitter du igjen med en rett som heter labra, og den er en utmerket grønnsakgryte og ikke lenger shukto. Si hvilken av dem du lagde.'}}]
},

{
  id:'mishti-doi', dish:'Mishti doi', course:'sweet', lesson:3, serves:6, veg:true,
  time:{prep:40, cook:20}, hero:'mishti-doi', tags:['sweet','yoghurt','caramel'],
  title:{en:'Mishti doi', no:'Mishti doi'},
  blurb:{en:'Sweet caramel yoghurt cultured warm, then chilled until firm.',
         no:'Søt karamellyoghurt dyrket varmt og deretter avkjølt til den er fast.'},
  heroCaption:{en:'The colour comes from sugar cooked dark before the milk goes in, not from anything added afterwards.',
               no:'Fargen kommer fra sukker som er kokt mørkt før melken går i, ikke fra noe som tilsettes etterpå.'},
  goesWith:[{en:'Served on its own as a sweet', no:'Serveres alene som noe søtt'},
            {en:'A ripe mango in season', no:'En moden mango i sesongen'}],
  headnote:{
    en:`<p>Mishti doi is a cultured milk sweet, one part of a much wider eastern repertoire that also includes chhana, reduced milk, grains and flour. Caramelised sugar or jaggery gives this course version its colour and flavour.</p>
<p>Reducing the milk concentrates its solids. The starter is added only after the mixture cools to about 43–45 °C, then the yoghurt cultures in a warm place until set and moves promptly to the refrigerator.</p>
<p>Food-safe unglazed clay can absorb some moisture and create a firmer surface, but it is optional. Clean glass or ceramic bowls work well too, especially when the milk has been reduced sufficiently.</p>`,
    no:`<p>Mishti doi er en syrnet melkesøtsak i et mye større østlig repertoar som også rommer chhana, innkokt melk, korn og mel. Karamellisert sukker eller palmesukker gir kursutgaven farge og smak.</p>
<p>Innkoking konsentrerer tørrstoffet i melken. Startkulturen går først i når blandingen er kjølt til omtrent 43–45 °C. Deretter står yoghurten lunt til den setter seg og flyttes raskt til kjøleskapet.</p>
<p>Uglasert leire som er godkjent for mat, kan trekke til seg noe fukt og gi en fastere overflate, men er valgfritt. Rene skåler av glass eller keramikk fungerer også godt, særlig når melken er kokt tilstrekkelig inn.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:1200, u:'ml', n:{en:'whole milk', no:'helmelk'}, note:{en:'the higher the fat the better', no:'jo høyere fettinnhold, jo bedre'}},
    {q:120, u:'g', n:{en:'sugar', no:'sukker'}, note:{en:'for caramelising', no:'til karamellisering'}},
    {q:60, u:'g', n:{en:'palm sugar or jaggery', no:'palmesukker eller jaggery'}, note:{en:'optional, for a darker flavour', no:'valgfritt, for en mørkere smak'}},
    {q:80, u:'g', n:{en:'natural yoghurt with live cultures', no:'naturell yoghurt med levende kultur'}, note:{en:'at room temperature', no:'i romtemperatur'}},
   ]}],
  steps:[
    {en:'Bring the milk to a simmer in a wide heavy pan and keep it there, stirring often and scraping the sides, until it has reduced by about a third. This takes twenty-five minutes and cannot be rushed.',
     no:'Kok opp melken i en vid, tung kjele og la den småkoke mens du rører ofte og skraper langs kantene, til den er kokt inn til omtrent to tredeler. Det tar tjuefem minutter og lar seg ikke forseres.'},
    {en:'While it reduces, melt the sugar in a dry pan over a medium flame without stirring it. Let it turn the colour of dark honey and then take it straight off the heat.',
     no:'Mens melken koker inn: smelt sukkeret i en tørr panne på middels varme uten å røre. La det få fargen av mørk honning, og ta det så rett av platen.'},
    {en:'Pour a ladle of the hot milk into the caramel. It will hiss and seize, which is expected. Stir it until the caramel dissolves.',
     no:'Hell en sleiv av den varme melken i karamellen. Den freser og stivner til, og det skal den. Rør til karamellen er løst opp.'},
    {en:'Tip the caramel back into the pan of milk, add the palm sugar if you are using it, and stir until everything is smooth and evenly coloured.',
     no:'Hell karamellen tilbake i kjelen med melk, ha i palmesukkeret hvis du bruker det, og rør til alt er glatt og jevnt farget.'},
    {en:'Take the pan off the heat and let the milk cool until it is just warm to a clean finger, about 45 °C. This is the step people get wrong.',
     no:'Ta kjelen av platen og la melken kjøle seg til den er så vidt lun mot en ren finger, omkring 45 °C. Det er dette steget folk gjør feil.'},
    {en:'Whisk the yoghurt smooth in a bowl, stir in a little of the warm milk to loosen it, then pour that back into the pan and stir once.',
     no:'Pisk yoghurten glatt i en bolle, rør inn litt av den lune melken for å tynne den ut, og hell så blandingen tilbake i kjelen og rør én gang.'},
    {en:'Pour into unglazed clay pots or small bowls. Do not stir them again from here on.',
     no:'Hell i uglaserte leirkrukker eller små skåler. Ikke rør i dem igjen fra nå av.'},
    {en:'Cover them, put them somewhere warm and draught-free, and leave them for six to eight hours. An oven with only the light on holds the right temperature.',
     no:'Dekk dem til, sett dem lunt og trekkfritt, og la dem stå i seks til åtte timer. En stekeovn med bare lyset på holder riktig temperatur.'},
    {en:'When the surface is set and does not move if you tilt the pot, move them to the fridge for at least four hours.',
     no:'Når overflaten har satt seg og ikke beveger seg når du vipper på krukka, setter du dem i kjøleskapet i minst fire timer.'},
    {en:'Serve cold, straight from the pot, with a small spoon.',
     no:'Server kald, rett fra krukka, med en liten skje.'}],
  notes:[
    {title:{en:'Why the milk is reduced first', no:'Hvorfor melken kokes inn først'},
     body:{en:'A firm set needs protein, and reducing the milk concentrates it. Unreduced milk gives a soft curd that weeps, and no amount of extra culture or extra time fixes that.',
           no:'En fast konsistens krever protein, og innkoking konsentrerer det. Melk som ikke er kokt inn, gir en løs masse som skiller seg, og verken mer kultur eller lengre tid retter opp i det.'}},
    {title:{en:'What an earthen pot changes', no:'Hva en leirkrukke gjør'},
     body:{en:'Food-safe porous clay can wick out some moisture as the yoghurt sets and create a firmer surface. It is optional: well-reduced milk also sets in clean glass or ceramic.',
           no:'Porøs leire som er godkjent for mat, kan trekke ut noe fukt mens yoghurten setter seg og gi en fastere overflate. Den er valgfri: godt innkokt melk setter seg også i rent glass eller keramikk.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Use the fattest plain yoghurt you can find as the starter, and check the label says live cultures.',
           no:'Bruk naturell yoghurt med levende kultur som starter, og pisk den ut med litt av den lune melken. Bruk bare leirkrukker som er laget og godkjent for mat; en ren glass- eller keramikkskål er tryggere enn en blomsterpotte. Mørkt muscovadosukker kan erstatte jaggery.'}}],
  variations:[
    {title:{en:'Nolen gur doi', no:'Nolen gur doi'},
     body:{en:'In winter Bengal makes this with nolen gur, fresh date-palm jaggery, instead of caramelised sugar. The flavour is smokier and more floral, and the season lasts only a few weeks.',
           no:'Om vinteren lager Bengal denne med nolen gur, ferskt palmesukker av saften fra daddelpalmen, i stedet for karamellisert sukker. Smaken blir mer røykpreget og mer blomsterpreget, og sesongen varer bare noen få uker.'}},
    {title:{en:'Baked, if the kitchen is cold', no:'Bakt, hvis kjøkkenet er kaldt'},
     body:{en:'A Norwegian flat in February is often too cold to set yoghurt. Put the covered pots in a roasting tin of hot water in an oven at 50 °C for four hours instead, and turn the oven off after two.',
           no:'En norsk leilighet i februar er ofte for kald til at yoghurt setter seg. Sett de tildekkede krukkene i en langpanne med varmt vann i stekeovnen på 50 °C i fire timer i stedet, og skru av ovnen etter to.'}}]
},

];
