/* Masala Dabba — recipes for The Deccan centre (IN-CEN). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-CEN'] = [

{
  id:'indori-poha', dish:'Indori poha', course:'breakfast', lesson:3, serves:4, veg:true,
  time:{prep:15, cook:15}, hero:'poha', tags:['breakfast','street food','rice'],
  title:{en:'Indori poha', no:'Indori poha'},
  blurb:{en:'Flattened rice steamed soft, finished at the plate with sev, lime and a sour spice powder.',
         no:'Flattrykt ris dampet mør, fullført på tallerkenen med sev, lime og et syrlig krydderpulver.'},
  heroCaption:{en:'The grains should be separate and moist, never sticky. The sev goes on last, or it softens.',
               no:'Kornene skal ligge løst og fuktig, aldri klissete. Seven går på til slutt, ellers blir den bløt.'},
  goesWith:[{en:'A hot jalebi, which is how Indore eats it', no:'En varm jalebi, slik Indore spiser den'},
            {en:'Strong milky tea afterwards', no:'Sterk te med melk etterpå'}],
  headnote:{
    en:`<p>Poha is parboiled rice that has been rolled flat and dried. It needs moistening rather than a full boil, and the amount of water depends on its thickness. When it is ready, the flakes are tender but still separate.</p>
<p>This recipe cooks the onion and spices first, lays the rinsed poha on top and covers the pan so trapped steam warms the flakes gently. Indori poha is also made by other methods, and neighbouring poha traditions overlap rather than dividing neatly into steamed and fried versions.</p>
<p>Sev, lime, raw onion, coriander and jiravan give this version its Indore character. Add them at the plate so the sev remains crisp and each diner can adjust the sourness and spice.</p>`,
    no:`<p>Poha er forvellet ris som er valset flat og tørket. Den trenger fukting framfor full koking, og vannmengden avhenger av tykkelsen. Når den er ferdig, er flakene møre, men fortsatt løse.</p>
<p>I denne oppskriften stekes løk og krydder først. Den skylte pohaen legges oppå, og lokket holder på dampen slik at flakene varmes skånsomt. Indori poha lages også på andre måter, og pohatradisjonene i naboregionene overlapper.</p>
<p>Sev, lime, rå løk, koriander og jiravan gir denne utgaven preg av Indore. Ha dem på ved bordet, slik at seven holder seg sprø og hver gjest kan justere syre og krydder.</p>`},
  ingredients:[
   {group:{en:'The pan', no:'I panna'}, items:[
    {q:300, u:'g', n:{en:'thick poha', no:'tykk poha'}, note:{en:'flattened rice; the thin grade will dissolve', no:'flattrykt ris; den tynne sorten går i oppløsning'}},
    {q:30, u:'ml', n:{en:'neutral oil', no:'nøytral olje'}},
    {q:5, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:3, u:'g', n:{en:'fennel seed', no:'fennikelfrø'}},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblader'}, round:'half'},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'flekket på langs'}},
    {q:150, u:'g', n:{en:'onion', no:'løk'}, note:{en:'finely chopped', no:'finhakket'}},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:6, u:'g', n:{en:'sugar', no:'sukker'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'At the plate', no:'På tallerkenen'}, items:[
    {q:60, u:'g', n:{en:'sev', no:'sev'}},
    {q:1, u:'', n:{en:'lime', no:'lime'}, round:'half'},
    {q:60, u:'g', n:{en:'raw onion', no:'rå løk'}, note:{en:'chopped small', no:'finhakket'}},
    {q:15, u:'g', n:{en:'coriander leaves', no:'koriander'}},
    {q:5, u:'g', n:{en:'jiravan', no:'jiravan'}, note:{en:'or the mix in the variations below', no:'eller blandingen i variantene under'}},
    {q:40, u:'g', n:{en:'pomegranate seeds', no:'granateplekjerner'}, note:{en:'optional, and common in Indore', no:'valgfritt, og vanlig i Indore'}},
   ]}],
  steps:[
    {en:'Put the poha in a sieve and run cold water through it, turning it with your fingers, until every grain is wet. This takes about half a minute.',
     no:'Ha pohaen i en sil og la kaldt vann renne gjennom mens du vender den med fingrene, til hvert korn er vått. Det tar omtrent et halvt minutt.'},
    {en:'Leave the sieve to drain for ten minutes. Then press a grain between two fingers: it should crush without resistance and without being wet. If it is still hard, sprinkle a little more water over and wait.',
     no:'La silen renne av i ti minutter. Klem så et korn mellom to fingre: det skal mose seg uten motstand og uten å være vått. Er det fortsatt hardt, skvett litt mer vann over og vent.'},
    {en:'Stir the turmeric, the sugar and a good pinch of salt through the drained poha with your hands, so the colour goes right through before it meets any heat.',
     no:'Vend gurkemeien, sukkeret og en god klype salt inn i den avrente pohaen med hendene, så fargen går helt gjennom før den møter varme.'},
    {en:'Heat the oil in a wide pan and add the mustard seed. When it stops popping, add the fennel seed, the curry leaves and the slit chillies, and give them ten seconds.',
     no:'Varm oljen i en vid panne og ha i sennepsfrøene. Når de slutter å sprette, ha i fennikelfrøene, karribladene og de flekkede chiliene, og gi dem ti sekunder.'},
    {en:'Add the chopped onion and cook it over a medium flame until it is soft and translucent but not browned, about five minutes.',
     no:'Ha i den hakkede løken og la den steke på middels varme til den er myk og gjennomsiktig, men ikke brunet, omtrent fem minutter.'},
    {en:'Tip the poha in on top of the onion and do not stir it. Turn the heat right down, cover the pan, and leave it for four minutes.',
     no:'Legg pohaen oppå løken uten å røre. Skru varmen helt ned, legg på lokk, og la den stå i fire minutter.'},
    {en:'Lift the lid and fold the poha through the onion with a flat spoon, from the bottom up, two or three times only. Cover it again for two minutes.',
     no:'Ta av lokket og vend pohaen inn i løken med en flat sleiv, nedenfra og opp, bare to eller tre ganger. Legg på lokket igjen i to minutter.'},
    {en:'Taste for salt. The poha should be warm through, loose and faintly sweet, and it should smell of fennel.',
     no:'Smak til med salt. Pohaen skal være gjennomvarm, løs og svakt søt, og den skal lukte av fennikel.'},
    {en:'Serve it straight onto plates. Scatter the raw onion and the coriander over, then the pomegranate, then the sev, and dust the jiravan over the top.',
     no:'Øs den rett over på tallerkener. Strø over den rå løken og korianderen, så granateplekjernene, så seven, og dryss jiravanen over til slutt.'},
    {en:'Squeeze the lime over at the table, not in the kitchen. It is the last thing that happens to the dish.',
     no:'Klem limen over ved bordet og ikke på kjøkkenet. Det er det siste som skjer med retten.'}],
  notes:[
    {title:{en:'Why it is steamed and not fried', no:'Hvorfor den dampes og ikke stekes'},
     body:{en:'Frying flattened rice drives moisture out of it and the grains go leathery at the edges. Covering the pan instead traps the water already in the poha and turns it to steam, which warms the grain through without drying it. That is why the lid matters more than the oil.',
           no:'Steker du flattrykt ris, driver du fuktigheten ut av den og kornene blir seige i kanten. Legger du på lokk i stedet, holdes vannet som alt er i pohaen inne og blir til damp, som varmer kornet gjennom uten å tørke det. Derfor betyr lokket mer enn oljen.'}},
    {title:{en:'The sev goes on last for a reason', no:'Seven går på sist av en grunn'},
     body:{en:'Sev is fried gram-flour dough and it takes up moisture within a minute or two. Scattered on at the stall it is still crisp when the plate reaches you. Stirred into the pan it becomes a soft yellow thread and the dish loses its only crunch.',
           no:'Sev er fritert deig av kikertmel, og den trekker til seg fuktighet i løpet av et par minutter. Strødd på i boden er den fortsatt sprø når tallerkenen når deg. Røres den inn i panna, blir den en myk gul tråd, og retten mister det eneste sprø den har.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Indian food shops usually sell poha in thick and thin grades; the thick grade is easiest to handle here. Look for plain sev or fine “nylon sev”. If jiravan is unavailable, use the course blend below and adjust lime or lemon to taste.',
           no:'Indiske matbutikker selger gjerne poha i tykk og tynn sort; den tykke er lettest å arbeide med her. Se etter vanlig sev eller fin «nylon sev». Finner du ikke jiravan, kan du bruke kursblandingen under og justere lime eller sitron etter smak.'}}],
  variations:[
    {title:{en:'Mix your own jiravan', no:'Bland din egen jiravan'},
     body:{en:'Toast cumin until fragrant, then grind it with dried mango powder, black salt, a little fennel, black pepper and a pinch of asafoetida. Let cumin make up roughly half of this course blend. Commercial and household jiravan formulas vary.',
           no:'Rist spisskummen til den dufter, og mal den med tørket mangopulver, svart salt, litt fennikel, svart pepper og en klype asafoetida. La spisskummen utgjøre omtrent halvparten av blandingen i kurset. Ferdige og hjemmelagde jiravanblandinger varierer.'}},
    {title:{en:'With potato', no:'Med potet'},
     body:{en:'Small cubes of potato can be cooked with the onion before the poha goes in. They make the dish more substantial and appear in both household and commercial versions.',
           no:'Små potetterninger kan stekes møre sammen med løken før pohaen går i. De gjør retten mer mettende og forekommer både hjemme og hos utsalg.'}},
    {title:{en:'Kanda poha, the Maharashtrian way', no:'Kanda poha, slik den lages i Maharashtra'},
     body:{en:'For a kanda-poha variation, add peanuts with the mustard seed and fold the softened poha directly through the onion mixture. Methods vary across Maharashtra; this version is drier and nuttier than the covered method above.',
           no:'For en variant av kanda poha kan du ha peanøtter i sammen med sennepsfrøene og vende den myke pohaen direkte inn i løkblandingen. Metodene varierer i Maharashtra; denne utgaven blir tørrere og mer nøttepreget enn metoden med lokk over.'}}]
},

{
  id:'bhutte-ka-kees', dish:'Bhutte ka kees', course:'snack', lesson:3, serves:4, veg:true,
  time:{prep:20, cook:20}, hero:'corn', tags:['corn','indore','milk'],
  title:{en:'Bhutte ka kees', no:'Bhutte ka kees'},
  blurb:{en:'Corn grated raw off the cob and cooked down in ghee and milk until it thickens.',
         no:'Mais revet rå av kolben og kokt inn i ghee og melk til den tykner.'},
  heroCaption:{en:'No free photograph of the finished dish exists, so this is what it is made of: fresh cobs, grated raw rather than cut.',
               no:'Det finnes ikke noe fritt bilde av den ferdige retten, så dette er det den lages av: ferske kolber, revet rå i stedet for skåret.'},
  goesWith:[{en:'Hot tea, late in the afternoon', no:'Varm te, sent på ettermiddagen'},
            {en:'A plain roti, if it is doing duty as a meal', no:'En enkel roti, hvis retten skal være et helt måltid'}],
  headnote:{
    en:`<p>Bhutte ka kees is associated with Indore. Raw corn is grated into a wet mash, then cooked in ghee with mustard seed and green chilli before milk is stirred in. The corn starch thickens the mixture as it cooks.</p>
<p>A box grater opens the kernels while leaving much of their skin on the cob, which gives a smoother result. A food processor can be used in short pulses if necessary, though the texture will be a little coarser.</p>
<p>Fresh corn in Norway is usually sweetcorn, so this adaptation may taste sweeter than versions made with less-sweet corn. Chilli and lime balance that sweetness; add them to taste rather than trying to enforce one fixed profile.</p>`,
    no:`<p>Bhutte ka kees forbindes med Indore. Rå mais rives til en våt masse og stekes i ghee med sennepsfrø og grønn chili før melk røres inn. Maisstivelsen tykner blandingen mens den koker.</p>
<p>Et rivjern åpner kornene og lar mye av skallet sitte igjen på kolben, noe som gir et glattere resultat. En kjøkkenmaskin kan brukes med korte pulser ved behov, men konsistensen blir litt grovere.</p>
<p>Fersk mais i Norge er som regel sukkermais, så denne tilpasningen kan bli søtere enn utgaver laget med mindre søt mais. Chili og lime balanserer sødmen; juster dem etter smak.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:600, u:'g', n:{en:'fresh corn kernels', no:'ferske maiskorn'}, note:{en:'grated raw off the cob, not cut off; about four cobs', no:'revet rå av kolben, ikke skåret av; omtrent fire kolber'}},
    {q:35, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:4, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'finely chopped', no:'finhakket'}},
    {q:15, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'grated', no:'revet'}},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:10, u:'', n:{en:'curry leaves', no:'karriblader'}, round:'half'},
    {q:350, u:'ml', n:{en:'whole milk', no:'helmelk'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {q:30, u:'g', n:{en:'grated coconut', no:'revet kokos'}, note:{en:'fresh or frozen, not desiccated', no:'fersk eller frossen, ikke tørket'}},
    {q:1, u:'', n:{en:'lime', no:'lime'}, round:'half'},
    {q:15, u:'g', n:{en:'coriander leaves', no:'koriander'}},
   ]}],
  steps:[
    {en:'Stand each cob on end in a bowl and run it down a coarse box grater. Work all the way round. What collects is a wet mash; the empty hulls stay on the cob and are thrown away.',
     no:'Sett hver kolbe på enden i en bolle og dra den nedover et grovt rivjern. Gå hele veien rundt. Det som samler seg, er en våt masse; de tomme skallene blir sittende på kolben og kastes.'},
    {en:'Heat the ghee in a heavy pan and add the mustard seed. When it stops popping, add the curry leaves, the chillies and the ginger and fry for half a minute.',
     no:'Varm gheen i en tykkbunnet panne og ha i sennepsfrøene. Når de slutter å sprette, ha i karribladene, chiliene og ingefæren, og stek et halvt minutt.'},
    {en:'Stir in the turmeric, then tip in the grated corn and a good pinch of salt.',
     no:'Rør inn gurkemeien, og ha så i den revne maisen og en god klype salt.'},
    {en:'Cook over a medium flame for six or seven minutes, stirring often, until the mash stops smelling raw and starts to smell like cooked corn. It will stiffen as you go.',
     no:'La det steke på middels varme i seks eller sju minutter, rør ofte, til massen slutter å lukte rått og begynner å lukte kokt mais. Den strammer seg mens du holder på.'},
    {en:'Pour in the milk in three lots, stirring well between them so no lumps form.',
     no:'Hell i melka i tre omganger, og rør godt mellom hver, så det ikke blir klumper.'},
    {en:'Turn the heat low and stir more or less continuously for ten to twelve minutes. The mixture thickens as the corn starch swells, and it will catch on the base if you leave it.',
     no:'Skru ned varmen og rør mer eller mindre uavbrutt i ti til tolv minutter. Blandingen tykner mens maisstivelsen sveller, og den svir seg i bunnen om du lar den stå.'},
    {en:'It is ready when a spoon dragged across the pan leaves a track that closes slowly. Check the salt now, because milk flattens it.',
     no:'Den er ferdig når en sleiv du drar over panna, legger igjen et spor som lukker seg langsomt. Smak på saltet nå, for melk demper det.'},
    {en:'Take the pan off the heat and stir in the coconut and most of the coriander.',
     no:'Ta panna av platen og rør inn kokosen og mesteparten av korianderen.'},
    {en:'Squeeze the lime over, scatter the rest of the coriander, and serve it hot with a spoon.',
     no:'Klem limen over, strø resten av korianderen på, og server retten varm med skje.'}],
  notes:[
    {title:{en:'Why grated and not blended', no:'Hvorfor den rives og ikke kjøres i maskin'},
     body:{en:'A blender chops the tough outer skin of each kernel into the mash, and you taste it as a faint bran-like grit that never cooks out. A grater tears the kernel open and leaves the skin attached to the cob. The difference is the whole texture of the dish.',
           no:'En blender hakker det seige ytterskallet på hvert korn ned i massen, og det merkes som en svak, kliaktig grynethet som aldri koker bort. Et rivjern river kornet opp og lar skallet bli sittende på kolben. Forskjellen er hele konsistensen i retten.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Fresh cobs are easiest to find in Norwegian shops in late summer. At other times, thawed frozen kernels can be pulsed briefly in a processor, though the texture will be coarser. Sweetcorn gives a sweeter result, so adjust chilli and lime to taste.',
           no:'Ferske maiskolber er lettest å finne i norske butikker sent på sommeren. Ellers kan tinte, frosne maiskorn kjøres kort i en kjøkkenmaskin, men konsistensen blir grovere. Sukkermais gir et søtere resultat, så juster chili og lime etter smak.'}},
    {title:{en:'Why it must be stirred', no:'Hvorfor den må røres'},
     body:{en:'Corn starch swells and sets at around seventy degrees, and it does so first where the pan is hottest. Left alone, that layer sticks and scorches while the rest is still thin. Constant stirring keeps the temperature even and is the difference between a smooth pan and a ruined one.',
           no:'Maisstivelse sveller og stivner rundt sytti grader, og den gjør det først der panna er varmest. Blir den stående, fester det laget seg og svir seg mens resten fortsatt er tynn. Jevn røring holder temperaturen lik overalt og avgjør om retten blir glatt eller svidd.'}}],
  variations:[
    {title:{en:'Without milk', no:'Uten melk'},
     body:{en:'Some Indore cooks use only a splash of water and finish with a spoon of cream. The dish comes out drier and more like a vegetable side, and it holds better if it has to wait.',
           no:'Noen kokker i Indore bruker bare en skvett vann og avslutter med en skje fløte. Retten blir tørrere og ligner mer på en grønnsakrett, og den tåler bedre å stå og vente.'}},
    {title:{en:'With sev on top', no:'Med sev over'},
     body:{en:'Scatter sev over each plate at the table, exactly as on poha. It is common at stalls and it gives the soft mash something to break against.',
           no:'Strø sev over hver tallerken ved bordet, akkurat som på poha. Det er vanlig i bodene, og det gir den myke massen noe å bryte mot.'}}]
},

{
  id:'dal-bafla', dish:'Dal bafla', course:'main', lesson:3, serves:4, veg:true,
  time:{prep:30, cook:70}, hero:'dal-bafla', tags:['wheat','ghee','feast'],
  title:{en:'Dal bafla', no:'Dal bafla'},
  blurb:{en:'Wheat balls boiled and then baked hard, broken open, soaked in ghee and pushed into a sour dal.',
         no:'Hveteboller som kokes og deretter bakes harde, brytes opp, trekkes fulle av ghee og dyppes i en syrlig dal.'},
  heroCaption:{en:'A bafla is cracked open at the table and the ghee is poured into it, not over it.',
               no:'En bafla brytes opp ved bordet, og gheen helles inn i den og ikke over den.'},
  goesWith:[{en:'A raw onion and a green chilli on the side', no:'En rå løk og en grønn chili ved siden av'},
            {en:'Plain yoghurt, cold', no:'Naturell yoghurt, kald'}],
  headnote:{
    en:`<p>Dal bafla belongs to Malwa and is closely related to Rajasthan's dal bati. In this recipe the wheat balls are simmered until they float and then baked, while bati is generally baked without that preliminary boil.</p>
<p>Boiling sets some of the starch before the dry heat reaches it, giving this bafla a tender centre and a firm, cracked crust. Both dishes have many regional and household versions, and the amount of ghee served with them varies.</p>
<p>The accompanying dal combines toor dal, turmeric, tamarind and a final tempering of cumin and mustard seed. Dal bafla also appears at feasts and weddings, where the recipe can be scaled and the baked balls finished with ghee at serving.</p>`,
    no:`<p>Dal bafla hører til i Malwa og er nært beslektet med dal bati fra Rajasthan. I denne oppskriften småkokes hvetebollene til de flyter og bakes deretter, mens bati vanligvis bakes uten denne forkokingen.</p>
<p>Kokingen får noe av stivelsen til å stivne før tørrvarmen når deigen, slik at denne baflaen får mør kjerne og fast, sprukken skorpe. Begge rettene finnes i mange regionale og hjemlige utgaver, og mengden ghee varierer.</p>
<p>Dalen her kombinerer toor dal, gurkemeie, tamarind og en avsluttende tempering med spisskummen og sennepsfrø. Dal bafla serveres også ved fester og bryllup, der oppskriften kan skaleres og bollene får ghee ved servering.</p>`},
  ingredients:[
   {group:{en:'The bafla', no:'Baflaen'}, items:[
    {q:400, u:'g', n:{en:'coarse wholemeal wheat flour', no:'grovt sammalt hvetemel'}, note:{en:'Indian atta if you have it', no:'indisk atta om du har det'}},
    {q:80, u:'g', n:{en:'coarse semolina', no:'grov semule'}},
    {q:70, u:'g', n:{en:'ghee', no:'ghee'}, note:{en:'for the dough', no:'til deigen'}},
    {q:200, u:'ml', n:{en:'water', no:'vann'}, note:{en:'roughly; add it slowly', no:'omtrent; ha det i litt om gangen'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {q:150, u:'g', n:{en:'ghee, to serve', no:'ghee, til servering'}, note:{en:'melted, in a bowl', no:'smeltet, i en skål'}},
   ]},
   {group:{en:'The dal', no:'Dalen'}, items:[
    {q:250, u:'g', n:{en:'toor dal', no:'toor dal'}, note:{en:'split pigeon pea; rinsed', no:'splittede dueerter; skylt'}},
    {q:1200, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:5, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:20, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'grated', no:'revet'}},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:20, u:'g', n:{en:'tamarind block', no:'tamarindblokk'}, note:{en:'soaked in hot water and strained', no:'bløtlagt i varmt vann og silt'}},
    {q:10, u:'g', n:{en:'gur', no:'gur'}, note:{en:'palm or cane sugar', no:'palme- eller rørsukker'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The tempering', no:'Temperingen'}, items:[
    {q:35, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:5, u:'g', n:{en:'cumin seed', no:'spisskummenfrø'}},
    {q:4, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:2, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
    {q:1, u:'g', n:{en:'asafoetida', no:'asafoetida'}},
    {q:4, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri chilipulver'}, note:{en:'for colour', no:'for fargen'}},
    {q:15, u:'g', n:{en:'coriander leaves', no:'koriander'}},
   ]}],
  steps:[
    {en:'Rub the ghee into the flour and the semolina with your fingers until the mixture holds together when squeezed. Add salt, then the water a little at a time, and work it into a stiff dough. It should be much firmer than a bread dough.',
     no:'Gni gheen inn i melet og semulen med fingrene til blandingen holder sammen når du klemmer den. Ha i salt, så vannet litt om gangen, og arbeid det til en stiv deig. Den skal være langt fastere enn en brøddeig.'},
    {en:'Rest the dough under a cloth for twenty minutes, then divide it into balls about the size of a small egg and roll each one smooth. Press a shallow cross into the top of each.',
     no:'La deigen hvile under et klede i tjue minutter, del den så i boller på størrelse med et lite egg, og rull hver av dem glatt. Trykk et grunt kors i toppen på hver.'},
    {en:'Heat the oven to 200 °C. Bring a wide pan of salted water to a rolling boil.',
     no:'Varm ovnen til 200 °C. Kok opp en vid kjele med saltet vann.'},
    {en:'Drop the balls into the boiling water in batches. They will sink, then rise. Give them four minutes from the moment they float, then lift them out with a slotted spoon and leave them to drain.',
     no:'Slipp bollene i det kokende vannet i omganger. De synker først og stiger så opp. Gi dem fire minutter fra de flyter, løft dem så ut med hullsleiv og la dem renne av.'},
    {en:'Put the drained balls on a rack over a tray and bake them for thirty to thirty-five minutes, turning once, until the outside is golden and cracked and they sound hollow.',
     no:'Legg de avrente bollene på rist over en langpanne og bak dem i tretti til trettifem minutter, snu dem en gang, til utsiden er gyllen og sprukken og de høres hule ut.'},
    {en:'Meanwhile cook the dal. Put it in a pot with the water, the turmeric and the ginger and simmer it, skimming the froth, until the pulses collapse. In a pressure cooker this takes about fifteen minutes.',
     no:'Kok dalen imens. Ha den i en gryte med vannet, gurkemeien og ingefæren og la det småkoke mens du skummer av, til dalen går i oppløsning. I trykkoker tar det omtrent femten minutter.'},
    {en:'Whisk the dal smooth, add the green chillies, the strained tamarind, the gur and salt, and simmer it for ten minutes more. It should pour off a spoon, not sit on it.',
     no:'Visp dalen glatt, ha i de grønne chiliene, den silte tamarinden, guren og salt, og la det småkoke ti minutter til. Den skal renne av en skje, ikke bli liggende på den.'},
    {en:'Make the tempering last. Heat the ghee, add the cumin and mustard seed, and when they crackle add the dried chillies and the asafoetida. Take the pan off the heat, stir in the chilli powder, and pour the lot over the dal.',
     no:'Lag temperingen til slutt. Varm gheen, ha i spisskummen- og sennepsfrøene, og når de spraker, ha i de tørkede chiliene og asafoetidaen. Ta panna av platen, rør inn chilipulveret, og hell alt over dalen.'},
    {en:'Crack each hot bafla open with your thumbs and dip it in the melted ghee, or spoon the ghee into the split. Do this at the table.',
     no:'Brekk opp hver varme bafla med tomlene og dypp den i den smeltede gheen, eller øs ghee ned i sprekken. Gjør det ved bordet.'},
    {en:'Serve the baflas in a bowl with the dal poured over them and the coriander scattered on top.',
     no:'Server baflaene i en skål med dalen helt over og korianderen strødd på toppen.'}],
  notes:[
    {title:{en:'What the boiling does', no:'Hva kokingen gjør'},
     body:{en:'Wheat starch needs water and heat together to swell and set. In a bati the dough goes straight into dry heat, so only the moisture already in it is available and the crumb stays tight. Boiling first floods the starch with water, and the bafla bakes around an inside that has already softened.',
           no:'Hvetestivelse trenger vann og varme samtidig for å svelle og stivne. I en bati går deigen rett inn i tørrvarme, så bare den fuktigheten som alt er i den, er tilgjengelig, og krummen blir tett. Koker du deigen først, får stivelsen rikelig med vann, og baflaen bakes rundt en innside som allerede har myknet.'}},
    {title:{en:'Why the dal is deliberately plain', no:'Hvorfor dalen er enkel med vilje'},
     body:{en:'The bafla is rich with ghee and heavy with wheat, so a thick, spiced, creamy dal would make the plate impossible. A thin dal soured with tamarind cuts the fat and carries it, which is the same reasoning behind sour pickle beside fried food anywhere.',
           no:'Baflaen er fet av ghee og tung av hvete, så en tykk, sterkt krydret og kremet dal ville gjort tallerkenen umulig. En tynn dal syrnet med tamarind skjærer gjennom fettet og bærer det, og det er den samme tanken som ligger bak sur pickle ved siden av fritert mat overalt.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Indian shops sell chakki atta, which is the right flour, and toor dal by the kilo.',
           no:'Indiske butikker selger chakki atta, som er riktig mel, og toor dal i kilos. Norsk sammalt hvetemel er malt annerledes og gir en tyngre bafla, så bland det med semule slik oppskriften sier. Toor dal heter også arhar eller tuvar; gule erter er ikke det samme og koker ut til grøt. Ghee står på glass i de samme butikkene; følg lagringsrådet på etiketten. Hjemmeklaret smør fungerer også og bør stå kaldt hvis holdbarheten er usikker. Tamarind kjøpes i blokk med kjerner, ikke som ferdig konsentrat.'}}],
  variations:[
    {title:{en:'Bati instead', no:'Bati i stedet'},
     body:{en:'For a bati-style variation, skip the boiling and bake the balls for about fifty minutes at 180 °C, checking that the centres are cooked. Serve with the dal and as much ghee as you prefer; cool and refrigerate leftovers promptly.',
           no:'For en variant i bati-stil kan du sløyfe kokingen og bake bollene i omtrent femti minutter på 180 °C. Kontroller at de er gjennomstekte. Server med dal og ønsket mengde ghee, og kjøl ned og sett rester raskt i kjøleskapet.'}},
    {title:{en:'Stuffed baflas', no:'Fylte baflaer'},
     body:{en:'Flatten each ball, put a spoonful of mashed spiced peas or crumbled paneer in the middle, and close it before boiling. The filling steams inside and the ball takes a few minutes longer in the oven.',
           no:'Trykk hver bolle flat, legg en skje moste, krydrede erter eller smuldret paneer i midten, og lukk den før kokingen. Fyllet dampes inni, og bollen trenger noen minutter mer i ovnen.'},},
    {title:{en:'Churma with what is left', no:'Churma av det som blir igjen'},
     body:{en:'Crush a cold bafla coarsely, work ghee and gur through it with your hands, and eat it from the same plate as the savoury food. Rajasthan does this as a matter of course and Malwa borrows it.',
           no:'Knus en kald bafla grovt, arbeid ghee og gur inn i den med hendene, og spis den fra samme tallerken som resten av maten. Rajasthan gjør det som en selvfølge, og Malwa låner vanen.'}}]
},

{
  id:'besan-chila', dish:'Chila', course:'breakfast', lesson:2, serves:4, veg:true,
  time:{prep:15, cook:20}, hero:'chila', tags:['gram flour','breakfast','quick'],
  title:{en:'Chila', no:'Chila'},
  blurb:{en:'A thin gram-flour pancake cooked on a griddle, savoury, quick and eaten at any hour.',
         no:'En tynn og rask pannekake av kikertmel, stekt på plate og spist når som helst på døgnet.'},
  heroCaption:{en:'The batter is thin enough to spread by tilting the pan. Curd and a tomato beside it make it a meal.',
               no:'Røren er så tynn at den brer seg når du vipper på panna. Yoghurt og en tomat ved siden av gjør den til et måltid.'},
  goesWith:[{en:'Green coriander chutney', no:'Grønn korianderchutney'},
            {en:'Cold plain yoghurt', no:'Kald naturell yoghurt'}],
  headnote:{
    en:`<p>Chila names a broad family of savoury pancakes. This course version uses gram flour, while rice and ground-pulse batters appear in Chhattisgarh and elsewhere. Gram flour contains no gluten, sets as its starch and protein cook, and browns readily.</p>
<p>The batter rests for twenty minutes, and each pancake then cooks in a few minutes on a hot pan. Chila can be breakfast, a snack or a light meal, with fillings and accompaniments adjusted to the occasion.</p>
<p>Gram flour absorbs water while it rests, so check the batter before cooking. If it no longer pours easily, whisk in a little water; if it tears, let the first side set longer before turning.</p>`,
    no:`<p>Chila er navnet på en bred familie av salte pannekaker. Utgaven i kurset bruker kikertmel, mens rismel og malte belgvekster brukes i Chhattisgarh og andre steder. Kikertmel inneholder ikke gluten, stivner når stivelse og protein varmes opp og brunes lett.</p>
<p>Røren hviler i tjue minutter, og hver pannekake stekes deretter på få minutter i en varm panne. Chila kan være frokost, mellommåltid eller et lett måltid, med fyll og tilbehør etter anledning.</p>
<p>Kikertmel trekker til seg vann mens røren hviler, så kontroller konsistensen før steking. Visp inn litt vann hvis den ikke lenger renner lett. Hvis pannekaka revner, lar du den første siden stivne lenger før du snur.</p>`},
  ingredients:[
   {group:{en:'The batter', no:'Røren'}, items:[
    {q:250, u:'g', n:{en:'gram flour', no:'kikertmel'}, note:{en:'besan, from split chickpeas', no:'besan, av splittede kikerter'}},
    {q:450, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:3, u:'g', n:{en:'ajwain', no:'ajwain'}, note:{en:'carom seed, crushed between the palms', no:'ajwainfrø, knust mellom håndflatene'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'Stirred through', no:'Rørt inn'}, items:[
    {q:120, u:'g', n:{en:'onion', no:'løk'}, note:{en:'chopped very small', no:'hakket svært fint'}},
    {q:120, u:'g', n:{en:'tomato', no:'tomat'}, note:{en:'seeded and chopped small', no:'uten kjerner, finhakket'}},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'finely chopped', no:'finhakket'}},
    {q:15, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'grated', no:'revet'}},
    {q:20, u:'g', n:{en:'coriander leaves', no:'koriander'}},
   ]},
   {group:{en:'For the pan', no:'Til panna'}, items:[
    {u:'', n:{en:'neutral oil or ghee', no:'nøytral olje eller ghee'}, scale:'none'},
   ]}],
  steps:[
    {en:'Put the gram flour in a bowl with the turmeric, the ajwain and a good pinch of salt, and whisk in the water in three lots. Whisk hard after each, because gram flour lumps easily.',
     no:'Ha kikertmelet i en bolle med gurkemeien, ajwainen og en god klype salt, og visp inn vannet i tre omganger. Visp godt etter hver, for kikertmel klumper seg lett.'},
    {en:'Leave the batter to stand for twenty minutes. It will thicken noticeably.',
     no:'La røren stå i tjue minutter. Den tykner merkbart.'},
    {en:'Stir in the onion, tomato, chillies, ginger and coriander, then thin the batter with a little more water until it pours like single cream.',
     no:'Rør inn løken, tomaten, chiliene, ingefæren og korianderen, og spe så røren med litt mer vann til den renner som matfløte.'},
    {en:'Heat a flat pan over a medium flame until a drop of water skitters across it. Wipe it with oil.',
     no:'Varm en flat panne på middels varme til en vanndråpe danser over den. Gni den inn med litt olje.'},
    {en:'Pour a ladleful into the middle and spread it outwards in a spiral with the back of the ladle, working quickly while it is still wet.',
     no:'Hell en øse i midten og bre den utover i en spiral med baksiden av øsa, og jobb raskt mens røren fortsatt er våt.'},
    {en:'Trickle a little oil round the edge. Cook for two or three minutes, until the top has set and the underside is brown in patches.',
     no:'La litt olje renne rundt kanten. Stek i to eller tre minutter, til oversiden har stivnet og undersiden er brunet i flekker.'},
    {en:'Slide a spatula under it, turn it, and give it a minute on the second side. It should be flexible, not crisp.',
     no:'Skyv en stekespade under, snu den, og gi den et minutt på den andre siden. Den skal være myk, ikke sprø.'},
    {en:'Fold it in half and eat it straight away, or keep the stack under a cloth while you cook the rest.',
     no:'Brett den i to og spis den med det samme, eller hold stabelen under et klede mens du steker resten.'}],
  notes:[
    {title:{en:'Why gram flour behaves differently', no:'Hvorfor kikertmel oppfører seg annerledes'},
     body:{en:'It has no gluten, so nothing holds the pancake together but set starch and protein. That means it cannot be stretched or flipped early, and it must be left alone until the top has visibly set. It also browns much faster than wheat, so a pan that is too hot gives you a dark, bitter chila with a raw middle.',
           no:'Det inneholder ikke gluten, så ingenting holder pannekaka sammen bortsett fra stivelse og protein som stivner. Derfor kan den verken strekkes eller snus for tidlig, og den må få ligge i fred til du ser at oversiden har stivnet. Det bruner seg også mye raskere enn hvete, så en for varm panne gir en mørk, bitter chila med rå midte.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy besan in an Indian shop rather than chickpea flour from a health-food shelf.',
           no:'Kjøp besan i en indisk butikk framfor kikertmel fra helsekosthylla. Besan males av skrellede, splittede kikerter (chana dal) og er finere og mildere; det grove kikertmelet i dagligvaren er malt av hele kikerter med skall og gir en tyngre og litt beskere pannekake. Ajwain står i de samme butikkene og heter ofte carom seeds; det finnes ingen god erstatning, og timian gjør ikke samme nytten. Melet harskner, så kjøp en liten pose og oppbevar den mørkt.'}}],
  variations:[
    {title:{en:'The Chhattisgarh version', no:'Utgaven fra Chhattisgarh'},
     body:{en:'Use rice flour instead of gram flour and let the batter stand for an hour. It cooks paler, tastes cleaner and crisps at the edge, and it is eaten with a chutney rather than with curd.',
           no:'Bruk rismel i stedet for kikertmel og la røren stå i en time. Den blir lysere, smaker renere og blir sprø i kanten, og den spises med en chutney i stedet for med yoghurt.'}},
    {title:{en:'With paneer', no:'Med paneer'},
     body:{en:'Crumble paneer over the wet surface before you turn it, then fold the chila around it. This is how it is sold as a street breakfast and it turns a snack into a meal.',
           no:'Smuldre paneer over den våte overflaten før du snur, og brett så chilaen rundt den. Slik selges den som frokost i gata, og da blir et mellommåltid til et helt måltid.'}},
    {title:{en:'Moong dal chila', no:'Chila av moong dal'},
     body:{en:'Soak split yellow moong dal for four hours and grind it to a batter instead of using flour. It is softer, sweeter and slightly grainy, and it is the version made in Punjab and Delhi.',
           no:'Bløtlegg splittet gul moong dal i fire timer og mal den til en røre i stedet for å bruke mel. Den blir mykere, søtere og litt grynete, og det er utgaven som lages i Punjab og Delhi.'}}]
},

{
  id:'bhopali-korma', dish:'Bhopali korma', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:30, cook:105}, hero:'korma', tags:['goat','yoghurt','slow'],
  title:{en:'Bhopali korma', no:'Bhopali korma'},
  blurb:{en:'Goat cooked slowly in yoghurt and browned onion, thickened with poppy seed, aromatic rather than hot.',
         no:'Geitekjøtt kokt langsomt i yoghurt og brunet løk, tyknet med valmuefrø, aromatisk heller enn sterk.'},
  heroCaption:{en:'The reference photograph shows a North Indian mutton korma. The course recipe uses yoghurt, browned onion and poppy seed, without tomato.',
               no:'Referansebildet viser en nordindisk korma av geitekjøtt. Oppskriften i kurset bruker yoghurt, brunet løk og valmuefrø, uten tomat.'},
  goesWith:[{en:'Sheermal or a plain roti', no:'Sheermal eller en enkel roti'},
            {en:'Raw onion rings with lime squeezed over', no:'Rå løkringer med lime klemt over'}],
  headnote:{
    en:`<p>Bhopal's food history includes courtly cooking as well as everyday urban and rural traditions. This course recipe presents one korma style: meat cooked slowly with yoghurt, browned onion, whole spices and a paste of poppy seed and chironji, without tomato or cream.</p>
<p>The order helps control the sauce. Brown the onion first, lower the heat before adding yoghurt, and cook the seed paste gently so it does not catch. Slow covered cooking then tenderises the meat and brings the gravy together.</p>
<p>The recipe is written for goat on the bone. Lamb shoulder is easier to find in Norway and works well, though its flavour and fat differ. Boneless shoulder can also be used; check it earlier and reduce the added water if the sauce is loose.</p>`,
    no:`<p>Mathistorien i Bhopal rommer hoffkjøkken så vel som hverdagsmat fra by og land. Oppskriften i kurset viser én kormastil: kjøtt kokt langsomt med yoghurt, brunet løk, hele krydder og en masse av valmuefrø og chironji, uten tomat eller fløte.</p>
<p>Rekkefølgen gjør sausen lettere å styre. Brun løken først, senk varmen før yoghurten tilsettes, og stek frømassen forsiktig så den ikke svir seg. Langsom koking under lokk mørner så kjøttet og samler sausen.</p>
<p>Oppskriften er skrevet for geitekjøtt med bein. Lammebog er enklere å finne i Norge og fungerer godt, selv om smak og fettmengde er annerledes. Bog uten bein kan også brukes; kontroller den tidligere og reduser vannet hvis sausen er løs.</p>`},
  ingredients:[
   {group:{en:'The paste', no:'Massen'}, items:[
    {q:40, u:'g', n:{en:'white poppy seed', no:'hvite valmuefrø'}, note:{en:'soaked in warm water for an hour', no:'bløtlagt i lunkent vann i en time'}},
    {q:20, u:'g', n:{en:'chironji', no:'chironji'}, note:{en:'or pine nuts', no:'eller pinjekjerner'}},
    {q:25, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:20, u:'g', n:{en:'garlic', no:'hvitløk'}},
   ]},
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:900, u:'g', n:{en:'goat or lamb shoulder, on the bone', no:'geite- eller lammebog, med bein'}, note:{en:'in large pieces', no:'i store stykker'}},
    {q:80, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:350, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'tynt skåret'}},
    {q:300, u:'g', n:{en:'thick yoghurt', no:'tykk yoghurt'}, note:{en:'whisked smooth, at room temperature', no:'vispet glatt, romtemperert'}},
    {q:4, u:'', n:{en:'green cardamom pods', no:'grønne kardemommekapsler'}, round:'half'},
    {q:2, u:'', n:{en:'black cardamom pods', no:'svarte kardemommekapsler'}, round:'half'},
    {q:6, u:'', n:{en:'cloves', no:'nellikspiker'}, round:'half'},
    {q:1, u:'', n:{en:'cinnamon stick', no:'kanelstang'}, round:'half'},
    {q:2, u:'', n:{en:'bay leaves', no:'laurbærblader'}, round:'half'},
    {q:5, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri chilipulver'}},
    {q:8, u:'g', n:{en:'Bhopali garam masala', no:'Bhopali garam masala'}, note:{en:'ground, for the end', no:'malt, til slutt'}},
    {q:400, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {q:10, u:'g', n:{en:'mint leaves', no:'mynteblader'}},
   ]}],
  steps:[
    {en:'Drain the soaked poppy seed and grind it with the chironji, the ginger, the garlic and just enough water to move the blades, until you have a smooth pale paste. Set it aside.',
     no:'Hell av vannet fra valmuefrøene og mal dem sammen med chironjien, ingefæren, hvitløken og akkurat nok vann til at knivene går rundt, til du har en glatt, lys masse. Sett den til side.'},
    {en:'Heat the ghee in a heavy pot and fry the sliced onion over a medium flame, stirring often, until it is deep golden brown. This takes twenty to twenty-five minutes and cannot be hurried.',
     no:'Varm gheen i en tykkbunnet gryte og stek den skårne løken på middels varme, rør ofte, til den er dypt gyllenbrun. Det tar tjue til tjuefem minutter og lar seg ikke forsere.'},
    {en:'Lift two thirds of the onion out with a slotted spoon and leave it to cool on a plate. Keep the fat in the pot.',
     no:'Løft to tredjedeler av løken ut med hullsleiv og la den kjøle seg på en tallerken. La fettet bli igjen i gryta.'},
    {en:'Drop the whole spices into the hot fat and let them swell for twenty seconds, then add the meat and a good pinch of salt. Turn it over a high flame until it is sealed on all sides but not browned.',
     no:'Slipp de hele krydderne i det varme fettet og la dem svelle i tjue sekunder, ha så i kjøttet og en god klype salt. Vend det på sterk varme til det er lukket på alle sider, men ikke brunet.'},
    {en:'Take the pot off the heat for a minute so it cools a little. Whisk the chilli powder into the yoghurt, then add the yoghurt a spoonful at a time, stirring constantly, until it is all in.',
     no:'Ta gryta av platen et minutt så den kjøler seg litt. Visp chilipulveret inn i yoghurten, og ha så yoghurten i en skje om gangen mens du rører hele tiden, til alt er i.'},
    {en:'Return it to a low flame and cook, stirring now and then, until the yoghurt has tightened round the meat and the ghee shows at the edges. Give it fifteen minutes and do not let it boil hard.',
     no:'Sett gryta tilbake på lav varme og la det koke, rør nå og da, til yoghurten har strammet seg rundt kjøttet og gheen synes i kanten. Gi det femten minutter, og la det ikke fosskoke.'},
    {en:'Crush the reserved fried onion between your fingers and stir it in, then stir in the poppy-seed paste. Fry it gently for four or five minutes so the raw taste cooks out.',
     no:'Knus den avsatte stekte løken mellom fingrene og rør den inn, og rør så inn massen av valmuefrø. Stek den forsiktig i fire eller fem minutter så den rå smaken koker bort.'},
    {en:'Pour in the water, bring it to a bare simmer, cover the pot and weight the lid. Cook on the lowest heat for an hour and a quarter, or until the meat pulls off the bone.',
     no:'Hell i vannet, la det så vidt småkoke, legg på lokk og tyng det ned. La det stå på lavest mulig varme i en og en kvart time, eller til kjøttet slipper beinet.'},
    {en:'Uncover it and check the gravy. It should coat the meat and pool slightly, never run. If it is thin, simmer it uncovered for a few minutes; if it is tight, loosen it with hot water.',
     no:'Ta av lokket og se på sausen. Den skal legge seg rundt kjøttet og samle seg litt, aldri renne. Er den tynn, la den småkoke uten lokk noen minutter; er den for stram, spe med varmt vann.'},
    {en:'Stir in the garam masala and the mint, cover the pot again and take it off the heat. Leave it to stand for ten minutes before serving.',
     no:'Rør inn garam masalaen og mynten, legg på lokket igjen og ta gryta av platen. La den stå i ti minutter før servering.'}],
  notes:[
    {title:{en:'Why the yoghurt splits, and how to stop it', no:'Hvorfor yoghurten skiller seg, og hvordan du hindrer det'},
     body:{en:'Yoghurt protein curdles when it meets high heat suddenly, and once it has separated nothing brings it back. Taking the pot off the heat, whisking the yoghurt smooth first and adding it in small amounts keeps the temperature climbing slowly enough for the protein to set as a gravy instead of as lumps.',
           no:'Proteinet i yoghurt koagulerer når det møter sterk varme brått, og har den først skilt seg, henter ingenting den tilbake. Tar du gryta av platen, visper yoghurten glatt først og har den i litt om gangen, stiger temperaturen langsomt nok til at proteinet stivner som saus i stedet for som klumper.'}},
    {title:{en:'Browned onion is the body of the dish', no:'Den brunede løken gir retten fylde'},
     body:{en:'Two thirds of the onion is fried, cooled and crushed back in, and that is deliberate. Onion fried until deep brown loses its water and gains sweetness, and crushed into the pot it dissolves into a thick base. Onion left in the fat from the start would simply melt away and thicken nothing.',
           no:'To tredjedeler av løken stekes, kjøles og knuses tilbake i gryta, og det er med vilje. Løk stekt til dypt brunt mister vannet og blir søtere, og når den knuses ned i gryta, løser den seg opp og blir en tykk bunn. Løk som blir liggende i fettet fra starten, smelter bare bort og tykner ingenting.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Goat is sold frozen in halal butchers in Oslo, and lamb shoulder is the everyday substitute.',
           no:'Geitekjøtt selges frossent hos halalslaktere i Oslo, og lammebog er det vanlige alternativet. Norsk lam er fetere og mildere enn indisk geit, så skum av mer og bruk litt mer chili. Naturell yoghurt i dagligvaren er tynn og skiller seg lett; velg tyrkisk eller gresk yoghurt, eller sil vanlig yoghurt i et klede i en time. Hvite valmuefrø heter khus khus og finnes i indiske butikker, og de blå fra bakehylla gjør sausen grå. Chironji er nesten umulig å få tak i her, så bruk pinjekjerner.'}}],
  variations:[
    {title:{en:'Chicken korma', no:'Korma av kylling'},
     body:{en:'Use chicken thighs on the bone and cut the covered cooking to thirty-five minutes. The gravy needs a little less water because the meat gives up more of its own.',
           no:'Bruk kyllinglår med bein og kort ned kokingen under lokk til trettifem minutter. Sausen trenger litt mindre vann, for kjøttet gir fra seg mer selv.'}},
    {title:{en:'Without the poppy seed', no:'Uten valmuefrø'},
     body:{en:'Cashews soaked and ground the same way give a similar body and a sweeter, rounder gravy. It is a common shortcut in restaurants and it does change the dish.',
           no:'Bløtlegger du cashewnøtter og maler dem på samme måte, får sausen liknende fylde, men blir søtere og rundere. Det er en vanlig snarvei på restaurant, og den endrer retten.'}},
    {title:{en:'Rogan josh, the Bhopal way', no:'Rogan josh slik den lages i Bhopal'},
     body:{en:'For a separate rogan-josh-inspired variation, leave out the poppy seed, add more Kashmiri chilli for colour and finish with a little extra garam masala. Treat this as an adaptation rather than a universal definition of either dish.',
           no:'For en egen variant inspirert av rogan josh kan du sløyfe valmuefrøene, bruke mer Kashmiri-chili for farge og avslutte med litt ekstra garam masala. Dette er en tilpasning, ikke en allmenn definisjon av noen av rettene.'}}]
}

];
