/* Masala Dabba — recipes for Goa & the Konkan (IN-KON). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-KON'] = [

{
  id:'pork-vindaloo', dish:'Vindaloo', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:30, cook:100}, hero:'dried-chillies', tags:['pork','vinegar','make ahead'],
  title:{en:'Pork vindaloo', no:'Vindaloo med svinekjøtt'},
  blurb:{en:'Pork in vinegar, garlic and Kashmiri chilli. Sour before it is hot, and better on the second day.',
         no:'Svinekjøtt i eddik, hvitløk og Kashmiri-chili. Sur før den er sterk, og bedre dagen etter.'},
  heroCaption:{en:'No free photograph of a Goan vindaloo exists, so here is what one starts from: whole dried red chillies, bought by the sack and ground at home.',
               no:'Det finnes ikke noe fritt bilde av en vindaloo fra Goa, så her er det retten begynner med: hele tørkede røde chilier, kjøpt i sekk og malt hjemme.'},
  goesWith:[{en:'Par-boiled rice, or a plain white loaf to mop with', no:'Forkokt ris, eller en vanlig loff til å tørke opp med'},
            {en:'Something cold and sour, such as a tomato and onion salad', no:'Noe kaldt og syrlig, for eksempel en salat av tomat og løk'}],
  headnote:{
    en:`<p>Vindaloo developed in Goa from Portuguese <em>vinha d'alhos</em>, a preparation named for wine and garlic. Goan cooks adapted the idea with local vinegar, chillies and spices. The resemblance between <em>alhos</em> and <em>aloo</em> is accidental; potatoes nevertheless appear in some household and later versions.</p>
<p>This recipe puts acidity and garlic before chilli heat. It produces a dark, close gravy rather than the very hot, loose sauce associated with some British restaurant versions.</p>
<p>Time does much of the work. Marinate the pork in the refrigerator, cook it slowly with little added water, then cool and refrigerate it promptly if resting it overnight. Reheat it thoroughly before serving.</p>`,
    no:`<p>Vindaloo utviklet seg i Goa fra portugisisk <em>vinha d'alhos</em>, en tilberedning oppkalt etter vin og hvitløk. Goanske kokker tilpasset ideen med lokal eddik, chili og krydder. Likheten mellom <em>alhos</em> og <em>aloo</em> er tilfeldig, men potet finnes likevel i noen husholdningsvarianter og nyere utgaver.</p>
<p>Denne oppskriften setter syre og hvitløk foran chilistyrke. Resultatet er en mørk og tett saus, ikke den svært sterke og tynne sausen som forbindes med enkelte britiske restaurantutgaver.</p>
<p>Tid gjør mye av arbeidet. Mariner svinekjøttet i kjøleskapet, la det koke langsomt med lite tilsatt vann, og kjøl det raskt ned før det settes kaldt hvis retten skal hvile over natten. Varm den grundig før servering.</p>`},
  ingredients:[
   {group:{en:'The paste', no:'Pastaen'}, items:[
    {q:12, u:'', n:{en:'dried Kashmiri chillies', no:'tørkede Kashmiri-chilier'}, round:'half', note:{en:'stalks and most seeds removed', no:'uten stilk og med det meste av frøene fjernet'}},
    {q:3, u:'', n:{en:'hot dried chillies', no:'sterke tørkede chilier'}, round:'half', note:{en:'more or fewer, to taste', no:'flere eller færre, etter smak'}},
    {q:150, u:'ml', n:{en:'palm or cider vinegar', no:'palmeeddik eller eplesidereddik'}},
    {q:40, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'peeled', no:'skrelt'}},
    {q:25, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:6, u:'g', n:{en:'cumin seed', no:'hele spisskummenfrø'}},
    {q:8, u:'', n:{en:'cloves', no:'hele nellik'}, round:'half'},
    {q:1, u:'', n:{en:'piece of cinnamon bark', no:'bit kanelbark'}, round:'half'},
    {q:4, u:'g', n:{en:'black peppercorns', no:'hele sorte pepperkorn'}},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:10, u:'g', n:{en:'jaggery or dark brown sugar', no:'jaggery eller mørk farin'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:900, u:'g', n:{en:'pork shoulder', no:'svinebog'}, note:{en:'in 4 cm cubes, fat left on', no:'i terninger på 4 cm, med fettet på'}},
    {q:200, u:'g', n:{en:'onions', no:'løk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:45, u:'ml', n:{en:'neutral oil or lard', no:'nøytral olje eller svinefett'}},
    {q:200, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15, u:'ml', n:{en:'vinegar, to finish', no:'eddik, til slutt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Break the dried chillies open, shake out most of the seeds and soak them in the vinegar for twenty minutes. They will soften and the vinegar will turn red.',
     no:'Brekk opp de tørkede chiliene, rist ut mesteparten av frøene og legg dem i eddiken i tjue minutter. De mykner, og eddiken blir rød.'},
    {en:'Grind the soaked chillies with their vinegar, the garlic, ginger, cumin, cloves, cinnamon, peppercorns, turmeric, jaggery and a good pinch of salt. Add no water at any point.',
     no:'Mal de bløtlagte chiliene sammen med eddiken, hvitløken, ingefæren, spisskummen, nelliken, kanelen, pepperkornene, gurkemeien, jaggeryen og en god klype salt. Ikke ha i vann på noe tidspunkt.'},
    {en:'Turn the pork in the paste until every cube is coated, cover it, and leave it in the fridge overnight. Six hours will do; twelve is better.',
     no:'Vend svinekjøttet i pastaen til alle terningene er dekket, dekk til og sett det i kjøleskapet over natten. Seks timer holder, tolv er bedre.'},
    {en:'Take the meat out an hour before you cook, so it is not going into the pan cold.',
     no:'Ta kjøttet ut en time før du skal lage retten, så det ikke går kaldt i gryta.'},
    {en:'Heat the oil in a heavy pot and fry the onion slowly until it is soft and properly brown, about fifteen minutes. Brown onion is the only browning in this dish.',
     no:'Varm oljen i en tung gryte og stek løken langsomt til den er myk og skikkelig brun, omtrent femten minutter. Løken er det eneste som brunes i denne retten.'},
    {en:'Tip in the pork with all its marinade and turn the heat up. Stir until the liquid boils and the sharp smell of raw vinegar has gone, three or four minutes.',
     no:'Ha i svinekjøttet med hele marinaden og skru opp varmen. Rør til væsken koker og den skarpe lukten av rå eddik er borte, tre–fire minutter.'},
    {en:'Add the water, bring it back to a simmer, cover, and cook on the lowest heat for an hour. Do not stir often; the meat should sit still and let the fat come out.',
     no:'Ha i vannet, la det så vidt koke opp igjen, legg på lokk og la det stå på lavest mulig varme i en time. Ikke rør for ofte; kjøttet skal ligge i ro og slippe fettet ut.'},
    {en:'Take the lid off and cook uncovered for fifteen to twenty minutes more, until the gravy is dark, thick and glossy and a slick of red fat sits on the surface.',
     no:'Ta av lokket og la det koke uten lokk i femten–tjue minutter til, til sausen er mørk, tykk og blank og et rødt fettlag legger seg på overflaten.'},
    {en:'Taste it. It should be sour first. Correct the salt, and add the last of the vinegar if the edge has gone soft during the cooking.',
     no:'Smak på den. Den skal være sur først. Juster saltet, og ha i den siste eddiken hvis syren har blitt for rund under kokingen.'},
    {en:'Cool it, cover it and refrigerate it for a day. Reheat gently before serving, and expect it to taste better than it did last night.',
     no:'Kjøl den ned, dekk den til og sett den i kjøleskapet et døgn. Varm den forsiktig opp før servering, og regn med at den smaker bedre enn den gjorde i går kveld.'}],
  notes:[
    {title:{en:'Why the paste is ground in vinegar', no:'Hvorfor pastaen males i eddik'},
     body:{en:'Vinegar supplies the defining acidity and enough liquid to grind the spices. It does not make raw marinade or cooked meat safe at room temperature: keep both refrigerated, use homemade paste within a few days or freeze it, and cool leftovers promptly.',
           no:'Eddik gir den tydelige syren og nok væske til å male krydderet. Den gjør ikke rå marinade eller kokt kjøtt trygt i romtemperatur: oppbevar begge kaldt, bruk hjemmelaget pasta i løpet av få dager eller frys den, og kjøl rester raskt ned.'}},
    {title:{en:'Why the meat is not browned', no:'Hvorfor kjøttet ikke brunes'},
     body:{en:'The pork goes into the pot straight from the marinade, wet, and that is deliberate. Searing acidic meat scorches the chilli and the sugar in the paste and turns the whole dish bitter. The colour and the depth come from the browned onion and from an hour of slow cooking, not from a hot pan.',
           no:'Svinekjøttet går rett fra marinaden og ned i gryta, vått, og det er med vilje. Bruner du surt kjøtt, svir du chilien og sukkeret i pastaen, og hele retten blir bitter. Fargen og dybden kommer fra den brunede løken og fra en time på lav varme, ikke fra en glovarm panne.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy shoulder rather than loin and ask the counter to leave the fat on, because the fat is what carries the chilli.',
           no:'Kjøp svinebog og ikke indrefilet, og be kjøttdisken la fettet sitte på, for det er fettet som bærer chilien. Nakkekoteletter uten bein fungerer også godt. Hele tørkede Kashmiri-chilier får du i indiske butikker på Grønland i Oslo; norsk chilipulver er sterkere og gir feil farge, så ikke bytt det ene mot det andre uten videre. Palmeeddik ses sjelden her, men kokoseddik fra en asiatisk butikk er den samme typen syre, og eplesidereddik er et brukbart siste valg. Malteddik er det ikke. Jaggery finner du i indisk butikk, og mørk farin gjør omtrent samme nytte.'}}],
  variations:[
    {title:{en:'Lamb or beef instead', no:'Med lam eller oksekjøtt i stedet'},
     body:{en:'Both work in the same paste. Lamb shoulder needs about the same time as pork; beef shin needs half an hour more and gives a stickier gravy. Goa itself makes the beef version, and it is one of the few Indian states where that is unremarkable.',
           no:'Begge fungerer i den samme pastaen. Lammebog trenger omtrent like lang tid som svinekjøtt, mens okseskank trenger en halvtime mer og gir en klissere saus. Goa lager selv utgaven med oksekjøtt, og det er en av få indiske delstater der det ikke vekker oppsikt.'}},
    {title:{en:'If you want the potato', no:'Hvis du vil ha poteten'},
     body:{en:'Some Goan households add potato. Fry small waxy potatoes whole in the oil before the onion and return them for the last twenty minutes. The ingredient is a variation even though the dish name itself does not derive from <em>aloo</em>.',
           no:'Noen goanske husholdninger bruker potet. Stek små fastkokende poteter hele i oljen før løken, og legg dem tilbake de siste tjue minuttene. Råvaren er en variant selv om rettens navn ikke kommer fra <em>aloo</em>.'}},
    {title:{en:'Vindalho de galinha', no:'Vindalho de galinha'},
     body:{en:'The chicken version uses thighs on the bone, marinates for two hours rather than overnight, and needs only thirty-five minutes in the pot. It is weeknight food where the pork version is a Sunday.',
           no:'Utgaven med kylling bruker lår med bein, den marineres i to timer i stedet for over natten, og den trenger bare trettifem minutter i gryta. Den er hverdagsmat der utgaven med svinekjøtt er søndagsmat.'}}]
},

{
  id:'goan-fish-curry-rice', dish:'Fish curry rice', course:'main', lesson:2, serves:4, veg:false,
  time:{prep:25, cook:35}, hero:'fish-curry-rice', tags:['fish','coconut','everyday'],
  title:{en:'Fish curry rice', no:'Fiskekarri med ris'},
  blurb:{en:'The everyday Goan lunch: a thin orange coconut gravy ground fresh that morning, over par-boiled rice.',
         no:'Hverdagslunsjen i Goa: en tynn oransje kokossaus malt samme morgen, over forkokt ris.'},
  heroCaption:{en:'The plate as it is actually served: rice in the middle, a bowl of curry, a fried fish, a vegetable and something sour to drink.',
               no:'Tallerkenen slik den faktisk serveres: ris i midten, en skål karri, en stekt fisk, en grønnsakrett og noe surt å drikke.'},
  goesWith:[{en:'A mackerel fried separately in chilli and turmeric', no:'En makrell stekt for seg i chili og gurkemeie'},
            {en:'Solkadhi, or plain buttermilk, at the end', no:'Solkadhi, eller vanlig kjernemelk, til slutt'}],
  headnote:{
    en:`<p><em>Xit kodi</em>, rice and curry, names an everyday meal pattern found across Goa, although the fish, rice and gravy vary by household, season and community. A plate might combine par-boiled rice, a light coconut fish curry and fried fish or vegetables.</p>
<p>This version uses a fresh wet masala of grated coconut, dried chilli, coriander, turmeric, garlic and tamarind. Other cooks roast some ingredients, use a different souring agent or adjust the texture.</p>
<p>Goan Hindu and Catholic kitchens overlap without being identical. Kokum and tamarind are both common souring agents; vinegar and onion appear in some recipes and not in others. The method below is one coherent version rather than a rule for every household.</p>`,
    no:`<p><em>Xit kodi</em>, ris og karri, er navnet på et hverdagsmåltid som finnes over hele Goa, men fisk, ris og saus varierer med husholdning, årstid og miljø. En tallerken kan samle forkokt ris, en lett fiskekarri med kokos og stekt fisk eller grønnsaker.</p>
<p>Denne utgaven bruker en fersk, våt masala av revet kokos, tørket chili, koriander, gurkemeie, hvitløk og tamarind. Andre kokker rister noen av råvarene, velger en annen syre eller justerer konsistensen.</p>
<p>Hinduistiske og katolske kjøkken i Goa overlapper uten å være identiske. Kokum og tamarind er begge vanlige syrer; eddik og løk finnes i noen oppskrifter og ikke i andre. Metoden nedenfor er én sammenhengende utgave, ikke en regel for alle husholdninger.</p>`},
  ingredients:[
   {group:{en:'The masala', no:'Masalaen'}, items:[
    {q:150, u:'g', n:{en:'grated coconut', no:'revet kokos'}, note:{en:'fresh or frozen and thawed, not desiccated', no:'fersk eller fryst og tint, ikke tørket kokosmasse'}},
    {q:8, u:'', n:{en:'dried Kashmiri chillies', no:'tørkede Kashmiri-chilier'}, round:'half'},
    {q:10, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:4, u:'g', n:{en:'cumin seed', no:'hele spisskummenfrø'}},
    {q:5, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:2, u:'g', n:{en:'black peppercorns', no:'hele sorte pepperkorn'}},
    {q:15, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:15, u:'g', n:{en:'tamarind from a block', no:'tamarind fra blokk'}, note:{en:'soaked in warm water and strained', no:'bløtlagt i lunkent vann og silt'}},
   ]},
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:700, u:'g', n:{en:'firm white fish, in thick steaks', no:'fast hvit fisk, i tykke koteletter'}, note:{en:'kingfish in Goa; wolffish or hake here', no:'kongemakrell i Goa; steinbit eller lysing her'}},
    {q:120, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chilier'}, round:'half', note:{en:'slit lengthways', no:'flekket på langs'}},
    {q:4, u:'', n:{en:'dried kokum rinds', no:'tørkede kokumskall'}, round:'half', note:{en:'rinsed; or a little more tamarind', no:'skylt; eller litt mer tamarind'}},
    {q:30, u:'ml', n:{en:'coconut oil', no:'kokosolje'}},
    {q:500, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The rice', no:'Risen'}, items:[
    {q:300, u:'g', n:{en:'par-boiled red rice', no:'forkokt rød ris'}, note:{en:'ukda or matta; rinsed until the water runs clear', no:'ukda eller matta; skylt til vannet er klart'}},
    {q:900, u:'ml', n:{en:'water for the rice', no:'vann til risen'}, scale:'sub'},
   ]}],
  steps:[
    {en:'Rinse the rice well and put it on to boil in plenty of water. Par-boiled rice takes about twenty-five minutes and is forgiving, so start it first and forget it.',
     no:'Skyll risen godt og sett den til koking i rikelig vann. Forkokt ris trenger omtrent tjuefem minutter og tåler mye, så sett den over først og glem den.'},
    {en:'Soak the tamarind in a little warm water, squeeze it with your fingers and strain out the seeds and fibres. Keep the liquid.',
     no:'Bløtlegg tamarinden i litt lunkent vann, klem den ut med fingrene og sil bort kjerner og tråder. Ta vare på væsken.'},
    {en:'Grind the coconut, dried chillies, coriander, cumin, turmeric, peppercorns and garlic with the tamarind liquid and just enough water to make a smooth orange paste. Keep going until no grit is left.',
     no:'Mal kokosen, de tørkede chiliene, korianderen, spisskummen, gurkemeien, pepperkornene og hvitløken sammen med tamarindvannet og akkurat nok vann til at det blir en glatt oransje pasta. Hold på til pastaen er helt glatt.'},
    {en:'Rub the fish steaks with salt and set them aside while you cook the gravy.',
     no:'Gni fiskekotelettene inn med salt, og sett dem til side mens du lager sausen.'},
    {en:'Warm the coconut oil in a wide pan and soften the onion over a low flame without letting it colour, about five minutes.',
     no:'Varm kokosoljen i en vid panne og la løken mykne på lav varme uten å ta farge, omtrent fem minutter.'},
    {en:'Stir in the ground paste and cook it for four or five minutes, until it thickens and smells cooked rather than raw. It will darken slightly.',
     no:'Rør inn den malte pastaen og la den surre i fire–fem minutter, til den tykner og lukter ferdig i stedet for rå. Den mørkner litt.'},
    {en:'Pour in the water, add the kokum and the green chillies, salt it, and bring it to a bare simmer. The gravy should be thin enough to pour.',
     no:'Hell i vannet, ha i kokumen og de grønne chiliene, salt, og la det så vidt småkoke. Sausen skal være tynn nok til å helles.'},
    {en:'Simmer uncovered for eight minutes so the coconut loses its raw edge, then taste. It should be sour, salty and only moderately hot.',
     no:'La det småkoke uten lokk i åtte minutter så kokosen mister den rå kanten, og smak så til. Sausen skal være sur, salt og bare middels sterk.'},
    {en:'Slide the fish in, turn the heat right down and cook for six to eight minutes. Swirl the pan instead of stirring, or the steaks break up.',
     no:'Legg fisken i, skru varmen helt ned og la det stå i seks–åtte minutter. Sving på pannen i stedet for å røre, ellers går kotelettene i stykker.'},
    {en:'Take the pan off the heat and let it stand for ten minutes before serving. Serve the rice separately and let people build their own plate.',
     no:'Ta pannen av platen og la den stå i ti minutter før servering. Sett risen for seg, og la hver enkelt sette sammen sin egen tallerken.'}],
  notes:[
    {title:{en:'Why the masala is ground and not roasted', no:'Hvorfor masalaen males og ikke ristes'},
     body:{en:'Roasting the coconut, as in many xacuti recipes, gives a darker, nuttier gravy. This curry aims for a lighter result. Raw ground coconut stays pale, and four minutes in the pan removes its raw edge.',
           no:'Rister du kokosen, slik mange xacuti-oppskrifter gjør, får du en mørkere og mer nøtteaktig saus. Denne karrien sikter mot et lettere resultat. Rå malt kokos holder seg lys, og fire minutter i pannen tar bort råkanten.'}},
    {title:{en:'Why the fish goes in last and the pan is never stirred', no:'Hvorfor fisken går i sist og pannen aldri røres'},
     body:{en:'A thin gravy has nothing to hold a fish steak together, so the fish is cooked for the shortest time that will do the job and moved as little as possible. If you want the fish and the gravy both at their best, fry a second fish separately in chilli and turmeric and lay it on the plate beside the bowl, which is what Goa does.',
           no:'En tynn saus har ingenting som holder en fiskekotelett sammen, så fisken kokes så kort tid som mulig og flyttes minst mulig. Vil du ha både fisken og sausen på sitt beste, steker du en fisk til for seg i chili og gurkemeie og legger den på tallerkenen ved siden av skålen, slik man gjør i Goa.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Ask the counter for steaks cut across the bone rather than fillets; a bone-in steak survives the gravy and a fillet falls apart in it.',
           no:'Be fiskedisken om koteletter skåret på tvers av beinet i stedet for filet, for en kotelett med bein tåler sausen mens en filet faller fra hverandre i den. Steinbit er den beste norske fisken til dette og ligner mest på kongemakrell; lysing og breiflabb fungerer også, mens torsk blir for løs. Fryst revet kokos fra en asiatisk butikk er langt bedre enn tørket kokosmasse fra bakeavdelingen, som er søtet og aldri blir glatt. Kokum og tamarind i blokk selges i indiske butikker; kokum heter ofte kokam eller amsul på pakken. Forkokt rød ris finner du som matta- eller ukda-ris i indisk butikk, og italiensk parboiled ris er ikke det samme.'}}],
  variations:[
    {title:{en:'With prawns', no:'Med reker'},
     body:{en:'Raw shell-on prawns need three minutes rather than eight, and go in at the very end. Keep the heads on if you can; they leak into the gravy and are half the reason to make it this way.',
           no:'Rå reker med skall trenger tre minutter i stedet for åtte og går i helt til slutt. Ha gjerne hodene på; de lekker ut i sausen, og det er halve grunnen til å lage retten slik.'}},
    {title:{en:'The monsoon version', no:'Monsunutgaven'},
     body:{en:'When the boats stay in, Goa cooks the same gravy with dried fish, or with nothing at all but a handful of okra and a few prawns. The curry is the constant; what goes in it is whatever the weather allowed.',
           no:'Når båtene blir liggende, lager Goa den samme sausen med tørket fisk, eller helt uten fisk med bare en neve okra og noen få reker. Karrien er det faste; hva som går i den, avhenger av hva været tillot.'}},
    {title:{en:'Ambot tik, the sour and hot one', no:'Ambot tik, den sure og sterke'},
     body:{en:'Leave the coconut out altogether, double the dried chilli and sour it with kokum and a little vinegar. You get a thin, fierce red curry that keeps for three days, traditionally made with shark or catfish.',
           no:'Sløyf kokosen helt, doble mengden tørket chili og syrne med kokum og litt eddik. Da får du en tynn og hissig rød karri som holder seg i tre dager, og som tradisjonelt lages med hai eller malle.'}}]
},

{
  id:'recheado-mackerel', dish:'', course:'main', lesson:1, serves:4, veg:false,
  time:{prep:35, cook:15}, hero:'recheado-mackerel', tags:['fish','vinegar','fast'],
  title:{en:'Recheado-stuffed mackerel', no:'Makrell fylt med recheado'},
  blurb:{en:'A whole mackerel slit along the bone, packed with a vinegar-ground chilli paste and fried.',
         no:'Hel makrell skåret opp langs beinet, fylt med en chilipasta malt i eddik og stekt.'},
  heroCaption:{en:'The cut runs along the backbone so the paste sits against the bone, where it cooks down to a sweet-sour jam.',
               no:'Snittet går langs ryggbeinet, så pastaen ligger inn mot beinet, der den koker inn til en sursøt masse.'},
  goesWith:[{en:'Par-boiled rice and a bowl of the daily fish curry', no:'Forkokt ris og en skål av den daglige fiskekarrien'},
            {en:'Raw onion and a wedge of lime, and nothing else', no:'Rå løk og en limebåt, og ikke noe mer'}],
  headnote:{
    en:`<p>Recheado means stuffed, and here the red vinegar-ground paste is packed into a whole fish before frying. Make only a small batch of paste unless you plan to freeze portions.</p>
<p>Oily fish such as mackerel stands up well to the sharp paste. Keeping the fish whole creates a pocket beside the backbone for the stuffing, though the same paste can season fillets.</p>
<p>The vinegar supplies flavour and grinding liquid, but it does not make the paste shelf-stable. Refrigerate it promptly, use it within a few days or freeze it. Keep the stuffed fish cold while it marinates.</p>`,
    no:`<p>Recheado betyr fylt, og her pakkes den røde pastaen som er malt med eddik, inn i en hel fisk før steking. Lag bare en liten porsjon pasta hvis du ikke vil fryse ned deler av den.</p>
<p>Fet fisk som makrell tåler den skarpe pastaen godt. En hel fisk gir en lomme ved ryggbeinet til fyllet, men den samme pastaen kan også smaksette fileter.</p>
<p>Eddiken gir smak og væske til malingen, men gjør ikke pastaen holdbar i romtemperatur. Sett den raskt kaldt, bruk den i løpet av få dager eller frys den. Hold den fylte fisken kald mens den marineres.</p>`},
  ingredients:[
   {group:{en:'The recheado paste', no:'Recheado-pastaen'}, items:[
    {q:15, u:'', n:{en:'dried Kashmiri chillies', no:'tørkede Kashmiri-chilier'}, round:'half', note:{en:'stalks off, most seeds shaken out', no:'uten stilk, med det meste av frøene ristet ut'}},
    {q:120, u:'ml', n:{en:'palm or cider vinegar', no:'palmeeddik eller eplesidereddik'}},
    {q:30, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:20, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:5, u:'g', n:{en:'cumin seed', no:'hele spisskummenfrø'}},
    {q:6, u:'', n:{en:'cloves', no:'hele nellik'}, round:'half'},
    {q:1, u:'', n:{en:'piece of cinnamon bark', no:'bit kanelbark'}, round:'half'},
    {q:3, u:'g', n:{en:'black peppercorns', no:'hele sorte pepperkorn'}},
    {q:10, u:'g', n:{en:'tamarind from a block', no:'tamarind fra blokk'}},
    {q:12, u:'g', n:{en:'sugar', no:'sukker'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The fish', no:'Fisken'}, items:[
    {q:4, u:'', n:{en:'whole mackerel', no:'hele makreller'}, round:'half', note:{en:'gutted and scaled, heads on', no:'sløyd og skrapt, med hodet på'}},
    {q:60, u:'g', n:{en:'fine semolina', no:'fint semulegryn'}, note:{en:'for dusting', no:'til å strø utenpå'}},
    {q:60, u:'ml', n:{en:'neutral oil, for frying', no:'nøytral olje, til steking'}, scale:'none'},
    {q:1, u:'', n:{en:'lime', no:'lime'}, round:'half'},
   ]}],
  steps:[
    {en:'Break the chillies open, shake out most of the seeds and soak them in the vinegar for half an hour, until they are soft and the vinegar has gone red.',
     no:'Brekk opp chiliene, rist ut mesteparten av frøene og legg dem i eddiken i en halvtime, til de er myke og eddiken har blitt rød.'},
    {en:'Grind the soaked chillies with their vinegar, the garlic, ginger, cumin, cloves, cinnamon, peppercorns, tamarind, sugar and a good pinch of salt into a thick smooth paste. Use no water.',
     no:'Mal de bløtlagte chiliene med eddiken, hvitløken, ingefæren, spisskummen, nelliken, kanelen, pepperkornene, tamarinden, sukkeret og en god klype salt til en tykk og glatt pasta. Ikke bruk vann.'},
    {en:'Taste it. It should be sharp, salty and faintly sweet. Put what you do not use into a clean container, refrigerate it promptly, and use within a few days or freeze it.',
     no:'Smak på den. Den skal være skarp, salt og svakt søt. Ha det du ikke bruker, i en ren beholder, sett den raskt kaldt og bruk den i løpet av få dager eller frys den.'},
    {en:'Lay each mackerel flat and cut a deep pocket along one side of the backbone, from behind the head to the tail, without cutting the fish in two.',
     no:'Legg hver makrell flatt og skjær en dyp lomme langs den ene siden av ryggbeinet, fra bak hodet og ut mot halen, uten å dele fisken i to.'},
    {en:'Salt the fish inside and out and pack the pocket with paste, pressing it right down against the bone. Smear a thin film over the skin as well.',
     no:'Salt fisken inn- og utvendig og pakk lommen full av pasta, og press den helt inn mot beinet. Smør også et tynt lag utenpå skinnet.'},
    {en:'Leave the stuffed fish in the fridge for at least twenty minutes, and up to two hours. The vinegar firms the flesh while it waits.',
     no:'La den fylte fisken ligge i kjøleskapet i minst tjue minutter, og gjerne opptil to timer. Eddiken strammer opp fiskekjøttet mens den venter.'},
    {en:'Dust both sides with semolina and press it on lightly. It should be a thin coat, not a batter.',
     no:'Strø semulegryn på begge sider og trykk det lett fast. Det skal være et tynt lag, ikke en røre.'},
    {en:'Heat the oil in a wide pan over a medium flame. Too hot and the paste burns before the fish is done; too cool and the coating goes soggy.',
     no:'Varm oljen i en vid panne på middels varme. Er den for varm, svir pastaen seg før fisken er ferdig; er den for kald, blir laget utenpå bløtt.'},
    {en:'Fry the fish for four or five minutes on the first side, until the semolina is crisp and dark gold, then turn it once and give it three or four minutes more.',
     no:'Stek fisken i fire–fem minutter på første side, til semulegrynet er sprøtt og mørkt gyllent, snu den så én gang og gi den tre–fire minutter til.'},
    {en:'Lift it onto paper for a minute, then serve it whole with lime. The paste against the bone should have cooked down dark and sticky.',
     no:'Løft den over på papir et minutt, og server den hel med lime. Pastaen inn mot beinet skal ha kokt inn og blitt mørk og klebrig.'}],
  notes:[
    {title:{en:'Why there is sugar in the paste', no:'Hvorfor det er sukker i pastaen'},
     body:{en:'A small amount of sugar does not make the paste sweet. It rounds off the sharpest edge of the vinegar and, more usefully, it caramelises against the hot bone and turns the stuffing from a wet paste into something jammy. Leave it out and the fish tastes raw and one-note.',
           no:'En liten mengde sukker gjør ikke pastaen søt. Det runder av den skarpeste kanten på eddiken, og enda nyttigere: det karamelliserer mot det varme beinet og gjør fyllet om fra en våt pasta til noe klebrig og syltetøyaktig. Sløyfer du det, smaker fisken rå og endimensjonal.'}},
    {title:{en:'Why semolina and not flour', no:'Hvorfor semulegryn og ikke mel'},
     body:{en:'Semolina is coarse, so it sits on the skin as separate grains and crisps in the pan instead of turning to paste. Flour absorbs the moisture coming out of the fish and goes gluey. This is the standard coating for fried fish all down the Konkan coast, and it is worth copying for any fish you pan-fry.',
           no:'Semulegryn er grovt, så det blir liggende som enkeltkorn på skinnet og blir sprøtt i pannen i stedet for å bli til en deig. Mel suger til seg væsken som kommer ut av fisken, og blir klissete. Dette er standarden for stekt fisk langs hele Konkan-kysten, og den er verdt å kopiere til all fisk du steker i panne.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Norwegian mackerel from late summer is fatter than anything Goa lands, and it is the best fish in the country for this.',
           no:'Norsk makrell fra sensommeren av er fetere enn noe Goa får i land, og den er den beste fisken i landet til dette. Be fiskedisken sløye den og la hodet sitte på; fryst makrell fungerer godt hvis den tines langsomt i kjøleskapet. Hele tørkede Kashmiri-chilier og tamarind i blokk får du i indiske butikker; kokoseddik fra en asiatisk butikk ligner mest på palmeeddik. Semulegryn står i vanlige dagligvarebutikker, og det fine er bedre enn det grove her. Den norske sildefileten i krydderlake er ikke et alternativ, og rødspette er for mager.'}}],
  variations:[
    {title:{en:'Prawns and squid', no:'Reker og blekksprut'},
     body:{en:'Toss large raw prawns or rings of squid in the paste and fry them hard for two minutes. There is nothing to stuff, so the paste works as a marinade, and the sugar in it browns fast, so keep the pan moving.',
           no:'Vend store rå reker eller ringer av blekksprut i pastaen og stek dem hardt i to minutter. Det er ingenting å fylle, så pastaen virker som marinade, og sukkeret i den bruner seg fort, så hold pannen i bevegelse.'}},
    {title:{en:'A whole flat fish', no:'Hel flyndre'},
     body:{en:'A plaice or a small turbot takes the same treatment, cut through the dark skin on the bias rather than along a backbone. It is leaner, so add a little oil to the paste before stuffing it.',
           no:'En rødspette eller en liten piggvar tåler den samme behandlingen, men snittet legges på skrå gjennom den mørke siden i stedet for langs ryggbeinet. Fisken er magrere, så ha litt olje i pastaen før du fyller den.'}},
    {title:{en:'Recheado pork chops', no:'Svinekoteletter med recheado'},
     body:{en:'Smear the paste over thick pork chops, leave them overnight and grill them. This is closer to what the paste was originally for, and it is the shortest route from a jar in the fridge to something that tastes of Goa.',
           no:'Smør pastaen utover tykke svinekoteletter, la dem ligge over natten og grill dem. Dette ligger nærmere det pastaen opprinnelig var til, og det er den korteste veien fra et glass i kjøleskapet til noe som smaker av Goa.'}}]
},

{
  id:'chicken-xacuti', dish:'Xacuti', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:30, cook:55}, hero:'xacuti', tags:['chicken','coconut','roasted spice'],
  title:{en:'Chicken xacuti', no:'Xacuti med kylling'},
  blurb:{en:'Chicken in a deep, aromatic masala of roasted coconut and whole spices.',
         no:'Kylling i en dyp og aromatisk masala av ristet kokos og hele krydder.'},
  heroCaption:{en:'Roasted coconut gives this version its brown colour and much of its body.',
               no:'Ristet kokos gir denne utgaven brunfargen og mye av fylden.'},
  goesWith:[{en:'Sannas, or a soft white roll to tear up', no:'Sannas, eller et mykt rundstykke å rive opp'},
            {en:'Plain rice, if you would rather', no:'Vanlig ris, hvis du heller vil ha det'}],
  headnote:{
    en:`<p>Xacuti is a family of Goan dishes built around roasted coconut and an aromatic masala. In this version the coconut is taken beyond gold into brown, giving the gravy colour, body and a slightly bitter edge.</p>
<p>The spice list varies between cooks. This recipe uses poppy seed for body, with nutmeg and star anise among the high aromatic notes; other sound versions omit or replace them. Roast by smell and colour rather than chasing a fixed number of spices.</p>
<p>The spelling is Portuguese. An initial x in that language is pronounced like an English sh, so the word is roughly sha-KOO-tee, and you will also see it written chacuti on older menus.</p>`,
    no:`<p>Xacuti er en familie av goanske retter bygd på ristet kokos og en aromatisk masala. I denne utgaven ristes kokosen forbi gyllen og over i brunt, slik at sausen får farge, fylde og en svakt bitter kant.</p>
<p>Krydderlisten varierer fra kokk til kokk. Denne oppskriften bruker valmuefrø for fylde, med muskat og stjerneanis blant de høye aromatiske tonene; andre gode utgaver utelater eller erstatter dem. Rist etter lukt og farge i stedet for å jage et fast antall krydder.</p>
<p>Skrivemåten er portugisisk. En x først i ordet uttales på det språket som norsk sj, så ordet lyder omtrent sja-KU-ti, og på eldre menyer ser du det skrevet chacuti.</p>`},
  ingredients:[
   {group:{en:'The masala', no:'Masalaen'}, items:[
    {q:120, u:'g', n:{en:'grated coconut', no:'revet kokos'}, note:{en:'fresh or frozen and thawed', no:'fersk eller fryst og tint'}},
    {q:8, u:'', n:{en:'dried Kashmiri chillies', no:'tørkede Kashmiri-chilier'}, round:'half'},
    {q:12, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:5, u:'g', n:{en:'cumin seed', no:'hele spisskummenfrø'}},
    {q:12, u:'g', n:{en:'white poppy seed', no:'hvite valmuefrø'}},
    {q:3, u:'g', n:{en:'black peppercorns', no:'hele sorte pepperkorn'}},
    {q:8, u:'', n:{en:'cloves', no:'hele nellik'}, round:'half'},
    {q:1, u:'', n:{en:'piece of cinnamon bark', no:'bit kanelbark'}, round:'half'},
    {q:2, u:'', n:{en:'star anise', no:'stjerneanis'}, round:'half'},
    {q:4, u:'', n:{en:'green cardamom pods', no:'grønne kardemommekapsler'}, round:'half'},
    {q:3, u:'g', n:{en:'grated nutmeg', no:'revet muskatnøtt'}, note:{en:'about a quarter of a whole one', no:'omtrent en fjerdedel av en hel'}},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
   ]},
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:1000, u:'g', n:{en:'chicken on the bone', no:'kylling med bein'}, note:{en:'thighs and drumsticks, skin off', no:'lår og klubber, uten skinn'}},
    {q:300, u:'g', n:{en:'onions', no:'løk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:20, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:20, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:50, u:'ml', n:{en:'coconut oil', no:'kokosolje'}},
    {q:500, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub'},
    {q:1, u:'', n:{en:'lime', no:'lime'}, round:'half', note:{en:'to finish', no:'til slutt'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Put a heavy dry pan on a medium flame and roast the grated coconut, stirring without stopping, until it goes from white through gold to a proper brown. This takes ten minutes and it burns in the last thirty seconds, so do not walk away.',
     no:'Sett en tung, tørr panne på middels varme og rist den revne kokosen under stadig omrøring, til den går fra hvit via gyllen til skikkelig brun. Det tar ti minutter, og den svir seg på de siste tretti sekundene, så ikke gå fra den.'},
    {en:'Tip the coconut out onto a plate to stop it cooking. In the same pan, roast the dried chillies, coriander, cumin, poppy seed, peppercorns, cloves, cinnamon, star anise and cardamom for two minutes, until they smell toasted.',
     no:'Hell kokosen over på en tallerken så den slutter å steke. Rist i den samme pannen de tørkede chiliene, korianderen, spisskummen, valmuefrøene, pepperkornene, nelliken, kanelen, stjerneanisen og kardemommen i to minutter, til det lukter ristet.'},
    {en:'Grind the roasted coconut and spices together with the nutmeg, the turmeric and just enough water to make a thick, dark, slightly gritty paste. Set it aside.',
     no:'Mal den ristede kokosen og krydderet sammen med muskaten, gurkemeien og akkurat nok vann til at det blir en tykk, mørk og litt grov pasta. Sett den til side.'},
    {en:'Crush the garlic and ginger together to a paste with a little salt.',
     no:'Knus hvitløken og ingefæren sammen til en pasta med litt salt.'},
    {en:'Heat the coconut oil in a heavy pot and fry the onion over a medium flame until it is soft and well browned, fifteen minutes or so. This is the base of the gravy and it cannot be hurried.',
     no:'Varm kokosoljen i en tung gryte og stek løken på middels varme til den er myk og godt brunet, omtrent femten minutter. Dette er grunnlaget for sausen, og det lar seg ikke forsere.'},
    {en:'Stir in the garlic and ginger paste and cook it for a minute, until it stops smelling raw.',
     no:'Rør inn pastaen av hvitløk og ingefær og la den surre et minutt, til den slutter å lukte rått.'},
    {en:'Add the chicken, salt it, and turn the pieces in the onion over a high flame for five minutes so the surface sets.',
     no:'Ha i kyllingen, salt, og vend bitene i løken på sterk varme i fem minutter så overflaten stivner.'},
    {en:'Stir in the ground masala and cook it for five minutes, scraping the base, until the oil begins to separate out at the edges of the pan.',
     no:'Rør inn den malte masalaen og la den surre i fem minutter mens du skraper bunnen, til oljen begynner å skille seg ut langs kanten av gryta.'},
    {en:'Pour in the hot water, bring it to a simmer, cover and cook on a low flame for twenty-five minutes, until the chicken is tender and the gravy has thickened.',
     no:'Hell i det varme vannet, la det så vidt koke opp, legg på lokk og la det stå på lav varme i tjuefem minutter, til kyllingen er mør og sausen har tyknet.'},
    {en:'Take the lid off and let it reduce for five minutes more. The gravy should coat the back of a spoon and sit close around the chicken rather than pooling.',
     no:'Ta av lokket og la det koke inn i fem minutter til. Sausen skal dekke baksiden av en skje og ligge tett rundt kyllingen i stedet for å flyte utover.'},
    {en:'Squeeze the lime over, take the pot off the heat and let it stand, covered, for ten minutes before serving.',
     no:'Press limen over, ta gryta av platen og la den stå med lokk i ti minutter før servering.'}],
  notes:[
    {title:{en:'Why the coconut has to go past golden', no:'Hvorfor kokosen må ristes forbi gyllen'},
     body:{en:'Lightly toasted coconut tastes sweet and gives a pale gravy. The dark, almost bitter note that makes xacuti what it is only appears in the last two minutes of roasting, when the sugars in the coconut caramelise and start to break down. Stop early and you have made a different and blander dish.',
           no:'Lett ristet kokos smaker søtt og gir en lys saus. Den mørke, nesten bitre tonen som gjør xacuti til det den er, kommer først i de siste to minuttene av ristingen, når sukkeret i kokosen karamelliserer og begynner å brytes ned. Stopper du for tidlig, har du laget en annen og flatere rett.'}},
    {title:{en:'Why the poppy seed matters more than it looks', no:'Hvorfor valmuefrøene betyr mer enn de ser ut til'},
     body:{en:'Ground poppy seed swells in liquid and thickens a gravy without flour, cream or tomato, which is how a curry built on water alone comes out thick. It also carries a faint milky sweetness that keeps the roasted coconut from tasting scorched. Cashew paste is the nearest substitute and is noticeably sweeter.',
           no:'Malte valmuefrø sveller i væske og jevner en saus uten mel, fløte eller tomat, og det er slik en karri som bare inneholder vann, likevel blir tykk. De bærer også en svak melkeaktig sødme som hindrer den ristede kokosen i å smake svidd. Pasta av cashewnøtter ligger nærmest og er tydelig søtere.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Use thighs and drumsticks on the bone; breast dries out in twenty-five minutes of simmering and gives a thin gravy.',
           no:'Bruk lår og klubber med bein; kyllingbryst blir tørt av tjuefem minutter i gryta og gir en tynn saus. Fryst revet kokos fra asiatiske butikker er det eneste som rister skikkelig; tørket kokosmasse fra bakeavdelingen er søtet og svir seg ujevnt. Hvite valmuefrø må kjøpes i indisk butikk og heter safed posto; de blå valmuefrøene i dagligvarebutikken gjør retten grå og bitter. Kjøp hel muskatnøtt og riv den selv, for ferdigmalt muskat mister det meste på noen måneder.'}}],
  variations:[
    {title:{en:'With potato', no:'Med potet'},
     body:{en:'Some households add halved small potatoes for the last twenty minutes. They absorb the masala and make the dish go further.',
           no:'Noen husholdninger har i halve småpoteter de siste tjue minuttene. De trekker til seg masalaen og drøyer retten.'}},
    {title:{en:'Lamb, or guinea fowl', no:'Med lam eller perlehøne'},
     body:{en:'Lamb shoulder in the same masala needs an hour and a half rather than twenty-five minutes, and the roasted coconut suits it better than it suits chicken. Guinea fowl is the version you see in Goan restaurants that still cook game.',
           no:'Lammebog i den samme masalaen trenger halvannen time i stedet for tjuefem minutter, og den ristede kokosen kler den bedre enn den kler kylling. Perlehøne er utgaven du finner på de restaurantene i Goa som fortsatt lager viltfugl.'}},
    {title:{en:'A vegetarian xacuti', no:'Vegetarisk xacuti'},
     body:{en:'The masala is vegetarian to begin with. Use mushrooms, chickpeas and chunks of potato, reduce the simmering time to about fifteen minutes, and adjust the water so the gravy stays close and thick.',
           no:'Masalaen er vegetarisk i utgangspunktet. Bruk sopp, kikerter og biter av potet, kort koketiden ned til omtrent femten minutter og juster vannet så sausen forblir tett og tykk.'}}]
},

{
  id:'bebinca', dish:'Bebinca', course:'sweet', lesson:3, serves:10, veg:true,
  time:{prep:30, cook:110}, hero:'bebinca', tags:['Christmas','coconut','egg'],
  title:{en:'Bebinca', no:'Bebinca'},
  blurb:{en:'Layers of coconut milk, egg yolk and ghee, poured and browned one at a time.',
         no:'Lag av kokosmelk, eggeplomme og ghee, helt og brunet ett om gangen.'},
  heroCaption:{en:'A cross-section reveals the bands formed by successive pours under top heat.',
               no:'Et tverrsnitt viser stripene som dannes når nye lag helles på og stekes med overvarme.'},
  goesWith:[{en:'Nothing hot. It is eaten in thin slices at room temperature', no:'Ingenting varmt. Den spises i tynne skiver i romtemperatur'},
            {en:'A small glass of feni, if the occasion allows', no:'Et lite glass feni, hvis anledningen tillater det'}],
  headnote:{
    en:`<p>Bebinca is strongly associated with Goan Catholic celebrations, including Christmas. Coconut milk, egg yolks, sugar, flour, ghee and nutmeg become a cake built one thin layer at a time.</p>
<p>A layer of batter cooks under heat from above until set and brown. Ghee is brushed over it, then the next layer is poured on. Layer counts vary; this recipe makes seven, and each may take roughly eight to ten minutes depending on the oven.</p>
<p>Two small mechanical points decide whether it works. The heat has to come from above, because a layer browned from below will not bond to the one under it. And the batter must be thin enough to pour and self-level, or the bands come out wavy and the slice loses the point of the exercise.</p>`,
    no:`<p>Bebinca forbindes sterkt med goansk-katolske høytider, blant annet jul. Kokosmelk, eggeplommer, sukker, mel, ghee og muskat blir til en kake som bygges ett tynt lag om gangen.</p>
<p>Et lag røre stekes med varme ovenfra til det har stivnet og blitt brunt. Så pensles ghee over før neste lag helles på. Antallet lag varierer; denne oppskriften lager sju, og hvert kan ta omtrent åtte–ti minutter avhengig av ovnen.</p>
<p>To små tekniske forhold avgjør om den lykkes. Varmen må komme ovenfra, for et lag som brunes nedenfra, binder seg ikke til laget under. Og røren må være tynn nok til å helles og legge seg jevnt av seg selv, ellers blir stripene bølgete og skiven mister hele poenget.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:400, u:'ml', n:{en:'full-fat coconut milk', no:'kokosmelk med fullt fettinnhold'}, note:{en:'tinned, not shaken, not light', no:'på boks, ikke ristet, og ikke light'}},
    {q:10, u:'', n:{en:'egg yolks', no:'eggeplommer'}, round:'half'},
    {q:250, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:180, u:'g', n:{en:'plain flour', no:'hvetemel'}, note:{en:'sifted', no:'siktet'}},
    {q:120, u:'g', n:{en:'ghee', no:'ghee'}, note:{en:'melted, for brushing between the layers', no:'smeltet, til å pensle mellom lagene'}},
    {q:2, u:'g', n:{en:'grated nutmeg', no:'revet muskatnøtt'}},
    {q:1, u:'g', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Warm the coconut milk gently with the sugar until the sugar dissolves, then take it off the heat and let it cool to room temperature.',
     no:'Varm kokosmelken forsiktig med sukkeret til sukkeret er løst opp, ta den så av platen og la den kjøle seg til romtemperatur.'},
    {en:'Beat the egg yolks until they are pale and thick, then whisk the cooled coconut milk into them a little at a time.',
     no:'Pisk eggeplommene til de er lyse og tykke, og visp så den avkjølte kokosmelken inn i dem litt om gangen.'},
    {en:'Sift the flour over the mixture with the nutmeg and the salt, and whisk until there is not a lump left. The batter should pour like single cream.',
     no:'Sikt melet over blandingen sammen med muskaten og saltet, og visp til det ikke er en eneste klump igjen. Røren skal renne som tynn fløte.'},
    {en:'Strain the batter through a sieve and leave it to stand for half an hour. This is what makes the layers lie flat.',
     no:'Sil røren gjennom en finmasket sil og la den stå i en halvtime. Det er dette som gjør at lagene legger seg flatt.'},
    {en:'Heat the oven grill and set a shelf so the top of a deep 20 cm tin will sit about 15 cm below the element. Brush the tin generously with ghee.',
     no:'Sett ovnen på grill og plasser risten slik at toppen av en dyp form på 20 cm står omtrent 15 cm under varmeelementet. Pensle formen godt med ghee.'},
    {en:'Pour in enough batter to cover the base to the depth of a coin, and grill it until it is set and evenly browned, eight to ten minutes.',
     no:'Hell i akkurat nok røre til å dekke bunnen så tykt som en mynt, og grill til laget har stivnet og er jevnt brunet, åtte–ti minutter.'},
    {en:'Take the tin out, brush the hot surface with ghee and let it soak in for a moment, then pour the next layer straight on top.',
     no:'Ta ut formen, pensle den varme overflaten med ghee og la det trekke inn et øyeblikk, og hell så neste lag rett oppå.'},
    {en:'Grill that layer as you did the first, and keep going. Later layers set faster than the first ones, so watch them rather than the clock.',
     no:'Grill det laget slik du gjorde med det første, og hold på videre. De siste lagene stivner raskere enn de første, så følg med på dem i stedet for på klokka.'},
    {en:'Finish on a layer that has browned a shade darker than the rest, which is the top of the cake and should look deliberate.',
     no:'Avslutt med et lag som er brunet et hakk mørkere enn de andre, for det er toppen av kaken og skal se tilsiktet ut.'},
    {en:'Let it cool completely in the tin, then turn it out and leave it a further two hours before cutting. It slices cleanly only when it is cold.',
     no:'La den kjøle seg helt ned i formen, vend den så ut og la den stå i to timer til før du skjærer i den. Den lar seg bare skjære pent når den er kald.'},
    {en:'Cut it in thin slices with a long knife wiped clean between cuts, so the layers stay visible.',
     no:'Skjær tynne skiver med en lang kniv som tørkes av mellom hvert snitt, så lagene holder seg synlige.'}],
  notes:[
    {title:{en:'Why the heat has to come from above', no:'Hvorfor varmen må komme ovenfra'},
     body:{en:'Each new layer is poured onto a hot cooked surface and has to bond to it while setting from the top down. Baking from below cooks the bottom layer twice, dries it out and leaves the new layer sitting loose on it, so the cake falls apart in slices instead of holding together in bands.',
           no:'Hvert nye lag helles på en varm og ferdig stekt flate og må binde seg til den mens det stivner ovenfra og ned. Steker du nedenfra, blir det nederste laget stekt to ganger, det tørker ut, og det nye laget blir liggende løst oppå. Da faller kaken fra hverandre i stedet for å holde sammen i striper.'}},
    {title:{en:'Why the batter rests', no:'Hvorfor røren må hvile'},
     body:{en:'Half an hour lets the flour hydrate fully and lets the air whisked into the yolks escape. An unrested batter holds bubbles that burst under the grill and pit the surface, and a pitted surface makes the next layer uneven. Every layer after that inherits the fault.',
           no:'En halvtime lar melet trekke til seg all væsken og lar luften du har pisket inn i plommene, slippe ut. En røre som ikke har hvilt, holder på bobler som sprekker under grillen og lager groper i overflaten, og en gropete overflate gjør neste lag ujevnt. Alle lagene etter det arver feilen.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy tinned full-fat coconut milk and do not shake the tin; the thick part at the top is what the recipe is built on.',
           no:'Kjøp kokosmelk på boks med fullt fettinnhold, og ikke rist boksen; den tykke delen øverst er det oppskriften bygger på. Kokosmelk merket «light» har ingen tykk del i det hele tatt og gir en vassen kake. Ghee selges i indiske butikker og i de fleste større dagligvarebutikker; klaret smør du lager selv, fungerer like godt, men vanlig smør gjør det ikke, for vannet i det damper mellom lagene og løsner dem. Kjøp hel muskatnøtt og riv den selv. Bruk eggeplommene fra store egg, og lag en kokosmakron av hvitene samme dag.'}}],
  variations:[
    {title:{en:'Sixteen layers', no:'Seksten lag'},
     body:{en:'The traditional boast. Use the same batter, pour half as much each time and expect three hours at the oven. The slices are finer and the cake is denser, and everyone who is told the number will count them.',
           no:'Det tradisjonelle skrytet. Bruk den samme røren, hell i halvparten så mye hver gang, og regn med tre timer ved ovnen. Skivene blir finere og kaken fastere, og alle som får høre tallet, kommer til å telle.'}},
    {title:{en:'Dodol, if bebinca is too much', no:'Dodol, hvis bebinca blir for mye'},
     body:{en:'The other Goan Christmas sweet is coconut milk, jaggery and rice flour stirred in one pan until it comes away from the sides, then set and cut in squares. It takes the same ingredients and one pan instead of an evening.',
           no:'Den andre søtsaken goanerne lager til jul, er kokosmelk, jaggery og rismel som røres i én kjele til massen slipper kanten, og som deretter får stivne og skjæres i firkanter. Den bruker de samme råvarene og krever én kjele i stedet for en hel kveld.'}},
    {title:{en:'Keeping it', no:'Slik oppbevarer du den'},
     body:{en:'Wrapped and kept somewhere cool, a bebinca is good for two weeks and arguably better after three days, when the ghee has settled and the layers have knitted. Do not refrigerate it; the ghee goes hard and the texture turns waxy.',
           no:'Pakker du den inn og oppbevarer den kjølig, holder en bebinca seg i to uker, og den er trolig bedre etter tre dager, når gheen har satt seg og lagene har vokst sammen. Ikke sett den i kjøleskapet; da stivner gheen og konsistensen blir voksaktig.'}}]
},

];
