/* Masala Dabba — recipes for Gujarat (IN-GUJ). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-GUJ'] = [

{
  id:'dhokla', dish:'Dhokla', course:'snack', lesson:3, serves:6, veg:true,
  time:{prep:30, cook:25}, hero:'dhokla', tags:['steamed','fermented','breakfast'],
  title:{en:'Dhokla, fermented properly', no:'Dhokla, gjæret slik den skal'},
  blurb:{en:'A batter of rice and split chickpea left overnight, steamed to a sponge and tempered with mustard, sesame and curry leaf.',
         no:'En røre av ris og splittede kikerter som står natten over, dampes til en svamp og tempereres med sennep, sesam og karriblad.'},
  heroCaption:{en:'The squares in this photograph are the quick gram-flour version. A fermented batter gives a paler, lighter crumb and a clear sourness behind the sweetness.',
               no:'Firkantene på bildet er den raske utgaven, laget av kikertmel. En gjæret røre gir en lysere og lettere krumme og en tydelig syrlighet bak sødmen.'},
  goesWith:[{en:'Green coriander chutney', no:'Grønn chutney av koriander'},
            {en:'Strong milky tea, which is what it is eaten with', no:'Sterk te med melk, som er det den spises til'}],
  headnote:{
    en:`<p>Most of what is sold as dhokla outside Gujarat is khaman: gram flour, a spoon of eno, twenty minutes. This is the other one. Rice and split chickpea are soaked, ground into a thick batter and left out overnight, and the wild yeasts and bacteria already on the grain raise it while the starch turns faintly sour.</p>
<p>You are trading twelve hours for flavour, and the trade is worth making once so that you know the difference. Fermented dhokla is paler, lighter and tangier, and it holds its crumb for a day instead of drying out by the afternoon. The chemical version is a good snack. This is a different food.</p>
<p>The two things that go wrong are both about temperature. A cold Norwegian kitchen will not ferment the batter in a night, so it needs somewhere warm, and a steamer run too hard makes the surface wet and the middle dense. Keep the water at a steady simmer rather than a rolling boil.</p>`,
    no:`<p>Det meste som selges som dhokla utenfor Gujarat, er khaman: kikertmel, en skje eno, tjue minutter. Dette er den andre. Ris og splittede kikerter bløtlegges, males til en tykk røre og blir stående natten over, og villgjæren og bakteriene som alt sitter på kornet, hever den mens stivelsen blir svakt sur.</p>
<p>Du bytter tolv timer mot smak, og byttet er verdt å gjøre minst én gang, så du kjenner forskjellen. Gjæret dhokla er lysere, lettere og syrligere, og den holder på krummen et helt døgn i stedet for å tørke ut utover ettermiddagen. Den kjemiske utgaven er en god liten rett. Denne er noe helt annet.</p>
<p>De to tingene som går galt, handler begge om temperatur. Et kaldt norsk kjøkken gjærer ikke røren på en natt, så den trenger et lunt sted, og en damper som går for hardt, gjør overflaten våt og midten tung. Hold vannet på jevn småkoking i stedet for fosskok.</p>`},
  ingredients:[
   {group:{en:'The batter', no:'Røren'}, items:[
    {q:200, u:'g', n:{en:'short-grain rice', no:'kortkornet ris'}, note:{en:'soaked 5 hours', no:'bløtlagt i 5 timer'}},
    {q:100, u:'g', n:{en:'chana dal', no:'chana dal'}, note:{en:'soaked separately, 5 hours', no:'bløtlagt for seg, 5 timer'}},
    {q:4, u:'g', n:{en:'fenugreek seed', no:'frø av bukkehornkløver'}, note:{en:'soaked with the dal', no:'bløtlagt sammen med dalen'}},
    {q:250, u:'ml', n:{en:'water', no:'vann'}, note:{en:'for grinding, added slowly', no:'til malingen, has i litt etter litt'}, scale:'sub'},
    {q:20, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste with the chillies', no:'malt til en pasta sammen med chiliene'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:10, u:'g', n:{en:'sugar', no:'sukker'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The tempering and the finish', no:'Temperingen og avslutningen'}, items:[
    {q:45, u:'ml', n:{en:'groundnut or sunflower oil', no:'jordnøttolje eller solsikkeolje'}},
    {q:8, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:10, u:'g', n:{en:'white sesame seed', no:'hvite sesamfrø'}},
    {q:15, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'snittet på langs'}},
    {q:100, u:'ml', n:{en:'water', no:'vann'}, note:{en:'for the sugared water poured over', no:'til sukkervannet som helles over'}, scale:'sub'},
    {q:20, u:'g', n:{en:'sugar', no:'sukker'}, note:{en:'for the same', no:'til det samme'}},
    {q:30, u:'g', n:{en:'grated fresh coconut', no:'revet fersk kokos'}},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
   ]}],
  steps:[
    {en:'Drain the rice and the dal and grind them together with the fenugreek and just enough of the water to move the blades. You want a batter about as thick as a pancake batter and slightly grainy rather than silky.',
     no:'Hell av bløtevannet fra risen og dalen, og kjør dem sammen med bukkehornkløveren og akkurat nok av vannet til at knivene går rundt. Røren skal være omtrent som en pannekakerøre, litt grynete og ikke helt glatt.'},
    {en:'Stir in salt, cover the bowl loosely and leave it somewhere warm for ten to twelve hours. An oven with only the light on holds the right temperature in a cold flat.',
     no:'Rør inn salt, legg et løst lokk over bollen og sett den lunt i ti til tolv timer. En stekeovn med bare lyset på holder riktig temperatur i en kald leilighet.'},
    {en:'The batter is ready when it has risen a little, carries bubbles on the surface and smells faintly sour. It will not double the way a bread dough does.',
     no:'Røren er ferdig når den har hevet seg litt, har bobler på overflaten og lukter svakt surt. Den dobler seg ikke slik en brøddeig gjør.'},
    {en:'Oil a shallow tray that fits inside your steamer, and bring the water in the steamer to a steady simmer rather than a hard boil.',
     no:'Smør et grunt brett som får plass i dampkokeren, og la vannet i dampkokeren gå på jevn småkoking og ikke fosskok.'},
    {en:'Beat the ginger and chilli paste, the turmeric and the sugar into the batter. Work quickly from here, and do not beat the air out of it.',
     no:'Pisk inn pastaen av ingefær og chili, gurkemeien og sukkeret i røren. Nå haster det, og du skal ikke piske luften ut av den.'},
    {en:'Pour the batter into the tray to a depth of about two centimetres, put it into the steamer and cover it. Steam for fifteen to eighteen minutes.',
     no:'Hell røren i brettet i et lag på omtrent to centimeter, sett det i dampkokeren og legg på lokk. Damp i femten til atten minutter.'},
    {en:'Test it with a skewer in the middle. It should come out clean and the surface should spring back when pressed. Take the tray out and let it stand for ten minutes before cutting.',
     no:'Stikk et grillspyd ned i midten for å prøve. Den skal komme ren opp, og overflaten skal sprette tilbake når du trykker på den. Ta ut brettet og la det stå i ti minutter før du skjærer.'},
    {en:'Cut it into squares while it is still in the tray, so the pieces stay in place and soak up what comes next.',
     no:'Skjær den i firkanter mens den fortsatt står i brettet, så bitene blir liggende og suger til seg det som kommer.'},
    {en:'Dissolve the sugar in the water and set it aside. Heat the oil in a small pan, add the mustard seed and wait until it pops, then the sesame, then the curry leaves and the slit chillies.',
     no:'Løs opp sukkeret i vannet og sett det til side. Varm oljen i en liten panne, ha i sennepsfrøene og vent til de spretter, så sesamen, og så karribladene og de snittede chiliene.'},
    {en:'Pour the sugared water into the hot tempering. It will spit hard, so stand back. Bring it to the boil for a few seconds and then pour the whole thing evenly over the cut dhokla.',
     no:'Hell sukkervannet i den varme temperingen. Det spruter kraftig, så stå litt tilbake. La det koke opp i noen sekunder, og hell så hele blandingen jevnt over den oppskårne dhoklaen.'},
    {en:'Scatter the coconut and the chopped coriander over, leave it for a quarter of an hour so the liquid is taken up, and serve at room temperature.',
     no:'Strø kokosen og den hakkede korianderen over, la det stå et kvarter så væsken trekker inn, og server ved romtemperatur.'}],
  notes:[
    {title:{en:'Why the fenugreek seed is in there', no:'Hvorfor bukkehornkløverfrøene er med'},
     body:{en:'Four seeds of fenugreek do nothing you can taste. What they do is carry the bacteria that start the fermentation, which is why south Indian dosa batter contains them too. In a cold kitchen they make the difference between a batter that rises overnight and one that just sits there.',
           no:'Noen få frø bukkehornkløver gir ingen smak du merker. De bærer med seg bakteriene som setter gjæringen i gang, og derfor har sørindisk dosarøre dem også. På et kaldt kjøkken avgjør de om røren hever seg over natten eller bare blir stående.'}},
    {title:{en:'Why the sugared water goes over at the end', no:'Hvorfor sukkervannet helles over til slutt'},
     body:{en:'Steamed batter dries from the cut surface inwards, and the hot sweetened water soaks back in and stops that. It also balances the sourness the fermentation produced, which is the same three-way argument the whole region makes with jaggery.',
           no:'Dampet røre tørker innover fra snittflaten, og det varme sukkervannet trekker inn igjen og stopper det. Det balanserer dessuten syren gjæringen har laget, og det er den samme trekanten hele regionen bygger på når den har jaggery i dalen.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Use a short-grain rice rather than basmati; the batter needs starch and basmati has the wrong kind.',
           no:'Bruk en kortkornet ris og ikke basmati, for røren trenger stivelse, og basmati har feil sort. Chana dal selges i indiske butikker på Grønland i Oslo og er ikke det samme som gule erter, som ikke gjærer likt. Karriblad kommer inn i bølger, så kjøp mye og legg dem i fryseren; tørkede duger ikke. Fersk kokos finnes frossen og revet i de samme butikkene, og det er langt bedre enn kokosmel fra bakehylla.'}}],
  variations:[
    {title:{en:'Khaman, the twenty-minute version', no:'Khaman, utgaven på tjue minutter'},
     body:{en:'Replace the rice and dal with the same total weight of gram flour whisked into warm water with the ginger, chilli, turmeric, sugar and a little lemon juice. Stir in a level teaspoon of eno or bicarbonate at the last second and steam at once. It is yellower, softer and sweeter, and it is a different dish honestly named.',
           no:'Bytt ut ris og dal med den samme vekten kikertmel, pisket ut i lunkent vann sammen med ingefær, chili, gurkemeie, sukker og litt sitronsaft. Rør inn en strøken skje eno eller natron i siste sekund og damp med én gang. Den blir gulere, mykere og søtere, og den er en annen rett som fortjener sitt eget navn.'}},
    {title:{en:'Green, with coriander and spinach', no:'Grønn, med koriander og spinat'},
     body:{en:'Blend a large handful of coriander and a few spinach leaves into the batter just before steaming. The colour is startling and the taste barely changes, which is a fair description of most green food.',
           no:'Kjør en stor neve koriander og noen spinatblader inn i røren rett før dampingen. Fargen er oppsiktsvekkende, mens smaken knapt endrer seg, og det er en rimelig beskrivelse av det meste som er grønt.'}},
    {title:{en:'Cut thicker, for a meal', no:'Skåret tykkere, som måltid'},
     body:{en:'Steam the batter twice as deep and give it about ten minutes longer. The crumb is denser and closer to a savoury cake, and with a chutney and a cup of tea it stops being a snack.',
           no:'Damp røren dobbelt så tykk og gi den omtrent ti minutter til. Krummen blir tettere og nærmer seg en salt kake, og sammen med en chutney og en kopp te er den ikke lenger småmat.'}}]
},

{
  id:'gujarati-kadhi', dish:'Gujarati kadhi', course:'side', lesson:2, serves:4, veg:true,
  time:{prep:10, cook:20}, hero:'kadhi', tags:['yoghurt','everyday','thali'],
  title:{en:'Gujarati kadhi', no:'Gujaratisk kadhi'},
  blurb:{en:'Thin buttermilk thickened with gram flour, sweetened with jaggery and poured over rice.',
         no:'Tynn kjernemelk jevnet med kikertmel, søtet med jaggery og helt over ris.'},
  heroCaption:{en:'The tempering floats on top and is stirred in at the table. The kadhi should be pourable, not spoonable.',
               no:'Temperingen flyter på toppen og røres inn ved bordet. Kadhien skal kunne helles, ikke øses.'},
  goesWith:[{en:'Plain rice, with the kadhi poured over it', no:'Vanlig ris med kadhien helt over'},
            {en:'Khichdi, which is what most Gujarati households eat it with', no:'Khichdi, som er det de fleste gujaratiske hjem spiser den til'}],
  headnote:{
    en:`<p>Kadhi is on every thali in Gujarat and it is the least understood thing on it. People who have met the Punjabi version expect something thick with fried dumplings in it. This one is thin enough to pour, pale yellow, and sweetened, and it is not a soup. It is a liquid for the rice.</p>
<p>It also does a job at the table that nothing else on the tray does. It cuts the fried farsan, it cools the chilli, and it clears the mouth between one vegetable and the next. A Gujarati meal without kadhi feels heavier than it should, and that is the whole argument for making it.</p>
<p>There is exactly one technique to learn, and it is the same one that matters in any dish where yoghurt meets heat. Yoghurt splits the instant it hits a hot pan. Whisk it cold with the gram flour, bring it up slowly, and keep stirring in one direction until it simmers. After that it is stable and you can leave it alone.</p>`,
    no:`<p>Kadhi står på hver eneste thali i Gujarat, og den er det folk forstår minst av alt som står der. Folk som har møtt den punjabske utgaven, venter seg noe tykt med friterte boller i. Denne er tynn nok til å helles, lysegul og søtet, og den er ingen suppe. Den er væske til risen.</p>
<p>Den gjør dessuten en jobb ved bordet som ingenting annet på brettet gjør. Den skjærer gjennom den friterte farsanen, den kjøler chilien, og den renser munnen mellom én grønnsak og den neste. Et gujaratisk måltid uten kadhi kjennes tyngre enn det burde, og det er hele grunnen til å lage den.</p>
<p>Det er nøyaktig én teknikk å lære, og det er den samme som gjelder i enhver rett der yoghurt møter varme. Yoghurt skiller seg i det øyeblikket den treffer en varm panne. Pisk den kald sammen med kikertmelet, varm den langsomt opp, og rør i én retning til den småkoker. Etter det er den stabil, og du kan la den være i fred.</p>`},
  ingredients:[
   {group:{en:'The base', no:'Bunnen'}, items:[
    {q:400, u:'g', n:{en:'natural yoghurt', no:'naturell yoghurt'}, note:{en:'as sour as you can find, whisked smooth', no:'så sur som du får tak i, pisket glatt'}},
    {q:700, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:30, u:'g', n:{en:'gram flour', no:'kikertmel'}},
    {q:25, u:'g', n:{en:'jaggery', no:'jaggery'}, note:{en:'grated', no:'revet'}},
    {q:15, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste with the chillies', no:'malt til en pasta sammen med chiliene'}},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The vaghar', no:'Vaghar'}, items:[
    {q:25, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:5, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:5, u:'g', n:{en:'cumin seed', no:'hele spisskummen'}},
    {q:3, u:'', n:{en:'cloves', no:'hele nellik'}, round:'half'},
    {q:1, u:'', n:{en:'small piece of cinnamon bark', no:'liten bit kanelbark'}, round:'half'},
    {q:2, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
    {u:'', n:{en:'asafoetida, a pinch', no:'asafoetida, en klype'}, scale:'none'},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
   ]}],
  steps:[
    {en:'Whisk the yoghurt and the gram flour together in a bowl until there is no lump left at all. Do this while everything is cold.',
     no:'Pisk yoghurten og kikertmelet sammen i en bolle til det ikke er én klump igjen. Gjør det mens alt er kaldt.'},
    {en:'Whisk in the water a little at a time, then the ginger and chilli paste, the grated jaggery and the salt.',
     no:'Pisk inn vannet litt om gangen, og så pastaen av ingefær og chili, den revne jaggeryen og saltet.'},
    {en:'Pour it into a heavy pan and set it over a low flame. Stir steadily in one direction and do not walk away.',
     no:'Hell blandingen i en tung kjele og sett den på lav varme. Rør jevnt i én retning, og gå ikke fra den.'},
    {en:'Keep stirring until it comes up to a simmer, which takes eight to ten minutes. Once it has simmered it will not split, and you can stop stirring.',
     no:'Fortsett å røre til den så vidt småkoker, noe som tar åtte til ti minutter. Når den først har småkokt, skiller den seg ikke, og du kan slutte å røre.'},
    {en:'Let it simmer gently for another ten minutes, until the raw taste of the gram flour has gone and it has thickened just enough to coat a spoon thinly.',
     no:'La den småkoke forsiktig i ti minutter til, til den rå smaken av kikertmel er borte og den er akkurat tykk nok til å legge seg tynt på en skje.'},
    {en:'Taste it now. It should read sweet, then sour, then a little hot, in that order. Adjust with jaggery or salt, not with more chilli.',
     no:'Smak nå. Den skal kjennes søt, så sur, så litt sterk, i den rekkefølgen. Juster med jaggery eller salt, ikke med mer chili.'},
    {en:'Heat the ghee in a small pan. Add the mustard seed, and when it pops add the cumin, the cloves, the cinnamon and the dried chillies.',
     no:'Varm gheen i en liten panne. Ha i sennepsfrøene, og når de spretter, har du i spisskummen, nellik, kanel og de tørkede chiliene.'},
    {en:'Throw in the curry leaves and the asafoetida, count to three, and pour the whole tempering into the kadhi.',
     no:'Slipp i karribladene og asafoetidaen, tell til tre, og hell hele temperingen ned i kadhien.'},
    {en:'Scatter the chopped coriander over and take the pan off the heat. Serve it warm, not hot, over rice.',
     no:'Strø den hakkede korianderen over og ta kjelen av platen. Server den lun, ikke rykende varm, over ris.'}],
  notes:[
    {title:{en:'Why you stir in one direction', no:'Hvorfor du rører i én retning'},
     body:{en:'The gram flour is doing two jobs: it thickens, and its starch protects the milk proteins from clumping as they heat. Steady stirring keeps the mixture moving past the hot base so no part of it gets far ahead of the rest. Changing direction is not a superstition so much as an easy way to remember to keep going.',
           no:'Kikertmelet gjør to ting: det jevner, og stivelsen beskytter melkeproteinene mot å klumpe seg mens de varmes. Jevn røring holder blandingen i bevegelse forbi den varme bunnen, så ingen del av den løper fra resten. Regelen om én retning er ikke overtro. Den er en enkel måte å huske på at du må fortsette å røre.'}},
    {title:{en:'Why it is served warm rather than hot', no:'Hvorfor den serveres lun og ikke rykende varm'},
     body:{en:'Sweetness reads much stronger when a dish is hot, and this one is balanced on the line between sweet and sour. Let it cool for a few minutes before it goes to the table and the two sit level, which is how it is meant to taste.',
           no:'Sødme kjennes mye kraftigere når en rett er svært varm, og denne balanserer på grensen mellom søtt og surt. La den kjøle seg ned noen minutter før den går på bordet, så ligger de to på linje, og det er slik den skal smake.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Sour yoghurt is what this needs, so leave a tub out of the fridge overnight if it is fresh.',
           no:'Retten trenger sur yoghurt, så la et beger stå ute på benken over natten hvis det er ferskt. Norsk naturell yoghurt er tykkere og mildere enn indisk dahi, og kulturmelk eller kefir gir faktisk en riktigere syre. Ekte jaggery selges i indiske butikker og er hardt som stein, så riv det på et grovt rivjern; mørk muscovado er den nærmeste erstatningen i dagligvarebutikken. Kikertmel fra helsekostbutikken er malt av hele kikerter og jevner litt annerledes enn indisk besan, men det fungerer her.'}}],
  variations:[
    {title:{en:'With gota, the soft dumplings', no:'Med gota, de myke bollene'},
     body:{en:'Beat a little gram flour with water and salt into a thick drop batter, and slide small spoonfuls into the simmering kadhi. They swell and go soft rather than crisp, which is the Gujarati answer to the Punjabi fried pakora.',
           no:'Pisk litt kikertmel ut i vann og salt til en tykk røre, og slipp små skjeer av den ned i den småkokende kadhien. De sveller og blir myke i stedet for sprø, og det er det gujaratiske svaret på den punjabske friterte pakoraen.'}},
    {title:{en:'Without jaggery, the Kathiawadi way', no:'Uten jaggery, på kathiawadisk vis'},
     body:{en:'West of Rajkot the kadhi is left unsweetened and gets more chilli and more garlic instead. It is a leaner, sharper dish, and it tells you as much about the geography of the state as a map does.',
           no:'Vest for Rajkot lages kadhien uten sukker og får mer chili og mer hvitløk i stedet. Den blir magrere og skarpere, og den forteller like mye om geografien i delstaten som et kart gjør.'}}]
},

{
  id:'thepla', dish:'Thepla', course:'bread', lesson:2, serves:4, veg:true,
  time:{prep:25, cook:25}, hero:'thepla', tags:['bread','fenugreek','travel'],
  title:{en:'Thepla, the bread that travels', no:'Thepla, brødet som reiser'},
  blurb:{en:'Soft fenugreek flatbreads that keep for days, which is why a Gujarati family carries them on every journey.',
         no:'Myke flatbrød med bukkehornkløver som holder seg i dagevis, og derfor har en gujaratisk familie dem med på hver reise.'},
  heroCaption:{en:'Thepla with yoghurt and a chilli pickle. The green flecks are fenugreek leaf, and there should be enough of them to see from across the table.',
               no:'Thepla med yoghurt og en chilipickles. De grønne prikkene er bukkehornkløver, og det skal være nok av dem til at du ser dem tvers over bordet.'},
  goesWith:[{en:'Thick yoghurt and a sharp mango pickle', no:'Tykk yoghurt og en skarp pickles av mango'},
            {en:'Nothing at all, eaten cold on a train', no:'Ingenting, spist kald på et tog'}],
  headnote:{
    en:`<p>A thepla is a wheat flatbread with gram flour, yoghurt, oil and chopped fenugreek leaf worked into the dough. Its compact shape and relatively dry surface make it convenient travel food. Let it cool before packing, and refrigerate it for storage beyond the day of cooking.</p>
<p>That one property has carried it further than any other Gujarati food. Gujaratis have been emigrating in large numbers since the nineteenth century, and a tin of thepla goes on the train, onto the plane and into the first week in a new country. It is the reason this recipe belongs in a course rather than in a list of breads.</p>
<p>The dough wants to be softer than a chapati dough and it wants a rest. Fenugreek leaf draws water out as it sits, so a dough that felt right when you mixed it will feel slack twenty minutes later, and that is expected.</p>`,
    no:`<p>En thepla er et hvetebrød med kikertmel, yoghurt, olje og hakket bukkehornkløver eltet inn i deigen. Den kompakte formen og den forholdsvis tørre overflaten gjør brødet praktisk på reise. Avkjøl det før pakking, og oppbevar det i kjøleskap utover samme dag.</p>
<p>Den ene egenskapen har båret den lenger enn noen annen gujaratisk mat. Gujaratier har reist ut i store tall siden 1800-tallet, og en boks thepla blir med på toget, om bord i flyet og inn i den første uka i et nytt land. Derfor hører denne oppskriften hjemme i et kurs og ikke i en liste over brød.</p>
<p>Deigen skal være mykere enn en chapatideig, og den vil ha hvile. Bladene av bukkehornkløver trekker vann ut mens den står, så en deig som kjentes riktig da du eltet den, kjennes slapp tjue minutter senere, og det skal den.</p>`},
  ingredients:[
   {group:{en:'The dough', no:'Deigen'}, items:[
    {q:250, u:'g', n:{en:'wholemeal wheat flour', no:'sammalt hvetemel'}, note:{en:'chapati atta if you have it', no:'chapati atta hvis du har det'}},
    {q:50, u:'g', n:{en:'gram flour', no:'kikertmel'}},
    {q:100, u:'g', n:{en:'fresh fenugreek leaves', no:'ferske blader av bukkehornkløver'}, note:{en:'picked off the stalks and chopped fine', no:'plukket av stilkene og finhakket'}},
    {q:80, u:'g', n:{en:'natural yoghurt', no:'naturell yoghurt'}},
    {q:30, u:'ml', n:{en:'groundnut or sunflower oil', no:'jordnøttolje eller solsikkeolje'}, note:{en:'worked into the dough', no:'eltet inn i deigen'}},
    {q:15, u:'g', n:{en:'ginger and green chilli paste', no:'pasta av ingefær og grønn chili'}},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:4, u:'g', n:{en:'red chilli powder', no:'rødt chilipulver'}},
    {q:6, u:'g', n:{en:'dhana-jeera', no:'dhana-jeera'}},
    {q:10, u:'g', n:{en:'white sesame seed', no:'hvite sesamfrø'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {q:60, u:'ml', n:{en:'water', no:'vann'}, note:{en:'added a splash at a time; you may need none', no:'has i litt om gangen, og du trenger kanskje ingenting'}, scale:'sub'},
   ]},
   {group:{en:'For cooking', no:'Til stekingen'}, items:[
    {u:'', n:{en:'oil for the pan', no:'olje til pannen'}, scale:'none'},
   ]}],
  steps:[
    {en:'Mix the two flours, the sesame, the turmeric, the chilli powder, the dhana-jeera and the salt in a wide bowl.',
     no:'Bland de to meltypene, sesamen, gurkemeien, chilipulveret, dhana-jeeraen og saltet i en vid bolle.'},
    {en:'Add the chopped fenugreek, the ginger and chilli paste, the yoghurt and the oil, and rub everything together with your fingers until it looks like damp crumbs.',
     no:'Ha i den hakkede bukkehornkløveren, pastaen av ingefær og chili, yoghurten og oljen, og gni alt sammen med fingrene til det ser ut som fuktige smuler.'},
    {en:'Bring it into a dough, adding water only if it will not come together. Fenugreek carries a lot of water and you will often need none at all.',
     no:'Samle det til en deig, og ha bare i vann hvis den ikke vil samle seg. Bukkehornkløver bærer mye vann, og ofte trenger du ikke noe.'},
    {en:'Knead for five minutes until it is smooth and softer than a chapati dough. Cover it and let it rest for twenty minutes.',
     no:'Elt i fem minutter til deigen er glatt og mykere enn en chapatideig. Dekk den til og la den hvile i tjue minutter.'},
    {en:'Divide the dough into balls about the size of a walnut and keep them covered so they do not skin over.',
     no:'Del deigen i kuler på størrelse med en valnøtt, og hold dem tildekket så de ikke tørker på overflaten.'},
    {en:'Roll each ball out on a lightly floured board to about the thickness of a coin and the width of a saucer. Roll from the centre outwards and turn the disc a quarter each time so it stays round.',
     no:'Kjevle hver kule ut på et lett melet bord til omtrent tykkelsen av en mynt og bredden av en skål. Kjevle fra midten og utover, og vri på leiven en kvart omdreining hver gang, så den holder seg rund.'},
    {en:'Heat a flat pan over a medium flame until a drop of water skips on it. Lay a thepla on the dry pan.',
     no:'Varm en flat panne på middels varme til en vanndråpe danser på den. Legg en thepla i den tørre pannen.'},
    {en:'When small bubbles appear on the surface, turn it over, brush the cooked side with oil, and press the edges down with a folded cloth so it cooks evenly.',
     no:'Når det kommer små bobler på overflaten, snu den, pensle den stekte siden med olje, og trykk kantene ned med en sammenbrettet klut så den stekes jevnt.'},
    {en:'Turn it once more, oil the second side, and cook until both faces carry brown spots. Each one takes about a minute and a half in all.',
     no:'Snu den en gang til, ha olje på den andre siden, og stek til begge sider har brune flekker. Hver av dem tar omtrent halvannet minutt til sammen.'},
    {en:'Stack them in a cloth as they come off the pan, which keeps them soft. Serve them hot, or cool them completely before they go into a tin.',
     no:'Legg dem i stabel i en klut etter hvert som de blir ferdige, så holder de seg myke. Server dem varme, eller kjøl dem helt ned før de legges i en boks.'}],
  notes:[
    {title:{en:'Why they keep and a chapati does not', no:'Hvorfor de holder seg, og en chapati ikke gjør det'},
     body:{en:'Staling is starch recrystallising, and fat gets in the way of it. The oil in the dough and the oil on the surface both slow it down, and the acid in the yoghurt holds off mould for a day or two more. Cool them completely before they go in a tin, because trapped steam undoes all of it.',
           no:'At et brød blir gammelt, er stivelse som krystalliserer seg på nytt, og fett kommer i veien for det. Både oljen i deigen og oljen på overflaten bremser det, og syren i yoghurten holder mugg unna et døgn eller to lenger. Kjøl dem helt ned før de legges i en boks, for innestengt damp ødelegger hele effekten.'}},
    {title:{en:'Why the dough must be firmer than it feels right', no:'Hvorfor deigen skal være fastere enn den kjennes riktig'},
     body:{en:'Chopped fenugreek releases water for the first half hour after it is salted, so a dough mixed to the perfect consistency will be slack by the time you roll it. Mix it a shade firm, rest it, and let the leaf do the rest.',
           no:'Hakket bukkehornkløver gir fra seg vann den første halvtimen etter at den er saltet, så en deig som er eltet til perfekt konsistens, er slapp når du skal kjevle. Elt den et hakk fastere, la den hvile, og la bladene gjøre resten.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Fresh fenugreek is the one hard ingredient, and there is an honest fallback.',
           no:'Fersk bukkehornkløver er den vanskelige ingrediensen. Indiske butikker på Grønland fører den fersk i bunter og ofte frossen og hakket, og den frosne fungerer utmerket her. Finner du ingen av delene, bruk en fjerdedel så mye kasuri methi, altså tørkede blader, bløtlagt i litt vann i ti minutter; smaken blir kraftigere og mer bitter, og deigen trenger da vann. Fint sammalt hvetemel ligger nærmest chapati atta, men atta selges billig i de samme butikkene og gir mykere brød. Ferdig pasta av ingefær og chili står på glass ved siden av.'}}],
  variations:[
    {title:{en:'Bottle gourd thepla', no:'Thepla med flaskegresskar'},
     body:{en:'Grate a piece of bottle gourd, squeeze it hard and work it into the dough instead of the fenugreek. The bread is softer and milder and keeps a day less, and it is what a household makes when the fenugreek season is over.',
           no:'Riv en bit flaskegresskar, klem den godt ut og elt den inn i deigen i stedet for bukkehornkløveren. Brødet blir mykere og mildere og holder seg et døgn kortere, og det er det en husholdning lager når sesongen for bukkehornkløver er over.'}},
    {title:{en:'Methi na gota, for the same dough gone wrong', no:'Methi na gota, av den samme deigen som ble for bløt'},
     body:{en:'If the dough ends up far too wet to roll, loosen it further with water into a thick batter and fry spoonfuls of it. That is a recognised Gujarati snack in its own right, and nobody needs to know it was an accident.',
           no:'Blir deigen alt for våt til å kjevles, spe den videre med vann til en tykk røre og friter skjeer av den. Det er en anerkjent gujaratisk smårett i seg selv, og ingen trenger å vite at det begynte som et uhell.'}},
    {title:{en:'Rolled thinner, as rotli', no:'Kjevlet tynnere, som rotli'},
     body:{en:'Leave out the fenugreek, the gram flour and the yoghurt and you have rotli, the everyday bread. Roll it much thinner, cook it dry and serve it straight off the pan, because it will not wait.',
           no:'Sløyf bukkehornkløveren, kikertmelet og yoghurten, så har du rotli, hverdagsbrødet. Kjevle det mye tynnere, stek det tørt og server det rett fra pannen, for det tåler ikke å vente.'}}]
},

{
  id:'khandvi', dish:'Khandvi', course:'snack', lesson:3, serves:4, veg:true,
  time:{prep:15, cook:20}, hero:'khandvi', tags:['gram flour','difficult','farsan'],
  title:{en:'Khandvi, and the ninety seconds that decide it', no:'Khandvi, og de nitti sekundene som avgjør'},
  blurb:{en:'Gram flour cooked in buttermilk to a precise set, spread paper-thin, rolled and tempered.',
         no:'Kikertmel kokt i kjernemelk til nøyaktig riktig konsistens, smurt tynt som papir, rullet og temperert.'},
  heroCaption:{en:'Tight, thin, slightly translucent rolls. If they tear when you lift them, the paste was cooked too long.',
               no:'Stramme, tynne og litt gjennomskinnelige ruller. Revner de når du løfter dem, har massen kokt for lenge.'},
  goesWith:[{en:'Green coriander chutney, and not much else', no:'Grønn korianderchutney, og ikke stort mer'},
            {en:'Tea, in the middle of the afternoon', no:'Te, midt på ettermiddagen'}],
  headnote:{
    en:`<p>Be warned before you start. Khandvi fails more often than any other dish in this module, and it fails in two specific ways that are worth naming in advance, because both are recoverable if you spot them and neither is if you do not.</p>
<p>Gram flour is whisked into buttermilk and cooked, stirring without stopping, until it thickens. Undercook it and it never sets, so it slides off the tray in a sheet of paste and the only thing to do is scrape it back into the pan and keep going. Overcook it and it sets before you have finished spreading it, so it tears into flakes instead of peeling away whole, and there is no way back from that one.</p>
<p>Between those two states there is a window of about ninety seconds, and everything you need for the spreading has to be oiled, laid out and within reach before you start. A cook who is looking for a palette knife at that moment has already lost. Read the whole recipe, set the kitchen up, and then light the flame.</p>`,
    no:`<p>En advarsel før du begynner. Khandvi mislykkes oftere enn noe annet i denne modulen, og den mislykkes på to bestemte måter som er verdt å navngi på forhånd, for begge lar seg redde hvis du oppdager dem, og ingen av dem hvis du ikke gjør det.</p>
<p>Kikertmel piskes ut i kjernemelk og kokes under stadig røring til det tykner. Koker du det for kort, stivner det aldri, og da sklir det av brettet som et lag masse, og det eneste du kan gjøre, er å skrape det tilbake i pannen og koke videre. Koker du det for lenge, stivner det før du er ferdig med å smøre det ut, og da revner det i flak i stedet for å løsne helt, og derfra finnes det ingen vei tilbake.</p>
<p>Mellom de to tilstandene ligger et vindu på omtrent nitti sekunder, og alt du trenger til utsmøringen, må være oljet, lagt fram og innen rekkevidde før du begynner. Den som leter etter en palettkniv i det øyeblikket, har alt tapt. Les hele oppskriften, gjør kjøkkenet klart, og tenn så på plata.</p>`},
  ingredients:[
   {group:{en:'The paste', no:'Massen'}, items:[
    {q:100, u:'g', n:{en:'gram flour', no:'kikertmel'}, note:{en:'sifted', no:'siktet'}},
    {q:300, u:'ml', n:{en:'buttermilk', no:'kjernemelk'}, note:{en:'sour, and at room temperature', no:'sur, og i romtemperatur'}},
    {q:100, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15, u:'g', n:{en:'ginger and green chilli paste', no:'pasta av ingefær og grønn chili'}},
    {q:2, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {u:'', n:{en:'asafoetida, a pinch', no:'asafoetida, en klype'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'oil for the trays', no:'olje til brettene'}, scale:'none'},
   ]},
   {group:{en:'The tempering', no:'Temperingen'}, items:[
    {q:30, u:'ml', n:{en:'groundnut or sunflower oil', no:'jordnøttolje eller solsikkeolje'}},
    {q:6, u:'g', n:{en:'black mustard seed', no:'svarte sennepsfrø'}},
    {q:10, u:'g', n:{en:'white sesame seed', no:'hvite sesamfrø'}},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblad'}, round:'half'},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'snittet på langs'}},
    {q:25, u:'g', n:{en:'grated fresh coconut', no:'revet fersk kokos'}},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
   ]}],
  steps:[
    {en:'Set the kitchen up first. Oil the backs of two large trays or a clean worktop, lay out a palette knife or a wide spatula, and keep a cold plate beside the stove for testing.',
     no:'Gjør kjøkkenet klart først. Smør baksiden av to store brett eller en ren benkeplate med olje, legg fram en palettkniv eller en bred stekespade, og ha en kald tallerken ved siden av platen til prøven.'},
    {en:'Whisk the gram flour into the buttermilk and the water in a bowl until there is no lump at all. Pass it through a sieve if you are not certain, because one lump ruins a sheet.',
     no:'Pisk kikertmelet ut i kjernemelken og vannet i en bolle til det ikke er én klump igjen. Sil det hvis du er i tvil, for én klump ødelegger et helt ark.'},
    {en:'Stir in the turmeric, the ginger and chilli paste, the asafoetida and the salt.',
     no:'Rør inn gurkemeien, pastaen av ingefær og chili, asafoetidaen og saltet.'},
    {en:'Pour it into a wide heavy pan over a medium flame and stir without stopping, scraping the base and the corners with a flat spoon.',
     no:'Hell blandingen i en vid, tung panne på middels varme og rør uten å stoppe, og skrap bunnen og hjørnene med en flat sleiv.'},
    {en:'For five or six minutes nothing much happens. Then it thickens quickly and starts to pull away from the base of the pan in one mass. Keep stirring through that.',
     no:'I fem–seks minutter skjer det lite. Så tykner den raskt og begynner å slippe bunnen av pannen som én masse. Fortsett å røre gjennom det.'},
    {en:'Test it now. Smear a thin line onto the cold plate, count to sixty, and try to lift an edge. It should peel off in one piece. If it will not, cook for another minute and test again.',
     no:'Ta prøven nå. Smør en tynn stripe på den kalde tallerkenen, tell til seksti, og prøv å løfte en kant. Den skal løsne i ett stykke. Gjør den ikke det, kok et minutt til og prøv på nytt.'},
    {en:'The moment it passes the test, take the pan off the heat and work fast. Pour a ladle of the paste onto an oiled tray and spread it as thin as you can with long strokes of the palette knife.',
     no:'I det øyeblikket den består prøven, tar du pannen av platen og jobber raskt. Hell en sleiv av massen på et oljet brett og smør den så tynn du klarer med lange drag av palettkniven.'},
    {en:'Keep going until all the paste is spread. Work in long strips rather than trying to cover the whole tray evenly, because strips are what you are going to cut anyway.',
     no:'Hold på til all massen er smurt ut. Jobb i lange striper i stedet for å prøve å dekke hele brettet jevnt, for striper er det du skal skjære uansett.'},
    {en:'Let it cool for two or three minutes, until it is set and no longer warm to the back of a finger.',
     no:'La det kjøle seg ned i to–tre minutter, til det har stivnet og ikke lenger kjennes varmt mot baksiden av en finger.'},
    {en:'Cut the sheet lengthways into strips about four centimetres wide, then roll each strip up from one end, firmly but without squeezing. Lay the rolls seam down on a plate.',
     no:'Skjær arket på langs i striper på omtrent fire centimeter, og rull hver stripe opp fra den ene enden, stramt, men uten å klemme. Legg rullene med skjøten ned på et fat.'},
    {en:'Heat the oil in a small pan, add the mustard seed and wait for it to pop, then the sesame, then the curry leaves and the slit chillies. Pour the whole thing over the rolls.',
     no:'Varm oljen i en liten panne, ha i sennepsfrøene og vent til de spretter, så sesamen, og så karribladene og de snittede chiliene. Hell hele blandingen over rullene.'},
    {en:'Scatter the coconut and the chopped coriander over and serve within the hour. Khandvi hardens in the fridge and does not come back.',
     no:'Strø kokosen og den hakkede korianderen over, og server innen en time. Khandvi blir hard i kjøleskapet og kommer seg ikke igjen.'}],
  notes:[
    {title:{en:'Why the liquid is sour', no:'Hvorfor væsken er syrlig'},
     body:{en:'Khandvi is built around the tang of yoghurt or buttermilk as well as gram flour. Acidity varies between products, so taste the uncooked mixture and add a little lemon only if it lacks tartness. The cold-plate test, rather than acidity alone, tells you when the paste will roll.',
           no:'Khandvi bygger på syren i yoghurt eller kjernemelk sammen med kikertmel. Syren varierer mellom produkter, så smak på den ukokte blandingen og tilsett bare litt sitron hvis den mangler friskhet. Prøven på kald tallerken, og ikke syren alene, viser når massen kan rulles.'}},
    {title:{en:'Why you spread onto something cold', no:'Hvorfor du smører ut på noe kaldt'},
     body:{en:'The sheet sets as it loses heat, and a cold steel tray takes the heat out from below in seconds. A warm tray, or a wooden board that insulates, leaves the paste soft in the middle and it will not lift cleanly. This is also why the cold plate makes an honest test.',
           no:'Arket stivner etter hvert som det mister varme, og et kaldt stålbrett trekker varmen ut nedenfra på sekunder. Et lunkent brett eller en trefjøl som isolerer, lar massen forbli myk i midten, og da løsner den ikke rent. Det er også derfor den kalde tallerkenen gir en ærlig prøve.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buttermilk and gram flour are the two things to get right, and the flour matters more than people expect.',
           no:'Kjernemelk og kikertmel er de to tingene du må få riktig, og melet betyr mer enn folk tror. Indisk besan er malt av chana dal og gir et smidigere ark enn kikertmelet fra helsekostbutikken, som er malt av hele kikerter; begge fungerer, men besan er verdt turen til Grønland. Kjernemelk finnes i alle dagligvarebutikker, og kulturmelk er surere og faktisk bedre her. Fersk kokos kjøper du frossen og revet i indiske butikker, og karriblad samme sted, gjerne til fryseren.'}}],
  variations:[
    {title:{en:'Suralichi vadi, the neighbouring version', no:'Suralichi vadi, utgaven fra nabolaget'},
     body:{en:'Maharashtra makes the same thing with more coconut and coriander spread over the sheet before it is rolled, so the roll carries a green spiral inside. It is the same technique and a slightly richer result.',
           no:'Maharashtra lager det samme, men strør mer kokos og koriander over arket før det rulles, så rullen får en grønn spiral inni. Teknikken er den samme, og resultatet blir litt fyldigere.'}},
    {title:{en:'In the microwave, which genuinely works', no:'I mikrobølgeovn, som faktisk virker'},
     body:{en:'Cook the mixture in a wide microwave bowl in bursts of two minutes, whisking hard between each one, until it passes the cold-plate test. It takes about six minutes in total and removes the risk of scorching the base, which is how a good many Gujarati households now do it.',
           no:'Kok blandingen i en vid bolle i mikrobølgeovn i omganger på to minutter, og pisk kraftig mellom hvert, til den består prøven på kald tallerken. Det tar omtrent seks minutter i alt og fjerner faren for å svi bunnen, og ganske mange gujaratiske husholdninger gjør det slik nå.'}}]
},

{
  id:'undhiyu', dish:'Undhiyu', course:'main', lesson:3, serves:6, veg:true,
  time:{prep:60, cook:60}, hero:'undhiyu', tags:['winter','vegetables','Surat'],
  title:{en:'Undhiyu, without the pit', no:'Undhiyu, uten gropa'},
  blurb:{en:'Winter roots, beans and fenugreek dumplings cooked slowly in a green masala, in a covered pot that nobody stirs.',
         no:'Rotgrønnsaker, bønner og boller med bukkehornkløver kokt langsomt i en grønn masala, i en tildekket gryte som ingen rører i.'},
  heroCaption:{en:'Muthiya dumplings among the vegetables. Everything should hold its shape, which is what not stirring buys you.',
               no:'Muthiya-boller mellom grønnsakene. Alt skal holde formen, og det er det du får igjen for å la være å røre.'},
  goesWith:[{en:'Puri, the small puffed breads', no:'Puri, de små oppblåste brødene'},
            {en:'Shrikhand afterwards, which is the traditional pairing', no:'Shrikhand etterpå, som er den tradisjonelle avslutningen'}],
  headnote:{
    en:`<p>Undhiyu is associated with winter around Surat, and its name is linked to <em>undhu</em>, upside down. The related village preparation umbhadiyu cooks seasonal vegetables in an inverted earthen pot over or under a fire. Modern undhiyu is usually cooked upright.</p>
<p>This home version uses a heavy covered pot. It keeps the layered winter vegetables, green paste and fenugreek dumplings while stirring as little as possible, so the softer vegetables retain their shape.</p>
<p>Undhiyu is a project rather than a weeknight dish. It takes an afternoon, it wants six people at the table, and it is better an hour after it is cooked than straight off the stove. Make the muthiya and the masala first, and the rest is assembly and patience.</p>`,
    no:`<p>Undhiyu forbindes med vinteren rundt Surat, og navnet knyttes til <em>undhu</em>, opp ned. Den beslektede landsbyretten umbhadiyu koker sesongens grønnsaker i en snudd leirgryte over eller under ild. Moderne undhiyu kokes som regel riktig vei.</p>
<p>Denne hjemmeutgaven bruker en tung gryte med lokk. Den beholder lagene av vintergrønnsaker, grønn masala og boller av bukkehornkløver og røres minst mulig, slik at de mykere grønnsakene holder formen.</p>
<p>Undhiyu er et prosjekt og ingen hverdagsrett. Den tar en ettermiddag, den vil ha seks personer rundt bordet, og den er bedre en time etter at den er ferdig enn rett fra platen. Lag muthiyaen og masalaen først, så er resten montering og tålmodighet.</p>`},
  ingredients:[
   {group:{en:'The muthiya', no:'Muthiyaen'}, items:[
    {q:100, u:'g', n:{en:'gram flour', no:'kikertmel'}},
    {q:50, u:'g', n:{en:'wholemeal wheat flour', no:'sammalt hvetemel'}},
    {q:80, u:'g', n:{en:'fresh fenugreek leaves', no:'ferske blader av bukkehornkløver'}, note:{en:'chopped fine', no:'finhakket'}},
    {q:5, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:4, u:'g', n:{en:'red chilli powder', no:'rødt chilipulver'}},
    {q:15, u:'ml', n:{en:'oil', no:'olje'}, note:{en:'worked into the dough', no:'eltet inn i deigen'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'oil for frying', no:'olje til fritering'}, scale:'none'},
   ]},
   {group:{en:'The green masala', no:'Den grønne masalaen'}, items:[
    {q:100, u:'g', n:{en:'grated fresh coconut', no:'revet fersk kokos'}},
    {q:80, u:'g', n:{en:'coriander leaves and stalks', no:'korianderblader og stilker'}},
    {q:5, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:25, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:15, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'left out in Jain households', no:'sløyfes i husholdninger hos jainer'}},
    {q:20, u:'g', n:{en:'white sesame seed', no:'hvite sesamfrø'}},
    {q:30, u:'g', n:{en:'peanuts', no:'jordnøtter'}, note:{en:'roasted and coarsely crushed', no:'ristede og grovt knuste'}},
    {q:15, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:10, u:'g', n:{en:'dhana-jeera', no:'dhana-jeera'}},
    {q:20, u:'ml', n:{en:'lemon juice', no:'sitronsaft'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The vegetables and the pot', no:'Grønnsakene og gryta'}, items:[
    {q:300, u:'g', n:{en:'surti papdi or other flat green beans', no:'surti papdi eller andre flate grønne bønner'}, note:{en:'strings pulled off', no:'trådene trukket av'}},
    {q:250, u:'g', n:{en:'purple yam', no:'lilla jams'}, note:{en:'peeled, in large chunks', no:'skrelt, i store biter'}},
    {q:250, u:'g', n:{en:'sweet potato', no:'søtpotet'}, note:{en:'peeled, in large chunks', no:'skrelt, i store biter'}},
    {q:300, u:'g', n:{en:'small waxy potatoes', no:'små fastkokende poteter'}, note:{en:'left whole, skin on', no:'hele, med skallet på'}},
    {q:300, u:'g', n:{en:'baby aubergines', no:'små auberginer'}, note:{en:'slit into quarters from the base, stalk left on', no:'snittet i fire fra bunnen, med stilken på'}},
    {q:200, u:'g', n:{en:'green banana', no:'grønn banan'}, note:{en:'peeled, in thick rounds', no:'skrelt, i tykke skiver'}},
    {q:100, u:'ml', n:{en:'groundnut or sunflower oil', no:'jordnøttolje eller solsikkeolje'}},
    {q:4, u:'g', n:{en:'ajwain', no:'ajwain'}},
    {u:'', n:{en:'asafoetida, a pinch', no:'asafoetida, en klype'}, scale:'none'},
    {q:200, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
   ]}],
  steps:[
    {en:'Make the muthiya first. Rub everything for them together into a stiff dough, adding a splash of water only if it will not hold. Squeeze small pieces in your fist into rough cylinders.',
     no:'Lag muthiyaen først. Gni alt til dem sammen til en fast deig, og ha bare i en skvett vann hvis den ikke vil henge sammen. Klem små biter til grove sylindre i neven.'},
    {en:'Fry them in hot oil over a medium flame until they are golden and firm, about four minutes. Lift them onto paper and set them aside.',
     no:'Friter dem i varm olje på middels varme til de er gylne og faste, omtrent fire minutter. Løft dem opp på papir og sett dem til side.'},
    {en:'Grind everything for the green masala to a coarse, damp paste. It should hold together when pressed and still show the texture of the coconut.',
     no:'Kjør alt som skal i den grønne masalaen, til en grov og fuktig masse. Den skal henge sammen når du klemmer på den, og fortsatt vise strukturen i kokosen.'},
    {en:'Stuff a good spoonful of the paste into each slit aubergine and into the slits you cut in the thickest pieces of yam. Keep the rest of the paste for layering.',
     no:'Stapp en god skje av massen inn i hver av de oppsnittede auberginene og inn i snittene du skjærer i de tykkeste bitene av jams. Ta vare på resten til lagene.'},
    {en:'Heat the oil in a wide heavy pot with a tight lid. Add the ajwain and the asafoetida and wait a few seconds for them to smell.',
     no:'Varm oljen i en vid, tung gryte med tett lokk. Ha i ajwain og asafoetida, og vent noen sekunder til det dufter.'},
    {en:'Put the beans in first as a layer on the base, then the potatoes, the yam and the sweet potato, spooning some of the green masala between each layer.',
     no:'Legg bønnene først som et lag i bunnen, så potetene, jamsen og søtpoteten, og ha noe av den grønne masalaen mellom hvert lag.'},
    {en:'Lay the green banana and the stuffed aubergines on top, spoon the last of the masala over, and pour the water down the side of the pot rather than over the vegetables.',
     no:'Legg den grønne bananen og de fylte auberginene øverst, ha resten av masalaen over, og hell vannet ned langs siden av gryta i stedet for over grønnsakene.'},
    {en:'Cover tightly, bring it up to a simmer over a medium flame, then turn the heat as low as it will go. Cook for forty minutes without lifting the lid.',
     no:'Legg på tett lokk, la det komme til småkoking på middels varme, og skru så platen så lavt den går. La det stå i førti minutter uten å løfte lokket.'},
    {en:'Do not stir at any point. If you think it is catching, take the pot off the heat for a minute and shake it flat rather than putting a spoon in.',
     no:'Ikke rør på noe tidspunkt. Tror du det setter seg fast, ta gryta av platen et minutt og rist den flat i stedet for å sette en skje ned i den.'},
    {en:'Lift the lid, tuck the fried muthiya down among the vegetables, cover again and give it ten more minutes.',
     no:'Løft lokket, stikk de friterte muthiyaene ned mellom grønnsakene, legg på lokket igjen og gi det ti minutter til.'},
    {en:'Take it off the heat and leave it covered for half an hour before serving. Cool any leftovers promptly, refrigerate them within two hours and reheat thoroughly the next day.',
     no:'Ta den av platen og la den stå under lokk i en halvtime før servering. Kjøl rester raskt, sett dem i kjøleskap innen to timer og varm dem grundig opp neste dag.'}],
  notes:[
    {title:{en:'Why nothing is stirred', no:'Hvorfor ingenting røres'},
     body:{en:'Vegetables of different densities share one pot, and vigorous stirring can turn the soft ones to purée while the yam is still firm. Layering puts slower-cooking pieces nearer the heat; a tight lid and gentle handling help each piece remain whole.',
           no:'Grønnsaker med ulik fasthet deler gryte, og kraftig røring kan gjøre de myke til puré mens jamsen fortsatt er fast. Lagdelingen legger det som trenger lengst tid, nærmest varmen; et tett lokk og varsom behandling hjelper bitene å holde formen.'}},
    {title:{en:'Why the muthiya go in late', no:'Hvorfor muthiyaene går i sent'},
     body:{en:'They are fried so that the outside firms up, and then they spend ten minutes taking up liquid from the pot. Put them in at the start and they dissolve into the gravy and thicken it, which some households actually want. Ten minutes gives you dumplings you can still pick up.',
           no:'De friteres for at overflaten skal stivne, og så bruker de ti minutter på å suge til seg væske fra gryta. Har du dem i fra starten, løser de seg opp i sausen og jevner den, og noen husholdninger vil faktisk ha det slik. Ti minutter gir deg boller du fortsatt kan plukke opp.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'The bean is the hard part, and the honest answer is that the season is short even in Gujarat.',
           no:'Bønnen er det vanskelige, og det ærlige svaret er at sesongen er kort selv i Gujarat. Surti papdi selges frossen som papdi eller valor i indiske butikker på Grønland, og frossen er helt greit her. Finner du den ikke, bruk brede bønner eller friske bondebønner; smaken blir mildere, men strukturen stemmer. Lilla jams selges som kand eller purple yam i indiske og afrikanske butikker, og bytter du den mot mer søtpotet, blir retten søtere enn den skal være. Små auberginer får du de samme stedene; de store norske faller fra hverandre. Blader av bukkehornkløver finnes ferske eller frosne, og kokebanan står i samme hylle.'}}],
  variations:[
    {title:{en:'Umbhadiyu, the related village method', no:'Umbhadiyu, den beslektede landsbymetoden'},
     body:{en:'Umbhadiyu uses seasonal vegetables and an earthen vessel cooked with fire, often inverted. Ingredients and fire arrangements vary locally. Treat it as a related regional preparation rather than a single original recipe for every modern undhiyu.',
           no:'Umbhadiyu bruker sesongens grønnsaker og en leirgryte som varmes med ild, ofte snudd. Ingredienser og plassering av ilden varierer lokalt. Se den som en beslektet regional rett, ikke som én originaloppskrift bak all moderne undhiyu.'}},
    {title:{en:'In the oven', no:'I stekeovnen'},
     body:{en:'Layer everything into a heavy casserole, cover it with a lid and a sheet of foil, and cook at 160 °C for an hour and a quarter. The heat comes from every side instead of the base, which is nearer to what the pit did, and nothing can catch.',
           no:'Legg alt lagvis i en tung, ildfast gryte, dekk den med et ark folie og lokk, og la den stå på 160 °C i en time og et kvarter. Varmen kommer fra alle kanter i stedet for fra bunnen, slik den gjorde i gropa, og ingenting kan svi seg.'}}]
},

];
