/* Masala Dabba — recipes for Kashmir & the Himalaya (IN-HIM). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-HIM'] = [

{
  id:'rogan-josh', dish:'Rogan josh', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:25, cook:110}, hero:'rogan-josh', tags:['goat','chilli','slow'],
  title:{en:'Rogan josh', no:'Rogan josh'},
  blurb:{en:'Goat cooked hard in fat with a mild red chilli, finished with yoghurt. Rich, aromatic and not hot.',
         no:'Geitekjøtt kokt hardt i fett med en mild rød chili, avsluttet med yoghurt. Fyldig, aromatisk og ikke sterk.'},
  heroCaption:{en:'The red film on top is fat that has separated and been coloured. It is a sign the dish is finished, not a warning.',
               no:'Den røde hinnen på toppen er fett som har skilt seg ut og blitt farget. Den er et tegn på at retten er ferdig, ikke en advarsel.'},
  goesWith:[{en:'Plain short-grained rice, and plenty of it', no:'Vanlig kortkornet ris, og rikelig med den'},
            {en:'Haak, boiled greens, in a bowl beside it', no:'Haak, kokte grønne blader, i en skål ved siden av'}],
  headnote:{
    en:`<p>The name has more than one proposed origin. A common explanation links Persian <em>roghan</em>, oil or clarified butter, with <em>josh</em>, boiling or stewing. Other explanations connect Kashmiri words for red with meat or juice. The etymology is disputed, and none of these readings makes a deep-red rogan josh automatically fierce with chilli.</p>
<p>The red is made on purpose and in two stages. Kashmiri chilli brings deep colour with comparatively mild heat, though batches vary. Ratan jot, a dried alkanet root, is steeped in the hot oil at the start and releases a fat-soluble red that rises to the surface. It is used chiefly for colour and may contribute a subtle aroma.</p>
<p>This is the Muslim kitchen's version, built on shallots browned dark and ground back into the pot. The Kashmiri Pandit version of the same dish uses no onion or garlic whatever, and it is written out as the first variation below. Both are authentic; they belong to different houses in the same city.</p>`,
    no:`<p>Navnet har flere foreslåtte opphav. En vanlig forklaring knytter persisk <em>roghan</em>, olje eller klaret smør, til <em>josh</em>, koking eller trekking. Andre forklaringer forbinder kashmirske ord for rødt med kjøtt eller saft. Etymologien er omstridt, og ingen av forklaringene gjør en dyprød rogan josh automatisk svært chilisterk.</p>
<p>Den røde fargen lages med vilje og i to omganger. Kashmiri-chili gir dyp farge og forholdsvis mild styrke, men partiene varierer. Ratan jot, en tørket alkannarot, trekkes i den varme oljen i starten og gir fra seg en fettløselig rødfarge som stiger til overflaten. Den brukes først og fremst for fargen og kan gi en svak aroma.</p>
<p>Dette er det muslimske kjøkkenets utgave, bygd på sjalottløk som brunes mørk og males tilbake i gryta. Pandit-utgaven av den samme retten bruker verken løk eller hvitløk, og den står som den første varianten nedenfor. Begge er ekte, og de hører til i hvert sitt hus i den samme byen.</p>`},
  ingredients:[
   {group:{en:'The pot', no:'Gryta'}, items:[
    {q:1, u:'kg', n:{en:'goat or mutton on the bone', no:'geitekjøtt eller fårekjøtt med bein'}, note:{en:'shoulder, neck and ribs, in large pieces', no:'bog, nakke og ribbe, i store biter'}},
    {q:120, u:'g', n:{en:'shallots', no:'sjalottløk'}, note:{en:'sliced fine', no:'finskåret'}},
    {q:20, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:20, u:'g', n:{en:'ginger', no:'ingefær'}, note:{en:'ground to a paste', no:'malt til pasta'}},
    {q:100, u:'ml', n:{en:'mustard oil', no:'sennepsolje'}},
    {q:40, u:'g', n:{en:'ghee', no:'ghee'}, note:{en:'to finish', no:'til slutt'}},
    {q:2, u:'g', n:{en:'ratan jot', no:'ratan jot'}, note:{en:'optional, for colour only', no:'valgfritt, bare for fargen'}},
   ]},
   {group:{en:'The seasoning', no:'Krydderet'}, items:[
    {q:250, u:'g', n:{en:'natural yoghurt', no:'naturell yoghurt'}, note:{en:'full fat, whisked smooth', no:'med høyt fettinnhold, pisket glatt'}},
    {q:15, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri-chilipulver'}},
    {q:8, u:'g', n:{en:'ground fennel', no:'malt fennikel'}},
    {q:4, u:'g', n:{en:'ground dry ginger', no:'malt tørket ingefær'}},
    {q:4, u:'', n:{en:'green cardamom pods', no:'grønne kardemommekapsler'}, round:'half', note:{en:'bruised', no:'lett knust'}},
    {q:2, u:'', n:{en:'black cardamom pods', no:'sorte kardemommekapsler'}, round:'half'},
    {q:4, u:'', n:{en:'cloves', no:'hele nellik'}, round:'half'},
    {q:1, u:'', n:{en:'piece of cinnamon bark', no:'bit kanelbark'}, round:'half'},
    {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
    {q:500, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Rub the meat with salt and leave it out of the fridge for half an hour, so it is not cold when it hits the pan.',
     no:'Gni kjøttet inn med salt og la det stå utenfor kjøleskapet i en halvtime, så det ikke er kaldt når det treffer gryta.'},
    {en:'Heat the mustard oil in a heavy pan until it just smokes, then pull it off the heat for a minute so it cools a little.',
     no:'Varm sennepsoljen i en tung gryte til den så vidt ryker, og trekk den så av platen et minutt så den kjøles litt ned.'},
    {en:'If you are using ratan jot, tie it in a scrap of muslin, hold it in the warm oil until the oil turns red, then lift it out and throw it away.',
     no:'Bruker du ratan jot, bind den inn i en bit tøy, hold den i den varme oljen til oljen blir rød, løft den så ut og kast den.'},
    {en:'Fry the shallots in the same oil over a medium flame until they are properly dark brown, which takes a good quarter of an hour. Lift them out and grind them to a paste with a splash of water.',
     no:'Stek sjalottløken i den samme oljen på middels varme til den er skikkelig mørkebrun, og det tar et godt kvarter. Løft den ut og mal den til pasta med en skvett vann.'},
    {en:'Brown the meat in the same pan in two or three batches over a high flame, until every piece has colour. A crowded pan steams the meat instead.',
     no:'Brun kjøttet i den samme gryta i to eller tre omganger på høy varme, til hver bit har fått farge. En full gryte damper kjøttet i stedet.'},
    {en:'Return all the meat, add the whole spices and the ginger and garlic pastes, and cook for two minutes until the raw smell goes.',
     no:'Ha alt kjøttet tilbake, tilsett de hele krydderne og pastaen av ingefær og hvitløk, og la det surre i to minutter til den rå lukten er borte.'},
    {en:'Take the pan off the heat, stir in the chilli powder, the fennel and the dry ginger, and put it back on a low flame. Ground spice burns in hot fat in seconds.',
     no:'Ta gryta av platen, rør inn chilipulveret, fennikelen og den tørkede ingefæren, og sett den tilbake på lav varme. Malt krydder svir seg i varmt fett på sekunder.'},
    {en:'Whisk the yoghurt until it is completely smooth, pour it in while the pan is barely simmering, and stir in one direction without stopping until it comes back to a simmer. It will split if you walk away.',
     no:'Pisk yoghurten helt glatt, hell den i mens gryta så vidt småkoker, og rør én vei uten stans til det koker opp igjen. Sausen skiller seg hvis du går fra den.'},
    {en:'Stir in the shallot paste and the hot water, salt it, cover, and cook on the lowest heat until the meat gives under a spoon. Allow an hour and a half.',
     no:'Rør inn sjalottløkpastaen og det varme vannet, salt, legg på lokk og la det stå på lavest mulig varme til kjøttet gir etter for en skje. Regn med halvannen time.'},
    {en:'Take the lid off and raise the heat for the last few minutes, until the fat separates and rises as a red film. Stir in the ghee, cover, and rest it for ten minutes before serving.',
     no:'Ta av lokket og skru opp varmen de siste minuttene, til fettet skiller seg ut og legger seg som en rød hinne. Rør inn gheen, legg på lokk, og la retten hvile i ti minutter før servering.'}],
  notes:[
    {title:{en:'Why there is no heat in it', no:'Hvorfor den ikke er sterk'},
     body:{en:'Kashmiri chilli has been selected for colour for centuries, so a spoonful of it stains a whole pot without burning anybody. If you want the dish hot, add a hotter chilli deliberately and measure it. Getting heat by accident from the colouring chilli is exactly what this kitchen avoids.',
           no:'Kashmiri-chili er foredlet for farge gjennom århundrer, så en skje av den farger en hel gryte uten å svi noen. Vil du ha retten sterk, har du i en sterkere chili med vilje og måler den opp. Chilien som bare skal farge, skal ikke gi styrke på kjøpet, og nettopp det skillet holder dette kjøkkenet på.'}},
    {title:{en:'Why the yoghurt is stirred one way', no:'Hvorfor yoghurten røres én vei'},
     body:{en:'Yoghurt curdles when it is heated, and it stays stable only once it has boiled with the meat. Constant movement in one direction keeps the curd dispersed while the pot climbs back to a simmer. Stop early and you get grains in the gravy that nothing later will dissolve.',
           no:'Yoghurt skiller seg når den varmes, og den blir først stabil etter at den har kokt sammen med kjøttet. Jevn bevegelse i én retning holder ostemassen fordelt mens gryta arbeider seg opp til kokepunktet igjen. Stopper du for tidlig, får du korn i sausen som ingenting senere løser opp.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Goat on the bone gives the firmer texture the long cooking is built around, and lamb finishes sooner and tastes milder.',
           no:'Geitekjøtt med bein gir den fastere strukturen den lange kokingen er bygd for. Geit og kje selges hos halalslaktere på Grønland i Oslo og i de fleste større byer, og norsk fårekjøtt er et godt alternativ som tåler hele koketiden; lammekjøtt blir ferdig tidligere og smaker mildere. Kashmiri-chilipulver får du i indiske butikker, og vanlig norsk chilipulver er ofte en blanding og gir både feil farge og feil smak. Mye sennepsolje i Norge er merket kun til utvortes bruk på grunn av erukasyre, så se etter flasker som sier «edible» eller «kachi ghani». Ratan jot selges i indiske butikker som «alkanet root», og retten fungerer godt uten.'}}],
  variations:[
    {title:{en:'The Pandit way, with no onion or garlic', no:'Pandit-måten, uten løk og hvitløk'},
     body:{en:'Leave out the shallots, the garlic and the fresh ginger entirely. Bloom a pinch of asafoetida in the hot oil before the meat goes in, and double the ground fennel and dry ginger. The gravy comes out cleaner and a little sweeter, and it is the version a Kashmiri Pandit household would recognise.',
           no:'Sløyf sjalottløken, hvitløken og den ferske ingefæren helt. La en klype asafoetida få noen sekunder i den varme oljen før kjøttet går i, og doble den malte fennikelen og den tørkede ingefæren. Sausen blir renere og litt søtere, og det er den utgaven en kashmirsk pandit-husholdning ville kjent igjen.'}},
    {title:{en:'Without ratan jot', no:'Uten ratan jot'},
     body:{en:'Use half again as much Kashmiri chilli powder and accept a slightly less glossy red. Some Pandit households colour with mawal, dried cockscomb flowers, steeped the same way. Never reach for food colouring, which is what the pillar-box red restaurant version is doing.',
           no:'Bruk halvannen gang så mye Kashmiri-chilipulver og godta at den røde fargen blir litt mindre blank. Noen pandit-husholdninger farger med mawal, tørkede blomster av hanekam, som trekkes på samme måte. Grip aldri etter konditorfarge, for det er akkurat det den knallrøde restaurantutgaven gjør.'}},
    {title:{en:'With lamb, and less time', no:'Med lam, og kortere tid'},
     body:{en:'Lamb shoulder on the bone is tender after about fifty minutes rather than ninety. Reduce the water by a third, because a shorter cook evaporates less, and watch it from forty minutes so it does not fall apart into the gravy.',
           no:'Lammebog med bein er mørt etter omtrent femti minutter i stedet for nitti. Reduser vannet med en tredel, for kortere koking fordamper mindre, og følg med fra førti minutter så kjøttet ikke faller fra hverandre i sausen.'}}]
},

{
  id:'yakhni', dish:'Yakhni', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:15, cook:80}, hero:'yakhni', tags:['yoghurt','pandit','mild'],
  title:{en:'Yakhni, the Pandit way', no:'Yakhni, slik pandit-kjøkkenet gjør det'},
  blurb:{en:'Meat simmered in whisked yoghurt with fennel and dry ginger. Nothing browned, no chilli, no onion.',
         no:'Kjøtt som småkoker i pisket yoghurt med fennikel og tørket ingefær. Ingenting brunet, ingen chili, ingen løk.'},
  heroCaption:{en:'The gravy should be pale and thin enough to pour. Any colour in it comes from the fat, not from a spice.',
               no:'Sausen skal være lys og tynn nok til å helles. Fargen den har, kommer fra fettet og ikke fra et krydder.'},
  goesWith:[{en:'Plain rice, so the gravy has somewhere to go', no:'Vanlig ris, så sausen har et sted å gjøre av seg'},
            {en:'A dry dish alongside, such as tabak maaz', no:'En tørr rett ved siden av, for eksempel tabak maaz'}],
  headnote:{
    en:`<p>Yakhni is the dish that shows what the Kashmiri Pandit kitchen is actually doing. Nothing is browned at any point, there is no chilli and no turmeric in it, and it contains neither onion nor garlic. What is left is meat, whole spices, whisked yoghurt and two ground powders, and it tastes of far more than that list suggests.</p>
<p>Ground fennel and ground dry ginger are the engine. Fennel is sweet and gives the gravy body as it cooks, which is the job the onion would have done, and dry ginger supplies the warmth and bite that garlic would have supplied. A pinch of asafoetida bloomed in ghee at the end gives a savoury, almost allium smell, and it is the third leg of the same stool.</p>
<p>One step decides whether the dish works, and it is the yoghurt. Yoghurt splits the moment it is heated unless it is kept moving, so it goes into a pot that is barely simmering and is stirred in one direction without a pause until the pot comes back up. After that it is stable and you can leave it alone for the rest of the cooking.</p>`,
    no:`<p>Yakhni er retten som viser hva det kashmirske pandit-kjøkkenet egentlig driver med. Ingenting brunes på noe tidspunkt, det er verken chili eller gurkemeie i den, og den inneholder verken løk eller hvitløk. Igjen står kjøtt, hele krydder, pisket yoghurt og to malte pulver, og den smaker av langt mer enn den listen skulle tilsi.</p>
<p>Malt fennikel og malt tørket ingefær er motoren. Fennikelen er søt og gir sausen fylde mens den koker, og det er nettopp jobben løken ville gjort, mens den tørkede ingefæren står for varmen og bittet hvitløken ellers ville gitt. En klype asafoetida som får noen sekunder i ghee til slutt, gir en smaksrik duft som ligger tett opp til stekt løk, og den er den tredje foten under den samme krakken.</p>
<p>Ett steg avgjør om retten lykkes, og det er yoghurten. Yoghurt skiller seg i det øyeblikket den varmes opp, med mindre den holdes i bevegelse, så den går i en gryte som så vidt småkoker og røres én vei uten pause til gryta koker opp igjen. Etter det er den stabil, og du kan la den stå resten av koketiden.</p>`},
  ingredients:[
   {group:{en:'The stock', no:'Kraften'}, items:[
    {q:900, u:'g', n:{en:'goat or mutton on the bone', no:'geitekjøtt eller fårekjøtt med bein'}, note:{en:'leg and neck, in pieces', no:'lår og nakke, i biter'}},
    {q:700, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
    {q:1, u:'', n:{en:'piece of cinnamon bark', no:'bit kanelbark'}, round:'half'},
    {q:4, u:'', n:{en:'green cardamom pods', no:'grønne kardemommekapsler'}, round:'half', note:{en:'bruised', no:'lett knust'}},
    {q:2, u:'', n:{en:'black cardamom pods', no:'sorte kardemommekapsler'}, round:'half'},
    {q:4, u:'', n:{en:'cloves', no:'hele nellik'}, round:'half'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The finish', no:'Avslutningen'}, items:[
    {q:500, u:'g', n:{en:'natural yoghurt', no:'naturell yoghurt'}, note:{en:'full fat, whisked completely smooth', no:'med høyt fettinnhold, pisket helt glatt'}},
    {q:8, u:'g', n:{en:'ground fennel', no:'malt fennikel'}},
    {q:4, u:'g', n:{en:'ground dry ginger', no:'malt tørket ingefær'}},
    {q:50, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:1, u:'g', n:{en:'asafoetida', no:'asafoetida'}},
    {q:2, u:'g', n:{en:'dried mint', no:'tørket mynte'}},
   ]}],
  steps:[
    {en:'Put the meat in a heavy pan with the water, the bay, the cinnamon and half the cardamom and cloves. Salt it lightly and bring it to a boil.',
     no:'Legg kjøttet i en tung gryte med vannet, laurbæret, kanelen og halvparten av kardemommen og nelliken. Salt lett og kok opp.'},
    {en:'Skim the grey foam off the top until the liquid runs clear. A yakhni that was not skimmed looks muddy for the rest of its life.',
     no:'Skum av det grå skummet på toppen til væsken er klar. En yakhni som ikke er skummet, ser grumsete ut resten av livet.'},
    {en:'Cover and simmer until the meat is nearly tender, allowing about fifty minutes. The liquid should reduce but never disappear.',
     no:'Legg på lokk og la det småkoke til kjøttet nesten er mørt, og regn med omtrent femti minutter. Væsken skal koke inn, men aldri forsvinne.'},
    {en:'Meanwhile whisk the yoghurt in a bowl with the ground fennel and the dry ginger until there is not a lump anywhere in it.',
     no:'Pisk i mellomtiden yoghurten i en bolle sammen med den malte fennikelen og den tørkede ingefæren, til det ikke er en eneste klump igjen.'},
    {en:'Pull the pan off the hard boil so the stock is barely moving, then pour the yoghurt in slowly down the side.',
     no:'Trekk gryta av platen så kraften så vidt beveger seg, og hell så yoghurten langsomt ned langs kanten.'},
    {en:'Start stirring the moment it goes in, always the same way round, and keep going over a medium flame until the pot comes back to a simmer.',
     no:'Begynn å røre i det øyeblikket den går i, alltid samme vei rundt, og fortsett på middels varme til gryta koker opp igjen.'},
    {en:'Once it has simmered the gravy is stable. It should have thickened very slightly and should still pour off a spoon.',
     no:'Når det først har kokt opp, er sausen stabil. Den skal ha tyknet så vidt og fortsatt renne av en skje.'},
    {en:'Melt the ghee in a small pan, add the asafoetida and the rest of the cardamom and cloves, and count five seconds while it foams and smells savoury.',
     no:'Smelt gheen i en liten panne, ha i asafoetidaen og resten av kardemommen og nelliken, og tell fem sekunder mens det skummer og lukter smaksrikt.'},
    {en:'Pour that over the pot and stir it through. Crush the dried mint between your palms as it falls in.',
     no:'Hell dette over gryta og rør det inn. Knus den tørkede mynten mellom håndflatene mens den faller ned i.'},
    {en:'Cover and simmer very gently for a further fifteen minutes, then taste for salt and serve pale, with plain rice.',
     no:'Legg på lokk og la det småkoke svært forsiktig i femten minutter til, smak så til med salt og server retten lys, med vanlig ris.'}],
  notes:[
    {title:{en:'Why there is no onion in it', no:'Hvorfor det ikke er løk i den'},
     body:{en:'A Kashmiri Pandit kitchen cooks meat freely and refuses onion and garlic entirely, so three things fill the gap. Fennel gives sweetness and body, dry ginger gives warmth and bite, and asafoetida bloomed in fat gives the savoury smell of fried onion. Leave any one of them out and the dish reads as unfinished.',
           no:'Et kashmirsk pandit-kjøkken lager kjøttretter uten videre og nekter helt å bruke løk og hvitløk, så tre ting fyller hullet. Fennikelen gir sødme og fylde, den tørkede ingefæren gir varme og bitt, og asafoetida som får noen sekunder i fett, gir den smaksrike duften av stekt løk. Sløyfer du én av dem, leses retten som uferdig.'}},
    {title:{en:'Why the stock is skimmed', no:'Hvorfor kraften skummes'},
     body:{en:'There is nothing in this dish to hide behind. No browning, no tomato and no chilli means the gravy is judged on how clean it looks, and the grey protein foam that rises in the first five minutes is the only thing that can spoil that. Take it off while it is still on the surface.',
           no:'Det finnes ingenting i denne retten å gjemme seg bak. Uten bruning, tomat og chili dømmes sausen på hvor ren den ser ut, og det grå proteinskummet som stiger de første fem minuttene, er det eneste som kan ødelegge det. Ta det av mens det fortsatt ligger på overflaten.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy the fattest plain yoghurt you can find and whisk it properly, because a thin yoghurt splits sooner.',
           no:'Norsk naturell yoghurt er tykkere og surere enn indisk dahi, så pisk den godt ut og bruk den feteste du finner; mager yoghurt skiller seg fortere. Asafoetida selges i små gule bokser i indiske butikker på Grønland i Oslo, og en boks holder i flere år. Malt tørket ingefær fra bakeavdelingen er riktig vare, men den står ofte lenge, så kjøp heller «sonth» i indisk butikk. Fennikelfrø males best selv i en kaffekvern. Geit og kje får du hos halalslaktere; norsk fårekjøtt fungerer godt og tåler koketiden.'}}],
  variations:[
    {title:{en:'Nadru yakhni, with lotus root', no:'Nadru yakhni, med lotusrot'},
     body:{en:'Replace the meat with lotus root, scrubbed hard and cut into thick rounds, and use water rather than stock. It needs about twenty minutes rather than fifty, and it keeps its bite. Frozen sliced lotus root from an Asian shop works perfectly well here.',
           no:'Bytt ut kjøttet med lotusrot som er skrubbet godt og skåret i tykke skiver, og bruk vann i stedet for kraft. Den trenger omtrent tjue minutter i stedet for femti, og den beholder biten. Frossen skivet lotusrot fra en asiatisk butikk fungerer utmerket her.'}},
    {title:{en:'The Muslim kitchen version', no:'Utgaven fra det muslimske kjøkkenet'},
     body:{en:'Fry a handful of sliced shallots gently in the ghee until they are golden rather than dark, and stir them in with the tempering at the end. Leave the asafoetida out. The gravy is rounder and slightly sweeter, and it is still called yakhni.',
           no:'Stek en neve skivet sjalottløk forsiktig i gheen til den er gyllen og ikke mørk, og rør den inn sammen med krydderfettet til slutt. Sløyf asafoetidaen. Sausen blir rundere og litt søtere, og den heter fortsatt yakhni.'}},
    {title:{en:'Chicken, in half the time', no:'Med kylling, på halve tiden'},
     body:{en:'Use thighs on the bone and cut the first simmer to twenty minutes. Add the yoghurt exactly as written. Chicken gives a thinner stock, so reduce the water by a quarter or the gravy will be watery.',
           no:'Bruk lår med bein og kort den første kokingen ned til tjue minutter. Ha i yoghurten nøyaktig som beskrevet. Kylling gir tynnere kraft, så reduser vannet med en fjerdedel, ellers blir sausen vassen.'}}]
},

{
  id:'kashmiri-dum-aloo', dish:'Dum aloo', course:'main', lesson:3, serves:4, veg:true,
  time:{prep:25, cook:50}, hero:'dum-aloo', tags:['potato','vegetarian','yoghurt'],
  title:{en:'Kashmiri dum aloo', no:'Kashmirsk dum aloo'},
  blurb:{en:'Small potatoes pricked, fried whole and then sealed into a red yoghurt gravy on the lowest heat.',
         no:'Små poteter som prikkes, stekes hele og så forsegles i en rød yoghurtsaus på lavest mulig varme.'},
  heroCaption:{en:'The gravy should cling rather than pool, and a little red oil should rise once it is finished.',
               no:'Sausen skal legge seg rundt potetene i stedet for å samle seg, og litt rød olje skal stige opp når retten er ferdig.'},
  goesWith:[{en:'Plain rice, and haak beside it', no:'Vanlig ris, med haak ved siden av'},
            {en:'Yoghurt, plain and cold', no:'Yoghurt, naturell og kald'}],
  headnote:{
    en:`<p>This has almost nothing to do with the dum aloo served in Delhi, which arrives in a sweet gravy of tomato, cream and cashew. The Kashmiri dish is red from mild chilli, sour from yoghurt, warm from fennel and dry ginger, and it contains no tomato and no onion at all.</p>
<p>Two mechanical steps carry it. The potatoes are pricked deeply all over with a fork and then fried whole in their skins, so the outside toughens while the inside stays soft and the holes stay open. Those holes are what let an hour of gravy get inside the potato rather than sitting around it, and a potato that was not pricked comes out bland in the middle however long you cook it.</p>
<p>The second step is the <em>dum</em> itself, which means cooking under a tight seal on the lowest possible heat. Traditionally the lid is luted on with a rope of dough. A heavy pan, a well-fitting lid and a very low flame do the same job, and the point is that nothing evaporates and the potatoes cook in the steam of their own gravy.</p>`,
    no:`<p>Dette har nesten ingenting å gjøre med den dum aloo som serveres i Delhi, og som kommer i en søt saus av tomat, fløte og cashewnøtter. Den kashmirske retten er rød av mild chili, syrlig av yoghurt og varm av fennikel og tørket ingefær, og den inneholder verken tomat eller løk.</p>
<p>To håndgrep bærer den. Potetene prikkes dypt over det hele med en gaffel og stekes så hele med skallet på, slik at utsiden blir seig mens innsiden holder seg myk og hullene står åpne. Hullene slipper en times saus inn i poteten i stedet for å la den ligge rundt, og en potet som ikke er prikket, kommer ut smakløs i midten uansett hvor lenge du koker den.</p>
<p>Det andre grepet er selve <em>dum</em>, som betyr å koke under tett forsegling på lavest mulig varme. Tradisjonelt tettes lokket med en pølse av deig. En tung gryte, et lokk som sitter godt, og en meget lav flamme gjør den samme jobben, og poenget er at ingenting fordamper og at potetene koker i dampen fra sin egen saus.</p>`},
  ingredients:[
   {group:{en:'The potatoes', no:'Potetene'}, items:[
    {q:800, u:'g', n:{en:'small waxy potatoes', no:'små fastkokende poteter'}, note:{en:'all about the same size', no:'omtrent like store'}},
    {u:'', n:{en:'oil for deep frying', no:'olje til frityrsteking'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The gravy', no:'Sausen'}, items:[
    {q:350, u:'g', n:{en:'natural yoghurt', no:'naturell yoghurt'}, note:{en:'full fat, whisked smooth', no:'med høyt fettinnhold, pisket glatt'}},
    {q:12, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri-chilipulver'}},
    {q:8, u:'g', n:{en:'ground fennel', no:'malt fennikel'}},
    {q:4, u:'g', n:{en:'ground dry ginger', no:'malt tørket ingefær'}},
    {q:1, u:'g', n:{en:'asafoetida', no:'asafoetida'}},
    {q:60, u:'ml', n:{en:'mustard oil', no:'sennepsolje'}},
    {q:4, u:'', n:{en:'green cardamom pods', no:'grønne kardemommekapsler'}, round:'half', note:{en:'bruised', no:'lett knust'}},
    {q:3, u:'', n:{en:'cloves', no:'hele nellik'}, round:'half'},
    {q:1, u:'', n:{en:'piece of cinnamon bark', no:'bit kanelbark'}, round:'half'},
    {q:350, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
   ]}],
  steps:[
    {en:'Scrub the potatoes and boil them in salted water until a knife just enters, which takes about eight minutes. Drain them and let them dry and cool.',
     no:'Skrubb potetene og kok dem i saltet vann til en kniv så vidt går inn, og det tar omtrent åtte minutter. Hell av vannet og la dem tørke og kjøle seg.'},
    {en:'Prick each potato deeply all over with a fork, twenty times or so. This is the step people skip and it is the one that matters.',
     no:'Prikk hver potet dypt over det hele med en gaffel, en tjue ganger eller så. Dette er steget folk hopper over, og det er det som betyr noe.'},
    {en:'Heat the frying oil to about 170 °C and fry the potatoes in batches until the skins are brown and wrinkled. Lift them onto kitchen paper.',
     no:'Varm frityroljen til omkring 170 °C og stek potetene i omganger til skallet er brunt og rynket. Løft dem opp på kjøkkenpapir.'},
    {en:'Whisk the yoghurt with the chilli powder, the fennel and the dry ginger until there is no lump and the colour is even.',
     no:'Pisk yoghurten sammen med chilipulveret, fennikelen og den tørkede ingefæren til det ikke er klumper igjen og fargen er jevn.'},
    {en:'Heat the mustard oil in a heavy pan until it just smokes, take it off the heat for half a minute, then add the cardamom, cloves and cinnamon.',
     no:'Varm sennepsoljen i en tung gryte til den så vidt ryker, ta den av platen et halvt minutt, og ha så i kardemomme, nellik og kanel.'},
    {en:'Add the asafoetida, count two seconds, and pour the spiced yoghurt straight in. Stir at once, always the same way round.',
     no:'Ha i asafoetidaen, tell to sekunder, og hell den krydrede yoghurten rett oppi. Rør med én gang, alltid samme vei rundt.'},
    {en:'Keep stirring over a medium flame until the gravy comes to a simmer and turns glossy. Leave it alone before that and it will curdle.',
     no:'Fortsett å røre på middels varme til sausen koker opp og blir blank. Går du fra den før det, skiller den seg.'},
    {en:'Add the water and the fried potatoes, salt it, and bring it back to a gentle simmer.',
     no:'Ha i vannet og de stekte potetene, salt, og la det komme forsiktig opp i småkoking igjen.'},
    {en:'Cover the pan as tightly as it will go, turn the heat to its lowest setting, and leave it alone for twenty-five minutes. That is the dum.',
     no:'Legg på lokket så tett som mulig, skru varmen ned til det laveste, og la gryta stå i fred i tjuefem minutter. Det er dum.'},
    {en:'Take the lid off, raise the heat, and reduce until the gravy clings to the potatoes and a little red oil rises. Rest it for ten minutes before serving.',
     no:'Ta av lokket, skru opp varmen, og kok inn til sausen legger seg rundt potetene og litt rød olje stiger opp. La retten hvile i ti minutter før servering.'}],
  notes:[
    {title:{en:'Why the potatoes are fried before they are stewed', no:'Hvorfor potetene stekes før de kokes'},
     body:{en:'Frying sets a tough skin that survives half an hour in liquid, so the potatoes stay whole instead of breaking up into the gravy. It also drives water out of the outer layer, which leaves room for the gravy to move in through the fork holes. Boiling alone gives you potatoes in sauce rather than potatoes full of sauce.',
           no:'Stekingen gir et seigt skall som tåler en halvtime i væske, så potetene holder seg hele i stedet for å gå i oppløsning i sausen. Den driver også vann ut av det ytterste laget, og det gir plass til at sausen kan trekke inn gjennom gaffelhullene. Bare koking gir deg poteter i saus i stedet for poteter fulle av saus.'}},
    {title:{en:'Why the seal matters', no:'Hvorfor forseglingen betyr noe'},
     body:{en:'Under a tight lid on a very low flame nothing evaporates, so the gravy stays the strength you mixed it at while the potatoes soak. Lift the lid to check and you lose steam, the gravy tightens, and the potatoes stop absorbing. Set a timer and trust it.',
           no:'Under et tett lokk på meget lav varme fordamper ingenting, så sausen holder den styrken du blandet den til mens potetene trekker til seg. Løfter du på lokket for å se, mister du damp, sausen strammer seg, og potetene slutter å suge. Sett en timer og stol på den.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Use small waxy potatoes of an even size; a floury variety collapses in the frying.',
           no:'Bruk små fastkokende poteter i jevn størrelse, for eksempel amandine eller ferske sommerpoteter. Melne sorter som beate og pimpernell faller fra hverandre i frityren. Kashmiri-chilipulver får du i indiske butikker på Grønland i Oslo, og det gir farge uten styrke, mens vanlig norsk chilipulver gir det motsatte. Asafoetida selges i små gule bokser og er ikke til å erstatte i denne retten, siden den skal gjøre løkens jobb.'}}],
  variations:[
    {title:{en:'Oven instead of a fryer', no:'Stekeovn i stedet for frityr'},
     body:{en:'Toss the pricked, boiled potatoes in a little oil and roast them at 220 °C until the skins blister and wrinkle, turning once. The texture is not quite the same but the dish works, and it uses a fraction of the oil.',
           no:'Vend de prikkede, forkokte potetene i litt olje og stek dem i ovnen på 220 °C til skallet får blærer og rynker seg, og snu dem en gang underveis. Konsistensen blir ikke helt den samme, men retten fungerer, og den bruker en brøkdel av oljen.'}},
    {title:{en:'With ver', no:'Med ver'},
     body:{en:'A Kashmiri Muslim household would crumble a piece of ver into the hot oil in place of the asafoetida, which brings garlic and shallot into the dish. Since ver is not sold in Norway, grinding a clove of garlic and a shallot into the yoghurt gets you most of the way.',
           no:'En kashmirsk muslimsk husholdning ville smuldret et stykke ver ned i den varme oljen i stedet for asafoetida, og det bringer hvitløk og sjalottløk inn i retten. Ver selges ikke i Norge, men maler du et hvitløkfedd og en sjalottløk inn i yoghurten, kommer du det meste av veien.'}},
    {title:{en:'The Delhi version, which is another dish', no:'Delhi-utgaven, som er en annen rett'},
     body:{en:'Tomato, cream and a cashew paste give the sweet orange gravy most people picture. It is perfectly good and it is not this. Say which one you cooked, because a Kashmiri will notice within one mouthful.',
           no:'Tomat, fløte og en pasta av cashewnøtter gir den søte oransje sausen de fleste ser for seg. Den er helt god, og den er ikke denne. Si hvilken av dem du lagde, for en kashmirer merker det i første munnfull.'}}]
},

{
  id:'haak', dish:'Haak', course:'side', lesson:3, serves:4, veg:true,
  time:{prep:10, cook:20}, hero:'haak', tags:['greens','everyday','fast'],
  title:{en:'Haak', no:'Haak'},
  blurb:{en:'Whole leaves boiled hard in water with mustard oil, green chilli and asafoetida. Nothing else at all.',
         no:'Hele blader kokt hardt i vann med sennepsolje, grønn chili og asafoetida. Ikke noe mer.'},
  heroCaption:{en:'Knol-khol with its leaves still attached. The leaf is haak and the bulb is monj, and the two are often cooked together.',
               no:'Knutekål med bladene på. Bladet er haak og knollen er monj, og de to kokes ofte sammen.'},
  goesWith:[{en:'Rice, with the green cooking liquid poured over it first', no:'Ris, med den grønne kokekraften helt over først'},
            {en:'A bowl of plain yoghurt', no:'En skål naturell yoghurt'}],
  headnote:{
    en:`<p>This is the plainest recipe in the whole course and the one a Kashmiri away from home misses most. A loose-leaf brassica is boiled in water with a spoonful of mustard oil, a couple of green chillies and a pinch of asafoetida, and that is the entire list. Nothing is fried, nothing is ground, nothing is thickened.</p>
<p>The cooking liquid is not a by-product. It is called haakh ras, it is thin and bright green and it tastes of the leaf and the oil, and it is poured over rice and eaten before the leaves are. Draining it away, which is what a European instinct says to do, throws out half the dish.</p>
<p>Two rules keep the colour. The pot stays uncovered and the flame stays high, because a lid traps the acids that come out of the leaves and turns them army green within minutes. And the leaves go in whole, because chopping them opens more surface and leaves you with something closer to spinach.</p>`,
    no:`<p>Dette er den enkleste oppskriften i hele kurset, og den retten en kashmirer utenlands savner mest. En bladkål som ikke setter hode, kokes i vann med en skje sennepsolje, et par grønne chilier og en klype asafoetida, og mer er det ikke på listen. Ingenting stekes, ingenting males, ingenting jevnes.</p>
<p>Kokekraften er ikke et biprodukt. Den heter haakh ras, den er tynn og knallgrønn og smaker av bladet og oljen, og den helles over risen og spises før bladene. Heller du den av, som en europeisk innskytelse sier at du skal, kaster du halve retten.</p>
<p>To regler holder på fargen. Gryta står uten lokk og flammen står høyt, for et lokk holder på syrene som kommer ut av bladene og gjør dem militærgrønne i løpet av få minutter. Og bladene går i hele, for skjærer du dem opp, blottlegger du mer flate og sitter igjen med noe som ligner mer på spinat.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:500, u:'g', n:{en:'collard greens or other loose-leaf brassica', no:'bladkål eller annen løsbladet kål'}, note:{en:'leaves left whole, thick stems trimmed', no:'bladene beholdes hele, de tykkeste stilkene skjæres bort'}},
    {q:800, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:40, u:'ml', n:{en:'mustard oil', no:'sennepsolje'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chilier'}, round:'half', note:{en:'slit lengthways, left whole', no:'flekket på langs, men hele'}},
    {q:1, u:'g', n:{en:'asafoetida', no:'asafoetida'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Wash the leaves in several changes of cold water and shake them dry. Leave them whole; nothing here is chopped.',
     no:'Vask bladene i flere omganger kaldt vann og rist dem tørre. La dem være hele; ingenting her skjæres opp.'},
    {en:'Bring the water to a rolling boil in a wide pan and salt it well.',
     no:'Kok opp vannet i en vid gryte til det fosskoker, og salt det godt.'},
    {en:'Heat the mustard oil in a small pan until it just smokes, then take it off the heat for a moment so it stops smoking.',
     no:'Varm sennepsoljen i en liten panne til den så vidt ryker, og ta den så av platen et øyeblikk så den slutter å ryke.'},
    {en:'Drop the asafoetida and the slit chillies into the oil. They will sizzle for a couple of seconds.',
     no:'Slipp asafoetidaen og de flekkede chiliene ned i oljen. Det freser et par sekunder.'},
    {en:'Pour the whole lot straight into the boiling water. It should hiss when it lands.',
     no:'Hell alt sammen rett i det kokende vannet. Det skal hvese når det treffer.'},
    {en:'Push the leaves in a handful at a time, letting each lot wilt down before the next goes in.',
     no:'Press bladene ned en neve om gangen, og la hver omgang falle sammen før den neste går i.'},
    {en:'Boil hard and uncovered for about ten minutes. Do not put a lid on at any point, or the leaves go grey.',
     no:'Kok hardt og uten lokk i omtrent ti minutter. Ikke legg på lokk på noe tidspunkt, ellers blir bladene grå.'},
    {en:'Taste a leaf. It should be tender with a little bite left, and the liquid should taste of greens and mustard oil rather than of water.',
     no:'Smak på et blad. Det skal være mørt med litt bitt igjen, og væsken skal smake av grønt og sennepsolje heller enn av vann.'},
    {en:'Take the pan off the heat and let it stand for five minutes so the liquid takes up more of the leaf.',
     no:'Ta gryta av platen og la den stå i fem minutter, så kraften trekker mer smak av bladene.'},
    {en:'Serve in a shallow bowl with all the liquid. Pour the liquid over the rice first and eat the leaves after it.',
     no:'Server i en grunn skål med all kraften. Hell kraften over risen først, og spis bladene etterpå.'}],
  notes:[
    {title:{en:'Why the lid stays off', no:'Hvorfor lokket blir liggende av'},
     body:{en:'Green leaves release volatile acids as they cook, and a lid sends them back into the water, where they strip the magnesium out of the chlorophyll and turn the leaf olive. An open pan lets them escape, so a high flame and no lid give a brighter dish in less time.',
           no:'Grønne blader gir fra seg flyktige syrer mens de koker, og et lokk sender dem tilbake i vannet, der de river magnesiumet ut av klorofyllet og gjør bladet olivengrønt. En åpen gryte lar dem slippe ut, så høy varme uten lokk gir en klarere rett på kortere tid.'}},
    {title:{en:'Why there is nothing else in it', no:'Hvorfor det ikke er noe mer i den'},
     body:{en:'Haak sits beside a rich meat dish and its job is to cut it, so onion, tomato or garam masala would make two rich dishes and no relief. The restraint is the recipe. If you find yourself adding things, cook something else instead.',
           no:'Haak står ved siden av en fyldig kjøttrett og har som oppgave å bryte den opp, så løk, tomat eller garam masala ville gitt to fyldige retter og ingen avveksling. Tilbakeholdenheten er selve oppskriften. Merker du at du har lyst til å tilsette ting, lag heller noe annet.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Any loose-leaf brassica that holds its shape in water will do; the leaf should be flat rather than curly.',
           no:'Ekte haak selges ikke her, men bladkål, som ofte selges under det engelske navnet collard greens, finnes i asiatiske og afrikanske butikker i Oslo og er nærmest. Grønnkål fungerer hvis du skjærer bort de tykke stilkene, men den er seigere og mer bitter, så kok den noen minutter lenger. Stilkene og bladene på knutekål er faktisk den riktige planten, så spør på torget eller i gårdsbutikken etter knutekål med topp. Spisskål og pak choi er for vasne og faller sammen til ingenting.'}}],
  variations:[
    {title:{en:'Monje haak, with the bulb as well', no:'Monje haak, med knollen i tillegg'},
     body:{en:'Add knol-khol peeled and cut into thin rounds, and give it five minutes in the water before the leaves go in. The bulb stays crisp and sweet and the dish becomes a meal rather than a side.',
           no:'Ha i knutekål som er skrelt og skåret i tynne skiver, og gi den fem minutter i vannet før bladene går i. Knollen holder seg sprø og søt, og retten blir et måltid i stedet for et tilbehør.'}},
    {title:{en:'Nadir haak, with lotus root', no:'Nadir haak, med lotusrot'},
     body:{en:'Thick slices of lotus root, boiled for a quarter of an hour before the leaves join them, turn this into a winter dish. It is the same principle as monje haak with a different crunch.',
           no:'Tykke skiver lotusrot, kokt i et kvarter før bladene kommer i, gjør dette til en vinterrett. Prinsippet er det samme som i monje haak, bare med en annen sprøhet.'}},
    {title:{en:'Hokh syun, the dried winter version', no:'Hokh syun, den tørkede vinterutgaven'},
     body:{en:'Kashmir dries greens, turnips, aubergine and tomato on strings through the autumn and cooks them in the months when nothing grows. Dried greens need soaking and roughly twice the cooking time, and they taste deeper and slightly smoky.',
           no:'Kashmir tørker grønne blader, neper, aubergine og tomat på snorer gjennom høsten og koker dem i de månedene da ingenting vokser. Tørkede blader må bløtlegges og trenger omtrent dobbelt så lang koketid, og de smaker dypere og litt røykpreget.'}}]
},

{
  id:'kahwa', dish:'Kahwa', course:'snack', lesson:3, serves:4, veg:true,
  time:{prep:5, cook:10}, hero:'kahwa', tags:['tea','saffron','almond'],
  title:{en:'Kahwa', no:'Kahwa'},
  blurb:{en:'Green tea with saffron, cardamom and cinnamon, poured over shaved almonds sitting in the cup.',
         no:'Grønn te med safran, kardemomme og kanel, helt over høvlede mandler som ligger i koppen.'},
  heroCaption:{en:'The colour should be amber rather than green, and the almonds should still be floating when it reaches the table.',
               no:'Fargen skal være ravgul heller enn grønn, og mandlene skal fortsatt flyte når den kommer på bordet.'},
  goesWith:[{en:'Anything rich, and especially after a wazwan', no:'Alt som er fyldig, og særlig etter en wazwan'},
            {en:'A plate of walnuts in winter', no:'En tallerken valnøtter om vinteren'}],
  headnote:{
    en:`<p>Kahwa is the cup a Kashmiri household gives a guest, and it is not the everyday tea. That is noon chai, which is salted and pink. Kahwa is the good one: green tea brewed with cardamom and cinnamon, perfumed with a few threads of saffron, and poured over shaved almonds already sitting in the bottom of the cup.</p>
<p>The word itself carries the route the drink came by. Kahwa comes from the Arabic for coffee, and the vessel it is made in, the samovar, is a Central Asian object with a Russian name. A copper samovar has a fire chamber running up the middle, so a handful of coals keeps the tea hot all day without it stewing on a hob.</p>
<p>Two things often go wrong at home. Green tea boiled with the spices turns bitter and grey, so the leaves go in off the heat and stay in for a short time. Crushing and steeping the saffron separately helps its colour and aroma spread evenly through the pot.</p>`,
    no:`<p>Kahwa er koppen en kashmirsk husholdning gir en gjest, og den er ikke hverdagsteen. Hverdagsteen heter noon chai, og den er saltet og rosa. Kahwa er den fine: grønn te trukket med kardemomme og kanel, parfymert med noen tråder safran og helt over høvlede mandler som allerede ligger i bunnen av koppen.</p>
<p>Selve ordet bærer veien drikken kom langs. Kahwa kommer fra det arabiske ordet for kaffe, og karet den lages i, samovaren, er en sentralasiatisk gjenstand med et russisk navn. En kobbersamovar har et ildrom som går opp gjennom midten, så en håndfull glør holder teen varm hele dagen uten at den koker seg i hjel på en plate.</p>
<p>To ting går ofte galt hjemme. Grønn te som kokes sammen med krydderet, blir bitter og grå, så bladene går i med kjelen av platen og trekker kort. Knust safran som trekkes for seg, fordeler fargen og aromaen jevnere i kanna.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:800, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:8, u:'g', n:{en:'green tea leaves', no:'grønne teblader'}, note:{en:'Kashmiri green tea if you have it', no:'kashmirsk grønn te hvis du har'}},
    {q:6, u:'', n:{en:'green cardamom pods', no:'grønne kardemommekapsler'}, round:'half', note:{en:'bruised so the husks crack', no:'knust så skallet sprekker'}},
    {q:1, u:'', n:{en:'piece of cinnamon bark', no:'bit kanelbark'}, round:'half'},
    {u:'', n:{en:'saffron threads, about twenty', no:'safrantråder, omkring tjue'}, scale:'none'},
    {q:25, u:'g', n:{en:'almonds', no:'mandler'}, note:{en:'blanched and shaved thin', no:'smuttet og høvlet tynt'}},
    {q:15, u:'g', n:{en:'sugar or honey', no:'sukker eller honning'}, note:{en:'optional, and less than you think', no:'valgfritt, og mindre enn du tror'}},
   ]}],
  steps:[
    {en:'Bruise the cardamom pods until the husks crack, and break the cinnamon into two or three pieces.',
     no:'Knus kardemommekapslene til skallet sprekker, og brekk kanelen i to eller tre biter.'},
    {en:'Crush the saffron between your fingers into a small cup, pour a little hot water over it, and leave it to steep while you make the tea.',
     no:'Knus safranen mellom fingrene ned i en liten kopp, hell litt varmt vann over, og la den trekke mens du lager teen.'},
    {en:'Bring the water to a boil with the cardamom and the cinnamon, and let it boil for two minutes so the spices give up their oils.',
     no:'Kok opp vannet sammen med kardemommen og kanelen, og la det koke i to minutter så krydderet gir fra seg oljene sine.'},
    {en:'Take the pan off the heat and wait half a minute, so the water is hot rather than boiling.',
     no:'Ta kjelen av platen og vent et halvt minutt, så vannet er varmt og ikke kokende.'},
    {en:'Add the green tea leaves, cover, and leave them for no more than two minutes. Longer than that and the tea turns bitter.',
     no:'Ha i de grønne tebladene, legg på lokk, og la dem trekke i høyst to minutter. Trekker de lenger, blir teen bitter.'},
    {en:'Strain into a warmed pot and stir the saffron water in. The colour should go from pale gold to amber.',
     no:'Sil over i en forvarmet kanne og rør inn safranvannet. Fargen skal gå fra lys gyllen til ravgul.'},
    {en:'Sweeten lightly if you want it sweet, and taste as you go. Kahwa should be perfumed rather than sugary.',
     no:'Sukre lett hvis du vil ha den søt, og smak deg fram. Kahwa skal være parfymert heller enn søt.'},
    {en:'Divide the shaved almonds between the cups so they lie in the bottom.',
     no:'Fordel de høvlede mandlene i koppene så de ligger i bunnen.'},
    {en:'Pour the tea over them from a height, which makes the almonds turn over in the cup.',
     no:'Hell teen over dem fra et stykke opp, så mandlene snur seg rundt i koppen.'},
    {en:'Serve at once, while the almonds are still floating and the cardamom is still on the nose.',
     no:'Server med én gang, mens mandlene fortsatt flyter og kardemommen fortsatt kjennes i duften.'}],
  notes:[
    {title:{en:'Why the tea is never boiled', no:'Hvorfor teen aldri kokes'},
     body:{en:'Green tea leaves release tannins quickly at a full boil, and tannin is what makes tea astringent and grey. The spices need boiling water and the leaves do not, so the two are brewed in that order in the same pan, which is why the tea goes in after the heat is off.',
           no:'Grønne teblader gir raskt fra seg garvestoffer i fosskokende vann, og garvestoff er det som gjør te besk og grå. Krydderet trenger kokende vann, mens bladene ikke gjør det, så de to trekkes i den rekkefølgen i den samme kjelen, og derfor går teen i etter at varmen er av.'}},
    {title:{en:'Why the saffron is steeped apart', no:'Hvorfor safranen trekkes for seg'},
     body:{en:'Saffron carries its colour in crocin and much of its aroma in safranal. Crushing and steeping a small quantity in warm water before it enters the pot extracts and distributes those qualities more evenly.',
           no:'Safran bærer fargen i krocin og mye av duften i safranal. Når en liten mengde knuses og trekker i varmt vann før den går i kanna, trekkes disse egenskapene ut og fordeles jevnere.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy saffron as threads rather than powder, and use blanched almonds so the skins do not muddy the cup.',
           no:'Kjøp safran som tråder og ikke som pulver, for pulver er det enkleste å drøye. Det som selges som kanelstang i norske dagligvarebutikker, er nesten alltid kassia, som er kraftigere og mer bitter; ekte kanel, ofte merket ceylon, får du i indiske butikker og gir en mildere og mer blomsteraktig te. Bruk smuttede mandler, ellers farger skallet koppen grå. Kashmirsk grønn te finnes sjelden her, og en vanlig kinesisk grønn te fungerer fint så lenge du ikke koker den.'}}],
  variations:[
    {title:{en:'Noon chai, the everyday pink one', no:'Noon chai, den rosa hverdagsteen'},
     body:{en:'Boil green tea leaves hard with a pinch of bicarbonate of soda until the liquor runs deep red, then add cold milk and salt instead of sugar. The colour turns pink, the taste is savoury, and it is what a Kashmiri actually drinks at breakfast.',
           no:'Kok grønne teblader hardt med en klype natron til kraften blir dyprød, og ha så i kald melk og salt i stedet for sukker. Fargen blir rosa, smaken er salt heller enn søt, og det er dette en kashmirer faktisk drikker til frokost.'}},
    {title:{en:'With walnut, in winter', no:'Med valnøtt, om vinteren'},
     body:{en:'Kashmir grows a great many walnuts, and a crushed walnut in the cup instead of almonds gives a heavier, slightly bitter drink that suits a cold afternoon. Do not use both nuts at once.',
           no:'Kashmir dyrker svært mange valnøtter, og en knust valnøtt i koppen i stedet for mandler gir en tyngre og litt bitrere drikk som passer en kald ettermiddag. Ikke bruk begge nøttene samtidig.'}},
    {title:{en:'Without a samovar', no:'Uten samovar'},
     body:{en:'A small pan and a warmed teapot do everything the samovar does except keep the tea hot for hours. If you want that, brew it strong and keep it in a vacuum flask, which is what many houses in Srinagar now do anyway.',
           no:'En liten kjele og en forvarmet tekanne gjør alt samovaren gjør, bortsett fra å holde teen varm i timevis. Vil du ha det, trekk den sterk og hold den på termos, og det er uansett det mange hus i Srinagar gjør i dag.'}}]
},

];
