/* Masala Dabba — recipes for Karnataka (IN-KAR). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-KAR'] = [

{
  id:'bisi-bele-bath', dish:'Bisi bele bath', course:'rice', lesson:3, serves:4, veg:true,
  time:{prep:25, cook:50}, hero:'bisi-bele-bath', tags:['rice','dal','one pot'],
  title:{en:'Bisi bele bath', no:'Bisi bele bath'},
  blurb:{en:'Rice, lentils and vegetables cooked into each other with tamarind, ghee and a spice powder made for this dish alone.',
         no:'Ris, linser og grønnsaker kokt inn i hverandre med tamarind, ghee og en krydderblanding som bare er laget til denne retten.'},
  heroCaption:{en:'It should leave the pan looser than you want to eat it, because it goes on thickening in the bowl.',
               no:'Ta den av platen mens den er løsere enn du vil spise den, for den fortsetter å tykne i skålen.'},
  goesWith:[{en:'Crisp boondi scattered over', no:'Sprø boondi strødd over'},
            {en:'A spoonful of ghee and a papad', no:'En skje ghee og en papad'}],
  headnote:{
    en:`<p>The name says what it is. Bisi is hot, bele is lentil and bath is a cooked rice dish, so this is hot lentil rice, and the three words are a recipe as well as a name. It belongs to the Mysore end of Karnataka and it is what a household cooks when a lot of people are coming.</p>
<p>The thing to understand before you start is that this is one dish and not two. Sambar with rice is a stew meeting a grain on a plate, and each keeps its own character. Here the rice and the toor dal are cooked past the point where they hold their shape, and then cooked together with tamarind, vegetables and the spice powder until the whole pot is a single thick, sour, faintly sweet mass eaten with a spoon.</p>
<p>Two things are not negotiable. The spice powder has roasted lentils ground into it, and those lentils are what gives the dish its body, so a plain sambar powder will leave you with something thin. And it must come off the heat looser than you want it, because the starch keeps drinking as it stands. A bisi bele bath that was perfect in the pan is a solid block ten minutes later.</p>`,
    no:`<p>Navnet sier hva retten er. Bisi betyr varm, bele betyr linse og bath er en kokt risrett, så dette er varm linse og ris, og de tre ordene er både et navn og en oppskrift. Retten hører hjemme i området rundt Mysore, og det er den en husholdning lager når det kommer mange gjester.</p>
<p>Før du begynner, er det én ting du må ha klart for deg: dette er én rett og ikke to. Sambar med ris er en gryterett og ris som møtes på tallerkenen, og begge beholder sitt eget preg. Her kokes risen og toor dalen til de ikke lenger holder formen, og så kokes de videre sammen med tamarind, grønnsaker og krydderblandingen til hele gryten er én tykk, sur og svakt søt masse som spises med skje.</p>
<p>To ting kan du ikke fire på. Krydderblandingen har ristede linser malt inn i seg, og de linsene gir retten fylde, så med vanlig sambarpulver blir den tynn. Dessuten må gryten av platen mens retten er løsere enn du vil ha den, for stivelsen fortsetter å trekke til seg væske mens den står. En bisi bele bath som var perfekt i gryten, er en fast blokk ti minutter senere.</p>`},
  ingredients:[
   {group:{en:'The spice powder', no:'Krydderblandingen'}, items:[
    {q:25, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:15, u:'g', n:{en:'chana dal', no:'chana dal'}},
    {q:10, u:'g', n:{en:'urad dal', no:'urad dal'}},
    {q:3, u:'g', n:{en:'fenugreek seed', no:'bukkehornkløverfrø'}},
    {q:20, u:'g', n:{en:'dried Byadgi chillies', no:'tørkede byadgichilier'}, note:{en:'stalks pulled off', no:'med stilkene revet av'}},
    {q:15, u:'g', n:{en:'dried coconut', no:'tørket kokos'}},
    {q:3, u:'g', n:{en:'cinnamon', no:'kanel'}},
    {q:6, u:'', n:{en:'cloves', no:'nellikspiker'}, round:'half'},
   ]},
   {group:{en:'The pot', no:'Gryten'}, items:[
    {q:200, u:'g', n:{en:'short-grain rice', no:'kortkornet ris'}, note:{en:'sona masoori or any round grain, not basmati', no:'sona masoori eller annen rundkornet ris, ikke basmati'}},
    {q:150, u:'g', n:{en:'toor dal', no:'toor dal'}},
    {q:1.4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:300, u:'g', n:{en:'mixed vegetables', no:'blandede grønnsaker'}, note:{en:'carrot, beans, peas, potato, in rough dice', no:'gulrot, bønner, erter og potet i grove terninger'}},
    {q:30, u:'g', n:{en:'tamarind pulp', no:'tamarindmasse'}},
    {q:15, u:'g', n:{en:'jaggery', no:'jaggery'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The tempering', no:'Temperingen'}, items:[
    {q:60, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:30, u:'g', n:{en:'cashew nuts', no:'cashewnøtter'}},
    {q:5, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:2, u:'', n:{en:'dried Byadgi chillies', no:'tørkede byadgichilier'}, round:'half', note:{en:'broken in half', no:'brukket i to'}},
    {q:15, u:'', n:{en:'curry leaves', no:'karriblader'}},
   ]}],
  steps:[
    {en:'Toast the coriander seed, chana dal, urad dal and fenugreek in a dry pan over a low flame until the lentils go gold and smell nutty. Tip them onto a cold plate.',
     no:'Rist korianderfrø, chana dal, urad dal og bukkehornkløver i en tørr panne på svak varme til linsene blir gylne og lukter nøtteaktig. Hell dem over på en kald tallerken.'},
    {en:'In the same pan toast the chillies, the cinnamon and the cloves for under a minute, then the dried coconut until it just colours. Let everything cool, then grind it all to a fine powder.',
     no:'Rist chiliene, kanelen og nellikspikrene i samme panne i under et minutt, og så den tørkede kokosen til den så vidt får farge. La alt kjøle seg, og mal det så til et fint pulver.'},
    {en:'Rinse the rice and the toor dal together and cook them in the water until both are soft and starting to break down. A pressure cooker does it in four whistles, an open pot in about forty minutes.',
     no:'Skyll risen og toor dalen sammen og kok dem i vannet til begge deler er myke og begynner å falle fra hverandre. En trykkoker klarer det på fire plystringer, en åpen gryte på omtrent førti minutter.'},
    {en:'While that cooks, boil the vegetables separately in salted water until just tender, and drain them.',
     no:'Mens dette koker, koker du grønnsakene for seg i saltet vann til de akkurat er møre, og heller av vannet.'},
    {en:'Soak the tamarind in hot water for ten minutes, squeeze it out with your fingers and strain the liquid.',
     no:'Bløtlegg tamarinden i varmt vann i ti minutter, klem den ut med fingrene og sil av væsken.'},
    {en:'Stir the vegetables, the tamarind water, the jaggery, salt and most of the ground powder into the rice and dal.',
     no:'Rør grønnsakene, tamarindvannet, jaggeryen, salt og det meste av krydderblandingen inn i risen og dalen.'},
    {en:'Cook it uncovered for ten to fifteen minutes, stirring often so it does not catch on the base. Loosen it with hot water whenever it stops pouring off the spoon.',
     no:'Kok det uten lokk i ti til femten minutter, og rør ofte så det ikke svir seg i bunnen. Spe med varmt vann hver gang det slutter å renne av skjeen.'},
    {en:'Taste and correct it: more powder for depth, more tamarind for sharpness, more salt. Then stir in most of the ghee.',
     no:'Smak til: mer krydderblanding for dybde, mer tamarind for syre, mer salt. Rør så inn det meste av gheen.'},
    {en:'Heat the rest of the ghee in a small pan and fry the cashews until gold. Add the mustard seed, and when it pops, the broken chillies and the curry leaves.',
     no:'Varm resten av gheen i en liten panne og stek cashewnøttene gylne. Ha i sennepsfrøene, og når de spretter, de brukne chiliene og karribladene.'},
    {en:'Pour the tempering over, stir once, and serve at once while it still moves in the bowl.',
     no:'Hell temperingen over, rør én gang, og server med det samme, mens retten fortsatt beveger seg i skålen.'},
  ],
  notes:[
    {title:{en:'Why it needs no other thickening', no:'Hvorfor den ikke trenger annen jevning'},
     body:{en:'Roasted chana dal and urad dal are ground into the spice powder, so the blend is a starch as well as a seasoning. That is what holds the dish together once the rice has given up its shape, and it is why substituting sambar powder gives you a soup with rice in it.',
           no:'Ristet chana dal og urad dal males inn i krydderblandingen, så blandingen er like mye stivelse som krydder. Stivelsen holder retten sammen når risen har mistet formen, og derfor gir sambarpulver deg en suppe med ris i.'}},
    {title:{en:'Why it must come off the heat too loose', no:'Hvorfor den må av platen for løs'},
     body:{en:'Cooked rice starch keeps taking up liquid for as long as it is warm. A pot that looks right on the stove will be stiff by the time it reaches the table, and reheating it never brings the texture back, it only dries it further. Cook it looser than seems sensible and thin it again with hot water if it stands.',
           no:'Kokt risstivelse fortsetter å ta opp væske så lenge den er varm. En gryte som ser riktig ut på platen, er stiv når den når bordet, og oppvarming gir aldri konsistensen tilbake, men tørker retten bare mer. Kok den løsere enn det virker fornuftig, og spe med varmt vann igjen om den blir stående.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Ready-made bisi bele bath powder is sold in Indian shops, MTR being the usual brand, and it is honest to use it. Toor dal is often labelled tuvar or arhar dal. Use a round or medium grain rice rather than basmati, which stays separate and is wrong here; ordinary Norwegian grøtris works. Buy tamarind as a block and soak it rather than as a bottled concentrate, which is saltier and darker.',
           no:'Ferdig bisi bele bath-pulver selges i indiske butikker, som regel fra MTR, og det er helt i orden å bruke det. Toor dal står ofte som tuvar eller arhar dal. Bruk rundkornet eller middelskornet ris heller enn basmati, der kornene holder seg hver for seg, og det blir feil her; vanlig norsk grøtris fungerer godt. Kjøp tamarind i blokk og bløtlegg den heller enn å bruke konsentratet på flaske, som er saltere og mørkere.'}}],
  variations:[
    {title:{en:'Everything in the pressure cooker', no:'Alt i trykkokeren'},
     body:{en:'Put the rinsed rice, the dal, the diced vegetables, turmeric and the water in together and cook for five whistles. The vegetables lose their edges, which some households prefer and others consider a failure, and it saves half an hour.',
           no:'Ha den skylte risen, dalen, grønnsakene i terninger, gurkemeie og vannet i samtidig, og kok i fem plystringer. Grønnsakene mister kantene, noe enkelte husholdninger foretrekker og andre regner som mislykket, og du sparer en halvtime.'}},
    {title:{en:'Avarekalu in the winter', no:'Avarekalu om vinteren'},
     body:{en:'Around Bengaluru the winter version is made with avarekalu, shelled hyacinth beans, thrown in with the vegetables. Frozen broad beans are the nearest thing available here and behave much the same way.',
           no:'Rundt Bengaluru lages vinterutgaven med avarekalu, altså avskallede lablabbønner, som går i sammen med grønnsakene. Frosne bondebønner ligger nærmest av det som finnes her, og de oppfører seg omtrent likt.'}},
    {title:{en:'Without the homemade powder', no:'Uten hjemmelaget blanding'},
     body:{en:'Sambar powder with a little extra cinnamon and clove will season the pot, but it will not thicken it. Grind fifty grams of roasted chana dal separately and stir that in, and you have most of the difference back.',
           no:'Sambarpulver med litt ekstra kanel og nellik krydrer gryten, men det tykner den ikke. Mal femti gram ristet chana dal for seg og rør det inn, så har du hentet tilbake det meste av forskjellen.'}}]
},

{
  id:'neer-dosa', dish:'Neer dosa', course:'breakfast', lesson:2, serves:4, veg:true,
  time:{prep:15, cook:25}, hero:'neer-dosa', tags:['rice','coconut','coast'],
  title:{en:'Neer dosa', no:'Neer dosa'},
  blurb:{en:'A coastal rice pancake with no lentil and no fermentation: soaked rice, coconut, water, and a very hot pan.',
         no:'En rispannekake fra kysten uten linser og uten gjæring: bløtlagt ris, kokos, vann og en glovarm panne.'},
  heroCaption:{en:'The batter is poured, never spread, and the holes open by themselves as the water flashes to steam.',
               no:'Røren helles, den bres aldri ut, og hullene åpner seg av seg selv når vannet slår over til damp.'},
  goesWith:[{en:'Fresh coconut chutney', no:'Fersk kokoschutney'},
            {en:'A chicken or fish curry, or grated coconut with jaggery', no:'En karri av kylling eller fisk, eller revet kokos med jaggery'}],
  headnote:{
    en:`<p>Neeru is water in Kannada, and this is the water dosa. There is no urad dal in it, nothing is left overnight and nothing ferments, which makes it the exact opposite of the batter Tamil Nadu's module explains at length. Soaked raw rice is ground with a little fresh coconut and then thinned with water until it is looser than milk.</p>
<p>Everything depends on that thinness. The batter is not spread with a ladle, because it is far too thin to hold a track; it is poured from the outer edge of the pan inwards and allowed to find its own level. On a properly hot pan the water in it turns to steam almost at once, and the holes that open across the surface are that steam escaping. Nothing crisps. A neer dosa is white, soft and pliable, and it is folded rather than rolled.</p>
<p>The trade is obvious once you have made it. You can put the rice to soak after breakfast and eat these at lunch, which no fermented batter will let you do. In return the batter is finished by the end of the day, and left in the fridge it goes sour and useless rather than better.</p>`,
    no:`<p>Neeru betyr vann på kannada, og dette er vanndosaen. Den har ingen urad dal i seg, ingenting settes over natten og ingenting gjærer, og dermed er den det stikk motsatte av røren modulen om Tamil Nadu forklarer i detalj. Bløtlagt rå ris males med litt fersk kokos og røren spes så med vann til den er tynnere enn melk.</p>
<p>Alt henger på den tynnheten. Røren bres ikke ut med en sleiv, for den er altfor tynn til å holde på et spor; den helles fra ytterkanten av pannen og innover og får legge seg jevnt av seg selv. I en ordentlig varm panne slår vannet nesten straks over til damp, og hullene som åpner seg over hele flaten, er den dampen som slipper ut. Ingenting blir sprøtt. En neer dosa er hvit, myk og bøyelig, og den brettes i stedet for å rulles.</p>
<p>Hva du vinner og taper, blir tydelig så snart du har laget dem. Du kan sette risen i bløt etter frokost og spise dem til lunsj, og det lar ingen gjæret røre deg gjøre. Til gjengjeld holder røren bare dagen ut, og står den i kjøleskapet, blir den sur og ubrukelig i stedet for bedre.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:250, u:'g', n:{en:'raw short-grain rice', no:'rå kortkornet ris'}, note:{en:'sona masoori or similar, not parboiled and not basmati', no:'sona masoori eller liknende, ikke parboiled og ikke basmati'}},
    {q:60, u:'g', n:{en:'fresh grated coconut', no:'fersk revet kokos'}},
    {q:700, u:'ml', n:{en:'water', no:'vann'}, scale:'sub', note:{en:'for grinding and for letting the batter down', no:'til maling og til å spe røren med'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'oil for the pan', no:'olje til pannen'}, scale:'none'},
   ]}],
  steps:[
    {en:'Rinse the rice until the water runs clear, then leave it to soak in cold water for at least four hours or overnight.',
     no:'Skyll risen til vannet er klart, og la den så ligge i kaldt vann i minst fire timer eller over natten.'},
    {en:'Drain it and grind it with the coconut and just enough fresh water to keep the blades moving, until you cannot feel any grit between two fingers.',
     no:'Hell av vannet og mal risen med kokosen og akkurat nok friskt vann til at knivene går rundt, helt til du ikke kjenner korn mellom to fingre.'},
    {en:'Let the batter down with the rest of the water and salt it. It should run off the ladle in a stream and leave no film behind.',
     no:'Spe røren med resten av vannet og salt den. Den skal renne av sleiven i en stråle og ikke legge igjen noen hinne.'},
    {en:'Heat a heavy iron or non-stick pan until a drop of water skitters across it, then wipe it with a little oil on kitchen paper.',
     no:'Varm en tung jernpanne eller en slippbelagt panne til en vanndråpe danser over den, og tørk den så over med litt olje på et kjøkkenpapir.'},
    {en:'Stir the batter, take the pan off the heat, and pour a ladleful in a quick circle from the outer edge towards the middle. Do not touch it with the ladle.',
     no:'Rør i røren, ta pannen av platen, og hell en sleiv i en rask sirkel fra ytterkanten og innover. Ikke rør ved den med sleiven.'},
    {en:'Put the pan back on the heat, cover it, and cook for about a minute until the surface is dry all over and the edge begins to lift.',
     no:'Sett pannen tilbake på platen, legg på lokk, og stek i omtrent et minutt til overflaten er tørr overalt og kanten begynner å løsne.'},
    {en:'Do not turn it. Slide it out, fold it in half and then in half again, and stack the folded dosas on a warm plate.',
     no:'Ikke snu den. Ta den ut, brett den i to og så i to igjen, og legg de brettede dosaene i en stabel på en varm tallerken.'},
    {en:'Stir the batter again before every single dosa, because the rice settles to the bottom within a minute, and thin it with a splash of water when it stops running freely.',
     no:'Rør i røren igjen før hver eneste dosa, for risen legger seg i bunnen i løpet av et minutt, og spe med litt vann når den slutter å renne lett.'},
  ],
  notes:[
    {title:{en:'Why it is poured and not spread', no:'Hvorfor den helles og ikke bres ut'},
     body:{en:'A dosa batter is spread because it is thick enough to hold the mark of the ladle. This one is not, and dragging a ladle through it only tears holes where you do not want them. Pouring from the edge inwards lets the batter run to an even depth of its own accord, which is also why the pan has to be level.',
           no:'En dosarøre bres ut fordi den er tykk nok til å holde på sporet etter sleiven. Denne er ikke det, og drar du en sleiv gjennom den, river du bare hull der du ikke vil ha dem. Heller du fra kanten og innover, renner røren ut i jevn tykkelse av seg selv, og derfor må pannen også stå vannrett.'}},
    {title:{en:'Why there is no lentil in it', no:'Hvorfor det ikke er linser i den'},
     body:{en:'Urad dal is in an idli batter because it traps the gas that fermentation makes. Nothing is fermenting here, so there is no gas to trap and no reason for the lentil. The lift comes from water turning to steam under a lid, which is instant, and that is the whole difference between a batter you plan a day ahead and one you decide on over breakfast.',
           no:'Urad dal er med i en idlirøre fordi den fanger gassen gjæringen lager. Her gjærer ingenting, så det finnes ingen gass å fange og ingen grunn til linsen. Luften i dosaen kommer av at vann blir til damp under et lokk, og det skjer med én gang. Nettopp der går skillet mellom en røre du planlegger dagen før, og en du bestemmer deg for ved frokostbordet.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy sona masoori or plain idli rice in an Indian shop. Basmati is wrong twice over, since it is aromatic and its starch does not set into a soft sheet, and parboiled rice belongs in the fermented batter instead. Use frozen grated coconut from an Asian shop rather than the desiccated coconut sold for baking, which is dried out and gives very little. A cast-iron pancake pan of the kind most Norwegian kitchens already own is the right pan.',
           no:'Kjøp sona masoori eller vanlig idliris i en indisk butikk. Basmati er feil på to måter, for den er aromatisk og stivelsen setter seg ikke til et mykt ark, og parboiled ris hører hjemme i den gjærede røren i stedet. Bruk frossen revet kokos fra en asiatisk butikk heller enn kokosmassen som selges til baking, som er tørket ut og gir svært lite. En pannekakepanne i støpejern, som de fleste norske kjøkken alt har, er den rette pannen.'}}],
  variations:[
    {title:{en:'With coconut milk', no:'Med kokosmelk'},
     body:{en:'Replace a third of the water with thin coconut milk. The dosa comes out softer and faintly sweet, and it suits a sharp fish curry better than the plain one does.',
           no:'Bytt ut en tredel av vannet med tynn kokosmelk. Dosaen blir mykere og svakt søt, og den passer bedre til en syrlig fiskekarri enn den vanlige gjør.'}},
    {title:{en:'Sweet, for children', no:'Søt, til barna'},
     body:{en:'Fold the dosa around grated coconut mixed with crumbled jaggery and a pinch of cardamom. This is the standard afternoon version on the coast and it uses the same batter.',
           no:'Brett dosaen rundt revet kokos blandet med smuldret jaggery og en klype kardemomme. Slik spises den vanligvis om ettermiddagen ved kysten, og den lages av den samme røren.'}},
    {title:{en:'With kori gassi', no:'Med kori gassi'},
     body:{en:'The classic pairing is a Mangalorean chicken curry built on coconut roasted dark with Byadgi chilli and coriander. The neutral, soft dosa exists to carry a gravy that strong.',
           no:'Den klassiske kombinasjonen er en kyllingkarri fra Mangaluru med en saus bygd på kokos som er ristet mørk sammen med byadgichili og koriander. Den nøytrale og myke dosaen er laget for å bære en så kraftig saus.'}}]
},

{
  id:'ragi-mudde', dish:'Ragi mudde', course:'main', lesson:2, serves:4, veg:true,
  time:{prep:10, cook:35}, hero:'ragi-mudde', tags:['millet','saaru','interior'],
  title:{en:'Ragi mudde, with a greens saaru', no:'Ragi mudde, med saaru av bladgrønnsaker'},
  blurb:{en:'A ball of stiff finger-millet dough with a thin peppery stew, eaten in lumps that are swallowed rather than chewed.',
         no:'En ball av stiv deig av fingerhirse med en tynn, pepret kraft, spist i klumper som svelges i stedet for å tygges.'},
  heroCaption:{en:'One ball a person, and a bowl of saaru thin enough to pour. The saaru is the meal; the ball carries it.',
               no:'Én ball per person og en skål saaru som er tynn nok til å helles. Saaruen er selve måltidet, og ballen bærer den.'},
  goesWith:[{en:'Buttermilk seasoned with curry leaf and ginger', no:'Kjernemelk krydret med karriblad og ingefær'},
            {en:'A dry vegetable palya on the side', no:'En tørr palya av grønnsaker ved siden av'}],
  headnote:{
    en:`<p>This is the dish the region sheet opens with, and it is the staple of the dry districts of the Karnataka interior. Finger millet is milled whole, bran and all, so the flour is brown; cooked with water into a stiff dough it goes a deep purple-grey. It is shaped into a ball while it is still almost too hot to handle.</p>
<p>You do not chew it. A walnut-sized lump is pinched off, dented with the thumb, rolled through the saaru until it is coated, and swallowed whole. That is not a quirk to be indulged: chewed ragi dough turns into a sticky paste that clings to the roof of the mouth and tastes of very little, while a coated lump goes down carrying the flavour of the liquid with it. It also means the saaru has to be genuinely thin, because it has to run into the dough rather than sit on it.</p>
<p>The proportion of flour to water is the only real variable, and it is worth getting close first time. Too much water and the ball will not hold; too little and it is dry and crumbly. Start at the ratio below, and remember that the dough firms up noticeably in the two minutes after it leaves the pot.</p>`,
    no:`<p>Dette er retten regionsiden åpner med, og den er hverdagsmaten i de tørre distriktene i innlandet i Karnataka. Fingerhirse males hel, med kli og alt, så melet er brunt, og kokes det med vann til en stiv deig, blir den dypt gråfiolett. Den formes til en ball mens den ennå er nesten for varm til å holde i.</p>
<p>Du tygger den ikke. En klump på størrelse med en valnøtt klypes av, får en grop med tommelen, rulles gjennom saaruen til den er dekket, og svelges hel. Dette er ikke en særhet du bare må finne deg i. Tygd deig av ragi blir en klebrig masse som setter seg i ganen og smaker svært lite, mens en klump som er dekket av saaru, glir ned og tar smaken av væsken med seg. Det betyr også at saaruen må være virkelig tynn, for den skal renne inn i deigen og ikke bli liggende oppå.</p>
<p>Forholdet mellom mel og vann er den eneste virkelige variabelen, og det lønner seg å treffe nokså godt første gang. Med for mye vann holder ballen ikke sammen, og med for lite blir den tørr og smuldrete. Begynn med forholdet nedenfor, og husk at deigen stivner merkbart de to første minuttene etter at den er tatt ut av gryten.</p>`},
  ingredients:[
   {group:{en:'The mudde', no:'Mudde'}, items:[
    {q:240, u:'g', n:{en:'ragi flour', no:'ragimel'}, note:{en:'plain finger millet flour, not a malted drink powder', no:'rent mel av fingerhirse, ikke maltet drikkepulver'}},
    {q:900, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The greens saaru', no:'Saaru av bladgrønnsaker'}, items:[
    {q:120, u:'g', n:{en:'toor dal', no:'toor dal'}},
    {q:900, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:200, u:'g', n:{en:'spinach or amaranth leaves', no:'spinat eller amarantblader'}, note:{en:'washed and roughly chopped', no:'vasket og grovhakket'}},
    {q:25, u:'g', n:{en:'tamarind pulp', no:'tamarindmasse'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'snittet på langs'}},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:3, u:'g', n:{en:'black pepper', no:'svart pepper'}, note:{en:'coarsely crushed', no:'grovt knust'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The tempering', no:'Temperingen'}, items:[
    {q:20, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:4, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:4, u:'g', n:{en:'cumin seed', no:'spisskummenfrø'}},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblader'}},
    {q:2, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
   ]}],
  steps:[
    {en:'Cook the toor dal in the water until it collapses entirely, then whisk it smooth.',
     no:'Kok toor dalen i vannet til den faller helt sammen, og visp den så glatt.'},
    {en:'Add the chopped greens, the green chillies, the turmeric, the crushed pepper and salt, and simmer for five minutes until the leaves are soft.',
     no:'Ha i de hakkede bladene, de grønne chiliene, gurkemeien, den knuste pepperen og salt, og la det småkoke i fem minutter til bladene er myke.'},
    {en:'Soak the tamarind in hot water, squeeze it out, strain it into the pot and let it boil once. Thin the saaru with hot water until it pours like a soup rather than a sauce.',
     no:'Bløtlegg tamarinden i varmt vann, klem den ut, sil væsken ned i gryten og la det koke opp én gang. Spe saaruen med varmt vann til den renner som en suppe og ikke som en saus.'},
    {en:'Heat the ghee in a small pan, add the mustard seed, and when it pops add the cumin, the broken dried chillies and the curry leaves. Pour it over the saaru and put a lid on.',
     no:'Varm gheen i en liten panne, ha i sennepsfrøene, og når de spretter, ha i spisskummenen, de brukne tørkede chiliene og karribladene. Hell det over saaruen og legg på lokk.'},
    {en:'Bring the water for the mudde to the boil in a heavy pot with a little salt.',
     no:'Kok opp vannet til mudde i en tung gryte med litt salt i.'},
    {en:'Slake a small handful of the ragi flour in cold water and stir that into the boiling water. Let it thicken for a minute, which is what stops the rest from lumping.',
     no:'Rør ut en liten neve av ragimelet i kaldt vann og rør blandingen inn i det kokende vannet. La det tykne i ett minutt, og det er nettopp det som hindrer resten i å klumpe seg.'},
    {en:'Tip the rest of the flour in as one heap in the middle, turn the heat right down, cover, and leave it alone for two minutes so the flour hydrates.',
     no:'Hell resten av melet i som én haug midt i gryten, skru varmen helt ned, legg på lokk, og la det stå i fred i to minutter så melet trekker til seg vann.'},
    {en:'Now work it. Press the dough against the side of the pot with a wooden stick or the handle of a spoon and turn it over on itself, again and again, until no dry flour is left and the mass pulls cleanly away from the pot.',
     no:'Nå skal du arbeide deigen. Press den mot gryteveggen med en trepinne eller skaftet på en sleiv og brett den over seg selv, om og om igjen, til det ikke er tørt mel igjen og massen slipper gryten rent.'},
    {en:'Wet your hands and a bowl in cold water, lift out a portion and roll it into a smooth ball. Repeat for each person and keep the balls covered.',
     no:'Fukt hendene og en bolle i kaldt vann, løft ut en porsjon og rull den til en glatt ball. Gjenta for hver person, og hold ballene tildekket.'},
    {en:'Serve one ball each with a bowl of the hot saaru. Pinch off a lump, dent it with your thumb, roll it through the saaru and swallow it whole.',
     no:'Server én ball til hver med en skål varm saaru. Klyp av en klump, trykk en grop i den med tommelen, rull den gjennom saaruen og svelg den hel.'},
  ],
  notes:[
    {title:{en:'Why the first handful is slaked in cold water', no:'Hvorfor den første neven røres ut i kaldt vann'},
     body:{en:'Ragi flour is very fine and hydrates instantly, so flour tipped straight into boiling water seizes on the outside of each lump and stays raw inside. A thin slurry stirred in first thickens the water slightly, and the rest of the flour then meets a liquid it cannot flash-set against.',
           no:'Ragimel er svært fint og trekker til seg vann med én gang, så mel som helles rett i kokende vann, stivner på utsiden av hver klump og blir rått inni. Rører du inn en tynn utrøring først, tykner vannet litt, og resten av melet møter da en væske det ikke kan stivne mot i samme øyeblikk.'}},
    {title:{en:'Why the saaru has to be thin', no:'Hvorfor saaruen må være tynn'},
     body:{en:'The lump is swallowed, so everything you are going to taste has to be on the outside of it when it goes down. A thick stew coats the lump in a layer that barely registers; a thin one soaks into the dented surface and carries. If your saaru holds its shape on a spoon, add water until it does not.',
           no:'Klumpen svelges, så alt du skal smake, må ligge utenpå den når den går ned. En tykk saaru legger seg som et lag du knapt merker, mens en tynn trekker inn i den gropete overflaten og bærer smaken. Holder saaruen formen på en skje, spe den med vann til den ikke gjør det.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Indian shops in Oslo sell ragi flour under ragi, nachni or finger millet flour. Buy the plain flour and not ragi malt, which is sprouted and sweetened for a drink and will not make a dough. Whole millet flour carries its own oil and goes rancid within a few months, so buy a small bag and keep it in the freezer. Spinach stands in perfectly for the amaranth leaves used at home.',
           no:'Indiske butikker i Oslo selger ragimel under navnene ragi, nachni eller finger millet flour. Kjøp det rene melet og ikke ragi malt, som er spiret og søtet til drikke og ikke lar seg koke til deig. Mel av hele hirsekorn har sin egen olje i seg og harskner i løpet av noen måneder, så kjøp en liten pose og oppbevar den i fryseren. Spinat er en utmerket erstatning for amarantbladene som brukes i India.'}}],
  variations:[
    {title:{en:'Half rice, half ragi', no:'Halvt ris, halvt ragi'},
     body:{en:'Cook a handful of rice in the water first and mash it before the flour goes in. The ball comes out softer and less dense, which is how it is made for children and for anybody meeting it for the first time.',
           no:'Kok en neve ris i vannet først og mos den før melet går i. Ballen blir mykere og mindre tett, og slik lages den til barn og til alle som møter retten for første gang.'}},
    {title:{en:'Bassaru instead', no:'Bassaru i stedet'},
     body:{en:'Boil the greens and the dal together, then drain them and keep the water. Season the water as the saaru, and fry the drained solids with grated coconut, onion and chilli into a dry side dish. One pot, two dishes, and nothing thrown away.',
           no:'Kok bladgrønnsakene og dalen sammen, sil dem av og ta vare på vannet. Krydre vannet som saaru, og stek det avsilte med revet kokos, løk og chili til en tørr siderett. Du får to retter av én gryte, og ingenting kastes.'}},
    {title:{en:'With buttermilk at the end', no:'Med kjernemelk til slutt'},
     body:{en:'Thin buttermilk with cold water and season it with crushed curry leaf, green chilli, grated ginger and salt. In the dry interior this closes the meal and cools the mouth after the pepper.',
           no:'Spe kjernemelk med kaldt vann og smak den til med knuste karriblader, grønn chili, revet ingefær og salt. I det tørre innlandet avslutter dette måltidet og kjøler munnen etter pepperen.'}}]
},

{
  id:'mysore-masala-dosa', dish:'Mysore masala dosa', course:'breakfast', lesson:3, serves:4, veg:true,
  time:{prep:40, cook:30}, hero:'mysore-dosa', tags:['dosa','chutney','potato'],
  title:{en:'Mysore masala dosa', no:'Mysore masala dosa'},
  blurb:{en:'The fermented dosa of the south with a raw red chilli and garlic chutney spread inside it before the potato goes in.',
         no:'Den gjærede dosaen fra sør med en rå rød chutney av chili og hvitløk smurt inni før poteten går i.'},
  heroCaption:{en:'The red layer sits between the crisp face and the soft potato, so the first bite is hot before the potato arrives.',
               no:'Det røde laget ligger mellom den sprø flaten og den myke poteten, så første bit er sterk før poteten kommer.'},
  goesWith:[{en:'Coconut chutney and a bowl of sambar', no:'Kokoschutney og en skål sambar'},
            {en:'Filter coffee afterwards', no:'Filterkaffe etterpå'}],
  headnote:{
    en:`<p>The batter is not what makes this dish. Rice and urad dal ground separately and left overnight is the common inheritance of the whole south, and Tamil Nadu's module sets out why urad is the only lentil that will trap the gas and why the rice is parboiled. Karnataka uses the same batter, and nobody here claims otherwise.</p>
<p>What Mysore adds is a smear of raw chutney. Byadgi chillies are soaked soft and ground with garlic, roasted gram and a little coconut into a thick red paste, and a spoonful of it goes onto the dosa on the griddle as soon as the batter has set, before the potato. Butter goes on rather than oil. When the dosa is folded, the chilli is sealed between the crisp surface and the soft filling, and you meet it in the first bite whether you meant to or not.</p>
<p>That is the whole difference, and it is a real one. A plain masala dosa is deliberately mild and leaves the heat to the chutney in the bowl beside it. This version makes the decision for you and puts it somewhere you cannot scrape it off.</p>`,
    no:`<p>Det særegne ved denne retten ligger ikke i røren. Røre av ris og urad dal som males hver for seg og står over natten, er felleseie i hele sør, og modulen om Tamil Nadu forklarer hvorfor urad er den eneste linsen som fanger gassen, og hvorfor risen er parboiled. Karnataka bruker den samme røren, og ingen her påstår noe annet.</p>
<p>Mysore legger til et strøk rå chutney. Byadgichilier bløtlegges til de er myke og males med hvitløk, ristet chana dal og litt kokos til en tykk rød masse, og en skje av den går på dosaen mens den ligger på takken, så snart røren har stivnet og før poteten. Kokken bruker smør og ikke olje. Når dosaen brettes, blir chilien forseglet mellom den sprø flaten og det myke fyllet, og du møter den i første bit enten du ville det eller ikke.</p>
<p>Der ligger hele forskjellen, og den er reell. En vanlig masala dosa er mild med vilje og overlater styrken til chutneyen i skålen ved siden av. Denne utgaven tar avgjørelsen for deg og legger den et sted du ikke får skrapt den av.</p>`},
  ingredients:[
   {group:{en:'The batter', no:'Røren'}, items:[
    {q:400, u:'g', n:{en:'parboiled idli rice', no:'parboiled idliris'}},
    {q:100, u:'g', n:{en:'urad dal', no:'urad dal'}, note:{en:'skinned and split, the white kind', no:'skrellet og splittet, den hvite typen'}},
    {q:5, u:'g', n:{en:'fenugreek seed', no:'bukkehornkløverfrø'}},
    {q:500, u:'ml', n:{en:'water', no:'vann'}, scale:'sub', note:{en:'cold, for grinding', no:'kaldt, til malingen'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The red chutney', no:'Den røde chutneyen'}, items:[
    {q:12, u:'', n:{en:'dried Byadgi chillies', no:'tørkede byadgichilier'}, round:'half'},
    {q:30, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:25, u:'g', n:{en:'roasted chana dal', no:'ristet chana dal'}, note:{en:'sold as putani or pottukadalai', no:'selges som putani eller pottukadalai'}},
    {q:25, u:'g', n:{en:'fresh grated coconut', no:'fersk revet kokos'}},
    {q:10, u:'g', n:{en:'tamarind pulp', no:'tamarindmasse'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The potato palya', no:'Potetpalya'}, items:[
    {q:600, u:'g', n:{en:'floury potatoes', no:'melne poteter'}},
    {q:150, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'skåret i tynne skiver'}},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:5, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:12, u:'', n:{en:'curry leaves', no:'karriblader'}},
    {q:25, u:'ml', n:{en:'oil', no:'olje'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'To cook', no:'Til steking'}, items:[
    {q:80, u:'g', n:{en:'butter', no:'smør'}},
   ]}],
  steps:[
    {en:'Rinse the rice and soak it in one bowl. Soak the urad dal and the fenugreek in another. Leave both for five hours.',
     no:'Skyll risen og legg den i bløt i én bolle. Legg urad dalen og bukkehornkløveren i bløt i en annen. La begge stå i fem timer.'},
    {en:'Grind the dal first with cold water until it is white, light and doubled in volume. Then grind the rice until it is fine but still faintly gritty between the fingers.',
     no:'Mal dalen først med kaldt vann til den er hvit, luftig og dobbelt så stor. Mal så risen til den er fin, men fortsatt så vidt kornete mellom fingrene.'},
    {en:'Fold the two together by hand with salt, cover, and leave in a warm place for eight to twelve hours until the batter has risen and smells pleasantly sour.',
     no:'Bland de to sammen for hånd med salt, dekk til, og la det stå lunt i åtte til tolv timer til røren har hevet seg og lukter behagelig surt.'},
    {en:'For the chutney, soak the chillies in hot water until they are soft, then grind them with the garlic, the roasted chana dal, the coconut, the tamarind, salt and as little water as will move the blades. It should be thick enough to spread.',
     no:'Til chutneyen bløtlegger du chiliene i varmt vann til de er myke, og maler dem så med hvitløken, den ristede chana dalen, kokosen, tamarinden, salt og så lite vann at knivene akkurat går rundt. Den skal være tykk nok til å smøres.'},
    {en:'Boil the potatoes in their skins, peel them while warm and crush them coarsely. Leave some lumps.',
     no:'Kok potetene med skallet på, skrell dem mens de er varme og mos dem grovt. La det være igjen noen klumper.'},
    {en:'Heat the oil, pop the mustard seed, then add the curry leaves, the sliced onion and the green chilli and cook until the onion is soft and sweet. Stir in the turmeric.',
     no:'Varm oljen, la sennepsfrøene sprette, og ha så i karribladene, løken i skiver og den grønne chilien, og stek til løken er myk og søt. Rør inn gurkemeien.'},
    {en:'Add the crushed potato, salt and a splash of hot water, and turn it over until it is moist and holds together. Keep it warm.',
     no:'Ha i den mosede poteten, salt og en skvett varmt vann, og vend det til det er fuktig og henger sammen. Hold det varmt.'},
    {en:'Heat a flat griddle until a drop of water skitters across it. Rub it with half an onion dipped in oil, which seasons it and stops the first dosa sticking.',
     no:'Varm en flat takke til en vanndråpe danser over den. Gni den med en halv løk dyppet i olje, som både gir takken en tynn fettfilm og hindrer at den første dosaen setter seg fast.'},
    {en:'Pour a ladle of batter in the middle and spread it outwards in a widening spiral with the back of the ladle. Dot butter around the edge.',
     no:'Hell en sleiv røre midt på og bre den utover i en voksende spiral med baksiden av sleiven. Legg smørklatter langs kanten.'},
    {en:'As soon as the surface has set, spread a spoonful of the red chutney across it, then lay the potato along the middle.',
     no:'Så snart overflaten har stivnet, smører du en skje av den røde chutneyen utover den, og legger så poteten langs midten.'},
    {en:'Cook until the underside is deep brown and the edges lift by themselves, fold the dosa over the filling, and serve it immediately.',
     no:'Stek til undersiden er dypt brun og kantene løsner av seg selv, brett dosaen over fyllet, og server den med én gang.'},
  ],
  notes:[
    {title:{en:'Why the chutney goes on before the potato', no:'Hvorfor chutneyen går på før poteten'},
     body:{en:'Spread on the hot batter, the chutney loses its raw edge in a few seconds and glues itself to the dosa, so it stays where it was put when the dosa is folded and lifted. Served alongside instead, it is a condiment you can avoid. Inside, it is part of the structure of the dish.',
           no:'Når chutneyen smøres på den varme røren, mister den den rå smaken på noen sekunder og fester seg til dosaen, så den blir liggende der den ble lagt når dosaen brettes og løftes. Serveres den ved siden av, er den et tilbehør du kan styre unna. Inni er den en del av selve retten.'}},
    {title:{en:'Why this batter is spread and the coastal one is poured', no:'Hvorfor denne røren bres ut og den fra kysten helles'},
     body:{en:'A fermented batter is thick and full of gas, so it holds the track of the ladle and browns into a sheet that can be folded without tearing. Neer dosa batter is water-thin and would tear under the same treatment. The two are cooked by opposite methods because they are built on opposite principles.',
           no:'En gjæret røre er tykk og full av gass, så den holder på sporet etter sleiven og brunes til et ark som kan brettes uten å revne. Røren til neer dosa er tynn som vann og ville revnet av samme behandling. De to stekes på motsatt måte fordi de bygger på motsatte prinsipper.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy parboiled idli rice and white skinned urad dal in an Indian shop, and do not substitute either; risotto rice and whole black urad both fail. Roasted chana dal is sold as putani or pottukadalai and is not the same as raw chana dal. For the fermentation, a Norwegian kitchen in winter is too cold: put the bowl in the oven with only the light on, or in a switched-off oven beside a roasting tin of hot water, and give it twelve hours rather than eight.',
           no:'Kjøp parboiled idliris og hvit skrellet urad dal i en indisk butikk, og ikke bytt ut noen av dem; med risottoris eller hel svart urad mislykkes røren. Ristet chana dal selges som putani eller pottukadalai og er ikke det samme som rå chana dal. Et norsk kjøkken er for kaldt om vinteren til at røren gjærer skikkelig. Sett bollen i stekeovnen med bare lyset på, eller i en avslått ovn ved siden av en langpanne med varmt vann, og gi den tolv timer heller enn åtte.'}}],
  variations:[
    {title:{en:'Benne dosa', no:'Benne dosa'},
     body:{en:'Davanagere in the middle of the state makes the same dosa with a great deal more butter and a softer, thicker batter. Benne is butter in Kannada, and the dosa comes off the griddle pale and rich rather than dark and crisp.',
           no:'I Davanagere midt i staten lages den samme dosaen med langt mer smør og en mykere og tykkere røre. Benne betyr smør på kannada, og dosaen kommer av takken lys og fyldig i stedet for mørk og sprø.'}},
    {title:{en:'Without a wet grinder', no:'Uten steinkvern'},
     body:{en:'A blender works if you keep the batter cold and grind in short bursts with iced water, stopping whenever the jug feels warm. Heat kills the bacteria that do the fermenting, and a batter ground warm never rises properly.',
           no:'En blender fungerer om du holder røren kald og maler i korte støt med iskaldt vann, og stopper hver gang kannen kjennes varm. Varme tar livet av bakteriene som står for gjæringen, og en røre som males varm, hever aldri ordentlig.'}},
    {title:{en:'The chutney on its own', no:'Chutneyen alene'},
     body:{en:'It keeps for a week in the fridge and is worth making in a larger batch. It goes on an idli, into a sandwich, or under an egg, and it is the single most useful thing in this recipe.',
           no:'Den holder seg en uke i kjøleskapet og er verdt å lage i en større porsjon. Den går på en idli, i en sandwich eller under et egg, og den er det mest anvendelige i hele denne oppskriften.'}}]
},

{
  id:'pandi-curry', dish:'Pandi curry', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:25, cook:95}, hero:'pandi-curry', tags:['pork','kodagu','sour'],
  title:{en:'Pandi curry, and what to do without kachampuli', no:'Pandi curry, og hva du gjør uten kachampuli'},
  blurb:{en:'Pork from Kodagu cooked in its own fat with a coarse home-ground masala and soured almost black at the end.',
         no:'Svinekjøtt fra Kodagu kokt i sitt eget fett med en grov, hjemmemalt masala og syrnet nesten svart til slutt.'},
  heroCaption:{en:'The fat is left on and cooked until it is soft. The colour deepens with every spoonful of souring that goes in.',
               no:'Fettet får sitte på og kokes til det er mykt. Fargen blir dypere for hver skje syrningsmiddel som går i.'},
  goesWith:[{en:'Steamed rice, or kadambuttu if you make them', no:'Dampet ris, eller kadambuttu om du lager dem'},
            {en:'A plain cucumber salad to cut the fat', no:'En enkel agurksalat som skjærer gjennom fettet'}],
  headnote:{
    en:`<p>Start with the honest part. Kachampuli is not sold in Norway and is difficult to order from here, and it is the ingredient that makes this dish look and taste the way it does. So what follows is not quite pandi curry. It is what a Norwegian kitchen can honestly borrow from it, with tamarind concentrate and a little dark treacle standing in for the syrup. You get the sourness. You do not get the smoke or the black colour, and it is better to know that than to be disappointed.</p>
<p>Everything else travels intact. Pandi curry belongs to the Kodava of Kodagu, the hill district on the western edge of Karnataka, and it is pork cut into large cubes with the skin and fat left on. Almost no oil goes into the pan. The meat is covered and left to render, then browned in what it has given up, and the masala is ground coarse at home rather than bought.</p>
<p>The one rule that matters is the order. The souring goes in at the end, off the boil, a spoonful at a time. Put it in early and it cooks away, taking the colour with it; put too much in at once and the dish is nothing but sour. Taste between spoonfuls and stop while you still want more.</p>`,
    no:`<p>Først det ærlige. Kachampuli selges ikke i Norge og er vanskelig å bestille herfra, og det er nettopp den ingrediensen som gir retten både utseendet og smaken sin. Så det som følger, er ikke helt pandi curry. Det er det et norsk kjøkken ærlig kan låne fra retten, med tamarindkonsentrat og litt mørk sirup i stedet for sirupen fra Kodagu. Du får syrligheten. Du får verken røyken eller den svarte fargen, og det er bedre å vite det enn å bli skuffet.</p>
<p>Resten lar seg overføre uten endringer. Pandi curry hører til kodavaene i Kodagu, åsdistriktet helt vest i Karnataka, og retten består av svinekjøtt som skjæres i store terninger med svor og fett på. Det går nesten ingen olje i pannen. Kjøttet legges under lokk og får smelte ut fettet sitt, brunes så i det det selv har gitt fra seg, og masalaen males grovt hjemme i stedet for å kjøpes.</p>
<p>Bare én regel betyr noe, og den gjelder rekkefølgen. Syrningsmiddelet går i til slutt, uten fosskoking, en skje om gangen. Går den i tidlig, koker den bort og tar fargen med seg; går det for mye i på én gang, blir retten bare sur. Smak mellom hver skje, og stopp mens du fortsatt vil ha mer.</p>`},
  ingredients:[
   {group:{en:'The meat', no:'Kjøttet'}, items:[
    {q:1, u:'kg', n:{en:'pork belly, rind on', no:'sideflesk med svor'}, note:{en:'in cubes of about four centimetres', no:'i terninger på omtrent fire centimeter'}},
    {q:5, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The masala', no:'Masalaen'}, items:[
    {q:15, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:6, u:'g', n:{en:'black peppercorns', no:'hele pepperkorn'}},
    {q:4, u:'g', n:{en:'cumin seed', no:'spisskummenfrø'}},
    {q:3, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:8, u:'', n:{en:'dried Byadgi chillies', no:'tørkede byadgichilier'}, round:'half'},
    {q:2, u:'', n:{en:'black cardamom pods', no:'kapsler svart kardemomme'}, round:'half'},
   ]},
   {group:{en:'The pot', no:'Gryten'}, items:[
    {q:250, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced', no:'i skiver'}},
    {q:30, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:30, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:15, u:'', n:{en:'curry leaves', no:'karriblader'}},
    {q:20, u:'ml', n:{en:'oil', no:'olje'}, note:{en:'only if the pot runs dry', no:'bare om gryten blir tørr'}},
    {q:250, u:'ml', n:{en:'hot water', no:'varmt vann'}, scale:'sub'},
    {q:25, u:'ml', n:{en:'kachampuli', no:'kachampuli'}, note:{en:'or tamarind concentrate with a little dark treacle', no:'eller tamarindkonsentrat med litt mørk sirup i'}},
   ]}],
  steps:[
    {en:'Rub the pork with the turmeric and salt and leave it while you grind the masala.',
     no:'Gni svinekjøttet inn med gurkemeien og saltet, og la det ligge mens du maler masalaen.'},
    {en:'Toast the coriander, peppercorns, cumin, mustard seed, chillies and cardamom in a dry pan over a low flame until they darken a shade and smell toasted. Grind them coarse, not fine.',
     no:'Rist koriander, pepperkorn, spisskummen, sennepsfrø, chili og kardemomme i en tørr panne på svak varme til de blir en nyanse mørkere og lukter ristet. Mal dem grovt, ikke fint.'},
    {en:'Put the pork in a heavy pot over a medium flame with no oil and no water. Cover it and let it cook in its own fat for twenty minutes, turning it now and then.',
     no:'Legg svinekjøttet i en tung gryte på middels varme, uten olje og uten vann. Legg på lokk og la det koke i sitt eget fett i tjue minutter, og vend på det innimellom.'},
    {en:'Take the lid off and let the liquid it has given up boil away, then keep going until the meat starts to brown in the rendered fat.',
     no:'Ta av lokket og la væsken det har gitt fra seg, koke inn, og fortsett så til kjøttet begynner å brune seg i det utsmeltede fettet.'},
    {en:'Push the meat to one side. Add the oil only if the pot looks dry, then the onion, garlic, ginger, green chilli and curry leaves, and fry until the onion is properly brown.',
     no:'Skyv kjøttet til side. Ha i oljen bare om gryten ser tørr ut, og så løken, hvitløken, ingefæren, den grønne chilien og karribladene, og stek til løken er ordentlig brun.'},
    {en:'Stir in the ground masala and cook it for two minutes, so it loses its raw edge without catching.',
     no:'Rør inn den malte masalaen og stek den i to minutter, så den mister den rå smaken uten å svi seg.'},
    {en:'Pour in the hot water, scrape the base clean, cover, and simmer very gently for an hour. The fat should be soft and a knife should meet no resistance.',
     no:'Hell i det varme vannet, skrap bunnen ren, legg på lokk, og la det småkoke svært rolig i en time. Fettet skal være mykt, og en kniv skal ikke møte motstand.'},
    {en:'Take the lid off and reduce the gravy until it clings to the meat rather than pooling around it.',
     no:'Ta av lokket og kok inn sausen til den kleber seg til kjøttet i stedet for å samle seg i bunnen.'},
    {en:'Off the heat, stir in the souring a little at a time, tasting between each addition. The gravy darkens as it goes in. Correct the salt last.',
     no:'Ta gryten av platen og rør inn syrningsmiddelet litt om gangen, og smak mellom hver gang. Sausen mørkner mens den går i. Juster saltet helt til slutt.'},
    {en:'Let it stand covered for at least ten minutes before serving, and reheat it the next day if you can, because it is better then.',
     no:'La den stå tildekket i minst ti minutter før servering, og spar den gjerne til dagen etter og varm den opp, for da er den bedre.'},
  ],
  notes:[
    {title:{en:'Why there is almost no oil', no:'Hvorfor det nesten ikke går olje i'},
     body:{en:'Belly pork is about a third fat, and covering it at the start renders that fat out before anything browns. Everything that follows is then fried in pork fat rather than vegetable oil, which is where most of the flavour of the finished dish comes from. Adding oil at the start would only make it greasy.',
           no:'Sideflesk er omtrent en tredel fett, og legger du lokk på i starten, smelter det fettet ut før noe brunes. Alt som kommer etterpå, stekes da i svinefett og ikke i planteolje, og derfra kommer det meste av smaken i den ferdige retten. Olje i starten ville bare gjort den fet.'}},
    {title:{en:'Why the souring goes in last and off the heat', no:'Hvorfor syrningsmiddelet går i sist og med gryten av platen'},
     body:{en:'Kachampuli is a reduced juice, and both its aroma and its colour are volatile. Boiled, it turns into ordinary sourness and the gravy goes a flat brown. Stirred in off the heat it keeps what it has, and it also lets you taste your way to the right amount instead of committing at the start.',
           no:'Kachampuli er inndampet saft, og både duften og fargen er flyktige. Kokes den, blir den til alminnelig syrlighet, og sausen blir matt brun. Røres den inn med gryten av platen, beholder den det den har, og du får dessuten smake deg fram til riktig mengde i stedet for å bestemme alt i starten.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Ask the butcher for ribbe or sideflesk with the rind on and have it cut into cubes; the dish depends on the fat rendering out, so belly rather than loin is not optional here. For the souring, mix tamarind concentrate with a little dark syrup or treacle until it is thick and almost black, and use it spoon for spoon. Black cardamom and whole Byadgi chillies come from Indian shops; ordinary supermarket chilli powder is a blend and will not do.',
           no:'Be slakteren om ribbe eller sideflesk med svoren på og få det skåret i terninger; retten er avhengig av at fettet smelter ut, så sideflesk framfor kotelettkam er ikke valgfritt her. Til syren blander du tamarindkonsentrat med litt mørk sirup til blandingen er tykk og nesten svart, og bruker den skje for skje. Svart kardemomme og hele byadgichilier får du i indiske butikker; vanlig chilipulver fra dagligvarebutikken er en blanding og duger ikke.'}}],
  variations:[
    {title:{en:'Made a day ahead', no:'Laget dagen før'},
     body:{en:'Cook it to the end of the simmer, cool it and refrigerate it overnight. Lift off the set fat if it looks like too much, reheat gently, reduce and then sour it. The meat is better for the rest and the dish is easier to serve.',
           no:'Kok den til den har småkokt ferdig, avkjøl den og sett den kaldt over natten. Løft av det stivnede fettet om det ser ut som for mye, varm den forsiktig opp igjen, kok den inn og syrne den til slutt. Kjøttet har godt av hvilen, og retten blir enklere å servere.'}},
    {title:{en:'Milder, for a mixed table', no:'Mildere, til et blandet bord'},
     body:{en:'Halve the black peppercorns and leave the green chillies whole and unslit. Byadgi carries the colour without much heat, so the dish stays red and looks exactly the same.',
           no:'Halver mengden pepperkorn og la de grønne chiliene være hele, uten å snitte dem. Byadgi bærer fargen uten særlig styrke, så retten holder seg rød og ser helt lik ut.'}},
    {title:{en:'With kadambuttu', no:'Med kadambuttu'},
     body:{en:'The Kodava eat this with steamed balls of coarsely broken rice. Cook broken rice into a thick porridge, roll it into balls with wet hands and steam them for ten minutes. They are bland on purpose, which is what the gravy needs.',
           no:'Kodavaene spiser dette med dampede baller av grovt knust ris. Kok knust ris til en tykk grøt, rull den til baller med våte hender og damp dem i ti minutter. De er smaksnøytrale med vilje, og det er nettopp det sausen trenger.'}}]
},

];
