/* Masala Dabba — recipes for Maharashtra (IN-MAH). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-MAH'] = [

{
  id:'misal-pav', dish:'Misal pav', course:'breakfast', lesson:3, serves:4, veg:true,
  time:{prep:40, cook:60}, hero:'misal', tags:['sprouts','breakfast','chilli'],
  title:{en:'Misal pav', no:'Misal pav'},
  blurb:{en:'Sprouted beans under a crisp lid of fried savouries, with a thin red gravy poured over at the table.',
         no:'Spirte bønner under et sprøtt lag stekt snacks, med en tynn rød saus helt over ved bordet.'},
  heroCaption:{en:'Misal is served half built. The rassa goes on last, and how much you pour is your own decision.',
               no:'Misal serveres halvferdig. Rassaen kommer til slutt, og hvor mye du heller, avgjør du selv.'},
  goesWith:[{en:'Soft pav, or any bread that will mop', no:'Myke pav, eller et annet brød som kan tørke opp sausen'},
            {en:'A glass of buttermilk, for afterwards', no:'Et glass kjernemelk, til etterpå'}],
  headnote:{
    en:`<p>This version of misal brings two preparations together on the plate. Underneath is <em>usal</em>, a thick curry of sprouted moth beans that could stand on its own with a bhakri. Over it goes a separately made rassa, and between the two sits a layer of fried savouries that stays crisp until serving.</p>
<p>Almost everything here can be done in advance. The beans need two days of attention before you start, but they need about four minutes of your time across those two days. The usal and the rassa both improve overnight. Only the assembly is urgent, and it takes half a minute.</p>
<p>Decide the heat before you cook. Misal varies greatly between cities and individual shops. This recipe separates a mild chilli for colour from a hot one for heat, so you can adjust the balance without changing the gravy's body.</p>`,
    no:`<p>Denne utgaven av misal fører to tilberedninger sammen på tallerkenen. Under ligger <em>usal</em>, en tykk gryte av spirte matki-bønner som godt kunne stått alene med en bhakri. Over den kommer en rassa som lages for seg, og mellom dem ligger et lag stekt snacks som holder seg sprøtt fram til servering.</p>
<p>Nesten alt kan gjøres på forhånd. Bønnene trenger to dager, men de trenger bare omtrent fire minutter av din tid i løpet av de to dagene. Både usalen og rassaen blir bedre av å stå til dagen etter. Bare selve sammensetningen haster, og den tar et halvt minutt.</p>
<p>Bestem styrken før du begynner. Misal varierer mye mellom byer og enkeltboder. Denne oppskriften skiller et mildt chilipulver for farge fra et sterkt for hete, så balansen kan justeres uten å endre fylden i sausen.</p>`},
  ingredients:[
   {group:{en:'The sprouts', no:'Spirene'}, items:[
    {q:250, u:'g', n:{en:'matki (moth beans), dried', no:'matki (moth bean), tørkede'}, note:{en:'whole mung beans sprout the same way', no:'hele mungbønner spirer på samme måte'}},
   ]},
   {group:{en:'The roasted paste, for both gravies', no:'Den ristede massen, til begge sausene'}, items:[
    {q:60, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:250, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'i tynne skiver'}},
    {q:40, u:'g', n:{en:'dry coconut, grated', no:'tørket kokos, revet'}},
    {q:20, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:20, u:'g', n:{en:'ginger', no:'ingefær'}},
   ]},
   {group:{en:'The usal', no:'Usalen'}, items:[
    {q:30, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:5, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:20, u:'', n:{en:'curry leaves', no:'karriblader'}},
    {q:15, u:'g', n:{en:'goda masala', no:'goda masala'}},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {u:'', n:{en:'asafoetida, a good pinch', no:'asafoetida, en god klype'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The rassa', no:'Rassaen'}, items:[
    {q:45, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:20, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri chilipulver'}, note:{en:'for colour', no:'for fargen'}},
    {q:8, u:'g', n:{en:'hot chilli powder', no:'sterkt chilipulver'}, note:{en:'for heat; move this number, not the other one', no:'for styrken; flytt på dette tallet, ikke på det andre'}},
    {q:1200, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
   ]},
   {group:{en:'To serve', no:'Til servering'}, items:[
    {q:8, u:'', n:{en:'pav or soft white rolls', no:'pav eller myke hvite rundstykker'}, round:'half'},
    {q:120, u:'g', n:{en:'farsan', no:'farsan'}, note:{en:'crushed chivda, sev, fried gram, or a mixture', no:'knust chivda, sev, stekte kikerter, eller en blanding'}},
    {q:120, u:'g', n:{en:'onion, finely chopped', no:'løk, finhakket'}},
    {q:2, u:'', n:{en:'limes', no:'lime'}, round:'half'},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
   ]}],
  steps:[
    {en:'Rinse the beans and soak them overnight in plenty of cold water.',
     no:'Skyll bønnene og bløtlegg dem over natta i rikelig kaldt vann.'},
    {en:'Drain them, tip them into a colander lined with a damp cloth, cover, and leave them in a warm corner for a day. They are ready when each bean has pushed out a short white sprout.',
     no:'Hell av vannet, ha bønnene i et dørslag kledd med et fuktig klede, dekk til, og la dem stå lunt et døgn. De er klare når hver bønne har skjøvet ut en kort hvit spire.'},
    {en:'Roast the grated dry coconut in a dry pan over a low flame until it is deep brown and smells nutty. Tip it out at once, or it will go on cooking.',
     no:'Rist den revne tørkede kokosen i en tørr panne på lav varme til den er mørkebrun og lukter nøtteaktig. Hell den straks ut, ellers steker den videre.'},
    {en:'Fry the sliced onion in the oil until it is genuinely brown, not golden. Grind it with the roasted coconut, the garlic and the ginger into a coarse dark paste, using a splash of water to move it.',
     no:'Stek løkskivene i oljen til de er ordentlig brune, ikke gylne. Kjør dem sammen med den ristede kokosen, hvitløken og ingefæren til en grov mørk masse, med en skvett vann så det går rundt.'},
    {en:'Make the phodni for the usal: heat the oil, add the mustard seed, and when it pops add the asafoetida, the turmeric and the curry leaves.',
     no:'Lag phodnien til usalen: varm oljen, ha i sennepsfrøene, og når de spretter, ha i asafoetidaen, gurkemeien og karribladene.'},
    {en:'Add the sprouts and salt, cover with water by two fingers, and simmer until they are soft enough to crush against the roof of your mouth. Twenty to thirty minutes, depending on the bean.',
     no:'Ha i spirene og salt, dekk med vann to fingre over, og la det småkoke til bønnene lar seg mose mot ganen. Tjue til tretti minutter, alt etter bønnen.'},
    {en:'Stir half the dark paste and the goda masala into the sprouts and cook for five more minutes. That is the usal, and it should be thick.',
     no:'Rør halvparten av den mørke massen og goda masalaen inn i spirene, og la det koke fem minutter til. Det er usalen, og den skal være tykk.'},
    {en:'For the rassa, heat the oil in a wide pan, take it off the heat and stir both chilli powders into it, so they colour the fat without catching. Return it to a low flame.',
     no:'Til rassaen varmer du oljen i en vid panne, tar den av platen og rører begge chilipulverne inn i den, så de farger fettet uten å svi seg. Sett den tilbake på lav varme.'},
    {en:'Add the rest of the dark paste, fry for three minutes, then pour in the water. Salt it, bring it to the boil and simmer for fifteen minutes.',
     no:'Ha i resten av den mørke massen, stek i tre minutter, og hell så i vannet. Salt, kok opp og la det småkoke i femten minutter.'},
    {en:'Take the pan off the heat and let it stand. A layer of red oil rises to the top, and that layer is what you want in the ladle.',
     no:'Ta pannen av platen og la den stå. Et lag rød olje legger seg på toppen, og det laget er det du vil ha i øsa.'},
    {en:'Build each plate to order: usal in a bowl, farsan heaped on top, chopped onion and coriander over that, a wedge of lime at the side and two pav. Pour the rassa over at the table.',
     no:'Sett sammen hver tallerken ved bestilling: usal i en skål, farsan i en haug oppå, hakket løk og koriander over der igjen, en limebåt ved siden av og to pav. Rassaen helles over ved bordet.'}],
  notes:[
    {title:{en:'Why the beans are sprouted', no:'Hvorfor bønnene spires'},
     body:{en:'Sprouting starts the seed breaking down its own starch, so the bean softens faster, digests more easily and tastes less flat. That matters in something eaten at eight in the morning. A bean soaked but not sprouted will cook, but it stays dense and the dish sits heavily.',
           no:'Når bønnen spirer, begynner den å bryte ned sin egen stivelse, så den blir mør fortere, er lettere å fordøye og smaker mindre flatt. Det betyr mye i noe som spises klokka åtte om morgenen. En bønne som er bløtlagt uten å spire, blir nok kokt, men den forblir tett, og retten ligger tungt.'}},
    {title:{en:'Why the rassa is made separately', no:'Hvorfor rassaen lages for seg'},
     body:{en:'A single pot would give you one dish at one strength. Two pots let the usal be thick and savoury and the rassa be thin and violent, and let each eater decide the ratio in the bowl. The red film on top is chilli oil, and it carries most of the colour, so ladle from the surface rather than stirring first.',
           no:'Én gryte ville gitt deg én rett med én styrke. To gryter lar usalen være tykk og smaksrik og rassaen tynn og brutal, og de lar hver enkelt bestemme blandingsforholdet i skåla. Den røde hinnen på toppen er chiliolje, og den bærer det meste av fargen, så øs fra overflaten i stedet for å røre om først.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Matki is sold in Indian shops as matki, moth bean or Turkish gram. Whole mung beans are the honest substitute and sprout on the same timetable.',
           no:'Matki selges i indiske butikker som matki, moth bean eller Turkish gram. Hele mungbønner er den ærlige erstatningen og spirer på samme tid. Tørket kokos skal være «kokosmasse» eller revet kopra, ikke kokosmel, som er avfettet og ikke blir brunt. Farsan står som «mixture», «chivda» eller «farsan» i indiske butikker, og en pose holder seg i uker. Pav finnes ikke her, men et mykt, litt søtt hamburgerbrød uten skorpe er nærmere enn et rundstykke fra bakeriet.'}}],
  variations:[
    {title:{en:'A hotter variation', no:'En sterkere variant'},
     body:{en:'Replace the goda masala with a hotter kala masala, increase the hot chilli powder cautiously and serve the rassa in a jug on the side. Check the blend first because strength varies by maker.',
           no:'Bytt goda masala med en sterkere kala masala, øk det sterke chilipulveret forsiktig og server rassaen i en mugge ved siden av. Smak på blandingen først, for styrken varierer mellom produsenter.'}},
    {title:{en:'A gentler variation', no:'En mildere variant'},
     body:{en:'Put a handful of soaked poha in the bowl under the usal, add a little jaggery to the usal and go lighter on the rassa. Some Pune versions use this sweeter balance.',
           no:'Legg en håndfull bløtlagt poha i skålen under usalen, ha litt jaggery i usalen og bruk mindre rassa. Enkelte utgaver fra Pune har denne søtere balansen.'}},
    {title:{en:'Usal on its own', no:'Usal alene'},
     body:{en:'Stop after the usal, skip the farsan and rassa, and eat it with bhakri and raw onion. Usal also stands on its own as a practical weekday meal.',
           no:'Stopp etter usalen, dropp farsan og rassa, og spis den med bhakri og rå løk. Usal fungerer også alene som et praktisk hverdagsmåltid.'}}]
},

{
  id:'vada-pav', dish:'Vada pav', course:'snack', lesson:3, serves:4, veg:true,
  time:{prep:35, cook:25}, hero:'vada-pav', tags:['potato','fried','street food'],
  title:{en:'Vada pav', no:'Vada pav'},
  blurb:{en:'A spiced potato ball fried in gram-flour batter, pushed into a soft roll with dry garlic chutney.',
         no:'En krydret potetball som stekes i en røre av kikertmel og presses inn i et mykt rundstykke med tørr hvitløkchutney.'},
  heroCaption:{en:'Everything in it is soft except the fried batter, which is exactly why it has to be eaten straight away.',
               no:'Alt i den er mykt bortsett fra den stekte røren, og nettopp derfor må den spises med en gang.'},
  goesWith:[{en:'A fried green chilli, salted, on the side', no:'En stekt grønn chili med salt ved siden av'},
            {en:'Strong milky tea', no:'Sterk te med mye melk'}],
  headnote:{
    en:`<p>Three things are being made here and only one of them is difficult. The potato filling is easy, the batter is easy, and the dry garlic chutney is the part people skip and should not, because without it a vada pav is a potato sandwich.</p>
<p>A widely repeated story credits Ashok Vaidya near Dadar station in the late 1960s or early 1970s, although contemporary documentation is thin and other vendors make claims. The snack's inexpensive, portable format suits station entrances and busy workplaces.</p>
<p>Time it so the vada goes into the bread hot. A vada that has been sitting steams the inside of the pav and loses the only crisp thing in the whole assembly. Frying is the last thing you do, not the first.</p>`,
    no:`<p>Her lages tre ting, og bare én av dem er vanskelig. Potetfyllet er enkelt, røren er enkel, og den tørre hvitløkchutneyen er delen folk hopper over, og det bør de ikke, for uten den er en vada pav et potetsmørbrød.</p>
<p>En mye gjentatt fortelling gir Ashok Vaidya ved Dadar stasjon æren sent på 1960-tallet eller tidlig på 1970-tallet. Samtidsdokumentasjonen er tynn, og andre selgere gjør krav på retten. Den rimelige og bærbare formen passer ved stasjonsinnganger og travle arbeidsplasser.</p>
<p>Beregn tiden så vadaen kommer varm i brødet. En vada som har stått, damper innsiden av paven og mister det eneste sprø i hele retten. Stekingen er det siste du gjør, ikke det første.</p>`},
  ingredients:[
   {group:{en:'The potato filling', no:'Potetfyllet'}, items:[
    {q:600, u:'g', n:{en:'floury potatoes', no:'melne poteter'}},
    {q:30, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:5, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:15, u:'', n:{en:'curry leaves', no:'karriblader'}},
    {q:15, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:10, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:3, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half'},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
    {u:'', n:{en:'asafoetida, a pinch', no:'asafoetida, en klype'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The dry garlic chutney', no:'Den tørre hvitløkchutneyen'}, items:[
    {q:40, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'peeled cloves, whole', no:'skrelte fedd, hele'}},
    {q:40, u:'g', n:{en:'dry coconut, grated', no:'tørket kokos, revet'}},
    {q:30, u:'g', n:{en:'roasted peanuts', no:'ristede peanøtter'}},
    {q:15, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri chilipulver'}},
   ]},
   {group:{en:'The batter, and to serve', no:'Røren, og til servering'}, items:[
    {q:150, u:'g', n:{en:'gram flour (besan)', no:'kikertmel (besan)'}},
    {q:3, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:170, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {u:'', n:{en:'bicarbonate of soda, a small pinch', no:'natron, en liten klype'}, scale:'none'},
    {u:'', n:{en:'oil for deep frying', no:'olje til frityrsteking'}, scale:'none'},
    {q:8, u:'', n:{en:'pav or soft white rolls', no:'pav eller myke hvite rundstykker'}, round:'half'},
    {q:4, u:'', n:{en:'green chillies, whole', no:'grønne chili, hele'}, round:'half'},
   ]}],
  steps:[
    {en:'Boil the potatoes whole in their skins until a knife goes through without resistance. Peel them while they are still warm and crush them coarsely with a fork. Do not make a purée.',
     no:'Kok potetene hele med skallet på til en kniv går rett gjennom. Skrell dem mens de ennå er varme og mos dem grovt med en gaffel. Ikke lag puré.'},
    {en:'Pound the ginger, garlic and green chillies together to a rough paste.',
     no:'Knus ingefær, hvitløk og grønn chili sammen til en grov masse.'},
    {en:'Heat the oil, pop the mustard seed, then add the asafoetida and the curry leaves. Add the pounded paste and fry for a minute, then take the pan off the heat and stir in the turmeric.',
     no:'Varm oljen, la sennepsfrøene sprette, og ha så i asafoetidaen og karribladene. Ha i den knuste massen og stek i ett minutt, ta så pannen av platen og rør inn gurkemeien.'},
    {en:'Fold the seasoned oil and the chopped coriander through the potato with plenty of salt. Taste it: it should be a little saltier than you think, because the bread is not seasoned. Cool it, then roll into eight balls.',
     no:'Vend den krydrede oljen og den hakkede korianderen inn i poteten med rikelig salt. Smak til: den skal være litt saltere enn du tror, for brødet er ikke smakt til. Avkjøl, og trill så åtte kuler.'},
    {en:'For the chutney, roast the garlic cloves in a dry pan until they brown in patches, then do the same with the dry coconut. Let both cool completely.',
     no:'Til chutneyen rister du hvitløksfeddene i en tørr panne til de er brune i flekker, og gjør så det samme med den tørkede kokosen. La begge deler bli helt kalde.'},
    {en:'Grind the garlic, coconut, peanuts and chilli powder with salt to a coarse dry powder. It should never turn into a paste, so pulse it and stop early.',
     no:'Mal hvitløk, kokos, peanøtter og chilipulver med salt til et grovt tørt pulver. Det skal aldri bli til en masse, så kjør i støt og stopp tidlig.'},
    {en:'Whisk the gram flour, turmeric, salt and water into a batter that coats the back of a spoon and runs off slowly. Leave it for ten minutes.',
     no:'Visp kikertmel, gurkemeie, salt og vann til en røre som legger seg på baksiden av en skje og renner langsomt av. La den stå i ti minutter.'},
    {en:'Heat the frying oil to 180 °C. Stir the bicarbonate into the batter only now, because it starts working the moment it is wet.',
     no:'Varm frityroljen til 180 °C. Rør natronet inn i røren først nå, for det begynner å virke i det øyeblikket det blir vått.'},
    {en:'Dip each potato ball, let the excess run off, and lower it into the oil. Fry three or four at a time for about four minutes, until the coating is pale gold and firm. Drain them on a rack.',
     no:'Dypp hver potetkule, la det overflødige renne av, og senk den ned i oljen. Stek tre eller fire om gangen i omtrent fire minutter, til laget er lysegyllent og fast. La dem renne av på en rist.'},
    {en:'Fry the whole green chillies in the same oil for half a minute and salt them while they are hot.',
     no:'Stek de hele grønne chiliene i den samme oljen i et halvt minutt, og salt dem mens de er varme.'},
    {en:'Split a pav almost through, dust both cut faces heavily with the chutney, push in a hot vada and press it shut. Serve at once with a chilli.',
     no:'Del en pav nesten gjennom, dryss begge snittflatene godt med chutneyen, press inn en varm vada og klem den igjen. Server straks, med en chili til.'}],
  notes:[
    {title:{en:'Why the potato is crushed and not puréed', no:'Hvorfor poteten moses og ikke pureres'},
     body:{en:'Working a hot potato smooth develops its starch into something gluey, and a gluey filling steams inside the batter instead of staying light. A fork and eight seconds is the whole technique. Lumps are correct.',
           no:'Jobber du en varm potet glatt, utvikler stivelsen seg til noe klistrete, og et klistrete fyll damper inne i røren i stedet for å holde seg lett. En gaffel og åtte sekunder er hele teknikken. Klumper er riktig.'}},
    {title:{en:'Why the chutney is dry', no:'Hvorfor chutneyen er tørr'},
     body:{en:'A wet chutney would soak the bread and the vada would slide. A dry powder of roasted garlic, coconut and chilli clings to the cut face, seasons the bread that is otherwise bland, and adds heat without adding a single drop of liquid.',
           no:'En våt chutney ville bløtt opp brødet, og vadaen ville skli. Et tørt pulver av ristet hvitløk, kokos og chili fester seg til snittflaten, smaker til brødet som ellers er nøytralt, og gir styrke uten å tilføre en eneste dråpe væske.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Use a genuinely floury potato and boil it in the skin so it does not take on water.',
           no:'Bruk en ordentlig melen potet, for eksempel Beate eller Pimpernel, og kok den med skallet på så den ikke trekker til seg vann. Kikertmel selges som besan i indiske butikker og som kikertmel i helsekostavdelingen, og de er det samme. Tørket kokos skal være «kokosmasse», ikke kokosmel. Pav finnes ikke i Norge, men et mykt hamburgerbrød er det nærmeste; et sprøtt rundstykke fra bakeriet er feil brød, for det skal ikke være noe sprøtt utenpå.'}}],
  variations:[
    {title:{en:'With green chutney too', no:'Med grønn chutney i tillegg'},
     body:{en:'Many stalls put a smear of coriander and green chilli chutney on one cut face and the dry garlic powder on the other. It makes the thing wetter and fresher, and it is how Mumbai most often serves it now.',
           no:'Mange boder smører koriander- og chilichutney på den ene snittflaten og har det tørre hvitløkpulveret på den andre. Det gjør retten våtere og friskere, og det er slik Mumbai oftest serverer den nå.'}},
    {title:{en:'Batata vada on its own', no:'Batata vada alene'},
     body:{en:'The vada without the bread, eaten hot with the dry chutney and tea, is a snack in its own right and is what the potato ball was before somebody put it in a roll.',
           no:'Vadaen uten brød, spist varm med den tørre chutneyen og te, er en rett i seg selv, og det var det potetkulen var før noen la den i et rundstykke.'}},
    {title:{en:'Fried and pressed', no:'Stekt og presset'},
     body:{en:'Butter the cut faces and press the assembled vada pav on a hot griddle for a minute a side. It is a modern stall habit rather than the original, and it rescues bread that is a day old.',
           no:'Smør snittflatene og press den ferdige vada paven på en varm takke i ett minutt på hver side. Det er en nyere vane fra gatebodene og ikke originalen, men det redder brød som er en dag gammelt.'}}]
},

{
  id:'kanda-poha', dish:'Kanda poha', course:'breakfast', lesson:3, serves:4, veg:true,
  time:{prep:15, cook:12}, hero:'kanda-poha', tags:['breakfast','quick','peanut'],
  title:{en:'Kanda poha', no:'Kanda poha'},
  blurb:{en:'Flattened rice rinsed rather than cooked, warmed through with onion, turmeric, peanuts and lime.',
         no:'Flattrykt ris som skylles i stedet for å kokes, varmet gjennom med løk, gurkemeie, peanøtter og lime.'},
  heroCaption:{en:'Poha is made in wide trays and sold through the morning. It is best served freshly heated.',
               no:'Poha lages i vide brett og selges utover morgenen. Den er best nylaget og varm.'},
  goesWith:[{en:'A wedge of lime and a spoon of sev', no:'En limebåt og en skje sev'},
            {en:'Sweet milky tea', no:'Søt te med melk'}],
  headnote:{
    en:`<p>Poha is rice that has been parboiled, flattened and dried. Thick flakes need brief rinsing or soaking and are then heated with the seasoned ingredients; exact preparation depends on their thickness.</p>
<p>The whole dish therefore turns on one judgement: how wet the flakes are when they go into the pan. Too dry and they stay hard in the middle, too wet and the pan gives you paste. The test takes a second, and once you have done it twice you will never measure anything again.</p>
<p><em>Kanda</em> means onion, and the onion is not a garnish. It is cooked soft and sweet before anything else goes in, and it does as much work as the spices. In Maharashtra this dish also names the meeting where two families size each other up with a marriage in mind, which tells you how thoroughly domestic it is.</p>`,
    no:`<p>Poha er ris som er forkokt, valset flat og tørket. Tykke flak trenger kort skylling eller bløtlegging og varmes så med de krydrede ingrediensene; den nøyaktige tilberedningen følger tykkelsen.</p>
<p>Hele retten hviler derfor på én vurdering: hvor våte flakene er når de går i pannen. For tørre, og de er harde inni; for våte, og pannen gir deg en klissen masse. Prøven tar ett sekund, og har du gjort den to ganger, måler du aldri mer.</p>
<p><em>Kanda</em> betyr løk, og løken er ingen pynt. Den stekes myk og søt før noe annet går i, og den gjør like mye av jobben som kryddene. I Maharashtra har retten også gitt navn til møtet der to familier ser hverandre an med et giftermål i tankene, og det sier hvor hjemlig den er.</p>`},
  ingredients:[
   {group:{en:'', no:''}, items:[
    {q:250, u:'g', n:{en:'thick poha (flattened rice)', no:'tykk poha (flattrykt ris)'}, note:{en:'jada poha; the thin kind dissolves', no:'jada poha; den tynne typen går i oppløsning'}},
    {q:45, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:60, u:'g', n:{en:'raw peanuts', no:'rå peanøtter'}},
    {q:5, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:20, u:'', n:{en:'curry leaves', no:'karriblader'}},
    {q:2, u:'', n:{en:'green chillies', no:'grønne chili'}, round:'half', note:{en:'slit lengthways', no:'delt på langs'}},
    {q:250, u:'g', n:{en:'onion', no:'løk'}, note:{en:'chopped small', no:'finhakket'}},
    {q:4, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:10, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:40, u:'g', n:{en:'fresh coconut, grated', no:'fersk kokos, revet'}},
    {q:1, u:'', n:{en:'lime', no:'lime'}, round:'half'},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
    {q:60, u:'g', n:{en:'sev, to finish', no:'sev, til slutt'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Put the poha in a sieve and run cold water through it, turning the flakes with your hand, until every one of them is wet. Ten seconds, no more. Leave the sieve to drain.',
     no:'Ha pohaen i en sil og la kaldt vann renne gjennom mens du vender flakene med hånda, til hvert eneste av dem er vått. Ti sekunder, ikke mer. La silen stå og renne av.'},
    {en:'After five minutes, take one flake and press it between two fingers. It should crush without resistance and without smearing. If it is hard, sprinkle a little water over and wait another five minutes.',
     no:'Etter fem minutter tar du ett flak og klemmer det mellom to fingre. Det skal mose seg uten motstand og uten å smøre seg ut. Er det hardt, drysser du litt vann over og venter fem minutter til.'},
    {en:'Stir the turmeric, the sugar and a good pinch of salt through the drained flakes with your fingers, so the colour goes on evenly before any heat is involved.',
     no:'Vend gurkemeien, sukkeret og en god klype salt inn i de avrente flakene med fingrene, så fargen fordeler seg jevnt før noe varme kommer til.'},
    {en:'Fry the peanuts in the oil over a medium flame until they darken a shade and smell roasted. Lift them out and keep them.',
     no:'Stek peanøttene i oljen på middels varme til de mørkner et hakk og lukter ristet. Løft dem ut og ta vare på dem.'},
    {en:'In the same oil, pop the mustard seed, then add the curry leaves and the slit chillies and stand back for a second.',
     no:'I den samme oljen lar du sennepsfrøene sprette, og har så i karribladene og de delte chiliene, og trekker deg unna et øyeblikk.'},
    {en:'Add the onion and cook it over a medium flame until it is soft and translucent. Do not let it brown; this dish wants sweetness, not colour.',
     no:'Ha i løken og stek den på middels varme til den er myk og gjennomskinnelig. La den ikke bli brun; denne retten vil ha sødme og ikke farge.'},
    {en:'Fold the poha in with a light hand, turning rather than stirring. Cover the pan and leave it on the lowest flame for two minutes.',
     no:'Vend pohaen forsiktig inn, med vendende bevegelser heller enn omrøring. Legg lokk på pannen og la den stå på lavest varme i to minutter.'},
    {en:'Take it off the heat. Squeeze the lime over, scatter the coriander, the coconut and the fried peanuts, and fold once.',
     no:'Ta pannen av platen. Press limen over, strø over koriander, kokos og de stekte peanøttene, og vend én gang.'},
    {en:'Serve straight away with sev on top. It will not wait, and it will not reheat.',
     no:'Server med en gang, med sev over. Den venter ikke, og den lar seg ikke varme opp igjen.'}],
  notes:[
    {title:{en:'Match water to the flakes', no:'Tilpass vannet til flakene'},
     body:{en:'The thick flakes used here soften after a quick rinse and rest. Other grades may need a short soak, while thin poha can collapse with too much water. Follow the texture in your packet rather than one rule for every kind.',
           no:'De tykke flakene her blir myke etter rask skylling og hvile. Andre kvaliteter kan trenge kort bløtlegging, mens tynn poha kan falle sammen med for mye vann. Følg konsistensen i pakken i stedet for én regel for alle typer.'},
    },
    {title:{en:'Why the sugar is there', no:'Hvorfor sukkeret er med'},
     body:{en:'This recipe uses a small amount to balance lime and chilli and to draw out the sweetness of the onion. It can be reduced or omitted according to taste.',
           no:'Denne oppskriften bruker en liten mengde for å balansere lime og chili og framheve sødmen i løken. Den kan reduseres eller utelates etter smak.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy thick poha, sold as jada poha or thick flattened rice. The thin kind is meant for chivda and turns to mush here.',
           no:'Kjøp tykk poha, som selges som jada poha eller thick poha i indiske butikker på Grønland. Den tynne typen er ment for chivda og blir til grøt her. Peanøttene i dagligvarebutikken er ristet og saltet og duger ikke, så spør etter rå peanøtter. Fersk kokos får du lettest som frossen revet kokos fra fryseren i indiske butikker, og den er langt bedre enn kokosmasse, som er tørr.'}}],
  variations:[
    {title:{en:'Batata poha', no:'Batata poha'},
     body:{en:'Add a diced potato with the onion and cook it through before the poha goes in. It makes the dish heavier and is what many households do when the poha has to last until lunch.',
           no:'Ha i en potet i terninger sammen med løken og stek den gjennom før pohaen går i. Det gjør retten tyngre, og mange husholdninger gjør det når pohaen skal holde til lunsj.'}},
    {title:{en:'Dadpe pohe', no:'Dadpe pohe'},
     body:{en:'The uncooked version: rinse thin poha, mix it raw with grated coconut, raw onion, coriander and lime, and pour a hot phodni of oil, mustard seed and curry leaf over the top. Nothing goes on the stove except the tempering.',
           no:'Utgaven uten steking: skyll tynn poha, bland den rå med revet kokos, rå løk, koriander og lime, og hell en varm phodni av olje, sennepsfrø og karriblad over. Ingenting kommer på platen bortsett fra phodnien.'}},
    {title:{en:'With peas', no:'Med erter'},
     body:{en:'A handful of fresh green peas cooked with the onion is a winter habit in Pune, and it gives the dish some sweetness and a second colour.',
           no:'En håndfull ferske grønne erter kokt sammen med løken er vanlig om vinteren i Pune, og det gir retten litt sødme og en farge til.'}}]
},

{
  id:'puran-poli', dish:'Puran poli', course:'sweet', lesson:2, serves:4, veg:true,
  time:{prep:60, cook:45}, hero:'puran-poli', tags:['festival','jaggery','bread'],
  title:{en:'Puran poli, with its amti', no:'Puran poli, med amtien sin'},
  blurb:{en:'A soft wheat flatbread stuffed with chana dal cooked down with jaggery, served with ghee and a thin dark soup made from the cooking water.',
         no:'Et mykt flatbrød av hvete med fyll av chana dal som er kokt ned med jaggery. Det serveres med ghee og en tynn, mørk suppe av kokevannet.'},
  heroCaption:{en:'The ghee pools in the middle and is not optional. A puran poli without it tastes dry within a minute.',
               no:'Gheen samler seg i midten og er ikke valgfri. En puran poli uten ghee smaker tørt etter ett minutt.'},
  goesWith:[{en:'Katachi amti, in a bowl alongside', no:'Katachi amti, i en skål ved siden av'},
            {en:'A glass of cold milk', no:'Et glass kald melk'}],
  headnote:{
    en:`<p>Puran poli is what a Maharashtrian house makes for Holi and for Gudi Padwa, and it is the one recipe here that will take you an afternoon. Nothing in it is technically hard. It is simply that the filling has to be exactly right before the rolling can begin, and there is no shortcut to that.</p>
<p>Two things are worth knowing before you start. The filling must be dry enough to hold a spoon upright, because a wet filling tears through the dough the moment you roll it. And the dough must be softer and stretchier than a chapati dough, because it has to travel a long way around a large ball of filling without splitting.</p>
<p>The second half of this recipe is the part most cookbooks leave out. The water the dal was boiled in is not thrown away. It becomes <em>katachi amti</em>, a thin, sharp, dark soup seasoned with goda masala and tamarind, and it is served in a bowl beside the sweet bread. Sweet and sour on the same plate, from the same pot, with nothing wasted.</p>`,
    no:`<p>Puran poli er det en maharashtrisk husholdning lager til Holi og til Gudi Padwa, og det er den ene oppskriften her som tar en ettermiddag. Ingenting i den er teknisk vanskelig. Det er bare det at fyllet må være helt riktig før kjevlingen kan begynne, og den delen finnes det ingen snarvei forbi.</p>
<p>To ting er verdt å vite før du setter i gang. Fyllet må være tørt nok til å holde en skje oppreist, for et vått fyll bryter gjennom deigen i det øyeblikket du kjevler. Og deigen må være mykere og mer elastisk enn en chapatideig, for den skal strekke seg langt rundt en stor kule fyll uten å revne.</p>
<p>Den andre halvdelen av oppskriften er det de fleste kokebøker utelater. Vannet dalen ble kokt i, kastes ikke. Det blir <em>katachi amti</em>, en tynn, skarp og mørk suppe smakt til med goda masala og tamarind, og den settes fram i en skål ved siden av det søte brødet. Søtt og surt på samme tallerken, fra samme gryte, uten at noe går til spille.</p>`},
  ingredients:[
   {group:{en:'The puran', no:'Puranen'}, items:[
    {q:250, u:'g', n:{en:'chana dal', no:'chana dal'}},
    {q:250, u:'g', n:{en:'jaggery', no:'jaggery'}, note:{en:'chopped or grated off the block', no:'hakket eller revet av blokka'}},
    {q:3, u:'g', n:{en:'ground cardamom', no:'malt kardemomme'}},
    {u:'', n:{en:'grated nutmeg, a little', no:'revet muskatnøtt, litt'}, scale:'none'},
   ]},
   {group:{en:'The dough', no:'Deigen'}, items:[
    {q:250, u:'g', n:{en:'plain wheat flour', no:'hvetemel'}},
    {q:40, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:150, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:2, u:'g', n:{en:'turmeric', no:'gurkemeie'}, note:{en:'for colour only', no:'bare for fargen'}},
    {u:'', n:{en:'salt, a pinch', no:'salt, en klype'}, scale:'none'},
    {u:'', n:{en:'rice flour, for dusting', no:'rismel, til å strø med'}, scale:'none'},
    {u:'', n:{en:'ghee, to cook and to serve', no:'ghee, til steking og servering'}, scale:'none'},
   ]},
   {group:{en:'The katachi amti', no:'Katachi amti'}, items:[
    {q:20, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:5, u:'g', n:{en:'mustard seed', no:'sennepsfrø'}},
    {q:15, u:'', n:{en:'curry leaves', no:'karriblader'}},
    {q:12, u:'g', n:{en:'goda masala', no:'goda masala'}},
    {q:20, u:'g', n:{en:'tamarind paste', no:'tamarindmasse'}},
    {q:25, u:'g', n:{en:'jaggery', no:'jaggery'}},
    {q:20, u:'g', n:{en:'dry coconut, grated', no:'tørket kokos, revet'}},
    {u:'', n:{en:'asafoetida, a pinch', no:'asafoetida, en klype'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Rinse the chana dal and boil it in plenty of water until the grains are soft but still whole. Drain it over a bowl and keep every drop of the water.',
     no:'Skyll chana dalen og kok den i rikelig vann til kornene er myke, men fortsatt hele. Hell den av over en bolle og ta vare på hver dråpe av vannet.'},
    {en:'Make the dough while the dal cooks: work the flour, turmeric, salt, oil and water into something noticeably softer than a chapati dough. Knead it for five minutes, oil the surface, cover it and leave it for an hour.',
     no:'Lag deigen mens dalen koker: arbeid mel, gurkemeie, salt, olje og vann sammen til noe som er merkbart mykere enn en chapatideig. Elt i fem minutter, smør overflaten med olje, dekk til og la den stå en time.'},
    {en:'Return the drained dal to a dry heavy pan with the jaggery. Cook it over a medium flame, stirring constantly, while the jaggery melts and then the whole mass dries back out again.',
     no:'Ha den avrente dalen tilbake i en tørr, tung gryte sammen med jaggeryen. Kok på middels varme under stadig omrøring mens jaggeryen smelter og hele massen tørker inn igjen.'},
    {en:'Stop when a spoon stood upright in the middle stays upright. This takes fifteen to twenty minutes and it is the only part of the recipe that decides whether the rest works.',
     no:'Stopp når en skje som settes rett opp i midten, blir stående. Det tar femten til tjue minutter, og det er den eneste delen av oppskriften som avgjør om resten lykkes.'},
    {en:'Stir in the cardamom and the nutmeg, let it cool, then pass it through a mill or mash it smooth. Roll it into eight balls.',
     no:'Rør inn kardemommen og muskatnøtten, la det avkjøles, og press det så gjennom en kvern eller mos det glatt. Trill det til åtte kuler.'},
    {en:'Divide the rested dough into eight balls of the same size as the filling balls. Flatten one, put a filling ball in the middle, draw the edges up over it and pinch the top closed.',
     no:'Del den hvilte deigen i åtte kuler på størrelse med fyllkulene. Trykk én flat, legg en fyllkule i midten, trekk kantene opp over den og klyp toppen igjen.'},
    {en:'Dust the board with rice flour and roll the parcel out from the centre with light, even pressure, turning it a quarter after every pass. Stop at the width of a side plate.',
     no:'Strø rismel på fjøla og kjevle pakken ut fra midten med lett og jevnt trykk, og vri den en kvart omdreining mellom hvert drag. Stopp ved bredden av en asjett.'},
    {en:'Cook it on a medium griddle. Turn it when the underside shows brown spots, brush the cooked side with ghee, and turn it once more. It should stay soft, not crisp.',
     no:'Stek den på en takke på middels varme. Snu den når undersiden har brune flekker, pensle den stekte siden med ghee, og snu én gang til. Den skal holde seg myk og ikke bli sprø.'},
    {en:'For the amti, heat the oil, pop the mustard seed and add the asafoetida and curry leaves. Stir in the goda masala and the grated dry coconut and fry for a minute.',
     no:'Til amtien varmer du oljen, lar sennepsfrøene sprette og har i asafoetidaen og karribladene. Rør inn goda masalaen og den revne tørkede kokosen, og stek i ett minutt.'},
    {en:'Pour in the reserved dal water, add the tamarind, the jaggery and salt, and simmer for ten minutes. It should be thin enough to drink and sharper than you expect.',
     no:'Hell i dalvannet du tok vare på, ha i tamarinden, jaggeryen og salt, og la det småkoke i ti minutter. Den skal være tynn nok til å drikkes og skarpere enn du venter.'},
    {en:'Serve the poli warm with a spoon of ghee melting on top and a bowl of the amti beside it.',
     no:'Server polien varm med en skje ghee som smelter på toppen, og en skål amti ved siden av.'}],
  notes:[
    {title:{en:'Why the filling has to be dry', no:'Hvorfor fyllet må være tørt'},
     body:{en:'Jaggery melts to a syrup and the boiled dal still holds a good deal of water, and all of it has to cook off before the filling is stable. A puran that is even slightly wet will find the thinnest point in the dough and come through it, and no amount of rice flour will stop that happening.',
           no:'Jaggeryen smelter til sirup, og den kokte dalen holder fortsatt mye vann, og alt sammen må koke bort før fyllet er stabilt. En puran som er bare litt fuktig, finner det tynneste punktet i deigen og bryter gjennom der, og ikke noe rismel i verden hindrer det.'}},
    {title:{en:'Why the dough rests', no:'Hvorfor deigen må hvile'},
     body:{en:'An hour under oil lets the gluten relax, and a relaxed dough stretches around the filling instead of springing back and tearing. The oil on the surface also keeps a skin from forming, which would show up as a crack the moment you roll.',
           no:'En time under olje lar glutenet slappe av, og en avslappet deig strekker seg rundt fyllet i stedet for å trekke seg tilbake og revne. Oljen på overflaten hindrer dessuten at det danner seg et skinn, som ville vist seg som en sprekk med en gang du kjevler.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Chana dal is split brown chickpea and nothing else will behave like it.',
           no:'Chana dal er delte brune kikerter, og ingenting annet oppfører seg likt. Gule erter fra dagligvarebutikken koker seg i stykker og gir en grøt i stedet for et fyll, så kjøp chana dal i en indisk butikk. Jaggery selges der i blokker, som gur eller jaggery, og du kan ikke bytte den med brunt sukker: brunt sukker er raffinert sukker med melasse tilbake i, og det gir sødme uten den syrlige dybden. Har du ingen puran-kvern, går det fint med en sil og en potetstapper.'}}],
  variations:[
    {title:{en:'The coconut version', no:'Utgaven med kokos'},
     body:{en:'Replace half the dal with freshly grated coconut cooked down with the jaggery. The filling is looser and sweeter and has to be rolled with a lighter hand, and it is what the Konkan makes more often than the plateau does.',
           no:'Bytt halvparten av dalen med fersk revet kokos kokt ned med jaggeryen. Fyllet blir løsere og søtere og må kjevles med lettere hånd, og det er det Konkan lager oftere enn platået gjør.'}},
    {title:{en:'An everyday dough', no:'En hverdagsdeig'},
     body:{en:'Use wholemeal wheat flour instead of plain. The bread is coarser, browner and harder to roll thin, and many households prefer it because it tastes of something other than sugar.',
           no:'Bruk sammalt hvetemel i stedet for siktet. Brødet blir grovere, brunere og vanskeligere å kjevle tynt, og mange husholdninger foretrekker det fordi det smaker av noe annet enn sukker.'}},
    {title:{en:'What to do with leftover puran', no:'Hva du gjør med puran til overs'},
     body:{en:'Roll it into small balls with a little ghee and eat them as they are, or thin it with milk into a pudding. It keeps for three days in the fridge and gets firmer, which only makes it easier to handle.',
           no:'Trill den til små kuler med litt ghee og spis dem som de er, eller spe den ut med melk til en dessert. Den holder seg tre dager i kjøleskapet og blir fastere, og det gjør den bare lettere å arbeide med.'}}]
},

{
  id:'kolhapuri-mutton-two-rassas', dish:'Kolhapuri mutton', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:45, cook:90}, hero:'kolhapuri-thali', tags:['goat','chilli','stock'],
  title:{en:'Kolhapuri mutton, with both rassas', no:'Geitekjøtt fra Kolhapur, med begge rassaene'},
  blurb:{en:'Goat simmered for its stock, and that one stock turned into two opposite gravies served side by side.',
         no:'Geitekjøtt trukket for kraftens skyld, og den ene kraften gjort om til to motsatte sauser som settes fram samtidig.'},
  heroCaption:{en:'The two small steel bowls are the dish: white on one side, red on the other, and you alternate.',
               no:'De to små stålskålene er selve retten: hvit på den ene siden, rød på den andre, og du veksler.'},
  goesWith:[{en:'Bhakri, or a plain chapati', no:'Bhakri, eller en enkel chapati'},
            {en:'Raw onion and a wedge of lime', no:'Rå løk og en limebåt'}],
  headnote:{
    en:`<p>This is one cook's afternoon that produces three things: a dry spiced meat, a red gravy that will hurt, and a white gravy that puts the red one out. They come to the table together, and the meal is the alternation between them.</p>
<p>Everything depends on the stock. The goat is simmered gently in water with whole spices until it is tender, and that liquid is the base of both gravies, so nothing is thrown away and nothing is watered down. Buy the meat on the bone for exactly this reason: the bone is where the body of the stock comes from.</p>
<p>The other piece of the design is the <em>vatan</em>, a dark paste of onion fried to brown, dry coconut roasted to brown, and sesame, coriander and cumin roasted the same way. It goes into the meat and into the red gravy, and it is the reason a Kolhapuri dish tastes deep rather than simply hot. Make it first and the rest is assembly.</p>`,
    no:`<p>Dette er én ettermiddag på kjøkkenet som gir tre ting: et tørt krydret kjøtt, en rød saus som gjør vondt, og en hvit saus som slukker den røde. De kommer på bordet samtidig, og måltidet er vekslingen mellom dem.</p>
<p>Alt avhenger av kraften. Geitekjøttet trekkes forsiktig i vann med hele krydder til det er mørt, og den væsken er grunnlaget for begge sausene, så ingenting kastes og ingenting spes ut. Kjøp derfor kjøttet med bein, for kraften får fylden sin fra beinet.</p>
<p>Den andre delen av konstruksjonen er <em>vatanen</em>, en mørk masse av løk stekt brun, tørket kokos ristet brun, og sesam, koriander og spisskummen ristet på samme vis. Den går både i kjøttet og i den røde sausen, og det er grunnen til at en kolhapurisk rett smaker dyp og ikke bare sterk. Lag den først, så er resten bare montering.</p>`},
  ingredients:[
   {group:{en:'The meat and the stock', no:'Kjøttet og kraften'}, items:[
    {q:1, u:'kg', n:{en:'goat on the bone', no:'geitekjøtt med bein'}, note:{en:'shoulder and leg, in large pieces', no:'bog og lår, i store biter'}},
    {q:25, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:25, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:8, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:5, u:'g', n:{en:'black peppercorns', no:'hele sorte pepperkorn'}},
    {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
    {q:1800, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'The vatan', no:'Vatanen'}, items:[
    {q:45, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:250, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'i tynne skiver'}},
    {q:60, u:'g', n:{en:'dry coconut, grated', no:'tørket kokos, revet'}},
    {q:15, u:'g', n:{en:'white sesame seed', no:'hvite sesamfrø'}},
    {q:10, u:'g', n:{en:'coriander seed', no:'korianderfrø'}},
    {q:5, u:'g', n:{en:'cumin seed', no:'hele spisskummenfrø'}},
   ]},
   {group:{en:'Tambda rassa, the red one', no:'Tambda rassa, den røde'}, items:[
    {q:45, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:20, u:'g', n:{en:'Kashmiri chilli powder', no:'Kashmiri chilipulver'}},
    {q:10, u:'g', n:{en:'hot chilli powder', no:'sterkt chilipulver'}},
    {q:15, u:'g', n:{en:'kala masala', no:'kala masala'}, note:{en:'or goda masala with more chilli', no:'eller goda masala med mer chili'}},
   ]},
   {group:{en:'Pandhra rassa, the white one', no:'Pandhra rassa, den hvite'}, items:[
    {q:30, u:'ml', n:{en:'groundnut oil', no:'peanøttolje'}},
    {q:100, u:'g', n:{en:'fresh coconut, grated', no:'fersk kokos, revet'}},
    {q:15, u:'g', n:{en:'ginger', no:'ingefær'}},
    {q:10, u:'g', n:{en:'garlic', no:'hvitløk'}},
    {q:5, u:'g', n:{en:'black pepper, coarsely ground', no:'sort pepper, grovmalt'}},
    {q:1, u:'', n:{en:'small bunch of coriander', no:'liten bunt koriander'}, round:'half', scale:'none'},
   ]}],
  steps:[
    {en:'Pound the ginger and garlic to a paste, rub the meat with half of it, the turmeric and salt, and leave it for half an hour.',
     no:'Knus ingefær og hvitløk til en masse, gni kjøttet inn med halvparten av den, gurkemeien og salt, og la det stå en halvtime.'},
    {en:'Put the meat in a heavy pan with the water, the peppercorns and the bay, bring it to a bare simmer and cook until it gives way to a fork. An hour and a half on the stove, or half an hour under pressure.',
     no:'Legg kjøttet i en tung gryte med vannet, pepperkornene og laurbæret, la det så vidt småkoke og kok til det gir etter for en gaffel. Halvannen time på platen, eller en halvtime i trykkoker.'},
    {en:'Strain it. Keep the meat and keep every drop of the stock; you will use all of it.',
     no:'Sil det av. Ta vare på kjøttet og på hver dråpe av kraften; du skal bruke alt sammen.'},
    {en:'Roast the grated dry coconut in a dry pan until it is dark brown, then tip it out. Roast the sesame, coriander and cumin the same way and tip them out too.',
     no:'Rist den revne tørkede kokosen i en tørr panne til den er mørkebrun, og hell den ut. Rist sesam, koriander og spisskummen på samme måte, og hell dem ut også.'},
    {en:'Fry the sliced onion in the oil until it is deep brown. Grind it with the roasted coconut and seeds and a ladle of stock into a thick dark paste. That is the vatan.',
     no:'Stek løkskivene i oljen til de er mørkebrune. Kjør dem sammen med den ristede kokosen, frøene og en øse kraft til en tykk mørk masse. Det er vatanen.'},
    {en:'For the red gravy, heat the oil in a wide pan, lift it off the heat and stir in both chilli powders so they bloom in the fat without burning. Put it back on a low flame.',
     no:'Til den røde sausen varmer du oljen i en vid panne, løfter den av platen og rører begge chilipulverne inn så de slipper farge og smak ut i fettet uten å svi seg. Sett den tilbake på lav varme.'},
    {en:'Add two thirds of the vatan and the kala masala and fry until the oil separates and rises. Pour in about half the stock, salt it, and simmer for fifteen minutes. It must stay thin.',
     no:'Ha i to tredeler av vatanen og kala masalaen, og stek til oljen skiller seg ut og legger seg på toppen. Hell i omtrent halvparten av kraften, salt, og la det småkoke i femten minutter. Den skal holde seg tynn.'},
    {en:'For the white gravy, grind the fresh coconut with the remaining ginger and garlic paste, the pepper and a little water into a smooth white paste.',
     no:'Til den hvite sausen kjører du den ferske kokosen sammen med resten av ingefær- og hvitløksmassen, pepperen og litt vann til en glatt hvit masse.'},
    {en:'Heat the oil, fry that paste for two minutes without letting it take any colour, then add the rest of the stock and simmer for ten minutes. Salt it and finish with the coriander. It has to stay white.',
     no:'Varm oljen, stek den massen i to minutter uten at den tar farge, og ha så i resten av kraften og la det småkoke i ti minutter. Salt, og avslutt med korianderen. Den skal holde seg hvit.'},
    {en:'Put the cooked meat in a pan with the last of the vatan and a ladle of the red gravy, and cook it down over a medium flame until the masala clings to the pieces and the pan is nearly dry.',
     no:'Ha det kokte kjøttet i en panne med resten av vatanen og en øse av den røde sausen, og kok det inn på middels varme til masalaen klistrer seg til bitene og pannen er nesten tørr.'},
    {en:'Serve the meat in the middle with a small bowl of each gravy beside it and bread to tear. Alternate: red, then white, then bread.',
     no:'Sett kjøttet i midten med en liten skål av hver saus ved siden av, og brød å rive av. Veksle: rød, så hvit, så brød.'}],
  notes:[
    {title:{en:'Why one stock makes two gravies', no:'Hvorfor én kraft gir to sauser'},
     body:{en:'This recipe divides one stock between two gravies so the red one can be hot while the pale one stays mild and coconut-rich. Other Kolhapuri preparations build the gravies differently.',
           no:'Denne oppskriften deler én kraft mellom to sauser, slik at den røde kan være sterk mens den lyse er mild og rik på kokos. Andre kolhapuriske tilberedninger bygger sausene på andre måter.'}},
    {title:{en:'Why the chilli goes into oil off the heat', no:'Hvorfor chilien går i oljen med pannen av platen'},
     body:{en:'Ground chilli burns in seconds on a hot pan and turns bitter, and burnt chilli cannot be rescued. Taking the pan off the flame lets the fat draw the colour and the flavour out at a temperature the powder survives. The red slick that rises later comes from this step.',
           no:'Malt chili svir seg på sekunder i en varm panne og blir bitter, og brent chili lar seg ikke redde. Tar du pannen av platen, trekker fettet ut fargen og smaken ved en temperatur pulveret tåler. Den røde hinnen som legger seg på toppen senere, kommer fra dette steget.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Goat on the bone is the right meat and it is worth asking for.',
           no:'Geitekjøtt med bein er det riktige kjøttet, og halalslaktere på Grønland og Tøyen i Oslo fører det, ofte frossent. Be om at det kappes på tvers av beinet. Lammebog er den praktiske erstatningen, men lam er fetere og søtere, så skum av mer og vær litt hardere med chilien. Kashmiri chilipulver gir fargen uten styrken og selges i indiske butikker; vanlig paprikapulver gir fargen, men ikke smaken. Kokosmasse kan være søtet, så les innholdsfortegnelsen før du rister den.'}}],
  variations:[
    {title:{en:'With chicken', no:'Med kylling'},
     body:{en:'Chicken on the bone works, but you have to make the stock separately from wings and backs, because forty minutes of chicken gives nothing worth calling a stock. Everything else is unchanged.',
           no:'Kylling med bein fungerer, men da må du koke kraften for seg av vinger og rygg, for førti minutter med kylling gir ingenting som fortjener å kalles kraft. Alt annet er likt.'}},
    {title:{en:'The dry one alone', no:'Bare den tørre'},
     body:{en:'Stop after the meat is cooked down with the vatan and serve that on its own with bhakri. It is called sukka, it is what a household makes on an ordinary evening, and it takes an hour less.',
           no:'Stopp etter at kjøttet er kokt inn med vatanen, og server det alene med bhakri. Det heter sukka, det er det en husholdning lager en helt vanlig kveld, og det tar en time mindre.'}},
    {title:{en:'A Saoji variation', no:'En Saoji-variant'},
     body:{en:'Some Saoji versions associated with Nagpur use white poppy seed, black pepper and substantial chilli in a darker, thicker gravy. Recipes and heat levels vary.',
           no:'Enkelte Saoji-utgaver forbundet med Nagpur bruker hvite valmuefrø, sort pepper og mye chili i en mørkere og tykkere saus. Oppskrifter og styrke varierer.'}}]
}

];
