/* Masala Dabba — recipes for Rajasthan (IN-RAJ). Contract: docs/recipe-format.md.
   Both languages live in the same file so a quantity is written exactly once and cannot drift.
   Recipes are never narrated: narrate.py only ever sees a reading's html. */
window.RECIPES = window.RECIPES || {};
window.RECIPES['IN-RAJ'] = [

{
  id:'laal-maas', dish:'Laal maas', course:'main', lesson:3, serves:4, veg:false,
  time:{prep:30, cook:105}, hero:'laal-maas', tags:['goat','yoghurt','chilli','dhungar'],
  title:{en:'Laal maas', no:'Laal maas'},
  blurb:{en:'Goat braised with yoghurt, aromatic red chillies and little added water.',
         no:'Geitekjøtt kokt med yoghurt, aromatisk rød chili og lite tilsatt vann.'},
  heroCaption:{en:'Laal maas. The red ghee standing on the surface is the sign that it is finished.',
               no:'Laal maas. Den røde gheen som legger seg på overflaten, er tegnet på at den er ferdig.'},
  goesWith:[{en:'Bajra roti, hot off the fire', no:'Bajra-roti rett fra ilden'},
            {en:'Salted buttermilk, cold', no:'Kald, saltet kjernemelk'}],
  headnote:{
    en:`<p>Laal maas needs chillies chosen for colour and aroma as well as heat. Mathania and Kashmiri pods vary, so taste one and reduce the number if the batch is hot. Yoghurt softens the sensation of chilli while ghee carries its colour and aroma.</p>
<p>The dish is commonly linked to Rajput hunting camps, although that origin survives chiefly as culinary tradition. This version uses yoghurt around the meat and only enough added water to prevent scorching during its long braise.</p>
<p>When the yoghurt masala has reduced, red fat separates and rises to the surface. Treat that as a sign to test the meat; the dish is ready when the goat is tender.</p>`,
    no:`<p>Laal maas trenger chili som er valgt for farge og duft i tillegg til styrke. Mathania- og kashmiri-belger varierer, så smak på én og bruk færre hvis partiet er sterkt. Yoghurt demper chilifølelsen, mens ghee bærer fargen og duften.</p>
<p>Retten knyttes ofte til rajputenes jaktleirer, men opphavet lever først og fremst som mattradisjon. Denne varianten bruker yoghurt rundt kjøttet og bare nok tilsatt vann til at den lange kokingen ikke svir seg.</p>
<p>Når yoghurtblandingen er redusert, skiller rødt fett seg ut på overflaten. Bruk det som tegn på at kjøttet skal prøves; retten er ferdig når geitekjøttet er mørt.</p>`},
  ingredients:[{group:{en:'', no:''}, items:[
    {q:800, u:'g', n:{en:'goat or lamb shoulder, on the bone', no:'geite- eller lammebog, med bein'}, note:{en:'in pieces the size of a walnut', no:'i biter på størrelse med en valnøtt'}},
    {q:400, u:'g', n:{en:'full-fat yoghurt', no:'yoghurt naturell med fullt fettinnhold'}, note:{en:'beaten smooth', no:'pisket glatt'}},
    {q:12, u:'', n:{en:'dried Kashmiri or Mathania chillies', no:'tørkede kashmiri- eller Mathania-chili'}, round:'half', note:{en:'stemmed', no:'renset for stilk'}},
    {q:120, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:60, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'half crushed to a paste, half sliced', no:'halvparten knust til pasta, halvparten skivet'}},
    {q:15, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:5, u:'g', n:{en:'kachri powder', no:'kachri-pulver'}, note:{en:'optional, a tenderiser', no:'valgfritt, mørner kjøttet'}},
    {q:5, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:6, u:'', n:{en:'cloves', no:'nellik'}, round:'half'},
    {q:4, u:'', n:{en:'green cardamom pods', no:'grønne kardemommekapsler'}, round:'half'},
    {q:2, u:'', n:{en:'black cardamom pods', no:'svarte kardemommekapsler'}, round:'half'},
    {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
    {q:200, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'a piece of lump charcoal, for the smoking', no:'en bit grillkull, til røykingen'}, scale:'none'},
  ]}],
  steps:[
    {en:'Cover the chillies with warm water and leave them for 30 minutes, then grind them to a smooth paste with a little of the soaking water.',
     no:'Dekk chilien med varmt vann og la den ligge i 30 minutter, og mal den så til en glatt pasta med litt av bløtevannet.'},
    {en:'Rub the meat with the yoghurt, the kachri powder, the turmeric and salt. Leave it somewhere cool for at least an hour, and longer if you have time.',
     no:'Gni kjøttet inn med yoghurten, kachri-pulveret, gurkemeien og salt. La det stå kjølig i minst en time, og lenger hvis du har tid.'},
    {en:'Melt the ghee in a heavy pan over a medium flame, add the cloves, both cardamoms and the bay, and wait until they smell.',
     no:'Smelt gheen i en tung gryte på middels varme, ha i nellik, begge slags kardemomme og laurbær, og vent til det dufter.'},
    {en:'Add the garlic and fry it until it is pale gold. It must not brown, because burnt garlic will sit under everything else.',
     no:'Ha i hvitløken og stek den til den er lysegyllen. Den skal ikke brunes, for brent hvitløk legger seg under alt det andre.'},
    {en:'Turn the heat down, stir in the chilli paste and the ground coriander, and cook for about five minutes until the ghee starts to separate at the edge of the pan.',
     no:'Skru ned varmen, rør inn chilipastaen og den malte korianderen, og la det surre i omtrent fem minutter til gheen begynner å skille seg ut langs kanten.'},
    {en:'Add the meat with all its marinade. Stir it over a low flame for ten minutes, so the yoghurt warms through gradually instead of splitting.',
     no:'Ha i kjøttet med hele marinaden. Rør i det på lav varme i ti minutter, slik at yoghurten varmes gradvis i stedet for å skille seg.'},
    {en:'Pour in the water, cover, and cook very gently for about 75 minutes, until the meat gives to a spoon. Stir now and then, and add a splash more water only if the pan runs dry.',
     no:'Hell i vannet, legg på lokk og la det koke svært forsiktig i omtrent 75 minutter, til kjøttet gir etter for en skje. Rør av og til, og spe med litt vann bare hvis gryta går tørr.'},
    {en:'Take the lid off and raise the heat a little. Keep going until red ghee separates out and stands on the surface. That is the dish telling you it is ready.',
     no:'Ta av lokket og skru opp varmen litt. Fortsett til rød ghee skiller seg ut og legger seg på overflaten. Da sier retten selv fra at den er ferdig.'},
    {en:'For the smoking, set a small steel bowl down in the middle of the meat, drop in a glowing coal and spoon a little ghee over it. Cover at once and leave it for two minutes, then lift the bowl out.',
     no:'Til røykingen setter du en liten stålskål ned midt i kjøttet, legger en glo i den og heller litt ghee over. Legg straks på lokket, la det stå i to minutter, og løft så skålen ut.'},
    {en:'Taste for salt, let it stand for a quarter of an hour, and serve it with bajra roti.',
     no:'Smak til med salt, la retten hvile et kvarter, og server den med bajra-roti.'}],
  notes:[
    {title:{en:'Why yoghurt and little water', no:'Hvorfor yoghurt og lite vann'},
     body:{en:'Yoghurt supplies acidity, moisture and body. Kachri, when used, provides additional tenderising enzymes. A little water prevents scorching while the meat slowly becomes tender.',
           no:'Yoghurt gir syre, væske og fylde. Kachri tilfører ekstra mørnende enzymer når den brukes. Litt vann hindrer fastbrenning mens kjøttet sakte blir mørt.'}},
    {title:{en:'Taste the chilli first', no:'Smak på chilien først'},
     body:{en:'Kashmiri and Mathania pods are valued for colour, but their heat is not fixed. Taste the batch and begin with fewer pods if necessary; more paste can be added during cooking.',
           no:'Kashmiri- og Mathania-belger verdsettes for fargen, men styrken er ikke fast. Smak på partiet og begynn med færre belger ved behov; mer pasta kan tilsettes underveis.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Goat is sold by halal butchers rather than by supermarkets; lamb shoulder is the honest substitute and behaves the same way. Use a thick Turkish or Greek yoghurt with real fat in it, because Norwegian low-fat naturell splits.',
           no:'Geitekjøtt selges hos halalslaktere og ikke i dagligvarebutikken, og på Grønland i Oslo får du det med bein, som er det du vil ha. Lammebog er den ærlige erstatningen og oppfører seg likt, og kje om våren er enda nærmere. Bruk tykk tyrkisk eller gresk yoghurt med ekte fett i; norsk mager yoghurt naturell skiller seg i gryta. Ghee selges i store bokser i indiske butikker til en brøkdel av helsekostprisen, og hele kashmiri-belger finnes samme sted.'}}],
  variations:[
    {title:{en:'Safed maas', no:'Safed maas'},
     body:{en:'The white version from the same kitchens. Leave the chilli out altogether and grind a handful of blanched almonds and cashews into the yoghurt instead. It is mild, rich and pale, and the two were served at the same table.',
           no:'Den hvite utgaven fra de samme kjøkkenene. Sløyf chilien helt og mal i stedet en neve skåldede mandler og cashewnøtter inn i yoghurten. Den blir mild, fyldig og lys, og de to ble servert ved samme bord.'}},
    {title:{en:'In the oven', no:'I stekeovnen'},
     body:{en:'After the meat has been stirred into the spices, move everything to a lidded casserole and cook it at 150 °C for two hours. It needs no watching, and the final reduction is done on the hob as before.',
           no:'Når kjøttet er rørt sammen med krydderet, kan du flytte alt over i en gryte med lokk og sette den i ovnen på 150 °C i to timer. Da trenger den ikke tilsyn, og den siste innkokingen gjør du på platen som før.'}}]
},

{
  id:'ker-sangri', dish:'Ker sangri', course:'side', lesson:3, serves:4, veg:true,
  time:{prep:30, cook:45}, hero:'ker-sangri-raw', tags:['dried','desert','yoghurt','keeps'],
  title:{en:'Ker sangri', no:'Ker sangri'},
  blurb:{en:'Dried desert berries and khejri pods, rehydrated, boiled and fried with spices.',
         no:'Tørkede ørkenbær og khejri-belger, bløtlagt, kokt og stekt med krydder.'},
  heroCaption:{en:'Fresh ker berries and sangri pods after picking. No free photograph of the cooked dish exists, so this is what it is made from.',
               no:'Ferske ker-bær og sangri-belger etter plukkingen. Det finnes ikke noe fritt bilde av den ferdige retten, så dette er det den lages av.'},
  goesWith:[{en:'Bajra roti and a spoon of ghee', no:'Bajra-roti og en skje ghee'},
            {en:'Panchmel dal, if it is a full meal', no:'Panchmel dal, hvis det er et helt måltid'}],
  headnote:{
    en:`<p>Ker is the berry of a leafless thorn bush in the caper family, while sangri is the pod of the khejri tree often retained in Rajasthani fields. Drying makes both ingredients durable and concentrates their flavour.</p>
<p>Washing, soaking and boiling rehydrate the ingredients and reduce bitterness before frying. Overnight soaking is convenient for this recipe, though the exact time depends on how old and dry the batch is.</p>
<p>The finished dish is comparatively dry and keeps well under refrigeration. Cool it promptly, refrigerate it in a covered container and use it within four days.</p>`,
    no:`<p>Ker er bæret fra en bladløs tornebusk i kapersfamilien, mens sangri er belgen fra khejri-treet som ofte får stå i åkrene i Rajasthan. Tørking gjør begge råvarene holdbare og konsentrerer smaken.</p>
<p>Skylling, bløtlegging og koking gir råvarene vann igjen og demper bitterheten før steking. En natt i bløt passer denne oppskriften, men tiden avhenger av hvor gammelt og tørt partiet er.</p>
<p>Den ferdige retten er forholdsvis tørr og holder seg godt i kjøleskap. Avkjøl den raskt, oppbevar den i en tett beholder og bruk den innen fire dager.</p>`},
  ingredients:[{group:{en:'', no:''}, items:[
    {q:100, u:'g', n:{en:'dried sangri', no:'tørket sangri'}},
    {q:50, u:'g', n:{en:'dried ker', no:'tørket ker'}},
    {q:2, u:'l', n:{en:'water, for the soaking', no:'vann, til bløtleggingen'}, scale:'sub'},
    {q:100, u:'ml', n:{en:'ghee or a neutral oil', no:'ghee eller en nøytral olje'}},
    {q:100, u:'g', n:{en:'yoghurt', no:'yoghurt naturell'}, note:{en:'beaten smooth', no:'pisket glatt'}},
    {q:6, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
    {q:10, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:5, u:'g', n:{en:'cumin seed', no:'hele spisskummenfrø'}},
    {q:5, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:6, u:'g', n:{en:'amchur, dried mango powder', no:'amchur, tørket mangopulver'}},
    {q:20, u:'g', n:{en:'raisins', no:'rosiner'}, note:{en:'optional', no:'valgfritt'}},
    {u:'', n:{en:'a good pinch of asafoetida', no:'en god klype asafoetida'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
  ]}],
  steps:[
    {en:'Rinse the sangri and the ker separately through several changes of water, until the water runs clear of dust.',
     no:'Skyll sangri og ker hver for seg i flere omganger med vann, til vannet er fritt for støv.'},
    {en:'Soak them overnight in separate bowls, each covered by plenty of salted water. They will roughly double in bulk.',
     no:'Bløtlegg dem over natten i hver sin bolle, godt dekket av saltet vann. De dobler omtrent volumet sitt.'},
    {en:'Drain both, cover with fresh water and boil until the sangri bends without snapping and the ker is soft, somewhere between 25 and 40 minutes depending on how old they are. Drain again and keep them.',
     no:'Hell av vannet, dekk med friskt vann og kok til sangrien bøyer seg uten å knekke og keren er myk, et sted mellom 25 og 40 minutter alt etter hvor gammel den er. Hell av igjen og sett dem til side.'},
    {en:'Heat the ghee in a wide pan over a medium flame, add the cumin and the whole chillies, and wait until the seeds darken.',
     no:'Varm gheen i en vid panne på middels varme, ha i spisskummen og de hele chiliene, og vent til frøene mørkner.'},
    {en:'Add the asafoetida, then straight away the drained ker and sangri, and fry them hard for about eight minutes so the edges catch and colour.',
     no:'Ha i asafoetidaen, og straks etter den avrente keren og sangrien, og stek hardt i omtrent åtte minutter så kantene tar farge.'},
    {en:'Pull the pan off the heat and stir in the turmeric and the ground coriander, so the powders colour the fat instead of burning in it.',
     no:'Trekk pannen av platen og rør inn gurkemeien og den malte korianderen, så pulverne farger fettet i stedet for å svi seg i det.'},
    {en:'Return the pan to a low flame, add the beaten yoghurt and stir steadily while it warms to a simmer.',
     no:'Sett pannen tilbake på lav varme, ha i den piskede yoghurten og rør jevnt mens den varmes til kokepunktet.'},
    {en:'Add the amchur, the raisins and salt, and cook on until the pan is dry again and the fat has come back out, about five minutes.',
     no:'Ha i amchur, rosiner og salt, og la det steke videre til pannen er tørr igjen og fettet har kommet fram, omtrent fem minutter.'},
    {en:'Taste for salt and sour. It should be distinctly sharp, because it is eaten in small quantities alongside bread.',
     no:'Smak til med salt og syre. Den skal være tydelig skarp, for den spises i små mengder ved siden av brød.'},
    {en:'Let the flavours settle briefly before serving. Cool leftovers promptly and refrigerate them in a covered container.',
     no:'La smaken sette seg litt før servering. Avkjøl rester raskt og sett dem i kjøleskap i en tett beholder.'}],
  notes:[
    {title:{en:'Why so much fat', no:'Hvorfor så mye fett'},
     body:{en:'The generous fat carries the spices and gives the dried ingredients a glossy coating. It is part of the dish’s texture, but it does not make cooked food safe at room temperature.',
           no:'Det rikelige fettet bærer krydderet og legger en blank hinne rundt de tørkede råvarene. Det hører til konsistensen, men gjør ikke tilberedt mat trygg i romtemperatur.'}},
    {title:{en:'Do not skip the soaking', no:'Ikke hopp over bløtleggingen'},
     body:{en:'Drying makes ker and sangri hard, so they need enough soaking and boiling to become tender. Changing the water also helps reduce bitterness. Older batches may need longer.',
           no:'Tørking gjør ker og sangri harde, så de trenger nok bløtlegging og koking til å bli møre. Vannbytte bidrar også til å dempe bitterheten. Eldre partier kan trenge lengre tid.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Ker and sangri are mail order and always have been. Buy enough for several attempts, since dried pods keep for years in a sealed jar.',
           no:'Ker og sangri er postordre. Ingen butikk i Norge fører dem fast, men indiske nettbutikker i Storbritannia og Tyskland sender hit, og tørkede belger holder seg i årevis i et tett glass, så kjøp nok til flere forsøk. Sennepsolje, som mange indiske oppskrifter ber om, selges i EU som regel merket «kun til utvortes bruk», så bruk ghee i stedet. Amchur finnes i alle indiske butikker og er ikke det samme som sitronsyre.'}}],
  variations:[
    {title:{en:'Panchkuta', no:'Panchkuta'},
     body:{en:'The full desert mixture adds kumatia seeds and gunda berries to the ker and sangri, in roughly equal weight to the ker. They are soaked with the rest and cooked the same way.',
           no:'Den fullstendige blandingen fra ørkenen har også kumatia-frø og gunda-bær i, i omtrent samme vekt som keren. De bløtlegges sammen med resten og lages på samme måte.'}},
    {title:{en:'Sangri alone', no:'Bare sangri'},
     body:{en:'If you can only find one of the two, use sangri. It is the milder of them and makes a perfectly good dish on its own, which is what many households cook anyway.',
           no:'Finner du bare den ene av de to, så bruk sangri. Den er den mildeste og gir en helt god rett alene, og det er den mange husholdninger lager uansett.'}}]
},

{
  id:'gatte-ki-sabzi', dish:'Gatte ki sabzi', course:'main', lesson:3, serves:4, veg:true,
  time:{prep:25, cook:35}, hero:'gatte', tags:['besan','yoghurt','no onion'],
  title:{en:'Gatte ki sabzi', no:'Gatte ki sabzi'},
  blurb:{en:'Gram-flour dumplings boiled, sliced and simmered in a yoghurt gravy. No vegetable required.',
         no:'Boller av kikertmel, kokt, skåret i skiver og småkokt i en yoghurtsaus. Ingen grønnsak nødvendig.'},
  heroCaption:{en:'Gatte ki sabzi. The discs are boiled dough and the gravy is yoghurt thickened with more of the same flour.',
               no:'Gatte ki sabzi. Skivene er kokt deig, og sausen er yoghurt jevnet med mer av det samme melet.'},
  goesWith:[{en:'Plain rice, or a wheat roti', no:'Kokt ris, eller en hveteroti'},
            {en:'Garlic and chilli chutney', no:'Chutney av hvitløk og chili'}],
  headnote:{
    en:`<p>This dish exists because there was nothing green in the house and no prospect of any. The answer a Rajasthani kitchen gives is gram flour, which supplies both the protein and the body that a vegetable would have supplied, and which keeps in a sack indefinitely.</p>
<p>This version reserves some of the starchy cooking water for the gravy, although other recipes use fresh water. Beaten yoghurt and besan provide the sauce's body.</p>
<p>The recipe contains no onion or garlic. That suits Jain and other households that avoid them, while asafoetida contributes its own savoury aroma.</p>`,
    no:`<p>Retten finnes fordi det ikke var noe grønt i huset og ingen utsikt til noe. Svaret et kjøkken i Rajasthan gir, er kikertmel, som gir både proteinet og fylden en grønnsak ville gitt, og som holder seg i en sekk i det uendelige.</p>
<p>Denne varianten tar vare på litt av det stivelsesrike kokevannet til sausen, mens andre oppskrifter bruker friskt vann. Pisket yoghurt og besan gir sausen fylde.</p>
<p>Oppskriften inneholder verken løk eller hvitløk. Det passer for jainistiske og andre husholdninger som unngår dem, mens asafoetida bidrar med sin egen fyldige duft.</p>`},
  ingredients:[
   {group:{en:'For the gatte', no:'Til gatte'}, items:[
    {q:200, u:'g', n:{en:'gram flour (besan)', no:'kikertmel (besan)'}},
    {q:60, u:'g', n:{en:'yoghurt', no:'yoghurt naturell'}},
    {q:30, u:'ml', n:{en:'neutral oil', no:'nøytral olje'}},
    {q:3, u:'g', n:{en:'ajwain seed', no:'ajwain-frø'}, note:{en:'crushed between the palms', no:'knust mellom håndflatene'}},
    {q:3, u:'g', n:{en:'chilli powder', no:'chilipulver'}},
    {q:5, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:2, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:1500, u:'ml', n:{en:'water, for boiling', no:'vann, til kokingen'}, scale:'sub'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'For the gravy', no:'Til sausen'}, items:[
    {q:250, u:'g', n:{en:'yoghurt', no:'yoghurt naturell'}, note:{en:'full fat', no:'med fullt fettinnhold'}},
    {q:20, u:'g', n:{en:'gram flour (besan)', no:'kikertmel (besan)'}},
    {q:45, u:'ml', n:{en:'ghee', no:'ghee'}},
    {q:5, u:'g', n:{en:'cumin seed', no:'hele spisskummenfrø'}},
    {q:3, u:'g', n:{en:'chilli powder', no:'chilipulver'}},
    {q:8, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:2, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:2, u:'g', n:{en:'garam masala', no:'garam masala'}},
    {u:'', n:{en:'a pinch of asafoetida', no:'en klype asafoetida'}, scale:'none'},
    {u:'', n:{en:'coriander leaf, to finish', no:'frisk koriander, til slutt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Rub the gram flour together with the oil, ajwain, chilli powder, ground coriander, turmeric and salt until the flour holds its shape when you squeeze a handful.',
     no:'Gni kikertmelet sammen med oljen, ajwain, chilipulver, malt koriander, gurkemeie og salt til melet holder formen når du klemmer en neve av det.'},
    {en:'Work in the yoghurt a little at a time and knead to a stiff dough. It should feel firm and not stick to your hands.',
     no:'Arbeid inn yoghurten litt om gangen og elt til en stiv deig. Den skal kjennes fast og ikke klebe til hendene.'},
    {en:'Roll the dough into ropes about as thick as a finger, and as long as the pan will take.',
     no:'Rull deigen til pølser omtrent så tykke som en finger, og så lange som gryta tar.'},
    {en:'Bring the water to a rolling boil, lower the ropes in and cook them for 15 minutes. They float when they are done.',
     no:'Kok opp vannet, legg pølsene forsiktig i og kok dem i 15 minutter. De flyter opp når de er ferdige.'},
    {en:'Lift the ropes out and reserve a generous jug of the cooking water. Slice them into discs once they are cool enough to hold.',
     no:'Løft opp pølsene og ta vare på en romslig mugge av kokevannet. Skjær dem i skiver når de er avkjølt nok til at du kan holde i dem.'},
    {en:'Whisk the gravy yoghurt with the gram flour until no lump is left at all. Any lump now will be a lump in the finished gravy.',
     no:'Visp yoghurten til sausen sammen med kikertmelet til det ikke er en eneste klump igjen. En klump nå blir en klump i den ferdige sausen.'},
    {en:'Heat the ghee, add the cumin and the asafoetida, and wait until the seeds colour and the hing smells savoury rather than raw.',
     no:'Varm gheen, ha i spisskummen og asafoetida, og vent til frøene tar farge og hingen lukter smaksrik i stedet for rå.'},
    {en:'Take the pan off the heat and stir in the chilli powder, turmeric and ground coriander.',
     no:'Ta pannen av platen og rør inn chilipulver, gurkemeie og malt koriander.'},
    {en:'Back on a low flame, pour in the yoghurt mixture and stir steadily while it warms to a simmer.',
     no:'Tilbake på lav varme heller du i yoghurtblandingen og rører jevnt mens den varmes til kokepunktet.'},
    {en:'Loosen the gravy with the reserved cooking water until it pours from a spoon, add the sliced gatte, and simmer for ten minutes.',
     no:'Tynn ut sausen med kokevannet til den renner av en skje, ha i gatte-skivene og la det småkoke i ti minutter.'},
    {en:'Stir in the garam masala, scatter the coriander leaf over, and serve.',
     no:'Rør inn garam masala, strø over frisk koriander, og server.'}],
  notes:[
    {title:{en:'Why some cooking water is kept', no:'Hvorfor litt kokevann tas vare på'},
     body:{en:'The water picks up a little flour and spice from the gatte and gives this gravy a useful head start. Fresh water also works, so reserve only what the recipe needs.',
           no:'Vannet trekker til seg litt mel og krydder fra gatte og gir denne sausen en nyttig start. Friskt vann virker også, så ta bare vare på det oppskriften trenger.'}},
    {title:{en:'Keep the heat gentle', no:'Bruk rolig varme'},
     body:{en:'Beaten yoghurt and besan are less likely to separate when they warm gradually under steady stirring. Stirring direction has no special effect.',
           no:'Glattpisket yoghurt og besan skiller seg mindre lett når de varmes gradvis under jevn omrøring. Retningen du rører i, har ingen egen virkning.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Besan is milled from brown chana dal, not from the pale chickpea, and the two do not behave alike. Buy besan from an Indian shop rather than chickpea flour from a health-food shop.',
           no:'Besan males av brune chana-erter og ikke av den lyse kikerten, og de to oppfører seg ikke likt: kikertmel fra helsekostbutikken er grovere, lysere og suger opp mindre væske, så deigen blir løs. Kjøp besan i en indisk butikk. Ajwain selges samme sted under navnet ajwain eller carom, og ferdig garam masala i pose er god nok her. Bruk gresk yoghurt til sausen, for norsk mager yoghurt naturell er for tynn og skiller seg lettere.'}}],
  variations:[
    {title:{en:'Govind gatte', no:'Govind gatte'},
     body:{en:'The festive version. Flatten each piece of dough, put a little chopped nut and raisin in the middle, close it up and boil as usual. The filling turns a side dish into something for a wedding.',
           no:'Festutgaven. Flat ut hver deigbit, legg litt hakkede nøtter og rosiner i midten, lukk den igjen og kok som vanlig. Fyllet gjør tilbehøret til noe man serverer i bryllup.'}},
    {title:{en:'Gatte fried first', no:'Gatte stekt først'},
     body:{en:'Many cooks shallow-fry the sliced discs in ghee until they are golden before they go into the gravy. They hold their shape better and taste nuttier, at the cost of a heavier dish.',
           no:'Mange kokker steker skivene gylne i ghee før de går i sausen. De holder formen bedre og smaker mer nøtteaktig, men retten blir tyngre.'}}]
},

{
  id:'dal-bati-churma', dish:'Dal bati churma', course:'main', lesson:2, serves:4, veg:true,
  time:{prep:40, cook:75}, hero:'dal-bati', tags:['five pulses','baked','ghee','festival'],
  title:{en:'Dal bati churma', no:'Dal bati churma'},
  blurb:{en:'Five pulses in one pot, hard wheat balls baked in the oven, and the sweet crumb made from the same dough.',
         no:'Fem belgfrukter i én gryte, harde hvetekuler bakt i ovnen, og de søte smulene laget av den samme deigen.'},
  heroCaption:{en:'Dal, bati and churma on one plate. The sweet part is not a dessert; it is eaten alongside the rest.',
               no:'Dal, bati og churma på én tallerken. Den søte delen er ingen dessert, men spises ved siden av resten.'},
  goesWith:[{en:'Garlic and chilli chutney', no:'Chutney av hvitløk og chili'},
            {en:'Sliced raw onion and a green chilli', no:'Rå løk i skiver og en grønn chili'}],
  headnote:{
    en:`<p>This is the plate Rajasthan is known by, and it is really three recipes that were designed to be made at the same fire. The batis are baked hard so that they keep for days, which is why a shepherd or a soldier could carry a bag of them, and the ghee poured over them at the table is what makes them edible again.</p>
<p>The dal is panchmel, five pulses cooked together. That is not decoration. Each of the five softens at a different rate, so some dissolve into the body of the dal while others stay whole, and the mixture ends up with a texture that no single pulse gives.</p>
<p>The third part, churma, is made from batis crushed with ghee and raw cane sugar. It arrives on the same plate as the savoury food rather than after it, which is the habit worth taking away from this recipe: a Rajasthani meal does not keep sweet and savoury apart.</p>`,
    no:`<p>Dette er tallerkenen Rajasthan er kjent for, og den er egentlig tre oppskrifter som ble innrettet slik at de kunne lages over én og samme ild. Batiene bakes harde for at de skal holde seg i dagevis, og derfor kunne en gjeter eller en soldat ta med seg en pose av dem, mens gheen som helles over dem ved bordet, er det som gjør dem spiselige igjen.</p>
<p>Dalen heter panchmel, fem belgfrukter kokt sammen. Det er ingen pynt. Hver av de fem mykner i sitt eget tempo, så noen løser seg opp i selve dalen mens andre holder formen, og blandingen ender med en konsistens ingen enkelt belgfrukt gir.</p>
<p>Den tredje delen, churma, lages av bati støtt sammen med ghee og ukokt rørsukker. Den kommer på den samme tallerkenen som den salte maten og ikke etterpå, og nettopp den vanen er verdt å ta med seg herfra: et måltid i Rajasthan holder ikke søtt og salt fra hverandre.</p>`},
  ingredients:[
   {group:{en:'For the panchmel dal', no:'Til panchmel dal'}, items:[
    {q:60, u:'g', n:{en:'chana dal', no:'chana dal'}},
    {q:40, u:'g', n:{en:'toor dal', no:'toor dal'}},
    {q:40, u:'g', n:{en:'moong dal', no:'moong dal'}},
    {q:30, u:'g', n:{en:'urad dal', no:'urad dal'}},
    {q:30, u:'g', n:{en:'moth beans', no:'moth-bønner'}},
    {q:1200, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:45, u:'g', n:{en:'ghee, for the tempering', no:'ghee, til temperingen'}},
    {q:20, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'finely chopped', no:'finhakket'}},
    {q:5, u:'g', n:{en:'cumin seed', no:'hele spisskummenfrø'}},
    {q:5, u:'g', n:{en:'ground coriander', no:'malt koriander'}},
    {q:5, u:'g', n:{en:'turmeric', no:'gurkemeie'}},
    {q:3, u:'g', n:{en:'chilli powder', no:'chilipulver'}},
    {q:2, u:'g', n:{en:'garam masala', no:'garam masala'}},
    {q:2, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half'},
    {u:'', n:{en:'a pinch of asafoetida', no:'en klype asafoetida'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'For the bati', no:'Til bati'}, items:[
    {q:400, u:'g', n:{en:'coarse wholemeal wheat flour', no:'grov sammalt hvete'}},
    {q:80, u:'g', n:{en:'fine semolina', no:'fin semule'}},
    {q:100, u:'g', n:{en:'ghee, melted, for the dough', no:'ghee, smeltet, til deigen'}},
    {q:5, u:'g', n:{en:'ajwain seed', no:'ajwain-frø'}},
    {q:180, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:150, u:'g', n:{en:'ghee, melted, for dipping', no:'ghee, smeltet, til dypping'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'For the churma', no:'Til churma'}, items:[
    {q:100, u:'g', n:{en:'ghee', no:'ghee'}},
    {q:80, u:'g', n:{en:'jaggery (gur), or dark muscovado', no:'gur, eller mørk muscovado'}, note:{en:'grated', no:'revet'}},
    {q:25, u:'g', n:{en:'almonds', no:'mandler'}, note:{en:'chopped', no:'hakkede'}},
    {q:2, u:'g', n:{en:'green cardamom seed, ground', no:'grønn kardemomme, malt'}},
   ]}],
  steps:[
    {en:'Rinse the five pulses together and leave them to soak for an hour.',
     no:'Skyll de fem belgfruktene sammen og la dem ligge i bløt i en time.'},
    {en:'Drain them, put them in a pan with the water and the turmeric, and simmer covered until everything is soft, about 45 minutes. Skim the foam off in the first ten.',
     no:'Hell av vannet, ha dem i en gryte med vann og gurkemeie, og la det småkoke under lokk til alt er mykt, omtrent 45 minutter. Skum av de første ti minuttene.'},
    {en:'Heat the oven to 200 °C. Rub the flour, semolina, ajwain and salt together with the melted ghee until a squeezed handful holds its shape.',
     no:'Varm ovnen til 200 °C. Gni sammen melet, semulen, ajwain og salt med den smeltede gheen til melet holder formen når du klemmer en neve av det.'},
    {en:'Add the water a little at a time and knead a stiff dough, then let it rest for 20 minutes under a cloth.',
     no:'Tilsett vannet litt om gangen og elt en stiv deig, og la den hvile under et klede i 20 minutter.'},
    {en:'Roll the dough into balls, press a thumb into the top of each to make a dimple, and bake for 35 to 40 minutes, turning them once, until they are hard, cracked and hollow-sounding.',
     no:'Trill deigen til kuler, trykk en tommel ned i toppen av hver så det blir en fordypning, og stek dem i 35 til 40 minutter. Snu dem én gang underveis. De skal bli harde, sprukne og lyde hult.'},
    {en:'Set a third of the batis aside for the churma and keep the rest warm.',
     no:'Sett en tredel av batiene til side til churmaen og hold resten varme.'},
    {en:'For the tempering, heat the ghee in a small pan, add the cumin, the whole chillies and the asafoetida, then the garlic, and fry until the garlic turns gold.',
     no:'Til temperingen varmer du gheen i en liten panne, har i spisskummen, de hele chiliene og asafoetidaen, deretter hvitløken, og steker til hvitløken blir gyllen.'},
    {en:'Off the heat, stir the chilli powder and ground coriander into the tempering, then pour the whole lot into the dal. Add the garam masala and salt and simmer five minutes more.',
     no:'Med pannen av platen rører du chilipulveret og den malte korianderen inn i temperingen, og heller så hele blandingen i dalen. Ha i garam masala og salt og la det småkoke fem minutter til.'},
    {en:'Break the reserved batis up and crush them coarse, in a mortar or with a few pulses in a processor. Leave some texture.',
     no:'Brekk opp batiene du satte til side og knus dem grovt, i morter eller med noen korte kjør i en foodprosessor. La det være litt tekstur igjen.'},
    {en:'Work the ghee into the warm crumbs, then the jaggery, the cardamom and the almonds. The churma should stay loose and crumbly, not turn into a paste.',
     no:'Arbeid gheen inn i de varme smulene, deretter gur, kardemomme og mandler. Churmaen skal holde seg løs og smuldrete og ikke bli en jevn masse.'},
    {en:'Crack the remaining batis open, douse them in the dipping ghee, pour the dal over, and put the churma on the same plate.',
     no:'Knekk opp de resterende batiene, dynk dem i den smeltede gheen, hell dalen over, og legg churmaen på den samme tallerkenen.'}],
  notes:[
    {title:{en:'Why the bati is so hard', no:'Hvorfor batien er så hard'},
     body:{en:'Nothing goes into the dough to make it rise, and the ghee rubbed through the flour stops gluten forming, so it bakes dense. That is what let it keep for days in a saddlebag, and the ghee at the table is the repair.',
           no:'Ingenting er tilsatt deigen for å heve den, og gheen som gnis inn i melet, hindrer at det danner seg gluten, så den bakes tett. Nettopp det gjorde at den holdt seg i dagevis i en salveske, og gheen ved bordet retter det opp.'}},
    {title:{en:'Five pulses, one texture', no:'Fem belgfrukter, én konsistens'},
     body:{en:'Chana holds its shape, moong collapses, and the other three land in between. Cooking them together gives a dal that is both smooth and granular, which is exactly why nobody here makes it with one pulse.',
           no:'Chana holder formen, moong faller sammen, og de tre andre havner imellom. Når de kokes sammen, gir de en dal som er både glatt og kornete, og derfor lager ingen her den med bare én belgfrukt.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'The five pulses are cheap by the kilo in any Indian shop and are not interchangeable with what a Norwegian supermarket sells as lentils.',
           no:'De fem belgfruktene koster lite kiloen i indiske butikker, og de er ikke det samme som det en norsk dagligvarebutikk selger som linser; røde linser koker helt i stykker og gir en grøt. Moth-bønner er det vanskeligste å få tak i, og du kan sløyfe dem og bruke litt mer chana. Til batien er grov sammalt hvete fra dagligvarebutikken god nok, men bland inn litt siktet hvetemel hvis deigen ikke vil henge sammen. Gur selges som gur eller jaggery i indiske butikker, og palmesukker er noe annet; mørk muscovado kommer nærmere.'}}],
  variations:[
    {title:{en:'Batis in the embers', no:'Bati i glørne'},
     body:{en:'The original method buries the balls in the embers of a wood or dung fire and turns them with tongs. On a barbecue, rake the coals to one side and give them 30 minutes with the lid down.',
           no:'I den opprinnelige metoden graves kulene ned i glørne fra et ved- eller møkkbål og snus med tang. På en grill raker du kullene til siden og gir dem 30 minutter med lokket nede.'}},
    {title:{en:'Bafla', no:'Bafla'},
     body:{en:'A softer cousin from the Malwa side. The balls are boiled in water for about fifteen minutes before they are baked, which makes them lighter and less likely to break a tooth.',
           no:'En mykere slektning fra Malwa-siden. Kulene kokes i vann i omtrent femten minutter før de bakes, og det gjør dem lettere og mindre harde mot tennene.'}}]
},

{
  id:'bajre-ki-roti', dish:'Bajre ki roti', course:'bread', lesson:2, serves:4, veg:true,
  time:{prep:20, cook:25}, hero:'bajra-roti', tags:['millet','gluten free','tava','chutney'],
  title:{en:'Bajre ki roti', no:'Bajre ki roti'},
  blurb:{en:'Millet bread patted out between wet palms and finished over the flame, with garlic chutney.',
         no:'Hirsebrød klappet ut mellom våte håndflater og avsluttet over flammen, med chutney av hvitløk.'},
  heroCaption:{en:'Bajra roti with garlic and chilli chutney and raw onion, eaten within minutes of leaving the fire.',
               no:'Bajra-roti med chutney av hvitløk og chili og rå løk, spist noen minutter etter at den er tatt av ilden.'},
  goesWith:[{en:'A spoon of ghee and raw cane sugar, in winter', no:'En skje ghee og ukokt rørsukker, om vinteren'},
            {en:'Ker sangri, or any dal', no:'Ker sangri, eller hvilken som helst dal'}],
  headnote:{
    en:`<p>Pearl millet has no gluten, so this dough will not stretch and a rolling pin tears it. The bread is patted out between wet palms instead, turned a quarter each time, until it is a thick disc the size of a hand. It takes three or four attempts to learn and then it is easy.</p>
<p>Boiling water is the trick that makes it possible. Hot water gelatinises some of the starch, which gives the dough just enough to hold together, and a dough made with cold water falls apart under your hands.</p>
<p>The other half of the recipe is the chutney, because a millet roti on its own is plain and slightly coarse. Lehsun ki chutney is mostly garlic, looks far more alarming than it tastes, and is what a Rajasthani field lunch is built on.</p>`,
    no:`<p>Perlehirse har ikke gluten, så denne deigen strekker seg ikke, og en kjevle river den i stykker. Brødet klappes i stedet ut mellom våte håndflater og vris en kvart omdreining for hver klapp, til det er en tykk skive på størrelse med en hånd. Det tar tre-fire forsøk å lære, og så går det av seg selv.</p>
<p>Kokende vann er grepet som gjør det mulig. Varmt vann får noe av stivelsen til å svelle, og det gir deigen akkurat nok feste til å henge sammen. En deig som er laget med kaldt vann, faller fra hverandre mellom hendene.</p>
<p>Den andre halvdelen av oppskriften er chutneyen, for en hirseroti alene er enkel og litt grov. Lehsun ki chutney er for det meste hvitløk, ser langt verre ut enn den smaker, og den er selve grunnlaget for en lunsj på jordet i Rajasthan.</p>`},
  ingredients:[
   {group:{en:'For the roti', no:'Til roti'}, items:[
    {q:320, u:'g', n:{en:'bajra flour (pearl millet)', no:'bajramel (perlehirse)'}, note:{en:'finely milled', no:'finmalt'}},
    {q:260, u:'ml', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:60, u:'g', n:{en:'butter or ghee, to finish', no:'smør eller ghee, til slutt'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]},
   {group:{en:'For the garlic chutney', no:'Til chutneyen av hvitløk'}, items:[
    {q:60, u:'g', n:{en:'garlic', no:'hvitløk'}, note:{en:'peeled', no:'skrelt'}},
    {q:10, u:'', n:{en:'dried red chillies', no:'tørkede røde chili'}, round:'half', note:{en:'Kashmiri, for colour', no:'kashmiri, for fargen'}},
    {q:20, u:'ml', n:{en:'oil', no:'olje'}},
    {q:10, u:'ml', n:{en:'lemon juice', no:'sitronsaft'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
   ]}],
  steps:[
    {en:'Cover the chillies for the chutney with warm water and leave them for 20 minutes.',
     no:'Dekk chilien til chutneyen med varmt vann og la den ligge i 20 minutter.'},
    {en:'Drain them and pound or blend them with the garlic, the lemon juice and salt to a coarse red paste, then stir the oil through it.',
     no:'Hell av vannet og støt eller kjør chilien sammen med hvitløken, sitronsaften og salt til en grov rød pasta, og rør så oljen inn i den.'},
    {en:'Bring the water for the dough to the boil, salt it, and pour it over the flour in a bowl. Stir with a spoon until you can put a hand in.',
     no:'Kok opp vannet til deigen, salt det, og hell det over melet i en bolle. Rør med en skje til du kan stikke hånden oppi.'},
    {en:'Knead the warm dough for a few minutes until it is smooth. It should be soft and a little tacky, and it will not stretch, which is normal.',
     no:'Elt den varme deigen i noen minutter til den er glatt. Den skal være myk og litt klebrig, og den strekker seg ikke, og det er som det skal.'},
    {en:'Divide it into balls and keep them under a damp cloth, because bajra dough dries out quickly.',
     no:'Del den i kuler og hold dem under et fuktig klede, for bajradeig tørker fort ut.'},
    {en:'Flatten a ball between wet palms, patting and turning it a quarter each time, into a disc about as thick as a little finger. A sheet of baking paper underneath helps if it keeps tearing.',
     no:'Klapp en kule flat mellom våte håndflater, og vri den en kvart omdreining for hver klapp, til den er en skive omtrent så tykk som en lillefinger. Et ark bakepapir under hjelper hvis den stadig revner.'},
    {en:'Heat a tava or a heavy frying pan over a medium flame with nothing in it.',
     no:'Varm en takke eller en tung stekepanne på middels varme, uten noe i.'},
    {en:'Cook the roti until the underside is speckled brown, turn it once, and cook the other side the same way.',
     no:'Stek rotien til undersiden er flekket og brun, snu den én gang, og stek den andre siden på samme vis.'},
    {en:'Lift it onto a live flame or a gas ring for a few seconds a side, until it puffs and blisters.',
     no:'Løft den over på en åpen flamme eller en gassbrenner i noen sekunder på hver side, til den blåser seg opp og får blemmer.'},
    {en:'Spread butter over it while it is hot, and eat it at once with the chutney. Make the next one while this one is being eaten.',
     no:'Legg smør på den mens den er varm, og spis den med en gang sammen med chutneyen. Lag den neste mens denne blir spist.'}],
  notes:[
    {title:{en:'Why the water must be boiling', no:'Hvorfor vannet må koke'},
     body:{en:'Millet has nothing to build a network with, so the dough holds together only because hot water swells some of the starch into a paste. Cold water gives you wet flour that crumbles the moment you lift it.',
           no:'Hirse har ingenting å bygge et nettverk av, så deigen henger bare sammen fordi varmt vann sveller noe av stivelsen til en masse. Kaldt vann gir deg vått mel som smuldrer i det øyeblikket du løfter det.'}},
    {title:{en:'Eat it now, not later', no:'Spis den nå, ikke senere'},
     body:{en:'A bajra roti is good for about ten minutes and then goes hard, which is why the cook stays at the fire and the family eats one at a time. There is no way to make a stack of them in advance.',
           no:'En bajra-roti er god i omtrent ti minutter og blir hard etterpå, og derfor står kokken ved ilden mens familien spiser ett brød om gangen. Det går ikke an å lage en stabel på forhånd.'}},
    {title:{en:'Sourcing it in Norway', no:'Slik får du tak i det i Norge'},
     body:{en:'Buy bajra flour from an Indian shop, where it is sold as bajri atta and is milled fine enough to work.',
           no:'Perlehirse selges i norske helsekostbutikker, men som regel som hele korn eller grovmalt, og grovt mel gir en deig som ikke lar seg klappe ut. Kjøp bajramel i en indisk butikk, der det heter bajri atta og er malt fint nok. Pass også på at det du kjøper faktisk er perlehirse: det som står merket bare «hirse» i helsekostbutikken, er ofte vanlig hirse, som er et annet korn og oppfører seg annerledes. Melet harskner fort, så kjøp små poser og oppbevar dem i fryseren.'}}],
  variations:[
    {title:{en:'With gur and ghee', no:'Med gur og ghee'},
     body:{en:'The winter breakfast. Skip the chutney, break the hot roti into a bowl, and work grated jaggery and a spoonful of ghee through it with your fingers.',
           no:'Vinterfrokosten. Sløyf chutneyen, brekk den varme rotien ned i en skål, og arbeid revet gur og en skje ghee inn i den med fingrene.'}},
    {title:{en:'Half and half', no:'Halvt om halvt'},
     body:{en:'If the dough defeats you, replace a quarter of the millet with wheat flour. It is not the real thing, but it rolls, and it is how many households outside the desert make it now.',
           no:'Hvis deigen vinner, kan du bytte ut en firedel av hirsen med hvetemel. Det er ikke den ekte varen, men den lar seg kjevle, og det er slik mange husholdninger utenfor ørkenen lager den i dag.'}}]
}

];
